### ISSUE TITLE
Italic placeholder on Android

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#10]
_From @BOBODDY on December 12, 2016 17:21_

I've been looking into applying italic effects to the hint text on Android. It seems the font used for the hint isn't exposed and is just set to whatever the regular text's font is. I found [this](http://stackoverflow.com/a/34808566) StackOverflow answer that finds the Layout using reflection and sets the hint font independently, but it's native and I'm not sure if it's something that can be converted to Xamarin.Android.

Thoughts?

_Copied from original issue: FormsCommunityToolkit/Effects#24_

**Comment by bartlannoeye** [comment]
_From @Depechie on December 12, 2016 17:33_

Not tried it myself, but pretty sure that if it is only doable low level, we would not get hold of it on effect level :/

**Comment by bartlannoeye** [comment]
_From @BOBODDY on December 13, 2016 14:17_

Looks like you can use reflection to get all the members of a class. I can do more testing later. If it does work, would you guys want it or is it too much of a hack?

**Comment by bartlannoeye** [comment]
_From @Depechie on December 13, 2016 14:27_

Good question, I would assume we would like effects to be equal on each platform ( if possible ), no matter how it is achieved - as long as it is in the boundaries of an effect.
But of course if this requires a lot of reflection, we need to validate the PR on performance I guess...

Anyhow, don't hold back, all PR's will be judged :)

**Comment by pauldipietro** [comment]
This seems like a rather specific user scenario and it appears to have no movement, so I'd not be inclined to add anything in like this.
