### ISSUE TITLE
[Proposal] Charts

### ISSUE THREAD

**Issue by listepo** [xamarin/XamarinCommunityToolkit#100]
I think there are not enough charts with styles for native platforms.

**Comment by pauldipietro** [comment]
I don't really understand what you mean. Can you please provide some examples?

**Comment by listepo-alterpost** [comment]
@pauldipietro I mean that each of the platforms the chat should look in its own style, for example Flat for IOS, Material for Android and Fluent Design for UWP

**Comment by listepo** [comment]
@pauldipietro I mean that each of the platforms the chat should look in its own style, for example Flat for IOS, Material for Android and Fluent Design for UWP

**Comment by pauldipietro** [comment]
I still don't understand. Are you requesting a chart control, or something else?

**Comment by pauldipietro** [comment]
This is better suited to other third party packages due to the number of uses cases that could exist in the scope of a chart.
