### ISSUE TITLE
[Enhancement] Implement more of EventArgsConverter

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1004]
## Summary
This proposal can be divided into two points:
- Implement the remaining most used types of events arguments converters to be used with `EventToCommandBehavior`.
- Merge those converters (plus existing `ItemTappedEventArgsConverter`, `ItemSelectedEventArgsConverter`) into one converter `EventArgsConverter`.

## API Changes
Initial proposal:
Initially I just gathered some events in the below list, **to be discussed** because some of the listed EventArgs could be not needed, in the case of an EventArgs where all properties are more or less equally important.

| Required| Event Args| Event Name|
|:---:|:---|:---|
| <ul><li>[ ] </li></ul> | `ItemsViewScrolledEventArgs` | `CarouselView.Scrolled` (base class `ItemsView`)|
| <ul><li>[ ] </li></ul> | `ScrolledEventArgs`  | `ListView.Scrolled`  (base class ListView) |
| <ul><li>[ ] </li></ul> | ~~`SelectionChangedEventArgs`~~ same as ItemSelectedEventArgsConverter | `CollectionView.SelectionChanged` (base class `SelectableItemsView`) |
| <ul><li>[ ] </li></ul> | `TextChangedEventArgs` | `Editor/Entry.TextChanged` (base class InputView) |
| <ul><li>[ ] </li></ul> | `DateChangedEventArgs` | `DatePicker.DateSelected` |
| ✔️  | `ToggledEventArgs` | `Switch.Toggled` |
| <ul><li>[ ] </li></ul> | `ValueChangedEventArgs` | `Stepper.ValueChanged` |
| <ul><li>[ ] </li></ul> | `CheckedChangedEventArgs` | `CheckBox.CheckedChanged` |

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
@pictos please assign me I have started working on this.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
