### ISSUE TITLE
[Enhancement] Let's Fix Snackbar 

### ISSUE THREAD

**Issue by dersia** [xamarin/XamarinCommunityToolkit#1006]
## Summary

First of all, I am not sure if this should be issued as a Bug or Feature Request, but I think since the original Spec of Snckbar designed it this way, it's not really a bug and since there is no better issue template like "Refine feature" or so, I'm going with the Feature Request issue Template.
I did use the search and couldn't find any issue on this Topic, so I started this one.

IMHO the Snackbar is broken, because it requires the page to be called and especially for MVVM flows this won't allow the user to Display a Snackbar or Toast. 
While thinking about it, I couldn't come up with a reason, why the page is needed for it. A Snackbar or Toast is going to always be displayed on the `CurrentPage`. I can't think of a reason why one would like to display a Snackbar on any other page than the current.
Sure, when we talk about Multi-Window Application, or even a `TwoPaneView`, but neither for a Multi-Windows Application nor for a `TwoPaneView`  a Page will be sufficient to decide where to display the Snackbar or Toast.

But may be I am totally wrong about this, in this case I am looking forward to have a nice discussion about this :)

## API Changes

Therefor I suggest to change the Snackbar to always display on the `CurrentPage` so it'll be accessible from everywhere and can be part of the Dependency-System or just as a static class. In the Renderer we should have access to the current page and this feature should be quite easy to implement.

## Intended Use Case
Display Snackbars and Toast from everywhere in your App

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
Hi @dersia thanks for the proposal, could you please read https://github.com/xamarin/XamarinCommunityToolkit/issues/504 and check whether it is the same as this or no ?

**Comment by dersia** [comment]
@Cfun1 thanks! Yeah, looks like a duplicate. Will close this one and put my thoughts into the other issue, becuase I think we should be discussing Multi-Window and `TwoPaneView` as part of this
