### ISSUE TITLE
[Enhancement] Add Scale support for SideMenuView

### ISSUE THREAD

**Issue by dersia** [xamarin/XamarinCommunityToolkit#1007]
## Summary

The `SideMenuView` is a nice View and I think we can make it a bit more Fancy by adding a scale animation to the main-view.
I'd like to get something like what @ahoefling shows in this BlogPost: https://www.andrewhoefling.com/Blog/Post/xamarin-forms-fancy-flyout-menu

![Fancy Flyout](https://www.andrewhoefling.com/Portals/2/adam/Image%20&%20Lightbox/ZwoCOjUggEeMV168OpX1zQ/Image/fancy-menu-android.gif)

## API Changes

There is already a `Shift` property on the `SideMenuView` which is used to translate the menu with an animation, so we would only need a `Scale` property which is also taken into account when executing the animation.
This should be a small change and shouldn't have any implications.

## Intended Use Case
More fancy `SideMenuView`

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
@dersia that's a great idea)
I thought about this enhancement. And definitely, we should implement it (it shouldn't be super difficult, I believe)

**Comment by dersia** [comment]
Ok, can I also then just throw this into the pool: honestly we need this for pages not just views. Having a fancy flyout that supports pages makes the app look so much better.
I know this is a different proposal, but I wasn't sure if that's something that within the responsibility of the toolkit, so far there are no pages, just views ;)

**Comment by ahoefling** [comment]
I am more than happy to contribute the fancy menu for this. Is the goal to implement this as an option on SideMenuView or make a new control for the toolkit?

**Comment by AndreiMisiukevich** [comment]
> Ok, can I also then just throw this into the pool: honestly we need this for pages not just views. Having a fancy flyout that supports pages makes the app look so much better.
> I know this is a different proposal, but I wasn't sure if that's something that within the responsibility of the toolkit, so far there are no pages, just views ;)

Hmm, what the difference?)

**Comment by AndreiMisiukevich** [comment]
> I am more than happy to contribute the fancy menu for this. Is the goal to implement this as an option on SideMenuView or make a new control for the toolkit?

I'll be happy to assign this enhancement to you :)
But I think that we should enhance the existing SideMenuView.

**Comment by ahoefling** [comment]
@AndreiMisiukevich go ahead and assign this to me. I'll look at how I can upgrade the current SideMenuView to include scaling.

I have a few things on my priority list so I may not start this for a few weeks or longer.

**Comment by dersia** [comment]
@ahoefling thanks!

@AndreiMisiukevich the difference is, that a Page can be a NavigationPage and I can have a better FlyoutPage (Master-Detail-Page) with all the nice features on the SideMenuView. Sure we could make MainView bindable and get a similar behavior, but a) it still does not support pages and b) you can't use navigation with it.
If it's a Page on the other hand, we could just easily use Navigation with it.

I hope this makes sense :)

**Comment by AndreiMisiukevich** [comment]
@dersia yep, it makes sense.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich go ahead and assign this to me. I'll look at how I can upgrade the current SideMenuView to include scaling.
> 
> I have a few things on my priority list so I may not start this for a few weeks or longer.

if you don't mind I will implement it then)

**Comment by AndreiMisiukevich** [comment]
Implementer in https://github.com/xamarin/XamarinCommunityToolkit/pull/1011
