### ISSUE TITLE
[Enhancement] TabView Icon center

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#1018]
If TabViewItem has no text, the icon is not centered vertically, how can I do it? I do not see anything in the documentation, I have achieved it with `pading="16"` and with the size of `TabStripHeight `to 60.

but in the case of sliding eyelashes the line also moves

**Comment by AswinPG** [comment]
I think you can use a custom control template with just an image to achieve that

**Comment by angelru** [comment]
Thank you very much, if that is the solution, you can close this issue without problem.

**Comment by angelru** [comment]
Muchas gracias a los 2 :+1:

**Comment by jfversluis** [comment]
Yep, this can be done, look at the samples. Thanks everyone for helping out here, great community effort! <3
