### ISSUE TITLE
[Enhancement] TabView TabStripBorderColor bottom

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#1019]
Currently with TabStripBorderColor the border is placed on top of the tabs, it would be nice if it could be chosen (top or bottom). I want to get this design:

![Instagram-search-bar-tags-587x1024](https://user-images.githubusercontent.com/11645585/109984510-23dd9f00-7d04-11eb-837d-908cc5909638.jpg)

you will see a border at the bottom and tabs with your TabIndicatorView overlaid.

**Comment by jfversluis** [comment]
Sorry, I'm not quite sure what you mean? You can already set the `TabIndicatorPlacement` is that not what you mean?

**Comment by SagarPanwala** [comment]
@jfversluis  

`<xct:TabView
        TabStripPlacement="Top"
        TabStripBackgroundColor="White"
        TabStripHeight="40"
        TabIndicatorPlacement="Bottom"
        TabStripBorderColor="Aqua"
        TabIndicatorColor="Purple">`

Above code produce below result, not the one @angelru  expects
![Simulator Screen Shot - iPhone 11 - 2021-06-14 at 11 19 59](https://user-images.githubusercontent.com/8872172/121845135-9ea25700-cd02-11eb-8c3c-02f411ea9404.png)

**Comment by justintemplar** [comment]
This would be a great addition for when designers want to separate the tabs at the top, to the content below.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
