### ISSUE TITLE
Setup/reevaluate build pipeline(s)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinCommunityToolkit#102]

**Comment by jfversluis** [comment]
We need to have a look at what is setup now and what we still use/need from that. I see there are some things in place, but seeing that we probably want to start from scratch that might not be relevant anymore.

Things from the top of my head that we need:
* CLA checking
* PR validation
* Running tests
* Publishing to nightly/private feed
* Publishing to NuGet

**Comment by jfversluis** [comment]
OK, most of this is in there. I need to have a call to see what is required to push a package to the actual NuGet.org feed in terms of signing and other things. Will do that this week. 

Nightly builds go into GitHub packages right now. I'm hoping Packages will allow connecting to the feed without authenticating anytime soon, else we'll have to look for a alternative maybe.

**Comment by jfversluis** [comment]
Changed nightly to Azure DevOps for now so they are publicly available. Last step to get this on nuget.org
