### ISSUE TITLE
[Bug] Can't set style for TabIndicatorColor

### ISSUE THREAD

**Issue by vipul386** [xamarin/XamarinCommunityToolkit#1024]
### Steps to Reproduce
Set the style given below in App.xaml
```
<Style TargetType="xct:TabView">
        <Setter Property="TabIndicatorColor"
                    Value="{StaticResource Primary}"/>
</Style>
```

### Expected Behavior
It was supposed to change tab indicator color.

### Actual Behavior
returns error System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Basic Information

- Version with issue: 1.0.3
- Last known good version: Dont know
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: Android SDK platform 30
- Nuget Packages: All default packages with xamarin community toolkit

**Comment by AndreiMisiukevich** [comment]
@vipul386 hi) did you solve this issue? Or why you decided to close this one) Thanks

**Comment by vipul386** [comment]
> @vipul386 hi) did you solve this issue? Or why you decided to close this one) Thanks

I closed this issue because I decided to stop using xamarin.
