### ISSUE TITLE
LazyView

### ISSUE THREAD

**Issue by Senso4sLab** [xamarin/XamarinCommunityToolkit#1029]
I tried to use ControlTemplate inside LazyView control. Unfortunately, it does not work.  Can someone explain what I have to change in class BaseLazyView. 

Thanks in advance

**Comment by pictos** [comment]
@Senso4sLab you can't use ControlTemplate with LazyView, you need to pass the view's type. You can take a look at our sample to have a better idea of how to use it.

https://github.com/xamarin/XamarinCommunityToolkit/blob/develop/samples/XCT.Sample/Pages/Views/TabView/LazyTabPage.xaml
