### ISSUE TITLE
[Enhancement] Expand MaskedBehavior to include MaskMoney.

### ISSUE THREAD

**Issue by paradisehuman** [xamarin/XamarinCommunityToolkit#1044]
## Summary

Hello. The masks provided by MaskBehavior are for stable patterns only. If we want to use a complicated pattern such as decimal currency format, nothing can be done. I suggest you check out the javascript example. It works exactly as we need it.

[javascript example](https://jsfiddle.net/msilvalopes/n0sz74qu/)
 

## Intended Use Case
MaskMoney masks input text as money.
## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
