### ISSUE TITLE
[Bug] AvatarView Image Uri

### ISSUE THREAD

**Issue by teymur371** [xamarin/XamarinCommunityToolkit#1046]
### Steps to Reproduce

1. AvatarView with the source from Uri
2. On first navigation to the page with AvatarView, everything is fine
3. On the second navigation, application throws an exception

### Expected Behavior
Display image properly

### Actual Behavior
Applciation throws "cannot access a closed Stream"

### Basic Information
Xamarin.Forms v5.0.0.2012
Xamarin.CommunityToolkit v1.0.3

### Workaround
To use Circle Image or regular Image control

**Comment by AndreiMisiukevich** [comment]
Hi @teymur371, could you please specify the platform?

**Comment by AndreiMisiukevich** [comment]
Also, could you please check if the issue exists on v1.0.2
And would be great if you could add a reproductions sample.

Thanks)

**Comment by teymur371** [comment]
Hi @AndreiMisiukevich , the platform is Android.
Checked with v1.0.2 , no issues there :)
And here is the sample for v1.0.3: https://github.com/teymur371/AvatarViewDemo
Steps to reproduce:
Navigate to ImagePage, then navigate to About, and then back to ImagePage )

**Comment by AndreiMisiukevich** [comment]
> Hi @AndreiMisiukevich , the platform is Android.
> Checked with v1.0.2 , no issues there :)
> And here is the sample for v1.0.3: https://github.com/teymur371/AvatarViewDemo
> Steps to reproduce:
> Navigate to ImagePage, then navigate to About, and then back to ImagePage )

awesome, thank you)

**Comment by AndreiMisiukevich** [comment]
You can verify the fix here https://github.com/xamarin/XamarinCommunityToolkit/pull/1052

**Comment by AndreiMisiukevich** [comment]
Fixed in #1052 will be available in the next major release (v1.1)

**Comment by teymur371** [comment]
Great, Thank you!
