### ISSUE TITLE
[Bug] CameraView does not take photos for iOS

### ISSUE THREAD

**Issue by janispa** [xamarin/XamarinCommunityToolkit#1059]
### Description
`CameraView` does not take photo under iOS. Android is not affected. 

### Steps to Reproduce

1. Put `CameraView` on a page
2. Trigger `ShutterCommand`

### Expected Behavior
1. `MediaCaptured` event __is__ triggered

### Actual Behavior
1. `MediaCaptured` event __is not__ triggered

### Basic Information

https://github.com/xamarin/XamarinCommunityToolkit/blob/caa3ebc71335d68e4a69758def542b322ccdbf90/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs#L189-L199

The check `photoOutput != null` prevents the further code from processing the photo.

- Version with issue: 1.0.3 and greater
- Last known good version: 1.02
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  14.4

**Comment by killer-frog** [comment]
I can confirm that this is an issue and downgraded to v1.0.2 is a workaround.  It is an issue in v1.1.0-pre2 too.

**Comment by GUOLDEV** [comment]
Hi @jfversluis, nice work fixing the issue, any idea when 1.1.1 is going to be released?
