### ISSUE TITLE
Solution can't be compile by VS Mac

### ISSUE THREAD

**Issue by flyingxu** [xamarin/XamarinCommunityToolkit#106]
## Bug 

The solution seems to be using some new project/build file format, which makes them compiling failed when compiled with VS Mac.

I'd like to know what's the suggested dev environment for this project. VS 2017 on Windows and connect to a Mac remotely?

### Expected Behavior

Projects in Toolkit.sln compiles OK with VS Mac

### Actual Behavior

When compiled for the project of _Effects_, there are 2 errors:
>Target ResolvePackageAssets:
    XamarinCommunityToolkit/Toolkit/Effects/Effects.csproj : error NU1202: Package Microsoft.NETCore.UniversalWindowsPlatform 6.1.5 is not compatible with netstandard1.0 (.NETStandard,Version=v1.0). Package Microsoft.NETCore.UniversalWindowsPlatform 6.1.5 supports:
    XamarinCommunityToolkit/Toolkit/Effects/Effects.csproj : error NU1202:   - netcore50 (.NETCore,Version=v5.0)
    XamarinCommunityToolkit/Toolkit/Effects/Effects.csproj : error NU1202:   - uap10.0.15138 (UAP,Version=v10.0.15138)
    XamarinCommunityToolkit/Toolkit/Effects/Effects.csproj : error NU1202: Package Win2D.uwp 1.21.0 is not compatible with netstandard1.0 (.NETStandard,Version=v1.0). Package Win2D.uwp 1.21.0 supports: uap10.0 (UAP,Version=v10.0)
Done building target "ResolvePackageAssets" in project "Effects.csproj" -- FAILED.

### Steps to reproduce the Behavior

1. Open Toolkit.sln with VS Mac
2. Set current project to Samples.iOS / Debug iPhoneSimulator
3. Compile Samples.iOS

**Comment by jfversluis** [comment]
Rebooting this repo and there will probably be a completely new solution/project and this won't be relevant for that anymore. As such, closing this one.
