### ISSUE TITLE
TouchEffect iOS command fires when scrolling

### ISSUE THREAD

**Issue by woutervanoorschot** [xamarin/XamarinCommunityToolkit#1070]
### Description

The TouchEffect command fires when a user scrolls or flicks a scrollable view, starting the gesture on an item with a command. This results in the command firing (navigation in my case), while also scrolling the list. This only happens on iOS. The effect used is the native effect.

### Steps to Reproduce

1. Create listview/scrollview/collectionview with TouchEffect on the itemtemplate
2.  Deploy on iOS
3. Scroll over the list to scroll, starting on an item
4. The TouchEffect.Command will fire

### Expected Behavior

The user can scroll without the command being fired (the scrolling gesture/motion should not fire 'tap' events)

### Actual Behavior

The command is fired when the user intents to scroll

- Version with issue: 1.1.0-pre2
- Last known good version: -
- IDE: Visual studio 2019 (windows)
- Platform Target Frameworks: 
  - iOS: 14.4
  - Android: 11.0
- Affected Devices: iPhone 12 (and others presumably)

**Comment by AndreiMisiukevich** [comment]
If anybody knows how to fix it, feel free to leave a comment and submit a PR 👍

**Comment by IeuanWalker** [comment]
@AndreiMisiukevich a few years back when I was building a button control for an internal project I ran into this issue. This is the Commit that fixed it, can't remember much about it sorry - https://github.com/IeuanWalker/Xamarin.Forms.FlexButton/commit/b2088dfe86e75da58ee09ad0288cd1df5c93fa89

**Comment by AndreiMisiukevich** [comment]
@woutervanoorschot can you try to set DisallowTouchThreshold="1" and see if the issue still exists

**Comment by woutervanoorschot** [comment]
Hello,

DisallowTouchThreshold=1 fixes the problem! I am trying to understand the implmentation code, but do not fully understand what it does yet. For now my problem is solved though, maybe '1' should be the default? But I don't know if that hinders usage elsewhere.

Thanks!

**Comment by AndreiMisiukevich** [comment]
@woutervanoorschot thanks for the feedback :) no problem I will explain what is it.

DisallowTouchThreshold manages how many points you may drag your finger overview before the touch will be canceled.

Usually, you can press the view and move your finger (view will be preserved as "pressed"), but when you set DisallowTouchThreshold=1 it means that the touch will be canceled as soon as you try to move your finger over "pressed" view.
