### ISSUE TITLE
[Bug] adding x:name="[some name here]" - TabView cause error CS0103 on CS xaml

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/XamarinCommunityToolkit#1079]
### Description
adding x:name="{some name here}" or element  <xct:TabView on TABVIEW can cause error CS0103 and InitializeComponent() doesn't exist in the current context.
i.e:  <xct:TabView
                x:Name="cfView"
cfView got an error CS0103 as well and all x;Name on stacklayout,grid etc got an error CS0103 

I was trying to
1. Close VS 2019 Community
2. delete BIN and OBJ folder on the ios and android project               
3. Reopen VS 2019
4. Rebuild the app

but no luck still got this error CS0103, but when I removed the file XAML that's include tab view or set project startup to ANDROID the error CS0103 is disappeared 
### Steps to Reproduce

1. Set Project start-up to IOS
2. add x:Name or element tabview at XAML file and save.
2. goto XAML CS file 

### Expected Behavior
should be normal without any error CS0103 on CS XAML and impacted to other components on InitializeComponent()
### Basic Information

- Version with issue: 1.0.3, 1.1.0 pre 1, 1.1.0 pre 2, 1.1.0
- Last known good version:
- IDE: Mac - VS 2019 community
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 9
 
- Android Support Library Version: 
- Nuget Packages: Xamarin Community Toolkit 1.1.0
- Affected Devices: iOS

### Reproduction imagery

![image](https://user-images.githubusercontent.com/3633650/111418977-964a7800-8723-11eb-897c-ad0e942be379.png)
![image](https://user-images.githubusercontent.com/3633650/111419126-d90c5000-8723-11eb-856e-d3f6e57333bc.png)

**Comment by pictos** [comment]
@sunkerGit could you attach a repro?

**Comment by sunkerGit** [comment]
> @sunkerGit could you attach a repro?

please on the attached fies above

**Comment by sunkerGit** [comment]
When I remove the XAML files that included <xct:TabView, all XAML cs was working normal, no error and red highlighted for iOS, see file: HospitalPage.xaml.cs
<img width="1440" alt="Screen Shot 2021-03-17 at 16 36 04" src="https://user-images.githubusercontent.com/3633650/111439343-3ca47680-8740-11eb-998f-12bc630c35e0.png">
<img width="1440" alt="Screen Shot 2021-03-17 at 16 32 29" src="https://user-images.githubusercontent.com/3633650/111439386-4928cf00-8740-11eb-9bfb-a17cce0b9ecd.png">

**Comment by pictos** [comment]
@sunkerGit thanks for the screenshots, that helps but I insist on you sending a small repro. Let me explain why. Most of the contributors here are community members, which means that we triage issues, review code, test code, fix bugs in our spare time. So it's a lot of stuff to do, and try to create a repro demands time as well, so if the person that opens the issue can attach a bug that makes our life easier :D

**Comment by sunkerGit** [comment]
> @sunkerGit thanks for the screenshots, that helps but I insist on you sending a small repro. Let me explain why. Most of the contributors here are community members, which means that we triage issues, review code, test code, fix bugs in our spare time. So it's a lot of stuff to do, and try to create a repro demands time as well, so if the person that opens the issue can attach a bug that makes our life easier :D

Thanks for the feedback!.
Please see the attached file repo and also screenshot below
<img width="1440" alt="Screen Shot 2021-03-18 at 08 11 17" src="https://user-images.githubusercontent.com/3633650/111554834-132c2f00-87c2-11eb-8d04-9e41c635d58f.png">
[TabViewBugs.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6160457/TabViewBugs.zip)

**Comment by pictos** [comment]
@sunkerGit thank you for it, I'll take a look asap

**Comment by pictos** [comment]
@sunkerGit, thanks for sharing the repro. I can't reproduce the issue on my end. I'm using Windows. Also, I noticed that in your sample you use a `shared project` structure, that's deprecated, trying to that project into a netStandard lib.

**Comment by pictos** [comment]
> Hi @pictos,
> 
> Thanks for the feedback, I'm using Mac with VS 2019 Community. when I created the solution is from the multiplatform app (basic structure like as attached repro previously). I didn't use any layer using.Shared / netStandard lib.
> 
> Those structures has been generated by VS 2019 when i choose Multiplatform App - Blank Form App
> 
> ![image](https://user-images.githubusercontent.com/3633650/113985102-60aa3200-987e-11eb-9ef7-2e0bd531c385.png)

on your print, you're using the netStandard style

**Comment by sunkerGit** [comment]
In my perception, VS 2019 created 4 basic structures from Xamarin Forms project:
1. Shared project (this is the presentation layer for Droid and iOS)
2. Android project
3. iOS project
4. UITest

sorry i don't get it what do you mean about netStandard style / lib for Xamarin Forms App. in my assumption are you refer to Library project?

![image](https://user-images.githubusercontent.com/3633650/114180416-bf50d800-9972-11eb-888f-e575ddc055b4.png)


I just have a question here, why are the VS 2019 for Windows & Mac make a different behavior? when on IDE editor, one available on the Android but not on the iOS

**Comment by pictos** [comment]
@sunkerGit I'm saying that in the repro that you sent, your shared code is a shared project structure. As you can see in the screenshot below
![image](https://user-images.githubusercontent.com/20712372/114222684-3ff8df80-9945-11eb-9f5f-1102797a891a.png)

the extension is `shproj` and not `csproj`. So my guess is that is the cause of the issue, that you can't use the `x:Name` notation. I couldn't reproduce it on my end using a netStandard project as my shared lib.

**Comment by Kapusch** [comment]
Hi @pictos , I actually also encounter this problem almost all the time (also in VS For Mac), and I don't have any share projects.

Though it would be great if you know how to investigate about this error, I'm not sure this is tightly related to the XCT.

As you can see [here](https://forums.xamarin.com/discussion/25409/problem-with-xaml-x-name-and-access-from-code-behind), this error has been occurring from many years 😕

**Comment by pictos** [comment]
@Kapusch try to clean bin/obj folders and rebuild your solution. Let me know if that fixes

**Comment by sunkerGit** [comment]
Hi @pictos & @Kapusch, from my issues above when I was trying to clean the bin/obj folder, reopen VS, Rebuild All my solution, the problem still exist! but when I take out the XCT, the problem disappears.

**Comment by pictos** [comment]
@sunkerGit If you remove the XCT you shouldn't be able to compile, because the Tabview control will not exist.

**Comment by sunkerGit** [comment]
> @sunkerGit If you remove the XCT you shouldn't be able to compile, because the Tabview control will not exist.

XCT here, I mean <xct:tabview /> at XAML file, not the nuget package.

**Comment by pictos** [comment]
@sunkerGit the project that you're seeing this issue is/can be open source?

**Comment by sunkerGit** [comment]
> @sunkerGit the project that you're seeing this issue is/can be open source?

I'm using VS 2019 Community for creating this project

Visual Studio Community 2019 for Mac
Version 8.9.5 (build 4)
Installation UUID: dcd706f9-57a0-4c9f-8ba5-b32003030237
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

Mono Framework MDK
Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

**Comment by Kapusch** [comment]
Maybe related to #871 ?

**Comment by sunkerGit** [comment]
@Kapusch when i'm adding [assembly: PreserveToolkit] based on #871 compile error and saying "Duplicate".

NB: There were no compile error when adding xct elements into XAML file but we got error on editor for iOS platform CS0103

**Comment by Kapusch** [comment]
It's been an entire day (fingers crossed) where I can see no more CS0103 error, what has changed since then is the two following actions :
- Updating VS for Mac to 8.9.6 (build 6)
- Removing all temp files and folders (bin, obj, packages with `git clean -fxd` (you will need to restore packages)
- Debugging on Android physical device instead of iOS Simulator (I put it here just in case)

Could you please give a try @sunkerGit ?

**Comment by pictos** [comment]
@jfversluis @AndreiMisiukevich can some of you test it on MAC? I couldn't reproduce it on Windows

**Comment by AndreiMisiukevich** [comment]
> @jfversluis @AndreiMisiukevich can some of you test it on MAC? I couldn't reproduce it on Windows

project builds successfully for me

**Comment by AndreiMisiukevich** [comment]
> > @jfversluis @AndreiMisiukevich can some of you test it on MAC? I couldn't reproduce it on Windows
> 
> project builds successfully for me

I see this, but when I build project it builds w/out errors
![image](https://user-images.githubusercontent.com/10124814/115131867-95935300-9ffb-11eb-8be9-1c6417b8574f.png)

**Comment by AndreiMisiukevich** [comment]
Please follow https://github.com/xamarin/XamarinCommunityToolkit/issues/1079#issuecomment-821801654 comment and let  us know if it doesn't help

**Comment by sunkerGit** [comment]
Hi Guys,

Thanks for the feedback.
it seems the problem still exist when I was followed instructions from @Kapusch. 
Compile / Build no error (for ios or android) but when editing code behind from the XAML file on **iOS as start-up** project I got this error (CS0103), and this is very annoying. It does not happen when I set the startup project to **Android**, no any CS0103 appears when I edit code behind from the XAML file.

please see the file attached below
<img width="1440" alt="Screen Shot 2021-04-18 at 18 24 11" src="https://user-images.githubusercontent.com/3633650/115143566-b51d9080-a07a-11eb-8556-9a68ece24ba0.png">

**Comment by sunkerGit** [comment]
> It's been an entire day (fingers crossed) where I can see no more CS0103 error, what has changed since then is the two following actions :
> 
> * Updating VS for Mac to 8.9.6 (build 6)
> * Removing all temp files and folders (bin, obj, packages with `git clean -fxd` (you will need to restore packages)
> * Debugging on Android physical device instead of iOS Simulator (I put it here just in case)
> 
> Could you please give a try @sunkerGit ?

please see my comment above
