### ISSUE TITLE
How to use Xamarin.Toolkit.Effects.dll

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/XamarinCommunityToolkit#108]
I have installed Xamarin.Toolkit.Effects.dll packages from NuGet Package manager in my Xamarin.Forms project.
Now how can I use this .dll file to switch button. I am trying this in my SwitchPage.xaml.cs

```
   async void OnChangeColorButtonClicked(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new EffectsSwitchChangeColorPage());
        }
```

The xaml is 

```
    <Grid HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>

            <Button Text="Change color effect"
                Clicked="OnChangeColorButtonClicked"
                Grid.Row="0" />
        </Grid>
```
The error is 

> Type of namespce name EffectsSwitchChangeColorPage could not be found

How can I use that .dll by imprting relevant usings

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Expected Behavior

I should be able to use.

### Actual Behavior

Unable to use
### Steps to reproduce the Behavior

![switch](https://user-images.githubusercontent.com/19743421/47907907-2f112d80-deb2-11e8-985c-84cd396f162c.png)

## Feature Request:
Please fill in what you would like

**Comment by Depechie** [comment]
The actual usage for the Switch control can be found here : https://github.com/xamarin/XamarinCommunityToolkit/blob/master/Samples/Samples/Views/EffectsSwitchChangeColorPage.xaml

In the sample app we use 1 page per effect to show off the result. The EffectSwitchChangeColorPage is a page only available in the samples app.

So the code to use the effect

```
        <Switch effects:SwitchChangeColor.FalseColor="#AAEE00"
                effects:SwitchChangeColor.TrueColor="Blue"
                Grid.Row="1" />
```

**Comment by arvindrajachourasiya** [comment]
@Depechie - Thank you for your instant help. It was here too https://github.com/xamarin/XamarinCommunityToolkit/issues/35.

one quick question, why these buttons are showing left in iOS right in Android, can't I change those directions.

**Comment by Depechie** [comment]
Hmm we don't do anything fancy with the control other than changing how the colors are used.
So all other visible elements are by design of the native control, in other words for your question there is nothing in the effect library and not sure myself how to do this either. So I guess you'll need to look for this online, see if someone already tackled what you are trying to achieve...

**Comment by arvindrajachourasiya** [comment]
@Depechie - Thank you. Last quick quick question, In iOS unselected area is highlighted with the given color but in android only Round of button is highlighted, Can we make them look alike. Please look at below screenshot.

![ios](https://user-images.githubusercontent.com/19743421/47911707-30dfee80-debc-11e8-92aa-47e3f12a5dbe.png)


![androidswitch](https://user-images.githubusercontent.com/19743421/47911734-3e957400-debc-11e8-8a1d-155a50ea4ec7.png)

**Comment by bartlannoeye** [comment]
These kind of questions should be asked on Stackoverflow. Please only use issues for real bugs and feature requests, thank you.

**Comment by Depechie** [comment]
@arvindrajachourasiya not with the current effect, no... I do think it is possible, but you'll need to digg through the different properties on Android to verify.
