### ISSUE TITLE
[Bug] BadgeView.BackgroundColor is not changed

### ISSUE THREAD

**Issue by shyunMin** [xamarin/XamarinCommunityToolkit#1080]
### Description

BadgeView.BackgroundColor is not changed after app is launched.

### Steps to Reproduce

1. Launch app which contains BadgeView
2. Change the BackgroundColor of the BadgeView

### Expected Behavior
The background color of the BadgeView is changed to the color I set.

### Actual Behavior
There was no changes on the app when I changed the BackgroundColor.
However that was applied when I changed TextColor.
![xct_badge](https://user-images.githubusercontent.com/20968023/111125759-4f3e7480-85b5-11eb-8abf-f1b834f53dae.gif)

### Basic Information

- Version with issue: https://github.com/xamarin/XamarinCommunityToolkit/commit/caa3ebc71335d68e4a69758def542b322ccdbf90
- Platform Target Frameworks: Tested on Android 10.0 emulator

**Comment by AndreiMisiukevich** [comment]
Fixed in #1081
