### ISSUE TITLE
Bug on LabelSizeFontToFit for Master Detail 

### ISSUE THREAD

**Issue by qmoabella08** [xamarin/XamarinCommunityToolkit#109]
## Bug 

Version Number of Plugin: 1.0.0

Device Tested On: Nexus 5 emulator on VS for mac

### Expected Behavior
The label retains the LabelSizeToFit effect
### Actual Behavior
The app crashes and have "cannot access disposed object" error
### Steps to reproduce the Behavior
On a master-detail page, navigate on the page that contains a label with LabelSizeFontToFit effect, go to another page then go back to the first page.

**Comment by Dageezah** [comment]
Has this ever been fixed?

**Comment by Depechie** [comment]
@Dageezah don't think so yet, sorry about that though...

**Comment by jfversluis** [comment]
I think there is a PR for this to be pulled into Forms by default, so this bug will hopefully become irrelevant soon
