### ISSUE TITLE
[Enhancement] Context menu

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/XamarinCommunityToolkit#1098]
## Summary
can we expect a simplified (using it in xaml) of [this](https://github.com/SKLn-Rad/Xam.Plugin.PopupMenu) POPUP MENU?
 i saw it in many native apps and it's a very handy feature!!!

## API Changes
I found a repo that did this but it's old and buggy!

https://github.com/SKLn-Rad/Xam.Plugin.PopupMenu

## Example Screenshot
i used it a year ago when I started using Xamarin.forms in my playground app and it works fine but not customizable (like background and text color or icon for items , etc) and haven't sub menus(I don't know iOS has it but android and UWP does 👀)! plus unfortunately NOT works in UWP Release mode. 

![Screenshot (479)_LI](https://user-images.githubusercontent.com/42671084/79636536-a5304f80-818d-11ea-9d37-ad83d5cbed20.jpg)

## Platforms 
Core/XAML 
iOS
Android
UWP

**Comment by pictos** [comment]
@mhrastegary77 please see the pop-up view control. We have the anchor feature that I believe do what you want.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
