### ISSUE TITLE
Feature Request: Autocompletition Effect

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#11]
_From @Emasoft on December 16, 2016 22:20_

An Autocompletition Effect like this one from Whatsapp would be very useful.

![whatsapp-broadcast-282x500](https://cloud.githubusercontent.com/assets/713559/21280382/eeeb5674-c3e5-11e6-86b5-55cae913fd42.png)
![whatsapp-broadcast-img-preview](https://cloud.githubusercontent.com/assets/713559/21280475/784bde7a-c3e6-11e6-91a4-d06eae940efa.jpg)

It should be able to:
- Pull up the textfield to the top of the view (even if the textfield is at the bottom of the page)
- Display a floating menu area of variable height just below the textfield and above the keyboard
- Drop a shadow below the menu
- Populate the menu with a list of elements from an item source List, and using a XAML custom cellview template, or directly from a remote (i.e. Google) data provider
- Display only the elements containing (anywhere, not only at the beginning) the keyword or the letters typed, and filtering the list as we type
- Le the user scroll the list with a drag gesture if the list is bigger than the space between the textfield and the keyboard. A small vertical scroll bar at the right should appear while we scroll as an hint of the remaining space to scroll to reach the bottom.
- Highlight the letters that we've typed in the text of all results in bold and with a customizable color
- Tapping an item should copy the tapped item content in the textfield and close the menu.
- The autocompletition menu should preserve the state when the device is rotated in landscape

_Copied from original issue: FormsCommunityToolkit/Effects#28_

**Comment by bartlannoeye** [comment]
_From @acaliaro on December 16, 2016 22:56_

I think this request is too complex to be an effect

**Comment by adamhill** [comment]
This is a probably better as a Control. I have implemented something like this in Forms with a Entry and a Listview.

**Comment by pauldipietro** [comment]
We currently have an [enhancement issue](https://github.com/xamarin/Xamarin.Forms/issues/1775) open for this sort of control, so I'm going to close this for the time being. If that proposal doesn't end up getting traction on the Core end, it might be worth revisiting this with a new issue and fuller description of the API.
