### ISSUE TITLE
[Enhancement] Simple implementation of NotifyPropertyChanged

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/XamarinCommunityToolkit#1100]
## Summary

I'm just wondering why we've to implement NotifyPropertyChanged ourselves?

## API Changes

```
public class NotifyPropertyChanged : INotifyPropertyChanged
{
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        ///     Triggers UI to update.
        /// </summary>
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        /// <summary>
        ///     Sets the properties new value and invokes PropertyChanged.
        /// </summary>
        /// <returns>Returns true if successful</returns>
        protected bool SetProperty<T>(ref T property, T newValue, [CallerMemberName] string propertyName = null)
        {
            if (Equals(property, newValue))
            {
                return false;
            }

            property = newValue;
            OnPropertyChanged(propertyName);

            return true;
        }
}
```

## Intended Use Case
Properties of any ViewModel.

## Who Will Do The Work?

- [X] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
@MaxFmi have you take a look at [ObservableObject](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/ObservableObject.shared.cs) ?

**Comment by AndreiMisiukevich** [comment]
Hey @MaxFmi thanks for the interest in this project)
As @Cfun1 mentioned, give a chance to ObservableObject that is pretty similar to what you posted and let us know about your experience. Feel free to reopen this issue if you have any concerns

**Comment by MaxFmi** [comment]
ObservableObject looks good. Thanks :-)
