### ISSUE TITLE
[Enhancement] Simple thread safe ObservableRangeCollection

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/XamarinCommunityToolkit#1101]
## Summary

We have a contract for ListViewItems. This contract gets implemented from multiple modules. To avoid thread issues we're using our own thread safe implementation of ObservableRangeCollection. Would be great to have a thread safe variant in the XCT.

## API Changes
```
public class ThreadSafeObservableRangeCollection<T> : ObservableRangeCollection<T>
{
       // Handle operations like adding, removing and so on inside a lock statement. 
}
```
## Intended Use Case
Everywhere where adding and removing can be triggered from multiple areas at the same time. 

## Who Will Do The Work?

- [X] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by maxkoshevoi** [comment]
IMHO: Better name would be `ConcurrentObservableRangeCollection` to be more inline with other thread safe collections already present in .Net

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
