### ISSUE TITLE
[Bug] Save area does not update on orientation and status bar changes

### ISSUE THREAD

**Issue by geskill** [xamarin/XamarinCommunityToolkit#1105]
### Steps to Reproduce

1. Open sample app with safe area effect demo
2. Rotate phone while effect is enabled

### Expected Behavior

![Simulator Screen Shot - iPhone 12 - 2021-03-22 at 13 53 39](https://user-images.githubusercontent.com/6826752/111993315-c3799a80-8b16-11eb-9549-fb2e1ec31a9d.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-22 at 13 54 18](https://user-images.githubusercontent.com/6826752/111993321-c70d2180-8b16-11eb-9656-49a6241702ac.png)

### Actual Behavior

![Simulator Screen Shot - iPhone 12 - 2021-03-22 at 13 54 35](https://user-images.githubusercontent.com/6826752/111993347-cffdf300-8b16-11eb-87dd-806b13e4e931.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-22 at 13 53 55](https://user-images.githubusercontent.com/6826752/111993362-d42a1080-8b16-11eb-8d73-1858c0ad0039.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Disable -> Enable effect after rotation.

**Comment by AndreiMisiukevich** [comment]
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1092
