### ISSUE TITLE
[Bug] StateLayout never go back to normal state

### ISSUE THREAD

**Issue by PaulP92** [xamarin/XamarinCommunityToolkit#1112]
StateLayoutController does not store the original content, because previousState is now nullable:

https://github.com/xamarin/XamarinCommunityToolkit/blob/aba6205274a7fb8c8a55eaedb8001e3a693ed5f1/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayoutController.shared.cs#L14

When switching to a template the if statement is wrong:
https://github.com/xamarin/XamarinCommunityToolkit/blob/aba6205274a7fb8c8a55eaedb8001e3a693ed5f1/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayoutController.shared.cs#L58-L65

Either change previousState back to non-nullable or add null-check to the if statement.

You can test it in the Sample App. Just click the "Show Fullscreen Loader", when going back to normal state the screen is blank.

**Comment by JoacimWall** [comment]
I have this issue also.

**Comment by jpmirfcb** [comment]
Me too...

**Comment by Cfun1** [comment]
I believe it is cleaner to initialize the previousState field with LayoutState.None value instead of doing a null check.

**Comment by rubiktubik** [comment]
Is there a workaround to prevent a blank screen?

**Comment by PaulP92** [comment]
Maybe if you use another LayoutState for your normal State, like LayoutState.Success.

**Comment by AndreiMisiukevich** [comment]
> Is there a workaround to prevent a blank screen? Without reverting to 1.0.3 ?

only by using reflection that is not good.
I merged a fix, it will be available in the next release
