### ISSUE TITLE
[Bug] Documentation for Delegate Weak Event Manager seems wrong.

### ISSUE THREAD

**Issue by cabal95** [xamarin/XamarinCommunityToolkit#1116]
### Description

The documentation markdown file for the Helpers directory seems to have incorrect information regarding DelegateWeakEventManager. More specifically, it seems like the exact same code as the section above. I think this section is supposed to use `DelegateWeakEventManager` instead of just `WeakEventManager`.

https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers#using-delegate

Unless I'm completely using something wrong, but in order to use this with my INotifyPropertyChanged implementation I had to use the `DelegateWeakEventManager`.

### Steps to Reproduce

1. Click link above
2. Copy and paste sample code into your project.
3. Try to compile.
4. Scratch head. 

### Expected Behavior

Documentation should be accurate :)

### Actual Behavior

Documentation section is for `Delegate` usage but still instantiates the normal event manager.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
@cabal95 I'll keep it here for now, but to make sure the right people look at it, please open Docs related issue on the repo you've linked :)

Thanks!

**Comment by brminnick** [comment]
Ah, yes this was done before [the official documentation website](https://docs.microsoft.com/xamarin/community-toolkit/?WT.mc_id=mobile-0000-bramin) was created.

I'll remove the markdown from the repo 👍

**Comment by brminnick** [comment]
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/commit/0ffd51a099e7472ff6101119e1c0a734687dc394
