### ISSUE TITLE
[Enhancement] Allow TabItem's text to not always be uppercase on Android

### ISSUE THREAD

**Issue by TravyDale** [xamarin/XamarinCommunityToolkit#1118]
## Summary

Currently, TabItem's on Android default to the Material Design template. That template will always use uppercase to follow Android's Material Design. To be flexible, it would be nice for developers to be able to override this and choose how the text would be displayed.

## API Changes

To solve this change, a new binding of type 'TextCaseType' would be added to the TabViewItem class. It would default to Upper to keep the existing logic the same, but allow users to override the value to get their desired effect. This binding would then be used within the MaterialTabViewItemTemplate class to set the Text property's case.

This could also be leveraged for the other templates (iOS, UWP) that are already built, but that may be out of scope for this request.

```
public static readonly BindableProperty TextCaseProperty =
		   BindableProperty.Create(nameof(TextCase), typeof(TextCaseType), typeof(TabViewItem), TextCaseType.Upper);

public TextCaseType TextCase
{
	get => (TextCaseType)GetValue(TextCaseProperty);
	set => SetValue(TextCaseProperty, value);
}

```

## Intended Use Case
TabItem's using the default Android control template (MaterialTabViewItemTemplate)

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Thank you for your suggestion @TravyDale however, you are already able to do this.

The default template indeed mimics how Android does things, including the uppercasing, but you can override the whole template and implement something custom. 

You can see that here for example: https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Views/TabView/CustomTabsPage.xaml#L12-L35

Does that fit your needs?

**Comment by TravyDale** [comment]
Yes it does. I was just trying to avoid doing a custom template. This works just fine though. Thanks for the reply!

**Comment by Kapusch** [comment]
Just in case it helps somebody, I'd like to give an example about what I have implemented to avoid uppercase on Android :

```
<ControlTemplate x:Key="ProductDetailsTabItemTemplate">
        <Label
            x:Name="ProductDetailsTabTitle"
            FontFamily="{TemplateBinding CurrentFontFamily}"
            HeightRequest="{OnPlatform Android='36',
                                       iOS='40'}"
            HorizontalTextAlignment="Center"
            Text="{TemplateBinding Text,
                                   Converter={StaticResource StringCaseConverter},
                                   ConverterParameter=TitleCase}"
            TextColor="{TemplateBinding CurrentTextColor}"
            VerticalTextAlignment="Center" />
        </ControlTemplate>
```

@jfversluis , you may have noticed that I'm not using the [XCT TextCaseConverter](https://github.com/xamarin/XamarinCommunityToolkit/blob/c138f205148f544f398703e943222d0930f73125/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs) 😄 
I actually wanted to do a PR to add the "TitleCase" TextCaseType enum, but I failed in running the unit tests in VS for Mac 😕

**Comment by jpozo20** [comment]
@jfversluis As @TravyDale says, this use case could be implemented by adding a TextCase property to the TabViewItem.
On Android, it can default to TextCaseType.Upper and on the other platforms to TextCaseType.None so the text stays equal as it is currently.

Though it is a pretty edge case I think it could be simple to implement and I'm willing to do it. What do you think?

**Comment by yunusefendi52** [comment]
I also noticed that the template chosen based on the platform it's running, no renderer tho which is a good thing. maybe give an option to not chosen based on the platform and pick the default one @jfversluis?
https://github.com/xamarin/XamarinCommunityToolkit/blob/aba6205274a7fb8c8a55eaedb8001e3a693ed5f1/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs#L526-L536
