### ISSUE TITLE
[Enhancement] SwitchConverter

### ISSUE THREAD

**Issue by sattew** [xamarin/XamarinCommunityToolkit#1121]
## Summary

Implement SwitchConverter that allows to set values for the bindning depends on some state. I think it's a good idea to allows the IfElse, IfElseIf conditions in XAML.

## API Changes

``` csharp
public class SwitchConverter : IValueConverter
{
    Collection<CaseExpression> Cases;
    object? DefaultValue;
}
```
``` csharp
public class CaseExpression
{
    object If;
    object Then;
}
```

## Intended Use Case
Picture, we have collection of Orders with Property "State" (Created, Paid, Canceled) and we need to change BackgroundColor

- white — Created
- green — Paid
- red — Canceled

With this converter we can simply implement this logic in XAML like

``` xaml
...
<Resources>
  <Color x:Key="white">White</Color>
  <Color x:Key="red">Red</Color>
  <Color x:Key="green">Green</Color>
  <SwitchConverter x:Key="StateSwitchConverter" DefaultValue="{StaticResource white}">
	<CaseExpression If="{x:Static space:OpderState.Canceled" 
	                Then="{StaticResource red}" />
	<CaseExpression If="{x:Static space:OpderState.Paid" 
	                Then="{StaticResource green}" />
  </SwitchConverter>
</Resources>
...
<CollectionView ItemSource={Binding Orders}>
  <CollectionView.ItemTemplate>
    <DataTemplate>
      <StackLayout BackgroundColor={Binding State, Converter={StaticResource StateSwitchConverter}}>
        ...
      <StackLayout>
    </DataTemplate>
  </CollectionView.ItemTemplate>
</CollectionView>
```

There can be a lot of situations when we can use this converter.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by IeuanWalker** [comment]
Isn't this just a data trigger? https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers#data-triggers

**Comment by sattew** [comment]
Oh, sorry, I haven't seen it ...or forgot 😄 . So it's looks like what I described... And it works fine. Closed)
