### ISSUE TITLE
[Enhancement] Extend SetFocusOnEntryCompleted behavior to Layout<View>

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1123]
## Summary
Extend current implementation of `SetFocusOnEntryCompleted` to layouts, provide auto focus on a next Entry child of the layout attached to it, based on:
- Visual tree order.
- Or custom order (not sure about usefulness of this compared to the current implementation)

## API Changes
```
<StackLayout xct:AutoSetFocusOnEntryBehavior Mode="VisualOrder">
    <Entry >
    ...
</StackLayout>
```
```
<StackLayout xct:AutoSetFocusOnEntryBehavior Mode="CustomOrder"`
    <Entry xct:AutoSetFocusOnEntryBehavior.FocusOrder="2">
    <Entry xct:AutoSetFocusOnEntryBehavior.FocusOrder="3">
    <Entry xct:AutoSetFocusOnEntryBehavior.FocusOrder="4">
    <Entry xct:AutoSetFocusOnEntryBehavior.FocusOrder="1">
    ...
</StackLayout>
```
PS: Please don't mind naming initially.

## Intended Use Case
Automatically focus on next visual Entry (child) of a layout.

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by Cfun1** [comment]
@AndreiMisiukevich @pictos any thoughts ?

**Comment by AndreiMisiukevich** [comment]
@brminnick @jfversluis

**Comment by AndreiMisiukevich** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/issues/1087
Is it the same?

**Comment by Cfun1** [comment]
@AndreiMisiukevich I am not sure 100% but I don't think so, since the issue you have linked is about 
> This indicates the focus order of the controls when a user is navigating via TalkBack/VoiceOver

but I see @jfversluis https://github.com/xamarin/XamarinCommunityToolkit/issues/1087#issuecomment-800525365 aiming to make the link with SetFocusOnEntryCompleted, so it's quite difficult to say at this stage.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
