### ISSUE TITLE
[Enhancement] Add ListCountConverter

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1128]
## Summary

I have just created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1127) adding a converter that returns the number of elements in a collection, even if the collection is null for example, reducing unnecessary null checks and returns what I want, just the number of elements.

## API Changes

Create a converter In order to facilitate getting the number of elements in a collection, even in case of the collection is not initialized.

## Intended Use Case

```
<Label Text="{Binding Items, Converter={xct:ListCountConverter}, StringFormat='The number of items is {0}'}" />
```
## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by maxkoshevoi** [comment]
Thanks for contribution, but I have some doubts regarding it's usefulness. 

> It is a converter in case checking the number of elements in a collection is necessary and you do not need to check if Items is null for example.
> It reduces unnecessary null checks and returns what I want, just the number of elements.

All this convertor does is removes `null` checks, but if you use `ObservableRangeCollection` (like you do on the sample page), it will never be null. Additionally `null` and `empty collection` doesn't always mean the same thing. If they do, you can just initialize your collection property with empty collection to begin with.

Another thing is that this convertor doesn't update the value when collection changes, so you have to add something like this to your view model:
`Items.CollectionChanged += (sender, e) => OnPropertyChanged(nameof(Items));`
While if you use `{Binding Items.Count}` it does update when collection changes.

**Comment by GUOLDEV** [comment]
@maxkoshevoi thank you very much for your feedback. What type of collection `Items` that you refer to that is not going to working with the converter `{Binding Items, Converter={xct:ListCountConverter}` but works with `{Binding Items.Count}` approach?

Another thing is that I don't think it is a good idea to bind nested objects as`{Binding Items.Count}`, I prefer binding flat objects.

**Comment by AndreiMisiukevich** [comment]
@GUOLDEV is there any case when a converter cannot be replaced by ```Items.Count```?
I don't think it's a bad practice to use "nested" bindings. We usually use them for x:Reference bindings when one control binds to another one)

**Comment by GUOLDEV** [comment]
@AndreiMisiukevich, thanks for your feedback. I think the intent of having a converter is to help active something avoiding extra coding, simplifying things. Answering your question, I believe it is case by case, I didn't say `Items.Count` is wrong or bad, but I do prefer flat objects in the bindings.

**Comment by maxkoshevoi** [comment]
> What type of collection `Items` that you refer to that is not going to working with the converter `{Binding Items, Converter={xct:ListCountConverter}` but works with `{Binding Items.Count}` approach

I didn't say that it's not going to work, just that value wouldn't update without additional code (in case of `ObsevableCollection` or `ObservableRangeCollection`). 

I just don't see much value in this convertor. `{Binding Items.Count}` will work just fine, or even better (considering that it would autoupdate its value). 

Regarding the null check:
- Creating a whole new convertor just to avoid null check on one property is a bit overkill (at least for the NuGet that's meant to contain commonly used things)
-  And more important point is. If you use `ObservableRangeCollection` (like you do on the sample page), it will never be `null` (since you don't need to create new instance of it replace its values). Additionally `null` and `empty collection` doesn't always mean the same thing. If they do, you can just initialize your collection property with empty collection to begin with.

**Comment by GUOLDEV** [comment]
@maxkoshevoi the reason that I am asking about the type of collection that you refer is that my sample for this converter is using `ObservableRangeCollection` and it works without any extra code.

**Comment by maxkoshevoi** [comment]
> it works without any extra code.

Try removing this line from you sample page:
`Items.CollectionChanged += (sender, e) => OnPropertyChanged(nameof(Items));`

This is extra code that is not needed for `{Binding Items.Count}`

**Comment by GUOLDEV** [comment]
@maxkoshevoi I see, thanks for pointing the issue, I missed that part.
