### ISSUE TITLE
VisualDemos sample build dependency problems

### ISSUE THREAD

**Issue by wtfink** [xamarin/XamarinCommunityToolkit#113]
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/VisualDemos

## Bug 

Version Number of Plugin: **visual studio 2019 pro** 
Device Tested On:  **n/a since cant build**
Simulator Tested On:  **n/a since cant build** 

### Expected Behavior
**successful build of unedited zip extract**

### Actual Behavior
**dependency problems prevent build** 

### Steps to reproduce the Behavior
**1. 1.download toolkit zip
2. 2.unzip via extract all to newly created empty folder
3. 3. load solution using vs2019pro  ver 16.2.4 ms .net framework ver 4.8.03752
4.  on my dell inspirion 15-3571 with: latest win10 and all updates, latest xamarin ver 16.2.0.95
5. 4.wait until all projects are loaded and installed
6. 5.load tools nuget package manager you see needing 13 updates and select all
7. 6.all nuget updates fail
8. 7.attempt solution build but it fails
9. 8.view all project dependencies. you should see these package errors:
10. 

1. 1-stylecops.analyzers(1.1.0-beta006)
2. 2-xamarin.forms(3.1.0.583944)
3. 3-mdoc(5.7.1)
4. 4-msbuild.sdk.extras(1.6.20-preview)
5. 5-netstandard.library(2.0.3)
6. 6-microsoft.net.test.sdk(15.7.2)
7. 7-mstest.testadapter(1.3.2)
8. 8-mstest.tesdframework(1.3.2)
9. 9-microsoft.netcore.app(2.0)
10. 10-netstandardlibrary(1.6.1)
11. 11-uap 10.0.16299**
12. 

## Feature Request:
Please fill in what you would like
**none but this code asis is exciting and important to me and my app development business**

**Comment by jfversluis** [comment]
Since the project will be overhauled I don't think this will be relevant anymore
