### ISSUE TITLE
[Enhancement] Add StringToListConverter

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1134]
## Summary

I have created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1132) adding a converter that returns an array whose elements contain the substrings in this string that are delimited by a separator, based on the converter ListToStringConverter.

![image](https://user-images.githubusercontent.com/22019245/112720903-cb896e00-8f4c-11eb-898e-13c2f64a16b5.png)

## API Changes

NA
## Intended Use Case

```
<Entry x:Name="ExampleText" Text="Item 1,Item 2,Item 3" />
<ListView BindingContext="{x:Reference Name=ExampleText}" ItemsSource="{Binding Path=Text, Converter={StaticResource StringToListConverter}}" />
```
## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@GUOLDEV Thanks for your interest in contributing to the XCT project. Just a friendly reminder, please wait for us to review the issue/proposal before submitting a PR. Could be cases that the feature will not be approved and we will need to close your PR and we don't want you to work in things that can't be accepted.

**Comment by GUOLDEV** [comment]
@pictos  thanks!

**Comment by GUOLDEV** [comment]
@pictos @AndreiMisiukevich is there anything else that I need to do for this issue?

**Comment by pictos** [comment]
@GUOLDEV I'll review it tomorrow and let you know if we need anything else. Thanks (:

**Comment by AndreiMisiukevich** [comment]
Implemented in https://github.com/xamarin/XamarinCommunityToolkit/pull/1132
