### ISSUE TITLE
[Spec] Calendar

### ISSUE THREAD

**Issue by DamianAntonowicz** [xamarin/XamarinCommunityToolkit#1135]
# Calendar

Calendar control that displays calendar ;) Spec is based on working solution from my GitHub: https://github.com/DamianAntonowicz/XamarinForms.CalendarControl

Calendar is using CalendarDay control to display specific days. Calendar is also using CalendarWeekDayHeader control to display at the top week day headers: Monday, Tuesday, etc.

# API

### Properties

| Property | Type | Description |
| ------------- | ------------- | ------------- |
| Date | DateTime | Current date that calendar is displaying. |
| SelectionMode | CalendarSelectionMode | Selection mode for days: SingleSelect or MultiSelect. |
| ShowDaysFromOtherMonths | bool | If set to `true` calendar will show days from other months. |
| ShowWeekends | bool | If set to `true` calendar will show weekends. |
| FirstDayOfWeek | DayOfWeek | First day of week: Monday, Sunday, etc. |
| SelectedDays | IReadOnlyCollection\<DateTime> | Days that are currently selected. |
| Days | IReadOnlyCollection\<CalendarDay> | Days that are currently being displayed.. |
| DayControlTemplate | ControlTemplate | ControlTemplate for all days. |
| WeekDayHeaderControlTemplate | ControlTemplate | ControlTemplate for week day header at the top of calendar. |

### Events

| Event | Args | Description |
| ------------- | ------------- | ------------- |
| DayTapped | CalendarDayTappedEventArgs | Event that is raised when user tapped on specific day. EventArgs allows get access to specific CalendarDay control. |
| DayUpdated | CalendarDayUpdatedEventArgs | Event that is raised when Calendar has updated day. EventArgs allows get access to specific CalendarDay control. |
 
## CalendarDay : TemplatedView

Displays specific day.

### Properties

| Property | Type | Description |
| ------------- | ------------- | ------------- |
| IsSelectable | bool | If set to `true` specific CalendarDay can be selected by user. |
| IsSelected | bool | If set to `true` specific CalendarDay is currently selected. |
| Date | DateTime | Current date that specific CalendarDay is displaying. |

## CalendarWeekDayHeader : TemplatedView

Displays week day header at the top of calendar.

### Properties

| Property | Type | Description |
| ------------- | ------------- | ------------- |
| DayOfWeek | DayOfWeek | Day of week that specific CalendarWeekDayHeader is displaying. |

# Scenarios

## Calendar

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
                         xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                         xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
                         x:Class="XamarinForms.CalendarComponent.MainPage">

    <xct:Calendar x:Name="Calendar"
                  DayUpdated="Calendar_OnDayUpdated"
                  DayTapped="Calendar_OnDayTapped"
                  Date="01/01/21"
                  ShowWeekends="True"
                  ShowDaysFromOtherMonths="True"
                  FirstDayOfWeek="Sunday"
                  SelectionMode="SingleSelect"
                  DayControlTemplate="{StaticResource CalendarDayControlTemplate}"
                  WeekDayHeaderControlTemplate="{StaticResource CalendarWeekDayHeaderControlTemplate}"/>

</ContentPage>
```

## ControlTemplate for DayControl

```xml
<ControlTemplate x:Key="CalendarDayControlTemplate">
    <Grid>

        <BoxView Color="Gray"
                 CornerRadius="5">

            <BoxView.Triggers>

                <DataTrigger TargetType="BoxView"
                             Binding="{TemplateBinding IsSelected}"
                             Value="True">
                    <Setter Property="Color"
                            Value="Green" />
                </DataTrigger>

                <DataTrigger TargetType="BoxView"
                             Binding="{TemplateBinding IsSelectable}"
                             Value="False">
                    <Setter Property="Color"
                            Value="LightGray" />
                </DataTrigger>

            </BoxView.Triggers>

        </BoxView>

        <Label Text="{TemplateBinding Date, Converter={StaticResource DateTimeToDayConverter}}"
               HorizontalOptions="Center"
               VerticalOptions="Center"
               FontSize="Medium"
               TextColor="Black">

            <Label.Triggers>

                <DataTrigger TargetType="Label"
                             Binding="{TemplateBinding IsSelectable}"
                             Value="False">
                    <Setter Property="TextColor"
                            Value="Gray" />
                </DataTrigger>

            </Label.Triggers>

        </Label>

        <Ellipse WidthRequest="5"
                 HeightRequest="5"
                 VerticalOptions="End"
                 HorizontalOptions="Center"
                 Margin="0,0,0,5"
                 IsVisible="False"
                 Stroke="Red"
                 Fill="Red">

            <Ellipse.Triggers>

                <DataTrigger TargetType="Ellipse"
                             Binding="{TemplateBinding BindingContext.HasAppointments}"
                             Value="True">
                    <Setter Property="IsVisible"
                            Value="True" />
                </DataTrigger>

            </Ellipse.Triggers>

        </Ellipse>

    </Grid>
</ControlTemplate>
```

## ControlTemplate for CalendarWeekDayHeader

```xml
<ControlTemplate x:Key="CalendarWeekDayHeaderControlTemplate">
    <Label Text="{TemplateBinding DayOfWeek, Converter={StaticResource DayOfWeekToAbbreviatedName}}" />
</ControlTemplate>
```

## Consuming Calendar events in code behind

```csharp
private async void Calendar_OnDayTapped(object sender, CalendarDayTappedEventArgs e)
{
    await DisplayAlert(title: "", message: "You clicked on: " + e.CalendarDay.Date, cancel: "ok");
}

private void Calendar_OnDayUpdated(object sender, CalendarDayAddedEventArgs e)
{
    if (e.CalendarDay.Date.DayOfWeek == DayOfWeek.Saturday ||
        e.CalendarDay.Date.DayOfWeek == DayOfWeek.Sunday)
    {
        e.CalendarDay.ControlTemplate = Resources["CalendarDayControlTemplateWeekend"] as ControlTemplate;
    }

    if (e.CalendarDay.Date.Day == 3 ||
        e.CalendarDay.Date.Day == 10)
    {
        e.CalendarDay.IsSelectable = false;
    }
    
    if (e.CalendarDay.Date.Day == 5 ||
        e.CalendarDay.Date.Day == 16)
    {
        e.CalendarDay.BindingContext = new Day {HasAppointments = true};
    }

    if (e.CalendarDay.Date.Month != Calendar.Date.Month)
    {
        e.CalendarDay.IsSelectable = false;
        e.CalendarDay.ControlTemplate = Resources["CalendarDayFromOtherMonthControlTemplate"] as ControlTemplate;
    }
}
```
# Screenshots

## iOS

![iOS_2](https://user-images.githubusercontent.com/12022141/112727474-ed6dfb00-8f22-11eb-8b84-c3e4288bb9ed.png)
![iOS_1](https://user-images.githubusercontent.com/12022141/112727464-e941dd80-8f22-11eb-92c0-59590a8b8b2c.png)

## Android

![Android_2](https://user-images.githubusercontent.com/12022141/112727472-ecd56480-8f22-11eb-9f08-c0d2617b6dec.png)
![Android_1](https://user-images.githubusercontent.com/12022141/112727470-ec3cce00-8f22-11eb-84d0-f4eb9ca0fc1a.png)

# Platform Compatibility
- Target Frameworks:
  - iOS: ✅ 
  - Android: ✅
  - UWP: ✅
# Backward Compatibility

N/A

# Difficulty : medium

**Comment by pictos** [comment]
@DamianAntonowicz thanks for this spec, looks great! I'll give it a try to your control this week and let you know about it.

Also, this is related to #848

**Comment by pictos** [comment]
@DamianAntonowicz I looked at your code and ran the app on my end (android emulator), it seems ok to me, I found some "issues", that we can improve it I believe.

First of all the code looks good, you will need to perform some changes to it to adequate to our pattern, and also I saw some places that we can refactor to avoid code duplication.

From the control itself, I saw some points to improvement:
1. Big delay when you move between months;
2. Delay when we mark one of the checkboxes;
3. Delay when changing the start day of the week;
4. Inconsistency when I want to select a day

Please see the video below about item 4, I can't select that Sunday 10th.

About the delay between months, I think that @ionixjunior could help us since he solved that issue for his Calendar Control.

https://user-images.githubusercontent.com/20712372/113080927-1e159500-91ae-11eb-8ed2-0af50ad2c866.mp4

**Comment by DamianAntonowicz** [comment]
@pictos thanks for the feedback. I'll investigate how to improve performance. About selecting 10th day of the month, this is made on purpose in code behind of MainPage.xaml.cs (https://github.com/DamianAntonowicz/XamarinForms.CalendarControl/blob/9c7cc6419be8aa62aa92b7da728b3621c061e45d/XamarinForms.CalendarComponent/MainPage.xaml.cs#L30) to show how to disable selection for specific days ;) Perhaps in that case there should be different visual appearance of the day to make it more understandable.

**Comment by ionixjunior** [comment]
@DamianAntonowicz in the [Xalendar](https://github.com/ionixjunior/Xalendar), the big problem to navigate between months was to inflate the view again to render the new days, that was slow. Fortunately, this was easy to solve. We create a "cache" for the day element. Instead of clear all elements of the view and add new references, the approach was to recycle the current elements to show new data.

**Comment by DamianAntonowicz** [comment]
@pictos just a quick update from my side: I've working solution with performance improvements (switching between months is now faster). Now I need to clean the code and fix some minor bugs. Hope I will push final code to my repo this week.

**Comment by DamianAntonowicz** [comment]
@pictos I've pushed performance improvements to my repo https://github.com/DamianAntonowicz/XamarinForms.CalendarControl Switching between months is now faster - I'm attaching gifs below. Let me know if this is fast enough :)

![iOS_Calendar](https://user-images.githubusercontent.com/12022141/115971798-d97ddf00-a54a-11eb-9d9a-69540b50b5f8.gif)
![Android_calendar](https://user-images.githubusercontent.com/12022141/115971803-dda9fc80-a54a-11eb-8567-a629d05c1467.gif)

**Comment by pictos** [comment]
@DamianAntonowicz I'll take a look and return to you ASAP

**Comment by davidbuckleyni** [comment]
NO doumentation on how to include the calendar in the header tag.

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              xmlns:components="clr-namespace:XamarinForms.CalendarComponent;assembly=XamarinForms.CalendarComponent"
             x:Class="App1.Views.Cal">
     <ContentPage.Content>

What should the value of  xmlns:components= Be ?

**Comment by DamianAntonowicz** [comment]
@davidbuckleyni thanks, I've updated the spec

**Comment by davidbuckleyni** [comment]
Its very good but @DamianAntonowicz I had trouble in being able to bind to the box view required for the Day Cell when I did calendarDay.Backcolor nothing happened it didnt change the active color of the cell in quesiton maybe if u made a cell color property would make my special day code easier/

**Comment by DamianAntonowicz** [comment]
@davidbuckleyni it would be better if we move our discussing to my repo: https://github.com/DamianAntonowicz/XamarinForms.CalendarControl because this thread is only about Spec. Could you open issue in my repo?

**Comment by pictos** [comment]
@DamianAntonowicz I did a quick test here and I liked the perf. improvement when I switch between months! Great job!

There are still some lags, listed in my previous list, I believe that we can help you with them as an enhancement.
For me, this is good to go.

I'll ping other members to see what they think about it as well (:

Thank you for the hard work @DamianAntonowicz <3

**Comment by jsuarezruiz** [comment]
Thanks so much for the hard work @DamianAntonowicz. After the performance improvements looks much better. Probably between all us we can improve it a little bit more. I think is good to go and start. Let us know when you have a PR to help you with the code etc.

**Comment by davidbuckleyni** [comment]
I agree this is an excellent little calendar, but I think for completeness and esp all things MAUI we will need a win ui version @jsuarezruiz

**Comment by davidbuckleyni** [comment]
@pictos  One thing I did notice was their didnt appear to be back and forward buttons unless am missing something?

**Comment by DamianAntonowicz** [comment]
@pictos @jsuarezruiz thanks for your answers! I will start working on PR in next week :)

**Comment by davidbuckleyni** [comment]
Do u have ur own code for this now ? Love to use it instead of syncfusion

**Comment by DamianAntonowicz** [comment]
Just letting know that I'm working on integrating Calendar control into XCT :) Here is a short video of work in progress: 

https://user-images.githubusercontent.com/12022141/119241954-6b810380-bb5a-11eb-96e5-4c73e6a59e82.mp4

What's left is cleaning the code. Hopefully I will submit PR soon :)

**Comment by DamianAntonowicz** [comment]
@pictos @jsuarezruiz I've submitted PR: https://github.com/xamarin/XamarinCommunityToolkit/pull/1331 any comments welcome :)

**Comment by davidbuckleyni** [comment]
Dont forget to let it handle null dates at the start ie non selected or place holders @DamianAntonowicz  one of the failings of the normal date pickers

**Comment by davidbuckleyni** [comment]
Just make sure that you allow for nulls on the Date property I know but somepeople like it either that or provide a selectedDate which can be null

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
