### ISSUE TITLE
[Enhancement] Autofit Label

### ISSUE THREAD

**Issue by felipebaltazar** [xamarin/XamarinCommunityToolkit#1136]
## Summary
A label that grows/shrinks the font size to fit entire bounds

For Android we have [this native API](https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview)
For IOS we have [this native API](https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth)
For UWP we have [this example](https://github.com/baskren/Forms9Patch/blob/58183808e4e320f3e79c76f919ff28c991160354/Forms9Patch/Forms9Patch.UWP/Renderers/LabeLRenderer.cs#L344):

Ive done a PR on Xamarin Forms for this:
https://github.com/xamarin/Xamarin.Forms/pull/7981

> **Important** this will need be a new control, since we need to change `TextView` to `AppCompatTextView`... [More details here](https://github.com/xamarin/Xamarin.Forms/pull/7981#discussion_r362300397)

## API Changes

- (enum) AutoFitTextMode Label.AutoSizeMode{ get; set; } //Bindable Property
- double Label.MaxAutoFitSize { get; set;} //Bindable Property
- double Label.MinAutoFitSize {get; set;} //Bindable Property

## Intended Use Case
Label to fit bounds and works as a responsive text

```xml
<AutoFitLabel AutoSizeMode="FitToWidth"/>

```
![image](https://user-images.githubusercontent.com/19656249/112735461-f19e1680-8f2a-11eb-972f-846ebdc759b5.png)

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
@felipebaltazar awesome) I like it! would you like to submit a pull request to XCT?

**Comment by felipebaltazar** [comment]
Yeah! I just need to adapt my PR to XCT

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
