### ISSUE TITLE
[Bug] Markup extension doesn't support c# mitting type in the new expression

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1137]
### Description
When using the new c# 9 feature that allows to omit the type in a `new` expression when the created object's type is already known, markup extension doesn't support it.

https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#fit-and-finish-features

### Steps to Reproduce
Works:
```
			List<Label> list = new()
			{
				new Label().Style(...),
				new Label().Bind(Label....),
			};
```
```
			List<Label> list = new()
			{
				new(),
				new(),
			};
```

Doesn't work:
> There is no target type for 'new()'
```
			List<Label> list = new()
			{
				new().Style(...),
				new().Bind(Label....),
			};
```
### Basic Information
- Version with issue: v1.1.0
- Last known good version: - 
- IDE: VS 2019 16.9.2
- Platform Target Frameworks: All shared code

**Comment by AmrAlSayed0** [comment]
Open an issue at [dotnet/roslyn](https://github.com/dotnet/roslyn/issues) because I don't think there is a solution from the library's side. This is a compiler issue/bug.

**Comment by 333fred** [comment]
This isn't a bug. `new()` needs a target type, and none is provided here. There is no way for the compiler to insert what you mean.

**Comment by maxkoshevoi** [comment]
@333fred This compiles without any issues

```
List<Label> list = new()
{
  new(),
  new(),
};
```

![image](https://user-images.githubusercontent.com/6609929/112761389-c63b2a80-9003-11eb-9ecf-d22affe06a90.png)

**Comment by Cfun1** [comment]
I am confused could someone confirm if this bug/issue belongs to xct or roslyn?

Cc @jfversluis @pictos @AndreiMisiukevich

**Comment by maxkoshevoi** [comment]
@Cfun1 It's not a bug. As mentioned by @333fred, compiler has no way of knowing what type do you mean when writing `new().Something`.
`new List<T> { new() }` works since type of the `new()` can be resolved from the type of the collection that it should be added in.

Here is the same code, but written differently:
```cs
List<T> list = new();
// Works
list.Add(new()); 
// Doesn't work, since compiler can infer type of "Something", but not of "new()"
list.Add(new().Something); 
```

**Comment by 333fred** [comment]
Perfect explanation @maxkoshevoi.
