### ISSUE TITLE
[Bug] StateView not displayed if StateKey property is matched to "None" value

### ISSUE THREAD

**Issue by Kapusch** [xamarin/XamarinCommunityToolkit#1138]
### Description
Given a StateView "A" with StateKey property defined to "Loading"
and another StateView "B" with StateKey property defined to "None"
and the binded value for CurrentState is defined to "Loading"
When CurrentState value becomes "None"
Then StateView "A" disappears
But StateView "B" does not show up

### Steps to Reproduce

1. Run XCT.Sample on iOS
2. Go to the StateLayout example page (Views > StateLayout)
3. Tap the button to launch the States cycle
4. When None state is loaded, the associated StateView is not showing up

### Expected Behavior

I was assuming StateView associated to "None" StateKey will appear on screen, is it the normal behavior ?

### Actual Behavior
The StateView with StateKey property defined to "None" never show up.

### Basic Information

- Version with issue: 1.1.0
- Last known good version: N/A
- IDE: VS for Mac v8.9.3
- Platform Target Frameworks: 
  - iOS:  iOS 14.4
- Nuget Packages:
-- Xamarin.Forms 5.0.0.1874,
-- Xamarin.Essentials 1.5.3.2
- Affected Devices: tested on iPhone Simulator only

### Workaround
I have substituted all "None" StateKey into "Success" StateKey

### Reproduction imagery
![XCT_StateView_Not_Appearing](https://user-images.githubusercontent.com/9576733/112768522-ae23d500-901c-11eb-808f-4d5f4ad0a36d.gif)

### Reproduction Link
[XCT_StateView_Not_Appearing.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6218087/XCT_StateView_Not_Appearing.zip)

**Comment by AndreiMisiukevich** [comment]
Is it the same with #1112

if yes, it was fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1122

can you please validate that PR?

**Comment by Kapusch** [comment]
Hi @AndreiMisiukevich , it looks like the same, indeed... but I have created my repro example from the XCT main branch yesterday, and your fix has been merged 2 days ago.

Otherwise, how could I directly validate the fix provided in the PR please ?

**Comment by Kapusch** [comment]
I confirm, your fix is already included in the repro sample:
```
LayoutState previousState = LayoutState.None;
```

**Comment by AndreiMisiukevich** [comment]
Duplicate of #1122

**Comment by Kapusch** [comment]
Sorry @AndreiMisiukevich , what I meant is that your fix was included in my repro sample, and even with that, the bug I have captured in the Gif is still valid.

Am I possibly wrongly using the None state ?

**Comment by AndreiMisiukevich** [comment]
@Kapusch ah, sorry for the misunderstanding.

is your issue the same with https://github.com/xamarin/XamarinCommunityToolkit/issues/1032 ?

**Comment by Kapusch** [comment]
No problem !

I had a look at the issue you are mentioning but no, mine is more about "none stateview never shows up"

But maybe I am not using it right.

**Comment by AndreiMisiukevich** [comment]
CC @sthewissen

**Comment by kerberosargos** [comment]
Same thing is for me.

**Comment by mkanyo** [comment]
Just wanted to note that this used to work fine with version 1.1.0-pre1

**Comment by AndreiMisiukevich** [comment]
Feel free to grab this issue, debug and submit a PR :)
I'll be happy to review it

**Comment by mkanyo** [comment]
Well... it does sound tempting... I'll have a look if I can this weekend and see what happens

**Comment by mkanyo** [comment]
Good news everyone! Running the code on develop branch with PR #1122 it works for me: `LayoutState.None` displays again after a state of `LayoutState.Loading`. 

I also undid the PR locally (the 1 line change in `Views\StateLayout\StateLayoutController.shared.cs`) and as expected it broke again. Brilliant!

I hope this will make it to be to be a nuget soon! 

Grin grin, wink wink, nudge nudge :) Miklos

**Comment by Kapusch** [comment]
Hi @mkanyo , except if I'm misunderstanding, the fix you're talking about is already part of my repro sample.
And even with that, the bug I have captured in the Gif is still valid.

Could you try applying your fix in my repro sample please ?
Or am I possibly using the None state incorrectly ?

Thanks for your investigation 👍

**Comment by mkanyo** [comment]
Hello @Kapusch 

Right, I've downloaded your sample zip file and ran it. Yes, I think you need to use it differently:

![image](https://user-images.githubusercontent.com/51201132/115967867-50a87880-a535-11eb-9423-5784d2890ad6.png)

You should not define "None" separately as stateview, rather it should be next to the StateViews collections:

![image](https://user-images.githubusercontent.com/51201132/115967900-7766af00-a535-11eb-864a-4dc2d8835cc9.png)

To be honest I also ran into this issue about 2 months ago when I adopted StateLayout in my project but if you use it like that then the "None" will also show.

![Screen Recording 2021-04-24 at 19 40 11](https://user-images.githubusercontent.com/51201132/115968043-05db3080-a536-11eb-98bd-1f5f53317759.gif)

I think this may need some more emphasis in the documentation as evidently it's not obvious 👍 

I just searched github for an example - here is one other case where "None" is implicitly used:
https://github.com/weeklyxamarin/WeeklyXamarin.mobile/blob/c723022628e1e448acfc251b326745c5e497f220/src/WeeklyXamarin.Mobile/WeeklyXamarin.Mobile/Views/BookmarksPage.xaml

I hope this helps,
Miklos

**Comment by Kapusch** [comment]
Thanks @mkanyo for your help !
I'll give a try soon in my app to verify if this does not break my VisualStates management.

@AndreiMisiukevich , can you please confirm if this is the way you wanted "None" state to be used ?
If so, I'll close current issue and propose that we update the documentation.

**Comment by sthewissen** [comment]
@Kapusch The behavior outlined above is indeed the intended usage. The `None` StateView is ignored and this default content should just be declared as children of your StateLayout aware element (Grid, StackLayout etc). Main reasoning is that it simplifies incorporating StateLayout into existing code without having to rewrite all your views into a `None` StateView. That way you only have to add the StateViews you need on top of your existing layout.

**Comment by Kapusch** [comment]
Thanks for these explanations @sthewissen

I wonder if allowing both implementations could not save time to somebody else who may encounter this:
- StateView with "None" value assigned to StateKey
- And current implementation with "None" content declared as children of the StateLayout

Meanwhile, I close the issue, thanks again.

**Comment by TalalYousif** [comment]
So, just to confirm, this is a known issue and a fix is on the way. The issue is, views outside of StateViews collection will not show up. The workaround is to define a success custom state and add the normal state as a state view with that key
