### ISSUE TITLE
[Bug] [Expander] InvalidOperationException: Header not initialized

### ISSUE THREAD

**Issue by kevin68** [xamarin/XamarinCommunityToolkit#1144]
### Description
Since updating from XCT 1.0.3 to 1.1.0 the application throws an exception when displaying the main page that contains an Expander.  
I found out that the crash happens when I set the property `Direction` to a value other than `Down` and whether or not I define a `Header`. After some digging it seems to come from [this line](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs#L400) which was added [by this commit](https://github.com/xamarin/XamarinCommunityToolkit/commit/d74ab1d633a78490eb3818cbb55a80d7ddd62a5a#diff-25b835d71d4a200c2ff9da4cf14c1762922356d8057d66f71c4db880ffaa0a98).

Exception: `System.InvalidOperationException: Header not initialized`.  
<details>
  <summary>Stacktrace (not much)</summary>

```
[mono] System.InvalidOperationException: Header not initialized
[mono]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
[mono]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
```
</details>

### Steps to Reproduce

1. Create a blank Xamarin.Forms project
2. Install the Xamarin Community Toolkit 1.1.0
3. Add `xmlns:xct="http://xamarin.com/schemas/2020/toolkit"` to the main page
4. Add a simple Expander with a Direction in the content of the main page
```xaml
       <xct:Expander Direction="Right">
            <xct:Expander.Header>
                <Label Text="header"/>
            </xct:Expander.Header>
            <Label Text="content"/>
        </xct:Expander>
```
5. Launch the app

### Expected Behavior
The main page displays with the Expander

### Actual Behavior
Visual studio catch an unhandled exception

### Basic Information

- Version with issue: 1.1.0
- Last known good version: 1.0.3
- IDE: Visual Studio 2019 16.9.2
- Platform Target Frameworks:  
  - iOS: 11.4
  - Android: 11.0 
- Android Support Library Version: None
- Nuget Packages:
  - Xamarin.Essentials@1.6.1
  - NETStandard.Library@2.0.3
  - Xamarin.Forms@5.0.0.2012
- Affected Devices:
  - Pixel 3XL (Android 11.0)
  - Pixel 3a (Emulator, Android 9.0)
  - IPhone SE (iOS 14.4)

### Workaround
Set the direction to Down, then change it after InitializeComponent() is called.

### Reproduction imagery
N/A

### Reproduction Link
[Repro project (489ko)](https://github.com/xamarin/XamarinCommunityToolkit/files/6223020/XCTBugRepro.zip)

**Comment by AndreiMisiukevich** [comment]
Should be
```void SetHeader(View? oldHeader)```

And the line you mentioned should be dropped.

Great report!

**Comment by kevin68** [comment]
Hi, I think there was an issue with the last release (1.2.0)
This issue (with its PR #1147) were marked as fixed in the changelog, but after updating the package I still encountered the error.
After cleaning the project, nuget cache, restarting VS, I downloaded the package directly from the NuGet page and checked with dotPeek.
The function `SetDirection` in the `Expander` view, still contains this piece of code :
```
if (this.Header == null)
        throw new InvalidOperationException("Header not initialized");
```
But it isn't in the [source code](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs#L430) on the main branch.
