### ISSUE TITLE
[Enhancement] Add ConditionalDoubleConverter

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1149]
## Summary

Add `ConditionalDoubleConverter` which seem to have similar name as existing `IntToBoolConverter` but the aim is totally different.

Input is a double and output is a bool, the difference with `IntToBoolConverter` is that the value of this bool depends on a condition set by the dev, <, >, ==, <=, >=, !=.

## API Changes
```
When ScrollY > 10 returns true otherwise false
<SomeView IsVisible="{Binding ScrollY, Converter={xct:ConditionalDoubleConverter Condition='>', Value=10}"/>

When ScrollY <= 10 returns true otherwise false
<SomeView IsVisible="{Binding ScrollY, Converter={xct:ConditionalDoubleConverter Condition='<=', Value=10}"/>
```
or better we could extend to more generic than `bool` like FalseObject TrueObject thing like in `BoolToObjectConverter`.

```
When ScrollY > 10 returns blue otherwise red
<SomeView Color="{Binding ScrollY, Converter={xct:ConditionalDoubleConverter Condition='>', Value=10, TrueObject= 'Blue', FalseObject= 'Red'}"/>
```
if `TrueObject` and `FalseObject` are not specified it will return the related bool.

## Intended Use Case
A real example could be used to implement a parallax effect, once the scroll value reach a certain threshold you want to set invisible a view. 

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by GUOLDEV** [comment]
What about using a [ConditionOperator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.conditionoperator?view=dynamics-general-ce-9) enum?

**Comment by Cfun1** [comment]
@GUOLDEV Thanks I didn't know about  ConditionOperator, it seems interesting, we'll check what better for this implementation   a classic switch statement or ConditionOperator.

**Comment by jBijsterboschNL** [comment]
> What about using a [ConditionOperator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.conditionoperator?view=dynamics-general-ce-9) enum?

This ConditionOoerator is part of the Microsoft.Xrm.Sdk namespace, which is used for developing with Microsoft Dynamics. Not sure if you would want to use that one in this scenario.

**Comment by GUOLDEV** [comment]
Actually, I was thinking about something very simple as the sample code below:

```
public class StringToListConverter : ValueConverterExtension, IValueConverter
{
    enum Conditional
    {
        Equal,
        NotEqual,
        LessThan,
        GreaterThan,
        LessThanOrEqual,
        GreaterThanOrEqual,
    }

    public Conditional? Condition { get; set; }

    public IList<Conditional> Conditions { get; set; } // If you prefer combining enums rather than specific single ones

    public object? ValueToCompare { get; set; }

    public object? Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
    {
        if(value is not IComparable c1 || ValueToCompare is not IComparable c2)
            throw new NotSupportedException();

        var result = c1.CompareTo(c2);

        switch (Condition)
        {
            case Conditional.NotEqual:
                return result != 0;
            case Conditional.Equal:
                return result == 0;
            case Conditional.GreaterThan:
                return result > 0;
            case Conditional.LessThan:
                return result < 0;
            default:
                return false;
        }
    }
}
```

**Comment by Cfun1** [comment]
Thanks @GUOLDEV it seems a nice readable approach.

**Comment by Cfun1** [comment]
@AndreiMisiukevich what do you think about this feature request ?

**Comment by GUOLDEV** [comment]
@Cfun1 if the CompareConverter idea is ok and if you don't mind, I can create a PR for this issue.

**Comment by AndreiMisiukevich** [comment]
CompareConverter sounds good

**Comment by Cfun1** [comment]
@GUOLDEV I have already [an implementation](https://github.com/Cfun1/XamsungHealth/blob/master/XamsungHealth.Lib/Converters/ConditionalDoubleConverter.cs) but I believe we can merge the best of both, I was just waiting for the [approval process](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/CONTRIBUTING.md#opening-a-pr-process) feedback and thoughts before sending a pr.

**Comment by pictos** [comment]
@GUOLDEV, @Cfun1 marked this issue as his want to work on it, so I ask you to let him do the implementation. Thanks

**Comment by GUOLDEV** [comment]
That's great @Cfun1 and thanks for considering merging the ideas, let me know if you need any help 👍

**Comment by sattew** [comment]
Also I think I can implement it in MathExpressionConverter (#1117)

**Comment by Cfun1** [comment]
@sattew I don't think `MathExpressionConverter`  serves the same purpose, this converter will **returns a boolean or an object** defined by the dev while `MathExpressionConverter` calculate a math expression and returns the result, IMHO better we don't mix up those two converters.
@AndreiMisiukevich @pictos What are your thoughts?

**Comment by sattew** [comment]
> 
> 
> @sattew I don't think `MathExpressionConverter` serves the same purpose, this converter will **returns a boolean or an object** defined by the dev while `MathExpressionConverter` calculate a math expression and returns the result, IMHO better we don't mix up those two converters.
> @AndreiMisiukevich @pictos What are your thoughts?

Yeah, is it right too. I think MathExpressionConverter can include this logic because the Math includes inequalities.

**Comment by Cfun1** [comment]
Implemented in https://github.com/xamarin/XamarinCommunityToolkit/pull/1172
