### ISSUE TITLE
[Bug] Application crashes after updating from 1.03 to 1.1.0. The view that crashes uses the Expander control

### ISSUE THREAD

**Issue by kaniosm** [xamarin/XamarinCommunityToolkit#1151]
The error report reported is :android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff

The Platform is Android 8.1

**Comment by Cfun1** [comment]
Hi @kaniosm thanks for the report, could please attach a repo?

**Comment by kaniosm** [comment]
It seems that the issue is caused by the direction property (Direction="Up").
Steps to reproduce:
1. Create a new Xamarin Forms project 
2. Add reference to Community toolkit
3. Add a new Expander in any page and set the Direction="Up"

Sample project attached
[App5.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6235650/App5.zip)

**Comment by Cfun1** [comment]
@kaniosm this merged pr https://github.com/xamarin/XamarinCommunityToolkit/pull/1147 has probably fixed the issue, could you please confirm it?

**Comment by kaniosm** [comment]
Yes I can confirm it.
#1147 fixes this issue

**Comment by AndreiMisiukevich** [comment]
@Cfun1 Thank you!)

**Comment by Cfun1** [comment]
@AndreiMisiukevich Anytime :)
