### ISSUE TITLE
[Bug] TabView SelectionChangedEvent returns the same value on both Old and New position.

### ISSUE THREAD

**Issue by samir-dahal** [xamarin/XamarinCommunityToolkit#1154]
### Title
TabView SelectionChangedEvent returns the same value on both Old and New position.

### Description
Please follow the steps to reproduce the issue.
### Steps to Reproduce

1. Create a file new Xamarin Forms application.
2. Install Xamarin Communit Toolkit
3. Create a simple layout using TabView
4. Set SelectionChanged Event on TabView
5. Change the selection on TabView
6. You'll see that the SelectionChanged event args object has two values Old and New.
7. Both values are same.
![image](https://user-images.githubusercontent.com/39849021/113231317-b0a35a80-92ba-11eb-906b-e3e1f03ac5dd.png)

### Expected Behavior
Old and New value should be different.
### Actual Behavior
Old and New value are same even if I change the Tab index
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pictos** [comment]
@samir-dahal could you update your issue by adding a title and a description? Thanks

**Comment by samir-dahal** [comment]
> @samir-dahal could you update your issue by adding a title and a description? Thanks

Please have a look now.

**Comment by pictos** [comment]
@samir-dahal thanks for that, can you upload a small repro? That will help us to triage faster the issue. Do you tried on our sample app?

**Comment by guru1413** [comment]
@pictos  I have faced the same issue in version **1.1.0**, but after updating to version **1.2.0**, it works fine.
Looks like this bug has been resolved in version **1.2.0**.

**Comment by pictos** [comment]
Thanks @guru1413. @samir-dahal Can you try the version 1.2.0 and see if that solves your issue? If don't, please reopen this issue

**Comment by samir-dahal** [comment]
> Thanks @guru1413. @samir-dahal Can you try the version 1.2.0 and see if that solves your issue? If don't, please reopen this issue

Yeah, I think it works in latest version.
