### ISSUE TITLE
[Bug] Hot reload not woking on ShadowEffectPage

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1160]
### Description
Hot reload not working on [ShadowEffectPage](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Effects/ShadowEffectPage.xaml).

### Steps to Reproduce

1. Run the sample
2. Navigate to ShadowEffectPage
3. Make a change and save

### Expected Behavior
Hot reload updates the page.
### Actual Behavior
Page not updated even that in the console:
> Successfully reloaded: ReloadChange in d:/xamarincommunitytoolkit/samples/XCT.Sample/Pages/Effects/ShadowEffectPage.xaml

### Basic Information

- Version with issue: 1.1.0
- Last known good version: -
- IDE: VS2019 16.9.3
- Platform Target Frameworks: xaml
- Affected Devices: tested on Pixel 2 emulator

### Workaround
As suggested by @maxkoshevoi, updating the sample project to Xamarin.Forms 5.0.0.2012 fixes the issue.

[Edit]
After i made clean, i had to set the linker options to none on order for hot reload to work. Even that VS suggest to put linker either none or sdk only, it should work on both.

**Comment by pictos** [comment]
@BretJohnson, since you're a hot reload expert, can you tell us if we can fix this here?

**Comment by jfversluis** [comment]
> As suggested by @maxkoshevoi, updating the sample project to Xamarin.Forms 5.0.0.2012 fixes the issue.

So it seems there is something wrong in Forms and not so much the Toolkit then? Opened #1174 to update the dependencies. I don't think there is much else we can do here.
