### ISSUE TITLE
[Enhancement] Apple's SFSymbols w/ Fallback for Unsupported Platforms

### ISSUE THREAD

**Issue by justadaniel** [xamarin/XamarinCommunityToolkit#1169]
## Summary

This feature creates an easy way to use Apple's 2,400+ *SF Symbols* on supported devices. If we want to add it to macOS, it's as simple as swapping a few declartions for AppKit instead of UIKit. The icons are provided by the system itself saving on app size and helping developers get instant access to a large quantity of artwork. This is especially great for those who only plan on releasing on Apple Platforms.

## API Changes

* iOS 13 or Greater: Implements `IImageSource` that returns their respect `UIImage/NSImage` objects with one of the symbols provided by Apple.
* iOS 12 or Older/Android/UWP: Will use an `ImageSource` base class as a fallback

## Intended Use Case
We create a new image source called `SFSymbolImageSource` or maybe even something such as `SystemImageSource` and adding platform-specific properties for the possibility of adding Android or UWP if they add something similar to SF Symbols.

### Properties
* Glyph: String -> *Apple's Symbol String*
* Weight: Enum -> *SymbolWeight (Like font weight)*
* Size: Float -> *Symbol Size (Like font size)*
* FallbackImageSource: ImageSource

```csharp
var symbol = new SFSymbolImageSource()
{
    Glyph = "square.and.arrow.up",
    Weight = SymbolWeight.Regular,
    Size = 16,
    FallbackImageSource = new FontImageSource()
    {
        FontFamily = "FONT_FAMILY",
        Glyph = "GLYPH",
        Size = 16
    }
};
```

or in XAML:

```xaml
<xct:SFSymbolImageSource Glyph="square.and.arrow.up" Weight="Regular" Size="16">
	<xct:SFSymbolImageSource.FallbackImageSource>
		<FontImageSource
			FontFamily="FONT_FAMILY"
			Glyph="FONT_GLYPH"/>
	</xct:SFSymbolImageSource.FallbackImageSource>
</xct:SFSymbolImageSource>
```

Here's an example of two tabs running in a TabbedPage. The glyphs for the tabs are:
* Tab 0 -> `wrench.and.screwdriver.fill`
* Tab 1 -> `gearshape.2.fill`

![Simulator Screen Shot - iPhone 12 - 2021-04-03 at 16 23 50](https://user-images.githubusercontent.com/1112585/113492428-e011bd00-949c-11eb-9b67-54c034477f5b.png)

## Who Will Do The Work?

- [x] I am willing to take this on myself. I have a prototype running in my own app.
- [ ] Just putting this out there for someone to pick up.

**Comment by jfversluis** [comment]
Hey @justadaniel good to see that here!

Is there a way we could implement it as a iOS Specific thing, i.e. like this: https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/iOSSpecific

Then we don't need the fallback and things :)

**Comment by justadaniel** [comment]
Sounds good to me @jfversluis!

**Comment by justadaniel** [comment]
> Hey @justadaniel good to see that here!
> 
> Is there a way we could implement it as a iOS Specific thing, i.e. like this: https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/iOSSpecific
> 
> Then we don't need the fallback and things :)

We could, however it doesn't use static classes and is an ImageSource with an IImageSourceHandler. The question I have is would we have a standard OnPlatform specific static class, or just have an ImageSource? Is there a way to have static class platform specific with an ImageSource?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
