### ISSUE TITLE
[Enhancement] Provide ability to start Animations from a Command

### ISSUE THREAD

**Issue by bijington** [xamarin/XamarinCommunityToolkit#1175]
## Summary

Provide the ability to start an Animation from something other than a View. Ideally I want to drive it when deciding whether a page is valid and the user is pressing the submit/save/create button.

## API Changes

Add `AnimateCommand` to `AnimationBehavior` which will be an `ICommand` with a `OneWayToSource` binding.

## Intended Use Case

Rather than disabling a Button based on whether there are validation errors on a Page. I would like to make the invalid controls shake to draw the users attention to the invalid controls. I believe this will serve a much wider set of use cases for being able to drive animations from within a ViewModel. See image below (apologies for my terrible touch screen based handwriting 😄 )

![113418666-d5ccc180-93bd-11eb-8644-ec86ef9321e7](https://user-images.githubusercontent.com/17139988/113712261-d2974580-96dd-11eb-80a5-f3139a216b17.jpeg)

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by bijington** [comment]
Update this was initiated from discussion #1156

**Comment by bijington** [comment]
I have actually completed the development work for this and just need to test it out in the sample app.

**Comment by pictos** [comment]
@bijington thank you for your proposal. Can you expand how it will work? And a code sample?

**Comment by AndreiMisiukevich** [comment]
> @bijington thank you for your proposal. Can you expand how it will work? And a code sample?

I believe, the Command will trigger animation to run (how it's working now when an event is triggered).

**Comment by bijington** [comment]
@pictos of course I can. It is as @AndreiMisiukevich suggested, I would like to trigger the animation by executing a command.

Here is an example based on my previous screenshot. Apologies if it isn't completely syntactically correct.

## The view

```xaml
<Entry Placeholder="WORD 1">
    <Entry.Behaviors>
        <xct:AnimationBehavior AnimateCommand="{Binding AnimateCommand, Mode=OneWayToSource}">
            <xct:AnimationBehavior.AnimationType>
                <xct:ShakeAnimation/>
            </xct:AnimationBehavior.AnimationType>
        </xct:AnimationBehavior>
    </Entry.Behaviors>
</Entry>
            
<Button Text="CREATE WORDSEARCH" Command="{Binding CreateCommand}" />
```

## The ViewModel

```csharp
private void OnCreate()
{
    if (SharedGameValidator.ValidateCategory(this.Category) == false)
    {
        // Make it clear to the user what they need to correct.
        this.AnimateCommand.Execute(null);
        return;
    }
}
```

**Comment by pictos** [comment]
@bijington I'll also mark this as `in-progress` since you will work on this, if anything happens and you can't work on this anymore, please let us know commenting here on this issue. If you need any help don't hesitate to ping us as well.

**Comment by bijington** [comment]
@pictos great thank you for the update and pointers. I followed @AndreiMisiukevich s approach from Expander.

I hope to submit a PR in the next day or so as soon as I have been able to test it out in the sample app. I'm just having some issues connecting a device to my VM.

**Comment by AndreiMisiukevich** [comment]
@bijington yeah, I agree that BindableProperty.CreateReadOnly makes more sense here. Great suggestion @pictos )

**Comment by bijington** [comment]
@AndreiMisiukevich I completely agree too :). I hadn't; realise that option existed until now so I have definitely learned something new today, thanks.

**Comment by bijington** [comment]
@AndreiMisiukevich / @pictos  Quick question: do I need to update any form of documentation to cover this change?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich / @pictos Quick question: do I need to update any form of documentation to cover this change?

I don't think that the documentation exists for this class, but you are welcome to add it if you wish :)
This is appreciated. 

https://github.com/MicrosoftDocs/xamarin-communitytoolkit/tree/master/docs/effects

**Comment by bijington** [comment]
@AndreiMisiukevich great thanks. I will try and fork that repo and see if I can add some valuable documentation 😄
