### ISSUE TITLE
[Enhancement] CancellationToken for Popups

### ISSUE THREAD

**Issue by ArunPrakashG** [xamarin/XamarinCommunityToolkit#1177]
## Summary

The CancellationToken can be passed to the popup from the constructor or through the the INavigation extension overload
`Shell.Current.Navigation.ShowPopup(popup, cancellationToken);`
This way, if the popup only has to be displayed for a specific amount of time, there is no need to handle closing of the popup as it will be handled by the cancellation token internally.

## API Changes

I think by using `cancellationToken.Register(() => Dismiss(default));` on the Popup would make it possible.

## Intended Use Case
An example use case would be where a popup is used to display a timer to the user, when the timer finishes, the popup has to be cancelled. instead of manually cancelling it, using CancellationToken will allow it to cancel itself. Its a Fire and forget system where once its shown, we dont need to be bothered about cancelling it as it can handle it itself with cancellation token.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
