### ISSUE TITLE
[Enhancement] Allow BaseTemplatedView to conditionally select the ControlTemplate

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1178]
## Summary
Currently I don't see a straightforward way using `BaseTemplatedView` to select the `ControlTemplate` conditionally (I could be missing something). Basically the suggested implementation will pass whatever dev sent as parameter to the `BaseTemplatedView`  constructor, to the `TControl` constructor, where the dev will evaluate conditions based on `parameters` and returns the appropriate `ControlTemplate`.
`TControl` could be a simple template with conditions in it constructor where dev omit/add code portions, or it could be seen like `DataTemplateSelector` concept, where dev conditionally returns completely different `ControlTemplate`.

## Implementation
https://github.com/xamarin/XamarinCommunityToolkit/blob/26c9dda6ef1ccc84a0f1fa53134a6888bc1da449/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BaseTemplatedView.shared.cs#L19-L20

Changed to:
```
		public BaseTemplatedView() : this(null)
		{
		}

		public BaseTemplatedView(params object[]? parameters)
			=> InitControlTemplate(parameters);

		public virtual void InitControlTemplate(params object[]? parameters)
		{
			if (parameters == null)
			{
				ControlTemplate = new ControlTemplate(typeof(TControl));
			}
			else
			{
				ControlTemplate = new ControlTemplate(() => { return Activator.CreateInstance(typeof(TControl), parameters); });
			}
		}
```

## API Changes

Changed `BaseTemplatedView`:
- Add a virtual method `InitControlTemplate()`, if you think it's not needed to be virtual it's fine also.
- Add a constructor with parameter `public BaseTemplatedView(params object[]? parameters)`
- Default constructor changed.

## Usage

`MainCardView.cs`
```
public class MainCardView : BaseTemplatedView<MainCardViewTemplate>
{
	public MainCardView()
	{
	}

	public MainCardView(bool aCondition) : base(aCondition)
	{
	}
	...
}
```
`parameters` will be handled by `MainCardViewTemplate` constructor.

Instantiation: 
```
var  mainCardViewInstance = new MainCardView(true) { ... }
var  anotherMainCardViewInstance = new MainCardView() { ... }
```

## Intended Use Case
You have a custom Control/View having multiple control templates and need to set appropriate one upon instantiation time.

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by AndreiMisiukevich** [comment]
Hey @Cfun1 
BaseTemplatedView is a base class for building "cross-platform" controls (like Expander, RangeSlider, AvatarView etc.)
It's not supposed to be used for selecting control templates.

And maybe it makes sense to hide ControlTemplate property somehow

**Comment by Cfun1** [comment]
Exactly what I was using it for, don't you think that building a modular "cross-platform" control may require more than one ControlTemplate depending on some conditions ?

**Comment by AndreiMisiukevich** [comment]
I haven't faced with this scenario yet) So idk

**Comment by pictos** [comment]
> Hey @AndreiMisiukevich , it is exactly what I am using it for, don't you think that building a modular "cross-platform" control may have more than one ControlTemplate and requires to select among them on control init depending on some conditions ?

@Cfun1 does not the DataTemplateSelector solves your issue?

**Comment by Cfun1** [comment]
@pictos I am not sure since I have based my control on `BaseTempaltedView` class from beginning you could take a look at the scenario I am talking about in https://github.com/Cfun1/XamsungHealth/tree/temp/XamsungHealth/Controls/MainCardView https://github.com/Cfun1/XamsungHealth/blob/temp/XamsungHealth.Lib/BaseTemplatedView.cs

**Comment by Cfun1** [comment]
@pictos I am not sure since I have based my control on `BaseTempaltedView` class from beginning you could take a look at the scenario I am talking about in https://github.com/Cfun1/XamsungHealth/tree/temp/XamsungHealth/Controls/MainCardView https://github.com/Cfun1/XamsungHealth/blob/temp/XamsungHealth.Lib/BaseTemplatedView.cs

**Comment by pictos** [comment]
At the end of the day, if we want to customize the `InitControlTemplate` we need to sub-class the BaseTemplated view as you did, so I think there isn't too much value in adding that on our end. Is that makes sense for you?

**Comment by Cfun1** [comment]
BadgeView, AvatarView, ShieldView are already sub classing `BaseTemplatedView` but they are using built-in types as TControl and I guess they have a single `ControlTemplate`, personally I found it helpful in my case (custom TControl  with conditional ControlTemplate) so thought to share it here in case it could be useful for someone else, again I might be missing something.

**Comment by AndreiMisiukevich** [comment]
Just a side note, in your solutions, if I understand it correctly, you should override OnChildRemoved and perform de-initialization as well cuz you change control templates and, I believe, old views are removed when new ones added.

But it's not supposed by XCT BaseTemplatedView...

**Comment by Cfun1** [comment]
@AndreiMisiukevich I didn't get your point regarding overriding `OnChildRemoved` when when is it supposed to be triggered in my case, and what do you mean by "de-initialization".
If you guys are sure it won't be useful to add, then please feel free to close this issue.

**Comment by AndreiMisiukevich** [comment]
@Cfun1 ah, sorry. I guess I didn't get your solution.
So, your proposal is to make it possible to pass parameters to TControl ctor?

**Comment by AndreiMisiukevich** [comment]
I guess for this purpose developers should initialize a "raw" control with parameterless ctor and then override OnControlInitialized and perform any tweaks they want.

I don't insist that my point of view is 100 percent right, but unfortunately, I don't see where/how can I apply it (That's my personal opinion).

**Comment by Cfun1** [comment]
> @Cfun1 ah, sorry. I guess I didn't get your solution.
> So, your proposal is to make it possible to pass parameters to TControl ctor?

Exactly, yes because I have a special card where the property `IsPersistent = true` (means no close button for it) but at the moment when the `ControlTemplate` is assigned, that property which is set in ctor initializer won't be assigned yet, and I don't want to load the button (it's a custom control) anyway and just bind it `IsVisible` property  since I don't need it, in that case. I believe by doing so it's more optimized since I am not loading unnecessary things when not needed  https://github.com/Cfun1/XamsungHealth/blob/daa6ad1cdd89052fc7e4aad359d433f7b8422d51/XamsungHealth/Controls/MainCardView/MainCardViewTemplate.cs#L195-L288

> I guess for this purpose developers should initialize a "raw" control with parameterless ctor and then override  OnControlInitialized and perform any tweaks they want.
> I don't insist that my point of view is 100 percent right, but unfortunately, I don't see where/how can I apply it (That's my personal opinion).

At that point the `ControlTemplate` is already assigned (in other words MainCardViewTemplate() already executed). I totally understand and respect your opinion no issue :)

**Comment by Cfun1** [comment]
I think i have an idea by changing  the current structure where indeed this is not required..i will update tomorrow.

**Comment by Cfun1** [comment]
I tried to sub-class from `BaseTemplatedView<Grid>` and then instantiate `MainCardViewTemplate` inside `OnControlInitialized()`, but I encounter the issue where at that point properties that are used as a condition on how to build the ControlTemplate are not initialized yet, also parameters sent through ctor won't be helpful in that case.

**Comment by Cfun1** [comment]
@AndreiMisiukevich , @pictos any update ?

**Comment by AndreiMisiukevich** [comment]
```csharp


class YourView : Grid {
	public YourView() { } // Just to show, that this view has empty constructor

	public void Init(object parameters) {
		// perform initializaion here
	}
}

class YourTemplatedView : BaseTemplatedView<YourView> {
	readonly object parameters;

	public YourTemplatedView(object parameters) {
		this.parameters = parameters;
	}


	protected override OnControlInitialized(YourView view) {
		view.Init(parameters);
		// Other setup
	}
}
```

How about this approach? You cannot create a view and then initialize it?

**Comment by AndreiMisiukevich** [comment]
Since Activator uses reflection, I'd prefer to avoid using it (Due to performance issues)

**Comment by Cfun1** [comment]
@AndreiMisiukevich 
- On your first comment: I am confused it seems to me a reverse way to do things, should I then create an instance of `YourTemplatedView` when I want to create an instance of `YourView`? knowing that bindable properties are living in `YourView`. I mean what I do expect from the design is to instantiate a `CustomView` and according to the initial values you assign to its bindable properties the appropriate control template is selected, am I wrong?

- The `Activator` won't affect the current TemplatedViews with a single template (will be using the current path null parameters), so it will only get hit if the dev asked for it (and that for a valid reason which is the topic of this issue), any better alternative that could do the job ensured by  `Activator`  in this case?

**Comment by AndreiMisiukevich** [comment]
Frankly speaking, it's never been supposed that BaseTemplatedView will be used outside of XCT (it's not internal because of inheritance issue only).

If other folks think that it's a good idea, then we can accept this proposal though.

@pictos @brminnick @jsuarezruiz please add your input here)

**Comment by Cfun1** [comment]
@jfversluis any thoughts ?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
