### ISSUE TITLE
[Bug] iOS - can't show Popup from a modal page

### ISSUE THREAD

**Issue by michaelb-yambay** [xamarin/XamarinCommunityToolkit#1189]
### Description

On iOS, Navigation.ShowPopup() fails when called from a modally presented Page.  The same scenario works fine on Android.

### Steps to Reproduce

1. Call Navigation.PushModalAsync(new ModalPage()) to show ModalPage
2. On ModalPage, call Navigation.ShowPopup(new CustomPopup()) so show CustomPopup.

### Expected Behavior
Popup should display on iOS as it does on Android

### Actual Behavior
Popup failed to display with error "2021-04-10 12:04:13.936120+0100 XF_PopupModalIssue.iOS[5438:145915] [Presentation] Attempt to present <Xamarin_CommunityToolkit_UI_Views_PopupRenderer: 0x7fcd44e60000> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fcd44c25ba0> (from <Xamarin_Forms_Platform_iOS_PageRenderer: 0x7fcd4711aba0>) which is already presenting <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x7fcd44d42e30>."

### Basic Information

- Version with issue: v1.1.0
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.4
  - Android: v9.0 (API Level 28)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
None discovered

### Reproduction imagery

![Screenshot 2021-04-10 at 12 09 34](https://user-images.githubusercontent.com/39366823/114267819-d553ac80-99f5-11eb-86e9-9286755dae3d.png)

### Reproduction Link
Attached zipped XF solution reproduces the issue
[XF_PopupModalIssue.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6289698/XF_PopupModalIssue.zip)

**Comment by jpacov** [comment]
Experiencing same issue in iOS:
Here my error in console:
................. [Presentation] Attempt to present <Xamarin_CommunityToolkit_UI_Views_PopupRenderer: 0x7fbfb036dfc0> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fbfa9c3de80> (from <Xamarin_Forms_Platform_iOS_PageRenderer: 0x7fbfac02f160>) which is already presenting <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x7fbfb151beb0>.

Hopefully someone finds a workaround :/

**Comment by pictos** [comment]
@ahoefling FYI

**Comment by jpacov** [comment]
Did you find a workaround yet @michaelb-yambay  or anybody?

**Comment by michaelb-yambay** [comment]
@jpacov - I've not found a workaround yet

**Comment by vhugogarcia** [comment]
I'm facing the same issue @jpacov and @michaelb-yambay are sharing here.

Is there any workaround?

**Comment by jfversluis** [comment]
Should be fixed in next release :)
