### ISSUE TITLE
[Feature request] - Rounded corner ContentView

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#12]
_From @Depechie on December 21, 2016 10:16_

See if this can be placed inside an effect http://www.qimata.com/?p=7813

_Copied from original issue: FormsCommunityToolkit/Effects#30_

**Comment by pauldipietro** [comment]
The original link no longer works. We can do a new proposal for this if it's something people would like to see, but this has otherwise not had much movement.
