### ISSUE TITLE
[Enhancement] Add a way to get device's currently selected language

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#1201]
## Summary

XCT provides some great localization features that allow to change app language in runtime, but there is one gap.
If user changes devise language while app is running, there is no easy way to update app's language accordingly.

If user changes device language while app is running, `CultureInfo.CurrentCulture` and other ways to see current culture won't be updated, and continue to return device language that was set during app start.

Also there is no event that Xamarin app can subscribe to, but that's a minor issue since `App.OnStart` will be called on device language change anyway, so it would be great to be able to do something like this:

```cs
protected override void OnStart()
{
    LocalizationResourceManager.Current.CurrentCulture = DeviceInfo.CurrentCulture;
}
```

## API Changes

- `CultureInfo DeviceInfo.CurrentCulture { get; }`

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
