### ISSUE TITLE
[Bug] TabView OnSelectionChanged TabSelectionChangedEventArgs OldPosition is incorrect

### ISSUE THREAD

**Issue by joergpichler** [xamarin/XamarinCommunityToolkit#1208]
### Description

The Property `OldPosition` in the `TabSelectionChangedEventArgs` is always incorrect as it is always the same value as `NewPosition`.

### Steps to Reproduce

1.  Create TabView with at least 2 items
2.  Subscribe to OnSelectionChanged 
3.  Switch Tab

### Expected Behavior

`OldPosition` is reported correctly

### Actual Behavior

`OldPosition` is reported incorrectly. Has always same value as `NewPosition`

### Basic Information

- Version with issue: 1.1.0
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 11

### Reproduction imagery

![grafik](https://user-images.githubusercontent.com/7032094/115155938-5cea8c80-a082-11eb-998f-487590812d20.png)

I had a look in the source code and it seems that in TabView.shared.cs Line 823 `OldPosition = SelectedIndex` must be changed to `OldPosition = oldposition`. But then the issue is with the first switching of tabs `OldPosition` is -1 when it actually is the first tab.

**Comment by albilaga** [comment]
I also have this issue. And also the problem also coming when there is tab that don't have the content. For the repro can see in here https://github.com/albilaga/tabview. When navigating to first tab, `OldPosition` and `NewPosition` will always be 0. When navigating to last tab it will show `OldPosition` = 2 and `NewPosition` to 1 which also incorrect because `NewPosition` should be 2.

**Comment by Huaba93** [comment]
As contentContainer a CarouselView is used. So maybe related to

**Comment by Huaba93** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs#L823

instead of
`OldPosition = SelectedIndex
`

should be
`OldPosition = oldposition
`

**Comment by jamers99** [comment]
I got the same issue, i made the change in this PR: #1361
