### ISSUE TITLE
[Enhancement] Docs

### ISSUE THREAD

**Issue by AlexHedley** [xamarin/XamarinCommunityToolkit#121]
## Summary

Is there a preference on how to document the toolkit?

Would it be ok to use [DocFX](https://dotnet.github.io/docfx/) and host on GitHub Pages?

We can automate the API documentation then have separate Articles written to explain how to use the various components. 

The following Actions can be used in a workflow:

- [GitHub Actions for GitHub Pages](https://github.com/peaceiris/actions-gh-pages) from [peaceiris](https://github.com/peaceiris) - Shohei Ueda

- [docfx-action](https://github.com/marketplace/actions/docfx-action) from [nikeee](https://github.com/nikeee) - Niklas Mollenhauer

Happy to add a PR with this functionality once there’s an initial code commit to work with.

**Comment by SunnyMukherjee** [comment]
I have not used GitHub Pages, but once the authors settle on a path for documentation, I'll be happy to assist in the documentation effort with any approach.

**Comment by jfversluis** [comment]
I think the Windows toolkit has their documentation included in the official Microsoft Docs. If that is a possibility for us as well I think that is the way to go. 

This will have the most discoverability and will have everything in one place.

**Comment by sthewissen** [comment]
Agreed! Taking Xamarin.Essentials as an example (which does something similar I think using docfx) would also fit the project.

https://github.com/xamarin/Essentials/tree/develop/docs/en

**Comment by jfversluis** [comment]
Sorry for the radio silence @AlexHedley! We have a separate repo and actual Docs URL for our documentation and are working on putting something on there and more importantly: have some kind of guide on how to contribute to that.

To be continued...

**Comment by AlexHedley** [comment]
No problem at all, I'll keep an eye out for this and look forward to contributing as soon as possible :)

Shall we just close the PR and use this Issue to track things?

**Comment by jfversluis** [comment]
Keep it open for the time being. You will still have the content as a reference of course, but it's a good indicator for us to remember we need to get an outline like that on the Docs. When we port everything over there we can close it.

Thanks for your support and patience!

**Comment by AlexHedley** [comment]
What do I see here :)

https://github.com/MicrosoftDocs/xamarin-communitytoolkit

**Comment by jfversluis** [comment]
There it is! I think it's safe to start making some changes there, so feel free to port some things over

**Comment by jfversluis** [comment]
OK I think the Docs are well underway and will be an ongoing thing so we don't need this issue to nag us :D
