### ISSUE TITLE
[Enhancement] Provide a possibility to use VariableMultiValueConverter inside MultiConverter

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1217]
## Summary
With the current implementation it's not possible to use a `VariableMultiValueConverter` inside a `MultiConverter`, since the latter requires an object (converter) implementing `IValueConverter` while `VariableMultiValueConverter` does implement `IMultiValueConverter`.

## API Changes
For now I don't see how this could be implemented. I guess it needs some discussion whether the current implementation will get enhaced, or a new converter created, (or idea rejected who knows, maybe I have missed something obvious 😅)

## Intended Use Case
```xml
<x:Double x:Key="ComparingValue">2</x:Double>

<xct:MultiConverter x:Key="MultiConverter">
	<xct:VariableMultiValueConverter ConditionType="Any"/>
	<xct:BoolToObjectConverter FalseOject=Red TrueObject=Green/>
</xct:MultiConverter>

<BoxView Color="{Binding Source={x:Reference slider}, Path=Value, Converter={xct:CompareConverter ComparisonOperator=Greater, ComparingValue={StaticResource ComparingValue}}}"

<BoxView>
        <BoxView.Color>
            <MultiBinding Converter="{StaticResource MultiConverter}">
                <Binding Path="Someththing.IsEnabled" />
                <Binding Source={x:Reference slider}, Path=Value,
                         Converter={xct:CompareConverter ComparisonOperator=Greater, ComparingValue={StaticResource ComparingValue}}} />
            </MultiBinding>
        </BoxView.Color>
</BoxView>
```

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
The presented use case for me was solved by enhancing `VariableMultiValueConverter` to accept `TrueObject` `FalseObject` (instead of the suggestion in the issue) like in [CompareConverter](https://github.com/xamarin/XamarinCommunityToolkit/blob/develop/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/CompareConverter.shared.cs) , would love to contribute with that approach if this will be approved.

**Comment by AndreiMisiukevich** [comment]
@pictos @jfversluis @brminnick ?

**Comment by Cfun1** [comment]
@pictos @jfversluis any thoughts ?

**Comment by pictos** [comment]
TBH I have no idea about the impact of this chsnfe I'll need to do a spike, for the next release

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
