### ISSUE TITLE
[Proposal] Behaviors

### ISSUE THREAD

**Issue by SunnyMukherjee** [xamarin/XamarinCommunityToolkit#122]
## Summary

I think a set of common behaviors would be helpful too in the new toolkit.

## API Changes

I am suggesting just one behavior that I use over and over again in multiple controls.

EventToCommandBehavior

I use the MVVM pattern as much as possible and I like to keep code as minimal as possible in my code-behind class.  If I find a control that has an event but not a corresponding command to handle the particular event, I use this behavior to handle the event in my ViewModel class instead of the code-behind class.

## Intended Use Case

The purpose would be a common set of behaviors to extend multiple types of controls, so please add more common behaviors that you use in your projects.

**Comment by acaliaro** [comment]
Something like https://github.com/davidbritch/behaviors

**Comment by SunnyMukherjee** [comment]
> * Reusable EventToCommandBehavior
>   https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior

Yup, I copy and paste from that page all the time.
