### ISSUE TITLE
[Bug] Shadow Effect

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/XamarinCommunityToolkit#1222]
Hello When i want Use Shadow Effect will show on Label of button!

![image](https://user-images.githubusercontent.com/48956033/115652740-0cee1d00-a343-11eb-9966-b5871518342b.png)

**Comment by Saleh-Software** [comment]
and can i round textbox?

**Comment by themronion** [comment]
Duplicate #988

**Comment by AndreiMisiukevich** [comment]
Closing in favor of #988
