### ISSUE TITLE
[Enhancement] Swipe-to-dismiss for notifications

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#1225]
## Summary

Hi.

Currently there is no way for a user to prematurely dismiss SnackBar notifications. This is a very important feature as users are conditioned to swipe away lingering notifications, and it's impossible to select a time to display that is long enough for the users to read the contents but short enough that the notification won't become bothersome.

Furthermore, no matter how well the position of the notification has been designed it's bound to obscure some form of UI navigation.

Hence I think that swipe-to-dismiss functionality would be an essential enhancement. If it's hard to implement in the meantime I would be completely fine with a small 'X' button in the upper right corner that users could press, or other such mechanism.

Thank you!

**Comment by AndreiMisiukevich** [comment]
@VladislavAntonyuk would you like to implement it?)

**Comment by VladislavAntonyuk** [comment]
Ok, I will take a look.
At least for Android and iOS.

**Comment by maxkoshevoi** [comment]
It's supported on Android out of the box (just open any SnackBar in sample app and swipe left to right on it).

**Comment by Tommigun1980** [comment]
@maxkoshevoi Thank you. Unfortunately the iOS SnackBar/Toast is not dismissible by swipe though :/

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
