### ISSUE TITLE
Touch effect command . Do I have to replace all commands with touch effect one?

### ISSUE THREAD

**Issue by developer9969** [xamarin/XamarinCommunityToolkit#1227]
Hi 
Love this feature!!..
I was planning to add a baseStyle in the appxaml so that all the buttons in the app could have the same touch effect!
However I discovered that the existing command of a button/or any other control no longer works and you have to use the touchEffect.Command.

Is this the case?
this prevents me for having just a single style but I have to apply the touch effect to all the controls individually so that I can change the command to the touch effect one.

Am I missing something here?

Many thanks!

**Comment by Cfun1** [comment]
Hi, for question or general discussion, please opt for the discussion section instead of creating an issue thanks.
Cc @AndreiMisiukevich

**Comment by developer9969** [comment]
will do didnt know

**Comment by developer9969** [comment]
I will close this issue here
