### ISSUE TITLE
[Enhancement] Add tests

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#123]
## Summary

Some of this code can be really easily tested, such as the value converters. We should add some testing to also include in our build/release pipelines.

## Intended Use Case
To improve code quality and help avoid changes breaking other things they shouldn't be breaking.

**Comment by jfversluis** [comment]
Adding blocker label to this. I would like to see as much tests as humanly possible for all the things we have merged now before we go live with this.
