### ISSUE TITLE
[Bug] NRE in DelegateWeakEventManager 

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#1236]
### Description

Not sure how, but once in a blue moon `DelegateWeakEventManager` can throw `System.NullReferenceException` with the stack shown bellow when using `ObservableObject`. 

### Expected Behavior
`SetProperty` doesn't throw NRE

### Actual Behavior
`SetProperty` throws NRE

### Basic Information

- Version with issue: 1.1.0
- Last known good version: Unknown (possibly 1.0.3)
- IDE: 
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Redmi Note 8 pro (android 9)

### Reproduction imagery

```cs
EventManagerService.HandleEvent (System.String& eventName, System.Object& sender, System.Object& eventArgs, System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[Xamarin.CommunityToolkit.Helpers.Subscription]]& eventHandlers)
DelegateWeakEventManager.RaiseEvent (System.Object sender, System.Object eventArgs, System.String eventName)
ObservableObject.OnPropertyChanged (System.String propertyName)
ObservableObject.SetProperty[T] (T& backingStore, T value, System.String propertyName, System.Action onChanging, System.Action onChanged, System.Func`3[T1,T2,TResult] validateValue)

TimetableViewModel.set_TimetableEndHour (System.Double value)
```

```cs
private double _timetableEndHour = 24;
public double TimetableEndHour { get => _timetableEndHour; set => SetProperty(ref _timetableEndHour, value); }
```

**Comment by AndreiMisiukevich** [comment]
Would be great to have a reproduction sample :) If it happens that you find a way of how to reproduce this issue, please let us know. It will help a lot.
Thank you!

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich I just got one crash report with that stack (out of 5000 users). Have no idea, how to reproduce it.
Feel free to close this issue. Just wanted to bring up a possible problem.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I just got one crash report with that stack (out of 5000 users). Have no idea, how to reproduce it.
> Feel free to close this issue. Just wanted to bring up a possible problem.

I don't think we should close the ticket if the problem exists. But need to find how to reproduce it.

**Comment by AndreiMisiukevich** [comment]
Or at least maybe find "suspicious" lines of code.

**Comment by AndreiMisiukevich** [comment]
I wonder, can it happen inside event handlers in your app code?

**Comment by maxkoshevoi** [comment]
> Or at least maybe find "suspicious" lines of code.

Here is the only subscriber: https://github.com/maxkoshevoi/NureTimetable/blob/main/NureTimetable/NureTimetable/UI/Views/Timetable/TimetablePage.xaml#L76

And here's what triggers the event: https://github.com/maxkoshevoi/NureTimetable/blob/main/NureTimetable/NureTimetable/UI/ViewModels/Timetable/TimetableViewModel.cs#L437
