### ISSUE TITLE
[Bug] Expander does not expand on content size changes

### ISSUE THREAD

**Issue by Jogge** [xamarin/XamarinCommunityToolkit#1248]
### Description

Ironically the `Expander` does not expand when content size is changed...

![image](https://user-images.githubusercontent.com/15981279/116547807-a6916d80-a8f3-11eb-9eab-b283f88a935a.png)
![image](https://user-images.githubusercontent.com/15981279/116547841-b446f300-a8f3-11eb-88b3-9ac81a4f1805.png)

### Steps to Reproduce

1. Initialize the `Expander` in a view with some content
2. On some event make the content larger
3. You'll now see that the last content of the `Expander` is cut off

### Expected Behavior
Resize on content size changed, just as a `StackLayout` would do.

### Actual Behavior
No resizing and overflowed content is cut off.

### Basic Information

- Version with issue: Xamarin.CommunityToolkit (1.1.0)
- Platform Target Frameworks: .NET Standard 2.1
- Android: 8.1.0

### Reproduction Code

View:
```XAML
<?xml version="1.0" encoding="utf-8"?>

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:views="http://xamarin.com/schemas/2020/toolkit"
             x:Class="ExpanderBug.MainPage">

    <StackLayout>
        <views:Expander IsExpanded="True">
            <StackLayout>
                <Label Text="Hello" />
                <Label x:Name="World" Text="World" IsVisible="False" />
                <Button Text="Expand me" Clicked="Button_OnClicked" />
            </StackLayout>
        </views:Expander>
    </StackLayout>

</ContentPage>
```

Code-behind:
```C#
using System;

namespace ExpanderBug
{
    public partial class MainPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        private void Button_OnClicked(object sender, EventArgs e)
        {
            World.IsVisible = true;
        }
    }
}
```

**Comment by AndreiMisiukevich** [comment]
Hello @Jogge 
Please read the documentation before reporting "bug". 
https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/expander#resize-an-expander-at-runtime

you should call ```ForceUpdateSizeCommand``` or ```ForceUpdateSize``` metod

**Comment by Jogge** [comment]
@AndreiMisiukevich Thank you for the link to the workaround. I have successfully implemented the workaround.

I still think it is a bug, since it does not what I was expecting... But it is not up to me to decide how the behavior should be. In my opinion it is not obvious that you must call a method to get the `expander` to expand.

**Comment by AndreiMisiukevich** [comment]
@Jogge thanks for your feedback.

> you must call a method to get the expander to expand.

You needn't have to call this method if your expander's content size is not a dynamic value (I believe, it works like that in most cases).

But if you wish to change content size "on the fly", then yes, you should call this method because the expander remains the content size from **1st** expanding and then saves times for recalculation it all next times.
