### ISSUE TITLE
[Bug] SideMenuView MainViewScaleFactor does not work correctly

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#1249]
### Description
MainViewScaleFactor reduce or increment the size of the MainView.
If you use a value less than 0, the size is smaller, otherwise bigger.
When you use a rightMenuView, you have a reversed situation (values > 0 = size is smaller).
@AndreiMisiukevich  knows the problem
### Steps to Reproduce

1. Use a SideMenuView with MainViewScaleFactor and RightMenuView
2. 
3. 

### Expected Behavior
MainView size should be smaller when MainViewScaleFactor < 0
### Actual Behavior
MainView size is greater than original

### Basic Information

- Version with issue: 1.1.0
- Last known good version: unknown
- IDE: VS 2019 16.9.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:  11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Cfun1** [comment]
You meant when the 0 < value < 1 it's smaller and if >1 it's bigger? (same behavior as Scale property on VisualElements)

**Comment by AndreiMisiukevich** [comment]
There is a bug is scale calculation for Right menu (with negative value). It should be fixed
Behavior should be consistent for both Left & Right menus (As it is working for left menu now)

**Comment by acaliaro** [comment]
> You meant when the 0 < value < 1 it's smaller and if >1 it's bigger? (same behavior as Scale property on VisualElements)

0<x<1 = smaller x>1 = bigger with leftMenuview
0<x<1 = bigger x>1 = smaller with rightMenuview

**Comment by Cfun1** [comment]
@acaliaro Thanks for the clarification :)
