### ISSUE TITLE
[Bug] Compiling XCT-Popups-Samples causes a Invalid Cast Exception in UWP Native Compilation

### ISSUE THREAD

**Issue by inforithmics** [xamarin/XamarinCommunityToolkit#1251]
### Steps to Reproduce

1. Get https://github.com/ahoefling/XCT-Popups-Samples
2. Set To Release / x64 and select UWP as startup
3. Start Project (Clicking on the Button causes a crash)

### Expected Behavior

Does not crash in the Native Compiled UWP app

### Actual Behavior

Does crash

### Basic Information

- Xamarin Community Toolkit Version UWP Version 1.1.0

### Workaround
Only start in Debug Mode

### Pull Request

This Checkin Fixes it

https://github.com/xamarin/XamarinCommunityToolkit/pull/1247/commits/e85895d4ab1d223d136c4b86ab374267193bcf66

**Comment by brminnick** [comment]
@ahoefling Can you confirm this?

**Comment by ahoefling** [comment]
I'm on family leave until June, won't be able to look at this until then

**Comment by phandcock** [comment]
Hi, this is an issue with my UWP store app.  I have put in a workaround to ignore the InvalidCastException until it is fixed.

**Comment by pictos** [comment]
@phandcock can you share your workaround?

**Comment by phandcock** [comment]
Workaround is too strong a term.  More like, swallow the exception and accept that the popup will not be displayed.  A pain but I am not good enough to fix it myself.

The code is:

 try
                {
                    DataLog.PopupDismissFlag = false;

                    // TODO Ignore exception. See https://github.com/xamarin/XamarinCommunityToolkit/issues/1251
                    var popup = new MessageLog();

                    var t = Application.Current.MainPage.Navigation.ShowPopupAsync(popup);
                }
                catch (InvalidCastException)
                {
                    // TODO fix UWP Release issue until fixed
                }

**Comment by inforithmics** [comment]
In the pull https://github.com/xamarin/XamarinCommunityToolkit/pull/1247 request I discovered this exact problem 

And this commit "fixes" the problem 

https://github.com/xamarin/XamarinCommunityToolkit/pull/1247/commits/e85895d4ab1d223d136c4b86ab374267193bcf66

I think the underlaying problem is a Code Optimization Bug in in the Native Compiler.

**Comment by inforithmics** [comment]
The nuget with this fix can be downloaded here

https://dev.azure.com/xamarin/public/_build/results?buildId=40249&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by phandcock** [comment]
It works!  You sir, as my father would have said, are a gentleman and a scholar.

I am setting up a new release now.  Thank you.

**Comment by ahoefling** [comment]
@brminnick @inforithmics 
Thanks for being patient while I was away on family leave. I have commented my thoughts on the PR. Thanks for all the investigation on this issue, seems like UWP is doing some funky things in release mode

**Comment by phandcock** [comment]
Still seems to be an issue in Release 1.2 which is not unexpected as its still open and not referenced in the Release notes :-)
