### ISSUE TITLE
[Bug] AsyncCommand with allowsMultipleExecutions does not disable

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#1255]
### Description

I have a button "logout"
```
                <Button
                    Command="{Binding LogoutCommand}"
                    IsEnabled="{Binding IsLoggedIn}"
                    Text="{x:Static resource:AppResource.Logout}" />
```

With this LogoutCommand
`            LogoutCommand = new AsyncCommand(LogoutAsync, allowsMultipleExecutions: false);
`
and LogoutAsync

```
 async Task LogoutAsync()
        {
            try
            {

                if (await Application.Current.MainPage.DisplayAlert(AppResource.Attenzione, AppResource.ConfermiLogout, AppResource.Si, AppResource.No))
                {


                    IsLoggedIn = false;
                }

            }
            catch (Exception ex)
            {
                await Utility.Utility.DisplayAlertAsync(AppResource.Errore, ex.Message, "LoginAsync");
            }
        }
```

When I press the button to logout, IsLoggedIn is set to false but the button is not disabled.
I think the problem is `allowsMultipleExecutions: false`
If I use `allowsMultipleExecutions: true`, the button is disabled when IsLoggedIn = false

@brminnick 

https://github.com/xamarin/Xamarin.Forms/issues/2758#issuecomment-831019583

### Steps to Reproduce

See above

### Expected Behavior
The button should disable following IsLoggedIn value

### Actual Behavior
The button is not disabled when IsLoggedIn is set to false

### Basic Information

- Version with issue: 
- Last known good version: 1.1.0
- IDE: VS2019 Versione 16.9.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:   11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: XF 5.0.0.2012
- Affected Devices:

### Workaround

Set `allowsMultipleExecutions`: to true

**Comment by workgroupengineering** [comment]
```xaml
                <Button
                    Command="{Binding LogoutCommand}"
                    CommandParamerter="{Binding IsLoggedIn, Mode=OneWay}"
                    Text="{x:Static resource:AppResource.Logout}" />
```

```csharp
LogoutCommand = new AsyncCommand(LogoutAsync
       , param => param is bool isLogged && isLogged == true
       , allowsMultipleExecutions: false);
```

**Comment by acaliaro** [comment]
> ```
>                 <Button
>                     Command="{Binding LogoutCommand}"
>                     CommandParamerter="{Binding IsLoggedIn, Mode=OneWay}"
>                     Text="{x:Static resource:AppResource.Logout}" />
> ```
> 
> ```cs
> LogoutCommand = new AsyncCommand(LogoutAsync
>        , param => param is bool isLogged && isLogged == true
>        , allowsMultipleExecutions: false);
> ```

Grazie @workgroupengineering 
is this the correct way?

**Comment by workgroupengineering** [comment]
Yes

**Comment by acaliaro** [comment]
Thanks!

**Comment by themronion** [comment]
@acaliaro btw you can use the translation extension from the toolkit instead of x:Static approach to change the language on the fly

**Comment by acaliaro** [comment]
> @acaliaro btw you can use the translation extension from the toolkit instead of x:Static approach to change the language on the fly

Thanks I know. this is a single language app... Maybe I will use the toolkit in the future. Thanks!
