### ISSUE TITLE
UtcToLocalDateTimeConverter?

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/XamarinCommunityToolkit#1260]
Do we have a UtcToLocalDateTimeConverter in the library if not is this something we can consider adding?

**Comment by AndreiMisiukevich** [comment]
Hi @LeoJHarris 
Currently we have only such one https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/DateTimeOffsetConverter.shared.cs

I guess we can add UtcToLocalDateTimeConverter (small note: string format parameter should be used for displaying value if passed)

**Comment by LeoJHarris** [comment]
I thought something like this might suffice

```csharp
public class UtcToLocalDateTimeConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (parameter is string dateTimeFormat)
            {
                if (value is DateTimeOffset dateTimeOffset)
                {
                    return dateTimeOffset.UtcDateTime.ToLocalTime().ToString(dateTimeFormat);
                }
                if (value is DateTime dateTime)
                {
                    return dateTime.ToLocalTime().ToString(dateTimeFormat);
                }
            }
            return string.Empty;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

Would accept DateTimeOffset and DateTime types.

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris 
Then this converter should have name "UtcDateTimeToLocalStringConverter" or something similar
Also, we should return a proper value if dateFormat is not provided as well.

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich have implemented the converter will PR shortly for review

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich @jfversluis first time PR, can you kindly advise the target branch to PR for a new Converter. Thanks

**Comment by LeoJHarris** [comment]
As a side note I couldn't get the unit tests to run for `TestCaseSource`, kept getting following:

```csharp
unit test system.collections.generic.list could not be loaded
```

Not sure if environment issue on my end.

**Comment by jfversluis** [comment]
Merged
