### ISSUE TITLE
[Bug] Toucheffect raised when scrolling

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/XamarinCommunityToolkit#1261]
### Description

The touch effect is raised, when the user only want to scroll the control with the attached effect.
All infos about the issue are in the comments of the Pull Request. Starting at comment: https://github.com/xamarin/XamarinCommunityToolkit/pull/566#issuecomment-790958712
 

### Expected Behavior
Touch effect should only raised it not scrolling, like ListView or CollectionView items.

### Actual Behavior
Touch effect is raised on scrolling

### Basic Information

- Version with issue:
- Last known good version: 1.1.0
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
@AlleSchonWeg hi
Is it on Android, right?

**Comment by AlleSchonWeg** [comment]
Hi @AndreiMisiukevich ,

i have only a Simulator for iOS, but it looks like the same problem with scrolling.

And some other thing happens. The item stays in "touched" mode. I created a video. The labels are greyed out sometimes:

https://user-images.githubusercontent.com/6727366/117143260-ed2e0e80-adb0-11eb-8ca3-6f27f6ef0ca2.mp4

**Comment by IeuanWalker** [comment]
@AndreiMisiukevich Might want to take a look at the platform implementation of this - https://github.com/IeuanWalker/Xamarin.Forms.StateButton

I'm not sure how the effects are implemented, but with this control 'Pressed' and 'Released' events are always raised _(even when scrolling)_, but 'Clicked' event is only raised when the user clicks, but doest get raised when scrolling a list.

**Comment by AndreiMisiukevich** [comment]
If you know how to fix that, then feel free to submit PR

**Comment by themronion** [comment]
Yeap, +1 here, also noticed this recently

**Comment by RenegadeVile** [comment]
This occurs with ScrollViews as well. Any View I add TouchEffect.NativeAnimation to will have that animation triggered when scrolling and I happen to start the scroll with a tap over said View.

**Comment by Seuleuzeuh** [comment]
Settings the xct:TouchEffect.DisallowTouchThreshold to 1 did the trick for me, using the NormalBackgroundColor and PressedBackgroundColor. And also with the LongPressCommand. All of that in elements of a CollectionView.

**Comment by mphill** [comment]
This may be related, but I want to make sure @AndreiMisiukevich is aware.  With the IsToggle property, on iOS Scrolling (In a ScrollView) will randomly stop working with IsToggle is triggers.  It like the control gets stuck into thinking it's pressed so scrolling stops.

I can reproduce this pretty reliably.  

I switched to using a real Button that appears to have resolved my issue.

**Comment by isness** [comment]
I tried playing with this, but nothing works. Latest CF, Collection view. I'd really like to apply any kind of touch effect on a single line without having it triggered while scrolling :(

**Comment by jfversluis** [comment]
We believe this might be fixed in https://github.com/xamarin/XamarinCommunityToolkit/releases/tag/2.0.6

If not, please let uw know, open a new issue and link this one. Thanks!
