### ISSUE TITLE
[Bug] XCT Media Element Crashes App

### ISSUE THREAD

**Issue by Painwraith** [xamarin/XamarinCommunityToolkit#1268]
### Steps to Reproduce

1. Download XCT Sample Application
2. Navigate to any page with Media Element
3. Quickly leave and re-enter that page several times

### Expected Behavior
The application continues to stay active.
### Actual Behavior
The application crashes.
### Basic Information
Tested and easily reproducible on Android. 

- Version with issue:  XCT v1.1.0
- Last known good version: n/a
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 
  - Android 11.0 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: XCT v1.1.0
- Affected Devices:

### Reproduction imagery

![image](https://user-images.githubusercontent.com/34556316/117474005-289b1b00-af20-11eb-95e3-a73cecf24856.png)

**Comment by pictos** [comment]
@Painwraith 
Could you attach a small repro?

**Comment by jfversluis** [comment]
Did you only test this on Android or also iOS by any chance?

**Comment by Painwraith** [comment]
I only tested on Android. I could attach a small repo, but this is reproducible in the XCT Sample that is part of this repo.

**Comment by jfversluis** [comment]
If I may ask, what is the use-case of switching a lot back and forth? It seems like you have to do it pretty quickly to encounter this. Still something that might need fixing, but trying to figure out how likely it is someone will encounter this with normal use

**Comment by Painwraith** [comment]
Honestly, you can get this to crash an app but clicking on the page once and off the page once. It is pretty severe. Someone just surfing an application casually can crash their app with this bug.

**Comment by YannSoulier** [comment]
Hi ! I have the same issue when I want to open a page containing videos, the app crashes on Android. I tested on iOS, the page loads, I can play videos but once I press the back button the app crashes.
If you have any workaround i'm interested.

**Comment by Painwraith** [comment]
Hello. Your app should not be crashing purely from opening a page with video. The bug I was describing occurs when you navigate to a page with XCT Media Element and then quickly leave the page it will crash. My work around has been to put the XCT Media Element behind a tab on the page, so it will not attempt to load it immediately if someone navigates to the page and quickly navigates away. It has effectively eliminated the crashes, but I had to change my UI presentation of content and I was not ideal.

**Comment by afnsvdan** [comment]
@jfversluis I have the same issue, how can I Dispose() XCT Media element when leaving the page?

**Comment by anvuks** [comment]
I believe this was fixed in #1870

**Comment by bijington** [comment]
Yes it looks like you are right @anvuks thanks.
