### ISSUE TITLE
[Enhancement] Support for iOS UIAccessibilityCustomActions

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/XamarinCommunityToolkit#1280]
## Summary

Add support for declaring [UIAccessibilityCustomActions](https://developer.apple.com/documentation/uikit/uiaccessibilitycustomaction).

[More info](https://www.raywenderlich.com/4720178-ios-accessibility-tutorial-making-custom-controls-accessible).

## API Changes

The goal is to allow XAML like the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ios="clr-namespace:Xamarin.CommunityToolkit.PlatformConfiguration.iOSSpecific"
             x:Class="Bug.MainPage"
             x:Name="Root">
    <StackLayout>
        <StackLayout BindableLayout.ItemsSource="{Binding Items}">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding Title}">
                        <ios:Semantic.CustomActions>
                            <ios:CustomAction
                                Text="Lengthen title"
                                Command="{Binding BindingContext.LengthenTitleCommand, Source={x:Reference Root}}"
                                CommandParameter="{Binding}" />
                            <ios:CustomAction
                                Text="Shorten title"
                                Command="{Binding ShortenTitleCommand, Source={RelativeSource AncestorType={x:Type bug:MainViewModel}}}"
                                CommandParameter="{Binding}" />
                        </ios:Semantic.CustomActions>
                    </Label>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>
    </StackLayout>
</ContentPage>
```

It is to be implemented using some platform specific bindable properties and an effect.

There is a working implementation here based on code I'm already using:

https://github.com/GalaxiaGuy/xf-bugs/tree/experiment/accessibility/Bug

## Intended Use case

Custom actions are a useful feature on iOS for improving accessibility. Items with one or more custom actions defined allow the user to swipe up or down to iterate through the available actions. iOS cells using the native editable functionality are implemented using this for instance.

[More info](https://www.raywenderlich.com/4720178-ios-accessibility-tutorial-making-custom-controls-accessible).

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

## Other stuff

One of the key requirements is that the custom actions can bind to all of the following:
* Element's `BindingContext`
* Other elements directly via `x:Reference`
* Other things via `RelativeSource`

This is made possible using a subclass of `ObservableCollection`, that may be useful outside of this feature for people who want to make collection valued attached properties that support the three bullet points above:

 ```csharp
public class XamlCollection<T> : ObservableCollection<T>
        where T : BindableObject
{
    public Element Owner { get; }

    public XamlCollection(Element bindable)
    {
        Owner = bindable;
        Owner.BindingContextChanged += BindableBindingContextChanged;
    }

    private void BindableBindingContextChanged(object sender, EventArgs e)
    {
        foreach (var item in this)
        {
            BindableObject.SetInheritedBindingContext(item, Owner?.BindingContext);
        }
    }

    private void UpdateItem(T item)
    {
        BindableObject.SetInheritedBindingContext(item, Owner?.BindingContext);
        NameScope.SetNameScope(item, NameScope.GetNameScope(Owner));
        if (item is Element element && Owner is Element parent)
        {
            element.Parent = parent;
        }
    }

    private void ClearItem(T item)
    {
        BindableObject.SetInheritedBindingContext(item, null);
        NameScope.SetNameScope(item, null);
        if (item is Element element && element.Parent == Owner)
        {
            element.Parent = null;
        }
    }

    protected override void InsertItem(int index, T item)
    {
        UpdateItem(item);
        base.InsertItem(index, item);
    }

    protected override void SetItem(int index, T item)
    {
        UpdateItem(item);
        base.SetItem(index, item);
    }

    protected override void RemoveItem(int index)
    {
        var item = this[index];
        ClearItem(item);
        base.RemoveItem(index);
    }

    protected override void ClearItems()
    {
        foreach (var item in this)
        {
            ClearItem(item);
        }
        base.ClearItems();
    }
}
```

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
