### ISSUE TITLE
[Enhancement] Kanban Board control

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#1281]
## Summary

Create new kanban board control.
It should allow
- Add columns 
- Delete columns
- Add cards
- Delete cards
- Drag and drop cards between columns 
- Support WIP limit

Example: https://vladislavantonyuk.azurewebsites.net/articles/Creating-Kanban-Board-using-Xamarin-Forms-5

## Intended Use Case
- Any task tracking system

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
