### ISSUE TITLE
[Enhancement] Diagram control

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#1282]
## Summary

Create a new control which allows us to build a diagram.
It should allow 
- add any shape to the board
- All shapes can be moved
- all shapes should contain connectors
- allow to draw arrow between connectors
- arrow annotations

## Intended Use Case
Flowchart diagram for commands execution.

Blazor example: https://github.com/VladislavAntonyuk/Blazor.Diagrams

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
