### ISSUE TITLE
[Enhancement] Add sample app

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#129]
## Summary

We need to add a (good looking!) sample app that shows all the stuff that is in the library. Additionally, add in the PR template and CONTRIBUTING.md that people are required to add a sample page for their new functionality as well as tests.

**Comment by AndreiMisiukevich** [comment]
@jfversluis can be closed, right?

**Comment by jfversluis** [comment]
We have a sample app which should just be evolving together with our codebase, so I think this can be closed for now
