### ISSUE TITLE
AvatarView crashes if generic style is defined in App.xml

### ISSUE THREAD

**Issue by Pankajgangwar613** [xamarin/XamarinCommunityToolkit#1292]
### Steps to Reproduce

1.  
```xaml
<Style ApplyToDerivedTypes="True" TargetType="xct:AvatarView">
            <Setter Property="Size" Value="40" />
            <Setter Property="Color" Value="Transparent" /> 
        </Style>
```
2. 
3. 
i am using up to date nuget package
AvatarView not working  in android platform app is crash when define xct:Avatar view  in app.xaml for Style

Crash error of my system
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Please share some more details as requested by the template, thanks

**Comment by Pankajgangwar613** [comment]
define in app.xaml
<Style ApplyToDerivedTypes="True" TargetType="xct:AvatarView">
            <Setter Property="Size" Value="40" />
            <Setter Property="Color" Value="Transparent" /> 
        </Style>
```
define in MainPage
2.    <xct:AvatarView />

this is  mre details ,  thanks

**Comment by pictos** [comment]
@Pankajgangwar613 
Could you attach a small repro? That way we can debug it faster. Thanks in advance

**Comment by AndreiMisiukevich** [comment]
Verified. The issue exists.
Working on fix
