### ISSUE TITLE
[Bug] ShadowEffect's shadow doesn't follow button's perimeter

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#1298]
Continuation of: #988

### Description

Shadow effect adds rectangular shadow even to buttons with rounded corners

### Steps to Reproduce

Add shadow effect to any rounded button

### Expected Behavior

Rounded shadows for rounded buttons 

### Actual Behavior

Rectangular shadows for rounded buttons

### Basic Information

- Version with issue: 1.2.0-pre2
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Use different NuGet for shadow needs

### Reproduction imagery

![image](https://user-images.githubusercontent.com/6609929/118381753-e8f6c200-b5f6-11eb-9fcb-60c5a75319c2.png)
![image](https://user-images.githubusercontent.com/6609929/118381757-ed22df80-b5f6-11eb-97aa-8218150a9a7b.png)

**Comment by AndreiMisiukevich** [comment]
@maxkoshevoi Thanks)
