### ISSUE TITLE
[Enhancement] Floating label entry

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#1309]
It would be nice to have something like this:
https://trailheadtechnology.com/building-a-floating-label-entry-with-xamarin-forms/

**Comment by jfversluis** [comment]
Looks cool! Not sure if @vecalion is willing and able to talk to us and see what we can do? :)

**Comment by vecalion** [comment]
@jfversluis I use XCT in all of my projects. If there is a way I can help, I'm all yours :)

**Comment by ankitgupta2oct** [comment]
New to the contribution world but I want to help here.

**Comment by pictos** [comment]
I believe that we can do it using the XF.Material package... Or am I missing something here?

**Comment by angelru** [comment]
@pictos  any example?

**Comment by pictos** [comment]
@angelru 
https://youtu.be/9ZAaffkSZ1Q

**Comment by lee-m** [comment]
I have an implementation of a floating label entry that I created for the app I work on. Is there still interest in having this part of XCT? If so I can see about trying to get it in shape to get a PR submitted.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
