### ISSUE TITLE
[Bug] CameraView crashing when snapping picture with FlashMode set to Torch

### ISSUE THREAD

**Issue by matteovelati** [xamarin/XamarinCommunityToolkit#1314]
### Description
When using Torch flash mode in a camera view, I'm unable to snap pictures without crashing.

### Steps to Reproduce

1. Create a CameraView with CaptureMode="Photo", CameraOptions="Back", FlashMode="{Binding CameraFlashMode}"
2. Toggle a button to switch from FlashMode="Off" to FlashMode="Torch"
3. Snap a picture

### Expected Behaviour
I expect to snap a photo having the flash always on (aka Torch mode)

### Actual Behavior

The flash mode changes correctly, but when I try to take a photo I get the following exception:

_Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: *** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] flashMode must be set to a value present in the supportedFlashModes array_

### Basic Information

- Version with issue: 1.0.2, 1.2.0 pre-2
- Last known good version:  na
- IDE: VisualStudio 2019 for Mac
- Platform Target Frameworks: 
  - iOS:  14.4
- Nuget Packages: Xamarin.Forms 5.0.0.2012, Xamarin.Essentials 1.6.1, NETStandardLibrary 2.0.3, Network.Json 13.0.1
- Affected Devices: iPhone 6s

**Comment by GUOLDEV** [comment]
@jfversluis @pictos I have created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1522) to fix the reported issue with CameraView. Could you please have a look?

**Comment by AndreiMisiukevich** [comment]
Fixed in #1522

**Comment by GUOLDEV** [comment]
Thanks @AndreiMisiukevich 👍
