### ISSUE TITLE
[Enhancement] Add Popup Support for macOS

### ISSUE THREAD

**Issue by KeithBoynton** [xamarin/XamarinCommunityToolkit#1320]
When trying to use the new Popup control in XCT 1.1.0 like this:

`Navigation.ShowPopup(new TestPopup());`

The following exception is raised.

`The current platform 'macOS' does not support Xamarin.CommunityToolkit.BasePopup`

I'm aware there was a similar issue for UWP that could be resolved by targeting it correctly at a specific SDK: https://github.com/xamarin/XamarinCommunityToolkit/issues/889

I wondered if it's possible there is a similar fix for macOS but I'm also aware that macOS often doesn't get the love it really should in Xamarin and maybe it truly isn't supported?

**Comment by AndreiMisiukevich** [comment]
@VladislavAntonyuk could you please address this question?) :) Thanks

**Comment by AndreiMisiukevich** [comment]
@ahoefling could you please address this question?) :) Thanks

**Comment by AndreiMisiukevich** [comment]
Yes, as I see, currently we don't have a macOs popup renderer.
Feel free to contribute it 👍

**Comment by ahoefling** [comment]
AFAIK macOS is not a supported platform. I believe the APIs are very similar between iOS and macOS so it may be able to use the same renderer.

**Comment by jfversluis** [comment]
Like the message (and comments in here) say: not supported atm. Turning this into a feature request, anyone who is up for it can contribute this!

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
