### ISSUE TITLE
[Enhancement] ValidationGroupBehavior

### ISSUE THREAD

**Issue by GuidoNeele** [xamarin/XamarinCommunityToolkit#1327]
## Summary

A behavior to validate multiple validation behaviors. When all validations have passed IsValid on the group validation will be true. Handy for enabling a button only when all validations have passed.

## API Changes

- **Behaviors\Validators\ValidationGroupBehavior.cs** (new file) 
Groups all validation behaviors and checks if all validations have passed.
- **Behaviors\Validators\ValidationBehavior.cs** (modification) 
Add Group property and fill the group with the validation on attach and remove it on detatching

```xaml
<StackLayout>
    <StackLayout.Behaviors>
      <xct:ValidationGroupBehavior x:Name="ValidationGroup" />
    </StackLayout.Behaviors>

    <Label Text="Name (required):" />
    <Entry Placeholder="e.g. John Doe">
      <Entry.Behaviors>
        <xct:CharactersValidationBehavior Flags="ValidateOnAttaching,ValidateOnValueChanging"
                                          Group="{Reference ValidationGroup}"
                                          MinimumCharacterCount="3" />
      </Entry.Behaviors>
    </Entry>

    <Label Text="Email (required):" />
    <Entry Placeholder="e.g. john@doe.com">
      <Entry.Behaviors>
        <xct:MultiValidationBehavior Group="{Reference ValidationGroup}">
          <xct:CharactersValidationBehavior MinimumCharacterCount="3" />
          <xct:EmailValidationBehavior />
        </xct:MultiValidationBehavior>
      </Entry.Behaviors>
    </Entry>

    <Label Text="Fill in all fields before button is enabled" />
    <Button x:Name="SubmitButton" IsEnabled="{Binding Source={Reference ValidationGroup}, Path=IsValid}">
      <Button.Triggers>
        <DataTrigger Binding="{Binding IsEnabled, Source={Reference SubmitButton}}" TargetType="Button" Value="True">
          <Setter Property="BackgroundColor" Value="Green" />
          <Setter Property="Text" Value="All valid" />
        </DataTrigger>
        <DataTrigger Binding="{Binding IsEnabled, Source={Reference SubmitButton}}" TargetType="Button" Value="False">
          <Setter Property="BackgroundColor" Value="Red" />
          <Setter Property="Text" Value="Invalid" />
        </DataTrigger>
      </Button.Triggers>
    </Button>
</StackLayout>
```

## Intended Use Case
To validate a group of validations at once. E.g. to enable a button when all validations have passed.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

I've got a PR standing by if you like it.

https://github.com/GuidoNeele/XamarinCommunityToolkit/commit/6697da01b00d3ff3a289abe8825f846fe6cb3f83

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
