### ISSUE TITLE
[Discussion] Implement IMarkupExtension in converters

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#133]
## Summary

By also making our converters implement `IMarkupExtension` we achieve some more freedom in implementing additional properties to handle common scenarios, as partly discussed in #130.

## API Changes

Implement `IMarkupExtension` in converters that have a need for it.

**Comment by AndreiMisiukevich** [comment]
I think this is a very good idea!

**Comment by AndreiMisiukevich** [comment]
Implemented in #139
