### ISSUE TITLE
[Bug] Localization. Picker "Cancel" doen't change after changing other languages.

### ISSUE THREAD

**Issue by Midnayt** [xamarin/XamarinCommunityToolkit#1333]
### Description
If device language is different than that selected it doesn't effect on Picker's "Cancel"
### Steps to Reproduce

1. Run sample
2. Go to Settings and change lang to Spanish
3.  Open picker

### Basic Information

- Version with issue:1.1.0
- Last known good version: unknown
- IDE: VS 19 (Version 16.9.6)
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0;10,0

### Reproduction imagery

![Screenshot_1621882088](https://user-images.githubusercontent.com/31686881/119393564-cab95200-bcd9-11eb-99b6-04bdb7459c75.png)
![Screenshot_1621882096](https://user-images.githubusercontent.com/31686881/119393566-cbea7f00-bcd9-11eb-9a7d-f9e8bf1fbb6c.png)

### Reproduction Link

https://github.com/xamarin/XamarinCommunityToolkit/tree/main/samples

**Comment by jfversluis** [comment]
Thank you for reporting @Midnayt ! However this is not a bug. The cancel button is a button that is translated by the OS, you should do extra configuration on the app to make that work. For the sample app we didn't do that, we only translate a couple of labels to show how our translation mechanism works. :)

**Comment by Midnayt** [comment]
> 
> 
> Thank you for reporting @Midnayt ! However this is not a bug. The cancel button is a button that is translated by the OS, you should do extra configuration on the app to make that work. For the sample app we didn't do that, we only translate a couple of labels to show how our translation mechanism works. :)

What about other controls which have OS translation(f.e. DatePicker)? Does it mean, that your translation works partially and need extra implementation for full translation(didn't see any warnings about this limitation)?
