### ISSUE TITLE
[Enhancement] [CameraView] Implement camera controls such as focus and exposure

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1334]
## Summary

 Implement camera controls such as a focus on tap, exposure, etc, like in the [MediaPlugin](https://github.com/jamesmontemagno/MediaPlugin) TakePhotoAsync or in the [ManualCameraControls](https://github.com/xamarin/ios-samples/tree/main/ManualCameraControls) as a reference.

![image](https://user-images.githubusercontent.com/22019245/119453550-e1fc4c00-bd7a-11eb-95fd-7e1d548e0421.png)

## API Changes

Implement camera properties:

- FocusMode;
```
public CameraFocusMode FocusMode { get; set; }

public enum CameraFocusMode
{
    Locked,
    AutoFocus,
    ContinuousAutoFocus
}
```
- ExposureMode;
```
public CameraExposureMode ExposureMode { get; set; }

public enum CameraExposureMode
{
    Locked,
    AutoExpose,
    ContinuousAutoExposure,
    Custom
}
```

## Intended Use Case

Allow the application to take control of the following camera features:

- Focus;
- Exposure;
 
A simple example of how to use FocusMode:

The application is able to turn on/off the camera auto focus.

![image](https://user-images.githubusercontent.com/22019245/120907032-8ba7db00-c6a1-11eb-9979-560bd8ef0a45.png)

![image](https://user-images.githubusercontent.com/22019245/120907054-c7db3b80-c6a1-11eb-98d2-05252a2bf302.png)

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by GUOLDEV** [comment]
Hi @conceptdev, I am happy to work on this issue, but I would like to ask you if it is achievable.

**Comment by davidbritch** [comment]
Hi @GUOLDEV 

I think you need to speak to @jfversluis

**Comment by GUOLDEV** [comment]
Hi @davidbritch , thanks for the prompt reply, I edited the comment adding @jfversluis as well 👍

**Comment by pictos** [comment]
@GUOLDEV  Do we have references for this feature across other platforms?

**Comment by GUOLDEV** [comment]
@pictos it's available for iOS and Android, I will need to confirm for other platforms

**Comment by jfversluis** [comment]
Seems definitely good to have! Let us know how you would implement this in code. What properties do you want to add to make this possible? Don't start coding it all just yet, just add a little pseudo-code here on what your thoughts are eon the implementation. If a developer is going to install the Toolkit, how do they enable this?

**Comment by GUOLDEV** [comment]
Hi @jfversluis, I have updated the description of the feature adding a use case for FocusMode. The idea is to expose the properties of the camera when supported. Please let me know what you think. Breaking this feature into small pieces, so we can implement FocusMode first for example, and then ExposureMode and so on.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Comment by GUOLDEV** [comment]
> Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).
> 
> 
> 
> Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.
> 
> 
> 
> I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

@brminnick Far enough 👍 I have already created a discussion for Community Toolkit Maui 😅
