### ISSUE TITLE
[Enhancement] Adding a converter argument on TranslateExtension

### ISSUE THREAD

**Issue by zeib** [xamarin/XamarinCommunityToolkit#1337]
## Summary

Often there is the need to convert the localized text (e.g. changing the text case). Since the TranslateExtension returns a BindableProperty it seems that there is no "pretty" way of doing this.

## API Changes

Example XAML call after the change:
`"{xcmt:Translate key, Converter={StaticResource ExampleConverter}}"`

Changes required on the TranslateExtension class:

Adding the conveter class variable on the TranslateExtension class:
`public IValueConverter? Converter { get; set; }`

Adding the converter to the binding that the ProvideValue returns:
`public BindingBase ProvideValue(IServiceProvider serviceProvider)
{
         ...
         binding.Converter = this.Converter;
         ...
 }`

## Intended Use Case
For any use that the StringFormat cannot cover, such as changing the text to uppercase, which I believe will be the most common case.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
I believe that we can do it without a Converter... We can just add a new Property on the Markup Extension that will control it. What do you think @zeib ?

**Comment by zeib** [comment]
> I believe that we can do it without a Converter... We can just add a new Property on the Markup Extension that will control it. What do you think @zeib ?

Yes, that is possible as well, but I do believe that exposing the Converter of the BindableBase that is returned is much more versatile. For example, I always have to use a custom uppercase converter to take care of capitalizing some special Greek characters, that almost no converter seems to handle. So using the converter included in the community toolkit is rather limiting and will still call for custom “hacky” solutions, such as forking the TranslateExtension to expose the Converter or creating a LocalizedString object in the code behind/view model, to allow for binding and as such the use of a converter. Also someone might need the use for something other than uppercasing a string, although I cannot think of something right now. I could be wrong though.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
