### ISSUE TITLE
[Enhancement] Initials Avatar component

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#134]
## Summary
Just a small control we could include where a user provides a string, we turn it into an avatar with the initials. We could randomize the background colors from a specific set. Possible properties:

- `MaxInitialsCount`
- `FontFamily`
- `FontSize`
- `CornerRadius`
- `TextColor`

## Intended Use Case
![image](https://user-images.githubusercontent.com/2419439/84538112-603e1a80-acf1-11ea-9340-20978840fbf3.png)

**Comment by davidortinau** [comment]
Would it be reasonable to follow the API of Fluent UI? https://developer.microsoft.com/en-us/fluentui#/controls/ios/avatar

https://github.com/microsoft/fluentui-apple/blob/master/ios/FluentUI/People%20Picker/AvatarView.swift

**Comment by davidortinau** [comment]
Would it be reasonable to follow the API of Fluent UI? 

https://developer.microsoft.com/en-us/fluentui#/controls/ios/avatar

https://github.com/microsoft/fluentui-apple/blob/master/ios/FluentUI/People%20Picker/AvatarView.swift

**Comment by AndreiMisiukevich** [comment]
> Would it be reasonable to follow the API of Fluent UI? https://developer.microsoft.com/en-us/fluentui#/controls/ios/avatar
> 
> https://github.com/microsoft/fluentui-apple/blob/master/ios/FluentUI/People%20Picker/AvatarView.swift

I think we are able (and should) make it better ;)
