### ISSUE TITLE
[Bug] Toast and Snackbar not shown on IOS 12.4 (simulator or device) 

### ISSUE THREAD

**Issue by ChrisFieldhouse** [xamarin/XamarinCommunityToolkit#1343]
### Description
On IOS 12.4 simulator and device, calling this.DisplayToastAsync and this.DisplaySnackBarAsync does nothing.  Calling (sender as VisualElement).DisplaySnackBarAsync works, and after calling this, all subsequent calls (using this or (sender as VisualElement)) work, but only for the current page.  Open a new page and DisplayToast/Snackbar fail again.

I assume that calling (sender as VisualElement).DisplaySnackbarAsync must change something on the page to make the subsequent calls work

### Steps to Reproduce

1. Create new solution
2. Add 4 buttons
3. Button 1 Clicked = this.DisplayToastAsync("Hello");
4. Button 2 Clicked = (sender as VisualElement).DisplayToastAsync("Hello");
5. Button 3 Clicked = this.DisplaySnackBarAsync(sbo); //sbi is a SnackBarOptions instance correctly set
6. Button 4 Clicked = (sender as VisualElement).DisplaySnackBarAsync(sbo);

### Expected Behavior

Toast and snackbar to be displayed

### Actual Behavior

Press button 1 - No action
Press button 2 - No action
Press button 3 - No action
Press button 4 - Snackbar displayed

Now pressing the other buttons also works.

Same code works without issue on IOS 14.5.

### Basic Information

- Version with issue: Toolkit 1.2.0 pre2
- Last known good version: Couldn't get this to work on any version
- IDE: VS2019 - Windows
- Platform Target Frameworks: 
  - iOS:   12.4 (works on 14.5)
  - 
- Nuget Packages:  Essentials 1.6.0; Xamarin Forms 5.0.0.2012
- Affected Devices: iphone 5/s and possibly others

**Comment by jfversluis** [comment]
@VladislavAntonyuk does this make any sense to you?

**Comment by VladislavAntonyuk** [comment]
I will try to reproduce. maybe some changes with constraints between ios12 and ios14.

**Comment by ChrisFieldhouse** [comment]
This is how it looks in the simulator on ios 12.4, you can see the very bottom of the toast message (I guess because it's a long message).

![Simulator Screen Shot - iPhone 5s - 2021-06-02 at 17 16 36](https://user-images.githubusercontent.com/44022687/120515988-cb7f7180-c3c6-11eb-9999-b482cd9a6e97.png)

**Comment by VladislavAntonyuk** [comment]
Does it look correct with the short message?

**Comment by ChrisFieldhouse** [comment]
With a smaller message the toast doesn't display, I guess it's shown, but off screen.  I've added a small video of the issue, as you will see, pressing 'Show toast with anchor' makes the toast work correctly.   This is using the current master branch.


https://user-images.githubusercontent.com/44022687/120606335-00cba400-c447-11eb-8d4c-620eac54742a.mp4

**Comment by VladislavAntonyuk** [comment]
looks like it works correctly with the second click on the button. or it happened after the anchor view is displayed. ok. I will investigate it

**Comment by jfversluis** [comment]
Interesting, for the first presses of the button I see a lot happening at the top of the screen, did you notice?

**Comment by VladislavAntonyuk** [comment]
fixed, will create a PR in a minute
