### ISSUE TITLE
[Enhancement] Camera View Subtitle

### ISSUE THREAD

**Issue by TFreudi1** [xamarin/XamarinCommunityToolkit#1353]
It would be nice to record a subtitle directly into every frame of the videofile, means a callback with the image that is currently recorded and change it. I know I can put an overlay on the camera view but this is only visible for the user, it is not recorded into the video if you look at it later.

**Comment by jfversluis** [comment]
Hi there @TFreudi1 thanks for the suggestion. Is there any specific reason why you decided to ignore the template we have in place? That helps us a great deal in getting som more information and details on how you want to use it and what you'd like to see.

Also, do you mean the MediaElement? I don't really see how this would work for CameraView?

**Comment by TFreudi1** [comment]
![CameraView](https://user-images.githubusercontent.com/4739177/120504226-409d7780-c3c4-11eb-893a-932ed8d6c642.jpg)

**Comment by TFreudi1** [comment]
In want to have a text (lets say the GPS Position) as text written in every frame in the final MP4. 
You get a picture from the camerasensor, than you put on the screen and in the file, an event PicFromSensorHasArrived(Image i) would be nice. I can than put some text on i (the image) and have that on the screen and in final video file. I know that is performance relevant because you have to wait until the eventhandler finished painting on the image.

See the picture of my Android/FFMpeg App. I put the GPS Text in an image that comes from the sensor, than I put it on the surface (preview screen of the mobile) and the ffmpeg lib writes it to a MP4 file. Very complex code and the ffmpeg libaries are platform independent and I know tht this is only one way to get what I need ( and many more users if you google arround )

**Comment by TFreudi1** [comment]
Sorry ffpmpeg libs are a special problem because they are NOT platform independent!

**Comment by TFreudi1** [comment]
On the screenshot:
Start = Start recording the video and than the coordinates shown in th epreview are also in the recorded videofile.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
