### ISSUE TITLE
[Bug] Typo in Android SemanticEffect implementation 

### ISSUE THREAD

**Issue by ces-tr** [xamarin/XamarinCommunityToolkit#1358]
### Description
Typo in Android SemanticEffect implementation 
I'm not sure if this builds correctly but even if I implement this same effect in my app , the IDE can not find this namespace

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffectRouter.android.cs#L4

**Comment by JosueDM94** [comment]
I have the same bug on my project that uses a dependency from Xamarin.AndroidX.Core like the NuGet Xamarin.AndroidX.ConstraintLayout. 

Looking from the using headers `using AndroidX.Core.View.Accessibiity;` on the SemanticEffect is only accessible from Xamarin.AndroidX.Core < 1.3.2.1 but updating a newer version Xamarin.AndroidX.Core > 1.3.2.1 uses `using AndroidX.Core.View.Accessibility;`.

The workaround is to add Xamarin.AndroidX.Core < 1.3.2.1 but if the AOT is enabled the build fails

**Bug stack trace** 
[SemanticEffectStacktrace.txt](https://github.com/xamarin/XamarinCommunityToolkit/files/6593777/SemanticEffectStacktrace.txt)

**Reproducible solution** [
[SemanticEffectTypoBug.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6593758/SemanticEffectTypoBug.zip)
](url)

**Comment by jamesmontemagno** [comment]
Good find, what we can see is that in 1.3.2.2 the namespace typo was fixed in the binding.

Xamarin.Forms doesn't use this namespace so shouldn't be an issue.

https://www.fuget.org/packages/Xamarin.AndroidX.Core/1.3.2.2/lib/monoandroid90/diff/1.3.2/ is the diff.

**Comment by jamesmontemagno** [comment]
This is only an issue if you have another library that has Xamarin.AndroidX.Core 1.3.2.2 or higher as a dependency and does not impact file -> new project with just Xamarin.Forms

**Comment by jamesmontemagno** [comment]
It does look like unfortunately 1.3.2.2 has some changes to Resources and things fail to compile. @jfversluis I may need some help here or @Redth as this is a funky one for sure.

**Comment by jamesmontemagno** [comment]
Alright, so if I bring in 1.5.0 as a dependency then it seems to compile, which is odd. I am not as comfortable with that and I am not sure about side effects on apps.

**Comment by brminnick** [comment]
The Xamarin.Forms team has opened a PR to resolve this https://github.com/xamarin/Xamarin.Forms/pull/14101/files#diff-a10b47d2a1fb6f9a0f879b70a6b268191496328089b0bd5776fcbd68759d59dbR25.

We'll test XCT against the new version of Xamarin.Forms that contains this fix, and (assuming everything is good) we'll push out an update that targets this new version of Xamarin.Forms 👍
