### ISSUE TITLE
[Enhancement] Entry Clear Button Color Effect

### ISSUE THREAD

**Issue by Axemasta** [xamarin/XamarinCommunityToolkit#1359]
## Summary

I recently came across the requirement to change the color of the clear button on an Entry and wrote and effect for it. It wasn't the nicest experience getting working on specifically iOS and thought it might be a nice addition to the community toolkit.

## API Changes

A new effect named:
`ClearButtonColorEffect`

With the parameters: `Color`, defaulting to `Color.Default`

## Intended Use Case

For making `Entry`s look fancier!

A pink clear button on iOS
![Hot Pink Clear Button on iOS](https://user-images.githubusercontent.com/33064621/120651092-4d7aa380-c476-11eb-8bdb-fcba8fd14869.png)

A red clear button on Android
![Red Clear Button on Android](https://user-images.githubusercontent.com/33064621/120651228-71d68000-c476-11eb-842e-6d5aebf3a605.jpg)

In Xaml:
```xml
<Entry Placeholder="Write Something" Text="Clear Me" ClearButtonVisibility="WhileEditing">
    <Entry.Effects>
        <effects:ClearButtonColorEffect Color="Lime"/>
    </Entry.Effects>
</Entry>
```

## Who Will Do The Work?

- [X] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by aritchie** [comment]
There is already a fix in a PR for XF to resolve this.  https://github.com/xamarin/Xamarin.Forms/pull/12391

**Comment by Axemasta** [comment]
Ah beat me to it!

Nevertheless [here](https://gist.github.com/Axemasta/7a8ba685870d32f2418da63ec2c17a95) is the effect in a gist, not optimised at all but it give people the feature now, instead of waiting for a XF release 😁
