### ISSUE TITLE
[Enhancement] MultiConverter

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#137]
## Summary
This is a converter that allows for multiple converters to be applied in series. I already made some code for this in the **multiconverter** branch. I would, however, like to have a discussion on whether or not this is useful or how we can improve upon it.

## API Changes

- Add a `MultiConverter`

## Intended Use Case
Use it as follows:

```
<xft:MultiConverter x:Key="myMultiConverter">
    <xft:IntToBoolConverter />
    <xft:BoolToObjectConverter />
</xft:MultiConverter>
```
And in XAML:

```
<MyElement Property="{Binding X, Converter={StaticResource myMultiConverter}, ConverterParameter='Y'}" />
```

## Code

```
public class MultiConverter : List<IValueConverter>, IValueConverter
{
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
            => this.Aggregate(value, (current, converter) => converter.Convert(current, targetType, parameter, culture));

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
            => throw new NotImplementedException();
}
```

## Discussion
The problem I have for now is that you can only pass in one parameter on the `MultiConverter` level that gets pushed down into the separate converters. Other than that the chaining of values would work fine in this scenario.

**Comment by AndreiMisiukevich** [comment]
I believe x:Array can be passed as a parameter to MultiConverter.

**Comment by AndreiMisiukevich** [comment]
I like this idea very much

**Comment by sthewissen** [comment]
> I believe x:Array can be passed as a parameter to MultiConverter.

So you would provide an array with 4 items if you chain 4 converters together and we grab them by index? There's not really a different way to indicate which parameter goes into which converter otherwise. Not sure if that is too much magic spaghetti for my liking though 😓  I will experiment a bit with some options.

**Comment by sthewissen** [comment]
@AndreiMisiukevich How do you feel about something like the following:

```
<ResourceDictionary>
    <xct:MultiConverter x:Key="myMultiConverter">
        <xct:IntToBoolConverter x:Name="intToBool" />
        <xct:BoolToObjectConverter x:Name="boolToObject" />
    </xct:MultiConverter>
    <x:Array x:Key="multiParams" Type="xct:MultiConverterParameter">
        <xct:MultiConverterParameter Converter="intToBool" Value="{Binding x}" />
    </x:Array>
</ResourceDictionary>
```

Then in the converter we can pass in this array as the root parameter and the converters can go grab the parameter from the array if their name exists in there.

**Comment by sthewissen** [comment]
Upon further exploration I might need to do a type-based check as the `x:Name` is obviously not available in the converter.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich How do you feel about something like the following:
> 
> ```
> <ResourceDictionary>
>     <xct:MultiConverter x:Key="myMultiConverter">
>         <xct:IntToBoolConverter x:Name="intToBool" />
>         <xct:BoolToObjectConverter x:Name="boolToObject" />
>     </xct:MultiConverter>
>     <x:Array x:Key="multiParams" Type="xct:MultiConverterParameter">
>         <xct:MultiConverterParameter Converter="intToBool" Value="{Binding x}" />
>     </x:Array>
> </ResourceDictionary>
> ```
> 
> Then in the converter we can pass in this array as the root parameter and the converters can go grab the parameter from the array if their name exists in there.

hmmm, can we working :)

**Comment by jfversluis** [comment]
We do need a sample for this in the sample app. And ideally tests (for all the things in here right now for that matter)

**Comment by AndreiMisiukevich** [comment]
This one is resolved, I guess

**Comment by jfversluis** [comment]
Opened a new issue to add tests/sample for this so we can close this one
