### ISSUE TITLE
[Enhancement] Add ColumnDefinitions and RowDefinitions to UniformGrid

### ISSUE THREAD

**Issue by DamianAntonowicz** [xamarin/XamarinCommunityToolkit#1370]
## Summary

 Add `ColumnDefinitions` and `RowDefinitions` to `UniformGrid`.

## API Changes

Add following properties to `UniformGrid`:
- `ColumnDefinitions`
- `RowDefinitions`

## Intended Use Case

Enhancement was created based on comment from Calendar PR: https://github.com/xamarin/XamarinCommunityToolkit/pull/1331#discussion_r639264363 Calendar control would use `ColumnDefinitions` and `RowDefinitions` from `UniformGrid`.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks Damien!

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
