### ISSUE TITLE
[Enhancement] Color converters / extensions

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#138]
## Summary
There's a lot of community code that we can bundle in this Toolkit. I would like to reach out to people in the community of things that we like and see if they're willing to PR it into the Toolkit. One such sample is this collection of extensions and converters related to colors:

https://blog.francois.raminosona.com/more-xamarin-forms-color-functions/

How do we feel about this strategy of reaching out to people to add useful snippets they might have into this NuGet? Also, how do we feel about the above sample? Is it something we think has a place in this Toolkit? I think it suits it and getting more people to contribute this way is definitely a goal I think we should want to strive for instead of just grabbing the code and pulling it in ourselves.

**Comment by sthewissen** [comment]
Regarding this one, I had a chat with François and he will take a look in the weekend :)

**Comment by jfversluis** [comment]
Re: this strategy. Yes! Definitely! I think it shows we are happy to collaborate and they will still get credit by putting it in here themselves. And I would hate anyone to think that we are taking code from people and assimilate it. Even if they don’t want to contribute themselves, I would always want to be in touch and get permission to put their code in or at least let them know we are doing something similar.

Of course to a certain extent. We can’t go out and trace all libraries that do remotely the thing we want to do. But I think we are aware of popular libraries and we want to make friends <3

**Comment by jfversluis** [comment]
Did @framinosona ever get back to this? :)

**Comment by Hackavist** [comment]
Hello, will this issue be available for Hacktoberfest ?

**Comment by pictos** [comment]
We already have some `ColorHelpers` in XE as you can see [here](https://github.com/xamarin/essentials/blob/main/Xamarin.Essentials/Types/ColorConverters.shared.cs). So we can see if this feature fits better in XE or here. If fits better here we can bring what we already have in XE to here and add more features.

**Comment by jfversluis** [comment]
@pictos looking at Essentials and this one there is no overlap. Essentials ones are all `FromRgb` etc. While these methods to `ToRgb`.

Also the PR that is opened has a lot of good stuff that is not in Essentials

**Comment by Hackavist** [comment]
I would like to implement it

**Comment by jfversluis** [comment]
There is already a PR open @Hackavist so I don't think that is going to work :)

**Comment by Hackavist** [comment]
okay sorry for the misunderstanding

**Comment by pictos** [comment]
@jfversluis yeah, they don't overlap. But my concern is about having a _same feature_ in different packages and this can lead to code duplication in the future. As a mobile developer, I want to have all Color features in one place, that way I don't need to scan different namespaces and/or packages looking for the method that I want. Said that I think we keep the `ColorHelpers` in one place, can be here or in Essentials. Is that make sense to you?

**Comment by jfversluis** [comment]
That definitely is a good point.

I think the big difference is that the Essentials APIs don't use the Xamarin.Forms.Color while this one does?

**Comment by pictos** [comment]
@jfversluis... Well XE grabbed the XF implementation... I was there (Bilbo's voice)... You can see more about the implementation [here](https://github.com/xamarin/Essentials/pull/1193#issuecomment-606188712)

**Comment by jfversluis** [comment]
This one is merged!
