### ISSUE TITLE
Displaying a Toast on iOS 12 using XamarinCommunityToolkit causes NSInvalidArgumentException

### ISSUE THREAD

**Issue by katomic** [xamarin/XamarinCommunityToolkit#1380]
### Steps to Reproduce

1.  Display a Toast using   await myPage.DisplayToastAsync with any parameter

### Expected Behavior
Toast is displayed

### Actual Behavior
Exception:
{Foundation.MonoTouchException: Objective-C exception thrown.  
Name: NSInvalidArgumentException Reason: +[UIColor systemBackgroundColor]: unrecognized selector sent to class 0x1261ebec0\n
Native stack trace:\n\t
0   CoreFoundation                      
0x00000001101938db __exceptionPreprocess + 331\n\t1   libobjc.A.dylib                     
0x0000000117f37ac5 objc_exception_throw + 48\n\t2   CoreFoundation                      
0x00000001101b1b94 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      
0x0000000110198623 ___forwarding___ + 1443\n\t4   CoreFoundation                      
0x000000011019a418 _CF_forwarding_prep_0 + 120\n\t5  
0x000000010fd42d39 xamarin_dyn_objc_msgSend + 217\n\t6   ???                                 
0x000000013aea1cea 0x0 + 5283388650\n"...

### Basic Information
macOS Catalina 
VS2019 with all stable updates installed as on 6 June 2021
- Version with issue: iOS 12
- Version that works: iOS 13 and later
Xamarin Forms 5.0.0.2012
Xamarin Community Toolkit 1.1.0
Net Standard 2.0.3
- IDE: MacOS VS2019
- Platform Target Frameworks: 
  - iOS:   12.4 (Tried both a simulator and actual device.
 iOS SDK 14.4

- Nuget Packages:
-   <PackageReference Include="Microsoft.CSharp">
      <Version>4.7.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.Platforms">
      <Version>5.0.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Win32.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="modernhttpclient-updated">
      <Version>3.4.3</Version>
    </PackageReference>
    <PackageReference Include="NETStandard.Library">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.1</Version>
    </PackageReference>
    <PackageReference Include="Plugin.DeviceOrientation">
      <Version>1.0.7</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="System.AppContext">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.5.1</Version>
    </PackageReference>
    <PackageReference Include="System.Collections">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Collections.Concurrent">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.TypeConverter">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Console">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.Debug">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.Tools">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.Tracing">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common">
      <Version>5.0.2</Version>
    </PackageReference>
    <PackageReference Include="System.Globalization">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Globalization.Calendars">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO.Compression">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO.Compression.ZipFile">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO.FileSystem">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO.FileSystem.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Linq">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Linq.Expressions">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.4</Version>
    </PackageReference>
    <PackageReference Include="System.Net.Http">
      <Version>4.3.4</Version>
    </PackageReference>
    <PackageReference Include="System.Net.Primitives">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Net.Sockets">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.ObjectModel">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Extensions">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Resources.ResourceManager">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Extensions">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Handles">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.InteropServices">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Numerics">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Formatters">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Algorithms">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Encoding">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.X509Certificates">
      <Version>4.3.2</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Encoding">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Encoding.Extensions">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Text.RegularExpressions">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Threading">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Tasks">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Timer">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.ReaderWriter">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.XDocument">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.XmlDocument">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="Toasts.Forms.Plugin">
      <Version>3.3.2</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity">
      <Version>3.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.DeviceInfo">
      <Version>4.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Geolocator">
      <Version>4.5.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Media">
      <Version>5.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Forms.KeyboardOverlap">
      <Version>1.0.0.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.CommunityToolkit">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Controls.SignaturePad.Forms">
      <Version>3.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.6.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>5.0.0.2012</Version>
    </PackageReference>
    <PackageReference Include="XLabs.Forms">
      <Version>2.0.5782</Version>
    </PackageReference>
    <PackageReference Include="Acr.UserDialogs">
      <Version>7.1.0.514</Version>
    </PackageReference>
- Affected Devices:

**Comment by VladislavAntonyuk** [comment]
Should be fixed with XCT 1.2.0-pre2

**Comment by jfversluis** [comment]
Please try with the version mentioned above, if that doesn't fix it feel free to reopen this one. Thanks!
