### ISSUE TITLE
[Bug] AsyncCommand causes RefreshView to complete instantly

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/XamarinCommunityToolkit#1388]
### Description
If you have a RefreshView to load some data asyncronsly on a pull to refresh the pull to refresh actions (IsRefreshing = false, animation goes away) will complete differently depending if you are using the normal Command vs XCT AsyncCommand.

### Steps to Reproduce

1. Add RefreshView and wire it up as per most tutorials
2. Change RefreshCommand to be backed by AsyncCommand provided by Xamarin Community Toolkit.

### Expected Behavior
When the user pulls to refresh the RefreshView will await for the specific method (ExecuteRefreshCommand in my sample) to finish before setting IsRefreshing to false and making the refresh animation go away.

### Actual Behavior
RefreshView completes refresh instantly when RefeshCommand is an AsyncCommand.

### Basic Information

Xamarin.Forms: 5.0.0.2012
Xamarin Community Toolkit: 1.1.0

### Workaround

Use Command instead of AsyncCommand. However this means you can't take advantage of the built in `allowsMultipleExecutions` functionality and you'd have to re-create that yourself. 

### Reproduction imagery

Command: 
![Command test](https://user-images.githubusercontent.com/904737/121763141-f57e2400-cb7c-11eb-9f20-1a97f4457803.gif)

AsyncCommand: 
![AsyncCommand test](https://user-images.githubusercontent.com/904737/121763144-fd3dc880-cb7c-11eb-84e0-926b36870224.gif)

### Reproduction Link

[AsyncCommandRefreshView.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6641553/AsyncCommandRefreshView.zip)

In this sample there are two pages to view the two different types of commands. In both `AsyncCommandPage.xaml.cs` and `CommandPage.xaml.cs` there is some `Debug.WriteLine` statements to observer when `ExecuteRefreshCommand` begins and ends as well as when `IsRefreshing` property is automatically toggled.

**Comment by maxkoshevoi** [comment]
Interesting case. Issue is with `RefreshView`, and not with `AsyncCommand`.

- Turns out, when `ICommand` becomes disabled (`CanExecute=false`), `RefreshView` immediately sets `IsRefreshing` to `false`.
- When you set `allowsMultipleExecutions` to `false`, you requested `AsyncCommand` to disable itself while it's being executed (in another words, removing `allowsMultipleExecutions: false` fixes your issue. `RefreshView` cannot be refreshed while it's being refreshed, so it's not needed in this case anyway).
- If you manually implement the same logic for `Command`, you'll see the same issue:
```cs
bool canExecute = true;
...
new Command(async () => await ExecuteRefreshCommand(), () => canExecute)
...
async Task ExecuteRefreshCommand()
{
    System.Diagnostics.Debug.WriteLine("ExecuteRefreshCommand Start");

    canExecute = false;
    RefreshCommand.ChangeCanExecute();

    await Task.Delay(2000);

    // Stop refreshing
    IsRefreshing = false;

    canExecute = true;
    RefreshCommand.ChangeCanExecute();

    System.Diagnostics.Debug.WriteLine("ExecuteRefreshCommand End");
}
```

I think, this issue can be closed as "As Designed".

**Comment by beeradmoore** [comment]
Dang my solution for this was going to be implement the can execute myself but I guess not 😅

I'll go handle it inside my ExecuteRefreshCommand so at least it can only execute once. I'll go file this as a potential bug with Xamarin.Forms repo. Thanks for digging into this though.
