### ISSUE TITLE
Popup Fullscreen

### ISSUE THREAD

**Issue by fredericoregateiro** [xamarin/XamarinCommunityToolkit#1391]
## Summary

Allow the Popup to be able to go full screen.

## API Changes

Add one property to the Popup bool IsFullScreen, that allow the Popup to go fullscreen

## Intended Use Case
Edit a record in a phone, will allow more space for the controls

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@fredericoregateiro I would say that if you need a full screen popup the best way is to perform a ModalNavigation. Or is there something that I can't see?

**Comment by jfversluis** [comment]
I kind of agree with @pictos here. What would be the use-case? Why do you need this over a regular modal?

@ahoefling do you have any thoughts about this?

**Comment by ahoefling** [comment]
Not sure if I understand the use case here and I agree with @pictos. Do you have any screenshots of what you are thinking

**Comment by fredericoregateiro** [comment]
Hello all,
In my opinion this is just a really nice feature for the pop up, and gives the developer the power of choice.
On the phone, screen size is something we should use with care. And the option to use all available space is something to consider.

And once i started using the popup and don't want to go back to the modal 😄 

![Screenshot_1623676704](https://user-images.githubusercontent.com/6304701/121898878-c3ef8f00-cd1b-11eb-98ea-95e8960fa1e4.png)

**Comment by fredericoregateiro** [comment]
Similar to #1398 
Making `Margin="0"` would be the same as `Fullscreen="True"` but with more control on how the popup is using the available screen size

**Comment by jfversluis** [comment]
Hm to be honest I see more in the margin approach which gives more flexibility and control and might have a side-effect of being able to open a popup fullscreen :)

If you don't mind I'm closing this one in favor of #1398
