### ISSUE TITLE
Popup not show Full screen on iOS

### ISSUE THREAD

**Issue by Pankajgangwar613** [xamarin/XamarinCommunityToolkit#1392]
### Steps to Reproduce

1. Popup perfectly show Full screen on  android but Popup not show Full screen on iOS
2.  
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pictos** [comment]
@Pankajgangwar613 , can you attach a small repro?

**Comment by jfversluis** [comment]
Thanks for reporting this @Pankajgangwar613, however there is very little detail.

I'd love to see a filled out report on what you're using and where you're seeing this. In this case it would be extremely helpful to either see some code or a reproduction project so we can see how you're trying to achieve this.

I'm closing this one for now, please open a new issue if this still affects you with more detail and a reproduction project attached. Thanks!
