### ISSUE TITLE
[Bug] XamlC error XFC0000 : Cannot resolve type "Popup"

### ISSUE THREAD

**Issue by fredericoregateiro** [xamarin/XamarinCommunityToolkit#1393]
### Description
When using a Popup the project build is ok, it can be deployed to an emulator or device but the Error List shows this error

### Steps to Reproduce

1. Create a Popup
2. Build the project

### Expected Behavior
Build with no errors and the error list empty

### Actual Behavior
Error in the Error List
XamlC error XFC0000 : Cannot resolve type "Popup"

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 16.10.1
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 11
  - UWP:  not tested
- Android Support Library Version: 
- Nuget Packages: Xamarin.CommunityToolkit 1.1.0 and 1.2.0 preview 2
- Affected Devices:

**Comment by jfversluis** [comment]
Similar to #1311 and #1384

**Comment by AmrAlSayed0** [comment]
@jfversluis Also here https://github.com/rotorgames/Rg.Plugins.Popup/issues/619
Apparently, It has to do with URL names spaces. Using the fully qualified Namespace will solve the issue but it doesn't explain why it is happening though

**Comment by jfversluis** [comment]
Yeah I think it's more of a tooling issue than something we can fix unfortunately

**Comment by fredericoregateiro** [comment]
I try using the full namespace
`xmlns:xctViews="clr-namespace:Xamarin.CommunityToolkit.UI.Views;assembly=Xamarin.CommunityToolkit"`

and the errors are gone

**Comment by semihbilis** [comment]
I deleted this from namespace on xaml side
xmlns:popups="clr-namespace:{FilePath}" x:DataType="popups:{FileName}"
and it was solved
