### ISSUE TITLE
TabView Icon Sizes Are Too Small

### ISSUE THREAD

**Issue by Egehanozsoy** [xamarin/XamarinCommunityToolkit#1394]
When adding an icon to TabView it looks so small

![image](https://user-images.githubusercontent.com/75164990/121799415-ab587980-cc34-11eb-88e0-163958d2e22a.png)

**Comment by pictos** [comment]
@Egehanozsoy, can you attach a small repro?

**Comment by michaldivis** [comment]
A good workaround would be to not use the `Icon` property and use a font icon in the `Label` instead. That approach is working for me, especially since the font icon can adapt to a theme change, whereas the image can't.

**Comment by alinberce** [comment]
Well, I encountered the same issue. So I took a look at official sample and found out that it had `TabStripHeight`. Setting that in xaml for TabView makes the icons size property.
