### ISSUE TITLE
Set warnings as errors

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#14]
_From @jimbobbennett on December 22, 2016 22:53_

To enforce code quality all warnings should be set to errors.

This will need to happen after the XML comments are all fixed by https://github.com/FormsCommunityToolkit/Effects/issues/33

_Copied from original issue: FormsCommunityToolkit/Effects#34_

**Comment by jamesmontemagno** [comment]
Added StyleCop #82
