### ISSUE TITLE
[Bug] Couple of native XCT crash reports from AppCenter

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#1401]
### Description

Hi.

Please find attached a couple of XCT-related native crash reports from my iOS app from AppCenter:

Safe area effect:

```c#
SIGABRT: Index was outside the bounds of the array.

SafeAreaEffectRouter.UpdateInsets ()
SafeAreaEffectRouter.<OnAttached>b__6_0 (Foundation.NSNotification _)
InternalNSNotificationHandler.Post (Foundation.NSNotification s)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

Snackbar:

```c#
SIGABRT: Objective-C exception thrown. Name: NSGenericException Reason: Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x600003999280 "UILayoutGuide:0x600001540380'UIViewSafeAreaLayoutGuide'.bottom"> and <NSLayoutYAxisAnchor:0x6000039ff9c0 "UILayoutGuide:0x600001540460'UIViewSafeAreaLayoutGuide'.bottom"> because they have no common ancestor. Does the constraint or its anchors reference items in different view hierarchies? That's illegal. Native stack trace: 0 CoreFoundation 0x00007fff20422fba __exceptionPreprocess + 242 1 libobjc.A.dylib 0x00007fff20193ff5 objc_exception_throw + 48 2 CoreAutoLayout 0x00007fff58912447 -[NSLayoutConstraint setActive:] + 0 3 ??? 0x000000010e43c70f 0x0 + 4534290191

Runtime.ThrowNSException (System.IntPtr ns_exception)
Runtime.throw_ns_exception (System.IntPtr exc)
(wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
(wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_bool(intptr,intptr,bool)
NSLayoutConstraint.set_Active (System.Boolean value)
BaseSnackBarView.ConstraintInParent ()
AppMainPage+<>c__DisplayClass24_0.<DisplayToastForAcceptedPendingRequest>b__1 (MyApp.ViewModels.UserActivityToastViewModel toastVm)
UserActivityToast+<>c__DisplayClass0_0.<PrepareUserActivityToast>b__1 ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
Application.Main (System.String[] args)
```

Unfortunately I don't have specific repro steps, but hopefully the stack traces will prove useful.

Thank you.

### Expected Behavior

No native crashes should occur.

### Actual Behavior

Some native crashes are seemingly occurring.

### Basic Information

- Version with issue: 1.1.0-preview1056
- Last known good version: None
- IDE: VS For Mac 8.10.2
- Platform Target Frameworks: 
  - iOS:  14.5

**Comment by jfversluis** [comment]
Hmm the snackbar one might already be fixed with a very recent PR, the other one is curious. I only see an index [here](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/SafeArea/SafeAreaEffectRouter.ios.cs#L54) so we might be able to add some defensive code there to see if that works

**Comment by jfversluis** [comment]
@VladislavAntonyuk do you know anything about that constraint one? Is it fixed with #1378 ?

**Comment by VladislavAntonyuk** [comment]
It should work with that PR, @Tommigun1980 could you please attach a small repro?

**Comment by jfversluis** [comment]
I don't think there is a repro as the errors are coming from analytics unfortunately :(
So I guess we should hope this fixes it and @Tommigun1980 will install the update and see if the errors go away :)

**Comment by Tommigun1980** [comment]
@jfversluis Thanks so much for fixing the OOB, and thanks for fixing the other issue @VladislavAntonyuk!

I will give the new nightly a spin and post here if the issues are still visible in the crash reports for the new version.

**Comment by Tommigun1980** [comment]
@jfversluis @VladislavAntonyuk I managed to repro the safe area issue with the old version, and it's actually really simple:
1) Have a safe area effect in your view (in my app I use it on the "main" page).
2) Quit the app by pulling from the bottom of the screen and swiping the app upwards

It crashes 100% of the time with the above stack trace.

**Comment by Tommigun1980** [comment]
Can confirm that the crash doesn't happen with the latest nightly build, so https://github.com/xamarin/XamarinCommunityToolkit/pull/1404 worked.
