### ISSUE TITLE
Tap / Swipe to Close or Dismiss

### ISSUE THREAD

**Issue by jrahma** [xamarin/XamarinCommunityToolkit#1403]
Hi,

Please add an option to Tap / Swipe to close the Toast and SnackBar instead of waiting for the duration.

Thanks,
Jassim

**Comment by jfversluis** [comment]
Please fill in the feature request template as provided.

**Comment by Cfun1** [comment]
> Please fill in the feature request template as provided.

In addition it is duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/1225
