### ISSUE TITLE
[Bug] Expander Direction Up does not work properly

### ISSUE THREAD

**Issue by sact1909** [xamarin/XamarinCommunityToolkit#1409]
### Description
When I'm trying to add Direction Up to the Expander and I run the app, it isn't showing the view

### Steps to Reproduce

1. Try to set Direction property Up
2. Run the app
3. The view won't change the content

### Expected Behavior
The expander show content to up

### Actual Behavior
Disable the view

### Basic Information

- Version with issue: 1.1.0
- Last known good version:
- IDE: Visual Studio

**Comment by jfversluis** [comment]
Would you be able to try the latest pre-release and see if this still happens? Also a piece of code, or even better, a small reproduction sample would be amazing :) Thanks!

**Comment by AndreiMisiukevich** [comment]
Please try latest pre-release version and let us know if this issue still exists

**Comment by AndreiMisiukevich** [comment]
Tested, works fine on iOS with latest code
