### ISSUE TITLE
[Bug] Validation behavior invalid color

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#141]
### Description

Right now the naming is confusing on the validation behavior. I would like to rename `TextColor` to something else. Also, I think we need to examine the current implementation. Right now what is going on here is if the text is valid then the text will always be default (black), but when it's invalid it will be the value of `TextColor` if set or red as a fallback/default value.

In that case I think `TextColor` might need a more descriptive text like `InvalidTextColor`. Also, what happens what we set a different `TextColor` on the parent control? Then the color will reset to black while the user wants to see a different color?

**Comment by sthewissen** [comment]
I think this isn't completely correct. The thing takes the "normal-state" TextColor from whatever the user has set on the control. The invalid state text color is the TextColor property set on the behavior (or red if not set). We should probably rename the property and we should be good to go.

**Comment by jfversluis** [comment]
OK, great! That's probably my lack of knowledge in this area then. But I would like it to be double-checked as part of this

**Comment by AndreiMisiukevich** [comment]
resolved by #132
