### ISSUE TITLE
[Feature]  Weak event manager class

### ISSUE THREAD

**Issue by pictos** [xamarin/XamarinCommunityToolkit#1410]
## Summary
In order to have a safe way to subscribe to events and avoid memory leaks we can [implement this weak event manager class](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/weak-event-patterns?view=netframeworkdesktop-4.8#using-an-existing-weak-event-manager-class).

## API Changes

In the docs they mentioned that pattern was created to solve the memory leak in WPF applications, so we need to see if that can be applied to Xamarin.Forms world. We can implement this as an `internal` feature and see how it goes. Doing it as `internal` will give us more speed to improve it as needed since we don't need to care about breaking it in future versions. If the community wants and/or when we feel comfortable with our implementation we can make it public for everyone.

I'll mark this issue as `not-up-for-grabs` because would be good if this first version was implemented at a fast speed.

**Comment by bijington** [comment]
@pictos or @brminnick is this covered by the `WeakEventManager` implementation?

**Comment by brminnick** [comment]
Yup! Closing
