### ISSUE TITLE
[Bug] TabView - Adding tabs during OnAppearing content won't show

### ISSUE THREAD

**Issue by GuidoNeele** [xamarin/XamarinCommunityToolkit#1412]
### Description
Tab content won't appear when the tabs are added in code behind in the OnAppearing method.

### Steps to Reproduce

1. Start a new Xamarin Forms project
2. Add a new TabView on a page
3. Give the TabView a x:Name property with a value of "MainTabs"
4. Go to the code behind of the page and override the OnAppearing method
5. Add a couple of tabs via this.MainTabs.TabItems.Add();
6. Run the app and see that the content part is not available.

### Expected Behavior
Content of tabs should appear on screen

### Actual Behavior
Tabs show up but the content will not show

### Workaround
Moving initialization of the tabs from OnAppearing to the constructor

### Reproduction Link
[Link to sample](https://github.com/GuidoNeele/TabViewBug)

```csharp
  public partial class MainPage : ContentPage
  {
    public MainPage()
    {
      InitializeComponent();

      //InitTabs(); // Works
    }

    protected override void OnAppearing()
    {
      InitTabs(); // Doesn't work
    }

    private void InitTabs()
    {
      ...

      this.MainTabs.TabItems.Add(new TabViewItem { Icon = smileIcon, Text = "Tab 1", Content = new Tab1LazyView() });
      this.MainTabs.TabItems.Add(new TabViewItem { Icon = bookIcon, Text = "Tab 2", Content = new Tab2LazyView() });
      this.MainTabs.TabItems.Add(new TabViewItem { Icon = bookIcon, Text = "Tab 3", Content = new View3() });
    }
  }
```

![image](https://user-images.githubusercontent.com/1301586/122426672-b8f16480-cf90-11eb-9ef8-85c2d9e41f0f.png)

**Comment by jfversluis** [comment]
If you put a breakpoint at the `OnAppearing` does it even get fired at all? Does this work on iOS?

I think the lifecycle events are a bit unreliable in some scenarios and I think this is not so much an XCT problem tbh

**Comment by GuidoNeele** [comment]
Jep it get's triggered because the tabstrip (in the bottom) is filled with buttons. Only the content part is missing (the part above the tabstrip).

I think the underlying problem is that the CarouselView isn't updated when the tabs are added via code. Because if you add buttons to an already existing strip of tabs and click the new button an index out of bounds error will show up. See https://github.com/xamarin/XamarinCommunityToolkit/issues/1219. So I think these issues are related to each other. Will have a look at the code.

**Comment by GuidoNeele** [comment]
This issue is a duplicate of #559
