### ISSUE TITLE
[Enhancement] Sample App Icon, Splash Screen, etc.

### ISSUE THREAD

**Issue by SunnyMukherjee** [xamarin/XamarinCommunityToolkit#142]
## Summary

Add a new app icon and splash screen to the Sample App

## API Changes

It may be a good idea to add an app icon and splash screen to the Sample App as more people add more samples going forward instead of using the blue Xamarin image for the app icon and the image within the app itself in the FlyoutHeader.  @sthewissen mentions in #114 to use a cool new logo.  If he is finalizing a new logo, perhaps we can use that for the app icon and the splash screen.  Plus, it will keep the sample app aligned with the general theme of the toolkit. Thoughts?

## Intended Use Case

App icon, splash screen
iOS and Android

**Comment by adenearnshaw** [comment]
Now that the project logo is formalized, I'd like to pick this up.

**Comment by jfversluis** [comment]
As I know @sthewissen is low on time, I'm sure he doesn't mind Aden doing this. So doing an assigned switch!

**Comment by sthewissen** [comment]
Go for it @adenearnshaw !
