### ISSUE TITLE
[Enhancement] Toast Visual Enhancements

### ISSUE THREAD

**Issue by czuck** [xamarin/XamarinCommunityToolkit#1425]
## Summary

A couple (hopefully) small changes/additions that would add a lot of flexibility and functionality to Toast.

## API Changes
1) Define text alignment:  In ToastOptions, remove bool IsRtl and add TextAlignOption TextAlign where
TextAlignOption { Left, Center, Right}.
2) Define width: In ToastOptions, add bool FullWidth where True renders the Toast from edge to edge, false renders it the length of the text + padding
3) Define a float: In ToastOptions, add int FloatMargin that will float the toast given number of pixels above the anchor.

## Intended Use Case
Used optionally whenever toast is used to position the toast in an optimal position.
![image](https://user-images.githubusercontent.com/1641428/122970839-388d8380-d343-11eb-9b02-1d73990c7ca3.png)

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Thanks for your ideas @czuck ! Please next time take the time to fill out the template to provide us with some more details about your valuable thoughts. The better the understanding we have about what you would like to see, the more likely it is to be implemented.

**Comment by Tommigun1980** [comment]
Very much related: https://github.com/xamarin/XamarinCommunityToolkit/issues/1399

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
