### ISSUE TITLE
[Bug] On iOS, button clicked method fires twice with TouchEffects while in a ScrollView on the first press

### ISSUE THREAD

**Issue by digitaldirk** [xamarin/XamarinCommunityToolkit#1428]
### Description
On iOS only: When you put a Button into a ScrollView with TouchEffect properties the button clicked method will be fired twice on the first press of the button (the presses after the first behave normally). In my provided code I have a button display a popup on each press, and the first press displays two popups.

### Steps to Reproduce
1. On iOS, press a button that has TouchEffect properties that is inside a ScrollView.

I provided the XAML and C# below.

### Expected Behavior
One method call per button press.
### Actual Behavior
Two method calls on first button press, then regular behavior for future presses. (iOS only, Android is fine from my testing)
### Basic Information

- Version with issue: 1.2.0-pre2
- Last known good version: Unsure, 1.2.0-pre2 is my first version used.
- IDE: Microsoft Visual Studio Community 2019 Version 16.10.2
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS '14.20.0.10'
  - Android: Android 10.0 Q

On Xamarin.Forms 5.0.0.2012

- Nuget Packages: Xamarin.CommunityToolkit 1.2.0-pre2
- Affected Devices: iOS physical device (Haven't tested simulated)

### Workaround
Use `Completed` event from TouchEffect instead of `Clicked` from Button
```xaml
<Button>
	<Button.Effects>
		<xct:TouchEffect Completed="OnCompleted" />
	</Button.Effects>
</Button>
```

### Reproduction Link
XAML and C# reproduction files: [https://gist.github.com/digitaldirk/f8445b1eed4a8286fa05bca48f0aab63](https://gist.github.com/digitaldirk/f8445b1eed4a8286fa05bca48f0aab63)

**Comment by digitaldirk** [comment]
Here is a video of the behavior:
https://user-images.githubusercontent.com/22691956/122955500-04ab6180-d335-11eb-9603-390d11a3a485.mov

**Comment by AndreiMisiukevich** [comment]
Confirmed this issue. But I don't think it will be possible to fix that

I propose to not use `Clicked` event. Instead I recommend to switch to `Completed`
```xaml
<Button>
	<Button.Effects>
		<xct:TouchEffect Completed="OnCompleted" />
	</Button.Effects>
</Button>
```

**Comment by digitaldirk** [comment]
Thank you that alternative works for me. @AndreiMisiukevich

**Comment by AndreiMisiukevich** [comment]
Hi @digitaldirk unfortunately, we cannot resolve this issue since the second "click" is sent from ButtonRenderer side and there is no way to ignore it.

please use the workaround
