### ISSUE TITLE
[Bug] Vertical and Horizontal options don't work as expected in Popup

### ISSUE THREAD

**Issue by czuck** [xamarin/XamarinCommunityToolkit#1429]
### Description
Changing the HorizontalOptions does change the placement of the popup but changing the VerticalOptions does not change anything.  Adding or removing the AndExpand does not change anything

### Steps to Reproduce

1. Using the Toolkit Test app, edit SimplePopup.xaml and remove the Size property from the Popup tag.  Add VerticalOptions and HorizontalOptions, both set to Center to both the Popup tag and the StackLayout. Add BackgroundColor="Blue" to the Label tag.  Run the test app on Android and navigate to the popup.  Note that the popup is centered horizontally, but is larger both horizontally and vertically than the label. 
2. Edit the file again. change the both layout options in the Popup tag to CenterAndExpand.  Run the app again, note that the popup looks exactly the same, it does not expand horizontally.
3. Repeat step 2 with Start, StartAndExpand, End, and EndAndExpand.  The popup does move horizontally to the Start and End, but is always the same size.
4. Repeat the same steps on iOS.  The results are slightly different - the popup is not full height, but is larger than necessary for the content and adding AndExpand does not change the size.

### Expected Behavior
The popup should size and place on the view the same way other objects using the same layout options would.  If AndExpand is not defined, the popup should not be larger than necessary for the content.  If AndExpand is defined, the popup should expand to cover the entire view.
In my use case I do not know the size of the message that will need to be displayed, so I can not set the size.  

### Actual Behavior
Changing the HorizontalOptions and VerticalOptions does not change the size of the popup, changing the HorizontalOptions will change the placement, but changing the VerticalOptions does not.

### Basic Information

- Version with issue: 1.2.0 pre2
- Last known good version: NA
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  14.20.0.3
  - Android: 11.3.0.1

### Reproduction imagery
With "Start" and "Start"
![image](https://user-images.githubusercontent.com/1641428/123005692-5c64bf80-d36b-11eb-9854-d048dab5ea85.png)

With "End" and "End"
![image](https://user-images.githubusercontent.com/1641428/123006866-2f191100-d36d-11eb-843b-d9b21cd8b107.png)

**Comment by pictos** [comment]
Similar to #937

We didn't implement the LayoutOptions logic

**Comment by czuck** [comment]
Thais interesting, because if you go into the toolkit sample SimplePopup.xaml and type Ver in the Popup tag, VerticalOptions appears, with a message that indicates it is implemented.
![image](https://user-images.githubusercontent.com/1641428/123280329-8b8b4600-d4bd-11eb-8c52-bffae9a3a690.png)
 
Doing the same on another page, such as AboutPage.xaml, and it clearly is not implemented.
![image](https://user-images.githubusercontent.com/1641428/123280654-d0af7800-d4bd-11eb-813f-6d6df650b9d9.png)

**Comment by pictos** [comment]
@ahoefling can you refresh my memory? I believe that this wasn't fully implemented and we opened an issue to implement it later, right?

**Comment by ahoefling** [comment]
`LayoutOptions` are implemented for Popups, but you need to explicitly set the `Size` as the `Content` doesn't automatically resize the popup. If you do not set the `Size` the popup will render full screen, which would explain the issue noted here. As @pictos linked, #937 the Popup doesn't automatically resize, without explicitly setting your popup `Size` you will run into issues like this.

try doing something like this
```xml
<xct:Popup Size="250, 250">
</xct:Popup>
```

You shouldn't have to explicitly set the `VerticalOptions` or `HorizontalOptions` as the default value for the `Popup` control is `CenterAndExpand`. If things aren't working for positioning you can explicitly set it. A good sample control to look at for positioning is the positioning popup. In the ViewModel you will see how it adjusts the position and renders.
https://github.com/xamarin/XamarinCommunityToolkit/blob/dd47000dbc04ef69f78dbc8d140655bb2fbd1460/samples/XCT.Sample/ViewModels/Views/Popups/PopupPositionViewModel.cs#L19-L64

**Comment by czuck** [comment]
Hard coding the size of the popup won't work in my use case because I have created a utility that takes a message and a message type and displays a toast or a popup depending on the type (a success is a toast, a failure is an alert that requires user interaction).  I want to change the alert to a popup because I can change the background color, but since I do not know the size of the message I can't hard code the size of the popup.

**Comment by acaliaro** [comment]
> Hard coding the size of the popup won't work in my use case because I have created a utility that takes a message and a message type and displays a toast or a popup depending on the type (a success is a toast, a failure is an alert that requires user interaction). I want to change the alert to a popup because I can change the background color, but since I do not know the size of the message I can't hard code the size of the popup.

#937
