### ISSUE TITLE
Error:  : XamlC error XFC0000 : Cannot resolve type "TabView"

### ISSUE THREAD

**Issue by roughiain** [xamarin/XamarinCommunityToolkit#1430]
```xml
xmlns:xct="http://xamarin.com/schemas/2020/toolkit"

...
<xct:TabView
     <xct:TabViewItem ...

```

![Screenshot 2021-06-23 at 09 33 40](https://user-images.githubusercontent.com/19661735/123055475-38a28780-d406-11eb-9248-09a60a7a61f3.png)

**Comment by pictos** [comment]
Closing this one in favor of #1311.

This is more an IDE issue than a lib. issue.
