### ISSUE TITLE
[Enhancement] Add support to prevent device audio capture / focus.

### ISSUE THREAD

**Issue by alexanderdibenedetto** [xamarin/XamarinCommunityToolkit#1431]
## Summary

It is sometimes desirable to have a media element play a video without any audio - such as a background video. This video should *not* capture or focus the audio of the device so that users can continue to listen to background music while using the application.

## API Changes

In order to facilitate these changes, I recommend the following:

For Android, you would need to set this prior to view.Start() in the UpdateSource():

```
view.SetAudioFocusRequest(AudioFocus.None);
```

For iOS, in the Play function, you would need to set this prior to avPlayerDiewController.Player.Play() instead of the enum for AVAudioSessionCategory.Playback:

```
Foundation.NSError err = audioSession.SetCategory(AVAudioSessionCategory.Ambient);
```

I recommend a new bindable property such as a AudioFocusMode enumeration defaulting to "Capture" as it does today, but allowing "None" also. This can then be checked in these functions and the appropriate iOS/Android API calls made to either capture or not capture the audio focus of the device.

## Intended Use Case

This is for app developers who want a background video on a page that does not capture that audio playback of the device so that users can continue to listen to their own music while using our application.

## Who Will Do The Work?

- [X] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by alexanderdibenedetto** [comment]
Or perhaps, even simpler, just add an IsMuted ala the WPF version of this control: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.mediaelement.ismuted?view=net-5.0

**Comment by alexanderdibenedetto** [comment]
@jfversluis can I work on this for y'all? My first time contributing to this project so not really clear as to when needs-approval becomes approved or not.

**Comment by pictos** [comment]
@peterfoot what do you think about this feature?

**Comment by pictos** [comment]
> can I work on this for y'all? My first time contributing to this project so not really clear as to when needs-approval becomes approved or not.

Hey @alexanderdibenedetto, for sure you can work on this as soon this gets approved. Sorry for the late reply, we are just fell maintainers and we have to check a lot of PRs and issues and in this particular case, we were focused on the 1.2 release.

**Comment by peterfoot** [comment]
Sounds like a great idea and is definitely worth adding. Hooking it into IsMuted seems a good idea and keeps it in step with WPF/UWP

**Comment by pictos** [comment]
@alexanderdibenedetto, you can work on this one. I labeled this issue as `in-progress`, please let me know if you can't continue working on this. Since this is a new feature please target the `develop` branch

**Comment by alexanderdibenedetto** [comment]
Thanks, will do! :)

**Comment by MaximilianLloyd** [comment]
Exactly what I need! Seeing as this is not implemented yet, is there a workaround to prevent audio capture?

**Comment by alexanderdibenedetto** [comment]
@MaximilianLloyd  sorry for just now getting back to you, was on vacation in Germany! You can implement a custom renderer of the mediaelement and use my code as above in the appropriate functions. That said, I am actively working on this and hopefully it will be accepted and merged soon.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
