### ISSUE TITLE
[Bug] CameraView Shutter stops responding after multiple calls

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1442]
### Description

The `Shutter()` stops responding after multiple calls. I can reproduce sometimes calling just around 10 times.

I have added a record of the issue and a sample [code](https://github.com/GUOLDEV/CameraViewSample).

### Steps to Reproduce

1. Call multiple times `Shutter()`
2. `MediaCaptured` is called until `Shutter()` stops responding

### Expected Behavior

The Shutter does not stop responding after multiple calls.

### Actual Behavior

The Shutter stops responding after multiple calls.

### Basic Information

- Version with issue: [1.2.0](https://github.com/xamarin/XamarinCommunityToolkit/tree/1.2.0)
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  iPhone 11 14.1
  - Android: Samsung Galaxy S8 - Android 9 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone 11 (iOS 14.1)

### Workaround

Close the Page with the `CameraView` and open it again.

### Reproduction Link

https://user-images.githubusercontent.com/22019245/123719325-9c282b80-d8c4-11eb-8e65-a1f3ffd44764.mov

https://user-images.githubusercontent.com/22019245/123880512-2ab0b180-d986-11eb-9202-41e17e138eee.mp4

**Comment by GUOLDEV** [comment]
Please let me know if there is a workaround or if I am missing something on how to correctly use the `CameraView`. Thanks in advance.

**Comment by jfversluis** [comment]
Did you happen to test it on Android as well by any chance?

**Comment by GUOLDEV** [comment]
Hi @jfversluis, it is more difficult to reproduce on Android, but it happens in the same way, after multiple calls it stops responding. I have uploaded a record testing on Android Emulator, but that happens on Android real devices as well, we have tested on Samsung Galaxy S8 - Android 9.

**Comment by GUOLDEV** [comment]
@jfversluis I have pushed a [fix](https://github.com/xamarin/XamarinCommunityToolkit/pull/1535) for the `CameraView` shutter not responding, could you please have a look when you have a chance?

**Comment by jfversluis** [comment]
@GUOLDEV I merged the PR, looked good, thanks!

Just 1 thing, I see you also mention it happens on Android. This fix was just for iOS?

**Comment by GUOLDEV** [comment]
@jfversluis thanks for reviewing the PR, and yes, the fix was just for iOS. For Android I couldn't reproduce while debugging, so now that iOS is fixed I can focus on Android.

**Comment by GUOLDEV** [comment]
@jfversluis I have tested on real device Galaxy S9+ Android 10 and Emulator Android 9, XCT 1.2.0 works fine, I couldn't reproduce the issue. 
As reported I could reproduce the issue on Samsung Galaxy S8 - Android 9 before, but I don't have access to that device at the moment, once I have access to it I will test again.
I think we can close this issue, what do you think?

**Comment by jfversluis** [comment]
Fixed by #1535
