### ISSUE TITLE
CameraView issue - EventToCommandBehavior: Couldn't resolve the event

### ISSUE THREAD

**Issue by slprog1** [xamarin/XamarinCommunityToolkit#1443]
Hello there,
I'm using CameraView and EventToCommandBehavior to create some sort of a simple app that makes photos.
But I've faced with the issue of using EventToCommandBehavior. When running app in Release mode on both android emulator and real device I do see the following error in Application Output:

> [MonoDroid] UNHANDLED EXCEPTION:
> [MonoDroid] Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
> [MonoDroid]   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
> [MonoDroid] android.runtime.JavaProxyThrowable: System.ArgumentException: EventToCommandBehavior: Couldn't resolve the event.
> [MonoDroid] Parameter name: EventName

The code itself isn't that complicated:
 ```
<xct:CameraView
                x:Name="CameraView"
                BindingContext="{Binding CameraModel}"
                CameraOptions="{Binding CameraOption}"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand"
                CaptureMode="Photo">
                <xct:CameraView.Behaviors>
                    <xct:EventToCommandBehavior EventName="MediaCaptured" Command="{Binding CaptureCommand}" />
                </xct:CameraView.Behaviors>
</xct:CameraView>
```

The Environment is the latest one at this moment:

> Visual Studio Community 2019 for Mac
> Version 8.10.3 (build 15)
> Installation UUID: c4debf69-38dc-430a-b7ff-71b5f73fb9f3
> GTK+ 2.24.23 (Raleigh theme)
> Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
> 
> Package version: 612000140
> 
> Mono Framework MDK
> Runtime:
> Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
> Package version: 612000140
> 
> Roslyn (Language Service)
> 3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
> 
> NuGet
> Version: 5.9.0.7134
> 
> .NET Core SDK
> SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
> SDK Versions:
> 	5.0.301

Thanks in advance for helping!!

**Comment by GUOLDEV** [comment]
Hi @slprog1, could you please share the Command that you are Binding to? It works for me without any error on Android, but I had to specify the event args as `MediaCapturedEventArgs` :
```
public DelegateCommand<MediaCapturedEventArgs> MediaCapturedCommand { get; }

private void ExecuteMediaCapturedCommand(MediaCapturedEventArgs e)
{
...
}
```

**Comment by slprog1** [comment]
Hi @GUOLDEV , thanks for replying!! 
Regarding the command I'm binding to, well it's nothing special here, just a command, which was accepting the object as a parameter type. I did try to specify the exact type **MediaCapturedEventArgs** as you mentioned, but still the behaviour is the same - in Release mode it does no work(
When adding event handler and doing all needed stuff for me there - it works fine. But that is the thing - I need to "bind" the event to command from my ViewModel :)

**Comment by GUOLDEV** [comment]
All good 👍 by the way, the code that I posted is in the ViewModel and it works. When I have a chance I will try in release mode as you reported to make sure it works.

**Comment by GUOLDEV** [comment]
Hi @slprog1 I can reproduce the issue that you reported, `CameraView.Behaviors` works only in `Debug` Mode.

**Comment by pictos** [comment]
@GUOLDEV can you change the Linker configuration in DEBUG mode to be Link SDK and assemblies? After that let me know if the issue happens in Debug as well. Thanks in advance.

**Comment by GUOLDEV** [comment]
@pictos thanks mate for the prompt reply. I have tested and it stops working setting the Linking to "Sdk Assemblies Only" or "Sdk and User Assemblies" in DEBUG mode. I have tested on Galaxy S9+ Android 10. Please let me know if I can help with any other info.

![image](https://user-images.githubusercontent.com/22019245/124867494-8bcd2a80-e001-11eb-8cb5-921c3cbc7aa2.png)

**Comment by pictos** [comment]
Yeah, this looks like a linker issue. I'll try to investigate this tomorrow or next week. Thanks for your help ❤

**Comment by pictos** [comment]
@GUOLDEV if you can attach your repro here will be amazing!

**Comment by GUOLDEV** [comment]
@pictos do you mean the sample code?

**Comment by GUOLDEV** [comment]
@pictos do you think it is affecting just CameraView or other controls in general? Sorry, I didn't have time to try other controls to confirm that. If it is just CameraView it would be good to add the CameraView label.

**Comment by pictos** [comment]
@GUOLDEV I didn't test either, for now, I'll assume that issue is general

**Comment by GUOLDEV** [comment]
@pictos I have created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1503) for the CameraView Linker issue. Could you please have a look when you have a chance? Thanks in advance.

**Comment by workgroupengineering** [comment]
I tried with release 1.3.0-pre1, but the issue is still present.

**Comment by GUOLDEV** [comment]
Hi @workgroupengineering, what is the event that you are using? It would be great if you could add more info 👍

**Comment by workgroupengineering** [comment]
I using MediaCaptured 
XCT 1.3.0-pre1
Tested on Android 8 and 10 Emulator in Release mode.

If add ``MediaCaptured="CameraView_MediaCaptured`` in xaml with empty eventhandler it work.

**Comment by GUOLDEV** [comment]
Hi @workgroupengineering as I thought, 1.3.0-pre1 doesn't have the fix, it's merged into dev branch only.

**Comment by GUOLDEV** [comment]
Hi @workgroupengineering 1.3.0-pre2 was just released, please have a look 👍
