### ISSUE TITLE
[Enhancement] More complete set of animations

### ISSUE THREAD

**Issue by bijington** [xamarin/XamarinCommunityToolkit#1447]
## Summary

Provide a larger set of animations to the toolkit.

Please advise on how it would be best to receive these changes. I currently count 97 animations across 16 groupings from the linked page: https://animate.style. Perhaps supplying an initial grouping (e.g. `Attention seekers`) would serve as a good starting point? I appreciate that supplying all those changes in a single hit could make reviewing more complex. Some of the much more complex ones I may in fact struggle with in general anyway (`lightSpeedInRight`).

## API Changes

I currently plan to make a few additions to hopefully keep the potential for this feature open to the consumer of the toolkit. For the purpose of showing my planned changes I will simply refer to a single animation addition for now `tada`.

### VisualElementExtension

Add new extension method(s) to enable invoking the animation directly on the `VisualElement`:

```csharp
// Calls to the below method but offers the simplicity of invoking without `IEnumerable`.
public static void AnimateTada(this VisualElement visualElements)

// This allows us to commit a single Animation for any number of elements.
public static void AnimateTada(this IEnumerable<VisualElement> visualElements)
```

There will also be the potential to add further parameters in order to be able to fine tune the animation for things like `Easing`, `duration`, or maximum/minimum values for scales or rotation angles.

### Behaviors / Animations / AnimationTypes

Additions of new `AnimationBase` implementations to allow for the animations to be defined in XAML and invoked in the usual manner. 

```csharp
public class TadaAnimation : AnimationBase
```

Then these rather light implementations would simply invoke the extension methods defined above.

Currently a number of my animations utilise the `Animation` class in order to achieve some of the more complex sequences, I assume this is fine to fit within the existing `AnimationBase` approach?

## Intended Use Case

To make all our apps look as pretty and fun as possible 😄 

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

## Discussed in https://github.com/xamarin/XamarinCommunityToolkit/discussions/1441

<div type='discussions-op-text'>

<sup>Originally posted by **bijington** June 28, 2021</sup>
I have recently implemented some animations based on this CSS site:
https://animate.style

Tada being a big favourite now (see attached)

https://user-images.githubusercontent.com/17139988/123698685-5896d880-d856-11eb-976c-b4f208e5b73b.mov

I wanted to investigate whether you would like a more complete set of animations?

My original approach has been to wrap these animations up inside extension methods so that they can easily be shared and triggered outside of user interaction. Would this approach suit XCT or would you prefer to keep them under the Behaviors approach and simply invoke them via a Command?
</div>

**Comment by pictos** [comment]
Hey @bijington thanks for bring all those goods to the XCT❣ In order to make the reviewers life easy can we split those 97 animations in different PRs? 

About the implementation let me ask some questions, that way I'll be able to brainstorm with you some specs for this API.

1. So talking about the extension methods `public static void AnimateTada(this VisualElement visualElements)` do we have one method per animation?
2. You said
> There will also be the potential to add further parameters in order to be able to fine-tune the animation for things like Easing, duration, or maximum/minimum values for scales or rotation angles.

If we have more properties to handle the animation, I would say that will be good to use the same approach used on the `BindableProperty.Create` method. And having an `Enum` that represents the animation that we want to trigger, something like (don't be tied on names)
```csharp
var lbl = new Label();
var TadaAnimation = XCT.CreateAnimation(animation: XCTAnimation.Tada, element: lbl, duration: 2, easing: Easing.Linear, maximum: 10, minimum: 2);

TadaAnimation.Commit();
TadaAnimation.Abort();
```

I'm not sure if my suggestion makes sense because I don't know how you implemented those animations.

**Comment by bijington** [comment]
@pictos please see my response(s) below:

More than happy to send in separate PRs for this stuff 😄. Hopefully they should end up being relatively small.

Yes my plan would be to have a single method per animation just with a load of default parameters. I am open to this not being required however, hopefully I can explain my current usage and I am more than happy to have a suggestion on a better approach :).

```csharp
public static Animation AnimateTada(
    this IEnumerable<View> views,
    int duration = 500, 
    double rotationAngle = 3,
    double minScale = 0.9,
    double maxScale = 1.1
    Easing easing = Easing.Linear)
{
    // Better names to be used in production honest :)
    var a = new Animation();

    foreach (var view in views)
    {
        // TODO: Do we need to take in to account any existing `view.Scale` or `view.Rotation` values?
        a.Add(0, 0.2, new Animation(v => view.Scale = v, 1, minScale));
        a.Add(0.2, 0.9, new Animation(v => view.Scale = v, minScale, maxScale));
        a.Add(0.9, 1.0, new Animation(v => view.Scale = v, maxScale, 1));

        a.Add(0, 0.2, new Animation(v => view.Rotation = v, 0, -rotationAngle));
        a.Add(0.2, 0.4, new Animation(v => view.Rotation = v, -rotationAngle, rotationAngle));
        a.Add(0.4, 0.6, new Animation(v => view.Rotation = v, rotationAngle, -rotationAngle));
        a.Add(0.6, 0.8, new Animation(v => view.Rotation = v, -rotationAngle, rotationAngle));
        a.Add(0.8, 1.0, new Animation(v => view.Rotation = v, rotationAngle, 0));
    }

    a.Commit(
        owner: views.First(), // Should probably pass in an owner parameter
        name: "Tada",
        length: duration,
        easing: easing,
        finished: (x, y) => { }); // Expose this also

    return a;
}
```

I am more than happy to remove the `Commit` logic from here and return the animation that a consumer can commit.

I use it this way for some animations because I am invoking these animations from UI code and need it to apply to multiple controls at once. 

In fact I like your approach for the `XCT.CreateAnimation` method. I guess there could be 2 methods one taking a single `element` and another taking `IEnumerable<VisualElement> elements`. 

If we didn't perform the `Commit` inside the creation of the animation method then the majority of the parameters might not be required however, I do quite like being able to provide most of that without the consumer needing to consider the defaults.

**Comment by pictos** [comment]
So if we implement the animations methods as public, we can't change anything there because will be a breaking change
`public static Animation AnimateTada( ... ) // we can't modify parameters`
 said that if we have some public wrapper like `XCT.CreateAnimation` we can implement the animation method as `private` and have more liberty to modify how the method looks like and just exposing a new overload for the `XCT.CreateAnimation`.

I think that returning the `Animation` object without committing will be better to give devs _more power_ to define when they want to trigger the animation. 

Instead of having two versions, one with one `VisualElement` and another with `IEnumerable<VisualElement> elements`, I believe that we can use the `params` keyword, them users will be able to add one or more `VisualElement`s, what do you think?

Just to illustrate my idea:

```csharp
public static Animation CreateAnimation(
    int duration, 
    double rotationAngle,
    double minScale,
    double maxScale,
    Easing easing,
    params View[] views);

// All methods with the same parameter as provided by `CreateAnimation`
private Animation Tada();
private Animation Shake();
private Animation XCTRules();
```
You're more than welcome to disagree with my ideas ;D

**Comment by bijington** [comment]
You have a much better hat at considering public APIs 😄. I am happy to avoid using the extension method approach, not doing so simplifies things like allowing the use of `params` like you have suggested.

I am happy with letting the dev calling `Commit` as the syntax would be fluent in this scenario:
```CSharp
XCT.CreateAnimation(xyzzy).Commit();
```

I guess the implementation for `CreateAnimation` will pretty much be a large switch statement and we pass an enum `AnimationType` or similar? As a slight tweak I am wondering whether each animation implementation could/should be it's own class and a subclass of `Animation`. This could make the code more testable if that is even possible with animations 😄 

One thing that concerns me initially is how many parameters we might need to pass in to `CreateAnimation` and how to make sure they are all relevant because some animations won't even perform a rotation. I do like the general concept though.

I think I am going to try and start playing around with the toolkit and see how this implement might fit and whether I hit any obvious hurdles with 2 very different animations.

**Comment by pictos** [comment]
@bijington 
> I guess the implementation for CreateAnimation will pretty much be a large switch statement and we pass an enum AnimationType or similar? 

No, we can grab the Maui idea and have a `Dictionary<Enum, Func<Animation>>` or something like that, that will be much cleaner than having a huge switch statement.

> how to make sure they are all relevant because some animations won't even perform a rotation. I do like the general concept though.

We need to think about it... Maybe a builder/fluent pattern, but let's see how your PR will look

**Comment by bijington** [comment]
> No, we can grab the Maui idea and have a `Dictionary<Enum, Func<Animation>>` or something like that, that will be much cleaner than having a huge switch statement.
> 

Sounds good! Any reason to avoid a giant switch statement is good in my book 😄 

> We need to think about it... Maybe a builder/fluent pattern, but let's see how your PR will look

I have some ideas on how this might work based on some tests I did on Friday. I think I could get it fluent without needing a builder pattern but more than happy for you to make a decision on that once I submit something.
