### ISSUE TITLE
[Enhancement] Implement EnumToListConverter and EnumToNameConverter

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1449]
## Summary

A converter that retrieves an array of the values of the constants in a specified enumeration.

- EnumToListConverter
- EnumToNameConverter

I have created a draft [PR](#1448) for better visualization of the Converter concept.

## API Changes

NA

## Intended Use Case

I like to use Enums in various scenarios to simplify the logic, for defining QuestionAnswer for example:

```
public enum QuestionAnswer
{
  Undefined,
  Yes,
  No
}
```

```
<Picker ItemsSource="{Binding SelectedEnumType, Converter={StaticResource EnumToListConverter}}" />
```

https://user-images.githubusercontent.com/22019245/124061952-2f9f5f00-da73-11eb-8e37-4e900bdad0b1.mov

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@GUOLDEV can you please fill this issue with more information?

**Comment by GUOLDEV** [comment]
@pictos I have updated the description.

**Comment by GUOLDEV** [comment]
Hey @pictos @AndreiMisiukevich, is there something else that I need to add to this ticket to get this feature considered? Thanks 🙏

**Comment by pictos** [comment]
@GUOLDEV sorry just missed this one. I'll take a look during the week

**Comment by GUOLDEV** [comment]
@pictos any chance to consider this feature?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
