### ISSUE TITLE
[Enhancement] Implement EnumToObjectConverter

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1450]
## Summary

A converter that retrieves an object based on specified enumeration(s).

I have created a draft [PR](#1517) for better visualization of the Converter concept.

## API Changes

NA

## Intended Use Case

```
<pages:BasePage.Resources>
    <xct:EnumToObjectConverter DefaultObject="icon_flash_off.png" x:Key="FlashModeToObjectConverter">
        <xct:EnumToObjectConverter Object="icon_flash_on.png">
            <xct:CameraFlashMode>On</xct:CameraFlashMode>
        </xct:EnumToObjectConverter>
        <xct:EnumToObjectConverter Object="icon_flash_off.png">
            <xct:CameraFlashMode>Off</xct:CameraFlashMode>
        </xct:EnumToObjectConverter>
        <xct:EnumToObjectConverter Object="icon_flash_auto.png">
            <xct:CameraFlashMode>Auto</xct:CameraFlashMode>
        </xct:EnumToObjectConverter>
    </xct:EnumToObjectConverter>
</pages:BasePage.Resources>
```

```
<Image Source="{Binding FlashMode, Converter={StaticResource FlashModeToObjectConverter}}" />
```

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by GUOLDEV** [comment]
Hi @AndreiMisiukevich, could you please have a look at this converter idea when you have a chance? I have pushed a PR that is in draft as it's not approved yet. Thanks in advance 🙏

**Comment by GUOLDEV** [comment]
@pictos any chance to consider this feature?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
