### ISSUE TITLE
TouchEffect doesnt work in UWP? How to use LongPressCommandParameter?

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#1456]
### Discussed in https://github.com/xamarin/XamarinCommunityToolkit/discussions/1454

<div type='discussions-op-text'>

<sup>Originally posted by **TuxCZ** July  1, 2021</sup>
Hello,
I have problem with a touch effect. It works perfectly in the Android APP, but in UWP doesnt. 

My UWP target version is Windows 10, 2004 (Build 19041) and Min version 1803, build 17134...

I tried this fix:
```
 var assembliesToInclude = new List<Assembly>()
                {
                    typeof(Xamarin.CommunityToolkit.Effects.TouchEffect).GetTypeInfo().Assembly
                };
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

but it doesnt helped me. I changed ,,Compile with .NET Native tool chain" but it doesnt helped too.. I tried to compile UWP with different target and min versions, but it doesnt work...

My second question is how to use LongPressCommandParameter? I have entry defined like this:
` <Entry x:Name="txtProjectName" Text="{Binding Project.Name}" Style="{StaticResource EntrySecondaryStyle}"
                               xct:TouchEffect.LongPressCommand="{Binding LongPressCommand}"
                               xct:TouchEffect.LongPressCommandParameter="{Binding .}"
                               xct:TouchEffect.LongPressDuration="1500"/>`

And I need to get LongPressCommandParameter (sender) in the code... How can I do that? </div>

**Comment by AndreiMisiukevich** [comment]
@pictos @jfversluis hey friends, could you please check this issue with UWP versions?
How should users work around it?

Does TouchEffect still work on UWP in main? (I think it should)

**Comment by AndreiMisiukevich** [comment]
@TuxCZ you can try to install the `nightly` version of XCT (it contains all the latest changes)

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/README.md#installation

**Comment by TuxCZ** [comment]
> @TuxCZ you can try to install the `nightly` version of XCT (it contains all the latest changes)
> 
> https://github.com/xamarin/XamarinCommunityToolkit/blob/main/README.md#installation

Ok, I will try it... But i must figure out how to install nightly version...

**Comment by AndreiMisiukevich** [comment]
source: `https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json`

https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops&tabs=windows#2-set-up-visual-studio

**Comment by TuxCZ** [comment]
> source: `https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json`
> 
> https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops&tabs=windows#2-set-up-visual-studio

Thx for the link... I tried it, I installed preview 1072, but it doesn´t helped...

**Comment by AndreiMisiukevich** [comment]
@pictos could you please check it?

**Comment by pictos** [comment]
@AndreiMisiukevich just saw it right now, sure I'll test by tomorrow and let you know

**Comment by pictos** [comment]
@AndreiMisiukevich LongPress is working on our sample in `main` branch

**Comment by AndreiMisiukevich** [comment]
@TuxCZ can you please provide a sample?

**Comment by TuxCZ** [comment]
> @TuxCZ can you please provide a sample?

I created sample APP... 
https://file.io/ii79QBsL34sz

**Comment by AndreiMisiukevich** [comment]
@TuxCZ 
![image](https://user-images.githubusercontent.com/10124814/124397903-2502f500-dd13-11eb-8edb-c88b9dde0b73.png)


Can you upload a zip archive here?

**Comment by TuxCZ** [comment]
[UWPSample.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6760512/UWPSample.zip)

**Comment by AndreiMisiukevich** [comment]
@pictos could you please check provided sample on UWP?

Thanks

**Comment by pictos** [comment]
@AndreiMisiukevich @TuxCZ I was able to make the sample work
![image](https://user-images.githubusercontent.com/20712372/124401185-40173a00-dcfe-11eb-88ae-a40a67940043.png)

The issue is related to the UWP target version. You need to have your version configuration like this to make it work
![image](https://user-images.githubusercontent.com/20712372/124401198-558c6400-dcfe-11eb-86fc-bdd52f5716f0.png)

@TuxCZ we're working harder to put this fix on the next stable release (1.3)

**Comment by TuxCZ** [comment]
Thx, it works for me now on boxview too, but if u change boxview to entry or different component it stopped working...

**Comment by AndreiMisiukevich** [comment]
@TuxCZ so it doesn't work if you use ContentView or StackLayout?

**Comment by TuxCZ** [comment]
> @TuxCZ so it doesn't work if you use ContentView or StackLayout?

This works if I set target and max version how u said:
```
<BoxView WidthRequest="100" HeightRequest="100" Text="Test" 
                 xct:TouchEffect.LongPressCommand="{Binding LongPressCommand}" 
                 xct:TouchEffect.LongPressCommandParameter="{Binding .}" 
                 xct:TouchEffect.LongPressDuration="1500"/>
```

but this doesnt work in UWP, only in android project:
```
<Entry WidthRequest="100" HeightRequest="100" Text="Test" 
                 xct:TouchEffect.LongPressCommand="{Binding LongPressCommand}" 
                 xct:TouchEffect.LongPressCommandParameter="{Binding .}" 
                 xct:TouchEffect.LongPressDuration="1500"/>
```

**Comment by AndreiMisiukevich** [comment]
@TuxCZ yeah, it can be an issue that Long Press is not working with entry on UWP, but you mentioned that ``` if u change boxview to entry or different component it stopped working```

So, doesn't it work only with Entry or with all other views except BoxView? Does it work well with ContentView, StackLayout, Label etc.

**Comment by TuxCZ** [comment]
> @TuxCZ yeah, it can be an issue that Long Press is not working with entry on UWP, but you mentioned that ` if u change boxview to entry or different component it stopped working`
> 
> So, doesn't it work only with Entry or with all other views except BoxView? Does it work well with ContentView, StackLayout, Label etc.

I tested other controls and all works except entry and the editor...

**Comment by AndreiMisiukevich** [comment]
@TuxCZ feel free to open a different issue (but I am not sure we will be able to fix it soon)
