### ISSUE TITLE
[Enhancement] Effect to control the frames border thickness

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#1457]
## Summary

An effect that gives you control over the frames border thickness.

Not sure if this is possible or not, if it is possible, if someone could give me some pointers I'll try and implement it myself.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
I don't think it's possible without hacking. I quickly checked Google as well as the iOS implementation and there are some fields that are private and we can't access with renderers or effects :(

While I'd love to provide a solution, I won't go as far as hacking things in this Toolkit to make it work. Let's hope we can add this early on in .NET MAUI!

Thanks for the suggestion though!
