### ISSUE TITLE
[Enhancement] Add NumberOfTapsRequired property in TouchEffect

### ISSUE THREAD

**Issue by nacompllo** [xamarin/XamarinCommunityToolkit#1461]
## Summary
My suggestion would be to add a new property called NumberOfTapsRequired to the TouchEffect, similar to the one that the [gesture recognizer](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/tap) has to establish how many clicks are necessary for the associated command to be executed.

## API Changes
e.g.
```
<StackLayout xct:TouchEffect.Command="{Binding SampleCommand}"
             xct:TouchEffect.CommandParameter="{Binding .}"
             xct:NumberOfTapsRequired="2">
```

## Intended Use Case
This functionality could be used in countless cases.

## Who Will Do The Work?
- [x]  Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
