### ISSUE TITLE
[Enhancement] DrawingView multiple line support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#1462]
## Summary

Allow drawing multiple lines

![image](https://user-images.githubusercontent.com/33021114/124515592-7e892380-dde8-11eb-8b76-47860c386ff8.png)

## API Changes

**new** 
properties: 
- Lines. It is a Collection of Lines.
- MultiLineMode. "False" -> Erase the image on Starting drawing. (Default value). "true" -> Add as many lines as you need

classes: 
- Line. I should have an Observable Collection of Points.

**update**:
rename DrawingCompletedCommand to DrawingLineCompletedCommand

## Intended Use Case
The same as for the current DrawingView.
Most likely for the cross-platform Paint application.

## Further improvements (most likely out of scope of this story):
1. Each line has its own settings (LineColor, LineWidth).
2. Line can be selected.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Sounds good to me! The only thing we need to think about is how this works together with ClearOnFinish.

I guess we need some property to enable “multi line mode”? Because right now if you start drawing one line and then the second it erases the first, or with ClearOnFinish enabled it erases as soon as you stop the first line.

you have a proposal for that?

**Comment by VladislavAntonyuk** [comment]
ClearOnFinish = "True" -> Erase the image on Finish drawing. It will be independent from MultiLineMode.
MultiLineMode = "False" -> Erase the image on Starting drawing. (Default value)
MultiLineMode = "true" -> Add as many lines as you need

**Comment by jfversluis** [comment]
And what happens when someone sets MultiLineMode to true _and_ ClearOnFinish to true? 😬

When do you know when the drawing is finished in a multi line scenario?

**Comment by VladislavAntonyuk** [comment]
Just when you finished the line it will be cleared. It’s independent from MultiLineMode. ClearOnFinish always wins.
It is a simplest scenario. We can extend with time-out property later. I think it is now out of scope

**Comment by jfversluis** [comment]
Ah so that means the drawing completed command is fired after each line then?

**Comment by VladislavAntonyuk** [comment]
yes, But I think it's better to name it DrawingLineCompletedCommand

**Comment by jfversluis** [comment]
Could you update the initial post with some C# code of the changes you want to make? Which properties you want to add, remove, rename, etc.

**Comment by VladislavAntonyuk** [comment]
I am still thinking about the possible changes which we'll have. let's update what we have so far

**Comment by VladislavAntonyuk** [comment]
@jfversluis I created a draft PR https://github.com/xamarin/XamarinCommunityToolkit/pull/1475. What do you think?

**Comment by VladislavAntonyuk** [comment]
@jfversluis implemented for all platforms. Verified on Android,
I will check it on iOS. If everything is fine, I will publish the PR.

**Comment by jfversluis** [comment]
Fixed
