### ISSUE TITLE
[Enhancement] Add `DrawingCompleted` Event to `DrawingView`

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#1466]
## Summary

To support both data binding and code-behind scenarios we want to add a `DrawingCompleted` event next to the already existing command with the same name.

## API Changes

Add:
* `DrawingView.DrawingCompleted` event
* `DrawingCompletedEventArgs` with the points that are in the drawing

## Intended Use Case
For when I don't want to use data-binding

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by VladislavAntonyuk** [comment]
I am willing to take this on myself

**Comment by bijington** [comment]
@VladislavAntonyuk have you looked in to this yet? I was just about to send in a PR for it

**Comment by bijington** [comment]
@VladislavAntonyuk I have gone ahead and raised my PR in a draft state as I found a potentially serious bug with the `DrawingView`. I am still happy for you to push your stuff and claim the PR if you had already looked in to the change 😄

**Comment by VladislavAntonyuk** [comment]
@bijington don't worry, I will migrate your changes to the https://github.com/xamarin/XamarinCommunityToolkit/issues/1462

**Comment by bijington** [comment]
@VladislavAntonyuk Great. Sorry just to be clear does that mean I should proceed with this and you will merge later or leave this and you can pick the best bits? I see there is quite a change to #1462

**Comment by VladislavAntonyuk** [comment]
My PR is a breaking change and it will be at least in XCT 1.3.
Your changes may appear in 1.2.1.
It’s up to you.

**Comment by bijington** [comment]
@VladislavAntonyuk great thanks. I will put that decision to the maintainers @jfversluis @pictos @AndreiMisiukevich 

If it does go ahead I'll be happy to assist with any merges to your stuff if you need

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
