### ISSUE TITLE
[Enhancement] Shell Support for Popups

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#1470]
## Summary

Right now, I think because of the difference in navigation, we don't support Shell for Popups. It would be cool if we could do that.

At this time putting this out there to gauge interest, not really investigated if it is even possible or how.

## API Changes

Not sure if we would actually need changes on the API but more on the implementation and switch between different navigation mechanisms under the hood.

## Intended Use Case
Enable Popups with Xamarin.Forms Shell

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
@ahoefling can it be done? Any perspective on this one?

**Comment by ahoefling** [comment]
I'll need to chat with @PureWeen and see what we can do. We can certainly add it but adding it to work with the Shell navigation may be tricky.

Are there extension points in the navigation API for shell?  Some things to consider
- Do we want to use the string/uri based navigation to display the popup?
- Do we want to create an extension method on the Shell root object?

I would argue it makes sense to stay away from the Shell navigation and add extension methods

**Comment by pictos** [comment]
Are you able to do `Shell.Current.Navigation.ShowPopup()`?

**Comment by ahoefling** [comment]
It has been a long while since I used shell, if the `INavigation` interface is available like that it should be an update to documentation than a code change.

**Comment by stephenhauck** [comment]
Can someone provide an example / confirm  how to use popup in Xamarin Shell ?

**Comment by stephenhauck** [comment]
ok well I built an example .... enjoy
https://github.com/stephenhauck/ZXingPopup

> Can someone provide an example / confirm how to use popup in Xamarin Shell ?
> 
> I'm used to simple navigation like this ..
> 
> ```
> var route = $"{nameof(ScanBarcodeView)}?_viewTitle=Scan Product Barcode";
> await Shell.Current.GoToAsync(route);
> ```

**Comment by pictos** [comment]
@stephenhauck did you try to use the Navigation object in Shell? I mentioned in this issue

**Comment by stephenhauck** [comment]
The code is there for you ....
![image](https://user-images.githubusercontent.com/12648793/132946699-47ca5436-6775-44da-9996-35acf7950e9b.png)

**Comment by pictos** [comment]
@stephenhauck can you confirm that works? If so I'll close this issue. Thanks

**Comment by stephenhauck** [comment]
Download my sample and run it …

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
