### ISSUE TITLE
[Bug] DrawingCompletedCommand improperly implemented

### ISSUE THREAD

**Issue by dansiegel** [xamarin/XamarinCommunityToolkit#1474]
### Description

The Renderers seems to have improperly implemented calling the Command. As a matter of standard practice, CanExecute for a Command expects the same value that will be passed to Execute. The purpose of CanExecute is to evaluate the Command Parameter to determine whether or not it should execute. The sample below points to the UWP renderer, but it appears all of the platforms have implemented this the same wrong way.

https://github.com/xamarin/XamarinCommunityToolkit/blob/17a23ee6fb03ccb1f473f362eb5d86fce2ca71d0/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.uwp.cs#L82-L83

### Steps to Reproduce

n/a

### Expected Behavior

A Command's `CanExecute(object obj)` should have the same object passed in that is passed into the `Execute(object obj)`.

### Actual Behavior

A null value is passed to CanExecute, the points are passed to Execute.

### Basic Information

- Version with issue:  1.2

### Workaround

n/a

### Reproduction imagery

n/a

### Reproduction Link

n/a

**Comment by jfversluis** [comment]
Good catch, thanks!

**Comment by bijington** [comment]
I am in and working around the `DrawingView` so happy to pick this up

**Comment by VladislavAntonyuk** [comment]
Fix in https://github.com/xamarin/XamarinCommunityToolkit/pull/1475

**Comment by pictos** [comment]
Closing this issue, since the related PR is already merged.
