### ISSUE TITLE
[Bug] All instances of DrawingView share an instance of Points

### ISSUE THREAD

**Issue by bijington** [xamarin/XamarinCommunityToolkit#1476]
### Description

Basically the call to initialise `Points` with `BindableProperty.Create(defaultValue: new ObservableCollection<Point>())` results in that instance being used for all instances of `DrawingView`.

### Steps to Reproduce

The following test case currently passes in the 1.2.0 codebase

```csharp
[Test]
public void ReferenceEquality()
{
    var drawingViewOne = new DrawingView();
    var drawingViewTwo = new DrawingView();

    drawingViewOne.Points.Add(Point.Zero);

    drawingViewTwo.Points.Clear();

    Assert.IsEmpty(drawingViewOne.Points);
    Assert.IsTrue(ReferenceEquals(drawingViewOne.Points, drawingViewTwo.Points));
}
```

### Expected Behavior

Each instance of `DrawingView` should have its own instance of `Points`.

### Actual Behavior

They all use the same instance.

### Basic Information

- Version with issue: 1.2.0 (`main`)
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
n/a

### Reproduction imagery
n/a

### Reproduction Link
n/a

**Comment by bijington** [comment]
For the record I am willing to fix this

**Comment by jfversluis** [comment]
Go for it!
