### ISSUE TITLE
[Bug]  Shadow Effect does not work with UWP with the 1.2.0 release.

### ISSUE THREAD

**Issue by shrikantbmali** [xamarin/XamarinCommunityToolkit#1477]
### Description
Shadow Effect does not work with UWP with the 1.2.0 release.
### Steps to Reproduce

1.  Create a simple app add the NuGet package reference and paste the code from Sample App.
2.  Or, you can choose to use the Xamain Community toolkit project but with NuGet package reference instead of project reference to Xamarin Community toolkit
3. With this setup it does not work.

### Expected Behavior
Shadow Effect works with UWP

### Actual Behavior
Shadow effect does not work with UWP

### Basic Information
- Nuget Packages: 1.2.0

**Comment by pictos** [comment]
@shrikantbmali can you check [if this ](https://github.com/xamarin/XamarinCommunityToolkit/issues/1456#issuecomment-873674900)workaround solves your issue?

**Comment by shrikantbmali** [comment]
@pictos that make it work, thanks...
