### ISSUE TITLE
[Bug] Unable to use drawing canvas when targeting UWP

### ISSUE THREAD

**Issue by bootcom-uk** [xamarin/XamarinCommunityToolkit#1479]
### Description

I am unable to draw anything when using the drawing canvas in my UWP app, I don't have this issue when targeting Android.

### Expected Behavior

Ability to draw a link in the UWP application.

### Actual Behavior

Nothing being drawn.

### Basic Information

Target Version: Windows 10, version 1903 (10.0; Build 18362)
Min Version; Windows 10, version 1803 (10.0; Build 17134)
Running Debug > x86
Xamarin Forms Nuget: 5.0.0.2012
Xamarin.Community Toolkit Nuget: 1.2.0

**Comment by VladislavAntonyuk** [comment]
most likely related to https://github.com/xamarin/XamarinCommunityToolkit/issues/1308

**Comment by VladislavAntonyuk** [comment]
@bootcom-uk By the way could you please attach a small repro?

**Comment by bootcom-uk** [comment]
@VladislavAntonyuk - have uploaded to a public repo https://github.com/bootcom-uk/Signature. If you want me to upload separately please let me know and I'll do that. Thanks.

**Comment by VladislavAntonyuk** [comment]
Set min version to 19041:
![image](https://user-images.githubusercontent.com/33021114/125619897-654012dd-ad6a-42f8-8ce0-64d97f9b5104.png)

![image](https://user-images.githubusercontent.com/33021114/125619856-997844bb-ea1e-4a06-9ed7-c13377af4429.png)

**Comment by VladislavAntonyuk** [comment]
@jfversluis is it a nuget issue or should we create a different target framework for different uwp versions?

**Comment by bootcom-uk** [comment]
@VladislavAntonyuk confirmed working. Thank you.

For now will add a reference back to this in my readme file.
