### ISSUE TITLE
[Bug] Unable to run Unit Test after adding the `XamarinCommunityToolkit` package to a project

### ISSUE THREAD

**Issue by alexeystrakh** [xamarin/XamarinCommunityToolkit#1482]
### Description

Unable to run Unit Test after adding the `XamarinCommunityToolkit` package to a project. I have a sample `Xamarin.Forms` app where I want to cover the shared core with Unit Tests (my view models and services). A complete sample to reproduce the issue is in [this repository (`xct-wpf-issue` branch)](https://github.com/xamcat/xamarin-unittesting/tree/xct-wpf-issue)

### Steps to Reproduce

1. In VS4Mac (or VS 2019), create a netstandard2.1 project library with some code to unit test (Proj1)
2. In VS4Mac (or VS 2019), create a net5.0 Unit Tests project (Proj2)
3. Add the `XamarinCommunityToolkit` package to both Proj1 and Proj2 projects
4. Run unit tests with `dotnet run` comman 

### Expected Behavior

Succesful unit test execution

### Actual Behavior

Compilation error:

> /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(362,5): error NETSDK1136: The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so. [/Users/my_user/Sources/xamarin-unittesting/XamarinUnitTesting.UnitTests/XamarinUnitTesting.UnitTests.csproj]

### Basic Information

- Version with issue: 1.2.0
- Last known good version: N/A
- IDE: Visual Studio Code, VS4Mac, VS2019
- Platform Target Frameworks: netstandard2.1, .net5.0
- Nuget Packages: 1.2.0
- Affected Devices: Unit Tests

### Workaround
Remove the reference to XamarinCommunityToolkit completely and reimplement functionality from scratch

### Reproduction Link

A complete sample to reproduce the issue is in this repository (`xct-wpf-issue` branch)
[https://github.com/xamcat/xamarin-unittesting/tree/xct-wpf-issue](https://github.com/xamcat/xamarin-unittesting/tree/xct-wpf-issue)

**Comment by pictos** [comment]
@alexeystrakh can you[ try this workaround?](https://github.com/xamarin/XamarinCommunityToolkit/issues/1167#issuecomment-833749480)

**Comment by alexeystrakh** [comment]
Thanks @pictos, just checked it and it works great! Downgrade from `net5.0` to `netcoreapp3.1` target along with the `GenerateErrorForMissingTargetingPacks = false` fixes the issue.

**Comment by vppetrov** [comment]
Now we have .net 6.0. Downgrading to .net core 3.1 does not seem like a (future oriented) solution. It would be better if XCTK removes references to Windows only libraries (WPF and OpenTK seems to be the problem).
