### ISSUE TITLE
[Bug] Buttons no longer work when using xct:TouchEffect.IsToggled [iOS Only]

### ISSUE THREAD

**Issue by mphill** [xamarin/XamarinCommunityToolkit#1487]
### Description

Buttons that use xct:TouchEffect.IsToggled no longer function in 1.2 with what I believe were changes introduced in https://github.com/xamarin/XamarinCommunityToolkit/commit/4c566de6b58035f719d0bd4a95ea7ec874290802

Impacts iOS only - Android seems fine.

### Steps to Reproduce

```
              <Button 
              Text="Test"
              xct:TouchEffect.IsToggled="{Binding IsToggled}">
                <Button.Triggers>
                    <DataTrigger TargetType="Button" Binding="{Binding IsToggled}" Value="True">
                        <Setter Property="Opacity" Value="1"  />
                        <Setter Property="BackgroundColor" Value="Green"  />
                    </DataTrigger>
                </Button.Triggers>
            </Button>
```

The button is effectively disabled.

### Expected Behavior

Button should toggle state

### Actual Behavior

Button is now non-functional

### Basic Information

- Version with issue: 1.2
- Last known good version: 1.1
- IDE: VS Mac
- Platform Target Frameworks: 
  - iOS: 13 
  - Android: 10  
  - UWP: n/a  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Don't use a button (I switched to a frame) or downgrade to 1.1

**Comment by AndreiMisiukevich** [comment]
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1465

Please use nightly NuGet until a new version is released
