### ISSUE TITLE
[Bug] Issue with the last release not containing all changes listed in the changelog

### ISSUE THREAD

**Issue by kevin68** [xamarin/XamarinCommunityToolkit#1489]
### Description
Hi, I think there was an issue with the last release (1.2.0)
The issue #1144  (with its PR #1147) were marked as fixed in the changelog, but after updating the package I still encountered the error.
After cleaning the project, nuget cache, restarting VS, I downloaded the package directly from the NuGet page and checked with dotPeek.
The function `SetDirection` in the `Expander` view, still contains this piece of code :
```
if (this.Header == null)
        throw new InvalidOperationException("Header not initialized");
```

But it isn't in the source code on the main branch.

### Steps to Reproduce

1. Use package v1.2.0
2. Reproduce #1144 
3. Download package from nuget.org
4. Open the .nupkg with dotPeek (or other software that can read compiled code)
5. Check the SetDirection function of the Expander view

### Expected Behavior
For issue #1144 to be fixed

### Actual Behavior
Issue #1144 not fixed (how is it possible ? i don't know)

### Basic Information

- Version with issue: 1.2.0
- Last known good version: 1.0.3
- IDE: 
- Platform Target Frameworks:
   - Android: 11.0
- Android Support Library Version: None
- Nuget Packages:
  -  Xamarin.Essentials@1.6.1
  -  NETStandard.Library@2.0.3
  -  Xamarin.Forms@5.0.0.2012
- Affected Devices:
  - Pixel 3a (Emulator, Android 9.0)

### Workaround
None

### Reproduction imagery

![image](https://user-images.githubusercontent.com/3018907/124926224-8ec61c00-dffd-11eb-89e6-04c579e50ea0.png)

### Reproduction Link
N/A

**Comment by pictos** [comment]
@AndreiMisiukevich did you already merge the fix for this one, right?

**Comment by kevin68** [comment]
My bad, i just found #1467 which already fixes that, guess i just need to wait for the next release !

**Comment by jfversluis** [comment]
Unfortunately there was a mixup with that commit and the actual change didn't end up in the release. Took it out of the release notes, should _really_ be fixed for the next release :) sorry about that!
