### ISSUE TITLE
[Bug] System.InvalidOperationException: Invalid on Color.Default

### ISSUE THREAD

**Issue by Tum4ik** [xamarin/XamarinCommunityToolkit#1490]
### Description

System.InvalidOperationException: Invalid on Color.Default

Color.MultiplyAlpha (System.Double alpha) D:\a\1\s\Xamarin.Forms.Core\Color.cs:151
PlatformShadowEffect.Update ()
PlatformShadowEffect.OnElementPropertyChanged (System.ComponentModel.PropertyChangedEventArgs args)
PlatformEffect`2[TContainer,TControl].SendOnElementPropertyChanged (System.ComponentModel.PropertyChangedEventArgs args) D:\a\1\s\Xamarin.Forms.Core\PlatformEffect.cs:31
RoutingEffect.SendOnElementPropertyChanged (System.ComponentModel.PropertyChangedEventArgs args) D:\a\1\s\Xamarin.Forms.Core\RoutingEffect.cs:39
Element.OnPropertyChanged (System.String propertyName) D:\a\1\s\Xamarin.Forms.Core\Element.cs:375
BindableObject.ClearValue (Xamarin.Forms.BindableProperty property, System.Boolean fromStyle, System.Boolean checkAccess) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:90
BindableObject.ClearValue (Xamarin.Forms.BindableProperty property, System.Boolean fromStyle) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:40
Setter.UnApply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) D:\a\1\s\Xamarin.Forms.Core\Setter.cs:117
VisualStateManager.GoToState (Xamarin.Forms.VisualElement visualElement, System.String name) D:\a\1\s\Xamarin.Forms.Core\VisualStateManager.cs:80
Button.ChangeVisualState () D:\a\1\s\Xamarin.Forms.Core\Button.cs:239
VisualElement.ChangeVisualStateInternal () D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:992
ButtonElement.ElementPressed (Xamarin.Forms.VisualElement visualElement, Xamarin.Forms.Internals.IButtonElement ButtonElementManager) D:\a\1\s\Xamarin.Forms.Core\ButtonElement.cs:70
Button.SendPressed () D:\a\1\s\Xamarin.Forms.Core\Button.cs:181
ButtonElementManager.OnTouch (Xamarin.Forms.VisualElement element, Xamarin.Forms.IButtonController buttonController, Android.Views.View v, Android.Views.MotionEvent e) D:\a\1\s\Xamarin.Forms.Platform.Android\ButtonElementManager.cs:13
IOnTouchListener.OnTouch (Android.Views.View v, Android.Views.MotionEvent e) D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs:202
View+IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v, System.IntPtr native_e) /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.View.cs:4211
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.72(intptr,intptr,intptr,intptr)

### Basic Information

- Version with issue: 1.2.0
- Last known good version: 1.1.0
- IDE: VS Community  2019 (16.10.2)
- Platform Target Frameworks:
  - Android: 9.0

**Comment by pictos** [comment]
@Tum4ik I'm sorry but your report doesn't provide useful information to us to investigate your issue, please open a new issue following our bug template.

**Comment by Tum4ik** [comment]
Hi @pictos , please, review https://github.com/xamarin/XamarinCommunityToolkit/pull/1492.
