### ISSUE TITLE
[Bug] The TouchEffect doesn't work with PanCakeView

### ISSUE THREAD

**Issue by ignatiucnetinfo** [xamarin/XamarinCommunityToolkit#1493]
### Description

The Touch Effect isn't always working on the iOS on the last 1.2.0 build, but it works in the 1.2.0-pre2 build

### Steps to Reproduce

1.  several touch effects on the main screen
2.  push to navigation the second screen
3.  the TE on the second screen doesn't work.

Just in case it's important, the controls are PancakeView.

**Comment by AndreiMisiukevich** [comment]
@ignatiucnetinfo Hi, could you please check a "nightly" XCT package?
https://github.com/xamarin/XamarinCommunityToolkit#installation

Because this issue might be fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1465

Also, you could you please provide a sample app if the nightly package is not working for you too

**Comment by ignatiucnetinfo** [comment]
@AndreiMisiukevich 
Here a sample of the issue.
https://drive.google.com/file/d/103VetiCuVQi5cdHySCE2WJmu2eHPuOUh/view?usp=sharing

**Comment by AndreiMisiukevich** [comment]
@ignatiucnetinfo hi, thanks for the sample!

Have you tried the nightly package?

**Comment by ignatiucnetinfo** [comment]
@AndreiMisiukevich In the nightly builds I'm seeing the last is the 1.1.0-*.

**Comment by AndreiMisiukevich** [comment]
@ignatiucnetinfo it should be a version value issue (CC @jfversluis)

But I think it's the latest build, because the publishing date is 7/9/2021 (3 days ago)

**Comment by taenito** [comment]
I tried the new 1.3.0-pre1 package and it's ok with Label, Frame and Image (SvgCachedImage from the [FFImageLoading](https://github.com/luberda-molinet/FFImageLoading) plugin).

But it still doesn't work with the [PancakeView](https://github.com/sthewissen/Xamarin.Forms.PancakeView) plugin for me.

**Comment by ignatiucnetinfo** [comment]
@AndreiMisiukevich , yes, the latest build still not working.

**Comment by AndreiMisiukevich** [comment]
@ignatiucnetinfo @taenito thanks for checking
Honestly speaking, if it works fine with all xamarin.forms views and even with FFImage view, then it most likely a PanCakeView issue, right?

**Comment by AndreiMisiukevich** [comment]
Okay, I think I can fix it
