### ISSUE TITLE
[Enhancement] SnackBars should not appear in front of navigation

### ISSUE THREAD

**Issue by Keivhin** [xamarin/XamarinCommunityToolkit#1494]
## Summary

Hi !

According to the [Google Material documentation](https://material.io/components/snackbars#placement), SnackBars should not appear in front of navigation. I just tried to display one in my app that has a TabbedPage as CurrentPage, and the result is that the SnackBar masks my Tabs (wich are placed at the bottom of my page)

![SnackBar](https://user-images.githubusercontent.com/76998493/125101747-da022c80-e0da-11eb-9d3f-67315c4ef27b.gif)

As a bonus, could a SnackBar be placed relatively, using horizontal and vertical alignments along with a Margin ? As we can see in Google Material documentation, SnackBars can span the entire width of a UI, but it seems to be always the case.

**Comment by maxkoshevoi** [comment]
Call `DisplaySnackbarAsync` on specific tab, and not on TabbedPage, then it will be displayed at the bottom of that tab.

Also you can call `DisplaySnackbarAsync` on your floating action button, so it will be displayed above it

**Comment by Keivhin** [comment]
Hi Max,

I'm already calling the `DisplaySnackBarAsync` on my specific tab. Calling the SnackBar on an equivalent to the floating button is working, thanks :). But I think it might be a little tricky in some cases.

**Comment by VladislavAntonyuk** [comment]
@Keivhin I believe you are calling it like Application.Current.MainPage.DisplaySnackbarAsync. as Max suggests could you try to call in like this.DisplaySnackbarAsync (where this is selected page)

**Comment by jfversluis** [comment]
Hm yeah I can see both sides of this. One the one hand we should adhere to the Google Material design as much as possible, on the other hand, I think the way this is implemented allows you to work around this yourself by calling the Snackbar on a different element. Not sure if the current implementation would even allow the detection of navigation elements etc.

Closing this one for now.
