### ISSUE TITLE
[Bug] DrawingView: Clearing points from the collection doesn't clear the UI on iOS

### ISSUE THREAD

**Issue by dejanbasic** [xamarin/XamarinCommunityToolkit#1495]
### Description
When I execute Clear() method, on Points collection in DrawingView, UI is not cleared on iOS
### Steps to Reproduce

1. Clear DrawingView's Points collection, in code behind or in view model
2. Points collection is empty
3. DrawingView is still showing points on the UI

### Expected Behavior
DrawingView UI is empty
### Actual Behavior
DrawingView UI is showing cleared points
### Basic Information

- Version with issue: 1.2.0
- Last known good version: -
- IDE: Visual Studio Community 2019 for Mac Version 8.10.5 (build 16)
- Platform Target Frameworks: 
  - iOS: 14.20.0.24
  - Android: - 
  - UWP: -  
- Android Support Library Version: -
- Nuget Packages: -
- Affected Devices: -

**It works on Android!**

**Comment by jfversluis** [comment]
Interesting! Thanks for reporting!

@VladislavAntonyuk

**Comment by jfversluis** [comment]
Fixed in #1520
