### ISSUE TITLE
[Bug] Toast doesn't apply CornerRadius property

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1496]
### Description
Feature introduced in https://github.com/xamarin/XamarinCommunityToolkit/pull/1437  (cc @VladislavAntonyuk)
The CornerRadius property for SnackBar  works but not for Toast.

### Steps to Reproduce

```
var options = new ToastOptions()
			{
				BackgroundColor = Color.FromHex("#CC0000"),
				CornerRadius = new Thickness(20),
				MessageOptions = new MessageOptions
				{
					Message = "Toast message",
					Foreground = Color.White,
					Font = Font.SystemFontOfSize(16),
				}
			};

			await this.DisplayToastAsync(options);
```

### Expected Behavior
Toast displayed with corner radius = 20.

### Actual Behavior
Toast displayed with corner radius = 0 (default).

### Basic Information

- Version with issue: not yet released. develop branch.
- Last known good version: - 
- IDE:-
- Platform Target Frameworks: 
  - iOS:  
  - Android:  11.0
  - UWP:   
- Android Support Library Version: -
- Nuget Packages:-
- Affected Devices:-

**Comment by VladislavAntonyuk** [comment]
We do not use the native toast.
We use the Snackbar in both cases.

**Comment by Cfun1** [comment]
Despite that native Snackbar is used for both, the `CornerRadius` property is not being applied for `DisplayToastAsync`

**Comment by VladislavAntonyuk** [comment]
yes, you are right. Found the issue.
will create a pr soon
