### ISSUE TITLE
Rename platform specific implementations of effects

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#15]
_From @jimbobbennett on December 26, 2016 22:42_

## Feature Request:
The platform specific implementation of each effect has the same class name as the portable effect. This means it is easy to use the wrong `using` directive and end up with the portable effect exported as the platform specific implementation (see https://github.com/FormsCommunityToolkit/Effects/pull/35 for a fix for this issue for the ClearEntryEffect).

If the names were different this would never happen - for example if all platform specific implementations had the platform name in them. E.g. `ClearEntryEffectDroidImpl` and `ClearEntryEffectiOSImpl`.

_Copied from original issue: FormsCommunityToolkit/Effects#36_

**Comment by bartlannoeye** [comment]
@jimbobbennett is this solved with the discussion result in #19 ?

**Comment by pauldipietro** [comment]
Closing since it's presumably solved.
