### ISSUE TITLE
[Enhancement] Add support for FFmpeg

### ISSUE THREAD

**Issue by nacompllo** [xamarin/XamarinCommunityToolkit#1514]
## Summary

I think adding support for FFmpeg (or another framework with similar features) should be an issue to consider for Xamarin Community Toolkit, we are in 2021 and file decoding or encoding is something that many clients demand for their projects, but it is difficult to offer them a solution based on Xamarin.Forms mainly because generating binding libraries can be an odyssey when it comes to large libraries and the few open source libraries available are not available for all platforms that Xamarin.Forms supports given the complexity involved in the support of such libraries on all platforms. So my suggestion would be for the Xamarin Community Toolkit to add support for FFmpeg (or another framework with similar features) on Android, iOS, UWP, and macOS officially. I think FFmpeg is a large enough cross-platform library to consider this suggestion.
https://www.ffmpeg.org/

Also, this could indirectly benefit MediaElement by implementing Ffmpeg functionalities. For example the [ffmediaelement](https://github.com/unosquare/ffmediaelement) project that exists for WPF implements some additional features to the native MediaElement:

- Easily apply FFmpeg video and audio filtergraphs.
- Specify input and codec parameters.
- Opt-in hardware decoding acceleration via devices or via codecs.
- Capture stream packets, audio, video and subtitle frames.
- Change raw video, audio and subtitle data upon rendering.
- Perform custom stream reading and stream recording.

Links of interest:
[Ruslan Balanukhin](https://github.com/Ruslan-B) has a FFmpeg interop link generator tool for C # /. NET and Mono that might be useful for this suggestion: [FFmpeg.AutoGen](https://github.com/Ruslan-B/FFmpeg.AutoGen)

## Who Will Do The Work?
- [x] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@nacompllo I can see a lot of value in your proposal, but I believe that's out of our roadmap for now... That will be not an easy feature to maintain among other features that we have on this project. As a fast solution, I would suggest you use the [VLC for Xamarin](https://github.com/videolan/libvlcsharp)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
