### ISSUE TITLE
[Bug] [iOS] When Using Can Execute In Command, Touch Effect Behave Incorrectly

### ISSUE THREAD

**Issue by albilaga** [xamarin/XamarinCommunityToolkit#1523]
### Description
In iOS, when we are using Command which also handle `CanExecute` then the view which attached by TouchEffect still in remain selected states after finishing executing command.
### Steps to Reproduce

1.  Open the sample in below or create 2 pages. In first page the content page will be like this
```
<Label HorizontalOptions="Center" VerticalOptions="Center" Padding="30" Text="Go To Second Page"
           effects:TouchEffect.Command="{Binding NavigateToSecondPageCommand}"
           effects:TouchEffect.NativeAnimation="True" effects:TouchEffect.NativeAnimationColor="Blue" />
```
and the page.xaml.cs
```cs
private bool _isBusy;

        public bool IsBusy
        {
            get => _isBusy;
            set
            {
                if (_isBusy == value)
                {
                    return;
                }

                _isBusy = value;
                _navigateToSecondPageCommand.ChangeCanExecute();
            }
        }

        private Command _navigateToSecondPageCommand;

        public Command NavigateToSecondPageCommand => _navigateToSecondPageCommand ??=
            new Command(async () =>
            {
                IsBusy = true;
                await Navigation.PushAsync(new SecondPage()).ConfigureAwait(true);
                IsBusy = false;
            }, () => !IsBusy);

        public MainPage()
        {
            InitializeComponent();
            BindingContext = this;
        }
```
2.  Run the app. Click the label and then go back.
3.  In android everything working as expected. In iOS, it is as attached below, when go back to main page, the label is still in the selected state.

### Expected Behavior
When finishing executing command, the state should be reset to default state.
### Actual Behavior
When finishing executing command, the state of touch effect is still the same
### Basic Information

- Version with issue: 1.2.0, 1.3.0-pre-1
- Last known good version: -
- IDE: Rider
- Platform Target Frameworks: 
  - iOS: 14.5
  - Android: 11
- Affected Devices: iOS

### Reproduction imagery

https://user-images.githubusercontent.com/2399099/126497339-9125c9f8-9eb6-4d7f-b352-528f01428a70.mp4

### Reproduction Link

[App1.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6856123/App1.zip)

**Comment by Huaba93** [comment]
@AndreiMisiukevich I think this is caused because `HandleTouch` executes `CanExecute`. Is this really a good idea? Imho it only causes negative performance impact. What do you think?

**Comment by AndreiMisiukevich** [comment]
@Huaba93 why does it cause a negative performance impact?

**Comment by Huaba93** [comment]
> @Huaba93 why does it cause a negative performance impact?

@AndreiMisiukevich  Because each call of CanExecute takes some time (but in most cases, I think, only a boolean property is evaluated). And I don't understand why CanExecute must be called at start, while moving and on end of touch. In my opinion, CanExecute only needs to be called before execution should occur. 

So imho this 
https://github.com/xamarin/XamarinCommunityToolkit/blob/a09a14fb58b3e119594dfe9222506e16266ac8b2/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs#L1169-L1175

should be changed to smth like this (and get rid of CanExecute in platform code, or why do you think we need this?)

```
 internal void RaiseCompleted() 
 { 
 	var element = Element; 
 	var parameter = CommandParameter; 
        if (Command != null && Command.CanExecute(parameter))
        {
           Command.Execute(parameter);
        }
 	weakEventManager.RaiseEvent(element, new TouchCompletedEventArgs(parameter), nameof(Completed)); 
 } 


```

Quite similar to the Xamarin.Forms.TapGestureRecognizer
https://github.com/xamarin/Xamarin.Forms/blob/809e75547cec1a4c84a2eabdcfddb4b4f43fccd5/Xamarin.Forms.Core/TapGestureRecognizer.cs#L40-L44

**Comment by AndreiMisiukevich** [comment]
@Huaba93 
CanExecute is a synchronous method and returns a bool.  It is not supposed to be a heavy operation (if it is, then there is a problem with the design).

>> CanExecute only needs to be called before execution should occur.
Yes, it works for TapGestureRecognizer, because TapGestureRecognizer isn't "responsive" to touches. It is not highlighted when it's pressed.
We don't want to see the view in the "pressed" state if CanExecute != True.

I hope that's clear now :)

**Comment by Huaba93** [comment]
@AndreiMisiukevich Yes, I understood it that way from the beginning.

I just thought it should behave the same as the Xamarin.Forms button. I have only tested on iOS, where the button always remains in the pressed state, even if CanExecute == false. On Android it is exactly as you say. 

So there is no right or wrong, you have implemented it as on Android and that is also good. I just got it wrong ;) 

Here a sample if you would like to test it by yourself 

```
    public class MainPage : ContentPage
    {
        bool _canExecute;
        Command Command;
        Label _canExecuteState = new Label();

        public MainPage()
        {
            Command = new Command(() =>
            {
                Console.WriteLine("Test");
            }, () => _canExecute);

            Task.Run(async() =>
            {
                while (true)
                {
                    await Task.Delay(5000);
                    _canExecute = !_canExecute;
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        Command.ChangeCanExecute();
                        _canExecuteState.Text = _canExecute.ToString();

                    });
                }
            });

            this.Content = new StackLayout
            {
                Margin = new Thickness(0,50,0,0),
                Children ={_canExecuteState,
                    new Button
            {
                Text = "Sample Button",
                Command = Command
            }}
            };
        }
    }
```

**Comment by AndreiMisiukevich** [comment]
@Huaba93 cool, thank you)
