### ISSUE TITLE
[Enhancement] Update API documentation for TabViewItem

### ISSUE THREAD

**Issue by jjgarrett0** [xamarin/XamarinCommunityToolkit#1536]
## Summary

The API documentation on https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/tabview says that the TabViewItem contains a TapCommandParameter Property, but the actual API doesn't seem to have it. Can the documentation be updated or better yet, can the TapCommandParameter property be added?

## API Changes

Add TapCommandParameter to the TabViewItem.

## Intended Use Case
It would be useful to be able to pass parameters to a TapCommand.

## Who Will Do The Work?

- [x ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! Please open a PR on the docs repo: https://github.com/MicrosoftDocs/xamarin-communitytoolkit
