### ISSUE TITLE
[Bug] Rename namespaces

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#154]
Based of #114 I guess we need someone to rename all the things in terms of namespaces.

So, everything from `XamarinCommunityToolkit.*` to `Microsoft.Toolkit.Xamarin.Forms.*`

**Comment by almirvuk** [comment]
I can do this. :)

**Comment by bartlannoeye** [comment]
Was about to pick it up, but you beat me to it ;)

**Comment by jfversluis** [comment]
Go for it!

**Comment by jfversluis** [comment]
Note to self: we also probably want to rename the NuGet to `Microsoft.Toolkit.Xamarin.Forms`. Either make that part of this change or a separate one.

**Comment by almirvuk** [comment]
I will probably take this one on Friday night or Saturday morning. :)
