### ISSUE TITLE
[Enhancement] Toast-Text should be centered

### ISSUE THREAD

**Issue by KrizCologne** [xamarin/XamarinCommunityToolkit#1541]
## Summary

The left aligned text don't look that good in some cases. A additional property "TextAlignment" in the MessageOptions would be great.

## API Changes

Add Labels HorizontalOrientation property and bind it to new created "TextAlignmet" property in the MessageOptions.

## Intended Use Case
Nearly every time when using a ToastMessage. Maybe its German taste, but centered text looks better sometimes.

## Who Will Do The Work?

- [x] I am willing to take this on myself (But I'm afraid I'm not skilled enough, so someone with more experience should do it)
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks @KrizCologne! Is this a bug fix or an enhancement? 

We are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

However, we are still merging Bug Fix PRs.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Comment by VladislavAntonyuk** [comment]
Because in Xamarin Community Toolkit we use Snackbar for both Toast and Snackbar, the message is displayed according to Snackbar behavior (aligned to the left). 
It is fixed in [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).
