### ISSUE TITLE
[Enhancement] Generic Regex validator

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#155]
## Summary

While going through the issues I came across #8 which mentions a generic regex validator which I think might be nice. Just throw the regex pattern in there and let our validator do the rest.

## API Changes

TBD

## Intended Use Case
Lets users easily create all kinds of validators based on a regex pattern.

**Comment by AndreiMisiukevich** [comment]
That's already supported by TextValidationBehavior )

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/TextValidationBehavior.shared.cs#L18L22

**Comment by jfversluis** [comment]
Whoops! Awesome work!
