### ISSUE TITLE
[Bug] Toast & Snackbar width adjustment and positioning

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/XamarinCommunityToolkit#1550]
### Description
We have difficulty adjusting width and positioning in android and ios.

in android the Toast / snackbar always set width = 100% ( full width at the bottom ), I was set padding & corner radius at the message option but the Toast box is enlarged bigger than we are expected.

### Steps to Reproduce

1. add padding to the message option - padding, for reducing the full width

### Expected Behavior
 width & positioning can be adjusted and also we can put a stack layout if there are some templates.

### Actual Behavior
in android the Toast / snackbar always set width = 100% ( full width at the bottom )

### Basic Information
- VS 2019 Community 8.10.6
- Version with issue: XCT 1.2.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.5
  - Android: 10
 
- Android Support Library Version: 
- Nuget Packages: XCT 1.2.0
- Affected Devices: Android & iOS

### Reproduction Link

![image](https://user-images.githubusercontent.com/3633650/127595345-46c36a05-0733-48b6-9955-20f39ffb25b8.png)

**Comment by pictos** [comment]
@VladislavAntonyuk do you have any input on this?

**Comment by VladislavAntonyuk** [comment]
It's a default Snackbar behavior.
And we use Snackbar for both DisplayToastAsync and DisplaySnackbarAsync.

**Comment by maxkoshevoi** [comment]
- You can get Snackbar/Toast with material design an Android by inheriting you app's theme from `Theme.MaterialComponents.DayNight.NoActionBar` for example. Or by setting it explicitly [like this](https://stackoverflow.com/a/62864686/4312132).
- As for the position. You can change it by calling `.DisplayToastAsync()` on different things. Page = at the bottom of the page (with margin if theme is used), Button (or other control on the page) = above that control.

Example of what's possible with current implementation:
![image](https://user-images.githubusercontent.com/6609929/128079879-31292bf9-b1b9-4138-9af1-4614786294cd.png)
