### ISSUE TITLE
[Bug]Error: : XamlC error XFC0000 : Cannot resolve type "TouchEffect"

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/XamarinCommunityToolkit#1562]
Hello after update from 1.1.0 to 1.2.0. I am getting error in compile time . Error message is `Error : XFC0000 Cannot resolve type "TouchEffect".` 

My XAML reference as following

`xmlns:xct="http://xamarin.com/schemas/2020/toolkit"`

Thank you in advance.

**Comment by AndreiMisiukevich** [comment]
Closing in favor https://github.com/xamarin/XamarinCommunityToolkit/issues/1311

**Comment by bricefriha** [comment]
I truly feel that it's not related to #1311.
I solved it by downgrading the package to 1.3.0
