### ISSUE TITLE
[Enhancement] Screen Transition

### ISSUE THREAD

**Issue by widhimp** [xamarin/XamarinCommunityToolkit#1566]
## Summary

To provide a way to make specific transition from Screen A to Screen B, using new Navigation for example **AnimatedNavigation** ("new AnimatedNavigation(new SomePages())") and in specific Screen could determine the transition type like **Fade**, **SlideFromTop**, **SlideFromRight**, **SlideFromBottom**, **SlideFromLeft** and etc

## Intended Use Case
It will be used when we need to make same transition between Android & iOS. And for example if we using TabView, click the details of TabViewContent then we can using transition "SlideFromBottom" to make it beauty.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
