### ISSUE TITLE
[Bug] TouchEffect.NativeAnimation="True" will deselect item in collection view

### ISSUE THREAD

**Issue by ziomek64** [xamarin/XamarinCommunityToolkit#1568]
### Description
I don't know if it's a bug or I'm not aware of something or maybe it's on my end. I have collection view that is stack layout with frames that have images in them. When I click on one that is already selected it will diselect itself when xct:TouchEffect.NativeAnimation="True" is on the Frame. It also happens when i put it to image in the frame. It's really confusing, because its just animation right? I know that i have default ripple animation in xamarin while selecting item but I'm using this one because I want to ripple animation to play only inside frame.

When I click just pixel or two outside of frame it will not deselect an item. I didn't show this in the gif. I've found out after
### Steps to Reproduce
```
            <CollectionView ItemsSource="{Binding Animes}"
                            HeightRequest="120"
                            BackgroundColor="Transparent"
                            ItemsLayout="HorizontalList"
                            SelectionMode="Single"
                            SelectionChanged="Collection1Changed"
                            x:Name="CollectionView1">
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout Orientation="Horizontal"
                                     Padding="5"
                                     IsClippedToBounds="True">

                            <Frame Padding="0"
                                   CornerRadius="5"
                                   BackgroundColor="White"
                                   xct:TouchEffect.NativeAnimation="True"
                                   >
                                <Image Source="{Binding coverImage.large}"
                                       HeightRequest="80"
                                       WidthRequest="80"
                                       Aspect="AspectFill"></Image>
                            </Frame>
                        </StackLayout>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
```

### Expected Behavior
Not deselecting item

### Actual Behavior
Deselecting item when clicking on the one that is already selected

### Basic Information

- Version with issue: 1.2.0
- Last known good version: I don't know
- IDE: Visual Studio 2019 newest version
- Platform Target Frameworks: 
  - Android: Android 11
- Nuget Packages: XamarinCommunityToolkit, Xamarin Essentials, GraphQL.Client

- Affected Devices:

### Reproduction imagery

![2021-08-11 01-26-40(1)](https://user-images.githubusercontent.com/84880432/128948533-b636ec84-f4bf-412b-8b93-0d048e8badff.gif)

**Comment by AndreiMisiukevich** [comment]
It can be a problem https://github.com/xamarin/XamarinCommunityToolkit/blob/a09a14fb58b3e119594dfe9222506e16266ac8b2/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs#L235


Does it work fine if you change NativeAnimation to some forms animation? (e.g. PressedOpacity etc.)

**Comment by ziomek64** [comment]
`xct:TouchEffect.PressedOpacity="0.1"`

It's the same with native animation on true and false.

Is it a bug or the way you guys implemented it? I hope something could be made about it

**Comment by AndreiMisiukevich** [comment]
@ziomek64 I think it's a bug. And the problem can be in line I attached. Need to investigate.
You can comment that line (with if) and check if the problem still exists

**Comment by ziomek64** [comment]
`
			if (Device.RuntimePlatform == Device.Android)
				HandleCollectionViewSelection(sender);`
				
Commented these two lines. Now i can't select any item in collection view

**Comment by AndreiMisiukevich** [comment]
@ziomek64 
ok, then try to change next line

https://github.com/xamarin/XamarinCommunityToolkit/blob/a09a14fb58b3e119594dfe9222506e16266ac8b2/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs#L254

```csharp
collectionView.SelectedItem = item;
```

Should be ok

**Comment by ziomek64** [comment]
That seems to be working for me, but you can double-check on me as I've never contributed or anything.
Thank you for solution
