### ISSUE TITLE
add play live Video URL or M3u8 support in Media element

### ISSUE THREAD

**Issue by eramrit78** [xamarin/XamarinCommunityToolkit#1569]
Today are,  no of customers required playing live video from their APP. but how we can achieve this from Media Element in xamarin forms or MAUI. currently  it de-supported. 

Today varies sources are used to live video like "Youtube Live Video" link or "Facebook Live Video" link or Wowza Stream Engine etc. 

Currently we are used Media Manager in Xamarin but it better for a developer add support in Media Element in Xamarin Community Toolkit.

Thanks

**Comment by jfversluis** [comment]
Already requested as a feature in #404 currently not possible
