### ISSUE TITLE
[Bug] MediaElement crashes the program if navigated away from too quickly

### ISSUE THREAD

**Issue by NickCRowork** [xamarin/XamarinCommunityToolkit#1571]
### Description
When using MediaElement in a Xamarin Forms application, if the page is navigated away from before the player finishes setting up, it will throw the exception: System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Xamarin.CommunityToolkit.UI.Views.FormsVideoView'.' This is when using a remote source for the video.
I've also seen this issue happen when the page with the video is navigated away from before the video with a remote source starts playing, but I've been unable to reliably reproduce that.
Version tested was Android. Unknown if error exists in IOS as well.

### Steps to Reproduce

1. Download the repro
2. Click the open video button
3. Click the back button before the black box of the video player appears

### Expected Behavior
Page is navigated away from successfully.
### Actual Behavior
App crashes.
### Basic Information

- Version with issue: 1.2.0
- IDE: Visual Studio Community 2019
- Platform Target Frameworks: 
  - iOS:  Xamarin default
  - Android: 11.0
- Nuget Packages:
NETStandard.Library
Xamarin.CommunityToolkit
Xamarin.Essentials
Xamarin.Forms
- Affected Devices:
Motorola One 5G Ace - Android 10

### Reproduction Link

https://github.com/NickCRowork/VideoViewError

**Comment by andos716** [comment]
@NickCRowork I can confirm that this affects iOS as well. I modified your example with a back button for iOS navigation and I get a "Got a segv while executing native code." I am getting this exact crash in an app with a similar scenario (hiding and showing a MediaElement)

Here is the iOS stacktrace from your example code:

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x104811284 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x104807dc4 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x104814ba0 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : mono_pmip
	0x1e52f029c - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x19a9e3924 - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x19a9eb334 - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x1a10e1e18 - /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore : <redacted>
	0x199271a84 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x19927381c - /usr/lib/system/libdispatch.dylib : <redacted>
	0x199281c70 - /usr/lib/system/libdispatch.dylib : _dispatch_main_queue_callback_4CF
	0x199600340 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1995fa218 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1995f9308 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1b0c7c734 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x19c07775c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x19c07cfcc - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x10227ea68 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x101985140 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x101984fc4 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x1007ebe20 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x1010934a0 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x104817f44 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : mono_pmip
	0x1048c4990 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : mono_pmip
	0x1048c9d3c - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : mono_pmip
	0x1047fc9c0 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x1049ad404 - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : xamarin_localized_string_format_9
	0x1007ebd2c - /private/var/containers/Bundle/Application/C9644AA7-A371-4731-8EA8-EB1EA60DFCAB/VideoViewError.iOS.app/VideoViewError.iOS : 
	0x1992b5cf8 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1ae18f08c):0x1ae18f07c  00 01 00 b4 00 01 f8 b7 08 00 40 f9 08 81 7d 92  ..........@...}.
0x1ae18f08c  09 39 c0 79 29 02 f8 36 3f 01 1e 72 00 01 80 9a  .9.y)..6?..r....
0x1ae18f09c  c0 03 5f d6 88 dc 26 90 08 81 20 91 09 08 40 92  .._...&... ...@.
0x1ae18f0ac  08 79 69 f8 69 dc 26 f0 29 61 3e 91 1f 01 09 eb  .yi.i.&.)a>.....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00007>
	  at UIKit.UIApplication:Main <0x0002f>
	  at UIKit.UIApplication:Main <0x00043>
	  at VideoViewError.iOS.Application:Main <0x0007f>
	  at System.Object:runtime_invoke_dynamic <0x0010f>
=================================================================

**Comment by ThanhNg** [comment]
@jfversluis Can you please help prioritize this? This crashes my video-player app so often.

**Comment by ilsur-dev111** [comment]
Hello everyone, I also have this problem, everything works fine on iOS, but it breaks on Android, I haven’t found workarounds yet, the player is on one of the TabbedPage pages, and switching to another page randomly breaks the application.
