### ISSUE TITLE
[Bug] Compile-time Warning "Detected package version outside of dependency constraint"

### ISSUE THREAD

**Issue by DancesWithDingo** [xamarin/XamarinCommunityToolkit#1576]
### Steps to Reproduce
I just installed XCT for a look around, and I'm getting the following compile-time warning: "Detected package version outside of dependency constraint: Xamarin.CommunityToolkit 1.2.0 requires Xamarin.Forms (>= 5.0.0.1874 && <= 5.0.0.2012) but version Xamarin.Forms 5.0.0.2083 was resolved. (NU1608)"

I'm running the current version of XF (5.0.0.2083 obviously), and I just got XCT 1.2 from nuget.

### Expected Behavior
No warning message?

### Actual Behavior
Warning message!

### Basic Information

- Version with issue: 1.2
- Last known good version: unknown
- Platform Target Frameworks: iOS

**Comment by pictos** [comment]
Hey @DancesWithDing, this is expected, the version 1.2 of XCT doesn't work with the latest version of XF. The versio 1.3-pre is the way to go.
