### ISSUE TITLE
[Enhancement] Improve accessibility for TouchEffect

### ISSUE THREAD

**Issue by taenito** [xamarin/XamarinCommunityToolkit#1579]
## Summary

Android :
Set View.Clickable or View.LongClickable to true only if we set Command or LongPressCommand respectively.
Both are currently set to true.

iOS :
Set UIAccessibilityTrait.Button when we have Command or LongPressCommand.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
