### ISSUE TITLE
[Bug] EventToCommandBehavior throws ArgumentException with ListView events

### ISSUE THREAD

**Issue by almirvuk** [xamarin/XamarinCommunityToolkit#158]
### Description
When using `EventToCommandBehaviour` implementation from `XamarinCommunityToolkit` with for example ListView and its events `ItemTapped` or `ItemSelected` event. Same approach and the same sample code is working with other implementation of `EventToCommandBehavior`, for example, the one from Prism library.

### Steps to Reproduce

1. Add behaviour to ListView and use it with ItemTapped event.
2. Debug the EventToCommandBehavior implementation

### Expected Behavior
To not throw an exception.

### Actual Behavior
It throws an exception on line 79, after calling:
`eventInfo.AddEventHandler(View, eventHandler);`

### Basic Information

```
System.ArgumentException has been thrown:

Object of type 'System.EventHandler' cannot be converted to type 'System.EventHandler`1[Xamarin.Forms.ItemTappedEventArgs]'.
```

### Reproduction Link
I have a reproduction sample and it is available on a pull request for ItemTappedeEventArgsConverter in ConvertersGallery page converter [here](https://github.com/xamarin/XamarinCommunityToolkit/pull/157).

**Comment by jfversluis** [comment]
Fixed by #159
