### ISSUE TITLE
[Enhancement] RemoveBorderEffect for Visual Material

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/XamarinCommunityToolkit#1582]
Hello can you extend **RemoveBorderEffect**  for Material Theme. Thank you in advance.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
