### ISSUE TITLE
[Enhancement] [CameraView] Remove unused code

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1587]
## Summary

I would like to remove unused code to make it easier to maintain, starting from `FormsCameraView`.

## API Changes

Removed:

- `UIImage RotateImage(UIImage image)`

## Intended Use Case

NA

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@jfversluis what do you think about it?

**Comment by GUOLDEV** [comment]
@pictos I will leave the PR as a draft for now 👍

**Comment by jfversluis** [comment]
Don't spend too much time on this. I appreciate the effort, but I think there might be big changes when we transition this to the .NET MAUI Community Toolkit. If you want to do some clean up and get some contributions in, I don't have any problem with that :)

**Comment by GUOLDEV** [comment]
Hey @pictos could you please close this issue? Thanks 🙏
