### ISSUE TITLE
Progress bar colors

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#16]
_From @jimbobbennett on January 13, 2017 2:6_

## Feature Request:
Add a new effect to colour progress bars

_Copied from original issue: FormsCommunityToolkit/Effects#38_

**Comment by bartlannoeye** [comment]
_From @Depechie on January 14, 2017 10:5_

Just wondering if this is at all possible with only an effect... cfr. https://forums.xamarin.com/discussion/28894/progressbar-color-in-xamarin-forms

**Comment by pauldipietro** [comment]
This was added to core per https://github.com/xamarin/Xamarin.Forms/issues/1690, I believe.
