### ISSUE TITLE
[Enhancement] Text Case Property for Translate XAML Extension

### ISSUE THREAD

**Issue by AlejandroRuiz** [xamarin/XamarinCommunityToolkit#1601]
## Summary

Some times a single string resource is required in different cases.

## API Changes

```
TranslateExtension.shared.cs

public TextCaseType? TextCase { get; set; }
...
if (TextCase.HasValue)
{
     binding.Converter = new TextCaseConverter
     {
             Type = TextCase.Value
     };
}
return binding;

```

e.g.

Since the framework already provides a Case converter we can use it over the XAML translate extension

```
<!-- New TextCase property -->
<Label Text="{xct:Translate HelloMessage, TextCase=Upper}" />
```

If the TextCase property is assigned the TextCaseConverter will be set to the binding definition -->

## Intended Use Case
Is common to have the usage of the same string resource in different cases across the app and is better to allow the case conversion instead of add a duplicate string resource.

## Who Will Do The Work?

- [X] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
