### ISSUE TITLE
[Bug] When TouchEffect.PressedScale is defined with a Command on a button, the command fire twice the first time.

### ISSUE THREAD

**Issue by mphill** [xamarin/XamarinCommunityToolkit#1603]
### Description

When TouchEffect.PressedScale is defined with a Command on a Button, the command fire twice the first time.

### Steps to Reproduce

1.
Define a button as such:

```
                <Button
                    xct:TouchEffect.PressedScale="1.1"
                    Command="{Binding ClickCommand}"
                    CommandParameter="{Binding ClickCommandParameter}"
                />
```

2.  Click the button
3.  The command fires 2 times the first time the app runs, subsequent clicks only fires once.

### Expected Behavior

- Version with issue:
- Last known good version: Unknown

- Platform Target Frameworks: 
  - iOS:  14.5.1
 
 I am using 1.3.0 pre-2

### Workaround
Use xct:TouchEffect.Command instead.  Do not mix native Command with any TouchEffect functions

@AndreiMisiukevich

**Comment by AndreiMisiukevich** [comment]
@mphill Hi! Thanks for your report
Does this issue happen on iOS only? Does it work fine on Android?

**Comment by AndreiMisiukevich** [comment]
Yeah, confirm this bug. But unfortunately, it's impossible to fix that.
I propose using a workaround for Buttons (the same issue https://github.com/xamarin/XamarinCommunityToolkit/issues/1428)
