### ISSUE TITLE
[Enhancement] BlockingAsyncCommand

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/XamarinCommunityToolkit#1605]
## Summary

I think we all have a problem when a user clicks 5 times on a button and we run 5 commands in parallel. And we need each command to be executed one by one

## API Changes

Add a new class BlockingAsyncCommand,
which will ensure that only one command of the same type is executed at a time

## Intended Use Case
You have a Login command, and a user who is wildly clicking buttons.
you don't want to write weird code that will check if your command is currently running. you just want to use BlockingAsyncCommand.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by ChristophWeigert** [comment]
If you use the AsyncCommand you can pass an allowsMultipleExecutions in the Constructor to prevent multiple clickss:
https://github.com/xamarin/XamarinCommunityToolkit/blob/1cc1f128895a52aef0d5a912ce139415aed90714/src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Internals/BaseCommand.shared.cs#L48
