### ISSUE TITLE
[Enhancement][Converter] Add Expression property to MathExpressionConverter and MultiMathExpressionConverter

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1608]
## Summary

Add `Expression` property to `MathExpressionConverter` and `MultiMathExpressionConverter`. I love this `Converter`, but based on the way that I normally use it,  it would be great to be able to set up the `Expression` value in the Resouce declaration.

## API Changes

Added:
- `public string Expression { get; set; } = string.Empty;`

## Intended Use Case

```
<xct:MathExpressionConverter x:Key="DivideByTwoConverter" Expression="x/2"  />
```

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by GUOLDEV** [comment]
I have pushed a draft PR #1609 to exemplify what I would like to activate. Thoughts?

**Comment by GUOLDEV** [comment]
Once the implementation is approved I can update the docs and sample 👍

**Comment by sattew** [comment]
> 
> 
> I have pushed a draft PR #1609 to exemplify what I would like to activate. Thoughts? @sattew it would be great to know what you think 👍

Hi) 
Honestly, I have no thoughts 🙃 I got your point and I like it. We should add it, I think. Thanks!)

**Comment by AndreiMisiukevich** [comment]
Approved
