### ISSUE TITLE
[Enhancement] Add a TextColorDisabled to TabViewItem

### ISSUE THREAD

**Issue by michaldivis** [xamarin/XamarinCommunityToolkit#1613]
## Summary

Add a `TextColorDisabled` to `TabViewItem` that would control what color the text is when the `IsEnabled` property is set to `False`. The text on an enabled and a disabled `TabViewItem` currently looks the same.

The disabled tab could then look like this:

![tabs](https://user-images.githubusercontent.com/45868547/132682146-903f4845-4e8b-457b-a5a6-30ee74d0d806.jpg)

## API Changes

Add a `TextColorDisabled` property (of type `Color`) to the `TabViewItem` class.

The property would then be used like this:
```xml
<xct:TabView>
    <xct:TabViewItem
        Text="Some text"
        TextColor="{DynamicResource TextColor}"
        TextColorSelected="{DynamicResource AccentColor}"
        TextColorDisabled="{DynamicResource SecondaryTextColor}">
        <Label Text="I'm a label" />
    </xct:TabViewItem>
</xct:TabView>
```

## Intended Use Case
The `TextColorDisabled` color would be used when the `IsEnabled` property is set to `False` to indicate that the tab is disabled and cannot be clicked.

## Who Will Do The Work?

I am willing to take this on myself

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
