### ISSUE TITLE
[Bug] [UWP] TouchEffect Press/LongPress not working at all

### ISSUE THREAD

**Issue by aodpi** [xamarin/XamarinCommunityToolkit#1616]
### Description
TouchEffect gestures (Press, LongPress) do not work on UWP platform (Tested PC with mouse and keyboard and Simulator with touch gestures). Android and iOS version are working as expected with no issues.

### Steps to Reproduce

1. Create a Blank Xamarin.Forms app.
2. Attach Xamarin Community Toolkit TouchEffect Commands (Command, LongPressCommand)
3. Run the app on UWP platform.
3. Try to perform Press or LongPress gestures on the said UI element.

### Expected Behavior

Press and  long press commands would execute normally

### Actual Behavior
Nothing happens after pressing or long pressing the UI

### Basic Information

- Version with issue: 1.2.0
- Last known good version: Unknown
- IDE: Visual Studio Enterprise 2019 version: 16.11.1
- Platform Target Frameworks:
  - UWP:  19041
- Nuget Packages:
  - Xamarin.Forms: 5.0.0.2083
  - Xamarin.CommunityToolkit: 1.2.0
  - Xamarin.Essentials: 1.7.0
- Affected Devices: Windows PC, Windows Simulator

### Workaround
No workaround.

### Reproduction Link
Reproduction sample project:
You can find the Label with text "Learn more at ...", try to press or longpress it.

[App28.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/7169156/App28.zip)

**Comment by AndreiMisiukevich** [comment]
Add this to UWP project (where XF is initialized) 
```
var assembliesToInclude = new List<Assembly>()
{
    typeof(Xamarin.CommunityToolkit.Effects.TouchEffect).GetTypeInfo().Assembly
};

Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

**Comment by AndreiMisiukevich** [comment]
let us know if it doesn't help

**Comment by aodpi** [comment]
@AndreiMisiukevich I've tried your suggestion but it still does nothing, neither on PC nor on Simulator. Android works well, I presume iOS works well too. Update project sample:

[App28.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/7172539/App28.zip)

**Comment by AndreiMisiukevich** [comment]
@pictos do you have any idea why it doesn't work?
Is that UWP target version issue?

**Comment by pictos** [comment]
@AndreiMisiukevich @aodpi I'll try on my end and update the issue ASAP

**Comment by AndreiMisiukevich** [comment]
@pictos any update? :)

**Comment by pictos** [comment]
@AndreiMisiukevich just looked here, and it's a target issue, the sample doesn't change the min version UWP version 2004, after this the touch effect work as expected.
![image](https://user-images.githubusercontent.com/20712372/134088626-4b20fc6a-559a-4a67-8f79-c7b7aaaae92f.png)

**Comment by AndreiMisiukevich** [comment]
@aodpi 🔝
