### ISSUE TITLE
[Bug] CornerRadius broken on Xamarin.Forms 4.7

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#163]
### Description
When upgrading the sample app to Xamarin.Forms 4.7.0.1080 both the `AvatarView` and the views with the contributors on the about page lose their rounded corners.

### Steps to Reproduce

1. Upgrade the sample app to 4.7.0.1080.
2. Check the AvatarView or the about page.

**Comment by sthewissen** [comment]
Possibly fixed in 4.7 SR2, but that came out just minutes ago so haven't been able to verify yet.

**Comment by jfversluis** [comment]
It's been 12 hours. Did you verify yet?! :P

This reminds me though. Let's have a label for things not verified yet. I'll do that now

**Comment by jfversluis** [comment]
Just confirmed this was broken on 4.7.0.1080. But fixed on 4.7.0.1142. So we should be able to upgrade safely from here on out. Didn't do that yet as I didn't see any reason for it.
