### ISSUE TITLE
[Enhancement] CameraView: add more control over the behaviour of the Cameraview

### ISSUE THREAD

**Issue by redek91** [xamarin/XamarinCommunityToolkit#1631]
## Summary

Hi everyone,

I would like to add some control on the CameraView control (already started):
- Add binding for enabling the Preview of the CameraView: this could come in handy, when the CameraView is in a TabbedView and it would release the camera when its not used
- Add an event that triggers if the CameraView is Recording to handle a change in the page that is using the Cameraview

## API Changes

The change does not affect the current usage of the CameraView
- The Preview is set to enabled by default
- The Event that is triggered when the Control starts to Record can be ignored
- The only thing that changes is the IsAvailable binding, that will be true if the Preview is enabled + the camera is available, IsAvailable will be replaced by IsCameraAvailable

Example instantiation:
```
<xct:CameraView
                    Grid.Column="0"
                    x:Name="cameraView"
                    CaptureMode="Photo"
                    FlashMode="Off"
                    IsPreviewEnabled="true"
                    CameraOptions="Front"
                    HorizontalOptions="FillAndExpand"
                    MediaCaptured="CameraView_MediaCaptured"
                    OnAvailable="CameraView_OnAvailable"
                    OnRecording="CameraView_OnRecording"
                    VerticalOptions="FillAndExpand" />
```

## Intended Use Case
The features described above are good if the CameraView is used in Components other than Pages (TabbedPages, ecc..) and give more control over the Cameraview

## Who Will Do The Work?

- [x] I am willing to take this on myself (maybe some help with the iOS part is appreciated)
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
