### ISSUE TITLE
[Enhancement][Converter] Add InvertedIntToBoolConverter

### ISSUE THREAD

**Issue by Robbert-jansen** [xamarin/XamarinCommunityToolkit#1634]
## Summary

Combines the functionality of [InvertedBoolConverter](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/InvertedBoolConverter.shared.cs) and and [IntToBoolConverter](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/IntToBoolConverter.shared.cs) 

## API Changes

Add a new converter `InvertedIntToBoolConverter`

## Intended Use Case

Convert an int to a bool whilst simultaneously inverting the bool, combining the functionality of both the converters listed above

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
