### ISSUE TITLE
[Bug] In Xamarin forms (Android) System.ArgumentException occurs in ImageService.SetTaskForTarget (FFImageLoading.Work.IImageLoaderTask currentTask)

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [xamarin/XamarinCommunityToolkit#1641]
### Description

We are facing a crash in our application due to this error "System.ArgumentException: Key already in the list Parameter name: key" occurred in ImageService.SetTaskForTarget (FFImageLoading.Work.IImageLoaderTask currentTask). And It was logged in the App Center. 

### Stack Trace

ConditionalWeakTable`2[TKey,TValue].Add (TKey key, TValue value)
ImageService.SetTaskForTarget (FFImageLoading.Work.IImageLoaderTask currentTask)
ImageServiceBase`1[TImageContainer].LoadImage (FFImageLoading.Work.IImageLoaderTask task)
TaskParameterPlatformExtensions.Into[TImageView] (FFImageLoading.Work.TaskParameter parameters, FFImageLoading.Work.ITarget`2[TImageContainer,TImageView] target)
TaskParameterPlatformExtensions.Into (FFImageLoading.Work.TaskParameter parameters, Android.Widget.ImageView imageView)
CachedImageRenderer.UpdateBitmap (FFImageLoading.Forms.Platform.CachedImageView imageView, FFImageLoading.Forms.CachedImage image, FFImageLoading.Forms.CachedImage previousImage)
CachedImageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e)
VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
Platform+DefaultRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e)
VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
CornerStackLayoutRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e)
VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
Platform+DefaultRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
ViewCellRenderer+ViewCellContainer.Update (Xamarin.Forms.ViewCell cell)
ViewCellRenderer.GetCellCore (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context)
CellRenderer.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context)
CellFactory.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context, Xamarin.Forms.View view)
ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent)
BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.144(intptr,intptr,int,intptr,intptr)

### Link to Reproduction Sample

This error was logged in the app center. Please refer to the stack trace above

### Steps to Reproduce

Cant able to replicate it from our side.

### Expected Behavior 
           
The application did not crash

### Actual Behavior

The application getting crash. 

### Basic Information

Version:
Xamarin.FFImageLoading -2.4.11.982
Xamarin.Forms - 5.0.0.2083
Visual Studio -2019

Platform:
-Xamarin.Forms (Android)

Note :
We have created a new issue in luberda-molinet/FFImageLoading ( https://github.com/luberda-molinet/FFImageLoading) but Can't get an update from them. Please find the Issue link: -  https://github.com/luberda-molinet/FFImageLoading/issues/1528

**Comment by jfversluis** [comment]
Hey there, I appreciate the ask for help. As you have already discovered yourself, this is an issue with FFImageLoading and/or somewhere in your code. We can't really support you with that.

The error seems to originate [here](https://github.com/luberda-molinet/FFImageLoading/blob/bb675c6011b39ddccecbe6125d1853de81e6396a/source/FFImageLoading.Droid/ImageService.cs#L86). 

Hope you'll figure it out!
