### ISSUE TITLE
Add Multilingual Support to the Sample App

### ISSUE THREAD

**Issue by Char0394** [xamarin/XamarinCommunityToolkit#165]
## Summary
Right now the app is hardcoding the strings in the code, we should move that to an AppResource file and read the strings from there. 

## API Changes
- Add a new AppResource file and move the strings 

*NOTE: I can add the Spanish translations and some of the community members can help us with other languages.*

**Comment by almirvuk** [comment]
Great idea! I can add the Bosnian language 😄

**Comment by Rabosa616** [comment]
I can add Catalan language

**Comment by AbuMandour** [comment]
I can Add Arabic language so we can support "RTL", what do you think?

**Comment by Char0394** [comment]
@jfversluis @sthewissen @AndreiMisiukevich @all since all the strings are in a Resource file already. How we will handle this? Open a new issue for each language support, or they can just go for it add the language Resource and submit the PR? 

Looks like we have: 
- Spanish 
- Arabic 
- Bosnian
- Catalan 

PDT:
**I still have pending to add the code to change the language.**

**Comment by AndreiMisiukevich** [comment]
Well, I can add Russian

**Comment by Char0394** [comment]
Sounds good @Depechie

**Comment by jfversluis** [comment]
Yep that sounds like a good approach. Do we also have something in the sample app to actually switch languages apart from the users configured one on the device? That might be a separate issue then

**Comment by Char0394** [comment]
Actually I was thinking to add the feature of changing the language in Runtime as part of the library using this approach -> https://devblogs.microsoft.com/xamarin/mastering-multilingual-in-xamarin-forms/ 
And add the ability to change the language in the Sample. 
What do you guys think?

**Comment by jfversluis** [comment]
That was exactly what I mean! :)

**Comment by Char0394** [comment]
So, can I go for it? :P

**Comment by jfversluis** [comment]
Fine by me!

**Comment by felipebaltazar** [comment]
I can add Pt-Br

**Comment by LucioMSP** [comment]
I can help with the Spanish version

**Comment by jfversluis** [comment]
@Char0394 did you make any progress with this? I guess it also starts to make sense to maybe have issues for the different languages so we can assign individuals to that

**Comment by Char0394** [comment]
@jfversluis yes, sorry for the delay, I'll submit a PR soon.

**Comment by jfversluis** [comment]
No worries! I didn't mean to say you should hurry up. Just checking :)

Great news!

**Comment by Char0394** [comment]
Anyone interesting in helping with this please leave a comment here https://github.com/xamarin/XamarinCommunityToolkit/issues/225 with the language you want to add.
