### ISSUE TITLE
Android uses the wrong track colour for switches

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#17]
_From @jimbobbennett on January 16, 2017 3:44_

## Bug 

Version Number of Plugin: 1.0.0.35-beta
Device Tested On: Samsung Galaxy Tab-A
Simulator Tested On:

### Expected Behavior
The track colour of a switch when on should be the same as the on colour with a 30% transparency

### Actual Behavior
The track colour is the styles accent colour with 30% transparency

### Steps to reproduce the Behavior
Add a switch to a page, sed the accent to one colour in the Android styles, set the switch to a different colour

![screenshot_20170116-164520](https://cloud.githubusercontent.com/assets/1710385/21970417/fa6a6ca0-dc0a-11e6-83e8-223f4ca6b25f.png)

_Copied from original issue: FormsCommunityToolkit/Effects#40_

**Comment by bartlannoeye** [comment]
_From @Depechie on January 16, 2017 7:49_

@jamesmontemagno any pointers on this?
Tried changing the received trueColor to trueColor = trueColor.MultiplyAlpha(0.7); but this will actually just change the transparency of the color and not 'drop' the blue value down by 30%.
Meaning that with adding Alpha you are able to see through the color and view the switch bar behind it.

<img width="79" alt="alpha" src="https://cloud.githubusercontent.com/assets/351693/21974698/ab540f64-dbc8-11e6-8059-8ce01bc6835a.png">

**Comment by jfversluis** [comment]
I think switches and thumb colors are now default option in Forms
