### ISSUE TITLE
[Bug] Rename solution folders

### ISSUE THREAD

**Issue by almirvuk** [xamarin/XamarinCommunityToolkit#170]
## Summary

This issue is the next step from #154, we still need to rename the solution folders. The task is to rename everything from `XamarinCommunityToolkit.*` to `Microsoft.Toolkit.Xamarin.Forms.*`.

I was working on namespace rename task, and the main issue that I experienced was a **git history** which was lost when I tried to rename the solution folders. All the folders were in removed/added state. 

@bartlannoeye already mentioned that he could help with this.

**Comment by jfversluis** [comment]
O gosh I totally could've done this with that PR. O well. I guess others want to do some work too ;)

**Comment by almirvuk** [comment]
Sharing (the work) is caring 😄

**Comment by jfversluis** [comment]
I think the folders are fine as they are for now since they mostly reflect the name. Not sure if, as we grow, we might need to come up with a somewhat better structure, but good for now
