### ISSUE TITLE
[Question]  is there any way to merge 2 info.plist in 1 project?

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/XamarinCommunityToolkit#1721]
Hello folks,

I have 2 project, One of them is a plugin project. Plugin project has a permission settings for using camera. I would like to create a info.plist in plugin project. My question is about merging two info.plist in my main iOS project in building time. My other similar question is for Android. I have searched much more in internet but I did not find anything about that. I am wondering is there any way to do this?

Thank you in advance.

**Comment by bijington** [comment]
Closing this as it doesn't directly relate to XCT and it has also been raised here with some actual discussion https://github.com/xamarin/Xamarin.Forms/issues/14889
