### ISSUE TITLE
[Bug] [iOS] ShadowEffect disappearing when coming back to the app (only with the Frame view)

### ISSUE THREAD

**Issue by lartisanetsonmobile-admin** [xamarin/XamarinCommunityToolkit#1725]
### Description
I have added a shadow effect to a Frame 

`<Frame WidthRequest="200" HeightRequest="100"
               xct:ShadowEffect.Color="Red"
               xct:ShadowEffect.OffsetY="5"
               xct:ShadowEffect.Radius="10"
               CornerRadius="10"
               HorizontalOptions="Center"
               BackgroundColor="Gray"/>`

The shadow effect is disappearing when coming back to the app. 
This issue exists only on iOS and only with the Frame view.

### Steps to Reproduce

1.  Create a blank Xamarin.Forms application.
2.  Add XCT package. 
3.  Add the Frame above to the MainPage.xaml
4.  Launch the app on iOS Simulator/Real device
5.  Put it on the background
6.  Return to it

### Expected Behavior

The shadow is not disappearing

### Actual Behavior

The shadow is disappearing

### Basic Information

- Version with issue: 1.3.0
- Last known good version: Unknown
- IDE: Visual Studio 2019 Mac
- Platform Target Frameworks:
  - iOS:  Tested on 14.1 and 15

### Reproduction imagery

![shadowissue](https://user-images.githubusercontent.com/67838679/142485949-9f961168-aed3-4fdb-85c6-8df58d811f8d.gif)

**Comment by SarthakGz** [comment]
@lartisanetsonmobile-admin are you having the same issue with other layout then frame like for StackLayout. As Frame has it's own shadow that might be interfering with shadow effect

**Comment by lartisanetsonmobile-admin** [comment]
@SarthakGz No, only with Frame layout. It works fine with StackLayout, Grid, Button etc.. But i use Frame because it has the CornerRadius property

**Comment by SarthakGz** [comment]
@lartisanetsonmobile-admin  For corner radius you can use CornerRadius effect provided by XCT or Clipping api by Xamarin forms you can apply that on any Layout for now at-least as a workaround

**Comment by lartisanetsonmobile-admin** [comment]
@SarthakGz I will try this workaround, thank you for helping :)

**Comment by lartisanetsonmobile-admin** [comment]
@SarthakGz I can't find any CornerRadius effect in XCT. And i think the ShadowEffect is overriding corner radius effects on Android

**Comment by SarthakGz** [comment]
@lartisanetsonmobile-admin check this PR I think this is merged though couldn't find it either
https://github.com/xamarin/XamarinCommunityToolkit/pull/1316

**Comment by bijington** [comment]
> @lartisanetsonmobile-admin check this PR I think this is merged though couldn't find it either
> 
> https://github.com/xamarin/XamarinCommunityToolkit/pull/1316

That PR has been merged but it's currently only on the `develop` branch which means it hasn't officially been released yet.

**Comment by timjamwoo** [comment]
> @SarthakGz I can't find any CornerRadius effect in XCT. And i think the ShadowEffect is overriding corner radius effects on Android

@lartisanetsonmobile-admin did you ever find a solution or workaround for this? I'm experiencing the same issue on XCT 2.0.0.

**Comment by AndreiMisiukevich** [comment]
@timjamwoo I've submitted a PR with the fix
