### ISSUE TITLE
[Bug] MauiCompact not working in new Maui project

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#1741]
See discussion for more details - https://github.com/xamarin/XamarinCommunityToolkit/discussions/1740

Here is the repo project -
[repo.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/7610188/repo.zip)

I'm using the latest VS2022 preview

**Comment by brminnick** [comment]
@VladislavAntonyuk Could you take a look?

**Comment by VladislavAntonyuk** [comment]
yes

**Comment by VladislavAntonyuk** [comment]
@IeuanWalker 
![image](https://user-images.githubusercontent.com/33021114/143645161-792ccaaf-f91f-419a-a290-eb198e013226.png)
you added lib only for android.
Also MauiCompat works only with iOS and Android. you have to remove net6.0-maccatalyst target framework
![image](https://user-images.githubusercontent.com/33021114/143647499-c8a954aa-185c-4622-ab97-df33712bee81.png)

**Comment by IeuanWalker** [comment]
thanks @VladislavAntonyuk, nice spot, VS installed it like that
