### ISSUE TITLE
[Bug] AnimationBehavior has unintended tap gesture recognizer

### ISSUE THREAD

**Issue by Hackmodford** [xamarin/XamarinCommunityToolkit#1759]
### Description

The description of the AnimationBehavior is that you can trigger an animation via a bindable command. But I noticed that there is a tap gesture recognizer that cannot be disabled. It seems like this should be removed or at the very least have a way to disable this gesture recognizer.

In my scenario, I wanted to trigger a shake animation via a command bound to my view model. But the shake animation would also trigger if the view was clicked.

### Steps to Reproduce

1. Create a view that has an animation behavior with the shake animation.
2.  Click the view.

### Expected Behavior

Should not shake

### Actual Behavior

Does shake

### Basic Information

- Version with issue: 1.3.1

### Workaround

My temporary workaround was to create my own version of the AnimationBehavior that just does not have the tap gesture recognizer.

**Comment by Hackmodford** [comment]
Yeah... I'm just not clear why it needs to be there in the first place. But if there's a way to not animate on a clicked event I would be fine.

**Comment by bijington** [comment]
So originally the only way to animate was by interacting with the control like this, it would then fire the `Command` down to a view model. We only recently added the `AnimateCommand` to allow the triggering from the view model. 

We will need to keep the original way but can provide a way to disable the addition of the `TapGestureRecognizer`.

**Comment by bijington** [comment]
@Hackmodford apologies for the delayed updates on this. Do you have a sample of XAML in which you saw this issue? It looks like the code checks to see if an `EventName` is set before clearing/adding a new gesture recogniser. Do you recall if you had set an `EventName`?

**Comment by LeoJHarris** [comment]
@bijington 

I've just noticed this issue as well, when applying a Animation to a row in a collection the Tap gesture for the row itself no longer works and neither does a swipe to refresh. If there is something I provide to help resolve this issue let me know.

**Comment by pictos** [comment]
@LeoJHarris will be great if you can arrange a repo for us. Thanks in advance

**Comment by LeoJHarris** [comment]
@pictos okay this is interesting seems to be working now. Cant say how this wasn't working before but swipe, tapped and shake all work together.

**Comment by pictos** [comment]
@LeoJHarris haha no worries (I'm happy to read that xP), I'll assume that this bug was fixed on our stable channel. If you see this happening again, please file a new issue.
