### ISSUE TITLE
[Enhancement] HasData Converter

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#176]
Hi, this is a converter I use in several projects, you have 2 similar converters in this project already -
- IsNullOrEmptyConverter 
- ListIsNullOrEmptyConverter 

You can pass any object into the and it would return true/ false whether it has data or not.
Let me know if you'd like a PR for this, I understand if not as you already have 2 similar converters already -

```csharp
public class HasDataConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        switch (value)
        {
            case null:
                return false;
            case string x:
                return !string.IsNullOrWhiteSpace(x);
            case IList list:
                return list.Count > 0;
            default:
                return true;
        }
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by AndreiMisiukevich** [comment]
Hi! Thank you for your big interest!)
As you mentioned we already have similar converters.
Not sure it makes sense to add one more.

@sthewissen ?

**Comment by IeuanWalker** [comment]
@AndreiMisiukevich fair enough, the benefit this converter gives, is that you can check if an object is null or not too.

Where as the others only checks strings and lists.

**Comment by IeuanWalker** [comment]
@AndreiMisiukevich The benefit this converter gives, is that you can use it to check if objects are null or not too.

Whereas the other ones are only for strings and lists.

**Comment by sthewissen** [comment]
Maybe we could add something like this to the `IsNullOrEmptyConverter` so that it also takes other types that can be null and works accordingly. I find the `HasData` moniker also a bit too cryptic for my taste. Functionally it makes sense, but people can have definitions for it that differ. I think adjusting what we have to add the scenario you're mentioning might be the better way to go.

**Comment by jfversluis** [comment]
@IeuanWalker is that feedback you can work with? Are you up for it? Else we can see if we will have a look or leave it for now.

**Comment by IeuanWalker** [comment]
@jfversluis ye ill take a look over the weekend

**Comment by IeuanWalker** [comment]
@jfversluis just about to do this, created a new fork, but got 91 error all inside the `CameraViewRenderer.uwp.cs` class.
I've done a clean/ rebuild, NuGet restore etc, so not sure how to get around it -
![image](https://user-images.githubusercontent.com/6544051/92504637-d8d24b80-f1fa-11ea-90b4-e5b03f28b583.png)

**Comment by jfversluis** [comment]
@bmacombe does that mean anything to you? With my limited UWP knowledge I would say you don't have the right UWP target SDK installed?

**Comment by bmacombe** [comment]
@IeuanWalker @jfversluis Yeah, that looks similar to the issue I was having yesterday.  Make sure the 16299 SDK is installed with the VS installer.

**Comment by bmacombe** [comment]
Under individual components in the VS installer
![image](https://user-images.githubusercontent.com/15127788/92512873-145a1f00-f1d5-11ea-9b21-063c4856ae50.png)

**Comment by jfversluis** [comment]
We should draft a list of prerequisites people should have installed to get started with contributing as well

**Comment by AndreiMisiukevich** [comment]
I guess we will go ahead with two separate converters approach for now.
