### ISSUE TITLE
AsyncCommand throwing exception in UWP release version

### ISSUE THREAD

**Issue by vishnupadakath1** [xamarin/XamarinCommunityToolkit#1771]
Hi

Using AsyncCommand in .net standard library causes UWP project  to break in release mode. The debug mode works fine . 

I am  using  the following code 

 this.Button.Command = new AsyncCommand(this.OnButtonClicked, allowsMultipleExecutions: false);

I tried to add the assembly  in the App.xaml.cs before Init() in the UWP project  , but did not help.

  typeof(Xamarin.CommunityToolkit.ObjectModel.AsyncCommand).GetTypeInfo().Assembly

Also tried adding the below code  in RegisterServices , but that also didnt help 
 DependencyService.Register<IAsyncCommand,AsyncCommand>();
  DependencyService.Register<AsyncCommand>();

Also tried adding the below in Default.rd.xml, but not luck

    <Namespace Name="Xamarin.CommunityToolkit.ObjectModel" Dynamic="Required All"  />
    <Type Name="Xamarin.CommunityToolkit.ObjectModel.AsyncCommand" Dynamic="Required All" />
    <Type Name="Xamarin.CommunityToolkit.ObjectModel.IAsyncCommand" Dynamic="Required All" />

- Version with issue: 1.3.1 Xamarin Community tool kit 
  Xamarin Forms version : 5.0.0.2125
- IDE: VS 2019
- Platform Target Frameworks: 
  - UWP:  19041

Please find attached the exception i am getting .
![Exception](https://user-images.githubusercontent.com/96631850/147368658-3b6c7685-6bba-4821-9b54-24aefd713760.PNG)

Could you please check the issue and let me know . Your help will be much appreciated . Please let me know if you need any further information.

**Comment by bijington** [comment]
@vishnupadakath1 to confirm from our chat earlier I am closing this issue down as it is unrelated to the toolkit
