### ISSUE TITLE
[Bug] TouchEffect on Image crashes on Android 5.1

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#1774]
### Description

1.2.0 broke TouchEffect on Android 5 again..
See #969 for more details. This seems to be the same issue.

Error message is still
```
Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/widget/ImageView;.getForeground()Landroid/graphics/drawable/Drawable;"'
```
### Steps to Reproduce

1. Run this app on Android 5 emulator (or real device): https://github.com/maxkoshevoi/NureTimetable
2. Add a timetable
3. Click on setting icon on the right of the added timetable

<details>

![image](https://user-images.githubusercontent.com/6609929/147484504-26edb79a-5f9e-4548-9975-51eeae040437.png)

</details>

### Stack Trace

VS doesn't show it for this exception

### Basic Information

- Version with issue: 1.2.0 - 1.3.1
- Last known good version: 1.2.0-pre2
- IDE: VS2022 17.1 Preview 1.1
- Platform Target Frameworks: 
  - Android: 5.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich, could you please take a look at that?

**Comment by VladislavAntonyuk** [comment]
@maxkoshevoi , @AndreiMisiukevich I think the issue is on this line: https://github.com/xamarin/XamarinCommunityToolkit/blob/0db5b1925555c58100f96dfd8df57e7e47cc296d/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs#L81
should be: ```if (XCT.SdkInt < (int)BuildVersionCodes.M || !effect.NativeAnimation)```
