### ISSUE TITLE
[Bug] The iOS Snack bar is not showing action button when the message's text is long

### ISSUE THREAD

**Issue by DamienDoumer** [xamarin/XamarinCommunityToolkit#1777]
### Description

The snackbar control on iOS, doesn't show action buttons when the message text is of a certain length.

### Link to Reproduction Sample
Here is a sample to reproduce.

`                  
             Shell.Current.DisplaySnackBarAsync(new SnackBarOptions
              {
                MessageOptions = new MessageOptions
                {
                    Foreground = Color.White,
                    Message = message
                },
                BackgroundColor = Color.DodgerBlue,
                Duration = TimeSpan.FromSeconds(5),
                Actions = new[]
                {
                    new SnackBarActionOptions
                    {
                        Text = buttonText,
                        ForegroundColor = Color.White,
                        Action = () => Task.FromResult(true)
                    }
                }
            });
`

### Steps to Reproduce

1. Create a Xamarin Forms app, preferably one with Shell navigation
2. Install Xamarin Community Toolkit
3. Call the snack bar control as shown above. (You can do this at any moment in your app)
4. in addition to the code snippet above, You can find the source code [with a reproduction here ](https://github.com/xamarin/Xamarin.Forms/files/7789932/ShellbugReproduction.zip)
### Expected Behavior

The snack bar's actions should display just like it does on android

### Actual Behavior

The snack bar actions do not display. See the image below
![Screenshot 2021-12-29 at 17 31 43](https://user-images.githubusercontent.com/16731017/147684509-1810fd5a-45c9-47a3-a9e6-22e2f3e5607c.png)

### Basic Information

- Version with issue: 1.3
- IDE: Visualstudio 2019
- Platform Target Frameworks: Xamarin.iOS
- Nuget Packages:
Xamarin Community Toolkit
- Affected Devices: Any iPhone

**Comment by pictos** [comment]
@DamienDoumer 
Could you attach a small repro?

**Comment by DamienDoumer** [comment]
@pictos Yeah, I just did.

**Comment by pictos** [comment]
@VladislavAntonyuk can you take a look on this one?
