### ISSUE TITLE
System.Exception: 'Handler not found for view Xamarin.CommunityToolkit.UI.Views.Expander

### ISSUE THREAD

**Issue by vplife1** [xamarin/XamarinCommunityToolkit#1788]
I have used Visual studio 2022 preview 2.0 MAUI.I want to used a expander using Community toolkit ,But right now i am facing a exception " System.Exception: 'Handler not found for view Xamarin.CommunityToolkit.UI.Views.Expander.'" How can i resolve this issue please Guide me .

Also I have download the nuget.
1)Xamarin Community Toolkit Markup MauiCompat
2)Xamarin.CommunityToolkit.MauiCompat
NOTE:--I want a MAUI Expander Control Please share me a solution
My View Is:-

NameSpace:-
xmlns:behaviors="http://xamarin.com/schemas/2020/toolkit"
View:-
behaviors:Expander
behaviors:Expander.Header 

<Image.Triggers>
</Image.Triggers>

</behaviors:Expander.Header>

<behaviors:Expander.ContentTemplate>
<DataTemplet>
</DataTemplet>
</behaviors:Expander.ContentTemplate>

</behaviors:Expander>

**Comment by pictos** [comment]
@vplife1 
Could you attach a small repro?

**Comment by vplife1** [comment]
@pictos I have create a small project . used Visual studio 2022 preview 2.0 MAUI.
Now the Expander UI is not display please check .Download my source.

https://github.com/vplife1/MauiApp3.git

**Comment by VladislavAntonyuk** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/issues/1750#issuecomment-985645536

**Comment by vplife1** [comment]
@pictos  Have you check??

**Comment by pictos** [comment]
@vplife1 didn't have a chance yet, I was working on other tasks. As mentioned by @VladislavAntonyuk if you're using a MAUI application you shouldn't use our MauiCompat packages use [this](https://www.nuget.org/packages/CommunityToolkit.Maui/1.0.0-pre4) instead. Be aware that this version was built on top of Maui p11, so it may fail on p12

**Comment by vplife1** [comment]
@pictos  Thank you reply. I will happy to use Maui Community Toolki.

**Comment by Lucasvor** [comment]
@vplife1 I managed to make it work with MAUI by removing the BaseTemplatedView and copying the source code from xf community (Expander), implementing the component from scratch.

Preview: 
![expander](https://user-images.githubusercontent.com/14074376/171087216-b098c158-1034-4af8-95b6-0463e47083f0.gif)

**Comment by VladislavAntonyuk** [comment]
Expander will be a part of MCT 1.1.0
