### ISSUE TITLE
Failed to resolve assembly on Android

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#18]
_From @MuhammadRashid on February 14, 2017 15:35_

Getting following exception when run on Android: 
Failed to resolve assembly: 'FormsCommunityToolkit.Effects, Culture=neutral, PublicKeyToken=null' (ThinkTime.Droid)

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
Please fill in what you would like

_Copied from original issue: FormsCommunityToolkit/Effects#47_

**Comment by pauldipietro** [comment]
I don't think this occurs any more; the merged updates all run as expected. We can reopen this if we get a specific scenario to look at.
