### ISSUE TITLE
[Bug] popup throw exception when page Appearing

### ISSUE THREAD

**Issue by KevinAnass** [xamarin/XamarinCommunityToolkit#1807]
hi everyone, i have issue with popup in **UWP** when page apearing the popup throw exception 
App.Current.MainPage.Navigation.ShowPopup(new Searching()); => System.ArgumentException: 'The parameter is incorrect.
element'
that happen just when command come from Appearing

xamarin forms version 5.0.0.2337
xamarin community toolkit version 2.0.0

this exception throw just in the UWP and when page on apearing

**Comment by bijington** [comment]
@KevinAnass please in future use our templates as it asks for a bit more detail, they can be found at: https://github.com/xamarin/XamarinCommunityToolkit/issues/new/choose or when clicking on New issue.

Are you able to provide some more details:

- The full stack trace of the exception
- A sample that reproduces the issue

**Comment by KevinAnass** [comment]
thank you i fix it buy using the lifecycle 
but still the background color of the popup transparent
