### ISSUE TITLE
[Bug] MediaElement throws on some devices Java.Lang.ClassNotFoundException: Didn't find class "android.media.PlaybackParams"

### ISSUE THREAD

**Issue by gsgou** [xamarin/XamarinCommunityToolkit#1809]
### Description

MediaElement throws Java.Lang.ClassNotFoundException: Didn't find class "android.media.PlaybackParams"

### Stack Trace

JniEnvironment+Types.FindClass (System.String classname)
Java.Interop.JniType..ctor (System.String classname) [0x00006] in <8b88d9f4da164ead9096e67e03e6def4>:0
JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname)
JniPeerMembers.get_JniPeerType ()
JniPeerMembers+JniInstanceMethods.get_JniPeerType ()
JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters)
Android.Media.PlaybackParams..ctor () [0x00034] in <e8df2f283ecb4fe0b10a49bd33ffa07a>:0
MediaElementRenderer.UpdateSpeed ()
IOnPreparedListener.OnPrepared (Android.Media.MediaPlayer mp)
MediaPlayer+IOnPreparedListenerInvoker.n_OnPrepared_Landroid_media_MediaPlayer_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_mp)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.109(intptr,intptr,intptr)
java.lang.ClassNotFoundException: Didn't find class "android.media.PlaybackParams" on path: DexPathList[[zip file "/data/app/com.xxx.yyy-1/base.apk", zip file "/data/app/com.xxx.yyy-1/split_config.ar.apk", zip file "/data/app/com.xxx.yyy-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.xxx.yyy-1/split_config.de.apk", zip file "/data/app/com.xxx.yyy-1/split_config.hdpi.apk"],nativeLibraryDirectories=[/data/app/com.xxx.yyy-1/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass BaseDexClassLoader.java:56
java.lang.ClassLoader.loadClass ClassLoader.java:511
java.lang.ClassLoader.loadClass ClassLoader.java:469
crc642e1c7a98bdb5c44a.MediaElementRenderer.n_onPrepared(Native Method)
crc642e1c7a98bdb5c44a.MediaElementRenderer.onPrepared(Unknown Source)
android.widget.VideoView$2.onPrepared VideoView.java:467
android.media.MediaPlayer$EventHandler.handleMessage MediaPlayer.java:3387
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:145
android.app.ActivityThread.main ActivityThread.java:6917
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke Method.java:372
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1404
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1199
Suppressed: java.io.IOException: Zip archive '/data/app/com.xxx.yyy-1/split_config.ar.apk' doesn't contain classes.dex (error msg: Entry not found)
dalvik.system.DexFile.openDexFileNative(Native Method)
dalvik.system.DexFile.openDexFile DexFile.java:295
dalvik.system.DexFile.<init> DexFile.java:80
dalvik.system.DexFile.<init> DexFile.java:59
dalvik.system.DexPathList.loadDexFile DexPathList.java:262
dalvik.system.DexPathList.makeDexElements DexPathList.java:231
dalvik.system.DexPathList.<init> DexPathList.java:109
dalvik.system.BaseDexClassLoader.<init> BaseDexClassLoader.java:48
dalvik.system.PathClassLoader.<init> PathClassLoader.java:65
dalvik.system.PathClassLoader.openArtFile PathClassLoader.java:76
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke Method.java:372
android.app.ApplicationLoaders.openArtFile ApplicationLoaders.java:62
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:118
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:45
android.app.LoadedApk.getClassLoader LoadedApk.java:419
android.app.LoadedApk.makeApplication LoadedApk.java:644
android.app.ActivityThread.handleBindApplication ActivityThread.java:5985
android.app.ActivityThread.access$1700 ActivityThread.java:218
android.app.ActivityThread$H.handleMessage ActivityThread.java:1779
... 7 more
Caused by: java.io.IOException: Failed to open oat file from dex location '/data/app/com.xxx.yyy-1/split_config.ar.apk'
... 27 more
Caused by: java.io.IOException: Failed to open oat file from /data/app/com.xxx.yyy-1/arm/split_config.ar.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
... 27 more
Caused by: java.io.IOException:
... 27 more
Suppressed: java.io.IOException: Zip archive '/data/app/com.xxx.yyy-1/split_config.armeabi_v7a.apk' doesn't contain classes.dex (error msg: Entry not found)
dalvik.system.DexFile.openDexFileNative(Native Method)
dalvik.system.DexFile.openDexFile DexFile.java:295
dalvik.system.DexFile.<init> DexFile.java:80
dalvik.system.DexFile.<init> DexFile.java:59
dalvik.system.DexPathList.loadDexFile DexPathList.java:262
dalvik.system.DexPathList.makeDexElements DexPathList.java:231
dalvik.system.DexPathList.<init> DexPathList.java:109
dalvik.system.BaseDexClassLoader.<init> BaseDexClassLoader.java:48
dalvik.system.PathClassLoader.<init> PathClassLoader.java:65
dalvik.system.PathClassLoader.openArtFile PathClassLoader.java:76
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke Method.java:372
android.app.ApplicationLoaders.openArtFile ApplicationLoaders.java:62
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:118
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:45
android.app.LoadedApk.getClassLoader LoadedApk.java:419
android.app.LoadedApk.makeApplication LoadedApk.java:644
android.app.ActivityThread.handleBindApplication ActivityThread.java:5985
android.app.ActivityThread.access$1700 ActivityThread.java:218
android.app.ActivityThread$H.handleMessage ActivityThread.java:1779
... 7 more
Caused by: java.io.IOException: Failed to open oat file from dex location '/data/app/com.xxx.yyy-1/split_config.armeabi_v7a.apk'
... 27 more
Caused by: java.io.IOException: Failed to open oat file from /data/app/com.xxx.yyy-1/arm/split_config.armeabi_v7a.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
... 27 more
Caused by: java.io.IOException:
... 27 more
Suppressed: java.io.IOException: Zip archive '/data/app/com.xxx.yyy-1/split_config.de.apk' doesn't contain classes.dex (error msg: Entry not found)
dalvik.system.DexFile.openDexFileNative(Native Method)
dalvik.system.DexFile.openDexFile DexFile.java:295
dalvik.system.DexFile.<init> DexFile.java:80
dalvik.system.DexFile.<init> DexFile.java:59
dalvik.system.DexPathList.loadDexFile DexPathList.java:262
dalvik.system.DexPathList.makeDexElements DexPathList.java:231
dalvik.system.DexPathList.<init> DexPathList.java:109
dalvik.system.BaseDexClassLoader.<init> BaseDexClassLoader.java:48
dalvik.system.PathClassLoader.<init> PathClassLoader.java:65
dalvik.system.PathClassLoader.openArtFile PathClassLoader.java:76
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke Method.java:372
android.app.ApplicationLoaders.openArtFile ApplicationLoaders.java:62
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:118
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:45
android.app.LoadedApk.getClassLoader LoadedApk.java:419
android.app.LoadedApk.makeApplication LoadedApk.java:644
android.app.ActivityThread.handleBindApplication ActivityThread.java:5985
android.app.ActivityThread.access$1700 ActivityThread.java:218
android.app.ActivityThread$H.handleMessage ActivityThread.java:1779
... 7 more
Caused by: java.io.IOException: Failed to open oat file from dex location '/data/app/com.xxx.yyy-1/split_config.de.apk'
... 27 more
Caused by: java.io.IOException: Failed to open oat file from /data/app/com.xxx.yyy-1/arm/split_config.de.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
... 27 more
Caused by: java.io.IOException:
... 27 more
Suppressed: java.io.IOException: Zip archive '/data/app/com.xxx.yyy-1/split_config.hdpi.apk' doesn't contain classes.dex (error msg: Entry not found)
dalvik.system.DexFile.openDexFileNative(Native Method)
dalvik.system.DexFile.openDexFile DexFile.java:295
dalvik.system.DexFile.<init> DexFile.java:80
dalvik.system.DexFile.<init> DexFile.java:59
dalvik.system.DexPathList.loadDexFile DexPathList.java:262
dalvik.system.DexPathList.makeDexElements DexPathList.java:231
dalvik.system.DexPathList.<init> DexPathList.java:109
dalvik.system.BaseDexClassLoader.<init> BaseDexClassLoader.java:48
dalvik.system.PathClassLoader.<init> PathClassLoader.java:65
dalvik.system.PathClassLoader.openArtFile PathClassLoader.java:76
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke Method.java:372
android.app.ApplicationLoaders.openArtFile ApplicationLoaders.java:62
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:118
android.app.ApplicationLoaders.getClassLoader ApplicationLoaders.java:45
android.app.LoadedApk.getClassLoader LoadedApk.java:419
android.app.LoadedApk.makeApplication LoadedApk.java:644
android.app.ActivityThread.handleBindApplication ActivityThread.java:5985
android.app.ActivityThread.access$1700 ActivityThread.java:218
android.app.ActivityThread$H.handleMessage ActivityThread.java:1779
... 7 more
Caused by: java.io.IOException: Failed to open oat file from dex location '/data/app/com.xxx.yyy-1/split_config.hdpi.apk'
... 27 more
Caused by: java.io.IOException: Failed to open oat file from /data/app/com.xxx.yyy-1/arm/split_config.hdpi.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
... 27 more
Caused by: java.io.IOException:
... 27 more
Suppressed: java.lang.ClassNotFoundException: android.media.PlaybackParams
java.lang.Class.classForName(Native Method)
java.lang.BootClassLoader.findClass ClassLoader.java:781
java.lang.BootClassLoader.loadClass ClassLoader.java:841
java.lang.ClassLoader.loadClass ClassLoader.java:504
... 12 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

### Steps to Reproduce

1.  Simple load a video from local file in MediaElement

### Expected Behavior

App does not crash by throwing exception

### Actual Behavior

App crashes

### Basic Information

- Version with issue: 1.3.1
- IDE:
- Platform Target Frameworks: 
  - Android: 12.0
- Affected Devices:
Galaxy J1(2016) - Android 5.1.1
Y6 Pro - Android 5.1

**Comment by gsgou** [comment]
relates to this https://github.com/google/ExoPlayer/issues/1977. Maybe catch it internally?

**Comment by Bonalogic** [comment]
Can it be related to API level? My Huawei 5.1.1 app crashes but Samsung 6 is working.

**Comment by bijington** [comment]
> Can it be related to API level? My Huawei 5.1.1 app crashes but Samsung 6 is working.

I think you have spotted the issue!

From Google's [documentation](https://developer.android.com/reference/android/media/PlaybackParams):

> Added in API level 23

And API level 23 is Android 6.0

**Comment by bijington** [comment]
Interestingly when I run the sample app up on an API 22 device I see this logged out to the console a lot:

> : This functionality is not available. Minimum supported API is 23

I haven't worked out what it relates to yet though

**Comment by gsgou** [comment]
When is planned a new release including this and few other MediaElement fixes:
https://github.com/xamarin/XamarinCommunityToolkit/projects/2

Currently nightly build does not include it yet being on v1.4.0-preview1006 right?
We had a lot of crashes and the quickest fix was so far to increase the min API.

**Comment by bijington** [comment]
@gsgou I don't know when the next release will be out but the current version is 2.0.0 so I would expect the nightly build to be from that version+.

@jfversluis do you know much about the nightly feed? It does appear our latest version is v1.4.0-preview1006 which doesn't seem right to me:
![Screenshot 2022-03-01 at 08 59 12](https://user-images.githubusercontent.com/17139988/156137759-a08c2e9b-7b0d-4621-bf27-a181377a4473.png)

**Comment by gsgou** [comment]
@bijington , @jfversluis i opened a ticket for the deprecated nightly build in case it helps prioritizing.
https://github.com/xamarin/XamarinCommunityToolkit/issues/1825
