### ISSUE TITLE
[Bug] Nightly build is stuck on v1.4.0-preview1006

### ISSUE THREAD

**Issue by gsgou** [xamarin/XamarinCommunityToolkit#1825]
### Description

Current version of XCT is 2.0.0 so the nightly build should derive from that version.
It does appear latest nightly build to be v1.4.0-preview1006 from 23.01.2022.

![156137759-a08c2e9b-7b0d-4621-bf27-a181377a4473](https://user-images.githubusercontent.com/911534/156552756-9ef7d0c9-dbce-472d-ae75-169e02f47b90.png)

**Comment by VladislavAntonyuk** [comment]
I believe nightly build was set to the develop branch, which is not used right now.
@jfversluis do we plan to have nightly builds?

**Comment by jfversluis** [comment]
I'll look into it!

**Comment by jfversluis** [comment]
It should work again! There is a version pushed right now with all the latest changes from main. You can find it under 2.0.0-*. 

Technically this wasn't correct, so I also updated the version number now to be 2.1.0-* so now we'll just have to wait and see if it also works when it's triggered at night automatically :)

You should be able to use the package that I released just now for what you want to do and not fork the repo at least. Let us know if there is still anything else!

**Comment by gsgou** [comment]
Thanks for the quick resolution. Curious to see on next build what time night falls in Xamarinland :)
