### ISSUE TITLE
[Bug] CameraView not avaiable in UWP MauiCompat, even though the code is here

### ISSUE THREAD

**Issue by StonedHackerman** [xamarin/XamarinCommunityToolkit#1837]
### Description

When I create a new MAUI project, and add the latest Xamarin.CommunityToolkit.MauiCompat NuGet package, and then try to use a CameraView, the project refuses to compile on Windows, saying that it's "not avaiable", which must be the mistake, because I can see the code right here: https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/UWP/CameraViewRenderer.uwp.cs

### Steps to Reproduce

1. Create new MAUI project
2. Install-Package Xamarin.CommunityToolkit.MauiCompat -Version 2.0.1-preview1007
3. try to reference CameraViewRenderer somewhere in code, then compile on Windows

### Expected Behavior

Project compiles and CameraView works

### Actual Behavior

VS complains

### Basic Information

- Version with issue: latest version Xamarin.CommunityToolkit.MauiCompat 2.0.1-preview1007
- Last known good version: never, older versions are broken too
- IDE: latest version VS 2022 and MAUI Preview 14
- Platform Target Frameworks: 
  - iOS:  net6.0-ios;net6.0-maccatalyst
  - Android: net6.0-android
  - UWP:  net6.0-windows10.0.19041
- Nuget Packages:
- Affected Devices:

### Reproduction imagery

<img width="932" alt="Screenshot 2022-03-27 22 40 46" src="https://user-images.githubusercontent.com/16528222/160300377-5d9a0e86-0618-4274-aa8d-fdeed1dd4b8b.png">

**Comment by pictos** [comment]
@StonedHackerman can you confirm that you're targeting an UWP app? Because .NET MAUI doesn't support UWP but WinUI3

**Comment by StonedHackerman** [comment]
Yes, I am targeting an UWP app

**Comment by pictos** [comment]
@StonedHackerman not sure if we still have an issue with the Windows target, but in your scenario, it shouldn't work, since .NET MAUI doesn't support UWP applications.

So I'll close this issue. If you change your project to be a WinUI3 project and still see the error comment here and we'll reopen this issue or you can create a new issue with more info and a sample project (:

**Comment by StonedHackerman** [comment]
sorry, I'm actually confused, I thought UWP and WinUI3 mean the same thing in this context, and I always read that MAUI supports Android, IOS and Windows, and when you create the project, under the Platforms directory, there is a Windows subdirectory, so I meant whatever "Windows" means in this context. Sorry for my ignorance 😅.
I just created an empty MAUI app, switched target framework to net6.0-windows10.0.19041 and clicked run. 

I attached a sample app here, as well as detailed screenshots of what I did.

<img width="768" alt="Screenshot 2022-03-29 19 56 24" src="https://user-images.githubusercontent.com/16528222/160680671-c20707f9-507c-427e-9dc6-d2550831af22.png">

<img width="345" alt="Screenshot 2022-03-29 20 10 38" src="https://user-images.githubusercontent.com/16528222/160680687-02c87f73-9e76-4890-94fb-29a0441dc7a7.png">

<img width="963" alt="Screenshot 2022-03-29 20 12 10" src="https://user-images.githubusercontent.com/16528222/160680819-58296bbf-451c-4fb9-a055-88c7631ae4fd.png">

<img width="1266" alt="Screenshot 2022-03-29 20 27 38" src="https://user-images.githubusercontent.com/16528222/160680853-8da1a4b7-4ab1-4ca3-a995-e74c132e1909.png">


[Sample.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/8374114/Sample.zip)

**Comment by VladislavAntonyuk** [comment]
@pictos MauiCompat doesn't support UWP apps, so we do not migrate and build the project. I think this won't be fixed

**Comment by pictos** [comment]
@VladislavAntonyuk I know, but he's using WinUI. He should got confused by names

**Comment by VladislavAntonyuk** [comment]
that is why it doesn't work. We didn't migrate XCT UWP to XCT MauiCompat WinUI, because WinUI doesn't have the all features which are available for the UWP.

**Comment by pictos** [comment]
Oh I see now! Good to know, well closing this again.
