### ISSUE TITLE
[Bug] UWP ShadowEffect does not work when using XCT nuget package

### ISSUE THREAD

**Issue by ConnorJBrown** [xamarin/XamarinCommunityToolkit#1841]
### Description

ShadowEffect is not working for me on UWP when I use the toolkit via a NuGet package.
If I download this repo and reference the XamarinCommunityToolkit project directly then the shadow works.

### Link to Reproduction Sample
[XCTShadowEffectUsingNuget.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/8448309/XCTShadowEffectUsingNuget.zip)

### Steps to Reproduce
1. Create a blank Xamarin.Forms project 
2. Install Xamarin Community Toolkit via the nuget package manager - may need Xamarin.Forms to be updated
3. Add a shadow to Mainpage.xaml
4. Launch UWP

### Expected Behavior
A shadow is shown
### Actual Behavior
A shadow is not shown
### Basic Information

- Version with issue: 2.0.1
- Last known good version: N/A
- IDE: VS2022 17.1.3
- Platform Target Frameworks:
  - UWP:  10.0.20348.0
- Affected Devices: UWP

### Workaround
If I download this repo and reference the project directly then the shadow works.

### Reproduction imagery
Using a project reference:
![image](https://user-images.githubusercontent.com/42499131/162357739-72774e52-6e19-4013-a620-2ceaa5ade4b1.png)

Using the nuget package:
![image](https://user-images.githubusercontent.com/42499131/162358140-831eb376-ac77-4b74-9ffa-cb4259d32967.png)

**Comment by bijington** [comment]
@ConnorJBrown are you only using the ShadowEffect in XAML or the toolkit in any C#?

**Comment by ConnorJBrown** [comment]
@bijington Only in XAML

**Comment by bijington** [comment]
> @bijington Only in XAML

Can you try referring to it in C# too just to see if the linker/compiler is ripping it out at build time?

**Comment by bijington** [comment]
@ConnorJBrown thanks for the update. I will aim to try and pull the latest NuGet Package and decompile it so see what is inside.

**Comment by bijington** [comment]
@ConnorJBrown I have downloaded the latest package from NuGet and decompiled it. You can see that the `PlatformShadowEffect` class is included in the package:

![Screenshot 2022-04-19 at 13 07 28](https://user-images.githubusercontent.com/17139988/163999856-e92ec5af-c9c7-4cae-b7c5-d56385894980.png)

This is from the `uap10.0.18362` folder. Are you able to confirm which framework your reference is pulling? I think you can check this by checking References under your project and then viewing the full path in the Properties pane.

**Comment by bijington** [comment]
Sadly my windows development environment is a little messed up at the moment, hopefully I can sort it out this week to try those steps.

`ShadowEffect` should be in the shared codebase as you mention but the platform specific part should be in the one that I mentioned.

**Comment by ConnorJBrown** [comment]
Ah no worries.

I am not able to navigate to the definition of UWP PlatformShadowEffect

![image](https://user-images.githubusercontent.com/42499131/164094219-e3879712-7e5a-4d0b-926b-041be104598c.png)

However this works fine for the Android and iOS projects

**Comment by bijington** [comment]
So where is the reference inside the UWP project pointing to for the XCT package? I wonder if it is bringing in the wrong dll somehow

**Comment by ConnorJBrown** [comment]
I am not sure how to check that, the properties pane is empty when selecting Xamarin.CommunityToolkit reference

![image](https://user-images.githubusercontent.com/42499131/164096997-b3da0af3-6fc0-49d0-af61-ac57544d305a.png)

**Comment by ConnorJBrown** [comment]
Actually navigating to the definition of ShadowEffect is different for each of the platforms. I think the location for UWP is
`C:\Users\Connor\.nuget\packages\xamarin.communitytoolkit\2.0.1\lib\netstandard2.0\Xamarin.CommunityToolkit.dll`

Repeating the same steps for Android gives 
` C:\Users\Connor\.nuget\packages\xamarin.communitytoolkit\2.0.1\lib\monoandroid10.0\Xamarin.CommunityToolkit.dll`

**Comment by bijington** [comment]
I have tried creating a new application under Visual Studio 2019 and I can confirm that I see the same issue. For some reason the UWP project appears to be taking the `netstandard2.0` dll and not the `uap10.0.18362` dll

**Comment by bijington** [comment]
I sadly don't have a clue why it is doing this yet. Is it because the `netstandard2.0` is in the list of dependencies before the uap one?

**Comment by VladislavAntonyuk** [comment]
If I am not mistaken we had the same issue in MCT where we put the artifacts in the same folder and they were overwritten.
I will take a look. It may fix a lot of issues related to UWP

**Comment by bijington** [comment]
That's great thanks @VladislavAntonyuk

**Comment by VladislavAntonyuk** [comment]
I can check later the fix.
But could you also try if this nuget package fixes the issue: https://dev.azure.com/xamarin/public/_build/results?buildId=60755&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by bijington** [comment]
I wonder how the NuGet reference compatibility is decided when pulling the package in. `netstandard2.0` is earlier in the list before `uap..` so perhaps it wins and is pulled in?

**Comment by VladislavAntonyuk** [comment]
You have MinVersion 16299, Update it to at least 18362
![image](https://user-images.githubusercontent.com/33021114/165160327-3e33b0a2-ec8f-49cd-b8ad-ece03952db59.png)

**Comment by bijington** [comment]
Oh yeah great spot! That explains why the `netstandard2.0` reference was being used as the `uap` one wasn't compatible with the minimum version

**Comment by ConnorJBrown** [comment]
Thanks @VladislavAntonyuk! Is this included in documentation somewhere? I did not realize that the min version needed to be upgraded.

**Comment by VladislavAntonyuk** [comment]
I believe it comes from Nuget.org: https://www.nuget.org/packages/Xamarin.CommunityToolkit/
![image](https://user-images.githubusercontent.com/33021114/165166520-fd75b414-d97b-4e0f-9e03-9b19aeb2b7be.png)
where the blue is a minimum supported version.
