### ISSUE TITLE
com.android.tools.r8.CompilationFailedException: Compilation failed to complet (MAUI RC1)

### ISSUE THREAD

**Issue by aherrick** [xamarin/XamarinCommunityToolkit#1842]
With RC1 Maui I'm getting the following error with the latest Maui Compat:

`com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\andrew.j.herrick\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class	TappedIn	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.D8.targets	79`

`	  <PackageReference Include="Xamarin.CommunityToolkit.MauiCompat" Version="2.0.1-preview1007" />
`

**Comment by bijington** [comment]
@aherrick I have seen a similar issue when compiling the toolkits sample application. The solution involved manually deleting the `bin` and `obj` folders and then trying again. Have you tried this?

**Comment by pictos** [comment]
@bijington looks like the issue is on our side, we need to compile against `MAUI RC1`
as you can see here https://github.com/xamarin/AndroidX/issues/509#issuecomment-1100465193

**Comment by bijington** [comment]
Oh good spot!
