### ISSUE TITLE
[Bug]  Setting Linking "Link Framework SDK Only"  thorwing Xaml parsing error on app.xaml

### ISSUE THREAD

**Issue by TrueTech-Source** [xamarin/XamarinCommunityToolkit#1849]
### Description
I'm Working a project in which i have need to set Linking to "Link Framework SDK Only" but when i turn this settting I'm getting the Xaml parse on app.xaml. If I turn this setting to "Don't Link" then it start working  but the problem i cannot use "Don't link"  due to some plugin of third party which require to set Linking "Link Framework SDK Only" I'm stuck on this issue anyone have resolved it or any suggestion.
The things i have tried
1: Updating the Xamarin.Essential verison to stable verision 1.7.2 not woking
2: updated the Xamarin forms version to latest stable and it still not wowking 

### Stack Trace
<img width="1079" alt="Screenshot 2022-04-26 at 1 57 26 AM" src="https://user-images.githubusercontent.com/56385550/165174701-360b3ed9-2e99-4e61-97aa-09a436d344ef.png">

### Steps to Reproduce
Please set these setting and run on physical device
<img width="742" alt="Screenshot 2022-04-26 at 1 55 52 AM" src="https://user-images.githubusercontent.com/56385550/165174881-d9178b99-c3d4-4bb4-9581-77caa25acaa0.png">

### Expected Behavior
It should not show error of xaml parse exception with the  linking  of "Link Framework SDK Only"
### Actual Behavior
Showing error of Xaml Parse Exception
<img width="1079" alt="Screenshot 2022-04-26 at 1 57 26 AM" src="https://user-images.githubusercontent.com/56385550/165174701-360b3ed9-2e99-4e61-97aa-09a436d344ef.png">
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019 Community
- Platform Target Frameworks: 
  - iOS:  11
- Nuget Packages: 
     Xamarin.Essentials 1.7.1
    Xamarin  forms 5.0.0.2012
- Affected Devices:
   Apple Iphone Xs and software version of iphone 14.7.1

**Comment by pictos** [comment]
You can create a linker.xml file and add the Popup to it, that way the Linker will keep the Popup

**Comment by pictos** [comment]
@TrueTech-Source please, take a look at [this doc](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker)

**Comment by TrueTech-Source** [comment]
> You can create a linker.xml file and add the Popup to it, that way the Linker will keep the Popup

Thanks its working now
