### ISSUE TITLE
[Bug] [CameraView] [Android] Flash works just for the first capture

### ISSUE THREAD

**Issue by GUOLDEV** [xamarin/XamarinCommunityToolkit#1863]
### Description

The CameraView does not trigger the flashlight after the first capture even keeping the FlashMode as On.

### Link to Reproduction Sample

This issue can be reproduced on XCT CameraView Sample.
### Steps to Reproduce

1. Open CameraView
2. Turn on Flash
3. Tap SNAP PICTURE, the flash works
4. Tap SNAP PICTURE again, the flash doesn't work

### Expected Behavior

The flash works for all creatures if on.

### Actual Behavior

The flash works just for the first capture

### Basic Information

- Version with issue: main branch
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

I couldn't find a good workaround, I have even tried forcing Turn Flash Off and then Turn Flash On again.

**Comment by GUOLDEV** [comment]
Hi @jfversluis 👋  I am going to work on a few issues around the CameraView reported by the community, but before that I really need this Flash issue fixed, so that is why I have created the issue and pushed a PR for it already.

**Comment by GUOLDEV** [comment]
@brminnick @pictos 🙏

**Comment by pictos** [comment]
thanks @GUOLDEV will review your PR later today (:
