### ISSUE TITLE
[Bug] AsyncCommand overriding IsEnable value 

### ISSUE THREAD

**Issue by PugTheMightyDog** [xamarin/XamarinCommunityToolkit#1878]
### Link to Reproduction Sample
.XAML
`        <Button
            Text="CLICK ME!"
            Command="{Binding TestCommand}"
            IsEnabled={Binding IsButtonEnabled} />`

ViewModel code

`TestCommand = new AsyncCommand(OnTestPressed, allowsMultipleExecutions:false);`
```
private async Task OnTestPressed()
{
    IsButtonEnabled = false;
}

```

### Steps to Reproduce

1. Invoke Button AsyncCommand allowMultipleExecutions: false
2. In the AsyncCommand action, disable the Button and Task.Await().
6. After the AsyncCommand completes execution, the button is enabled.

### Expected Behavior
The Button should remain disabled.
### Actual Behavior
The Button is Enabled. The AsyncCommand is overriding the IsEnabled value.

### Basic Information
- Version with issue: 2.0.2
- Last known good version:
- IDE: Visual Studio 2022 
- Platform Target Frameworks: 
  - Android:  12 (S)
- Nuget Packages:
- Affected Devices:

### Workaround

The workaround is either to use Command instead of AsyncCommand, or use AsyncCommand and set allowsMultipleExecutions: true.
### Reproduction imagery

**`TestCommand = new AsyncCommand(OnTestPressed, allowsMultipleExecutions:false);`**

https://user-images.githubusercontent.com/24286072/176043707-540d783a-f231-43cb-b7fe-8df0e42c2f47.mp4

**`TestCommand = new AsyncCommand(OnTestPressed, allowsMultipleExecutions:true);`**

https://user-images.githubusercontent.com/24286072/176043700-a751ef15-f4f2-41d7-9d0d-d4166bc7edd4.mp4

**Comment by PugTheMightyDog** [comment]
> @PugTheMightyDog I think the videos are under the wrong headings, either that or I am misunderstanding the issue.
> 
> That aside the disabling of the button is by design, in fact the actual disabling is performed via the CanExecute implementation of Commands in general and I would recommend that you investigate using those instead of using a boolean property to control it. Essentially `AsyncCommand` returns false for CanExecute at the start of your method and ultimately returns true once your method has finished. This is to prevent users from tapping on the button multiple times and triggering the code to execute multiple times.
> 
> For more context on what `allowMultipleExecutions: false` does please check out this video https://docs.microsoft.com/en-gb/xamarin/community-toolkit/objectmodel/asynccommand starting at roughly 06:20.

Makes sense. It is a little counter-intuitive though, given the basic usage scenario. 

I think how `AsyncCommand` works "behind the curtains" is not very clear, because it requires separating the View's .XAML IsEnabled implementation from the `AsyncCommand` implementation. I have read through the documentation and XCT videos and have actually been using `AsyncCommand` for some time now.

I had to figure out that a `AsyncCommand` was overriding the IsEnabled binding. A feature like "if the Button IsEnabled Value has changed, don't return CanExecute" would be nice.

**Comment by bijington** [comment]
> > @PugTheMightyDog I think the videos are under the wrong headings, either that or I am misunderstanding the issue.
> > That aside the disabling of the button is by design, in fact the actual disabling is performed via the CanExecute implementation of Commands in general and I would recommend that you investigate using those instead of using a boolean property to control it. Essentially `AsyncCommand` returns false for CanExecute at the start of your method and ultimately returns true once your method has finished. This is to prevent users from tapping on the button multiple times and triggering the code to execute multiple times.
> > For more context on what `allowMultipleExecutions: false` does please check out this video https://docs.microsoft.com/en-gb/xamarin/community-toolkit/objectmodel/asynccommand starting at roughly 06:20.
> 
> Makes sense. It is a little counter-intuitive though, given the basic usage scenario.
> 
> I think how `AsyncCommand` works "behind the curtains" is not very clear, because it requires separating the View's .XAML `IsEnabled` implementation from the `AsyncCommand` implementation. I have read through the documentation and XCT videos and have actually been using `AsyncCommand` for some time now.
> 
> I had to figure out that `AsyncCommand` was overriding the `IsEnabled` binding. A feature like "if the Button `IsEnabled` Value has changed, don't return `CanExecute`" would be nice.

Thanks for this feedback, we appreciate that our documentation hasn't been the greatest on this toolkit. I will make a note to try and turn this feedback into something that can be added to that documentation page 👍
