### ISSUE TITLE
[Bug] Popup, Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view ...'

### ISSUE THREAD

**Issue by 8m0** [xamarin/XamarinCommunityToolkit#1885]
Hello, 
I get `Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view fortestingshit.Controls.SimpP.'` exception.
I've seen Microsoft documentation and other sources, same error anyway. 

### Stack Trace

```
Microsoft.Maui.Platform.HandlerNotFoundException
  HResult=0x80131500
  Message=Handler not found for view fortestingshit.Controls.SimpP.
  Source=Microsoft.Maui
  StackTrace:
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at CommunityToolkit.Maui.Views.PopupExtensions.PlatformShowPopup(Popup popup, IMauiContext mauiContext)
   at CommunityToolkit.Maui.Views.PopupExtensions.PlatformShowPopupAsync(Popup popup, IMauiContext mauiContext)
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[TPopup](Page page, TPopup popup)
   at fortestingshit.MainPage.<OnCounterClicked>d__1.MoveNext() in ...\fortestingshit\MainPage.xaml.cs:line 17
```

[Repository](https://github.com/8m0/Popup-HandlerNotFoundException)

Steps:
1. Open project
2. Click the "Click me to open popup" button

Ide etc.:
- IDE: Microsoft Visual Studio Community 2022, Version 17.3.0 Preview 2.0
- Platform Target Frameworks: 
    Android, Windows
- CommunityToolkit.Maui version 1.0.0

**Comment by pictos** [comment]
@8m0, the `Renderers and Handlers` story for MauiCompat isn't that great and we will not invest time in fixing it. For Popup, I would recommend you to use the CommunityToolkit.Maui package.

**Comment by pictos** [comment]
Good catch @bijington , I was in the auto-pilot mode xP

**Comment by pictos** [comment]
@8m0 please copy all the info and open an issue on the https://github.com/CommunityToolkit/Maui, as suggested by @bijington. Thanks in advance

**Comment by 8m0** [comment]
> @8m0 please copy all the info and open an issue on the https://github.com/CommunityToolkit/Maui, as suggested by @bijington. Thanks in advance

Done.
https://github.com/CommunityToolkit/Maui/issues/492
