### ISSUE TITLE
Type Converter Error when running Popup on iOS without debugging.

### ISSUE THREAD

**Issue by DanielMuhlig** [xamarin/XamarinCommunityToolkit#1889]
Eg. setting popup.Size = new Size(640, 480) works fine when running the app on an iPad in debug mode from Visual Studio, but crashes with error "Position 5:75. Type converter failed: Cannot convert "" into Microsoft.Maui.Graphics.Size" when starting app directly from the iPad.

This may be Maui related and not CommunityToolkit?

Edit: Same error if not setting the Size property on the popup!

**Comment by pictos** [comment]
@DanielMuhlig, please use the CommunityToolkit.Maui instead
