### ISSUE TITLE
[Bug] back button on Android is causing Command to execute from EventToCommandBehavior

### ISSUE THREAD

**Issue by FigmentCoder** [xamarin/XamarinCommunityToolkit#1891]
### Description

 When I tap the back button on Android the Command I have set for a Switch being toggled is executing.  This doesn't happen on iOS
`<Switch IsToggled="{Binding IsEnabled, Mode=TwoWay}"
                                    Grid.Row="1"
                                    Grid.Column ="5">
                                <Switch.Behaviors>
                                    <behaviors:EventToCommandBehavior 
                                        EventName="Toggled" 
                                        Command="{Binding Path=BindingContext.SaveReminderSelected, 
                                        Source={x:Reference Name=pageName}}" CommandParameter="{Binding .}"/>
                                </Switch.Behaviors>
</Switch>`
[ReminderView.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/9192160/ReminderView.zip)
Please see the attached xaml file for context
### Steps to Reproduce

1.  Navigate to the Screen
2.  Navigate away from the screen via the back button

### Basic Information

- Version with issue: 2.0.4
- Last known good version:
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - iOS:  15.5 
  - Android: API 30 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by bijington** [comment]
@FigmentCoder the reproduction file doesn't show us the bigger picture of the pages use in an application, are you able to provide more of a solution with the view model and navigation parts to ease the investigation please?

**Comment by FigmentCoder** [comment]
Thank you for checking out my issue :) Please see the attached files.  Also you'll see I'm using an IAsyncCommand, I've tried using the regular ICommand as well and have the same results.
[Files.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/9198475/Files.zip)

**Comment by FigmentCoder** [comment]
I have solved the issue or rather someone else did.
https://stackoverflow.com/questions/46221189/switch-toggled-event-fires-when-toggled-programmatically?rq=1
`
                            <services:CustomSwitch 
                                ToggledStateFromCode="{Binding IsEnabled, Mode=TwoWay}"
                                    Grid.Row="1"
                                    Grid.Column ="5">
                                <Switch.Behaviors>
                                    <behaviors:EventToCommandBehavior 
                                        EventName="UserToggled" 
                                        Command="{Binding Path=BindingContext.SaveReminderSelected, 
                                        Source={x:Reference Name=pageName}}" CommandParameter="{Binding .}"/>
                                </Switch.Behaviors>
                            </services:CustomSwitch>
`

**Comment by bijington** [comment]
@FigmentCoder I am glad you managed to solve your issue and thank you for sharing the solution.
