### ISSUE TITLE
TouchEffect: Non-standard properties of TouchEffect causes Jetbrains Rider to show false errors

### ISSUE THREAD

**Issue by mlyrstad** [xamarin/XamarinCommunityToolkit#1897]
### Description

TouchEffect properties don't follow the traditional BindableProperty pattern, in that there are both attached _and_ instance properties for the bindable properties. In principle, this is fine. _However._ Jetbrains Rider claims properties like xct:TouchEffect.Command, PressedTranslationY, NativeAnimation etc. are missing a writable property, despite not actually being readonly - because although the attached properties have setters, the instance properties _do not_ - and thus it thinks the properties are read-only and shows errors.

### Steps to Reproduce

1. Use Jetbrains Rider as the IDE
2. Add a Style for a property
3. Set any of the TouchEffect attached properties

### Expected Behavior
No error.

### Actual Behavior
Rider shows error because it thinks the property is readonly.

### Proposed solution
Add setters to the instance properties. They're writable anyway, right?

### Basic Information

- Version with issue: 2.0.4
- IDE: Jetbrains Rider

### Reproduction imagery

![image](https://user-images.githubusercontent.com/46678036/185315255-8edf2df7-0d9c-4e42-9aa1-c56bbf9b1b1f.png)

**Comment by pictos** [comment]
@mlyrstad thanks for your report, this isn't on our end. I suggest you to file a bug report to the Rider team.

**Comment by mlyrstad** [comment]
Great. Means it will likely not be fixed at all, as *they* will likely
claim it's on *your end *they're following the logical specifications of
how binding properties work...

I just thought, it's such an easy fix for you guys, probably less so for
them.

**Comment by olekssmyk** [comment]
Does anybody find a solution? I faced the same issue in MAUI as well
