### ISSUE TITLE
[Bug] The initial value of property couldn't display correctly on xct:BadgeView  when using data binding.

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/XamarinCommunityToolkit#1900]
### Description

 The initial value of the binding property couldn't display correctly on `xct:BadgeView`  when using data binding. But after changing the value of the binding property, the UI could update correctly on  `xct:BadgeView`.

### Steps to Reproduce

1. create a  xamarin forms demo
2. copy the following code to this demo:
  
 ```
  public class MyViewModel: INotifyPropertyChanged 
    {
        public ICommand TestCommmand => new Command(TestMethod);

        private void TestMethod(object obj)
        {
            NotificationsNumber = 168;
        }

        private int _notificationsNumber = 0;

   
        public int NotificationsNumber
        {
            get => _notificationsNumber;
            set => SetProperty(ref _notificationsNumber, value);
        }

        public MyViewModel() {

            NotificationsNumber = 0;
        }

        bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
        {
            if (Object.Equals(storage, value))

                return false;

            storage = value;

            OnPropertyChanged(propertyName);

            return true;

        }

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }

```

  **MainPage.xaml**

```
  <?xml version="1.0" encoding="utf-8" ?> 
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit" xmlns:formapp826="clr-namespace:FormApp826"
             x:Class="FormApp826.MainPage">

    <ContentPage.BindingContext>
        <formapp826:MyViewModel></formapp826:MyViewModel>
    </ContentPage.BindingContext>

    <StackLayout Padding="10">
        <Label  Text="{Binding NotificationsNumber}" HorizontalOptions="Center" FontSize="Header"   />

        <xct:BadgeView
            
            Margin="10"
            BackgroundColor="Red"
            FontAttributes="Bold"
            FontSize="Medium"
            TextColor="White"
            Text="{Binding NotificationsNumber}">
            <Label
                Text="This label has a badge in the top-right"/>
        </xct:BadgeView>


        <Button  Text="change value" Command="{Binding TestCommmand}"  />

    </StackLayout>

</ContentPage>
```

3.  deploy the app to a android device, the result is as follows:
   
     
![image](https://user-images.githubusercontent.com/42464252/186850709-16063846-f27e-4269-a6fd-db2da35fdb0d.png)

  We could find that the first Label could   display `NotificationsNumber` correctly(`0`) ,but for the   `xct:BadgeView`  ,the value of `NotificationsNumber`  can not display correctly.

After that, we can try to click button `change value`,  here  we change  the value  of  `NotificationsNumber`, we can find that the value of `NotificationsNumber` could update correctly for both `label` and  `xct:BadgeView` .

![image](https://user-images.githubusercontent.com/42464252/186851874-d6c55d41-e2d4-493e-9ff5-ee5883e58624.png)

### Expected Behavior

The initial value of property could display correctly on xct:BadgeView  when using data binding.

### Actual Behavior

The initial value of property couldn't display correctly on xct:BadgeView  when using data binding.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by FedericoNembrini** [comment]
Have you tried with the property "AutoHide"?

As per documentation "Gets or sets if the badge should be hidden automatically when the value is "0". This is a bindable property."

If it doesn't work with that property it is probably due to a bug. I have a similar problem.

**Comment by Martin-4Spaces** [comment]
I am experiencing the exact same thing.
Making BadgeView useless. :/

**Comment by FedericoNembrini** [comment]
I have implemented my own version based on the xamarin community badge view toolkit to solve this type of bug. I will post the code when I have time.
