### ISSUE TITLE
[Spec]

### ISSUE THREAD

**Issue by Sacrifaiz** [xamarin/XamarinCommunityToolkit#192]
# [The feature] 

Provide a concise description of the feature and the motivation for adding it to Xamarin.CommunityToolkit

# API

### Properties

| API | Description |
| ------------- | ------------- |
| [name] | Gets or sets [description]. |

### Events

| API | Description |
| ------------- | ------------- |
| [name] | [API documentation/description] |
 
# Scenarios

# Platform Compatibility
- Target Frameworks: 
  - iOS:  
# Backward Compatibility

# Difficulty : [low/medium/high]

**Comment by jfversluis** [comment]
@Sacrifaiz Closing this one since it doesn't seem to describe anything? Please open a new one with detailed information what you want to see in a new feature. Thanks!
