### ISSUE TITLE
[Enhancement] Navigation from/with ViewModel

### ISSUE THREAD

**Issue by AbuMandour** [xamarin/XamarinCommunityToolkit#194]
## Summary

from while I saw a suggestion about navigation with ViewModel From Xamarin Team "for sorry I don't remember where I saw it", but I told to myself why not?!

most of Xamarin Developer use Mvvm framework(Like prism, cross, etc) or create there own(like me) for navigation flow and some helper class, I can see XamainCommunityToolKit that will offer some amazing features but I will still need to use another framework or nuget to handle IOC container and Navigation so why don't add navigation from ViewModel and make it super Toolkit 

## API Changes
The following is some thoughts about the shape of this Service which will depend on IModal, INavigationService and BaseViewModel, for sure we can create totally new API from this as I didn't implement any of this

* IModal: it will be the base container of pages, Basic Content Page, Navigation Page or TabbbedPage ..etc, and will use to navigate from and to it.

*INavigationService: will be an interface for all navigation flows

*BaseViewModel: will hold some basic property and method we need in ViewModel and will be base class for Navigation Service 

```
    public interface IModal
    {
        object NavigationParameter { get; set; }
        string Name { get; set; }
    }
```

```    
public class BasicModal : IModal
    {
        public BaseViewModel ViewModel { get; set; }
        public object NavigationParameter { get; set; }
        public string Name { get; set; }
    }
```

```    
public interface INavigationService
    {        
        Task SetMainModal(IModal modal);
        Task PopModelAsync(object parameter = null);
        Task PushModalAsync(IModal modal);
        Task PopPageFromNavigationModelAsync(object parameter = null);
        void RemovePageFromNavigationModalAsync<TViewModel>() where TViewModel : BaseViewModel;
        Task PushPageToNavigatetionModelAsync<TViewModel>(object parameter = null) where TViewModel : BaseViewModel;        
        Task<bool> ChangeDetail(IModal modal);
        bool SetMasterPresentation(bool isPresent);
        void ChangeCurrentTabbedModal<TBaseViewModel>() where TBaseViewModel : BaseViewModel;
    }
}
```

```
    public class BaseViewModel : NotifiedObject
    {
        protected readonly INavigationService NavigationService;

        private volatile bool _isInitialize;
        private bool _isBusy = true;
        private volatile bool _isAppeared;
        private bool _isRefreshing;
        public bool IsRefreshing
        {
            get => _isRefreshing;
            set { _isRefreshing = value; OnPropertyChanged(); }
        }
        protected BaseViewModel()
        {
            NavigationService = LocatorService.Instance.Resolve<INavigationService>();         
        }

        public bool IsBusy
        {
            get => _isBusy;
            set
            {
                    _isBusy = value;
                    OnPropertyChanged();
            }
        }
        protected internal virtual void CleanUp()
        {
            _isAppeared = false;
            _isInitialize = false;
        }
        protected virtual Task OnNavigateFrom(BaseViewModel viewmodel, object parameter)
        {
            return Task.CompletedTask;
        }
        protected virtual Task OnAppearing(object view)
        {
            return Task.CompletedTask;
        }
        protected internal virtual Task OnDisappearing(object view)
        {
            return Task.CompletedTask;
        }
        protected virtual Task InitializeAsync(object navigationData)
        {
            return Task.CompletedTask;
        }
        protected virtual Task InitializeVolatileAsync(object navigationData)
        {
            NavigationData = navigationData;
            return Task.CompletedTask;
        }
        internal async Task InternalInitialize(object navigationData)
        {
            await InitializeVolatileAsync(navigationData);
                
            if (_isInitialize)
                return;
            _isInitialize = true;
            await InitializeAsync(navigationData);
        }
        protected virtual Task OnAppeared()
        {
            return Task.CompletedTask;
        }
        internal Task InternalOnAppear(object view)
        {
            OnAppearing(view).SafeFireAndForget();
            if (_isOnAppeared)
                return Task.CompletedTask;
            _isOnAppeared = true;
            OnAppeared().SafeFireAndForget();
            return Task.CompletedTask;
        }
        protected internal virtual bool HandleBackButton()
        {
            return false;
        }
    }
```

## Intended Use Case
```
           var detailModal = new BasicModal()
            {
                ViewModel = LocatorService.Instance.Resolve<DetailViewModel>(),
                Parameter = "Hello am from home"
            };
            return NavigationService.PushModalAsync(detailModal);
```

**Comment by roubachof** [comment]
Thank you very much @AbuMandour for taking the time to put together this nice spec 👍 
Now, from my point of view, the `XamarinCommunityToolkit` should not become a mvvm framework but a simple toolkit with useful helpers and controls.
This is just my opinion though :)

**Comment by AbuMandour** [comment]
> Thank you very much @AbuMandour for taking the time to put together this nice spec 👍
> Now, from my point of view, the `XamarinCommunityToolkit` should not become a mvvm framework but a simple toolkit with useful helpers and controls.
> This is just my opinion though :)

Thanks for your reply and time.
Does your talk make sense? sure, but what I mean what if we have navigation flow here, I can tell you I will create an amazing app with only Xamarin Forms and XamarinToolkit, for sure sometime I will need more complex functions and flow so I will move to use Mvvm Framework.
in another way, it's simple if you just learned Xamarin and want to create simple app "basic News app for example", it will be simple Just use Xamarin.Forms Xamarin.Essential, Xamarin.Toolkit

**Comment by jfversluis** [comment]
Thank you for the very extensive description and the idea @AbuMandour!

I think I have to agree with @roubachof though. I feel like there is enough MVVM frameworks out there that are both very simple and just provide enough or are much more extensive and offer you a lot of things.

The "danger" of us implementing another MVVM framework is that, while it starts simple, another person will want to add this, and then that and then x and then y, etc. and before we know it we have built another big MVVM framework. I think the aim for this library is to provide mainly:

* Code that is repeated by a lot of Xamarin.Forms developers, like common behaviors, effects, converters, etc.
* Controls/Views/Layouts that will not be able to go into Forms directly and prove their worth in this Toolkit first

Again, thank you for your suggestion and I hope you won't be discouraged by us turning down your first idea. I love your enthusiasm and I hope you can see our point of view on this and keep honoring us with your great ideas and maybe some contributions!
