### ISSUE TITLE
[Bug]  Cannot resolve type "schemas....toolkit:foo" in Maui Class Library

### ISSUE THREAD

**Issue by Marioo1357** [xamarin/XamarinCommunityToolkit#1944]
### Description

When I try to reference to something in toolkit from Maui Class Library project, the compiler throw me an error.
Works fine when I do it in startup project (this one with MauiProgram.cs).

### Stack Trace

  FooPage.xaml(13, 14): [XFC0000] Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:ByteArrayToImageSourceConverter".

### Steps to Reproduce

1. Create Maui project
2. Add .UseCommunityToolkit() to your builder chain in MauiProgram class
3. Create Maui class library
4. Project from step 1 should reference to project from step 3
5. In Maui Class Library create a page with any toolkit control or converter

### Expected Behavior

Compile and works fine

### Actual Behavior

throw   CropImagePage.xaml(13, 14): [XFC0000] Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:ByteArrayToImageSourceConverter".
during compile

### Basic Information

- Version with issue: 4.0.0
- Last known good version: -
- IDE: Rider, macos
- Platform Target Frameworks: 7.0.0
  - iOS:  any
  - Android: any
  - Windows:  -
- Android Support Library Version: any
- Nuget Packages: CommunityToolkit.Maui
- Affected Devices:
- MAUI Version: newest with .net 7.0.0

**Comment by thor3** [comment]
Got this error, too... 

Error	XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:MediaElementState".	

Any idea what to do?

**Comment by WebGoose** [comment]
I am having the same issue. 

I have an app with toolkit installed and working just fine. I also have a MAUI class library with controls that are reused by my other apps. 

If I try use toolkit in the class library I get the same error as OP, even if I add the nuget to the class library as well as in my app.

**Comment by Raystorm7** [comment]
> Adding a x:Name to the control in the xaml fixes this problem for me

I have the same issue but this fix doesn't help me :(

this is my XAML component:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentView 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"    
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Name="pippo"
    x:Class="LibMobile.VolosSearchBar">

    <ContentView.Content>
        <SearchBar
            x:Name="pluto"
            CancelButtonColor="{StaticResource Arancione}"
            BackgroundColor="Transparent"
            Placeholder="{Binding SearchText}"
            Text="{Binding FilterText}">
            <SearchBar.Behaviors>
                <toolkit:EventToCommandBehavior
                    EventName="TextChanged"
                    Command="{Binding InternalTextChangedCommand}" />
            </SearchBar.Behaviors>
        </SearchBar>
    </ContentView.Content>
</ContentView>
```

**Comment by bijington** [comment]
Try adding the `x:Name` tag to the `EventToCommandBehavior`

**Comment by kamyaw010** [comment]
Same issue, not working with x:Name in any places, works fine in my workplace PC but not my own PC, even don't know what's the problem, and code auto completion works fine but happens when building

**Comment by nick5454** [comment]
> Same issue, not working with x:Name in any places, works fine in my workplace PC but not my own PC, even don't know what's the problem, and code auto completion works fine but happens when building

Put x:Name on the ContentPage also
