### ISSUE TITLE
[Bug] Two-way Binding a property using TextCaseConverter throws a NotImplementedException

### ISSUE THREAD

**Issue by nord-** [xamarin/XamarinCommunityToolkit#1955]
### Description
Binding a property using TextCaseConverter will throw a `NotImplementedException` if the property is updated in viewmodel.

### Steps to Reproduce

Create an `<Entry Text="{Binding AnyString, Converter={StaticResource TextCaseConverter}}" />` and set the property `AnyString` to a value in the constructor.
This will cause the `ConvertBack`-function to be called and it throws a `NotImplementedException`.

### Expected Behavior
Returns the string as provided.

### Actual Behavior
Throws a `NotImplementedException`.

**Comment by bijington** [comment]
I don't understand the use case for wanting to have a two way binding which won't convert backwards. Why are you using it this way?

**Comment by pictos** [comment]
@nord- can you provide a small and simple project that reproduces this issue?
Then we can debug and see if we can fix it in another way. Not throwing the exception is a breaking change and this lib is in code freeze mode, so we would like to avoid changing any existing behavior.

**Comment by nord-** [comment]
Yes. You can find a project reproducing the error [here](https://github.com/nord-/XCT-TextCaseConverter).
![image](https://user-images.githubusercontent.com/3777600/225724594-4cfc429c-e815-4d77-b845-7e4c6c345bab.png)

**Comment by VladislavAntonyuk** [comment]
It's a one-way converter, so two-way conversion is not supported

**Comment by IeuanWalker** [comment]
@nord- you can use the `TextTransform="Uppercase"` property of the entry.

Think this converter is meant more for labels

**Comment by nord-** [comment]
> @nord- you can use the `TextTransform="Uppercase"` property of the entry.

Wow! I didn't even know there was a `TextTransform` property on entry! Yes, that's exactly what I want to achieve, and much easier than using a converter… Thanks!
