### ISSUE TITLE
[Spec]  Implied Order Grid

### ISSUE THREAD

**Issue by bmacombe** [xamarin/XamarinCommunityToolkit#196]
# Implied Order Cell Behavior

Behavior that auto sets row and column assignments of child views by the order they are defined in the grid.  RowSpan and ColumnSpan are honored during the auto-assignment of row and column.

By default, if more cells in the grid are needed by the number of child views then are defined an output warning will be generated.  If a row or column span exceeds the defined rows and columns output warnings will be generated.

The user may at their choice decide to have output warnings treated as exceptions.

If the user manually assigns a row or column on a view, it will be honored.  

# API

### Properties

| API                  | Description                                                  |
| -------------------- | ------------------------------------------------------------ |
| ThrowOnLayoutWarning | If any warnings generated should be logged or thrown as exceptions when true.  Defaults to false. |

All other behaviors of Grid is retained

# Scenarios

Allows a user to omit the Grid.Row and Grid.Column attributes and rely on the order child views are defined in XAML or added in code determine what grid cell they are assigned to.

# Platform Compatibility

- Target Frameworks: 
  - iOS:  
  - Android: 
  - UWP: 

# Backward Compatibility

# Difficulty : [low]

Prototype

https://github.com/bmacombe/AutoLayoutGrid

XAML Def
```xaml
<Grid x:Name="TestGrid" Margin="30" BackgroundColor="Gray">
    <Grid.Behaviors>
	<autoLayoutGrid:ImpliedOrderGridBehavior />
    </Grid.Behaviors>

    <Grid .RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="*" />
        <RowDefinition Height="*" />
        <RowDefinition Height="*" />
    </Grid .RowDefinitions>

    <Grid .ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid .ColumnDefinitions>

    <!-- Row 0 -->
    <autoLayoutGrid:TestLabel Grid .RowSpan="2"/>
    <autoLayoutGrid:TestLabel />
    <autoLayoutGrid:TestLabel />
    <autoLayoutGrid:TestLabel Grid .ColumnSpan="2"/>

    <!-- Row 1 -->
    <autoLayoutGrid:TestLabel/>
    <autoLayoutGrid:TestLabel />
    <autoLayoutGrid:TestLabel Grid .ColumnSpan="2"
                              Grid .RowSpan="2" />

    <!-- Row 2 -->
    <autoLayoutGrid:TestLabel />
    <autoLayoutGrid:TestLabel />
    <autoLayoutGrid:TestLabel />

    <!-- Row 3 -->
    <autoLayoutGrid:TestLabel />

</Grid >
```

Layout Generated
![image](https://user-images.githubusercontent.com/15127788/89721360-4859de80-d9a2-11ea-806b-e1fbeb6f9edc.png)

**Comment by dotMorten** [comment]
Looks good but I don't think you should reuse Grid.Row/ColumnSpan. The pattern is that attached properties should be defined on the clases that uses them, so I'd define row span/ColumnSpan on this class.

Also what happens if you use rowspan?

**Comment by bmacombe** [comment]
@dotMorten  Sure, at least with the prototype it's just a subclass of Grid though, the base grid will still pay attention to the Grid attached properties which could be confusing.

I've given a little thought to how I might be able to not inherit directly from grid which I'll explore after the API is finalized.  But if it stays inherited from Grid would you just do an output warning or exception and ignore if a Grid attached property was assigned?

Another thought I had was to see if this could just be implemented as a behavior that you just attach to a grid.

**Comment by dotMorten** [comment]
Aaah yes it definitely shouldn't inherit from Grid directly.
You don't warn on ignored attached properties. That seems wrong. They are attached properties for something elsez and since you're not using grid, autogrid shouldn't care

**Comment by bmacombe** [comment]
@dotMorten I updated the prototype to not inherit from Grid and just use one internally (I haven't found a good way to reuse the XF grid logic without using one or inheriting from it)  Mind giving it a quick look for some feedback?  It still needs some work of course and to expose more of the other properties for a Grid, but it has its own row and column span attached properties.

https://github.com/bmacombe/AutoLayoutGrid/blob/master/AutoLayoutGrid/AutoLayoutGrid/AutoLayoutGrid/AutoGrid2.cs

**Comment by bmacombe** [comment]
I also prototyped a behavior instead of a new class.  The only issue here is how to handle the user assigning a Row or Column.

1) They could be ignored, probably not the best action
2) They could be honored and placed exactly where the user-specified.

My first thought is to do 2 and then there are a couple of ways to handle a conflict

a) If a view has already been assigned the same location, just stack them like what would happen if you manually assigned two views to the same cell.  If the cell hasn't been used already, it will just be marked as used and views added afterward will just be flowed around it.

b) Recalculate the entire layout giving preference to the manually defined row/column.

c) Throw an exception

```xaml
<Grid x:Name="TestGrid" Margin="30" BackgroundColor="Gray">
			<Grid.Behaviors>
				<autoLayoutGrid:AutoGridLayoutBehavior/>
			</Grid.Behaviors>
			<Grid.RowDefinitions>
				<RowDefinition Height="*"></RowDefinition>
				<RowDefinition Height="*"></RowDefinition>
				<RowDefinition Height="*"></RowDefinition>
				<RowDefinition Height="*"></RowDefinition>
			</Grid.RowDefinitions>
			<Grid.ColumnDefinitions>
				<ColumnDefinition Width="*"></ColumnDefinition>
				<ColumnDefinition Width="*"></ColumnDefinition>
				<ColumnDefinition Width="*"></ColumnDefinition>
				<ColumnDefinition Width="*"></ColumnDefinition>
			</Grid.ColumnDefinitions>

			<autoLayoutGrid:TestLabel Grid.RowSpan="2"/>
			<autoLayoutGrid:TestLabel />
			<autoLayoutGrid:TestLabel />

			<autoLayoutGrid:TestLabel Grid.ColumnSpan="2"/>
			<autoLayoutGrid:TestLabel/>

			<autoLayoutGrid:TestLabel />
			<autoLayoutGrid:TestLabel Grid.ColumnSpan="2" Grid.RowSpan="2" />
			<autoLayoutGrid:TestLabel />

			<autoLayoutGrid:TestLabel />
			<autoLayoutGrid:TestLabel />
			<autoLayoutGrid:TestLabel />

		</Grid>
```

**Comment by roubachof** [comment]
This is really a **great** idea. I use so much grid everyday to avoid nesting.
I prefer the Behaviors approach which is less intrusive.
I think we definitely don't want to throw an exception since there are some common scenario where you have a 2 columns grid, and the first one is just used for an Image. So a lot of the children will have Grid.Column="1" set.

**Comment by bmacombe** [comment]
@roubachof If we go with the behavior route I'm leaning towards 2, A from above.

Existing Row/Column assignments be honored and placed exactly where the user-specified.  If a  view has already been assigned the same location, just stack them like what would happen if you manually assigned two views to the same cell. If the cell hasn't been used already, it will just be marked as used and views added afterward will just be flowed around it.

Then maybe log with a warning that you stacked to items.  If someone wants to know for sure they stacked views they could use the "ThrowOnLayoutWarning" to have it throw on that warning instead of just logging.

**Comment by roubachof** [comment]
Well I think it's also a desirable feature to be able to stack item, so i'm fine with that strategy.
I am not even sure it should raise a warning.

**Comment by bmacombe** [comment]
The warning would just be to the output log, like a binding failure.  My thought there is with the mix of the auto-assignment of cells based on the order defined clashes with a user assigned Row/Column or span, someone could be confused with the layout they get and it would just provide some context of why.

**Comment by sthewissen** [comment]
Just fwiw, I'd also be partial to the behavioral approach as that makes opting in and out a bit less obtrusive.

**Comment by bmacombe** [comment]
After making prototypes of a subclass of Grid, a custom control that uses a grid internally and the behavior.  I'm leaning towards the behavior being the right approach.

**Comment by bmacombe** [comment]
Could always make a control also, that just used the behavior if there is any value or enhanced discoverability with a control.

**Comment by bmacombe** [comment]
@jfversluis @sthewissen @AndreiMisiukevich I've updated this issue to be the behavior version.  Please review and approve if it looks good.  Then I'll clean up my prototype and work up a PR.

Thanks!

**Comment by roubachof** [comment]
I say yay!

**Comment by jfversluis** [comment]
Sorry it took a bit @bmacombe! I think it looks pretty good, so I would say go ahead.

@AndreiMisiukevich any comments about this?

**Comment by AndreiMisiukevich** [comment]
Yeah, that's cool!) I approve this idea 👍

**Comment by jfversluis** [comment]
![](https://res.cloudinary.com/teepublic/image/private/s--pi4s-z5B--/t_Preview/b_rgb:262c3a,c_limit,f_jpg,h_630,q_90,w_630/v1517994312/production/designs/2345248_0.jpg)

Go for it!

**Comment by bmacombe** [comment]
Great, I pretty much have it done except for the really fun part...tests!!
