### ISSUE TITLE
[Bug] TabViewItem Font does not load on iOS

### ISSUE THREAD

**Issue by Hufeisen2** [xamarin/XamarinCommunityToolkit#1978]
### Description

I use a font that I added to the project to display icons in TabView. On Android it works without problems, but on iOS the font does not load. In other parts where I use a normal label it works. I looked at the source code of the TabView and noticed that Android uses the MaterialTabViewItemTemplate and Apple uses the CupertinoTabViewItemTemplate. When comparing I noticed that the line `text.SetBinding(Label.FontFamilyProperty, "CurrentFontFamily");` is missing in the CupertinoTabViewItemTemplate. I think this is the cause of the error, but I am not sure if this was done on purpose. I am also fairly new to C# application development and think that there are more competent people who can look at this bug and fix it if possible.

### Steps to Reproduce

1. Create a TabView
2. Set a Font
3. Start with iOS

### Expected Behavior

The font is used

### Actual Behavior

The default font is used

### Basic Information

- Version with issue: 2.0.6
- IDE: Visual Studio
- Platform Target Frameworks:
  - iOS:  14.4
  - Android: 33

### Reproduction imagery

iOS:
![Bildschirm­foto 2023-07-12 um 18 52 00](https://github.com/xamarin/XamarinCommunityToolkit/assets/56114313/b4f270a5-47c6-43bb-a88a-31d906fe44a0)

Android:
![Bildschirm­foto 2023-07-12 um 18 54 01](https://github.com/xamarin/XamarinCommunityToolkit/assets/56114313/40e2e828-4f88-4e53-8d18-21005389470b)

**Comment by FedericoNembrini** [comment]
I confirm the issue, and the same thing happens in UWP. I'm going to open a pull request to fix the issue.
