### ISSUE TITLE
[Enhancement] TouchEffect

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#200]
## Summary

Import https://github.com/AndreiMisiukevich/TouchEffect

Hey folks (especially @Char0394) do you think I should import this one into the ToolKit as well?

## Intended Use Case
Responsive touches

**Comment by AndreiMisiukevich** [comment]
@sthewissen @jfversluis

**Comment by sthewissen** [comment]
I think this shouldn't be a problem to add.

**Comment by jfversluis** [comment]
This would just be extending the thing from Charlin right? So a couple of extra effects for that?

Yeah, I don't think that would be a problem :)

**Comment by AndreiMisiukevich** [comment]
> This would just be extending the thing from Charlin right? So a couple of extra effects for that?
> 
> Yeah, I don't think that would be a problem :)

No, I think it will be another one. This effect brings "Pressed" state, not just tap

**Comment by jfversluis** [comment]
Ah ok! This is more like a control while Charlins' was a behavior that just applies an animation to a view?

What would this add over the AnimationBehavior? Why should someone use one or the other?
(Note that I'm not saying we should not do it, just trying to determine what the difference is and have clear what both of these do :))

**Comment by AndreiMisiukevich** [comment]
> Ah ok! This is more like a control while Charlins' was a behavior that just applies an animation to a view?
> 
> What would this add over the AnimationBehavior? Why should someone use one or the other?
> (Note that I'm not saying we should not do it, just trying to determine what the difference is and have clear what both of these do :))

This is an Effect that can be attached to any view. It will add "pressed" "released" state handling (Like button). This effect fire Comand (so no need to use tapGestureRecognizer)

AnimationBehavior adds animation to some event (it can be any event) or it adds tapGestureRecognizer (so you cannot change view when control is pressed)

**Comment by HakanCelikMK1** [comment]
I wanted add my 2 cents here.

Existing animation behaviours are really useful. But, TouchEffect provides much more. 

For example, I used it to add Android's native ripple effect to a Frame. Now the frame responds like a button with a ripple effect. Therefore I have achieved a consistent visual feedback across the app.

I've already added it to my toolkit, and if it is part of this project, more people could discover and use it. 

An example :
```XML
          <Frame touch:TouchEff.Command="{Binding ShowProductPage}"
                 touch:TouchEff.IsAvailable="True"
                 touch:TouchEff.NativeAnimation="True"
                 touch:TouchEff.NativeAnimationColor="#80FFFFFF"
                 touch:TouchEff.PressedBackgroundColor="{StaticResource CustomBlue}"
                 touch:TouchEff.RegularBackgroundColor="{StaticResource CustomBlue}"
                 touch:TouchEff.ShouldMakeChildrenInputTransparent="False"
                 CornerRadius="5"
                 HeightRequest="50"
                 Visual="Default"
                 WidthRequest="50">
            <StackLayout Orientation="Horizontal" Spacing="10">
              <ffimagesvg:SvgCachedImage Aspect="AspectFit"
                                         BackgroundColor="Transparent"
                                         HorizontalOptions="Start"
                                         Source="resource://022-oil-gauge.svg"
                                         WidthRequest="50" />
            </StackLayout>
          </Frame>
```

**Comment by jfversluis** [comment]
OK! Got it, yeah sounds good :)
