### ISSUE TITLE
"Bug: Application crashes when pressing tab+spacebar while video is playing using CommunityToolkit.Maui.MediaElement on Windows platform"

### ISSUE THREAD

**Issue by SanthoshAthili3101** [xamarin/XamarinCommunityToolkit#2007]
While testing our .NET MAUI application on the Windows platform, we encountered a critical issue related to the CommunityToolkit.Maui.MediaElement package. When a video is playing using the MediaElement control provided by this package, the application crashes if the user presses the "Tab" key along with the "Spacebar" key simultaneously.

Steps to Reproduce:

1. Launch the .NET MAUI application on a Windows platform.
2. Navigate to the screen where a video is displayed using the MediaElement control.
3. Start playing the video.
4. While the video is playing, press the "Tab" key and the "Spacebar" key simultaneously.

Expected Result:

The application should handle the key press combination without crashing, and the video playback should continue uninterrupted.

Actual Result:

The application crashes immediately upon pressing the "Tab" key and the "Spacebar" key simultaneously while the video is playing. The crash occurs consistently, and no error message or exception is displayed to the user.

Additional Information:

.NET MAUI Version: 7
CommunityToolkit.Maui.MediaElement Version: 2.0.0
Windows

**Comment by bijington** [comment]
If you are seeing an issue with the .NET MAUI Community Toolkit then you want this repository instead: https://github.com/CommunityToolkit/Maui

Can you please open an issue there?
