### ISSUE TITLE
[Enhancement] RequiredStringValidationBehavior

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#202]
##  Intended Use Case

When needed to input the string for some "danger" action e.g. delete repository on github, or just confirm your password.

**Comment by jfversluis** [comment]
We can use one of the PRs that are open for this? If we make them a bit more generic.

**Comment by AndreiMisiukevich** [comment]
> We can use one of the PRs that are open for this? If we make them a bit more generic.

Yes, exactly
