### ISSUE TITLE
[Enhancement] CameraView

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#211]
## Summary

There has been a PR on the Xamarin.Forms repo for [CameraView](https://github.com/xamarin/Xamarin.Forms/pull/4084). Now that Forms will not see any major new versions for a while, they have asked if it can come stay with us for a little. I have always wanted to see this control, so I'm very happy to take it in.

In the longer run, it might be cool to hook into the raw data feed and let people hook up barcode scanning or computer vision stuff, but that's just a thing I'm daydreaming about. First, let's get this in. I've copied some things from the PR linked above into this issue so you know what it's about. This is all based on just taking the code as is for now from said PR.

||Android|iOS|UWP|
|---|:---:|:---:|:---:|
|Preview|✅|✅|✅|
|Preview Aspect|✅|🚫|🚫|
|Mirror preview|✅|🚫|🚫|
|Zoom|✅|✅|✅|
|Take photo|✅|✅|✅|
|Flash|✅|✅|✅|
|Take video|✅|✅|✅|
|Record audio|✅|✅|✅|
|Video stabilization|✅|✅|✅|

## API Changes

Added:
- CameraView class
- CameraOptions enum
- CameraCaptureOptions enum
- CameraFlashMode enum

### Required permissions ###

**Android**
`AndroidManifest.xml` should include the following lines inside `manifest` tag
```XML
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
```

**iOS**
`Info.plist` should include the following lines inside `dict` tag
```XML
	<key>NSCameraUsageDescription</key>
	<string>This app would like to access the camera</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app would like to access the microphone to record movies</string>
```

**UWP**
`Package.appxmanifest` should include the following lines inside `Capabilities`
```XML
	<DeviceCapability Name="webcam" />
	<DeviceCapability Name="microphone" />
```

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

This is a new control

### Before/After Screenshots ### 

**iPhone**
![img_0067](https://user-images.githubusercontent.com/27482193/46955864-96e70c00-d09c-11e8-9f13-9b22d6015e11.PNG)

**Android**
![android](https://user-images.githubusercontent.com/27482193/46996369-191b1300-d125-11e8-9ec7-32b01af7554f.png)

**Comment by jfversluis** [comment]
@bmacombe has expressed he wanted to look into this, and I was planning to do it as well, so we decided to combine powers and make it happen

**Comment by bijington** [comment]
Is this actively being worked on? I only ask as I have implemented something recently internally for iOS and Android at least because we need to be able to control the flash directly and at times prevent the user from choosing the flash mode. Happy to assist if required.

**Comment by bmacombe** [comment]
I believe @jfversluis is going to start on it during his live stream on twitch tomorrow.

**Comment by jfversluis** [comment]
@bijington that sounds interesting! Does it make sense to have us shape up the bits that are out there now and have you review that? I'd love your view on it and see where we can improve from there

**Comment by bijington** [comment]
@jfversluis yes that sounds good. That will let me see how I could have done a better job then ;).

I would be really quite keen to see it as I battled a lot with myself over how to split out the shared/platform specific parts.

**Comment by jfversluis** [comment]
OK I'm pretty far along with the iOS one

@bmacombe the UWP one and @pictos the Android one. Just need to see how we go about a potential breakup of packages.
