### ISSUE TITLE
[Enhancement] A project logo!

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#213]
We've decided on naming and things (#114), I would however like to have some kind of logo that we can use on NuGet and else where so we're a bit more identifiable. Anyone has any ideas on what that would look like?

**Comment by jfversluis** [comment]
Also see #142 where it can be applied

**Comment by sthewissen** [comment]
Just some concepts from my end
![image](https://user-images.githubusercontent.com/2419439/90765553-73212c80-e2ea-11ea-89fb-7fbcf2718527.png)

**Comment by Char0394** [comment]
I like #1 and #2, For some reason, #4 reminds me to Xamarin Essentials :P

**Comment by Beelzenef** [comment]
@sthewissen my vote for the third one, box with light colors and not-connected nodes 😄

**Comment by almirvuk** [comment]
I vote for:

Grid.Row="1"
Grid.Column="0"

**Comment by acaliaro** [comment]
2

**Comment by sthewissen** [comment]
@dansiegel The thought behind it was to be somewhat similar to what Essentials does (a Xamarin endorsed a separate package of tools) which is where the circles came from. While adding in some tools definitely sells the toolbox idea I wonder if it wouldn't become too generic.

Open to discuss all of this though, just whipped something up as a starting point here :)

**Comment by dansiegel** [comment]
@sthewissen totally get the inspiration there. IMO the Xamarin logo gives away the Xamarin endorsed toolset. It's not really necessary to look like the Essentials logo, and better to have it's own branding. But again that's just my opinion, take it for what you will.

**Comment by danieeis** [comment]
#2 I vote or Row 0 Column 1

**Comment by bijington** [comment]
Looking great! I vote for 2. I think that 1 and 3 imply the toolkit supports more than just Xamarin.

A concept I have just considered is a Swiss army style knife. I will see if I can knock something up but it probably won't beat your work @sthewissen.

**Comment by MSicc** [comment]
My vote goes straight to 2.

**Comment by exendahal** [comment]
For some reason, I felt 4th picture more informative. I go for 4.

**Comment by jfversluis** [comment]
> A concept I have just considered is a Swiss army style knife. I will see if I can knock something up but it probably won't beat your work @sthewissen.

I know he is happy to be beaten, please give it a shot @bijington !

**Comment by sthewissen** [comment]
Dropping an alternative in here more towards the toolbox idea.

![image](https://user-images.githubusercontent.com/2419439/90868159-b933ca00-e396-11ea-885c-208d6fbba1cc.png)

**Comment by roubachof** [comment]
It inspires craftsmanship with a more modern style. Like it!

**Comment by bijington** [comment]
I didn't appreciate how much effort this might take. I am also not convinced that it is any better than the options already suggested. Here is a general concept of my Swiss army knife but it is certainly not complete.

![Screenshot 2020-08-24 at 21 20 36](https://user-images.githubusercontent.com/17139988/91092408-e363e100-e64f-11ea-9a7a-b5a97fa8ebbf.png)

**Comment by kphillpotts** [comment]
I vote for Grid.Row = 1 - Grid.Column = 1

**Comment by jfversluis** [comment]
I'm closing the entry for new logo suggestion tomorrow (Friday) end of day and then find some way to create a poll and let the people decide!

**Comment by ricardoromaobr** [comment]
I like  the **#1**

**Comment by mhrastegary77** [comment]
#2

**Comment by roubachof** [comment]
If I don't win this it will mean that the whole thing is rigged.
![xct](https://user-images.githubusercontent.com/596903/91548045-15fa2c00-e925-11ea-9928-7f2a5b14b4a8.png)

**Comment by jfversluis** [comment]
Sorry @roubachof your entry was _just_ too late for the cutoff time :(

**Comment by roubachof** [comment]
I knew it. The vote is rigged!

**Comment by jfversluis** [comment]
![New Project (4)](https://user-images.githubusercontent.com/939291/91721286-ce7bd600-eb98-11ea-90ca-43c430c06f79.png)

OK everyone! I came up with a very intuitive way of voting! In the image above, each of the options has an Emoji attached. Place the Emoji of your choice on this **COMMENT** to cast your vote!

I can't stress enough that the 😕  option is not meant to be negative in any way. I just ran out of positive Emoji options that you can place on a GitHub comment.

Voting starts immediately, up until Thursday 20:30 CEST / 11:30 PT / 14:30 EDT / 18:30 UTC when _coincidentally_ I will be live streaming on Twitch and we will see what decision has been made. And why not then and there apply it to our NuGets and accounts and all the things?!

<details>
  <summary>Disclaimer</summary>
  We as the core team reserve the right to overrule the decision if we detect any kind of funny business 👀 
</details>

**Comment by egbakou** [comment]
I vote for:
Grid.Row = 1 
Grid.Column = 1

**Comment by shareefsystems** [comment]
> I vote for:
> Grid.Row = 1
> Grid.Column = 1

I agree with @egbakou. It shows the Xamagon rightly on the box. The circles symbolise the elements of the toolkit effectively.

**Comment by luismts** [comment]
Well, I think you need to look for a designer.

**Comment by awaescher** [comment]
My mind paints this as soon as I hear the words Xamarin + Toolkit.

![Unbenannt](https://user-images.githubusercontent.com/3630638/91765399-38b46b00-ebd9-11ea-8929-cae40b7d3e5e.png)

**Comment by luismts** [comment]
That's better, I was thinking about something similar. Thanks for saving me the effort xD

**Comment by egbakou** [comment]
> My mind paints this as soon as I hear the words Xamarin + Toolkit.
> 
> ![Unbenannt](https://user-images.githubusercontent.com/3630638/91765399-38b46b00-ebd9-11ea-8929-cae40b7d3e5e.png)

Ohhh that's better. I like it.

**Comment by jfversluis** [comment]
@awaescher thanks for the input! This puts me kind of in a tough spot.

I like it, but also the deadline for entries has past. In addition, I appreciate you crediting the original authors of the icon, but I don't think that's not something we can use when we use this under the Microsoft name. :(

**Comment by awaescher** [comment]
> ... but also the deadline for entries has past.

Oh, sorry, I must have missed this.

The logo was just to visualize the idea, I did not expect to have this finalized with credits from FreePik.

**Comment by jfversluis** [comment]
No worries! I certainly appreciate the input and as I said, I like the idea. But yeah, with the voting already started and all, its kind of hard to determine how to go about this now 😅

**Comment by jfversluis** [comment]
@awaescher are you able to create one from scratch without bits from another author? A lot of people also seem to like this idea. So maybe we should give it another round

**Comment by awaescher** [comment]
I could give it a try, I think it's possible. 
However, I'd love to donate a [month of the Flaticon premium subscription](https://www.flaticon.com/profile/preagreement/getstarted) to help the toolkit with the icon. What do you think?

![image](https://user-images.githubusercontent.com/3630638/91850321-a2765880-ec5d-11ea-9165-7144ea7b3243.png)

![image](https://user-images.githubusercontent.com/3630638/91850809-76a7a280-ec5e-11ea-9611-34b6fa2eae28.png)

**Comment by jfversluis** [comment]
@awaescher I wish it was that simple. It's not about the money, but about all kinds of legal things and approvals and long wait times and corporate things we don't want to know about probably ;) 

I really appreciate the gesture, thank you for that! But I'm afraid it won't be that simple

**Comment by awaescher** [comment]
Okay, I tried to do it by myself. It's not as smooth as the one from Freepik, but I'm not a designer anyway 😅

![XamarinCommunityToolkit](https://user-images.githubusercontent.com/3630638/92228710-9af6bf80-eea8-11ea-8490-8d5912a1b24e.png)

The download below contains this version as .png, .svg and .gvdesign (in case anyone likes to improve it with [Gravit Designer](https://www.designer.io/) which I used for this)

-  📦 [XamarinCommunityToolkit.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5174178/XamarinCommunityToolkit.zip)

I'd like to hand it over to the project team with each and every permission you might come up with. Use it, edit it, do whatever you want.

PS: Sometimes I think the tools might look a bit un-centered. However, the guides show that everything's correct. Might be the heavy wrench head vs. the thin screwdriver tip.

![image](https://user-images.githubusercontent.com/3630638/92228653-89adb300-eea8-11ea-9295-68cd8f2c468a.png)

**Comment by jfversluis** [comment]
Very awesome! Thank you @awaescher I really appreciate the effort :)

Would it make sense to take the winner of the vote I opened above and this one for a second round of voting and from that vote determine the winner? That way this icon will still get a fair chance I think :)

**Comment by awaescher** [comment]
Fine for me, I did not want to undermine the vote. I'm still a bit ashamed, tbh.

**Comment by jfversluis** [comment]
Don't be! Absolutely no reason to! I mean, it's a logo. While very nice to have, not at all the most important thing that is going to make or break this library. And I really appreciate your design, and I think so do others. Thats why I think it's worth at least considering it :) 

No worries at all!

**Comment by jfversluis** [comment]
OK! Round 2 (last round 😅 ) Just to be absolutely clear here 

# !!! New entries will not be accepted anymore !!!

The winner of the previous vote was this one by @sthewissen. Vote for this by using the 🚀  emoji **on this comment**

![90868159-b933ca00-e396-11ea-885c-208d6fbba1cc](https://user-images.githubusercontent.com/939291/92390382-09db4f00-f11b-11ea-807c-f08fe19d6be4.png)

But then came a new contestant from @awaescher which was very much liked. So let's see what people like best. Vote for this by using the ❤️  emoji **on this comment**

![92228710-9af6bf80-eea8-11ea-8490-8d5912a1b24e](https://user-images.githubusercontent.com/939291/92390445-26778700-f11b-11ea-8e6a-5b5751dd4451.png)

Voting starts immediately, up until Thursday 20:30 CEST / 11:30 PT / 14:30 EDT / 18:30 UTC when coincidentally I will be live streaming on Twitch and we will see what decision has been made. And why not then and there apply it to our NuGets and accounts and all the things?!

**Comment by roubachof** [comment]
wow, I just realized I made a mistake when voting and I guess many other people did the same mistake that me...
If you look quickly to the post, since the heart is right under @sthewissen logo, you tend to associate them.
So I clicked ❤️ thinking I was voting for steven's logo 🤦‍♂️ 

![source](https://user-images.githubusercontent.com/596903/95736945-3b4dba00-0c87-11eb-8ad8-3a06f6d2a48e.gif)
