### ISSUE TITLE
[Spec]  Expander

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#214]
## Summary
@samhouts proposed to shift Expander from Forms to Community Toolkit.

We should do it from this branch https://github.com/xamarin/Xamarin.Forms/pull/10498 (it has Direction property support)

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/expander

## Intended Use Case
The Xamarin.Forms Expander control provides an expandable container to host any content. The control has a header and content, and the content is shown or hidden by tapping the Expander header. When only the Expander header is shown, the Expander is collapsed. When the Expander content is visible the Expander is expanded.

**Comment by jfversluis** [comment]
Let's do it! And we even have Docs that we cam simply copy! @AlexHedley

**Comment by AlexHedley** [comment]
I'll keep an eye on this and when it's approved I can move the docs over :)

Would it also need removing from the Xamarin ones, how would that be handled? Do they get deprecated and a link to the new location as people might be using previous versions that would still have it available?
