### ISSUE TITLE
[Enhancement] Better contribution docs/content

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#215]
## Summary

As a result of #208, I would want to restructure the whole thing at some point. I think people won't read that whole thing tbh.

I think it might be nice to maybe work scenario-based. I.e.:

* I am a first-time contributor, what should I know?
* I have a great idea for a feature, what do I do?
* I've opened a PR, what can I expect?

Have that list on top so people can pick the thing that is closest to them and just read the bits that are relevant. Maybe because of the size just link those bits to the wiki instead of having it all in the `contributing.md`.

Anyone have ideas around that?

**Comment by bmacombe** [comment]
I think this a great idea.  At this point, I don't think I have enough experience with the project to flush those all out.  But I'd be glad to modify the document with whatever discussions and conclusions are made in this issue.

**Comment by jfversluis** [comment]
Starting something here: https://github.com/xamarin/XamarinCommunityToolkit/wiki/Contributing-to-XamarinCommunityToolkit

My idea would be that the entry point is the contributing.md which we should keep small and maybe list the same scenarios and link directly to them. Then in the wiki we can describe all these things.

Maybe putting it all on one page will still make for a big wall of text and we should split them up, but this would be my general idea.
