### ISSUE TITLE
[Bug] Resx strings missing for UriValidationDescription and UriValidationDescription causes build error when editing

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/XamarinCommunityToolkit#217]
### Description
AppResource.resx is missing resources `UriValidationDescription` and `UriValidationDescription` but the getters exists in the generated designer.cs. If you build the sample app, it will compile, but the text on the screen is blank. The next time you edit the resx file, the accessors in the generated code will be deleted which causes a build error.

This is a fairly easy fix, I'll send a PR shortly.

### Steps to Reproduce

1. Clone Main branch.
2. Run sample
3. Navigate to Behaviours
4. The last item "UriValidationBehavior" has no description on it
5. Click on the item 
6. Page displays no description text.
7. Add a new value to AppResource.resx
8. Try to build Sample
9. Build fails because the generated code for `UriValidationDescription` has been over written by code gen.

### Expected Behavior
UriValidationDescription should have description text.

I should be able to edit the resx without causing a build error unrelated to my code.
### Basic Information

- Version with issue: Main branch as of 2020-08-20
- Last known good version: unknown
- IDE: All
- Platform Target Frameworks:  ALL
  - iOS:   ALL
  - Android:  ALL
  - UWP:   ALL
- Android Support Library Version: n/a
- Nuget Packages: n/a
- Affected Devices: Tested on iOS simulator but will be the same everywhere

### Reproduction imagery

<img width="617" alt="Screen Shot 2020-08-20 at 3 27 55 pm" src="https://user-images.githubusercontent.com/29908924/90721978-46c2db80-e2fd-11ea-8301-990a10492ae5.png">

**Comment by jfversluis** [comment]
Noticed this too. Thanks for the quick fix @lachlanwgordon!

**Comment by jfversluis** [comment]
Fixed by #218
