### ISSUE TITLE
[Enhancement] UWP Sample

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/XamarinCommunityToolkit#220]
## Summary

This toolkit supports UWP but only has samples for iOS and Android. 

Can I add a project called `Xamarin.CommunityToolkit.Sample.UWP` and add it to the `XamarinCommunityToolkitTable.sln`?

Does anyone have opinions about whether I add the project to the existing sample solution, or add a separate Mac and Windows Solution? My preference is to keep it simple with just one .sln and VSMac users just work with the UWP unloaded.

## API Changes

None, sample code only.

## Intended Use Case
Provides an app for features to be tested on UWP, adds a sample for anyone wanting to run it on UWP.

**Comment by jfversluis** [comment]
Done! Boom! Thanks @lachlanwgordon
