### ISSUE TITLE
[Enhancement] UserStoppedTypingBehavior

### ISSUE THREAD

**Issue by jBijsterboschNL** [xamarin/XamarinCommunityToolkit#223]
## Summary

- After a certain threshold has been reached after the user has stopped typing, a given command can be executed
- Stopped Typing Threshold will be adjustable
- Auto Dismiss Keyboard will be adjustable when user has stopped typing

See this repository for an example: https://github.com/jBijsterboschNL/Xamarin.Forms-UserStoppedTypingBehavior

And this blog post about the implementation:
https://blog.johndotnet.nl/automatic-search-trigger-when-user-stopped-typing-in-xamarin-forms/

## Intended Use Case
If you want a command (f.e. a search command) to be automatically executed after the user has stopped typing, but you don't want it to be triggered on each text changed event (triggering too many and also obsolete search calls).

**Comment by jfversluis** [comment]
I am Gerald and I approve of this idea!

**Comment by sthewissen** [comment]
Sounds cool!

**Comment by jBijsterboschNL** [comment]
Great! :) will try to get this implemented into the Xamarin Community Toolkit in the next weeks.

**Comment by jBijsterboschNL** [comment]
PR has been merged, so this issue can be closed :) thanks all for your feedback

**Comment by AndreiMisiukevich** [comment]
Closed by #253
