### ISSUE TITLE
[Enhancement] Add different languages to the Sample project 

### ISSUE THREAD

**Issue by Char0394** [xamarin/XamarinCommunityToolkit#225]
## Summary

Now we have the multilingual support https://github.com/xamarin/XamarinCommunityToolkit/issues/165 we need to add the translations of each language. 
Here is the list of some language proposed:
- Spanish
- Arabic
- Bosnian
- Catalan
- Russian
- Portuguese
- French 

Based on https://github.com/xamarin/XamarinCommunityToolkit/issues/165.

**Comment by almirvuk** [comment]
I will add Bosnian :)

**Comment by Pujolsluis** [comment]
Will take on Spanish support

**Comment by LucioMSP** [comment]
> Will take on Spanish support :)

+1 / I too

**Comment by Rabosa616** [comment]
I will take Catalan

**Comment by DamienDoumer** [comment]
What about French ? 🤔 no one mentioned it...  I can take it.

**Comment by Char0394** [comment]
@DamienDoumer go for it! :)

**Comment by AbuMandour** [comment]
I will take Arabic for sure

**Comment by Char0394** [comment]
@AbuMandour go for it! :)

**Comment by sthewissen** [comment]
Ill happily do Dutch.

**Comment by kichloo** [comment]
@Char0394 How about Hindi? I can do that.

**Comment by jfversluis** [comment]
I would say it is @kichloo!

**Comment by jfversluis** [comment]
Let's hold off on the localization for the time being as we discuss this internally

**Comment by kichloo** [comment]
Is there any problem in the documentation of the Hindi language?

**Comment by jfversluis** [comment]
Absolutely not @kichloo sorry if I made you think that :)

The thing we are worried about is that with each update of the sample app we also need to update all the languages. Since one person is not able to do that, we have to rely on a number of people to keep the translations up-to-date.

It is very unlikely that the translations will be updated that often, so we were wondering if we should maybe not translate the whole app but just add a localization sample with a couple of examples and leave it at that :)

**Comment by kichloo** [comment]
@jfversluis No problem! But, I would definitely like to contribute in case this issue moves towards completion.

**Comment by almirvuk** [comment]
@jfversluis I agree and like that idea. In my opinion, the sample app does not need to be 100% localized. It is fine to have example how to do that and have a couple of different languages there. It will be easier for others to add some languages and for future maintenance. :)

**Comment by gokujax** [comment]
Don't forget the Flow Direction of the page/control after changing the culture which should be applied to active and inactive pages in case of Tabbed or Modal Page too.

**Comment by sthewissen** [comment]
Since the sample app will only demonstrate the concept of i18n on the sample page for it and we have a base set of languages in there to prove the concept; do we need to add more? To me, if the sample demonstrates the concept we shouldn't, meaning we could close this issue.

**Comment by jfversluis** [comment]
As mentioned earlier; translating all of the sample app is not really feasible as much as I'd love to. 

We now have the concept of the localization in there to show how that works, for now that's going to be it. Closing this one for now.
