### ISSUE TITLE
[Enhancement] Add an UnitTest to validate missing Resource file key 

### ISSUE THREAD

**Issue by Char0394** [xamarin/XamarinCommunityToolkit#226]
## Summary
Using the same concept of **GitTrends** https://github.com/brminnick/GitTrends/blob/main/GitTrends.UnitTests/Tests/Resx/ResxTests.cs 
We should add some tests to validate the key is added in all the languages when adding a new key to the Resource file.

**Comment by Pujolsluis** [comment]
Will be taking on this issue :)

**Comment by jfversluis** [comment]
Since #225 is out of scope we can close this one as well
