### ISSUE TITLE
[Enhancement] MFractor Gitignore

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/XamarinCommunityToolkit#228]
## Summary

The current .gitignore does not include MFractor files, which means I have to be careful not to commit them. The [GitHub git ignore template for Visual Studio](https://github.com/github/gitignore/blob/218a941be92679ce67d0484547e3e142b2f5f6f0/VisualStudio.gitignore#L346-L347) has it so i would base it one this. Can I add it please?

That template also has a lot of patterns that we're not ignoring, would we prefer to bring in all those patterns at once to prevent future updates, or just update those two lines, and add others as they come up? The downside of bringing them all in is that a longer gitignore does slow git down, but the GitHub template has been well written so the performance difference will probably be invisible. Slow downs tend to be caused by having lots of explicit rules like having another line for every `.dll` instead of a single line to ignore all `/bin`s.

## API Changes

None, house keeping only.

## Intended Use Case

Make git life a little easier for me, and anyone else using MFractor.

**Comment by jfversluis** [comment]
Go for it!
