### ISSUE TITLE
[Bug] Multilingual support not working on UWP, all Text in sample app is now blank.

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/XamarinCommunityToolkit#230]
### Description

Since pulling down the latest Main with the multilingual support, all text in the app that comes from the resx files is blank when running on UWP. Rolling back to previous commit the app has lots of text. When I look in `Items` in WelcomeViewModel.cs, all calls to `AppResources` return null, where they used to return a string.

Text is working fine on iOS and Android. I've only tested in English on all platforms.

### Steps to Reproduce

1. Clone latest Main on a windows 
2. Run on UWP on Local Device
3. Almost all of the text in the app is blank

### Expected Behavior
App has lots of text in it that is loaded from resx file.
### Actual Behavior
App has no text in it.
### Basic Information

- Version with issue:
- Last known good version: Commit 21bfb02
- IDE: Visual Studio Windows 2019
- Platform Target Frameworks: 
  - UWP:  16299
- Affected Devices: Tested on Windows 10 1903

### Reproduction imagery

![Screen Shot 2020-08-25 at 10 57 51 am](https://user-images.githubusercontent.com/29908924/91110674-e13a6a80-e6c1-11ea-8ed3-0184a4e33572.png)
All Labels are blank.

![Screen Shot 2020-08-25 at 10 34 13 am](https://user-images.githubusercontent.com/29908924/91110690-ef888680-e6c1-11ea-8815-8122b306ab0b.png)
All Labels used to have text.

![Screen Shot 2020-08-25 at 10 59 38 am](https://user-images.githubusercontent.com/29908924/91110742-1777ea00-e6c2-11ea-8e51-43cd23e9e0b7.png)
AppResources returns null

![Screen Shot 2020-08-25 at 10 33 48 am](https://user-images.githubusercontent.com/29908924/91112318-23fe4180-e6c6-11ea-8ae4-1e6da5191613.png)
AppResources used to return strings.

**Comment by lachlanwgordon** [comment]
I dug into this a little, if I go into the settings page and change the language to English or Spanish it works but until then it's blank. 

On launch my culture is "en-AU" but this app only supports "en" and "es". It looks like our LocalizationResourceManager matches the culture strings exactly, but we should do some fuzzy matching so that "en-AU" or "en-US" fallback to "en" if not available.

I think UWP handles this by default https://stackoverflow.com/questions/32084612/en-vs-en-us-as-default-language-for-windows-10-uwp-distributed-worldwide, but we're doing it differently, in a cross platform way.

I think this is the list of all possible culture-strings in Windows and I think iOS and Android probably work the same. https://docs.microsoft.com/en-us/windows/win32/wmformat/language-strings.

**Comment by lachlanwgordon** [comment]
I tried fixing this with something like 

```
var match = resourceManager.GetString(text, CurrentCulture);
if (match == null)
    match = resourceManager.GetString(text, CurrentCulture.Parent);
```

But it's still getting nulls.

I also tried a hacky fix to debug
```
LocalizationResourceManager.Current.SetCulture(CultureInfo.GetCultureInfo("en"));
```

But that's no good either.

@Char0394 do you have any thoughts on this?

**Comment by Char0394** [comment]
mmm, @lachlanwgordon  can you try this https://stackoverflow.com/questions/48309297/resourcemanager-returning-null-for-default-culture/50651824 ?

**Comment by lachlanwgordon** [comment]
Thanks @Char0394, the Assembly Info fix in the .Net Standard sample did it.
