### ISSUE TITLE
[Bug] Toolbar items are white text on white background on Android sample

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/XamarinCommunityToolkit#231]
### Description

The settings and About buttons in the Tool Bar are white and the background color is a slightly different white. This makes it tricky to see the wonderful list of contributors.

I think this is probably fixed in the android resource xml styles.

See screenshot below.

### Steps to Reproduce

1. Run sample on Android
2. Look very closely at the top right of the screen, it says "Settings" and "About", but they're hard to see

### Expected Behavior
Text should be black.
### Actual Behavior
Text is white
### Basic Information

- Version with issue: Current Main
- Last known good version: Probably never?
- IDE: VS Windows 2019
- Platform Target Frameworks: 

  - Android: 9, 10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: PIxel 3a, Samsung T510

### Workaround
Squint and move phone really close to face

### Reproduction imagery
![118334308_808375806648277_8864197331111778347_n](https://user-images.githubusercontent.com/29908924/91114809-1cda3200-e6cc-11ea-8d25-949d99345c32.png)

**Comment by jfversluis** [comment]
I bet it's that @sthewissen guy again only testing on iOS...

**Comment by AndreiMisiukevich** [comment]
> I bet its that @sthewissen guy again only testing on iOS...

iOS rules the World. We cannot blame him xD

**Comment by lachlanwgordon** [comment]
Perhaps this is not a bug, but a difference of design oppinion. Steven knows more about design than me so I'll trust him and 
close the issue.
