### ISSUE TITLE
[Enhancement] Add DateTimeOffset Converter

### ISSUE THREAD

**Issue by mallibone** [xamarin/XamarinCommunityToolkit#234]
## Summary

Add a converter for converting from DateTimeOffset to DateTime and back.

## API Changes

Adds a new Converter To the converters.

## Intended Use Case
Often times DateTime is stored with the offset on the backend to allow for storing the timezone in which a DateTime originated from. Controls like the DatePicker in Xamarin.Forms will only work with DateTime. To be able to easily hook up ViewModels/Models containing a DateTimeOffset property this converter would come in handy.

**Comment by mallibone** [comment]
I would also be happy to provide the implementation of the DateTimeOffsetConverter 🙂

**Comment by Depechie** [comment]
Love it! A go from me :)

**Comment by jfversluis** [comment]
It’s a yes for me


![](https://media.tenor.com/images/de1b40295e1d462d1f6bc726b74dba2a/tenor.gif)

**Comment by AndreiMisiukevich** [comment]
Looking forward 👍

**Comment by lachlanwgordon** [comment]
But if @mallibone implements it, @jfversluis can't be mean to him on the Null Pointers podcast any more. That's my favourite bit of the show.

**Comment by jfversluis** [comment]
> But if @mallibone implements it, @jfversluis can't be mean to him on the Null Pointers podcast any more. That's my favourite bit of the show.

I know, right?! Now I have to do a poll to find out what else I can hold against him...
