### ISSUE TITLE
How to use behaviors?

### ISSUE THREAD

**Issue by mohammedmsadiq** [xamarin/XamarinCommunityToolkit#236]
Not able to get behaviours from nuget package

1. Added =  "Xamarin.Toolkit.Effects" to all projects 
2. Added =   xmlns:b="clr-namespace:Xamarin.Toolkit.Effects;assembly=Xamarin.Toolkit.Effects"
3. 
`<Entry
           Margin="0,10"
           Placeholder="UserName"
           Visual="Material"
           Text="{Binding Username, Mode=TwoWay}">
           <Entry.Behaviors>
                      <b:EmailValidationBehavior/>
           </Entry.Behaviors>
</Entry>` 

Error: The type 'b:EmailValidationBehavior' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.

- Version with issue: 1.0.0
- Last known good version: N/A
- IDE: VS for mac

**Comment by AndreiMisiukevich** [comment]
Hi @mohammedmsadiq 
```Xamarin.Toolkit.Effects``` is not related to this project.

Official nuget package that contains  all behaviors/converters/views currently is in **pre**-release state.

Please go through the [installation guide](https://github.com/xamarin/XamarinCommunityToolkit#installation) and install the proper nuget package.

CC @jfversluis

**Comment by jfversluis** [comment]
Thanks for your question @mohammedmsadiq !

As Andrei already pointed out, it seems you have found an older version of this project on NuGet :) I am looking to see if I can find someone to unlist those to minimize confusion with those. The right package should be the `Xamarin.CommunityToolkit`, as seen here: https://www.nuget.org/packages/Xamarin.CommunityToolkit

We have just a pre-release right now, so for it to show up in your IDE you have to check the "show pre-releases" checkbox. Closing this one for now, if you still have trouble using it after this, please feel free to open a new issue.

Thanks!
