### ISSUE TITLE
[Enhancement] ArithmeticConverter

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#237]
## Summary

Allow performing arithmetic operations in XAML.

https://github.com/Apress/pro-wpf-4.5-in-csharp/blob/master/Pro%20WPF%204.5%20in%20C%23/Chapter15/Animation/ArithmeticConverter.cs

**Comment by jfversluis** [comment]
I like the idea, I'm kind of worried about the license on this code you linked though. I don't think we can simply take this and use it as our own.

**Comment by AndreiMisiukevich** [comment]
> I like the idea, I'm kind of worried about the license on this code you linked though. I don't think we can simply take this and use it as our own.

That's just an example. I think we can implement it ourselves.

I'd like to support different functions as well (Abs, Sign, Squrt, Power etc.)

**Comment by YZahringer** [comment]
another example: https://github.com/hexinnovation/MathConverter

**Comment by AndreiMisiukevich** [comment]
I was thinking to implement **RPN** algorithm for solving this problem.

**Comment by AndreiMisiukevich** [comment]
Implemented in #1117
