### ISSUE TITLE
[Enhancement] ListToStringConverter

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#238]
## Summary
Convert enumerable of objects (strings) to the single string. Combine "ToStrings" representations into a single string with separator.

```xaml
<Label Text="{Binding Errors, Converter={StaticResource ListToStringConverter}, ConverterParameter={StaticResource CommaWithSpaceSeparator}}" />
```
Input
```["error1", "error2", "error3"]```

Output
```error1, error2, error3 ```

**Comment by sthewissen** [comment]
I'm assuming that whatever you pass into the parameter is what's going to be the separator character?
