### ISSUE TITLE
[Enhancement] Get decimal separator from CultureInfo.CurrentCulture in NumericValidationBehavior 

### ISSUE THREAD

**Issue by berhir** [xamarin/XamarinCommunityToolkit#247]
## Summary

Currently, the decimal separator is hardcoded in NumericValidationBehavior: `const char decimalPartDelimeter = '.';`
This does not work if the users' culture uses a different decimal separator.
Can you take it from `CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator`? Or maybe there is even a better way?

## API Changes

No API changes

## Intended Use Case

As described above, I want to use the behavior with other languages than English. In German, for example, the `','` character is used as decimal separator.

**Comment by AndreiMisiukevich** [comment]
Feel free to submit PR 👍

**Comment by jfversluis** [comment]
Ah yeah, I don't see how we missed that during the review. Great find! Would you like to take a stab at implementing it yourself?

**Comment by jfversluis** [comment]
I think this was fixed 🎉
