### ISSUE TITLE
[Enhancement] Enable Nullable check for the project

### ISSUE THREAD

**Issue by pictos** [xamarin/XamarinCommunityToolkit#254]
## Summary

Since we are using the coolest new C# 8 would be good to enable the NullableReference warnings, to make the lib safer.

## API Changes

Add <Nullable>enable</Nullable> into the csproj.

## Intended Use Case
Avoid `NullReferenceExceptions`

**Comment by jfversluis** [comment]
Should we plan a moment to get this in?

**Comment by pictos** [comment]
I think that will be great!

**Comment by brminnick** [comment]
Closed via #1009
