### ISSUE TITLE
[Enhancement] Toast

### ISSUE THREAD

**Issue by djordje200179** [xamarin/XamarinCommunityToolkit#260]
## Summary
There are several libraries/plugins that already provide toast messages, but they are either out-dated or don't support all major platforms (like UWP). 

## API Changes
Add new method which will call native implementation:

`Application.Current.MainPage.DisplayToast(message: "Hello world!", duration: ToastDuration.LONG, type: ToastType.MESSAGE); `

This implementation could be used as startpoint: 
[ishrakland/Toast](https://github.com/ishrakland/Toast/)

## Intended Use Case
Show Toast messages on Android, iOS and UWP

**Comment by AndreiMisiukevich** [comment]
I approve it)

**Comment by jfversluis** [comment]
Isn't this the same as #197 ?

**Comment by djordje200179** [comment]
> Isn't this the same as #197 ?

It's not same, toast messages are simpler
![Toast](https://user-images.githubusercontent.com/17686905/91964002-e70dfc80-ed0e-11ea-87b4-ed877f17056d.jpg)

**Comment by jfversluis** [comment]
Hm, to be honest I find them pretty similar apart from how they might look. And doing some research, I see that even Android themselves [recommend to use Snackbars over toast](https://developer.android.com/training/snackbar). The thing I'm a bit worried about is that the user will have multiple APIs that do kind of the same thing and will only confuse them.

What does the Toast bring that the Snackbar won't have? Can we combine the two somehow?

**Comment by djordje200179** [comment]
There are people who like Toast simplistic design and therefore prefer Toast messages over Snackbars. Other than that, Toast has no significant advantages over Snackabrs.

**Comment by VladislavAntonyuk** [comment]
Snackbar = Toast + action buttons. I design Snackbar to allow hide action buttons. So I think they may be merged when Snackbar PR will be merged

**Comment by VladislavAntonyuk** [comment]
Toasts will be easier to implement after #261

**Comment by AndreiMisiukevich** [comment]
Do we still want to implement toasts if we have Snackbar?

**Comment by roubachof** [comment]
I don't think so... It doesn't even appear in google material design components.
I think Snackbar took over.

**Comment by djordje200179** [comment]
I can help you with the code if people think that this feature is useful.

**Comment by AndreiMisiukevich** [comment]
@jfversluis I guess we need a board for voting 💯 where we would be able to post polls)

Should we bring toast in additional to snack bar or not (As I understand Toast is deprecated)

**Comment by VladislavAntonyuk** [comment]
Toast ≈ Snackbar - action button. All that you need is not set action and button text

**Comment by AndreiMisiukevich** [comment]
Then I lean towards closing this issue.
Let's get back to the conversation in the future if there is a need in Toast in addition.

**Comment by jfversluis** [comment]
Re:voting. The way that's done on Forms basically is just open an issue/spec and let people vote with the emoji :)

Personally I don't see much added value in adding Toasts additionally in this case
