### ISSUE TITLE
[Enhancement] DataTemplateSelector for single content control

### ISSUE THREAD

**Issue by bmacombe** [xamarin/XamarinCommunityToolkit#265]
## Summary

Content Control that can use a DataTemplate or DataTemplateSelector.

See details in these Forms issue.
https://github.com/xamarin/Xamarin.Forms/issues/6052
https://github.com/xamarin/Xamarin.Forms/issues/4127

The Forms team didn't want to add such a control, but maybe it could be added here?

There is an implementation I have in the Forms issue or open to a better way.  Attached Property, behavior, etc.

**Comment by AndreiMisiukevich** [comment]
I guess it's something similar to "BindableLayout", but only for a single element inside ContentView, correct?

**Comment by AndreiMisiukevich** [comment]
CC @andreinitescu

**Comment by bmacombe** [comment]
@AndreiMisiukevich yep

**Comment by jfversluis** [comment]
Looks like there is a lot of people that will have a use for this. What would be your preferred way of doing this @bmacombe ?

Any reasons why we should go one way or the other?

**Comment by bmacombe** [comment]
There was some discussion in those XF issues about using attached properties or adding properties to ContentView.

Personally I like the idea of a subclass on ContentVIew just because I think it's more discoverable than an attached property or behavior.  But we could do attached properties like BindableLayout works in XF, which would be consistent with the XF core which might be valuable.

Here is a link to a sample implementation of a stand-alone control.
 https://github.com/xamarin/Xamarin.Forms/issues/6052#issuecomment-488032370

I'm interested in what everyone else thinks would be the best approach.  I do think a lot of people would find this useful.

**Comment by jfversluis** [comment]
@jBijsterboschNL didn't you want this a while back?

I would lean towards subclassing it as well and make it a proper standalone control

**Comment by AndreiMisiukevich** [comment]
> @jBijsterboschNL didn't you want this a while back?
> 
> I would lean towards subclassing it as well and make it a proper standalone control

Should "Content" property be available for use in such kind control?
If not, then we can subclass "TemplatedView" :)

**Comment by bmacombe** [comment]
> > @jBijsterboschNL didn't you want this a while back?
> 
> > 
> 
> > I would lean towards subclassing it as well and make it a proper standalone control
> 
> 
> 
> Should "Content" property be available for use in such kind control?
> 
> If not, then we can subclass "TemplatedView" :)

I'm OK with that...I've had that content view based control since before I know about templated view 😁

**Comment by bmacombe** [comment]
@jfversluis @AndreiMisiukevich Is this good to go then?  I'll plan to use a TemplatedView if possible.

**Comment by AndreiMisiukevich** [comment]
I guess we should merge it https://github.com/xamarin/XamarinCommunityToolkit/pull/269 firstly

**Comment by bmacombe** [comment]
Sure or I'll aleast grab those bits if it's not when I start

**Comment by bmacombe** [comment]
Hey @jfversluis, I didn't purposely wait for Hacktoberfest to start working on this, just got buried with other work.  But now that it's here and my other work is going down a bit, I'll plan to work on this if it's approved?

**Comment by bmacombe** [comment]
I'll do some experiments and then create a formal spec.

I'm thinking subclass of TemplatedView or behavior to attach to a TemplatedView or ContentControl

**Comment by GuidoNeele** [comment]
Any word on this? Looks like a very useful control!

**Comment by Cfun1** [comment]
> I'll do some experiments and then create a formal spec.
> 
> I'm thinking subclass of TemplatedView or behavior to attach to a TemplatedView or ContentControl

@bmacombe any update regarding the spec ?

**Comment by bmacombe** [comment]
No sorry, I got really busy at work and haven't been able to make progress on this.

If you need something right now, feel free to go use this code I posted in the XF repo.
https://github.com/xamarin/Xamarin.Forms/issues/6052#issuecomment-488032370

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
