### ISSUE TITLE
[Enhancement] More cells

### ISSUE THREAD

**Issue by djordje200179** [xamarin/XamarinCommunityToolkit#268]
## Summary
I have recently developed an application and I needed to make a settings page. Obviously, the best way to populate a settings page is to create a TableView with a lot of cells. Unfortunately, there are only a few built-in cells, so I needed to use a lot of custom ViewCells. 

Therefore, an idea came to my mind: we could make a few new cells, like ButtonCell, RadioCell, PickerCell, CheckboxCell, EntryCell (improved version) ...

I have found out a library that does this with custom renderers, but only Android and iOS are supported: [muak/AiForms.SettingsView](https://github.com/muak/AiForms.SettingsView)

Here is a screenshot of it and what cells we can create. Of course, we don't need to stick to this, we can make anything.
![Sample image](https://raw.githubusercontent.com/muak/AiForms.SettingsView/master/images/iOS_SS.png)

I think that renderers aren't really needed and that all controls can be built in shared code (creating a control that derives from ViewCell).

## API Changes

A few new classes that derive from `Xamarin.Forms.Cell` will be created. Controls will be avaliable on all platforms because shared code is used.

## Intended Use Case
New cells will be used to make it easier to create settings page.

**Comment by jfversluis** [comment]
Hey @djordje200179 !

Thanks for the suggestion! I'm not quite sure how I feel about this one. I think we would want people to transition away from the `ListView` and `Cell` as much as possible. So I'm not sure if adding more things to make it more appealing to use it will be the best idea.

Can't we create something custom maybe for this based on `CollectionView`?

**Comment by djordje200179** [comment]
It couldn't really be used with CollectionView, because it is intended to be used with TableView.

**Comment by roubachof** [comment]
reminds me of the wonderful MonoTouch.Dialog :)
https://github.com/migueldeicaza/MonoTouch.Dialog

**Comment by Cfun1** [comment]
@jfversluis has this been approved? or it was using an old GitHub feature-template that why it is missing the "needs-approval " label?

**Comment by pictos** [comment]
@Cfun1 this was opened using the old template. Thanks

**Comment by jfversluis** [comment]
I'm going to close this one for now, I would like us to push more for using CollectionView over promoting ListView. I also don't see very many people that seem to have interest in this (right now).

Thank you @djordje200179 for the suggestion! Not adding this right now doesn't mean we don't appreciate your suggestion. I hope you will have more to add in the future!
