### ISSUE TITLE
[Enhancement] AsyncCommand

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#272]
## Summary
Add `ICommand` implementation that support `async` execution and allow the prevention of simultaneous/reentrant execution.

Maybe take `MVVM Helpers` implementation of [AsyncCommand](https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/Commands/AsyncCommand.cs).

## API Changes
Based on [IAsyncCommand](https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/Interfaces/IAsyncCommand.cs) defined on `MVVM Helpers`:
````cs
/// <summary>
/// Interface for Async Command
/// </summary>
public interface IAsyncCommand : ICommand
{
    /// <summary>
    /// Allow simultaneous/reentrant execution. 
    /// Default value is True.
    /// </summary>
    bool AllowMultipleExecution { get; set; }

    /// <summary>
    /// Execute the command async.
    /// </summary>
    /// <returns>Task to be awaited on.</returns>
    Task ExecuteAsync();

    /// <summary>
    /// Raise a CanExecute change event.
    /// </summary>
    void RaiseCanExecuteChanged();
}

/// <summary>
/// Interface for Async Command with parameter
/// </summary>
public interface IAsyncCommand<T> : ICommand
{
    /// <summary>
    /// Allow simultaneous/reentrant execution. 
    /// Default value is True.
    /// </summary>
    bool AllowMultipleExecution { get; set; }

    /// <summary>
    /// Execute the command async.
    /// </summary>
    /// <param name="parameter">Parameter to pass to command</param>
    /// <returns>Task to be awaited on.</returns>
    Task ExecuteAsync(T parameter);

    /// <summary>
    /// Raise a CanExecute change event.
    /// </summary>
    void RaiseCanExecuteChanged();
}
````

**Comment by AndreiMisiukevich** [comment]
Nice idea!)

**Comment by jingliancui** [comment]
Nice idea!)

**Comment by jfversluis** [comment]
Lovely! Since we already have the blessing of James, do you want to port that over yourself @YZahringer or you want us to do it?

**Comment by YZahringer** [comment]
@jfversluis I can port this. I have some doubts:
1. Do we take the implementation as is or we adapt it? 
The current implementation use [WeakEventManager](https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/WeakEventManager.cs) which is a copy of [XF private class](https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Core/WeakEventManager.cs). We copy that too?
2. Which namespace? `Xamarin.CommunityToolkit.ObjectModel`?
3. We make adaptations for `AllowMultipleExecution`?

**Comment by jfversluis** [comment]
1. What would you like to adapt? In the issue I see linked there is also the implementation from @brminnick which seems already improved? I'm almost certain he would allow us to take that if it has changes you'd like to see. We could also try to force an answer for that Forms issue by just opening a PR to make that class public and see what they say. I can do that if needed

2. Good question. At this point I would like to try and not expand to any more namespaces. `ObjectModel` I guess?

3. Again; what would you like to change?

**Comment by brminnick** [comment]
Hi friends!

Feel free to assign this to me. 

I’d be happy to port my implementation of AsyncCommand from [AsyncAwaitBestPractices](https://github.com/brminnick/AsyncAwaitBestPractices/blob/main/Src/AsyncAwaitBestPractices.MVVM/AsyncCommand.cs)

**Comment by sthewissen** [comment]
@brminnick Sounds good. What's the actual difference between these implementations? And if there are differences, could we come to a best of both worlds covering e.g. concerns as mentioned above by @YZahringer?

**Comment by brminnick** [comment]
Yup - it's no problem to merge everything!

MVVMHelpers' implementation was actually [inspired by AsyncAwaitBestPractices](https://montemagno.com/asynccommand-more-come-to-mvvmhelpers/)
<img width="747" alt="image" src="https://user-images.githubusercontent.com/13558917/92655949-0ffe3680-f2a7-11ea-9ed5-068b606e9f9a.png">

To answer your question, AsyncAwaitBestPractices has some performance improvements, includes support for `ValueTask` and has a robust suite of unit tests.

**Comment by brminnick** [comment]
Looking at the spec, above, I'll be making two small changes:
- Add support for `ValueTask`
- Remove `IAsyncCommand.AllowMultipleExecutions`

`ValueTask` was introduced in .NET Standard 2.1 and offers performance gains over `Task`. 

`AllowMultipleExecutions` isn't necessary for `ICommand`, because it breaks the `ICommand` paradigm. `ICommand` includes `CanExecute` which is what should be used to prevent multiple executions. `ICommand` should be stateless and `AllowMultipleExecutions` implements a state-pattern by tracking whether or not the `Task` is currently running.

**Comment by YZahringer** [comment]
@brminnick I agree, `AllowMultipleExecutions` is not stateless in `ICommand`. But it is very useful and simple solution for a recurrent problem to maintain every time you use `IAsyncCommand`.

Without this, you have to manage in every `VM` an `IsBusy`, set on `try...finally` in each `execute`, `canExecute => !IsBusy` and raise can execute changed when `IsBusy` changed.

**Comment by brminnick** [comment]
Interesting - I didn't realize there was a paradigm shift in adding this to other AsyncCommand commands! 

I'll pause and delve into these implementations to understand the ecosystem a bit better 👍
