### ISSUE TITLE
[Spec] StateLayout

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#275]
# StateLayout

Displaying items when your app is in a specific state is a common pattern throughout any mobile app. For instance, creating loading views to overlay on an entire screen or maybe a subsection of your screen needs an individual loader. When there's no data to display we create empty state views or when something goes wrong we need to build an error state view. By implementing the `StateLayout`'s attached properties you can turn any layout element like a `Grid` or `StackLayout` into an individual state-aware element.

This is pretty much me wanting to incorporate StateSquid 🦑  in here :)

# API

## StateView
```
public class StateView : ContentView
{
    public State StateKey { get; set; }
    public string CustomStateKey { get; set; }
    public int RepeatCount  { get; set; }
    public StateView RepeatTemplate { get; set; }

    ...
}
```

## State (Enum)
```
public enum State
{
    None,
    Loading,
    Saving,
    Success,
    Error,
    Empty,
    Custom
}
```
## StateLayout
```
public static class StateLayout
{
    public IList<StateView> StateViews { get; set; }
    public State CurrentState { get; set; }
    public string CurrentCustomStateKey { get; set; }
    public bool AnimateStateChanges { get; set; }
}
```

## StateLayoutController
```
public class StateLayoutController
{
    void SwitchToContent(bool animate) { }
    void SwitchToTemplate(string customState, bool animate)  { }
    void SwitchToTemplate(State state, string customState, bool animate) { }
    bool HasTemplateForState(State state, string customState) { }

    ...
}
```

# Scenarios

## Basic scenario

Each layout that you make state-aware using the `StateLayout` attached properties contains a collection of `StateView` objects. These can be used as templates for the different states supported by `StateLayout`. Whenever the `CurrentState` is set to a value that matches the `State` property of one of the `StateViews` its contents will be displayed instead of the main content.

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
   xmlns:state="clr-namespace:Xamarin.Forms.StateSquid;assembly=Xamarin.Forms.StateSquid" 
   x:Class="SampleApp.MainPage">

   <Grid state:StateLayout.CurrentState="{Binding CurrentState}">
      <state:StateLayout.StateViews>
         <state:StateView StateKey="Loading">
            <Grid BackgroundColor="White">
               <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
                  <ActivityIndicator Color="#1abc9c" IsRunning="{Binding CurrentState, Converter={StaticResource StateToBooleanConverter}, ConverterParameter={x:Static state:State.Loading}}" />
                  <Label Text="Loading..." HorizontalOptions="Center" />
               </StackLayout>
            </Grid>
         </state:StateView>
      </state:StateLayout.StateViews>      
  
     ...
     
  </Grid>  
</ContentPage>
```

The `State` property supports one of the following values:

- Loading
- Saving
- Success
- Error
- Empty
- Custom
- None (this will show the default view).

## Custom states

Besides the built-in state this also supports a `Custom` state. By setting `State="Custom"` and `CustomStateKey="[yourvalue]"` you can create custom states beyond the built-in ones. You can use the `CurrentCustomStateKey` on your root `StateLayout` element to databind a variable that indicates when to show one of your custom states.

```
 <StackLayout Padding="10" state:StateLayout.CurrentState="{Binding CurrentState}" state:StateLayout.CurrentCustomStateKey="{Binding CustomState}" BackgroundColor="#f0f1f2">
   <state:StateLayout.StateViews>
      <state:StateView StateKey="Custom" CustomStateKey="ThisIsCustomHi">
         <Label Text="Hi, I'm a custom state!" VerticalOptions="Center" VerticalTextAlignment="Center" HorizontalOptions="Center" HorizontalTextAlignment="Center"  />
      </state:StateView>
      <state:StateView StateKey="Custom" CustomStateKey="ThisIsCustomToo">
         <Label Text="Hi, I'm a custom state too!" VerticalOptions="Center" VerticalTextAlignment="Center" HorizontalOptions="Center" HorizontalTextAlignment="Center"  />
      </state:StateView>
   </state:StateLayout.StateViews>
   <Label Text="This is the normal state." VerticalOptions="Center" VerticalTextAlignment="Center" HorizontalOptions="Center" HorizontalTextAlignment="Center" />
</StackLayout>
```

## Repeat a template multiple times

When loading multiple items of the same type it could be beneficial if we can simply repeat a piece of XAML without having to copy-paste it multiple times. This is where `RepeatCount` comes into play. By defining a `RepeatTemplate` we can repeat the same bit of XAML but only define it once. A sample of this process can be seen here.

```
<StackLayout state:StateLayout.CurrentState="{Binding CurrentState}" Grid.Row="0">
     <state:StateLayout.StateViews>
        <state:StateView StateKey="Loading" RepeatCount="3">
            <state:StateView.RepeatTemplate>
                <DataTemplate>
                    <Grid Padding="20" HeightRequest="120">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="24" />
                            <RowDefinition Height="20" />
                            <RowDefinition Height="Auto" />
                            <RowDefinition Height="14" />
                            <RowDefinition Height="Auto" />
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*" />
                            <ColumnDefinition Width="*" />
                            <ColumnDefinition Width="*" />
                        </Grid.ColumnDefinitions>
                        <state:SkeletonView CornerRadius="6" Grid.Row="0" Grid.ColumnSpan="2" HeightRequest="20" BackgroundColor="#cccccc" WidthRequest="120" />
                        <state:SkeletonView CornerRadius="6" Grid.Row="1" Grid.ColumnSpan="3" HeightRequest="20" BackgroundColor="#cccccc" WidthRequest="200" />
                        <BoxView Grid.Row="2" Grid.ColumnSpan="3" HeightRequest="1" BackgroundColor="#cccccc" Margin="0,8" />
                        <Label Grid.Row="3" Grid.Column="0" HorizontalOptions="Center" Text="TOTAL ARTICLES" FontSize="10" TextColor="Gray" />
                        <Label Grid.Row="3" Grid.Column="1" HorizontalOptions="Center" Text="PRICE" FontSize="10" TextColor="Gray" />
                        <Label Grid.Row="3" Grid.Column="2" HorizontalOptions="Center" Text="BOXES" FontSize="10" TextColor="Gray" />
                        <state:SkeletonView CornerRadius="6" Grid.Row="4" Grid.Column="0" HeightRequest="20" BackgroundColor="#cccccc" HorizontalOptions="Fill" />
                        <state:SkeletonView CornerRadius="6" Grid.Row="4" Grid.Column="1" HeightRequest="20" BackgroundColor="#cccccc" HorizontalOptions="Fill" />
                        <state:SkeletonView CornerRadius="6" Grid.Row="4" Grid.Column="2" HeightRequest="20" BackgroundColor="#cccccc" HorizontalOptions="Fill" />
                    </Grid>
                </DataTemplate>
            </state:StateView.RepeatTemplate>
        </state:StateView>
    </state:StateLayout.StateViews>
<StackLayout>
```

## Skeleton loading

Skeleton screens in different shapes and sizes are found everywhere across the web and apps — anywhere we humans are forced to wait. They are usually perceived as being shorter in duration when compared against a blank screen and a spinner. This solution supports adding a skeleton loader like appearance using a `SkeletonView`. This view is automatically animated to show a slight blinking state animation. Simply add it to your loading template and size it accordingly. You can even use `CornerRadius` to make rounded variations of it. This view however might be nicely templatable or hooked up through a resource to a custom view users would want to use for it (not in currently).

# Platform Compatibility
This should work on all platforms as it's a completely forms-based solution.

# Difficulty : low
All of the code already exists and while improvements can obviously be made there's already a solid base.

**Comment by roubachof** [comment]
RepeatTemplate is a very neat idea!

**Comment by bmacombe** [comment]
This would be awesome!

**Comment by jfversluis** [comment]
Maybe I'm missing something. What is the discussion we're expecting here? On whether or not we want this in? Or other details about it?

**Comment by sthewissen** [comment]
Yeah, I suppose what I'm looking for is whether or not this approach seems viable to most people. Obviously the technical implementation will spark more discussion once it's PRed, but maybe people have some additional features that might be nice additions to this or see problems emerging already that I may have not noticed :)

**Comment by AndreiMisiukevich** [comment]
Closed in #450

**Comment by dersia** [comment]
I know this in closed since october 2020, but am I missing something? Can't find the `SkeletonView`. @sthewissen where can I find it?

**Comment by Cfun1** [comment]
@dersia from the linked pr
> The only thing I haven't put in here is the SkeletonView that was mentioned there. I don't want to take that in to be honest, as I think it should be up to the user to create their own visualization. I'm sure we could come up with a better skeleton loading solution anyway.

The initial implementation could be fond in [sthewissen/../SkeletonView.cs](https://github.com/sthewissen/Xamarin.Forms.StateSquid/blob/master/src/Xamarin.Forms.StateSquid.Multi/Platforms/Shared/SkeletonView.cs)
