### ISSUE TITLE
[Enhancement] WPF GTK support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#278]
## Summary

 
XamarinCommunityToolkit should support all platforms which Xamarin.Forms supports

**Comment by jfversluis** [comment]
While I'd love to do that, it seems like that for GTK (#193) we had to take on a dependency of a couple of MBs which I don't really think is worth it. WPF is fine for me.

**Comment by AndreiMisiukevich** [comment]
> While I'd love to do that, it seems like that for GTK (#193) we had to take on a dependency of a couple of MBs which I don't really think is worth it. WPF is fine for me.

But I guess that those libs won't be referenced from iOS/Android etc. platforms. Only from GTK.

Those bins will just increase nuget size, won't they?

**Comment by jfversluis** [comment]
Hopefully. Can we verify that some way? @jsuarezruiz do you know about any of this?

**Comment by VladislavAntonyuk** [comment]
I don't have gtk libs in the output of other platforms

**Comment by VladislavAntonyuk** [comment]
@jfversluis what do you think about adding support for Tizen, GTK?

**Comment by jfversluis** [comment]
Let's do it. Do you want to add it @VladislavAntonyuk ?

**Comment by VladislavAntonyuk** [comment]
I saw @AndreiMisiukevich created PR for that. You can reopen it

**Comment by AndreiMisiukevich** [comment]
> I saw @AndreiMisiukevich created PR for that. You can reopen it

feel free to create a new one if you wish 👍

**Comment by jsuarezruiz** [comment]
Yes, that GTK dependencies will be only referenced on the GTK project.
