### ISSUE TITLE
[Bug] [CameraView] [iOS] If the app goes to the background, the camera gets deactivated and not reactivated on resume

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#282]
### Description
When using the CameraView on iOS, if the app goes in the background the Camera gets deactivated. Once the user resumes the app, the Camera is frozen and does not get reactivated.

### Steps to Reproduce

1. Use CameraView
2. Put the app in background
3. Resume the app.

### Expected Behavior
The camera gets activated again.

### Actual Behavior
The camera is frozen.

### Basic Information

- Platform Target Frameworks: 
  - iOS:  13.6.1

**Comment by bmacombe** [comment]
I'm looking at #286 and will see if I can figure this one out at the same time since it's in a similar area.

**Comment by bmacombe** [comment]
@acuntex I've been trying to reproduce this and but I'm not having any luck.

I've tried an older iPad Pro and an iPhone 6s.  They are all iOS 14 though, I don't have a device with a lower iOS version to test with right now.

Can you provide any more details to help reproduce it?

Thanks

**Comment by acuntex** [comment]
@bmacombe I also have an iPhone 6s. I remember putting the App in the background by pressing the button.

I tried to reproduce it again but failed. Until I can reproduce it, i will close this issue.
