### ISSUE TITLE
[Enhancement] [CameraView] Commands for Events (MVVM)

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#285]
## Summary
In order to use the CameraView in am MVVM architecture with a view model it would be helpful to have commands for the existing events.

## API Changes

The following commands would be necessary to have a clean MVVM architecture:

```
		public static readonly BindableProperty MediaCapturedCommandProperty = BindableProperty.Create(nameof(MediaCapturedCommand), typeof(ICommand), typeof(CameraView));
		public static readonly BindableProperty MediaCaptureFailedCommandProperty = BindableProperty.Create(nameof(MediaCaptureFailedCommand), typeof(ICommand), typeof(CameraView));
		public static readonly BindableProperty OnAvailableCommandProperty = BindableProperty.Create(nameof(OnAvailableCommand), typeof(ICommand), typeof(CameraView));
		public static readonly BindableProperty ShutterCommandProperty = BindableProperty.Create(nameof(ShutterCommand), typeof(ICommand), typeof(CameraView), defaultBindingMode: BindingMode.OneWayToSource);

		public ICommand MediaCapturedCommand
		{
			get => (ICommand)GetValue(MediaCapturedCommandProperty);
			set => SetValue(MediaCapturedCommandProperty, value);
		}
		
		public ICommand MediaCaptureFailedCommand
		{
			get => (ICommand)GetValue(MediaCaptureFailedCommandProperty);
			set => SetValue(MediaCaptureFailedCommandProperty, value);
		}
		
		public ICommand OnAvailableCommand
		{
			get => (ICommand)GetValue(OnAvailableCommandProperty);
			set => SetValue(OnAvailableCommandProperty, value);
		}
		
		public ICommand ShutterCommand
		{
			get => (ICommand)GetValue(ShutterCommandProperty);
			set => SetValue(ShutterCommandProperty, value);
		}
```
The ShutterCommand is a special case because it is a command that's injected in the ViewModel to trigger the shutter.
The following approach with the code example above would make the commands work on all platforms by modifying the constructor of CameraView:
```
		public CameraView()
		{
			MediaCaptured += (sender, args) => MediaCapturedCommand?.Execute(args);
			MediaCaptureFailed += (sender, s) => MediaCaptureFailedCommand?.Execute(s);
			OnAvailable += (sender, b) => OnAvailableCommand?.Execute(b);
			ShutterCommand = new Command(Shutter);
		}
```

## Intended Use Case
Any MVVM app using CameraView.

**Comment by bmacombe** [comment]
Hey @acuntex would the EventToCommandBehavior in the toolkit resolve this?

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs

**Comment by acuntex** [comment]
Hey @bmacombe I guess for the first 3 events yes. Not sure about the ShutterCommand since it's something the view model would trigger.

**Comment by pictos** [comment]
@bmacombe do you think that we need Commands for `MediaCaptureFailed`, `MediaCaptured`, `OnAvailable`?

For `OnAvailable` I think that dev can use the `IsAvailable` property to track it.
For the others and don't like too much the idea of having a Command with an argument, because we need to make the property strongly typed, something like

```csharp
public static readonly BindableProperty MediaCapturedCommandProperty =
			BindableProperty.Create(nameof(MediaCapturedCommand),
						typeof(Command<MediaCapturedEventArgs>),
						typeof(CameraView),
						null);

		public Command<MediaCapturedEventArgs> ShutterCommand
		{
			get => (Command<MediaCapturedEventArgs>)GetValue(ShutterCommandProperty);
			set => SetValue(ShutterCommandProperty, value);
		}
``` 

And this can be very confusing for the users. If you have a better way to implement this, please let me know.
