### ISSUE TITLE
[Bug] [CameraView] [iOS] When binding CameraOptions the Camera gets initialized twice

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#286]
### Description
If you bind the Property CameraOptions, the CameraViewRenderer initializes the Camera twice.
If the initial value is CameraOptions.Front it will first initialize the back camera (because of CameraOptions.Default) and then the front camera.
If the initial value is CameraOptions.Back it will first initialize the back camera (because of CameraOptions.Default) and then again the back camera.

### Steps to Reproduce
1. Create CameraView
2. Bind property CameraOptions to a view model

### Expected Behavior
Only the camera that is bound with CameraOptions will be initialized.

### Actual Behavior
The back camera will always be initialized because of CameraOptions.Default, following by the camera referenced by CameraOptions.

### Basic Information

- Platform Target Frameworks: 
  - iOS:  13.6.1

**Comment by AndreiMisiukevich** [comment]
Hi, thanks for the report )

Does it cause some kind of unexpected app's behavior?

**Comment by acuntex** [comment]
It seems to work for now.

But we should keep an eye on it because there is code running, that should not run.
That means:
- Possibility of a side effect
- Performance issues
- More battery usage

Just please please don't let this project fade into "well, it somehow works, so we don't care", but instead focus on quality.

**Comment by bmacombe** [comment]
I'm going to see what I can do to reduce this, from a quick look it looks like the iOS camera device would be accessed at least twice if the "Default" camera was used and maybe three times if another camera is used.
