### ISSUE TITLE
[Enhancement] [CameraView] Remove CameraOptions.Default

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#290]
## Summary
At the moment, the enum CameraOptions has the following values:
```
	public enum CameraOptions
	{
		Default,
		Front,
		Back,
		External
	}
```
Default is current the same as CameraOptions.Back
```
			switch (cameraOptions)
			{
				default:
				case CameraOptions.Default:
				case CameraOptions.Back:
					position = AVCaptureDevicePosition.Back; break;
				case CameraOptions.Front:
					position = AVCaptureDevicePosition.Front; break;
				case CameraOptions.External:
					position = AVCaptureDevicePosition.Unspecified; break;
			}
```
Problem with this implementation is that if the UI binds the property `CameraOptions` of `CameraView` it will trigger a property-changed-event leading to a new initialization (and therefore deactivation/activation) of the camera which should not be necessary.

## API Changes

Remove CameraOptions.Default

**Comment by pictos** [comment]
@bmacombe do you know if this makes sense for UWP? 
For mobile devices, I can see that `Default` looks like a waste, but for desktop or even IoT, that you can have a lot of cameras this looks good.

**Comment by acuntex** [comment]
Wouldn't these be Externals?

**Comment by pictos** [comment]
> Wouldn't these be Externals?

For UWP the default is the first camera device, and that can be the attached webcam or an external camera.

> I think the library should not decide what's default since that's based on the use case.

The `Default` value isn't the default devices camera and it's the default camera for the control, so if the dev doesn't set which camera he wants we will use the Back camera, for mobile devices. If we have more than 2 cameras (back and frontal) we use the first camera in the collection.

If we can connect more cameras in Android/iOS devices we should change the code to behaves this way.

**Comment by bmacombe** [comment]
I think we should keep the default and each platform can be opinionated on what the default is.  But maybe we could try to prevent the unneeded inits.

**Comment by jfversluis** [comment]
I tend to agree. If we are supporting UWP (we do now), macOS and GTK (hopefully in the future) the default might be different amongst different devices. We should look into not initializing over and over again though.

Is this something you have actually seen happening @acuntex or is this an assumption based on the code? I would assume that the OS would not reinitialize when it sees the front camera is already open and you switch to the front camera again. But that is a big assumption on that on my side :D

**Comment by acuntex** [comment]
@jfversluis I saw it when debugging.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
