### ISSUE TITLE
[Enhancement] Leverage `Xamarin.Forms.WeakEventManager`

### ISSUE THREAD

**Issue by brminnick** [xamarin/XamarinCommunityToolkit#293]
## Summary

If/when we increase the minimum Xamarin.Forms dependency to Xamarin.Forms v5.0, let's leverage `Xamarin.Forms.WeakEventManager`.

This PR adds `Xamarin.CommunityToolkit.Helpers.WeakEventManager`: https://github.com/xamarin/XamarinCommunityToolkit/pull/279

In Xamarin.Forms v5.0, `Xamarin.Forms.WeakEventManager` will be public: https://github.com/xamarin/Xamarin.Forms/pull/12063.

However, XamarinCommunityToolkit cannot currently leverage `Xamarin.Forms.WeakEventManager` because it has a dependency on Xamarin.Forms v4.5.

## API Changes

Mark `Xamarin.CommunityToolkit.Helpers.WeakEventManager` as obsolete: 

```csharp
[Obsolete("Use Xamarin.Forms.WeakEventManager")]
public class WeakEventManager
```

## Intended Use Case

This will ensure that we aren't duplicating code/features between Xamarin.Forms and XamarinComunityToolkit.

XamarinCommunityToolkit can continue to extend `Xamarin.Forms.WeakEventManager` (same it currently extends `Xamarin.CommunityToolkit.Helpers.WeakEventManager`), adding support for `EventHandler<T>`, `Action`, and `Action<T>` events.

**Comment by pictos** [comment]
@brminnick can we close this one?

**Comment by brminnick** [comment]
Has XamarinCommunityToolkit increased its Xamarin.Forms dependency to Xamarin.Forms v5.0 yet?

**Comment by pictos** [comment]
I don't think so, I asked because the two PRs mentioned were merged.
