### ISSUE TITLE
[Spec] Auto-Suggest Box Control

### ISSUE THREAD

**Issue by techduggu** [xamarin/XamarinCommunityToolkit#294]
## Summary

Create an Auto-Suggest Box Control that allows selection of items from a list with the option of entering text to filter down that list (the equivalent of a classic [WPF ComboBox or the UWP AutoSuggestBox](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/auto-suggest-box)

I also noticed that few years back it was heavily requested in Xamarin.Forms too by @hartez as well as community but it hasn't picked up and now moved to inactive: https://github.com/xamarin/Xamarin.Forms/issues/1775 

## API Changes

The initial suggestion is to port the implementation offered by @dotMorten in X.F. 
https://github.com/dotMorten/XamarinFormsControls/tree/main/AutoSuggestBox
And NuGet here: https://www.nuget.org/packages/dotMorten.Xamarin.Forms.AutoSuggestBox

The implementation is based on UWP's AutoSuggestBox. It uses native controls under the covers and works for UWP, Android and iOS. 

I am creating this Spec to further receive any community feedback/questions on this otherwise @dotMorten can help to port this library as-it-is to XCT.

## Intended Use Case

This is a common control required by all platforms specially while developing features like Search with auto-populated suggestions.

## Visuals

![image](https://user-images.githubusercontent.com/17450941/93015842-58d12a80-f5da-11ea-8086-89da5fd20101.png)

**Comment by AndreiMisiukevich** [comment]
I think it would be awesome to have such control in XCT!

**Comment by AndreiMisiukevich** [comment]
But I am not sure about the name of this control. How about something like
AutoCompleteEntry ?

**Comment by dotMorten** [comment]
Just FYI my control is native and thus doesn't provide a templates list because XF still do this day does not allow us to convert things into native views unless they are entire pages

**Comment by dotMorten** [comment]
> How about something like
AutoCompleteEntry ?

As mentioned above this is a port of the existing UWP control. The design and doc aligns and can be reused as is.

**Comment by techduggu** [comment]
Yeah, AutoSuggestBox sounds good to me and it is inline with UWP too: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/auto-suggest-box

**Comment by techduggu** [comment]
> Just FYI my control is native and thus doesn't provide a templated list because XF still to this day does not allow us to convert things into native views unless they are entire pages

I removed the 'templated' word from the Description as it was confusing. I think we are good with Native approach because that is what was being initially proposed in X.F. too [here](https://github.com/xamarin/Xamarin.Forms/issues/1775) (see at the end of the Description about the UWP, Android and iOS native approach).

**Comment by powerdude** [comment]
i'd suggest`Entry` as the suffix since the Xamarin Forms control is called `Entry` and this could be seen as an enhancement of it. `Box` works for UWP since its control is called `TextBox` i believe.

**Comment by sthewissen** [comment]
> i'd suggest`Entry` as the suffix since the Xamarin Forms control is called `Entry` and this could be seen as an enhancement of it. `Box` works for UWP since its control is called `TextBox` i believe.

I'm tempted to agree with this sentiment.

**Comment by techduggu** [comment]
As the initial idea is to port @dotMorten existing [library](https://www.nuget.org/packages/dotMorten.Xamarin.Forms.AutoSuggestBox) to XCT which is originally based on UWP Auto-Suggest Box control (and hence goes its name).

If we would like to change its name in XCT, probably we should also consider its design implementation. 
At present, @dotMorten implementation is based on UWP and native controls. Hence, please share any feedback for design too which will help in the decision (whether to port the existing library or build purely forms based e.g. templated approach).

Please note, months of discussion already happened here which you may refer: https://github.com/xamarin/Xamarin.Forms/issues/1775

**Comment by jBijsterboschNL** [comment]
Hi @techduggu / @dotMorten / @jfversluis, is there still some progress going on for this awesome control? What is holding you back for starting to port the AutoSuggestBox implementation from @dotMorten over to the XCT? Could I perhaps be of any assistance to you guys?

As for naming I would go for @AndreiMisiukevich suggestion, as this is more in line with Xamarin.Forms controls naming: AutoCompleteEntry.

**Comment by techduggu** [comment]
Hi @jBijsterboschNL 
Thanks for showing your interest.
I talked to @dotMorten and we think it is best to create another implementation of this control for XCT as his control (like he mentioned in above thread) is a port of existing UWP control and hence goes its original name.

So, if we plan to create implementation of this control from scratch in XCT, we should start listing the specs (based on the discussion already happened here: https://github.com/xamarin/Xamarin.Forms/issues/1775). Can you help with starting the process for this or feel free to implement (if you need any help, I can help out over weekends)?

**Comment by Cfun1** [comment]
@techduggu any update on the spec ?

**Comment by techduggu** [comment]
@Cfun1 With reference to my previous comment, it is open to pick up for implementation.
For details around implementation/spec, you can refer: https://github.com/xamarin/Xamarin.Forms/issues/1775

@jfversluis / @AndreiMisiukevich / @pictos : As the initial idea of porting has been dropped now, I'd need some experts help here to define the initial architecture/design of this control (the way we want in XCT). If you/someone can help with providing details & guidance for its MVP version, I would love to learn further, pair up and help with the implementation.

**Comment by pictos** [comment]
@techduggu someday next week I can take a look at this and provide some spec.

**Comment by amirvenus** [comment]
My requirement is that the results list to overlay View(s) under the label instead of pushing them down the page to make up space for itself

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
