### ISSUE TITLE
[Bug] [CameraView] [Android] Taken photos are rotated by 90°

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#297]
### Description
When taking a photo with CameraView on Android, photos are rotated by 90°.

### Steps to Reproduce

1. Use the sample to take a photo.
2. Look at the preview below.

### Expected Behavior
Photos are not rotated but have the same rotation as the CameraView.

### Actual Behavior
Photos are rotated by 90°.

### Reproduction imagery

![Screenshot_20200913_175908_com companyname xamarincommunitytoolkitsample](https://user-images.githubusercontent.com/17462039/93022836-7eb2fb00-f5eb-11ea-94a7-cf1fe7a3e274.jpg)

**Comment by SPTutorial** [comment]
how to fix this issue? I am also getting the rotate image after capture

**Comment by rnguye2** [comment]
This is still a bug

**Comment by Natalia-eng1** [comment]
Any updates on this fix?

**Comment by ouijahija** [comment]
Still not working....

**Comment by justinlee0516** [comment]
If I take a video in the sample app on my Android phone (in portrait position), the output file show the video rotated by 90 degrees.

**Comment by pictos** [comment]
Please if you're still facing this issue open a new one with a repro attached. Thanks
