### ISSUE TITLE
[Bug] [CameraView] [Android] CameraView does not use the view space defined in Xamarin.Forms

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#300]
### Description
When using CameraView in Xamarin.Forms the default option for HorizontalOptions and VerticalOptions are FillAndExpand, yet the CameraView on Android does not use the space given to it and scale the image as AspectFill as it is on iOS.
I tried e.g. to create a CameraView that uses the whole screen. While on iOS it fills the whole screen, on Android it's only a square.

### Steps to Reproduce

1. Create a "full screen" CameraView that spans the whole screen
or:
1. Use the sample app
2. Change to photo

### Expected Behavior
The CameraView does use the whole space while using AspectFill as Aspect.

### Actual Behavior
The CameraView does not use the whole space.

### Reproduction imagery
Android (invalid):
![Screenshot_20200913_175908_com companyname xamarincommunitytoolkitsample](https://user-images.githubusercontent.com/17462039/93022836-7eb2fb00-f5eb-11ea-94a7-cf1fe7a3e274.jpg)
iOS (valid):
![IMG_0049](https://user-images.githubusercontent.com/17462039/93022841-85da0900-f5eb-11ea-9717-48b9f4912e27.png)

**Comment by pictos** [comment]
@acuntex can you confirm if this still happens?

**Comment by acuntex** [comment]
@pictos Yes, it's still happening.

It's also interesting that in the sample if you switch to Front Camera and then from Video to Photo, the camera image is suddenly zoomed in.

**Comment by Depechie** [comment]
I face the same issue... also on a Samsung SM-G950, the preview with zoom 1 is still more zoomed in than the actual picture taken.

**Comment by jfversluis** [comment]
Do we think the zoom issue has the same cause? If not, can we open a separate issue for that?

**Comment by GeorgeVelikov** [comment]
This still happens I'm afraid

**Comment by DBAaaSDarran** [comment]
I think I can see a very similar issue with the CameraView on iOS when rotating the screen.

The page layout looks ok when launching the app in portrait on an iPhone. When rotating, the CameraView doesn't seem to redraw itself correctly within it's new bounds. I can see additional space pushing the CameraView off-screen. I've coloured the background yellow to highlight the issue.
Rotating one way to landscape pushes the camera down (screenshot with yellow space), rotating to the opposite landscape pushes the camera and all other controls up, anchoring to the bottom of the CameraView control.

Xamarin.CommunityToolkit 1.2.0

CameraPage.xaml
```cs
            ...Content...
            <StackLayout x:Name="LabelsAndCameraStack"
                         VerticalOptions="FillAndExpand" 
                         HorizontalOptions="FillAndExpand"
                         >
            ...Content...
            <xct:CameraView x:Name="cameraView"
                                CaptureMode="Photo"
                                FlashMode="Off"
                                HorizontalOptions="FillAndExpand"
                                VerticalOptions="FillAndExpand"
                                MediaCaptured="CameraView_MediaCaptured"
                                MediaCaptureFailed="CameraView_MediaCaptureFailed"
                                OnAvailable="CameraView_OnAvailable"
                                BackgroundColor="Yellow"
                                />  
            ...Content...
            </StackLayout>
            ...Content...
```

CameraPage.xaml.cs
```xaml
private DeviceOrientations _CurrentOrientation;
        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);

            var newOrientation = CrossDeviceOrientation.Current.CurrentOrientation;
            if (!(newOrientation == _CurrentOrientation))
            {
                _CurrentOrientation = newOrientation;

                //Rotate the Image inside the camera
                switch (newOrientation)
                {
                    case DeviceOrientations.Undefined:
                        cameraView.Rotation = 0;
                        break;
                    case DeviceOrientations.Portrait:
                        cameraView.Rotation = 0;
                        break;
                    case DeviceOrientations.Landscape:
                        cameraView.Rotation = 90;
                        break;
                    case DeviceOrientations.PortraitFlipped:
                        cameraView.Rotation = 180;
                        break;
                    case DeviceOrientations.LandscapeFlipped:
                        cameraView.Rotation = 270;
                        break;
                    default:
                        cameraView.Rotation = 0;
                        break;
                }
            }
        }
```

![IMG_8778](https://user-images.githubusercontent.com/88893387/129370452-867f1e8a-1eb5-45fe-8741-1c3ce407f128.PNG)
![IMG_8779](https://user-images.githubusercontent.com/88893387/129370471-94d08037-7814-4a5e-9ff3-22fc2c4d6362.PNG)

Does that all make sense?
Many thanks
