### ISSUE TITLE
[Bug] [CameraView] [Android] CameraView only creates low res (640x480) jpegs

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#302]
### Description
The CameraView on Android only creates jpegs with a low resolution (640x480) while on iOS photos are captured with high resolution.
The images are also landscape while the screen is in portrait mode.

### Steps to Reproduce

1. Create a CameraView with CameraCaptureOptions.Photo
2. Trigger the shutter.

### Expected Behavior
High resolution photos are taken, depending on the device.

### Actual Behavior
Images are always in landscape mode and with a low resolution (640x480).

**Comment by jfversluis** [comment]
Yeah I think I've seen that hardcoded in the code :(

Does it make sense to follow the pattern of MediaPlugin where we can set different sizes? https://github.com/jamesmontemagno/MediaPlugin#resize-photo-size

**Comment by pauldiston** [comment]
Can I ask, how might I set the Resolution for the photo to be taken by the CameraView? Is this possible in XAML?
