### ISSUE TITLE
[Bug] [CameraView] [Android] VideoStabilization can not work

### ISSUE THREAD

**Issue by acuntex** [xamarin/XamarinCommunityToolkit#303]
### Description
The video stabilization of CameraView can not work on Android.
This is because of the following code:

```
		public void SetVideoStabilization()
		{
			if (sessionBuilder == null || !stabilizationSupported)
			{
				sessionBuilder.Set(CaptureRequest.ControlVideoStabilizationMode,
					(int)(Element.VideoStabilization ? ControlVideoStabilizationMode.On : ControlVideoStabilizationMode.Off));
			}
		}
```
If sessionBuilder is null it would throw a NullReferenceException.
If stabilizationSupported is false, the device does not support video stabilization and therefore if would not work either.

The code should probably be:
```
		public void SetVideoStabilization()
		{
			if (sessionBuilder == null || !stabilizationSupported)
				return;
			sessionBuilder.Set(CaptureRequest.ControlVideoStabilizationMode,
				(int)(Element.VideoStabilization ? ControlVideoStabilizationMode.On : ControlVideoStabilizationMode.Off));
		}
```

**Comment by jfversluis** [comment]
Thanks for all the bug reports @acuntex! Really appreciate the early feedback :)

Would you be also willing to pitch in with fixing some of them?

**Comment by acuntex** [comment]
@jfversluis I'm hitting the F5 Button like crazy on the PR ;-)

**Comment by jfversluis** [comment]
For the android cameraview to merge first you mean?

**Comment by acuntex** [comment]
Joking aside ☺️
Yes, once it's merged I'll start to fix. Just to avoid problems.

**Comment by jfversluis** [comment]
Sure I totally get that! Let me get on it right now

**Comment by jfversluis** [comment]
OK merged it! Gimme all those PRs! :D

Let me know which ones you'll be working on so I can assign you to it so other people won't start on them
