### ISSUE TITLE
[Spec]  Gravatar Image Source

### ISSUE THREAD

**Issue by dansiegel** [xamarin/XamarinCommunityToolkit#312]
# GravatarImageSource

It is fairly common for apps to want to use a Gravatar Image based on a User's Email. The Toolkit should include a GravatarImageSource. This is something I've already got in my toolkit but am happy to contribute to the CommunityToolkit. 

# API

### Values

- FileNotFound
- MysteryPerson
- Identicon
- MonsterId
- Wavatar
- Retro
- Robohash
- Blank

### Properties

| API | Description |
| ------------- | ------------- |
| Email | Gets or sets Email. |
| Size | Gets or sets Size. |
| DefaultGravatar | Gets or sets DefaultGravatar. |

### Events

none
 
# Scenarios

You have an authenticated user and would like to display a profile picture of the user using their Gravatar Image

# Platform Compatibility
- Target Frameworks: 
  - iOS:  supported
  - Android: supported
  - UWP: supported
# Backward Compatibility

# Difficulty : low

**Comment by jfversluis** [comment]
Sorry for the long wait @dansiegel! Sounds good to me, let's do it!
