### ISSUE TITLE
[Bug] CommandNotExecutesYetBeforeTimeThresholdExpires test fails randomly

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#313]
### Description

The `UserStoppedTypingBehavior_Tests.CommandNotExecutesYetBeforeTimeThresholdExpires` test seems flaky. Probably some race condition?

I've noticed a couple of times the build will fail on this one while re-running it without any changes made it succeed. I.e.: https://github.com/xamarin/XamarinCommunityToolkit/pull/311/checks?check_run_id=1115322568

We need to have a look at that or remove it probably.

@jBijsterboschNL any ideas?

**Comment by jBijsterboschNL** [comment]
@jfversluis, this has probably something to do with the test execution time. When the threshold is set to 1000ms, this test awaits 900ms to check whether the command has not been executed yet. Unsure why the test assertion is taking more then 100ms, but I could change this test to not wait 900ms (which is only 100ms less then the user stopped typing threshold setting), but not wait at all or wait f.e. for 100ms. Let me know what you prefer and I'll send a pull request.

**Comment by jfversluis** [comment]
Didn't really see this happening anymore. Closing for now, we can revisit later.

And thanks for the help @jBijsterboschNL !
