### ISSUE TITLE
How can I get URI to use in MediaElement?

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/XamarinCommunityToolkit#318]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170227/how-can-i-get-uri-to-use-in-mediaelement.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I would like to know what websites offer the option of inserting an mp3 file I get the URI that I can use in MediaElement according to your tutorial here https://docs.microsoft.com/pl-pl/xamarin/xamarin-forms/user-interface/mediaelement . That link must play audio automatically, user does not need to click to play. You did not provide full instructions on how to use MediaElement with my own sounds so that's why I'm asking.
Yours sincerely,  Kamysz Arkadiusz

---
#### Feedback Bot on 9/1/2020, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/2/2020, 06:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Enbi Zhang Zhang [MSFT] solved on 9/2/2020, 02:59 AM, 0 votes: 

<p>Thanks for your question.<br>
We guess this tutorial <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.mediaelement?view=netcore-3.1">https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.mediaelement?view=netcore-3.1</a> will useful for you.</p>

**Comment by jfversluis** [comment]
Linked with #319
