### ISSUE TITLE
The tutorial 'ElementMedia' you shared doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/XamarinCommunityToolkit#319]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1173127/the-tutorial-elementmedia-you-shared-doesnt-work.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I ran into problems while I was creating an mobile app in Xamarin Forms. The tutorial you shared here " https://docs.microsoft.com/pl-pl/xamarin/xamarin-forms/user-interface/mediaelement " is not working. I want to play Web Audio or Video but going step by step as you show doesn't help. I added " Device.SetFlags(new string[]{ "MediaElement_Experimental" }); " to App.xaml.cs , after that I added " <MediaElement Source="https://sec.ch9.ms/ch9/5d93/a1eab4bf-3288-4faf-81c4-294402a85d93/XamarinShow_mid.mp4"
              ShowsPlaybackControls="True" /> " to MainPage.xaml but that video still doesn't play. Why? Is it necessery to add something else? 
Please help me resolve this problem.

---
#### Feedback Bot on 9/3/2020, 06:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Has been some time already since the feedback ticket was opened on the portal, and asked the author again for input on this issue. I will close this for now, can be reopened whenever we get a response and discuss
