### ISSUE TITLE
The sample file you shared doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/XamarinCommunityToolkit#320]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1173129/the-sample-file-you-shared-doesnt-work.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
The file you shared here https://docs.microsoft.com/pl-pl/samples/xamarin/xamarin-forms-samples/userinterface-mediaelementdemos/  doesn't work. There is a problem visible in the attachment. How to fix that? Or can you send me a file that works?

---
#### Feedback Bot on 9/4/2020, 01:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Haven't heard anything back in 14+ days, so closing this one for now.
