### ISSUE TITLE
[Bug] Xamarin Community Toolkit NuGet is unlisted

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#328]
I just updated to Xamarin.Forms 5 pre-1 and was using the expander component. The release notes say it has been moved to the Xamarin Community Toolkit. However, the NuGet pre-release link referenced from the Toolkit's page, https://www.nuget.org/packages/Microsoft.Toolkit.Xamarin.Forms, says that packages are unlisted.
Could this be fixed so I can test Xamarin.Forms 5?

Thanks.

**Comment by AndreiMisiukevich** [comment]
@bmacombe @Tommigun1980 is this ticket completed?

**Comment by bmacombe** [comment]
Yes
