### ISSUE TITLE
[Bug] MediaElement playback controls (paper cut)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/XamarinCommunityToolkit#331]
### Description

By default, the `ShowsPlaybackControls` property on `MediaElement`, which determines whether the platforms playback controls are displayed, is `false`.

I'd suggest it should default to `true`, as it seems that having playback controls by default should be the correct user experience.

**Comment by jfversluis** [comment]
I think this makes sense, marked it as a good first issue for newcomers since Hacktober is coming up and the change shouldn't be too hard

**Comment by ionixjunior** [comment]
I'd like to work on that.

**Comment by AndreiMisiukevich** [comment]
> I'd like to work on that.

Perfect :) Looking forward to reviewing a PR

**Comment by jfversluis** [comment]
Weirdly enough this issue wasn't closed when the PR was merged. Thanks for your efforts @ionixjunior !
