### ISSUE TITLE
[Enhancement] TopMenu | Bottom Menu

### ISSUE THREAD

**Issue by roughiain** [xamarin/XamarinCommunityToolkit#366]
## Summary

Enhance side menu to be able to slide from any side of the screen.

## API Changes

Rename side menu to Menu or MenuDrawer

```csharp

public enum MenuDrawerPosition
	{
		LeftMenu = 0,
		TopMenu,
		RightMenu,
                BottomMenu,
	}
````

## Intended Use Case
Having a top/bottom menu is  useful when using devices in horizontal orientation

## Who Will Do The Work?

- [x ] Just putting this out there for someone to pick up

**Comment by Hackavist** [comment]
Can you please explain more maybe with an image or a gif

**Comment by IainCoSource** [comment]
I'm terrible at images. If you have ever worked with the Telerik side drawer, you can set which of the 4 sides you want the drawer to slide from.  Here is a gif of sorts showing an ios top drawer https://iosexample.com/content/images/2019/07/TopDrawerx.gif

**Comment by rougiain** [comment]
I'm terrible at images. If you have ever worked with the Telerik side drawer, you can set which of the 4 sides you want the drawer to slide from. Here is a gif of sorts showing an ios top drawer https://iosexample.com/content/images/2019/07/TopDrawerx.gif

**Comment by ahoefling** [comment]
Thank you @rougiain for suggesting this issue. I really like it and think it could have a lot of value. I personally find this very similar to #362. They differ enough where I could be convinced either way to have them separate or not.

Currently there is a specification for a Popup Control #292. We are waiting for XCT to support Xamarin.Forms 5.0.0 which will allow the merging of the code which is already done. Using the implementation of the popup control I have solved very similar problems by rendering the popup to meet the desired TopMenu as suggested.  

I think it makes the most sense to wait until the Popup Control is merged and then we can implement a composite control to solve this problem. This will give us high code sharing and only 1 native control to handle popups throughout the XCT.

**Comment by Cfun1** [comment]
This issue needs the Label "needs-approval" if it has not yet been approved. (probably was opened using the old GitHub feature-request template)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
