### ISSUE TITLE
[Bug] XCT doesn't build in release mode for iOS - MediaSource/MediaCapturedEventArgs linking fails

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#367]
### Description

Xamarin.Forms 5-pre1 is announcing XCT as an upgrade path for certain features that were present in Xamarin.Forms 4. Unfortunately the following error happens when building release builds for iOS:

`/Users/myname/Projects/myproject/MyApp.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'Xamarin.Forms.MediaSource', referenced from the method 'System.Void Xamarin.CommunityToolkit.UI.Views.MediaCapturedEventArgs::.ctor(System.String,System.Byte[])' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (MyApp.iOS)`

I reported this issue at https://github.com/xamarin/Xamarin.Forms/issues/12224#issuecomment-702812225 and was told that there's a pending pull request to fix this in XCT.

When will this pull request be merged and a new package released? As this blocks proper release builds until it is in I'd urge to ship one soon, as it also prevents proper testing of Xamarin.Forms 5 preview releases.

PS. I'm not using media source at all so it's not related to my code, should happen with a vanilla project.
PS 2. There is also an XCT AOT error that I think is related to this, which I reported here: https://github.com/xamarin/XamarinCommunityToolkit/issues/368.

Thanks.

### Steps to Reproduce

1. Add the latest XCT NuGet to a Xamarin.Forms 5 project.
2. Build for iOS in release mode, with target set to "| iPhone" (don't use "| iPhoneSimulator").
3. The above build error prevents the build from succeeding.

### Expected Behavior

iOS release builds should finish successfully.

### Actual Behavior

iOS release builds fail with the above error.

### Basic Information

- Version with issue: 1.0.0-pre3
- IDE: VS For Mac 8.7.8 build 4F
- Nuget Packages: Xamarin.Forms 5-pre1

### Workaround
Project Options -> iOS Build -> Set 'Linker behaviour' to 'Don't link'.

**Comment by pictos** [comment]
I can confirm the issue

![image](https://user-images.githubusercontent.com/20712372/95018629-58efa380-0637-11eb-9e5c-7b3ed61430be.png)

**Comment by pictos** [comment]
I'm on it

**Comment by Tommigun1980** [comment]
Hi guys. Any idea when https://github.com/xamarin/XamarinCommunityToolkit/issues/367 and https://github.com/xamarin/XamarinCommunityToolkit/issues/368 will be in a release so that XCT is Xamarin.Forms 5 compatible? Considering that XCT is *the* upgrade path for Xamarin.Forms 5 I think this is something that should make its way into a release ASAP. Thanks.

**Comment by Tommigun1980** [comment]
Hi. I tested XCT's latest bleeding edge version and this issue seems fixed! Thanks a lot.
