### ISSUE TITLE
[Enhancement] DateTimePicker

### ISSUE THREAD

**Issue by Softtinn** [xamarin/XamarinCommunityToolkit#375]
## Summary

We should have a control combining both the DatePicker and the TimePicker where we can pick both the date and the time.
I haven't seen any existing implementation for this control in Xamarin.Forms yet. 

Something like the picture below:
![image](https://user-images.githubusercontent.com/7129814/95135323-82f2b400-0764-11eb-842b-c63de71d7e86.png)

## Intended Use Case
A common use case is to pick a complete DateTime and not just the Date or the TimeSpan.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
This issue needs the Label "needs-approval" if it has not been approved yet. (probably was opened using the old GitHub feature-request template)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
