### ISSUE TITLE
[Enhancement] Range slider additions

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#376]
## Summary

So far I have been using https://github.com/halkar/xamarin-range-slider as range slider, but wouldn't mind migrating to the one in XCT.

1) Missing bindable properties:

I couldn't find the equivalence for the following properties that prevent me from migrating yet; maybe there's something similar in the component and I just missed it, but here goes:

StepValue: Minimum step value when the slider is scrubbed.

2) Editing step position in step changed callback is ignored:

The following use case doesn't work with XCT's range slider:
"When slider is scrubbed, detect in what range the change is, and possibly edit the value in the callback".

The reason for this is a range slider that has different granularities, say the leftmost part is for values 1-20, after 20 every 'tick' increments 5, and after 50 every 'tick' increments 10.

My code for this, which works with https://github.com/halkar/xamarin-range-slider, is:

```c#
private void SomeSlider_ValueChanged(object sender, ValueChangedEventArgs e)
{
    var stepValue = e.NewValue < 15 ? 1 : (e.NewValue < 50 ? 5 : 10);

    var newStep = Math.Round(e.NewValue / stepValue);
    var newValue = newStep * stepValue;
    if (newValue != this.maxDistanceSlider.Value)
        this.someSlider.Value = newValue;
}
```

So TLDR: In my use case I have set step value to 1, and then in the value changed callback modify the value further depending on where it ends up in the range, but this doesn't work with XCT's range slider (modifying the value in the callback seems to do nothing). The effect should be that when scrubbing the higher ranges the knob moves larger distances at a time.

3) Look of the control (Minor):

The range slider component doesn't look native at least on iOS (didn't test it on Android), as it doesn't have a shadow under the thumb as regular sliders do. It would be a great addition to add it for a more native look.

Alternatively, https://github.com/halkar/xamarin-range-slider uses native iOS and Android components behind the scenes. Shouldn’t native controls be preferred whenever possible instead of implementing them manually, as they will follow OS styling and behavior to a tee?

Thanks.

**Comment by Tommigun1980** [comment]
Is #2 actually a bug?

**Comment by Tommigun1980** [comment]
Hi. If you guys think that number 2 is a bug I'd be happy to move it to a bug report, but would prefer confirmation on it being a bug first.

Thanks!

**Comment by AndreiMisiukevich** [comment]
3) Definitely, native controls are preferable over cross-platform solutions
if @halkar agrees to contribute his controls, I think everyone will be happy

**Comment by AndreiMisiukevich** [comment]
1. StepValue: Minimum step value when the slider is scrubbed.
This property is not implemented yet. Can be a good enhancement

**Comment by AndreiMisiukevich** [comment]
2. Could you specify what event do you use in XCT RangeSlider? (seems there is no any event there)

**Comment by Tommigun1980** [comment]
1) Oh I see. My use case is to set it to 1. When I tested the control and scrubbed it, I got values like 1.223323, 2.3424234 etc (with a range of 15 to 80). I'd at least like the value to be an integer and not a floating number. The values displayed on the right side of the control took up almost the entire horizontal space as it showed so many decimals, not to mention that when the user should pick integers and it shows decimal numbers it just doesn't work. Looking forward to this as I think this is a mandatory addition.

2) I can't actually remember. It is possible I forgot to actually bind the event when testing XCT's range slider. Now looking at the code I can't find a command or event for it either, which can explain why it didn't work :P Well, in that case another absolutely mandatory addition is the ability to subscribe to position changed events.

3) I understand, but on platforms where there is a native component (as is Android in this case) shouldn't it use the native control there, and a managed control on other platforms?

Thanks!

**Comment by Tommigun1980** [comment]
Once a configurable step value (and support for integer steps) has been implemented, along with the necessary events, I am very much looking forward to using this component and think it's a really nice addition!

**Comment by AndreiMisiukevich** [comment]
1. ValueLabelStringFormat. You can try to play with this property to show only integers

**Comment by AndreiMisiukevich** [comment]
2. Actually you can do it now :) PropertyChanged event. But I agree that it makes sense to expose a separate event for it

**Comment by Tommigun1980** [comment]
1) I see, thanks! That should fulfil my use case, albeit i still think there should be a value for step length (I just happen to use 1 in my case).

2) Thanks for that too. I'll give it a try, but yeah I think separate events for these kinds of things make a lot of sense.

**Comment by halkar** [comment]
I'm happy to give the component to XCT if they are interested.

**Comment by AndreiMisiukevich** [comment]
> I'm happy to give the component to XCT if they are interested.

They are highly interested, I guess :) CC @jfversluis

**Comment by jfversluis** [comment]
Definitely! Can we integrate this with what's already here now?

**Comment by AndreiMisiukevich** [comment]
> Definitely! Can we integrate this with what's already here now?

I think yes, but my impl can be enabled for Tizen / WPF / GTK and optionally for all platforms (maybe we can add a property for managing whether we should use native look or cross-plat)

**Comment by Tommigun1980** [comment]
I always think that the best option is to use a native control whenever one is available, and a cross-platform version on platforms where one does not exist. This ensures look and feel parity with other UI components on platforms where a native control exists.

So imho, and this is just imho, the best course of action in this case would be to:
1) Keep the existing control and focus on making it as robust as possible (including exposing events for data changing and step value, to reach feature parity with @halkar's control - there may be more but those I think are most important).
2) Then copy over whatever native code can be taken from @halkar's control and use it on supported platforms (iirc iOS and Android).

**Comment by Tommigun1980** [comment]
@AndreiMisiukevich Thank you for the additions! It works absolutely flawlessly and I started using it in my project. It really is a solid component so thank you so much for it.

The only other enhancement idea I have is to use the native component on Android as one exists there, but the current one looks very very close to it already.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich Thank you for the additions! It works absolutely flawlessly and I started using it in my project. It really is a solid component so thank you so much for it.
> 
> The only other enhancement idea I have is to use the native component on Android as one exists there, but the current one looks very very close to it already.

Thank you :)
I've created a ticket for adding "ShadowEffect". Once the shadow effect is done, we will be able to add it to RangeSlider's thumbs. So they will look more attractively 👍
