### ISSUE TITLE
[Enhancement] Snackbar additions

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#377]
## Summary

I am really looking forward to a flexible snackbar component in XCT. I gave it a quick spin but couldn't find any way to:

1) Set styling in a single place. I would like to set the styling for all snackbars (colors, fonts, default durations etc.) in one place. In fact outside of duration I couldn't find where to theme it at all, but I didn't really look too hard.

2) Couldn't find where to define placement (top, bottom etc.) and appearing direction and/or effect (fade in/out etc). But I didn't look too hard either.

3) More than one action. Sometimes you need more than one action, but the snackbar component only seems to allow adding one action.

4) Swipe to dismiss: Considering it seemed a little too bare bones to use atm I never tested my code with it, but swipe to dismiss is something users will expect. Is it supported? If not one will be forced to add a 'Close' action, which then will eat up the only action it allows right now.

5) This would be really really nice: Ability to add an image.

Thanks.

**Comment by VladislavAntonyuk** [comment]
SnackBarOptions Interface
actionText: string
actionTextColor: string
snackText: string
hideDelay: number
textColor: string
backgroundColor: string
maxLines: number
isRTL: boolean

**Comment by VladislavAntonyuk** [comment]
I can implement this one.
 as for the summary requests.
1. Agree
2-5. if we are talking about native implementation (Snackbar on android), I haven't seen it allows to define placement. Needs more discussion/investigation. For other platforms it is possible

**Comment by Tommigun1980** [comment]
Great. thanks @VladislavAntonyuk.

I noticed a SnackbarAppearance property exists in IOSSnackBar, but it looks to me it's iOS only and using it would require one to use platform dependent code. Is that the way to go right now until styling is implemented?

**Comment by Tommigun1980** [comment]
> SnackBarOptions Interface
> message: MessageOptoins
> action: IEnumerable
> duration: number
> backgroundColor: string
> isRTL: boolean
> 
> MessageOptions Interface
> message: string
> font: Font
> fontSize: double
> color: Color
> 
> ActionOptions Interface
> action: Func
> text: string
> font: Font
> fontSize: double
> color: Color
> 
> @jfversluis , @AndreiMisiukevich please review

If possible I'd prefer it these could be set once (possibly with the option to also provide them when creating an instance). The reason is that I'd like to set the theme once in my app, instead of sending them in everywhere.

**Comment by AndreiMisiukevich** [comment]
> SnackBarOptions Interface
> message: MessageOptoins
> action: IEnumerable
> duration: number
> backgroundColor: string
> isRTL: boolean
> 
> MessageOptions Interface
> message: string
> font: Font
> fontSize: double
> color: Color
> 
> ActionOptions Interface
> action: Func
> text: string
> font: Font
> fontSize: double
> color: Color
> 
> @jfversluis , @AndreiMisiukevich please review

Sounds good) Only one question: do you think that's better to split configuration around 3 separate interfaces? Or maybe we can consider putting all "UI configuration" inside single class?

**Comment by VladislavAntonyuk** [comment]
> Great. thanks @VladislavAntonyuk.
> 
> I noticed a SnackbarAppearance property exists in IOSSnackBar, but it looks to me it's iOS only and using it would require one to use platform dependent code. Is that the way to go right now until styling is implemented?

That code is for internal usage only. With the first implementation I decided to implement only SanckBar without any styling. I didn’t try, but it would interesting to know if it’s react to theme changes. Because it uses label and button, most likely you already have styles for the controls in your resource dictionary.

**Comment by VladislavAntonyuk** [comment]
> > SnackBarOptions Interface
> > message: MessageOptoins
> > action: IEnumerable
> > duration: number
> > backgroundColor: string
> > isRTL: boolean
> > MessageOptions Interface
> > message: string
> > font: Font
> > fontSize: double
> > color: Color
> > ActionOptions Interface
> > action: Func
> > text: string
> > font: Font
> > fontSize: double
> > color: Color
> > @jfversluis , @AndreiMisiukevich please review
> 
> Sounds good) Only one question: do you think that's better to split configuration around 3 separate interfaces? Or maybe we can consider putting all "UI configuration" inside single class?

I would like to keep the class simple. Also having similar options in the same class (messageColor, actionColor, actionBackgroundColor, snackbarBackgroundColor etc) can make the class complicated.

**Comment by AndreiMisiukevich** [comment]
> > > SnackBarOptions Interface
> > > message: MessageOptoins
> > > action: IEnumerable
> > > duration: number
> > > backgroundColor: string
> > > isRTL: boolean
> > > MessageOptions Interface
> > > message: string
> > > font: Font
> > > fontSize: double
> > > color: Color
> > > ActionOptions Interface
> > > action: Func
> > > text: string
> > > font: Font
> > > fontSize: double
> > > color: Color
> > > @jfversluis , @AndreiMisiukevich please review
> > 
> > 
> > Sounds good) Only one question: do you think that's better to split configuration around 3 separate interfaces? Or maybe we can consider putting all "UI configuration" inside single class?
> 
> I would like to keep the class simple. Also having similar options in the same class (messageColor, actionColor, actionBackgroundColor, snackbarBackgroundColor etc) can make the class complicated.

Well, then let's try with your approach) 👍
