### ISSUE TITLE
[Bug] Can't get safe area to work

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#379]
Hi.

I tried using the safe area but I can't seem to get it to work.

There's no documentation or samples for it, but it seems to me like you should just add the effect to whatever view and it should do its thing. So I did the following:

```xaml
    xmlns:xcteffects="clr-namespace:Xamarin.CommunityToolkit.Effects;assembly=Xamarin.CommunityToolkit"

    ...

    <ContentPage.Content>
        <StackLayout>
            <StackLayout.Effects>
                <xcteffects:SafeAreaEffectRouter />
            </StackLayout.Effects>
    ...
```

But nothing happens. Disassembling the effect with 'Visibility: All members' shows only the following:

```c#
using Xamarin.Forms;

public class SafeAreaEffectRouter : RoutingEffect
{
	public SafeAreaEffectRouter ()
		: this ("CommunityToolkit.SafeAreaEffectRouter")
	{
	}
}
```

Is it accidentally stripped, or am I doing something horribly wrong?

I tested both with the latest released version and with the latest nightly build, and am using Xamarin.Forms 5-pre1.

Thanks.

**Comment by Tommigun1980** [comment]
Can anyone else get safe area to work?

**Comment by sthewissen** [comment]
You can apply the effect using attached properties, e.g:

```
<StackLayout effects:SafeAreaEffect.SafeArea="True,False" />
```

**Comment by sthewissen** [comment]
Regarding docs and samples, we realize we are horribly behind on these since the amount of new features coming in is pretty booming. We hope to have some more of these made available soon.

**Comment by Tommigun1980** [comment]
> You can apply the effect using attached properties, e.g:
> 
> ```
> <StackLayout effects:SafeAreaEffect.SafeArea="True,False" />
> ```
> 
> You can provide 1, 2 or 4 booleans, which works similar to margins. They indicate whether or not the safe areas should be applied to:
> 
> * 1: All sides
> * 2: Horizontal, Vertical
> * 4: Left, Top, Right, Bottom

Oooh I see, thanks so much!
