### ISSUE TITLE
[Enhancement] CollectionView staggered layout

### ISSUE THREAD

**Issue by prakash-malodiya** [xamarin/XamarinCommunityToolkit#380]
We should have a control staggered grid view includes multiple columns with multiple rows of varying sizes that include infinite scrolling, empty list, refresh view etc. I haven't seen any existing implementation for this control in Xamarin.Forms yet. For example, please find below images for reference:

![image](https://user-images.githubusercontent.com/8983699/95164972-afd8b280-07c8-11eb-9b0d-93e278f86a0f.png)

![image](https://user-images.githubusercontent.com/8983699/95165032-cb43bd80-07c8-11eb-96b1-78531a1ed267.png)

Additionally, it could be possible to have some items that stretch trough the full width or height like in this scenario. 

![image](https://user-images.githubusercontent.com/8983699/95165069-e44c6e80-07c8-11eb-827e-8d267eb4d504.png)

![image](https://user-images.githubusercontent.com/8983699/95165140-06de8780-07c9-11eb-8379-d82cda42c52a.png)

**Comment by jfversluis** [comment]
Thanks for your suggestion!

I think this is something that is possible out of the box in Android, but something custom needs to be made for iOS. That is basically why it wasn't implemented into Forms directly. But happy to discuss some more on the why and how and gauge the interest with this issue :)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
