### ISSUE TITLE
[Enhancement] A button with content layout

### ISSUE THREAD

**Issue by levelfivecoder** [xamarin/XamarinCommunityToolkit#383]
## Summary

Xamarin forms Button control is limited to text and icon. Usually we used to create components with Frame or Grid if we require a to define a Button with complex template.
## API Changes

e.g.

```
<views:ContentButton Padding="2" BorderColor="Red" BackgroundColor="Gray" CornerRadius="12" IsClippedToBounds="True"  WidthRequest="200">
                <views:ContentButton.Content>
                        <StackLayout Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                            <Label Text="Test Button" TextColor="Black" HorizontalOptions="Center" VerticalOptions="Center" FontSize="Medium" />
                             <Label Text="Test subheading" TextColor="Black" HorizontalOptions="Center" VerticalOptions="Center" FontSize="Small" />
                        </StackLayout>
                </views:ContentButton.Content>
            </views:ContentButton>
```

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by IeuanWalker** [comment]
@levelfivecoder i've done something similar here - https://github.com/IeuanWalker/Xamarin.Forms.FlexButton

When I have time I was going to create a new control that would allow people to anything to the content.
You also would need to extend different controls within XF to allow the user to set different colours for different states i.e. pressed unpressed changes background and text color

**Comment by levelfivecoder** [comment]
> @levelfivecoder i've done something similar here - https://github.com/IeuanWalker/Xamarin.Forms.FlexButton
> 
> When I have time I was going to create a new control that would allow people to anything to the content.
> You also would need to extend different controls within XF to allow the user to set different colours for different states i.e. pressed unpressed changes background and text color
> 
Nice to hear that community has the requirements for the button with content

**Comment by AbuMandour** [comment]
What about if I put button in button? Which button event will fire?

**Comment by IeuanWalker** [comment]
@levelfivecoder @AndreiMisiukevich @pictos 
I know there is already a PR for this in progress (#386), just wanted to share my solution - 
https://github.com/IeuanWalker/Xamarin.Forms.StateButton

Feel free to copy stuff if you need to for the existing PR.

**Comment by IeuanWalker** [comment]
Here an example of what the control can do.
This shows the `StateButton` as the wrapper for a card. When the card is pressed or clicked then the title is set to bold and the border goes darker. 

The card also shakes when clicked, this shows that it works with the animation behaviour stuff from this NuGet.

It also shows that it works with nested TapGestureRecognizer, XF native button and nested `StateButton` - 
![2021-04-21 21-56-05](https://user-images.githubusercontent.com/6544051/115620253-da193a00-a2ec-11eb-8b1d-c3238b75803a.gif)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
