### ISSUE TITLE
[Enhancement] SegmentsView control

### ISSUE THREAD

**Issue by hnabbasi** [xamarin/XamarinCommunityToolkit#385]
## Summary

>Note: Migrating from Xamarin.Forms [Issue 6904](https://github.com/xamarin/Xamarin.Forms/issues/6904)

Have a segmented control for Xamarin.Forms. iOS has `UISegmentedControl`, but Android does not. This control will provide native looking segments for Android platform.

iOS | Android
--|--
<img src="https://raw.githubusercontent.com/hnabbasi/Segments/master/media/Segments_iOS_Text.gif"/> | <img src="https://raw.githubusercontent.com/hnabbasi/Segments/master/media/Segments%20Android%20Text.gif"/>
<img src="https://raw.githubusercontent.com/hnabbasi/Segments/master/media/Segments_iOS_Image.gif"/> |<img src="https://raw.githubusercontent.com/hnabbasi/Segments/master/media/Segments%20Android%20Image.gif" />
|| <img src="https://raw.githubusercontent.com/hnabbasi/Segments/master/media/Segments_Corner_Radius.gif" />

## API
The `SegmentsView` implements `IList<string>` with `DisplayMode` of `Text` or `Image`.

`SegmentsView`:
```csharp
class SegmentsView : View {}
```

### SegmentsView

Name | Type | Description
---|---|---
Display Mode | Enum | Display mode is `SegmentMode.Text` by default and can be set to `SegmentMode.Image` as an alternative.
Color | Xamarin.Forms.Color | Main color for the control
Items | IList\<string\> | List of string values for title or image source
ItemsSource | IList | Items source for the values
SelectedItem | object | Selected item   
SelectedIndexChanged | Event | Event handler for when a segment is selected. Raises `SelectedItemChangedEventArgs` with segment and selected index
SelectedIndex | System.Int32 | Index of selected segment

### Platform Specific - Android
Name | Type | Description
---|---|---
CornerRadius | double | Corner radius on Android ONLY

## Usage

**XAML**
```xml
<SegmentsView SelectedIndexChanged="OnSegmentSelected">
    <SegmentsView.Items>
        <x:String>View A</x:String>
        <x:String>View B</x:String>
    </SegmentsView.Items>
</SegmentsView>

<!-- Using ItemsSource -->

<SegmentsView 
    SelectedIndexChanged="OnSegmentSelected"
    ItemsSource="{Binding values}">
</SegmentsView>
```
**C#**
```csharp
var segments = new SegmentView
    {
        Children = new List<string>
        {
            "View A",
            "View B",
            "View C"
        }
    };
segments.SelectedIndexChanged += OnSegmentSelected;

// handler
void OnSegmentSelected(object sender, SelectedItemChangedEventArgs e){ }
```

### iOS
On iOS, this is simply a `UISegmentedControl`.

### Android
On Android, this is be a `RadioGroup` with a custom `RadioButton` that renders a simple text or bitmap drawable in image mode.

```csharp
class FormsSegmentsView : Android.Widget.RadioGroup
```

### UWP
👀 TBD 

## Who Will Do The Work?

- [x] I have already worked on this and migrating from Xamarin.Forms core per Xamarin team's request
- [ ] Just putting this out there for someone to pick up

Enjoy! 👍

**Comment by jBijsterboschNL** [comment]
This would be a great addition to the XCT! @hnabbasi , could you also add something like a DisplayValueConverter? So we could potentially provide any kind of object in the ItemsSource and let this converter define the text value or image source value for each segment? If I could be of any assistance, please let me know 😊👌

**Comment by hnabbasi** [comment]
> This would be a great addition to the XCT! @hnabbasi , could you also add something like a DisplayValueConverter? So we could potentially provide any kind of object in the ItemsSource and let this converter define the text value or image source value for each segment? If I could be of any assistance, please let me know 😊👌

Good one. I have a private `Display` property that I can expose and use for that purpose. Just like the **Picker** does.

**Comment by jBijsterboschNL** [comment]
Exactly! That would be awesome! Thanks

**Comment by hnabbasi** [comment]
Hey @jfversluis @PureWeen,

So, in Xamarin.Forms we had `GetNativeImageAsync()` extension to `ImageSource`. And `GetNativeImageAsync()` calls up the `IImageSourceHandler`'s `LoadImageAsync()` on all possible sources. 

https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Platform.iOS/Renderers/ImageElementManager.cs#L264

I have a need for that handy extension for this control and I am wondering if I should recreate that whole suite of classes so future controls can also use the `GetNativeImageAsync()` or is there a way we can expose that in `Xamarin.Forms.Internals` so I can just reuse that? Thoughts

**Comment by haavamoa** [comment]
This would be awesome! 👌

**Comment by hnabbasi** [comment]
> This would be awesome! 👌Only thing I don't like with the android version is that it misses animations when you change items :(

Good point 🤔. Maybe I can work on it after I am done migrating over the Android version.

**Comment by Cfun1** [comment]
@pictos  This issue needs the Label "in-progress".

**Comment by hnabbasi** [comment]
Hello world! I finally got back to this. I am making some changes to the API and will close the PR currently open in favor of a new one, when ready. I have added `Normal Text Color` and `Selected Text Color` to both iOS and Android. Currently running in to Background Color issue on Android that I am working on.

Stay tuned.

**Comment by GUOLDEV** [comment]
@hnabbasi very nice! I cannot wait to use it in my next project.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Comment by brminnick** [comment]
Reopening because it looks like this was approved and a PR was opened before the new feature deadline

**Comment by pictos** [comment]
Closing this one. If anyone wants this feature please open a proposal in MCT

**Comment by GUOLDEV** [comment]
> Reopening because it looks like this was approved and a PR was opened before the new feature deadline

Hi @brminnick , @pictos closed this PR again, it would be great to have it in XCT 🙏

**Comment by hnabbasi** [comment]
I will resume working on this for MAUI. Please leave it open if possible 🙏

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bijington** [comment]
@hnabbasi it would be great if this made it to the MAUI toolkit but if you are planning on implementing this for the MAUI toolkit that will need to be done in another repo as mentioned by @brminnick here:

> Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).
> 
> Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.
> 
> I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
