### ISSUE TITLE
[Enhancement] Extend UserHasStoppedTypingBehavior with a minimum text length property

### ISSUE THREAD

**Issue by jBijsterboschNL** [xamarin/XamarinCommunityToolkit#387]
## Summary

The UserHasStoppedTypingBehavior executes a command when the user has stopped typing (or at least the configured threshold time has passed). I would like this behavior to also support a minimum text length before this command gets executed.

## API Changes

The UserHasStoppedTypingBehavior gets an extra property: MinimumTextLength of type int.

## Intended Use Case
In the case that you don't want to start searching when the user has only typed less then x characters. F.e. the minimum text length is set to 5 and the user has stopped typing after 3 characters, the command shouldn't get executed. Also the Keyboard shouldn't get dismissed in this case, so the user can easily continue his typing.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Excellent idea!
