### ISSUE TITLE
[Enhancement] Implement MaxLengthReachedBehavior

### ISSUE THREAD

**Issue by jBijsterboschNL** [xamarin/XamarinCommunityToolkit#388]
## Summary

I would like to have a behavior that executes a certain command (or invokes a certain event handler) when the max length of an entry field has been reached.

## API Changes

Create a new MaxLengthReachedBehavior with the following properties:

- Command: of type ICommand. This will get executed when the MaxLength of the Text property of the attached Entry field has been reached.
- MaxLengthReachedEvent: of type eventhandler. This will get invoked when the MaxLength of the Text property of the attached Entry field has been reached.
- AutoDismissKeyboard: of type boolean. Default value is true. When the commands get executes, the keyboard will be dismissed (or not).

## Intended Use Case
If your user needs to type in a certain code to verify 'something' which always contains x number of characters, I would like to automatically execute a certain command without the user having to click a button to continue.

If your user has to type in his date of birth and we use the nice MaskBehavior (which is also available in the XCT!), we could invoke a certain event handler which could set the focus of the next entry field on our form, so our user can quickly continue filling out the entire form without having to click on the next entry field manually to start typing.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Hackavist** [comment]
I would like to implement this

**Comment by AndreiMisiukevich** [comment]
> I would like to implement this if it is okay with @jBijsterboschNL

I guess @jBijsterboschNL checked "I am willing to take this on myself". So... let's see what he will say about it :)

**Comment by jBijsterboschNL** [comment]
I already started working on this :)

**Comment by Hackavist** [comment]
It is perfectly fine best of luck mate 🙏🏼🙌🏼
