### ISSUE TITLE
[Enhancement] Please add Xamarin University Infrastructure Library to XCT

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#390]
Hi.

Xamarin University Infrastructure Library has some highly useful collections (https://github.com/xamarinhq/xamu-infrastructure/tree/598f97d6f5cc68fc603873e913ccc9089dbc60df/src/XamU.Core/Collections) whereof I use OptimizedObservableCollection (https://github.com/xamarinhq/xamu-infrastructure/blob/598f97d6f5cc68fc603873e913ccc9089dbc60df/src/XamU.Core/Collections/OptimizedObservableCollection.cs) extensively.

I think these would be perfect in XCT. There may be other useful things in there as well but I have personally only used OptimizedObservableCollection.

Thanks.

**Comment by Tommigun1980** [comment]
Hi guys! I was wondering if anyone else was using the collections from https://github.com/xamarinhq/xamu-infrastructure/tree/598f97d6f5cc68fc603873e913ccc9089dbc60df/src/XamU.Core/Collections?

I think they would totally be a great fit with XCT, are made by Microsoft and are under the MIT license.

**Comment by Cfun1** [comment]
This issue needs the Label "needs-approval" if it has not been approved yet. (probably was opened using the old GitHub feature-request template).

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
