### ISSUE TITLE
[Bug] Media Element skipping part of a media file.

### ISSUE THREAD

**Issue by musictopia2** [xamarin/XamarinCommunityToolkit#396]
### Description
I have a simple app with a button that when I click, I expect to skip 30 seconds ahead.
Code is something like this.
 private void Button_Clicked(object sender, EventArgs e)
        {
            Media.Position = new TimeSpan(0, 0, 30);
        }

However, no matter what I tried, it won't skip 30 seconds ahead.  Ideally should be able to set it before even playing a file for cases where somebody wants to autoresume a video for example.

### Steps to Reproduce

1. Click the button to skip 30 seconds.

### Expected Behavior
should skip 30 seconds.

### Actual Behavior
nothing happens.

The platform i am using is android.

**Comment by jamsoft** [comment]
I'm seeing exactly this issue too. In fact everything I've needed to do or tried with this control has failed to the point where I'm looking for an alternative.

**Comment by peterfoot** [comment]
Can you share the sequence of steps you are using with Xamarin forms and those with the Android native media player? Trying to setup a repro scenario

**Comment by jfversluis** [comment]
No reproduction provided and it's been a year, let's close this for now unless someone can provide us with some new info.
