### ISSUE TITLE
On Android emulator, MediaElement (preview), the Volume is only taken into account when set after Media has been started

### ISSUE THREAD

**Issue by EricOuellet2** [xamarin/XamarinCommunityToolkit#398]
### Description
On Xamarin Forms 4.5 using the new MediaElement. Tests done on the emulator only for the moment.
It seems that the Volume is not applied until the media has started. In fact, it seems that any changes on Volume is only taken into account when the media has already been really started. 

Either the following code does not fix the problem (looks like the media as not been really started and the volume seems to not been taken into account)
:

<MediaElement x:Name="MyMediaElement" Volume=".1" MediaOpened="MyMediaElementMediaOpened" ></MediaElement>

       // This is a patch because it seems that the volume is not taken into account if the media is not yet started on Android.
        private void MyMediaElementMediaOpened(object sender, EventArgs e)
        {
            // EO: Does not seems to fix the audio delay problem. Will remove temporarily and will try to see if it happen on a real device.
            if (MyMediaElement.CurrentState == MediaElementState.Opening || MyMediaElement.CurrentState == MediaElementState.Playing)
            {
                MyMediaElement.Volume = .1;
            }
        }

### Steps to Reproduce

1.  Create in page:  <MediaElement x:Name="MyMediaElement" Volume=".1" MediaOpened="MyMediaElementMediaOpened" ></MediaElement>
2. Open the page and see the Volume will be at maximum.
3. Bug appears at least on Android Emulator. Perhaps everywhere?

### Expected Behavior
Volume level (Property "MediaElement.Volume") taken into account at start. Volume level should be set before openning the media... 

### Actual Behavior
Volume always start to maximum

### Basic Information

- Version with issue: Xamarin Forms 4.5
- Last known good version: ??
- IDE: VS2019 16.5.4 (4.8.03752)
- Platform Target Frameworks: 
  - iOS:  Not yet tested on iOS
  - Android: 9.0 (Pie)
  - UWP:  Not yes tested
- Android Support Library Version: ???
- Nuget Packages: Xamarin Essentials 1.5.2 and Xamarin.Forms 4.5.0.617
- Affected Devices: Android (at least)

### Reproduction Link

See previous comments

### Workaround

None yet found

**Comment by jfversluis** [comment]
See the linked issue above for a reproduction
