### ISSUE TITLE
[Bug] MediaElement never reach Opening state

### ISSUE THREAD

**Issue by EricOuellet2** [xamarin/XamarinCommunityToolkit#406]
### Description
MediaOpened event does not occurs on "media started". The state is never in "Opening" of "Playing"

### Steps to Reproduce

1. Play a media
2. 
3. 

### Expected Behavior
Reach state : MediaElementState.Opening or MediaElementState.Playing when we start a media (ex: mp3.

### Actual Behavior
Never reach states: MediaElementState.Opening or MediaElementState.Playing

### Basic Information

- Version with issue: 4.5
- Last known good version: None
- IDE: vs2019 latest
- Platform Target Frameworks: Android
  - iOS:  No
  - Android: Emulator
  - UWP:  No
- Android Support Library Version: ?
- Nuget Packages: Xamarin.Essentials (1.5.2), Xamarin.Forms (4.5.0.617)
- Affected Devices: Emulator

### Screenshots

None

### Reproduction Link

None

### Workaround
None

**Comment by peterfoot** [comment]
I think this may be related to the Metadata bug I've recorded in #666

**Comment by jfversluis** [comment]
As Peter mentioned I think this is fixed. Tried the reproduction and I see Opening and Playing. Please try the current Toolkit version, if you think otherwise please open a new issue. Thanks!
