### ISSUE TITLE
[Bug] MediaElement Position polling paper cut

### ISSUE THREAD

**Issue by davidbritch** [xamarin/XamarinCommunityToolkit#411]
### Description

The `MediaElement.Position` property must be polled to get its value for display. I realise this is to avoid the property change notifications that might need to fire every 100ms. 

However, it does seem likely that some users will automatically try binding to `Position` and expect it work, and then will have to seek out an answer as to why it's not working.

Just wondering if there's anything that can be done about this to satisfy users who will want to bind to `Position`, without making a performance compromise that will hurt everyone.

**Comment by jfversluis** [comment]
I think this should be fixed by #381

**Comment by sthewissen** [comment]
Could we easily verify that this bug is fixed by the referenced PR?

**Comment by peterfoot** [comment]
@sthewissen yes, the whole point of that PR was to make the property bindable for this exact scenario

**Comment by jfversluis** [comment]
Let's assume this is fixed then :D
