### ISSUE TITLE
[Bug] Exiting full screen of MediaElement calls MainPage's OnAppearing() method

### ISSUE THREAD

**Issue by nhinze** [xamarin/XamarinCommunityToolkit#413]
### Description
The MainPage OnAppearing() method is called when exiting full screen of MediaElement. This creates issues when using dynamic logic for MasterDetailPages or Tabbedpages.

Is it expected that exiting fullscreen on MediaElement would call MainPage OnAppearing() method?

### Steps to Reproduce

1. Download attached project
2. Launch project into iOS Simulator
3. Tap "First Item"
4. Make MediaElement full screen.
5. Place break on line 29 in MainPage.cs
6. Exit MediaElement full screen. Code will stop in MainPage's OnAppearing().

### Expected Behavior
Exiting fullscreen on MediaElement should not call MainPage OnAppearing() method

### Actual Behavior
Exiting fullscreen on MediaElement calls MainPage OnAppearing() method

### Basic Information

- Version with issue: Latest Xamarimn.Forms 4.5.0.495
- Last known good version:
- IDE: VS 2019 Mac
- Platform Target Frameworks:
  - iOS: 13.4

### Reproduction Link

[MediaElementTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4415889/MediaElementTest.zip)

**Comment by sthewissen** [comment]
As the `MainPage` goes from not visible to visible I would personally expect the `Appearing` event to be triggered.

**Comment by nhinze** [comment]
Shouldn't it call the `Appearing` event of the open TapPage instead? I have since then upgraded to AppShell and it has fixed this issue.

**Comment by sthewissen** [comment]
I'm not sure if that is actually fixing your issue, or if an open bug in Shell is causing it to work as you expected:

https://github.com/xamarin/xamarin.forms/issues/6486

**Comment by nhinze** [comment]
I guess I'm missing some fundamentals on how to deal with a user exiting full-screen mode. I expected it to behave in a similar fashion as when one hits the back button to return to a previous page on the stack. What am I missing?

**Comment by jfversluis** [comment]
To be fair I find it kind of making sense like Steven mentions. In addition, but this is mostly personal taste I guess, I don't think executing logic that makes up that kind of UI should be in the OnAppearing (or similar). For now I'm closing this one.
