### ISSUE TITLE
[Bug][Android] MediaElement custom position bar doesn't work

### ISSUE THREAD

**Issue by davidbritch** [xamarin/XamarinCommunityToolkit#417]
### Description

On the `MediaElement` control on Android, my custom position bar doesn't work. However, it does work on iOS.

This is all because setting `MediaElement.Position` on Android doesn't actually update the `Position` value. I confirmed this with the following code:

```
// Set position to 1 min
mediaElement.Position = new TimeSpan(0,1,0);
```

The `Position` property doesn't change after running this code on Android.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the last page in the list (Custom Position Bar).
3. Play the video.
4. Drag the slider to later in the video.

### Expected Behavior

Slider is draggable and the video plays from the new seek point.

### Actual Behavior

Slider is draggable but the video keeps on playing from the beginning.

### Basic Information

- Version with issue: 4.5-pre4
- IDE: VS Mac 8.4.5
- Platform Target Frameworks: 
  - Android: API 28

### Reproduction Link

[WorkingWithMediaElement.zip](https://github.com/xamarin/Xamarin.Forms/files/4219419/WorkingWithMediaElement.zip)

**Comment by jfversluis** [comment]
I think this might be fixed by #381

**Comment by sthewissen** [comment]
Could we easily verify that this bug is fixed by the referenced PR?

**Comment by jamsoft** [comment]
I'm seeing this issue on Android on all the latest versions of XF and the Toolkit.

**Comment by peterfoot** [comment]
The reference PR re-wrote how Position is handled. However there is an outstanding issue where you can't seek increments smaller than 300ms. Another user was investigating whether this limitation is still required with the new implementation.

**Comment by jfversluis** [comment]
Then I'm ruling this one as done and we'll have the other one for the <300ms to investigate that. If this is not correct to anyone in here let me know and I will reopen it

**Comment by greg84** [comment]
I'm setting `Position` in the `MediaOpened` event and it doesn't work on Android. Video just plays from the beginning. This should be re-opened.
