### ISSUE TITLE
Improved ListView

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/XamarinCommunityToolkit#42]
## Feature Request:

The `ListView` is a central control in almost any XF app.
Yet it lacks some very basic functionality, especially now the XF is supposed to target not only mobile screens but also tablets and bigger screens.

So here are some of the things I'd like to see implemented in the `ListView` control:

- Horizontal Orientation
- Repeater functionality, e.g. non-selectable `ListView` (`ItemsControl`)
- Better sizing options (size to content is a pain ITA!, especially inside a `StackLayout`)
- Customizable scrollbars (`IsEnabled` etc.)
- Why Cells? Why not a plain object and `ContentView` like WPF's `ContentControl` to enable templating of a single item within or without a `ListView`
`Grid.IsSharedSizeGroup` to allow sharing a grid between cells, and size all cells in a column/row to `Auto`/`*` as set in the `ColumnDefinition`/`RowDefinition`

In general, it looks like the XF team is mostly Android/iOS oriented, while I believe that as a XAML based technology it can still improve to achieve WPF/UWP functionality.

**Comment by Depechie** [comment]
Hey @weitzhandler sorry for the long non communication... seems we had big goals up front, but can currently only manage a smaller part of the toolkit. Hence our not so big focus on controls as of yet.

I would still like to keep these issues open on the Toolkit, because they give insight on what people think is still missing from current standard XF controls set.
Of course PR's to try to solve this are also welcome, only not 100% sure we can manage them just yet.

**Comment by rogihee** [comment]
Good ideas, the idea of ContentViews as Cell is already on the Forms radar. If you search for RepeaterView then you should be a able to find some examples, there are examples on the forum.

**Comment by weitzhandler** [comment]
Examples online are not enough. We need something official. Like the UWP or
WPF toolkit.

**Comment by bartlannoeye** [comment]
Hey @weitzhandler, that was our initial plan, build a good looking (and helpful) sample application to put in all stores. However the few of us that kicked of this initiative are also very busy in several other projects. We do have a sample application in the repo to help people out for now. The real demo application is still on our mind, but not something that's set to be released on short term without external input.

**Comment by weitzhandler** [comment]
@bartlannoeye 
The truth is that I'm not after a sample app. We just need more controls. XF's control set is very limited. Essential controls are lacking, such as the one this post was opened for, among `RadioButton`, `CheckBox` etc. XF also has a very limited set of events and is very mobile-biased, and because of the 'lowest common' agenda. For instance implementing keyboard shortcuts, collecting mouse clicks, is nightmare.

**Comment by pauldipietro** [comment]
As part of getting this project in order, I think this is something I want to close for the time being. It's recently been publicly stated (see part of a comment by Jason [here](https://github.com/xamarin/Xamarin.Forms/issues/2415#issuecomment-381281513), at the end) that we plan for a `"ListView2"` that would make improvements like ditching `Cell`/`ViewCell`. Making changes to the current `ListView` doesn't make a ton of sense. Depending on various factors, enhancements to that future implementation (such as behaviors/effects, etc.) can be made.
