### ISSUE TITLE
[Bug] [Expander] Expander does not resize to fit changed contents

### ISSUE THREAD

**Issue by varyamereon** [xamarin/XamarinCommunityToolkit#420]
### Description

The Expander control does not appear to resize itself when the size of it's contents are changed. Perhaps it works in other scenarios but in the scenario demonstrated in the steps it does not.

### Steps to Reproduce

1. Add an Expander
2. Set the contents to various bindable properties, some of which can be set to not visible if they are null
3. Change the bindable properties and observe that the expander is always set to the largest size and does not shrink when the contents become smaller.

### Expected Behavior

Expander should always fit the size of the contents within. Much the same as the Auto property on a Grid row.

### Actual Behavior

Expander does not appear to resize but seems to fit the largest case scenario. I have not tested extensively many scenarios but in the sample app this can be observed using the method above.

### Basic Information

- Version with issue: v4.7.0.813-pre2
- Last known good version: n/a
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  iOS 13 tested
  - Android: Api 28 tested
  - UWP:  not tested
- Android Support Library Version: n/a
- Nuget Packages: n/a
- Affected Devices: n/a

### Screenshots

![Android-Emulator-pixel-x86-api-2](https://user-images.githubusercontent.com/29577046/83337320-2fea8b00-a2b2-11ea-98a6-00c8a2bd4b01.gif)

### Reproduction Link

https://github.com/varyamereon/ExpanderGridTest

### Workaround

Haven't found a workaround but would be interested.

**Comment by AndreiMisiukevich** [comment]
As I mentioned **ForceUpdateSizeCommand** should be used in such cases.
