### ISSUE TITLE
[Enhancement] [Expander] Set expansion direction

### ISSUE THREAD

**Issue by varyamereon** [xamarin/XamarinCommunityToolkit#421]
## Summary

It should be possible to set the expansion direction of the Expander control. Currently this is limited only to being expanded downwards but it should be possible to expand upwards or sideways too.

## API Changes

This would be with a property such as 'Direction', for example:

`<Expander Direction="Left"/>`

## Intended Use Case

My use case is an Expander which currently expands from the top of the page on mobile devices but I would like to expand sideways from the right of the page on tablet devices. I can also envisage situations where you might want to expand from the bottom of the page such as for an order summary.

**Comment by AndreiMisiukevich** [comment]
Closed via xamarin/Xamarin.Forms#10498
