### ISSUE TITLE
[Bug] SideMenuView.UWP - Menu not collapsing when clicking outside the menu area

### ISSUE THREAD

**Issue by zleao** [xamarin/XamarinCommunityToolkit#422]
### Description
This issue is related to the functionality introduced in [PR 187](https://github.com/xamarin/XamarinCommunityToolkit/pull/187).
In the UWP sample app in the SideMenuView, the menu view is not collapsing when clicking outside of the menu area. It only collapses via the swipe gesture.
This behavior is only seen in UWP. Android and iOS version works as expected

### Steps to Reproduce

1. Run XTC UWP sample app
2. Go to Views -> SideMenuView
3. Open one of the menus (right or left)
4. Try to collapse the menu, by clicking outside of the menu area.

### Expected Behavior
The menu should collapse once we click outside of the menu area

### Actual Behavior
The menu only collapses using the swipe gesture (only seen in UWP)

### Basic Information

- Version with issue: Current main branch code from 8 October 2020
- Last known good version:
- IDE: VS2019 (16.7.5)
- Platform Target Frameworks: 
  - UWP:  17763
- Affected Devices: PC Windows Pro 10.0.19041

### Workaround
Setting `BackgroundColor = Color.Transparent` in the [overlay view that serves as click/tap/touch catcher](https://github.com/xamarin/XamarinCommunityToolkit/blob/abe314842bc1fceeb89704b63e7564b666294ce7/XamarinCommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs#L191) seems to solve the problem.
This code change does not affect iOS and Android (did some testing)

### Aditional Info
Once this bug is validated I can make a PR with the workaround/solution I found.

**Comment by AndreiMisiukevich** [comment]
@zleao nice catch :) Yes, indeed, this is old know XF issue.
Would you like to make PR with the fix you mentioned? Or I can do it myself

**Comment by zleao** [comment]
I can do the PR. Just give me 5 min... :)
