### ISSUE TITLE
[Bug] [Android] EventToCommandBevavior crashes for Release in Android

### ISSUE THREAD

**Issue by Agredo** [xamarin/XamarinCommunityToolkit#426]
### Description
Exception for Android 10 when using EventToCommandBehavior

for iOS and UWP this works

![image](https://user-images.githubusercontent.com/16531090/95649960-dfe1c780-0ae0-11eb-8776-8a1994c8e7b0.png)

### Steps to Reproduce

1. Install Nuget XamarinCommunityToolkit Pre 3
2. Use EventToCommandBehavior in Entry for Completed Command

### Expected Behavior
Working Bevavior

### Actual Behavior
Crash when loading assemblies

### Basic Information

XamarinCommunityToolkit 1.0.0 Pre 3
Xamarin Forms 4.8 SR3
Android 10 SDK

### Workaround
Using other Package Xamarin.Forms.BehaviorsPack

**Comment by pictos** [comment]
@Agredo can you provide a small sample that reproduces the issue?

**Comment by AndreiMisiukevich** [comment]
> ### Description
> Exception for Android 10 when using EventToCommandBehavior
> 
> for iOS and UWP this works
> 
> ![image](https://user-images.githubusercontent.com/16531090/95649960-dfe1c780-0ae0-11eb-8776-8a1994c8e7b0.png)
> 
> ### Steps to Reproduce
> 1. Install Nuget XamarinCommunityToolkit Pre 3
> 2. Use EventToCommandBehavior in Entry for Completed Command
> 
> ### Expected Behavior
> Working Bevavior
> 
> ### Actual Behavior
> Crash when loading assemblies
> 
> ### Basic Information
> XamarinCommunityToolkit 1.0.0 Pre 3
> Xamarin Forms 4.8 SR3
> Android 10 SDK
> 
> ### Workaround
> Using other Package Xamarin.Forms.BehaviorsPack

Yeah, the sample will be very helpful! 👍

**Comment by jfversluis** [comment]
@Agredo would you be able to try the new pre4 version and see if that fixes the issue?

If not, please provide a reproduction project showing this issue so we can get to fixing it. Thanks! :)

**Comment by Agredo** [comment]
@jfversluis sorry I currently domt have much time. I will try it to reproduce it the next days

**Comment by jfversluis** [comment]
Sure thing, let us know! Thanks!

**Comment by jfversluis** [comment]
@Agredo did you manage to get a reproduction? Or try with the latest pre-release? :) Maybe we fixed it in the meanwhile

**Comment by jBijsterboschNL** [comment]
@jfversluis I can confirm this is broken and also still is with the 4th pre-release version. When setting the `EventToCommandBehavior` on a View, the Android app crashes in Release mode (it works properly in Debug mode, so no crash, but the Command execution also works properly). It even crashes on Android without having set the `EventName` property on the EventToCommandBehavior (so just plain adding this Behavior to a View). I've tried changing the linker settings, but that didn't made any difference (also didn't expect this to, but just wanted to be sure). I'll try to have another look at this tomorrow and hopefully solve this issue. And otherwise I'll share a reproduction project here 👌 !

**Comment by jfversluis** [comment]
Did you reference it in XAML only? Could you try adding a dummy reference in code, to completely rule out the linker? Because I still have a suspicion that has to do with it.

**Comment by jBijsterboschNL** [comment]
@jfversluis that didn't make any difference unfortunately. The logs are also pointing to a `NullReferenceException` inside the `EventToCommandBehavior`, so it's not the behavior reference that could not be found. The Exception occurs in `EventToCommandBehavior.RegisterEvent()` after the `EventToCommandBehavior.OnAttached()` is called.

Here are the logs:

2020-11-06 07:18:42.820 25029-25029/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.companyname.xct.eventtocommandandroidbug, PID: 25029
    android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
      at Xamarin.CommunityToolkit.Behaviors.EventToCommandBehavior.RegisterEvent () [0x0005b] in <2d63463870934a409d06bd6d670251a6>:0 
      at Xamarin.CommunityToolkit.Behaviors.EventToCommandBehavior.OnAttachedTo (Xamarin.Forms.View bindable) [0x00007] in <2d63463870934a409d06bd6d670251a6>:0 
      at Xamarin.Forms.Behavior`1[T].OnAttachedTo (Xamarin.Forms.BindableObject bindable) [0x00007] in <195b153c216c400ab511ea0b93c8af0b>:0

And this is the `EventToCommandBehavior.RegisterEvent()` code:

```
void RegisterEvent()
{
    UnregisterEvent(); // the stack trace don't list this method, so it's not in here, right?!

    var eventName = EventName;
    if (View == null || string.IsNullOrWhiteSpace(eventName))
        return; // when not setting the EventName at all, it still crashes, so the crash must be before this line of code, right?!

    ...
}
```

**Comment by jfversluis** [comment]
Just verified with attached repro. When you set it to release it crashes, but when you set Linker to Don't Link, it all works. So _something_ gets taken out. @pictos you are the linker expert by now? :D

[XCTRepro426.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5500412/XCTRepro426.zip)

**Comment by jfversluis** [comment]
Just checked iOS. Happens there too.

**Comment by jfversluis** [comment]
Looking closer at what @jBijsterboschNL posted earlier I see: `at Xamarin.Forms.Behavior`1[T].OnAttachedTo (Xamarin.Forms.BindableObject bindable) [0x00007] in <195b153c216c400ab511ea0b93c8af0b>:0`

It seems to happen in the `BaseBehavior.OnAttachedTo`?

**Comment by pictos** [comment]
@jfversluis I'll investigate this one (:

**Comment by pictos** [comment]
This is odd, from my tests, the linker is removing the `Entry.TextChanged` event, from XF. So maybe the fix should be in the XF project and not here. The NRE is because the code can't create the `eventHandler` [here](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs#L78), as you can see in the image:

<img width="1666" alt="Screen Shot 2020-11-08 at 11 57 54" src="https://user-images.githubusercontent.com/20712372/98469228-07e64880-21bd-11eb-94ba-fc283cde45c2.png">

**Comment by pictos** [comment]
Yeah, it's a linker issue, and looks like that I found a solution for sure. I'll send a PR ASAP to solve this. Tks @jBijsterboschNL to take the time to create a reproduction sample <3.

**Comment by andersondamasio** [comment]
Olá, eu tenho um problema similar no IOS, que só acontece em release, nós temos alguma solução?
