### ISSUE TITLE
[Enhancement] Adding safe area effect to the sample app

### ISSUE THREAD

**Issue by Hackavist** [xamarin/XamarinCommunityToolkit#428]
## Summary
Adding the safe area effect to the sample app based on [this documentation link](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md)

## Spec
* Adding an effects section the main page 
* Adding a safe area effects page that has a background  color and a Stack Layout with a different one containing some text to explain what a safe area is and a toggle to the show the effect in action.

## Intended Use Case
Provide more understanding to the missing feature by example & seeking a more complete sample app

## Who Will Do The Work?

- [*] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Hackavist** [comment]
That is perfect I am on it

**Comment by jfversluis** [comment]
Fixed in #429
