### ISSUE TITLE
LabelSizeFontToFit effect

### ISSUE THREAD

**Issue by abrasat** [xamarin/XamarinCommunityToolkit#43]
## Feature Request:
Would be possible to add the LabelSizeFontToFit effect also for UWP ?

**Comment by Depechie** [comment]
We hope someone can indeed pick this up... for now the current maintainers of the project have not been able to implement this.
All help is welcome for this feature :)

**Comment by jfversluis** [comment]
I think there is a PR for this to be pulled into Forms by default, so this bug will hopefully become irrelevant soon

https://github.com/xamarin/Xamarin.Forms/pull/7981
