### ISSUE TITLE
[Enhancement] Adding missing converters In the sample app

### ISSUE THREAD

**Issue by Hackavist** [xamarin/XamarinCommunityToolkit#430]
## Summary

After inspecting the converters folder in the [documentation repo](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/tree/master/docs/converters)  
I found that the following converters are missing in the sample app
TextCaseConverter
NotEqualConverter
ListToStringConverter
ListIsNullOrEmptyConverter
ListIsNotNullOrEmptyConverter
IsNullOrEmptyConverter
IsNotNullOrEmptyConverter
InvertedBoolConverter
IntToBoolConverter
IndexToArrayItemConverter
EqualConverter
DoubleToIntConverter
BoolToObjectConverter

## API Changes

No Api changes

## Intended Use Case

Enhancing the understanding of the toolkit from the sample app

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Hackavist** [comment]
pr Number converters #446  is not for this issue but it contain helper code

**Comment by jfversluis** [comment]
Are you going to still work on this @Hackavist ?

**Comment by Hackavist** [comment]
@jfversluis yes i am but i was moving so that is why there is a little bit of a delay

**Comment by jfversluis** [comment]
No worries, just checking :)

Hope your move was OK!

**Comment by jfversluis** [comment]
@Hackavist I think we still have converters that are not in there? You still want to do this?

**Comment by Hackavist** [comment]
@jfversluis I am so sorry for the delay , yes i still want to do them and i will have them done this weekend

**Comment by Hackavist** [comment]
@jfversluis  as promised sorry for being late

**Comment by pictos** [comment]
@Hackavist just double-checking here, did you implement all converters listed on this issue?

**Comment by Hackavist** [comment]
Yes i have implemented them all

**Comment by GUOLDEV** [comment]
Hi @Hackavist, I think this issue was addressed and good to be closed, is that right?

**Comment by Hackavist** [comment]
Yes please do

**Comment by GUOLDEV** [comment]
Sorry @Hackavist, I am not able to close an issue : (

**Comment by pictos** [comment]
Closing the issue since the author agreed with that
