### ISSUE TITLE
[Bug] AvatarView: Label is not centralized 

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#442]
### Steps to Reproduce

1. Create avatar view with text

### Expected Behavior
Text is vertically centrilized

### Actual Behavior
text is in the top

### Reproduction imagery

![image](https://user-images.githubusercontent.com/33021114/95790599-60264980-0ce8-11eb-8bb8-475d05fe9340.png)

**Comment by VladislavAntonyuk** [comment]
I am going to fix it

**Comment by VladislavAntonyuk** [comment]
expected:
![image](https://user-images.githubusercontent.com/33021114/95790914-f6f30600-0ce8-11eb-9c22-bf6a79a13234.png)

**Comment by pictos** [comment]
Closing this issue since #443 is merged
