### ISSUE TITLE
[Enhancement] OTP Autofill Control

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#452]
## Summary

Inspired by https://blog.verslu.is/xamarin/xamarin-forms-xamarin/otp-auto-fill-entry-for-ios-with-xamarin-forms/

## API Changes

Add new OTPAutofillControl
It should contain Entry and Request Button

Entry should be autofilled on SMS received
RequestButton should run the command which requests OTP Code (up to user)

iOS:
Entry - extend Entry render with `Control.TextContentType = UITextContentType.OneTimeCode;`

Android: (https://www.c-sharpcorner.com/article/verify-otp-automatically-in-android-without-sms-read-permission-using-xamarin-fo/)
We should use `SMS Retriever API`

**WHY we should implement SMS Retriever API**
From Jan 9th, 2019 Google removed apps from playstore with permissions READ SMS AND CALL LOG, if they don’t explain the necessity
Advantages of SMS Retriever API
- From now not every app with READ SMS permission can access your personal data like messages.
- Usually, to auto-fill OTP we give access to an android app. With SMS Retriever API apps won’t ask for READ SMS permission to auto-fill OTP.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jBijsterboschNL** [comment]
Wouldn't it be better to just create an effect for this? Instead of an entire control?

**Comment by krdmllr** [comment]
I would combine the implementation with https://github.com/xamarin/XamarinCommunityToolkit/issues/702 and implement it

**Comment by krdmllr** [comment]
I have two things to discuss for the android implementation:
* It requires the Xamarin.GooglePlayServices.Auth library, is it okay to add that dependency to XCT?
* The automatic Intent registration seems to fail when the Intent is part of an external library. 
```
[BroadcastReceiver(Enabled = true, Exported = true)]  
    [IntentFilter(new[] { SmsRetriever.SmsRetrievedAction })]  
    public class SmsReceiver : BroadcastReceiver  
```
I work around that with a manual registration which is called whenever the effect is added, something like this:
```
public static void RegisterOtpReceiver(this Activity activity)
		{
			var receiver = new SmsReceiver();
			activity.RegisterReceiver(receiver, new IntentFilter(SmsRetriever.SmsRetrievedAction));
		}
```
Is there any better way to do that?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
