### ISSUE TITLE
[Enhancement] TokenBox

### ISSUE THREAD

**Issue by globodemic** [xamarin/XamarinCommunityToolkit#456]
## Summary

Add new TokenBox (in UWP:TokenizingTextBox)
It should behave like Editor and AutoSuggestBox. The user can select the chips/tags and add to/ remove from the collection.

## API Changes

TokenBox 

                        SelectedItems="{x:Bind SelectedItems}"
                        ItemsSource="{x:Bind ExampleItems}"
                        Visual="OutLineBox"
                        DisplayMemberPath="Name"
                        SelectedTokenBackground="{StaticResource GrayColor}"
                        SelectedTokenForeground ="{StaticResource WhiteColor}"
                        UnSelectedTokenBackround="{StaticResource LightGrayColor}"
                        UnSelectedTokenForeground="{StaticResource LightGrayColor}"
                       ItemsSelected="EventHandler"
                        IsPopup="True"
                        Placeholder="TokenBox"
                        PlaceholderColor="White"
                        AutoSize="TokenChanges"
                        ClearButtonVisibility="True"
                        
TokenBox

In the feature you can customize the selected/unselected tokens in DataTemplate.

UWP: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.ui.controls.tokenizingtextbox?view=win-comm-toolkit-dotnet-stable

Android:
![Android Mobile – 17](https://user-images.githubusercontent.com/54986841/96333732-e08fd600-106b-11eb-94b9-36e85f21a440.png)
![Android Mobile – 18](https://user-images.githubusercontent.com/54986841/96333739-ebe30180-106b-11eb-9aef-2691d86b5e4f.png)

iOS:
![Android Mobile – 19](https://user-images.githubusercontent.com/54986841/96333748-f69d9680-106b-11eb-9345-08e35f7c9014.png)

                   

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
Maybe https://github.com/xamarin/XamarinCommunityToolkit/issues/294 needs to be implemented first.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
