### ISSUE TITLE
Make AnimationBase generic

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#460]
https://github.com/xamarin/XamarinCommunityToolkit/blob/f92ef897b4e184760f228235810c7eccd70059ad/XamarinCommunityToolkit/Behaviors/Animations/AnimationTypes/AnimationBase.shared.cs#L33

Now AnimationBase Animate method has 1 parameter View. Lets say I animate the Label. if I need to access specific property (Text) I have to cast the View to Label. If I want to animate the TextView, I have to duplicate the code.

**Comment by AndreiMisiukevich** [comment]
```csharp
public abstract class AnimationBase<TView> : BindableObject {
}
public abstract class AnimationBase : AnimationBase<View> {
}
```

?

**Comment by VladislavAntonyuk** [comment]
yes. The use case where I try to use it: https://forums.xamarin.com/discussion/158746/number-from-to-animation
