### ISSUE TITLE
[Enhancement] ShadowEffect

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#461]
## Summary
Need to provide the possibility to assign a shadow effect to any view.

## API Changes
- ShadowEffect (Radius, Opacity, Color (?))

## Intended Use Case
Pretty UI

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by Hackavist** [comment]
I really like the Idea and i think it should be added to XF 5

**Comment by filipkristo** [comment]
@Hackavist If you need to help for this one, feel free to contact me, I have one implementation...

**Comment by Hackavist** [comment]
> @Hackavist If you need to help for this one, feel free to contact me, I have one implementation...

Tell me your preferred way of communication and i would love to discuss it together

**Comment by filipkristo** [comment]
> > @Hackavist If you need to help for this one, feel free to contact me, I have one implementation...
> 
> Tell me your preferred way of communication and i would love to discuss it together

You can find me on twitter & telegram @filipkristo.

**Comment by felipebaltazar** [comment]
@Hackavist if you need some help, feel free to contact me too
Think that you can use Sharpnado.Shadows and Javier`s PR as inspiration

https://github.com/roubachof/Sharpnado.Shadows/tree/master/Shadows
https://github.com/xamarin/Xamarin.Forms/pull/10650

**Comment by Cfun1** [comment]
@AndreiMisiukevich does this issue needs to be closed ?

**Comment by AndreiMisiukevich** [comment]
Implemented in #725
