### ISSUE TITLE
[Question] csproj & new files

### ISSUE THREAD

**Issue by Axemasta** [xamarin/XamarinCommunityToolkit#463]
This issue is not strictly related to the library but i do experience it with this library. My examples are coming from an external project where I have a class library that is multi targeting platforms, however I "took inspiration" 😄  from the code in this project and want to understand how I can better work with the project multi-targeting as I've only worked with code like this on this library & the one I am developing.

The csproj is using the extension names of the files to conditionally compile per platform:
```xml
<ItemGroup>
    <PackageReference Include="Xamarin.Build.TypeRedirector" Version="0.1.2-preview" PrivateAssets="all" />
    <Compile Include="**/*.shared.cs" />
    <Compile Include="**/*.shared.*.cs" />
</ItemGroup>
```

If I add a file or move files around, it will get added to this item group and will affect the projects ability to build until I manually go into the csproj and remove it. Below I've added `EmptyClass.shared.cs` to my project:
```xml
<ItemGroup>
    <PackageReference Include="Xamarin.Build.TypeRedirector" Version="0.1.2-preview" PrivateAssets="all" />
    <Compile Include="**/*.shared.cs" />
    <Compile Include="**/*.shared.*.cs" />
    <Compile Include="Controls\WebBrowser\Android\EmptyClass.cs">
        <SubType></SubType>
    </Compile>
</ItemGroup>
```

Is there anything I can do in visual studio to prevent this link being added to the csproj? Is this just a quirk of the multiplatform targeting that contributors to this library & similar live with?

I'm working primarily from visual studio for mac fyi. Wasn't sure if this was the best place to ask the question, but I couldn't see anyone asking this before. When I contributed to this library I had checked in the csproj changes and had to remove them, so I'm hoping this is a pitfall other new contributors to this library fall for! Also nothing is mentioned in [contributing.md](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/CONTRIBUTING.md) so maybe if there is any good advice to come of this thread it could be added there?

**Comment by pictos** [comment]
@Axemasta if I'm not wrong, to solve this issue you should add 
`<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` tag to your `PropertyGroup` tag. That way VS will stop to messing around with your files and build targets.

Sometimes, when you add a new file that has in the name `.shared` VS can add a tag to make MSBuild ignore that file, sadly you will need to remove it manually. I hope that with .NET5 VS improve in this aspect.

**Comment by Axemasta** [comment]
@pictos Thanks for the answer, I did infact add `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` to my csproj, it won't actually build the project without that line.

I did suspect these issues were just a result of early adoption and that it would probably get better down the line. Good to know it is an issue for other developers!
