### ISSUE TITLE
[Improvement] Multi-language improvements

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#464]
### Description
Remove multi-language for each and every page, except for the sample page to show how it works.

The reason for this being that with each feature or change we onboard, we also have to update all the different translations. Every contributor is expected to provide a sample already (preferably) but adding the need to translate them as well adds additional unnecessary work that might deter people. I would personally much rather show off the translation extension on its own little isolated sample page than throughout the entire sample app.

Happy to discuss this though if people feel otherwise.

**Comment by jfversluis** [comment]
Yeah I think this has been discussed somewhere. I really like the idea of being inclusive and translate all those things, but I don't think it's really feasible. We would need people to catch up after every new thing that is added in the app. Maybe at some point that will stabilize, but at least right now a lot of new things are coming in.

For the moment I think it's best to get it out for everything in the whole app and just add a sample that shows how to work with the translation.

**Comment by AndreiMisiukevich** [comment]
Yeah, this was discussed over discord. And I agree with all points.
