### ISSUE TITLE
[Enhancement] GesturePad

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#467]
## Summary

It's been a while since I created gesturepad control for my own product "Draw & GO". I created a PR: https://github.com/xamarin/SignaturePad/pull/138, but looks like that project is not supported since 2018. It's now the time to share my code with the world. it works on the same platforms which Xamarin.Forms supports

## API Changes
```
private const int MinValueGranularity;

        public IEnumerable<Point> Points

        public ICommand GestureCompletedCommand

        public int Granularity

        public bool EnableSmoothedPath

        public Color LineColor

        public float LineWidth

        public bool ClearOnFinish

        public Stream GetImageStream(double imageSizeWidth, double imageSizeHeight)

        public static Stream GetImageStream(IEnumerable<Point> points,
            Size imageSize,
            float lineWidth,
            Color strokeColor,
            Color backgroundColor)
```

## Intended Use Case
Draw signature

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by VladislavAntonyuk** [comment]
In progress

**Comment by oscarjaergren** [comment]
@pictos AND @VladislavAntonyuk  how's it going with this feature? 

I'm a big fan of this one and if you need any assistance I would gladly help ensure it gets shipped

**Comment by pictos** [comment]
@oscarjaergren thanks for your interest. I merged that one into a separate branch to work on it, but I didn't find time so far. I'll try to set everything up until the end of the month and open a PR for that.

**Comment by VladislavAntonyuk** [comment]
You can also use my fork of the original Signature Pad. I added support for all platforms: https://github.com/VladislavAntonyuk/SignaturePad

**Comment by jfversluis** [comment]
Yes! This is still a very awesome control! @pictos @VladislavAntonyuk how can we arrange this that you can both work on it? That is, if @VladislavAntonyuk is open to that of course :) Not sure what still needs to happen for this?

**Comment by VladislavAntonyuk** [comment]
@jfversluis I recently created a PR in XCT. Petro merged it into his branch and made some improvements. As he told, we is going to create a PR to the main branch in the end of the month. 
As for my fork, it is based on the old SignaturePad control and I created it just for people who needs it right now for macOS and WPF.

**Comment by jfversluis** [comment]
That makes total sense :)

Yeah, I just want to make sure we're not blocking by waiting for one person if you are willing to help out with adding some new things right now. If that is the case, we need to find a solution for that. I guess, if you want to add GTK and Tizen you could get Pedro's branch and do some work on that as well? If you open a PR, just make sure that you check the box that maintainers are allowed to make changes. Then Pedro can work together with you on that same branch and we can make some progress.

Or, another route would be to add Pedro to the fork of your Toolkit repo so he has access to that to work on it. Not saying that you _should_ be doing this. Just thinking out loud for ideas to make progress here.

**Comment by pictos** [comment]
I'll find a time this weekend to hook up everything and open a PR to the main.
