### ISSUE TITLE
[Enhancement] SnackBar dismissal enhancements

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#476]
Hi.

I was really looking forward to the snackbar component as I've tried many of them and they all are lacking in some fundamental aspect.

My use case is really simple; I want to display chat messages as some kind of toasts/snackbars/notifications/whatever to the user if he is currently not on the chat page. The toast position should preferably be configurable (top or bottom) so as not to obscure UI navigation elements and/or the notifications should support 'swipe to dismiss' (or other means of closing them).

Unfortunately the snackbar in XCT can't be dismissed, so I thought I'd add two actions to it: 'Hide' and 'Open'. Unfortunately it seems as XCT's snackbar can display one action only (not sure if it's a bug as it accepts an enumeration of actions).

So is there any way this could be addressed in some way? I'd really like to use it, but unfortunately I can't as the user experience would be bad as the user would have to wait out all of the toasts that currently block him from using the app if I were to use it.

Suggestions:
1) Make the position configurable (top or bottom)
2) Add swipe to dismiss, an 'X' close button or something, to allow hiding them prematurely
3) ACT.UserDialogs animates the toasts in/out via a slide instead of a fade, which I strongly prefer. It would also be more natural to swipe away sliding notifications. Any chance of changing this or at least making it configurable?

Thanks.

**Comment by roubachof** [comment]
A Snackbar has a clear semantic that you can find here:
https://material.io/components/snackbars
None of the enhancement you list is part of this semantic unfortunately.
Your behavior is very specific and should be easily done with a simple custom view like a Grid with 3 column *,60,60 for your 2 actions and a SwipeGesture :)

**Comment by Tommigun1980** [comment]
> A Snackbar has a clear semantic that you can find here:
> https://material.io/components/snackbars
> None of the enhancement you list is part of this semantic unfortunately.
> Your behavior is very specific and should be easily done with a simple custom view like a Grid with 3 column *,60,60 for your 2 actions and a SwipeGesture :)

Was not aware this was following material design. Almost every platform has a completely different definition for for example what a toast message is. Where is it stated this follows material design?

**Comment by roubachof** [comment]
> Was not aware this was following material design

Well a Snackbar **is** a material design component, so yes :)

It is implemented with a native snackbar on Android, and the others implementations are just following those specs.

**Comment by Tommigun1980** [comment]
> > Was not aware this was following material design
> 
> Well a Snackbar **is** a material design component, so yes :)
> 
> It is implemented with a native snackbar on Android, and the others implementations are just following those specs.

Thank you for the reply. The terminology gets a bit muddled as there's the ShowToastAsync etc methods, where 'toast' can mean anything from push notifications to a snackbar:esque brief notification, where the position (top/bottom) is configurable in lots of existing APIs. But thank you for the clarification.

**Comment by roubachof** [comment]
Yeah well that happens when you want to please to many people ;)

**Comment by Seuleuzeuh** [comment]
I'm up for the position configurable. According to the [placement design](https://material.io/components/snackbars#placement), we need a way to make the position configurable (only an absolute position perhaps ?), so we can handle the case when we have important content/action button under the snackbar.

**Comment by Tommigun1980** [comment]
@roubachof I checked out the native Android component and it does seem to support swipe to dismiss and positioning, unless I'm terribly mistaken.

So in that regard I think my enhancement ticket is still valid, no? Swipe to dimiss is great as the user can get rid of a notification that may obscure some UI elements without having to wait for it to disappear, which may be the most frustrating thing in the world. And by being able to control at least top/bottom placement would allow the app designer to select a position where it least obscures UI elements.

Thanks again for considering!

**Comment by roubachof** [comment]
It's true that you can add an action or swipe to dismiss a snackbar. A "top" snackbar that close only on the user action is called a banner: https://material.io/components/banners

A snackbar is a low priority UI, putting it at the top of the screen would make it a high priority. 

I would keep a clear UI semantic for component here.

**Comment by Tommigun1980** [comment]
> It's true that you can add an action or swipe to dismiss a snackbar. A "top" snackbar that close only on the user action is called a banner: https://material.io/components/banners
> 
> A snackbar is a low priority UI, putting it at the top of the screen would make it a high priority.
> 
> I would keep a clear UI semantic for component here.

Thank you for the reply. So the 'swipe to dismiss' functionality is on the table then? :)

**Comment by roubachof** [comment]
I would suggest to close this one as and open an issue to add a swipe to dismiss feature.

**Comment by VladislavAntonyuk** [comment]
> I checked out the native Android component and it does seem to support swipe to dismiss and positioning, unless I'm terribly mistaken.

could you please share the documentation link where it is described

**Comment by Tommigun1980** [comment]
> > I checked out the native Android component and it does seem to support swipe to dismiss and positioning, unless I'm terribly mistaken.
> 
> could you please share the documentation link where it is described. I found only Behavior but not the position

It's in the Android developer reference at
https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar

**Comment by VladislavAntonyuk** [comment]
I see that it can be swiped to dismiss, but as for your suggestion 1: They show a brief message at the bottom of the screen on mobile and lower left on larger devices. 
Snackbar is not displayed at the top of the screen

**Comment by Tommigun1980** [comment]
> I see that it can be swiped to dismiss, but as for your suggestion 1: They show a brief message at the bottom of the screen on mobile and lower left on larger devices.
> Snackbar is not displayed at the top of the screen

Ah sorry. Yeah doesn't seem like snackbars' position can be changed on Android.

**Comment by VladislavAntonyuk** [comment]
as for the dismissal swipe action. what do you think if we add a cancellation token? it will be a better way to cancel the task and will work on all platforms

**Comment by Tommigun1980** [comment]
> as for the dismissal swipe action. what do you think if we add a cancellation token? it will be a better way to cancel the task and will work on all platforms

Sounds like a fair way to go about it. Of course the native swipe animation won't trigger on Android in that case, but one would have to implement one anyway for iOS.

**Comment by Tommigun1980** [comment]
> as for the dismissal swipe action. what do you think if we add a cancellation token? it will be a better way to cancel the task and will work on all platforms

> as for the dismissal swipe action. what do you think if we add a cancellation token? it will be a better way to cancel the task and will work on all platforms

Sounds like a fair way to go about it. Of course the native swipe animation won't trigger on Android in that case, but one would have to implement one anyway for iOS.

This of course as long as there is enough control to bind some kind of event listener to the snackbar element, that is.

If this can be implemented straight into the control will of course be easier and saves everyone the effort of doing all of the above.

**Comment by dersia** [comment]
Maybe I am wrong, but I think the XTC should look at concepts and semantics and be inspired by those, but a community toolkit should always be about the community and less about specific concepts. I think from a usability point of view the requested behaviors/actions/animations are not just valid but necessary. Every user today expects for banners/toast/Snackbar to be dismissable. I can't count the times where I was just frustrated as a user because I couldn't dismiss it and it was hiding important information. And it can also be configurable, so if really needed it can be set to not-dismissable.

Having said that, I understand, why the toolkit would try to stick to semantics and concepts, but I think there should really be a discussion on to what point will the toolkit comply with these rules. Also I am "pretty new" to this repo and maybe it's not my place to critize decisions made by the contributors. If so please let me know 😊

**Comment by Tommigun1980** [comment]
I've now been testing the XCT snackbar and it's shaping up really nicely, but I just can't live without ability to dismiss it or placing it at the top of the screen instead.
The problem is that I have the app's main buttons at the bottom of the screen and the snackbar obscures them completely, so every time a notification is shown the user has to stop using the app for a few seconds. This just isn't an acceptable user experience.

For what it's worth, I have seen apps that display notifications at the top. If they are called banners and are meant for 'high prio' notifications, so be it -- all the users care about is that it doesn't prevent them from using the app, and if the only place where they can be shown at is the top, then that's where they have to go.

Thanks.

**Comment by Tommigun1980** [comment]
I've now been testing the XCT snackbar and it's shaping up really nicely, but I just can't use it without the ability to dismiss it or place it at the top of the screen instead.
The problem is that I have the app's main buttons at the bottom of the screen and the snackbar obscures them completely, so every time a notification is shown the user has to stop using the app for a few seconds. This just isn't an acceptable user experience.

For what it's worth, I have seen apps that display notifications at the top. If they are called banners and meant for 'high prio' notifications, so be it -- all the users care about is that it doesn't prevent them from using the app, and if the only place where they can be shown at is the top, then that's where they have to go. The users really don't care about UI paradigms if they can't interact with the app.

Thanks.

**Comment by vniehues** [comment]
@Tommigun1980 I'm currently facing the same problem (positioning).
Did you find a solution to this? I'm kinda at my witts end :D

**Comment by Cfun1** [comment]
In order for Swipe dismiss to work: 
> Having a CoordinatorLayout in your view hierarchy allows Snackbar to enable certain features, such as swipe-to-dismiss and automatically moving of widgets.

[Source](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar#make)

**Comment by VladislavAntonyuk** [comment]
> In order for Swipe dismiss to work: 
> 
> > Having a CoordinatorLayout in your view hierarchy allows Snackbar to enable certain features, such as swipe-to-dismiss and automatically moving of widgets.
> 
> 
> 
> [Source](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar#make)
> 
> 
> 
> @VladislavAntonyuk can we do something about that ?

As for Android as it was mentioned it is possible with native implementation. As for other platforms I think we can use gesture recognizes.

**Comment by Cfun1** [comment]
> > In order for Swipe dismiss to work:
> > > Having a CoordinatorLayout in your view hierarchy allows Snackbar to enable certain features, such as swipe-to-dismiss and automatically moving of widgets.
> > 
> > 
> > [Source](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar#make)
> > @VladislavAntonyuk can we do something about that ?
> 
> As for Android as it was mentioned it is possible with native implementation. As for other platforms I think we can use gesture recognizes.

@VladislavAntonyuk  I meant that even if that the feature already exist in native Android, it is not working in the sample probably we don't have a `CoordinatorLayout` in the tree, hence was my question "can we do something about that ?", should we wrap somehow inside a `CoordinatorLayout`?

**Comment by VladislavAntonyuk** [comment]
This feature needs to be enabled in Snackbar. It is disabled by default. I used the base call to show Snackbar.

**Comment by Cfun1** [comment]
@VladislavAntonyuk I was searching on Android official documentation I didn't find anything regarding explicitly enabling/disabling it (or disabled by default)  also was and playing with [setBehavior()](https://developer.android.com/reference/com/google/android/material/snackbar/BaseTransientBottomBar#setBehavior(com.google.android.material.snackbar.BaseTransientBottomBar.Behavior)) without success, I think it can be a matter of missing `CoordinatorLayout` in our tree structure (additional: https://stackoverflow.com/questions/38823767/snackbar-is-not-dismissing-on-swipe).

**Comment by AndreiMisiukevich** [comment]
@VladislavAntonyuk is this task closed by https://github.com/xamarin/XamarinCommunityToolkit/pull/1005 ?

**Comment by VladislavAntonyuk** [comment]
@AndreiMisiukevich The discussion describes 2 issues. The first issue is about Swipe to dismiss. I think it is not implemented. 
The second issue is about position of the Snackbar. And it is fixed by the PR

**Comment by AndreiMisiukevich** [comment]
@Tommigun1980 could you please fill the separate ticket? It will be more convenient to follow the discussion :)
Thanks

**Comment by Tommigun1980** [comment]
> @Tommigun1980 could you please fill the separate ticket? It will be more convenient to follow the discussion :)
> Thanks

https://github.com/xamarin/XamarinCommunityToolkit/issues/1225
