### ISSUE TITLE
[Enhancement] Allow configuring snackbar in one place

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#477]
ACT.UserDialogs's toasts allows one to set up toast defaults in one place.

I think XCT's snackbar should separate the config from actually showing the notifications, as currently one has to send in all the styling, durations etc every time a snackbar is shown.

I'd like to set up defaults once (theming, fonts, durations etc.), and in my code just define the message and actions when I show them. One has now to make a wrapper class or utility methods for XCT's snackbar that always sends in the theming, or duplicate a ton of code.

As a pointer, this is roughly how I am setting up ACT.UserDialog's toasts:

```c#
        private void SetupToastDefaults()
        {
            ToastConfig.DefaultPosition = ToastPosition.Top;
            ToastConfig.DefaultDuration = TimeSpan.FromSeconds(4.5);
            ToastConfig.DefaultBackgroundColor = (Color)this.Resources["SomeColor"];
            ToastConfig.DefaultMessageTextColor = (Color)this.Resources["SomeOtherColor"];
            ToastConfig.DefaultActionTextColor = (Color)this.Resources["YetAnotherColor"];
        }
```

There is no equivalent for XCT's snackbar -- I'd have to send in all of those every time a notification is shown.

**Comment by pictos** [comment]
I'll ping you first and ask later

@VladislavAntonyuk any thoughts?

Do you mind if I mention you in the `snackbar` issues?

**Comment by VladislavAntonyuk** [comment]
It can be implemented. I can do it after finishing with DrawingView PR

**Comment by Tommigun1980** [comment]
Thanks guys, I appreciate it.

**Comment by VladislavAntonyuk** [comment]
in progress

**Comment by AndreiMisiukevich** [comment]
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/508

**Comment by Tommigun1980** [comment]
Thanking you here as well @VladislavAntonyuk, absolutely fantastic job once again! You truly are a wizard.
