### ISSUE TITLE
[Housekeeping] Add sample for CharactersValidationBehavior

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#480]
## Summary
It's just housekeeping work :) Need to implement a sample page for **CharactersValidationBehavior** following the example as done for other behaviors.

## API Changes
None

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by Seuleuzeuh** [comment]
I've tested the CharactersValidationBehavior and made a Sample page for this.
Did you want me to made a PR of it ? @AndreiMisiukevich 
![Screenshot_1603443524](https://user-images.githubusercontent.com/14994342/96978695-ec254600-151e-11eb-8849-d44b9bbed59b.png)

**Comment by AndreiMisiukevich** [comment]
> I've tested the CharactersValidationBehavior and made a Sample page for this.
> Do you want me to make a PR of it ? @AndreiMisiukevich
> ![Screenshot_1603443524](https://user-images.githubusercontent.com/14994342/96978695-ec254600-151e-11eb-8849-d44b9bbed59b.png)

Yes, please :)
Thanks for the help

**Comment by AndreiMisiukevich** [comment]
Please keep in mind that you needn't have to localize your sample anymore. Just put text directly to the page
