### ISSUE TITLE
Add font options to Shield

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#482]
As proposed in the original PR, let's extend the `Shield` with all the font options

---
@sthewissen Sounds like a good idea to me, we can add `FontFamily`, `FontSize` and `FontAttributes` BindableProperties. Should include these properties in this PR or in a future iteration?

_Originally posted by @jsuarezruiz in https://github.com/xamarin/XamarinCommunityToolkit/pull/338#issuecomment-713467423_

**Comment by jBijsterboschNL** [comment]
This sounds like a good plan :) I'm willing to take on this one and try to implement those extra options on the Shield control. If that's ok?! :)

**Comment by jfversluis** [comment]
![image](https://media0.giphy.com/media/R459x856IfF6w/200.gif)

**Comment by Seuleuzeuh** [comment]
@jBijsterboschNL Remember to add the attribute `[TypeConverter(typeof(FontSizeConverter))]` on the FontSize properties 
:smile:

#485 
#471

**Comment by jsuarezruiz** [comment]
And let me know if can help with something :)
