### ISSUE TITLE
[Enhancement] Add a PluralityConverter

### ISSUE THREAD

**Issue by kazo0** [xamarin/XamarinCommunityToolkit#484]
## Summary

Does anyone think it would be useful to have a quick converter that will provide the proper pluralization of a given value?
Something like:

`<converter:PluralityConverter x:Key="DaysPluralityConverter" PluralValue="Days" SingularValue="Day"/>`

Which would result in:
| Number       | Value          |
| ------------- |:-------------:|
| 0      | Days |
| 1     | Day      | 
| 6 | Days      | 

## API Changes

`<converter:PluralityConverter x:Key="DaysPluralityConverter" PluralValue="Days" SingularValue="Day"/>`

```
public class PluralityConverter : IValueConverter
{
	public string PluralValue { get; set; }
	public string SingularValue { get; set; }

	public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
	{
		if (value is int num)
		{
			return num == 1 ? SingularValue : PluralValue;
		}

		return null;
	}

	public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
	{
		throw new NotImplementedException();
	}
}
```
This may not be necessary, just a random thought I had

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Hey @kazo0! Thanks for your suggestion. Much appreciated.

Why not use [Humanizer](https://github.com/Humanizr/Humanizer) which is specialized in these kinds of things?

**Comment by AndreiMisiukevich** [comment]
Actually, it depends on the current culture.
For example, in Russian, it's more complex

|English|Russian|
| ---- | :----: |
| 1 day | 1 **день** |
| 2 days | 2 дня |
| 11 days | 11 _дней_ |
| 21 days | 21 **день** |
| 101 days | 101 **день** |
| 102 days | 102 дня |
| 105 days | 105 _дней_ |

Also, it depends on the context

|English|Russian|
| ---- | :----: |
| I have 2 pens | У меня 2 **ручки** |
| I will share 2 pens | Я поделюсь 2 **ручками** |

**Comment by kazo0** [comment]
To be honest I never knew about Humanizer, that's awesome!

**Comment by jfversluis** [comment]
Glad you learned something! :D 

I think it's best to leave this to solutions like Humanizer and not try to fiddle with this ourselves. Thanks for the suggestion though! Keep them coming!
