### ISSUE TITLE
[Bug] NamedSize on BadgeView

### ISSUE THREAD

**Issue by Seuleuzeuh** [xamarin/XamarinCommunityToolkit#485]
### Description

When declaring a BadgeView in Xaml, we cannot use NamedSize for the FontSize property.

### Steps to Reproduce

1. Declare a BadgeView in Xaml
2. In the FontSize property put Medium

### Expected Behavior

Like Xamarin.Forms controls, be abble to use NamedSize

### Actual Behavior

Unable to use named size

### Basic Information

- Version with issue: All
- Last known good version: None

### Workaround

Set it in code behind using : `Device.GetNamedSize(NamedSize.Medium, typeof(Label))`

**Comment by jBijsterboschNL** [comment]
@Seuleuzeuh are you willing to take this one on for yourself? If not, I could easily fix this one as well, as I'll also will be implementing this on the Shield view #482

**Comment by Seuleuzeuh** [comment]
Already did in #486
