### ISSUE TITLE
[Bug] Expander on a Collectionview

### ISSUE THREAD

**Issue by legyas** [xamarin/XamarinCommunityToolkit#493]
### Description
When an Expander which is defined in the ItemTemplate of a CollectionView is opened (expanded) and the ItemSource has at least 15 elements, other Expanders will open randomly. The bug wasn't observed when the CollectionView was replaced with a ListView
### Steps to Reproduce

1. Add an Expander to the ItemTemplate of a CollectionView
2. The ItemsSource has to have more than 10 elements
3. open one Expander and another will open randomly

### Expected Behavior
only one Expander opens
### Actual Behavior
a second Expander opens randomly
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Using a Listview will avoid this bug

**Comment by AndreiMisiukevich** [comment]
Hello @legyas and thank you for raising this issue.
I confirm that the issue exists, but this problem is related to CollectionView (All works fine with StackLayout + ScrollView)

https://github.com/xamarin/Xamarin.Forms/issues/10288

**Comment by AndreiMisiukevich** [comment]
@jfversluis I don't think we can fix it on our side.

**Comment by AndreiMisiukevich** [comment]
duplicated #608

**Comment by sachinkanadia** [comment]
Hi @AndreiMisiukevich 

Thanks for looking into this. Whats the update for this bug? Has it been resolved? Does it has to be reallocated to another project?

I agree with you that the expander view works within a stacklayout as a bindable layout control so I think it needs to be looked at by the team responsible for CollectionView.

I achieved this on this app - https://play.google.com/store/apps/details?id=com.alphacore_consulting.todoit&hl=en_GB&gl=US

Ultimately this needs to be fixed. I'd be grateful for your help.
