### ISSUE TITLE
[Enhancement] Implement IconTintColorEffect for Image and ImageButton

### ISSUE THREAD

**Issue by jBijsterboschNL** [xamarin/XamarinCommunityToolkit#496]
## Summary

To be able to better support theming, or even for whitelabeling your apps, I would like to have an IconTintColorEffect. With this effect you could tint an Image or ImageButton without needing to add your icon in multiple colors to your project.

## API Changes

Added `IconTintColor` Effect which holds an attached property `Xamarin.Forms.Color TintColor`.
When this attached property is set, the effect will automatically get added to the view.

Implemented a shared `IconTintColorEffectRouter` and implemented an Android and iOS specific `IconTintColorEffectRouter` to implement this effect for these platforms.

## Intended Use Case
If your app supports theming, you already easily can change colors on almost anything, except for your icons that you might use in an Image control or ImageButton. With this effect you can now easily change the color of your icons as well.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Look useful to me!

**Comment by AndreiMisiukevich** [comment]
> Look useful to me! Should we indicate in any way that this is only for iOS? How will we do that?

Why did you decide it's for iOS only?)

**Comment by jBijsterboschNL** [comment]
> Look useful to me! Should we indicate in any way that this is only for iOS? How will we do that?

I will implement this for Android and for iOS! Not just for iOS.
