### ISSUE TITLE
[Enhancement] Synchronised ObservableCollection

### ISSUE THREAD

**Issue by filipkristo** [xamarin/XamarinCommunityToolkit#498]
## Summary

As a software developer who use MVVM pattern, sometime I get error because at a same time I adding items to collection and enumerating it. Usually that happens if you use in root page, like NavigationPage.

To avoid that I created Synchronised ObservableCollection that implement regular ObservableCollection and use lock on every method and have custom Synchronised enumerator.

## API Changes

There is no existing API changes, I would like to bring that class to Xamarin.CommunityToolkit.ObjectModel 

e.g.

![Screenshot 2020-10-25 at 16 56 36](https://user-images.githubusercontent.com/8782505/97112182-2e978000-16e3-11eb-9949-67fc96c85978.png)

## Intended Use Case
On global collection that can be modified from different sources

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
