### ISSUE TITLE
[Bug] Error compiling in Release mode

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#505]
### Description
Compiling in Release mode, I have this error:

Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.CommunityToolkit.UI.Views.MediaCapturedEventArgs::.ctor(System.String,System.Byte[])' in assembly: 'Xamarin.CommunityToolkit.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.MediaSource
   in Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   in Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   in MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   in Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
   in Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type)
   in Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   in MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   in Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   in Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   in Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   in Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   in Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in Mono.Linker.Steps.MarkStep.ProcessQueue()
   in Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   in Mono.Linker.Steps.MarkStep.Process()
   in Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   in MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   in Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   in Mono.Linker.Pipeline.Process(LinkContext context)
   in MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   in Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   in Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   in Xamarin.Android.Tasks.AndroidTask.Execute()				

### Steps to Reproduce

1. Build in Release  

### Expected Behavior
No error
### Actual Behavior
Error
### Basic Information

- Version with issue: 1.0.0-pre3
- Last known good version: unknown
- IDE: Visual Studio 2019 16.7.7
- Platform Target Frameworks: 
  - Android: Android 10 Api 29
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms 5.0.0.1487-pre1
- Affected Devices: Zebra TC72

**Comment by jfversluis** [comment]
Please retry with the latest pre-release package from the Toolkit, I think this should be fixed in there :)

**Comment by acaliaro** [comment]
Yes @jfversluis you are right. Thanks
