### ISSUE TITLE
[Enhancement] PageContainerView

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/XamarinCommunityToolkit#510]
This is copied from https://github.com/xamarin/Xamarin.Forms/issues/5891 . This might now be a better place for it.

## Summary

A view that can embed Pages, conceptually similar to iOS's view controller containment.

This is an example implementation:
https://github.com/TomSoderling/PageContainerView/blob/master/Library/PageContainerView.Plugin/PageContainerView.cs

## API Changes

```csharp
namespace Xamarin.CommunityToolKit.UI.Views
{
	public class PageContainerView : View
	{
		public static readonly BindableProperty ContentProperty = BindableProperty.Create(nameof(Content), typeof(ContentPage), typeof(PageViewContainer));

		public ContentPage Content
                {
			get => (ContentPage)GetValue(ContentProperty);
			set => SetValue(value);
		}
	}
}
```

## Intended Use Case
This would allow creating things like a custom tabbed page or a split view page without resorting to a platform specific implementation.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
> This would allow creating things like a custom tabbed page or a split view page without resorting to a platform specific implementation.

@GalaxiaGuy thanks for submitting this proposal... I'm feeling that I missed something about this proposal, I'll share my thoughts about this. And, please, feel free to increase the use cases and so on.

We can create custom tabbed pages, these days, without going into the specific platform, we can use a grid or absolute layout and compose these controls.
I don't know if you say `split view` as an example, as far as I know, the split view is a concept in iOS to allow users to have two apps opened at the same time. But if you are using as a concept, I can reference the [gridsplitter](https://github.com/jsuarezruiz/TemplateUI#gridsplitter) that can do that for us.

**Comment by GalaxiaGuy** [comment]
By split view, I meant something similar to uisplitviewcontroller (or master detail page).

Composing controls like this is not a problem, but doing so with Pages is. The idea is to be able to use a Page as an arbitrary control and then also connect up the child page lifecycle events correctly.

**Comment by VladislavAntonyuk** [comment]
Why do you need to embed the contentpage into view, if you can use the contentview? Also Shell can partially achieve the result

**Comment by GalaxiaGuy** [comment]
The glib answer is whatever the answer to "Why do I need to use pages with a NavigationPage?" is.

The better answer is I already have pages. There are places that Xamarin Forms only allows pages (like navigation, or the current container pages like master detail or tabs) so I use pages. But then if I wan't to compose them (at the Forms layer, without custom renderers), I can't.

There are also things that pages do that content doesn't, like built in OnAppearing and OnDisappearing.

**Comment by pictos** [comment]
@GalaxiaGuy,

> There are also things that pages do that content doesn't, like built in OnAppearing and OnDisappearing.

I don't think this is a good point to have this implemented. `Pages` are expensive controls compared with `ContentViews`. Maybe what we can do here or on the Forms/Maui side is trying to implement these lifecycles into the `ContentView` control. Right now, to be honest with you, I don't see a good reason to implement this feature in this way. I mean, **your request is valid**, but I don't think that uses Pages is a good approach.

Said that, if the ContentView has these life-cycle events, are your problems solved?

And feel free and comfortable to disagree with me (;

**Comment by GalaxiaGuy** [comment]
@pictos 

>  if the ContentView has these life-cycle events, are your problems solved

That would help, but it wasn't really the biggest issue (although I've manually implemented this enough times that having it built-in would be useful anyway).

Just to clarify the exact situation in which I wanted this (which never went ahead for other reasons, and isn't something particularly pressing for me right now):

We wanted a tablet layout a bit like a master detail page, but with a slightly different layout (there was a header area at the top, and there were two panes side by side). Importantly, the app was already implemented on phone, using normal navigation and pushing pages. The desire was to just use the same pages in the new layout (which we did try for a while using a master detail page but found it wasn't flexible enough).

There were some other minor conveniences to doing it this way, like the pages already having titles that the parent layout could do stuff with.

---

The other option I considered was to make everything a `ContentView` instead of a `ContentPage`, and wrap stuff in a `ContentPage` at runtime if I need to use somewhere that only accepted a `Page`...

**Comment by pictos** [comment]
@GalaxiaGuy I need to look at how XF implements `PageRenderer` to see if this makes sense (that we don't have troubles with memory and performance in general), right now in my head the best approach is using `ContentView`s, as you mentioned.
And to be honest, this can take a while, my pipeline is full 😅.
Also, this just come out of the blue right now, if we create a `ContentView` control that mimics a `ContentPage`? Let me know your thoughts.

**Comment by IeuanWalker** [comment]
@pictos I needed life-cycle event for a custom control created for work. Found this solution that works really well _(not had an issue with it, was implemented a few years back, can't remember where I got it from)_ -

Solution
```csharp
/// <summary>
/// Class to add onAppearing and onDisappearing to a ContentView
/// </summary>
public static class PageAwareExtension
{
    public static void AttachLifecycleToPage(this Element element, EventHandler onAppearing = null, EventHandler onDisappearing = null)
    {
        var task = new Task(() =>
        {
            var page = GetPage(element);
            if (page == null)
            {
                return;
            }

            if (onAppearing != null)
            {
                page.Appearing += onAppearing;
            }

            if (onDisappearing != null)
            {
                page.Disappearing += onDisappearing;
            }
        });
        task.Start();
    }

    public static Page GetPage(this Element element, int timeout = -1)
    {
        if (element is Page page) return page;

        Element el = element;
        // go up along the UI tree
        do
        {
            if (el.Parent == null)
            {
                // either not attached to any parent, or no intend to attach to any page (is that possible?)
                var signal = new AutoResetEvent(false);
                PropertyChangedEventHandler handler = (object sender, PropertyChangedEventArgs args) =>
                {
                    // https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Element.cs
                    // Setting Parent property is tracked
                    Element senderElement = (Element)sender;
                    if (args.PropertyName == "Parent" && senderElement.Parent != null)
                    {
                        signal.Set();
                    }
                };
                el.PropertyChanged += handler;

                var gotSignal = signal.WaitOne(timeout);
                if (!gotSignal)
                {
                    throw new TimeoutException("Cannot find the parent of the element");
                }

                el.PropertyChanged -= handler;
            } // if parent is null

            el = el.Parent;
        } while (!(el is Page));

        return (Page)el;
    }
}
```

Usage _(based on a ContentView)_ - 
```csharp
public IShare()
{
    InitializeComponent();
    this.AttachLifecycleToPage(OnAppearing, OnDisappearing);
}

private void OnDisappearing(object sender, EventArgs eventArgs)
{
    ishareView.RemoveAllLocalCallbacks();
    Connectivity.ConnectivityChanged -= Connectivity_ConnectivityChanged;
}

private void OnAppearing(object sender, EventArgs eventArgs)
{
    ishareView.AddLocalCallback("coordinatesCSharp", CoordinatesCSharp);
    ishareView.AddLocalCallback("outsideBoundryCSharp", OutsideBoundryCSharp);
    ishareView.AddLocalCallback("layerInfoCSharp", LayerNamesCSharp);
    ishareView.AddLocalCallback("mapLoadedCSharp", MapLoadedCSharp);

    // If no internet
    if (!(Connectivity.NetworkAccess == NetworkAccess.Internet))
    {
        LoaderAnimation.Animation = "NoConnection.json";
        LoaderAnimation.Loop = false;
        NoConnection.IsVisible = true;
        LoaderAnimation.HeightRequest = 150;
        LoaderAnimation.WidthRequest = 150;
    }

    Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
}
```

**Comment by pictos** [comment]
@IeuanWalker thanks for the suggestions and code snippets but we will follow another approach for LifeCycle events. Will be better to rely on native APIs, I'll open a PR sooner for it, you can see the current progress in [this branch](https://github.com/xamarin/XamarinCommunityToolkit/tree/pj/Lifecycle-events)

**Comment by IeuanWalker** [comment]
@pictos ahh awesome, thanks.

**Comment by pictos** [comment]
@GalaxiaGuy, first of all thanks for your proposal, we really appreciate any idea that can improve our work as a mobile developer. Talking with the XCT team we decided to closed this issue now as `not-on-roadmap` label. Maybe in the future we can revisit this proposal.
