### ISSUE TITLE
[Bug] AvatarView.Source attachableProperty does not work in Xamarin forms 

### ISSUE THREAD

**Issue by EddieNoureddine** [xamarin/XamarinCommunityToolkit#512]
### Description
Using the inline property Source for AvatarView works fine , but then we do not have control over Caching the image.
Trying to use the AttachableProperty AvatarView.Source does not work at all although it it compiles well.
### Steps to Reproduce

Add the following to a Content page 
```
 <views:AvatarView Size="70">
     <views:AvatarView.Source>
        <UriImageSource 
                      Uri="{Binding ImageUrl}"  
                      CacheValidity="50"  
                      CachingEnabled="true" >
         </UriImageSource>
     </views:AvatarView.Source>
</views:AvatarView>
```

### Expected Behavior
Should show  image 
### Actual Behavior
Not showing image at all, No exception  
### Basic Information

if we rather try the following code: **with inline Source property** , it works fine
```
<views:AvatarView  
      Source="{Binding ImageUrl}"
      Size="70">
</views:AvatarView>
```
- Version with issue:1.0
- Last known good version: 
- IDE: vs2019
- Platform Target Frameworks: 
  - iOS: all
  - Android: 7.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

use inline source property:
```
<views:AvatarView  
      Source="{Binding ImageUrl}"
      Size="70">
</views:AvatarView>
```

**Comment by jfversluis** [comment]
Thanks for the report! Just to check: you tried this on iOS and Android and both showed the same behavior, correct?

**Comment by EddieNoureddine** [comment]
Yes . True . On both physical devices and emulators
