### ISSUE TITLE
[Spec] Badge support for Shell

### ISSUE THREAD

**Issue by Dresel** [xamarin/XamarinCommunityToolkit#517]
## Summary

There are requests for badge support for classic [tabs](https://github.com/xamarin/Xamarin.Forms/issues/3352) and there are also some libraries out there which kinda support that. With shell it's not possible to use this libraries without touching / replacing too much of the shell internals so it would be great if shell supports this scenario out of the box. I couldn't find anything related in [shell spec](https://github.com/xamarin/Xamarin.Forms/issues/2415), that's why I'm proposing it here.

## API Changes

Badges should be supported on all shell navigation patterns, which are

- Flyout menu items
- Bottom tabs
- Top tabs

I propose the following properties for first iteration of badge support:

**Primary properties**

`BaseShellItem (bindable properties)`

- `BadgeText`: string to set the number (or something else) of notification-like items
- `BadgeMoreText`: string to set the number (or something else) of the aggregated more tab
- `BadgeTextColor`: Foreground color of badge text
- `BadgeUnselectedTextColor`: Foreground color of badge text if underlying navigation item is in unselected state
- `BadgeEffectiveTextColor (readonly)`: If `BadgeUnselectedTextColor` is unset, `BadgeTextColor` will be returned. Otherwise it will return `BadgeTextColor` if the underlying navigation item is in selected state or `BadgeUnselectedTextColor` if in unselected state.
- `BadgeColor`: background color of badge
- `BadgeUnselectedColor`: background color of badge if navigation item is in unselected state
- `BadgeEffectiveColor (readonly)`: If `BadgeUnselectedColor` is unset, `BadgeColor` will be returned. Otherwise it will return `BadgeColor` if the underlying navigation item is in selected state or `BadgeUnselectedColor` if in unselected state.

**Future implementations / considerations**

- Add font image support (might also work for "little dot mode")
- CSS Styling
- Inheritance of styling related properties
- Additional More properties (TextColor, UnselectedTextColor, Color, UnselectedColor, ...)

Bottom tabs use the concept of the More tab if there are more than 5 items. All items with index >= 5 will be "hidden" by this more tab and handled by a platform specific context menu.

One use case would be the transformation of the underlying items hidden by this more tab. For example Item 5 (Messages) has "1" new item and Item 6 (Notifications) has "2" new items, so you could show "3" in the more tab, but the user would not how how this is split between the aggregated items.

We could think of modifying the text (e.g. for the example above "Messages (1)" and "Notifications (6)"). I'm proposing this because adding a badge to the underlying platform specific context menu could be too much work / impossible for a specific platform. Modifying the title value should definitely work though and we would see at least something.

### Android

Material components will support [badges](https://github.com/material-components/material-components-android/blob/master/docs/components/BadgeDrawable.md) out of the box, which when I understood it correctly can be used when [AndroidX](https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX#android-support---androidx-roadmap) is supported by Xamarin. In the meantime we have to supply a custom implementation like [this](https://stackoverflow.com/a/46591378/1249506) for badges.

#### Flyout

Flyout menu is created by the `ShellFlyoutTemplatedContentRenderer` in combination with `ShellFlyoutRecyclerAdapter`. The data template is based on forms controls, so we just might use a [Frame](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.frame?view=xamarin-forms) here for the default template. For custom templates the user has to provide the necessary controls and bind color, text, etc.. 

#### Bottom tabs

`ShellItemRenderer` uses `BottomNavigationView`, which can be used to retrieve the underlying `BottomNavigationItemView` items and inject the badge view.

The `more` tab uses a `BottomSheetDialog`.

#### Top tabs

`ShellSectionRenderer` uses `TabLayout`, which can be used to retrieve the underlaying `TabView` items and inject the badge view.

#### Flyout

Flyout menu is created by the `ShellTableViewController` in combination with `ShellTableViewSource`. The data template is based on forms controls, so we just might use a [Frame](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.frame?view=xamarin-forms) here for the default template. For custom templates the user has to provide the necessary controls and bind color, text, etc.. 

#### Bottom tabs

`ShellItemRenderer` uses `UITabBarController` which can use the `UITabBarItem` to specify native Badge properties.

The `more` tab uses the default implementation of the `MoreNavigationController` of `UITabBarController`.

#### Top tabs

`ShellSectionRootRenderer` uses a UICollectionView, so you would have to modify `ShellSectionHeaderCell` and add a custom badge view (something like [this](http://ootips.org/yonat/the-simplest-ios-badge/)).

## Screenshots

**TODO**: Add them here

Feedback welcome.

**Comment by John0King** [comment]
It's unbelievable that current Xamarin doesn't support it.
just look at the Wechat mini program
- navigation   https://developers.weixin.qq.com/miniprogram/en/dev/api/route/wx.switchTab.html
- ability      https://developers.weixin.qq.com/miniprogram/en/dev/api/ui/tab-bar/wx.showTabBarRedDot.html

**Comment by jfversluis** [comment]
@John0King you're referencing things in a tab bar. Badges are supported in the TabView that is available in this Toolkit. Did you see that one?

I think there is some exploration going on about integrating that into Shell so that it's also available there

**Comment by John0King** [comment]
@jfversluis   is there any document about how to using that ?

**Comment by jfversluis** [comment]
Not published yet. We have some minimal info here: https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/views/tabview.md

And you can always check out the sample app: https://github.com/xamarin/XamarinCommunityToolkit/tree/main/samples/XCT.Sample/Pages/Views/TabView

**Comment by angelru** [comment]
TabView is fine but not lazy loading yet. Let's see if Badge comes out soon in Shell

**Comment by decv86** [comment]
> TabView is fine but not lazy loading yet. Let's see if Badge comes out soon in Shell

I think never ... Probably all efforts are directed to the new MAUI

**Comment by jfversluis** [comment]
@decv86 this project won't do anything on regard to .NET MAUI, all efforts will target Forms 5 and that includes Shell

**Comment by vniehues** [comment]
@Dresel Do you have an update on this for us? :)

**Comment by angelru** [comment]
I don't know if they will leave it for MAUI or what will happen...

**Comment by smhasan** [comment]
Any update on this topic

**Comment by TanishqThakral** [comment]
@samhouts @Dresel  Any updates??

**Comment by angelru** [comment]
any idea of this for MAUI?

**Comment by nichojo89** [comment]
> I've quickly setup a NuGet package / Plugin library to ease the implementation for a badge on a bottom bar for you guys: https://github.com/galadril/Xam.Shell.Badge
> 
> ( @angelru @jmelendez025 @tawrey @kamranmasud @tawreyhap @thuyetpv @dan5602 )
> 
> You can use the nuget package, or look at the code on how to do it yourself

This nuget was a life saver, thank you @galadril !

**Comment by pictos** [comment]
This will not happen on this project, since it's in code freeze mode. IF you want to see this feature, open a discussion around it [here](https://github.com/communityToolkit/maui/discussions)

**Comment by PlaysafePP** [comment]
So if I get this right, some great badge support was suggested 4 years ago. Some great progress was made, but it was never integrated in any Xamarin release, however a nuget is available to add support show badges in bottom tabs, 

What about badges in shell flyout items?  Does anybody have any solutions for this?

**Comment by angelru** [comment]
@PlaysafePP  Maybe on MAUI or the MAUI Community Toolkit.
