### ISSUE TITLE
[Bug] GravatarImageSource doesn't seem to work?

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#526]
### Description

Didn't really dive into it, but it seems the GravatarImageSource is not working? Or do I have wrong expectancies? If I go in the sample app and to the sample I don't see any image show up.

### Steps to Reproduce

1. Start sample app
2. Go to GravatarImageSource sample
3. No image :(

### Expected Behavior

@dansiegel's lovely face

### Actual Behavior

Not Dan's lovely face

**Comment by jfversluis** [comment]
Of course when I wanted to make a screenshot it now works. But while sliding the slider for size it still hides/shows randomly. So at the very least _something_ fishy is going on.

**Comment by dansiegel** [comment]
@jfversluis sounds like we may want to look at some of the caching changes that were done as part of the PR review

**Comment by AndreiMisiukevich** [comment]
I know the reason and I will prepare a fix today
