### ISSUE TITLE
[Bug] Bindable Stacklayout in Expander in RefreshView does not change size when refreshed

### ISSUE THREAD

**Issue by ngreen-asli** [xamarin/XamarinCommunityToolkit#528]
### Description
When Bindable Stacklayout in Expander is refreshed in a RefreshView the height of the expander content does not change to match the number of rows in the stacklayout
### Steps to Reproduce

1. Create a Bindable Stacklayout in Expander in RefreshView
2. Expand the Expander to show the initial data which would show, say, 2 rows
3. Refresh the view to change the number of rows to 1, 3, 4 rows etc and the size of the expander content will still be the height of 2 rows

### Expected Behavior
The expander content would resize to the size of the stacklayout

### Actual Behavior
The height of the stacklayout remains static

### Basic Information

- Version with issue: 1.0.0-pre4
- Last known good version: n/a
- IDE: VS 2019 16.7.7
- Platform Target Frameworks: 
  - Android: Android 10.0 API 29 
- Affected Devices: Pixel 2 (emulator)

**Comment by AndreiMisiukevich** [comment]
You should call ForceUpdateSizeCommand or ForceUpdateSize method once your stack layout changes size in this case.
