### ISSUE TITLE
[Enhancement] Repo sorting and cleanup

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#529]
Opening an issue to keep track of a couple of different things we might want to improve on the repo:

- [x] Change the TabView sample to use the XmlnsDefinition improvement
- [x] Merge Markup sample with main sample
- [x] Merge Markup unit tests with other unit tests 
- [x] Better organize our folders on the repo root, with Markup coming in there is way too much there for my taste
- [x] Unify naming on folders (some have XamarinCommunityToolkit while others are Xamarin.CommunityToolkit, I would prefer the latter)

**Comment by Seuleuzeuh** [comment]
I suggest you to follow this [.Net project structure](https://gist.github.com/davidfowl/ed7564297c61fe9ab814), more readable and easy to find all parts of the repos.
The actual structure is not "friendly" for contributors/readers.

**Comment by jfversluis** [comment]
That is a great suggestion, thank you!

**Comment by pictos** [comment]
I think that we can do the merge between Markup extension samples and UnitTests in the XF5.0 branch. I'll update that branch on this weekend.

**Comment by jfversluis** [comment]
I think this is all done!
