### ISSUE TITLE
[Bug] [Android] MediaElement Opacity not working

### ISSUE THREAD

**Issue by HausBJB** [xamarin/XamarinCommunityToolkit#530]
Hello

first of all I'm sorry

if I want to change the Opacity of the MediaElement, the MediaElement is not displayed at all

### Basic Information
- IDE: Visual Studio 2019 16.7.7
.- iOS: 14.1 
.- Android 10

### Steps to Reproduce
`<MediaElement Opacity="0.5"  Source="https://sec.ch9.ms/ch9/5d93/a1eab4bf-3288-4faf-81c4-294402a85d93/XamarinShow_mid.mp4" ShowsPlaybackControls="True" />`

![image](https://user-images.githubusercontent.com/53478848/98438917-e10d1100-20ed-11eb-9d5c-9fa692cbf126.png)

**Comment by jfversluis** [comment]
Hey @HausBJB is there any particular reason that you are ignoring almost the complete bug issue report template? It is there for a reason so that we can get as much detail as possible so we can help you better. This is not a lot to go on. If you could add some more detail that would be great. Thanks!

**Comment by AndreiMisiukevich** [comment]
@jfversluis 

Tested on iOS simulator: works pretty fine
Tested on Android emulator: **issue exists**

**Comment by AndreiMisiukevich** [comment]
After hours of investigations
It seems impossible to fix this issue for android with the current implementation https://stackoverflow.com/a/33328785/6255544

**Comment by AndreiMisiukevich** [comment]
CC @pictos @jfversluis @jsuarezruiz

**Comment by pictos** [comment]
@AndreiMisiukevich I don't think that just ignore the opacity will be a good fix, because we should keep the control similar on all platforms for common properties. I can see two solutions.

1. Removing this property;
2. Refactor this property into a platform-specific one.

**Comment by AndreiMisiukevich** [comment]
But MediaElement inherits  **Opacity** property from VisualElement

**Comment by pictos** [comment]
Oh, I forgot about that... Maybe I need some sleep haha. In that case.

1. Ignoring for all platforms;
2. Ignoring for just android.
