### ISSUE TITLE
[Question] Missing views?

### ISSUE THREAD

**Issue by bPoller2810** [xamarin/XamarinCommunityToolkit#534]
For me it seems like there are a lot of views missing (Looking for the TabView specialy). I am using 1.0.0-pre4 on XF 5.0.0.1558-pre3
Did i miss some obvious point here?

![image](https://user-images.githubusercontent.com/36732235/98458959-36046200-2196-11eb-9ed6-69d609030683.png)

**Comment by jBijsterboschNL** [comment]
> For me it seems like there are a lot of views missing (Looking for the TabView specialy). I am using 1.0.0-pre4 on XF 5.0.0.1558-pre3
> Did i miss some obvious point here?
> 
> ![image](https://user-images.githubusercontent.com/36732235/98458959-36046200-2196-11eb-9ed6-69d609030683.png)
> 
> 

In the 4th pre-release the TabView wasn't implemented yet. Could you try the nightly build? Do you need any help with that? We are working to get a new and stable version out, which will also contain the TabView.

**Comment by jfversluis** [comment]
Exactly right! I'm waiting for the C# Markup PR to be merged before we release a new pre-release version. That should be somewhere next week.

In the meanwhile, if you really can't wait try the nightly feed which has the TabView already :)

Thank your for being an early adopter! 😄

**Comment by bPoller2810** [comment]
Well then its obvious why i could not find it 👍 

Is there a nuget for the nightlies? or how would you reccomend to include them.

**Comment by jfversluis** [comment]
No worries. I think we should make more clear what is released when and what is in there. Probably release notes will help with that :)

For the nightly, you can use this link: https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json

If you don't know how to add nuget feeds, you can use [this video](https://youtu.be/HaEHR8gWk_E)
