### ISSUE TITLE
[Bug] I am not able to use <xtc tag in xaml 

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#543]
### Description
I have installed the package and I try to use EventToCommandBehavior 

I add 
<Button Text="Click Me"
                    TextColor="White"
                    BackgroundColor="{StaticResource NormalButtonBackgroundColor}">
                <Button.Behaviors>
                    <xct:EventToCommandBehavior
                        EventName="Clicked"
                        Command="{Binding IncrementCommand}" />
                </Button.Behaviors>
            </Button>

to my xaml and 
                xmlns:xct="http://xamarin.com/schemas/2020/toolkit"

But I have an error
![image](https://user-images.githubusercontent.com/5759350/98564583-d0ef6000-22ac-11eb-8a89-9a08b0e908fc.png)

If I use the xct in csharp, it works

### Expected Behavior
Able to use the xct

### Actual Behavior
Does not recognize xaml tags
### Basic Information

- Version with issue: 1.0.0-pre4
- Last known good version: unknown
- IDE: vs2019 Versione 16.7.7
- Platform Target Frameworks: 
  - Android: 10.0
- Android Support Library Version: 
- Nuget Packages: XF 5.0.0.1558-pre3
- Affected Devices:

**Comment by jfversluis** [comment]
This is not available yet in the pre-release packages only in the nightlies for now. It should be available for -pre5, so hold on a little longer! :)
