### ISSUE TITLE
[Spec]  AppBar

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/XamarinCommunityToolkit#545]
# AppBar

An app bar consists of a toolbar and potentially other views. Expose one or more actions.

The main benefit of using the appbar is being able to customize everything. Customization options like:
* Custom app bar height.
* Include any content without restrictions or limitations (margins, size, etc.).
* Transparent appbar.
* Etc.

**NOTE:** AppBar is a **cross-platform view** that takes over when native navbar hit their limits, such as adding custom content, positioning with layouts, etc.

![appbar](https://cdn.dribbble.com/users/1769705/screenshots/8578385/media/77ddf55b2f7a42f7aac4df8ae785bca4.jpg)

# API

Next, a list with the AppBar properties and events.

## Properties

| Property   |      Type      |      Description      |
|----------|:-------------:|:-------------:|
| Placement |    AppBarPlacement   |  The AppBar placement (top or bottom).  |
| BarHeight |  double | Define the app bar height.  |
| BarBackground |  Brush | A brush that provides the background.   |
| BarBackgroundImage |  ImageSource | An ImageSource that provides the background.  |
| BarTextColor |  Color | The color used in the texts (title, etc.).  |
| NavigationIcon |  ImageSource | An ImageSource that provides the navigation icon (back button, etc).  |
| BackButtonTitle |  string | Define the app bar back button title.  |
| BorderColor |  Color | The app bar border color.  |
| BorderThickness |  Thickness | The appbar border width in every side.  |
| FontFamily |  string | The font family used in the app bar texts.  |
| FontAttributes |  FontAttributes | The font attributes used in the app bar texts.  |
| FontSize |  double | The font size used in the app bar texts.  |
| TitleView |  View |  Display any Xamarin.Forms View in the app bar.  |
| BackCommand |  ICommand | Command executed navigating back.  |
| BackCommandParameter |  object | The command parameter used navigating back.  |

## Events

| Event   |      Description      |
|----------|:-------------:|
| BackTapped | Event that is raised when the user navigate back.  |

# Scenarios

Let's see some samples covering common scenarios.

## Simple app bar

Let's see a basic example:

```
<ContentPage>
     < ContentPage.AppBar>
         <AppBar />
     </ContentPage.AppBar>
    ...
</ContentPage >
```

## Custom app bar

Customizing the appearance using a transparent bar with a custom height and custom content (TitleView).

```
<ContentPage >
     <ContentPage.AppBar>
        <AppBar  
            BarHeight="120"
            BarBackgroundColor="Transparent">
            <AppBar.TitleView>
            ...
            </AppBar.TitleView>
        </AppBar>
     </ContentPage.AppBar>
    ...
</ContentPage>
```
## Placement

A top app bar (default placement) displays navigation and actions at the top of mobile screens.

```
<ContentPage>
     <ContentPage.AppBar
          Placement="Top">
         <AppBar />
     </ContentPage.AppBar>
    ...
</ContentPage>
```
![appbar-top](https://user-images.githubusercontent.com/6755973/82044247-4c30da00-96ad-11ea-8631-f49864a0b6c4.png)

A bottom app bar displays navigation and actions at the bottom of mobile screens.

```
<ContentPage >
     <Shell.AppBar
          Placement="Bottom">
         <AppBar />
     </ContentPage.AppBar>
    ...
</ContentPage>
```

![appbar-bottom](https://user-images.githubusercontent.com/6755973/82044250-4d620700-96ad-11ea-9ef2-dd7c60459235.png)

## Using Styles

Can customize the appearance of the tab content, tab strip, tab item, etc. using **XAML** styles or **CSS**.

Using XAML:

```
<Style
    x:Key="AppBarStyle"
    TargetType="AppBar">
    <Setter
        Property="BarHeight"
        Value="120" />
    <Setter
        Property="BarBackgroundColor"
        Value="Transparent" />
</Style>
```

Using CSS:

```
.appBarStyle {
  background: transparent;
  height: 120px;
}
```

# Difficulty : Medium

**Comment by nor0x** [comment]
What do you think about adding an `Orientation` property to this spec, to also allow vertical `AppBar`s?

Could probably be done with a collapsable `Flyout` or `Main-Detail layout,` but this seems to more suited for showing very similar views and just changing the underlying data for the detatil view.

**Additional context**
More and more apps, especially on landscape orientation (Desktop, Tablets,...) are using vertical tabs as their main navigation mechanism. i.e. Discord, MS Teams, MS Edge, Mac App Store...

Here are some examples:
<img width="1433" alt="IMG_12389123" src="https://user-images.githubusercontent.com/3210391/97561936-2f7d2a00-19e1-11eb-8cbf-cd8b6378c844.png">
©redit [https://dribbble.com/shots/13818645-Project-Kanban-Style](https://dribbble.com/shots/13818645-Project-Kanban-Style)
©redit [https://dribbble.com/shots/14158637-Deals](https://dribbble.com/shots/14158637-Deals)
©redit [https://dribbble.com/shots/9834917-Careers-Hiring-Job-Admin-UI-Design/attachments/1867783?mode=media](https://dribbble.com/shots/9834917-Careers-Hiring-Job-Admin-UI-Design/attachments/1867783?mode=media)
©redit [https://dribbble.com/shots/13616742-User-Profile](https://dribbble.com/shots/13616742-User-Profile)

**Comment by acaliaro** [comment]
> What do you think about adding an `Orientation` property to this spec, to also allow vertical `AppBar`s?
> 
> Could probably be done with a collapsable `Flyout` or `Main-Detail layout,` but this seems to more suited for showing very similar views and just changing the underlying data for the detatil view.
> 
> **Additional context**
> More and more apps, especially on landscape orientation (Desktop, Tablets,...) are using vertical tabs as their main navigation mechanism. i.e. Discord, MS Teams, MS Edge, Mac App Store...
> 
> Here are some examples:
> <img alt="IMG_12389123" width="1433" src="https://user-images.githubusercontent.com/3210391/97561936-2f7d2a00-19e1-11eb-8cbf-cd8b6378c844.png">
> ©redit https://dribbble.com/shots/13818645-Project-Kanban-Style
> ©redit https://dribbble.com/shots/14158637-Deals
> ©redit https://dribbble.com/shots/9834917-Careers-Hiring-Job-Admin-UI-Design/attachments/1867783?mode=media
> ©redit https://dribbble.com/shots/13616742-User-Profile

There is a `Placement` property that could be use for this...?? left and right?

**Comment by Cfun1** [comment]
It will nice if it will be possible to override by keeping the existing/current app bar (let say generated by Shell) and appending elements to it above/below? Maybe supported by a coming custom renderer/handler? could be helpful to achieve something like https://stackoverflow.com/questions/64397674/append-a-control-above-upper-to-the-shell-app-bar-without-altering-it

**Comment by Cfun1** [comment]
A very important point is scroll behavior, another property `ScrollBehavior` ?
@jsuarezruiz
https://material.io/components/app-bars-top#behavior
https://developer.android.com/reference/com/google/android/material/appbar/AppBarLayout.LayoutParams

**Comment by jingliancui** [comment]
Hello , any progress or dev plan about appbar ?

**Comment by Cfun1** [comment]
I see that this spec is still opened here and not moved to any of https://github.com/CommunityToolkit/Maui or https://github.com/dotnet/maui. @jfversluis @brminnick what is the fate of this spec?

**Comment by brminnick** [comment]
We will be focusing on bug fixes for Xamarin Community Toolkit going forward and won't be adding new features.

We will be only adding new features to the .NET MAUI Community Toolkit.  

I recommend starting a New Feature Discussion for the .NET MAUI Community Toolkit: https://github.com/CommunityToolkit/Maui/discussions/new
