### ISSUE TITLE
[Enhancement] Adding api to support floating tabs in tabview

### ISSUE THREAD

**Issue by AswinPG** [xamarin/XamarinCommunityToolkit#548]
## Summary

Adding attributes to Tabview that can enable developers to create floating tabbar like in pinterest and postion them easily using margin
## API Changes

Adding two properties - IsFloating and MarginFromScreen
When IsFloating is true, the contentcontainer will be placed in the whole grid(_mainContainer). This way the content can flow below the tabview
After that we can use the MarginFromScreen Property to apply padding to the _tabStripContainer grid giving the tabview a floating feel. (Also need to set the background color to transparent)

## Intended Use Case
Bottom tabs in pinterest is an example

## Who Will Do The Work?

- [Y ] I am willing to take this on myself

@jsuarezruiz  @jfversluis 

If the spec is okay I am ready to implement this
![WhatsApp Image 2020-11-11 at 8 27 25 PM (1)](https://user-images.githubusercontent.com/29278621/98835316-45b9ca00-2466-11eb-898f-a6626adc345c.jpeg)

**Comment by jfversluis** [comment]
Isn't this what the appbar spec can do as well? #545

**Comment by AswinPG** [comment]
> Isn't this what the appbar spec can do as well? #545
It's not the top bar that I meant. Sorry for the confusion.. I should've cropped just the bottom part. It's the bottom tabbar seen in the screenshot. Just like the bottom navigation bar of Pinterest.. 
![20201112_042617](https://user-images.githubusercontent.com/29278621/98874001-6a7e6380-249f-11eb-85b4-bc4e43233282.jpg)

**Comment by jfversluis** [comment]
Aah ok great!

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
