### ISSUE TITLE
Stride 3D View for Xamarin.Forms 

### ISSUE THREAD

**Issue by Agredo** [xamarin/XamarinCommunityToolkit#549]
## Summary

Currently the only way for rendering 3D in Xamarin.Forms is UrhoSharp (https://github.com/xamarin/urho) but it seems this repository is abandoned (very sad).
Nevertheless because currently I am working with Unity I got a bit more into game engines but trying to create somthing like: 

![Screenshot 2020-11-11 192239](https://user-images.githubusercontent.com/16531090/98849366-63c9ff00-2453-11eb-9f8e-a06f3823d8a1.png)

is in unity pain in the ****

I wondered if there is an other solution and I found Stride (https://github.com/stride3d/stride). Stride/Xenko generates simply UWP, Xamarin.iOS and Xamarin.Android Visual Studio projects. 

![image](https://user-images.githubusercontent.com/16531090/98850470-1fd7f980-2455-11eb-8def-4dc4df6ffb76.png)
Pretty similar to X.F, ;) 

For the sample I showed in the picture I simply created a Slider and modified the Stride/Xenko sphere inside the ValueChanged event handler method. 

`    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition Height="10*"/>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="10*"/>
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="10*"/>
            <ColumnDefinition Width="80*"/>
            <ColumnDefinition Width="10*"/>
        </Grid.ColumnDefinitions>
        
        <SwapChainPanel Grid.Column="1" Grid.Row="1" x:Name="SwapChainPanel" />

        <Slider Grid.Row="2" Grid.Column="1" Minimum="0.5" Maximum="1.5" Value="1" ValueChanged="Slider_ValueChanged"/>
    </Grid>`

`
private void Slider_ValueChanged(object sender, RangeBaseValueChangedEventArgs e)
        {
            var sphere = Game?.SceneSystem?.SceneInstance?.RootScene?.Entities?.Where(entity => entity.Name == "Sphere").FirstOrDefault();

            if(sphere != null)
                sphere.Transform.Position.Y = Convert.ToSingle(e.NewValue);
        }
`

Then I wondered if there is a way to combine this with Xamarin.Forms and create a custom renderer for UWP, iOS and Android to create a embedded 3D View to create an app like obove: Modifie the 3D View by native controls writing code one time. 

Maybe someone can help me answering a questions:

Is there a way to create a custom renderer for iOS and Android to get something like <xck:StrideView/> and if yes, how?
For UWP there is SwapChainPanel and the Game object but for Android there is only this:

`[Activity(MainLauncher = true, 
              Icon = "@drawable/icon", 
              ScreenOrientation = ScreenOrientation.Landscape,
              ConfigurationChanges = ConfigChanges.UiMode | ConfigChanges.Orientation | ConfigChanges.KeyboardHidden | ConfigChanges.ScreenSize)]
    public class SampleGameActivity : AndroidXenkoActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            Game = new Game();
            Game.Run(GameContext);
        }

        protected override void OnDestroy()
        {
            Game.Dispose();

            base.OnDestroy();
        }
    }`

and for iOS:

`[Register("SampleGameAppDelegate")]
    public class SampleGameAppDelegate : XenkoApplicationDelegate
    {
        /// This method is invoked when the application has loaded and is ready to run the gane.
        // In this method you should instantiate the game and perform additional setup here.
        // You have 17 seconds to return from this method, or iOS will terminate your application.
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            // Instantiate the game
            Game = new Game();

            return base.FinishedLaunching(app, options);
        }

        static void Main(string[] args)
        {
            UIApplication.Main(args, null, "SampleGameAppDelegate");
        }

        public override void WillTerminate(UIApplication application)
        {
            Game.Dispose();
        }
    }` 

## API Changes

Somethiong like `<xck:StrideView/>` in XAML or 
`
var strideView = new StrideView();
`

## Intended Use Case
See my example

## Who Will Do The Work?

- [ x] I am willing to take this on myself (when this is possible)
- [x ] Just putting this out there for someone to pick up (if someone want to help i am open for this too)

here is the sample project
[SampleGame.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5526136/SampleGame.zip) (created with Xenko 3.1 with installed UWP SDK for 20H1 and Xamarin.Forms for Android and iOS on Visual Studio 2019)

**Comment by freever** [comment]
I guess it would depend on what those activity and app delegate classes are doing. There is a similar discussion regarding mono game here: https://github.com/MonoGame/MonoGame/issues/7191

**Comment by pictos** [comment]
@Agredo thanks for your suggestion, but this out of the scope of this project.
