### ISSUE TITLE
[Enhancement] Converters modification

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#553]
## Summary

There are converters which have return the value and the opposite value. They can be combined into 1 converter by using converter parameter.
e.g. IsNullOrEmptyConverter vs IsNotNullOrEmptyConverter. ListIsEmptyConverter vs ListIsNotEmptyConverter

## API Changes

1. remove *Not*Converters
2. use boolean parameters.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jBijsterboschNL** [comment]
Though this sounds like a good idea, I don't think the usage of the converter parameter will make the code better or easy readable. As the converter parameter can't have a specific name where it is used for. And thus you'll need to check the implementation of this converter to check where the converter parameter is used for.

But maybe if we add a specific `InvertCheck` parameter (or a better name haha) to these converters, it would make more sense? As we can give this parameter a specific name which also explains where it is used for? So the usage would be something like this:

`<conv:IsNullOrEmptyConverter x:Name="IsNotNullOrEmptyConverter" InvertCheck=True />'

What do you think of this solution??

**Comment by jBijsterboschNL** [comment]
We could even combine the ListIsEmpty and the IsNullOrEmpty converters, right??!

**Comment by Seuleuzeuh** [comment]
I see in some PR of converters, they discuss about it and choose to not use parameter for invert, for better understanding.

**Comment by VladislavAntonyuk** [comment]
we can add parameters for those who prefer to use them without removing the previous converters.

**Comment by GUOLDEV** [comment]
Hi @VladislavAntonyuk, I believe this issue can be closed?

**Comment by VladislavAntonyuk** [comment]
@GUOLDEV It's up to you. Has any progress been made on this issue?

**Comment by GUOLDEV** [comment]
@VladislavAntonyuk, I thought the issue was already solved, I misunderstood the issue. I have created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1141) to address this issue. Please let me know if it helps.

**Comment by AndreiMisiukevich** [comment]
Hey folks, let's discuss whether we want to merge several converters (Regular and Inverted) into a single one.

Personally, I'd prefer to go ahead with our current approach. **xct:IsNullOrEmptyConverter** and **xct:IsNotNullOrEmptyConverter**. So you needn't have to specify any properties.

Let's bring more people into this conversation

Hey folks, can you please take a look @jfversluis @jsuarezruiz @sthewissen @brminnick @pictos


Also, separately, let's discuss if we want to merge ListEmpty and StringEmpty converters.

**Comment by pictos** [comment]
> Personally, I'd prefer to go ahead with our current approach. xct:IsNullOrEmptyConverter and xct:IsNotNullOrEmptyConverter. So you needn't have to specify any properties.

I agree with this. This change doesn't make any tec. improvement (perf, stability, etc) but adds more work to maintain it, since we need to obsolete the old way (we need to await one major release after obsolete something to remove it) and can add confusion in our users. So I would say to keep our current approach for `Is` and `IsNot` converters

**Comment by pictos** [comment]
We will close this issue for now, since we will not implement this change. Thanks for your proposal.
