### ISSUE TITLE
[Enhancement] Provide ability to specify the animation during a Shell navigation

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#555]
## Summary

To provide a way to specify the animation (FadeTo, TraslateTo right/left...) that will be used when issuing a shell navigation 
for example `Shell.Current.GoToAsync("//MainPage", true,FadeTo);`

## Intended Use Case
It will be used in case someone want to specify an animation during the navigation rather than the default one, like for example I want my next page to come from left, I will specify in the `GoToAsync` method something like:
`Shell.Current.GoToAsync("//MainPage", true, TranslateToRight);`

## More Context
[ [Spec] Transitions Api #6033 ](https://github.com/xamarin/Xamarin.Forms/issues/6033)

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AdamDiament** [comment]
@Cfun1 I think this belongs in the main xamarin forms repo

**Comment by Cfun1** [comment]
I think you are right, but we will probably have to wait long to see this ready. https://github.com/xamarin/Xamarin.Forms/issues/6033

**Comment by pictos** [comment]
@Cfun1 I'll reopen this issue since @PureWeen wants to implement a lot of cool features for Shell here. Since Forms 5.0 is released we will not see any new features there, just bug fixes and improvements.

**Comment by Cfun1** [comment]
@pictos oh nice, I was pessimiste even whan I have opened it that maybe it is not possible to achieve such feature from xct.

**Comment by pictos** [comment]
@Cfun1 TBH I don't know if we can do it here with the opened APIs from Shell, but we should try it (:

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
