### ISSUE TITLE
[Bug] StateLayout crashes when AnimateStateChanges is True

### ISSUE THREAD

**Issue by mondul** [xamarin/XamarinCommunityToolkit#557]
### Description
When using StateLayout without putting `xct:StateLayout.AnimateStateChanges="False"`, the application crashes when changing the binding state too quickly.

### Steps to Reproduce

1. In the demo, remove  `xct:StateLayout.AnimateStateChanges="False"` for the full screen loading
2. Run the demo
3. Toggle the full screen loading

### Expected Behavior
Not crashing

### Actual Behavior
Crashes in `StateLayoutController.ChildrenFadeTo`, throws a `System.InvalidOperationException` with the message `Collection was modified; enumeration operation may not execute.`

### Workaround
`xct:StateLayout.AnimateStateChanges` could be set to `False` by default

**Comment by adammeaney** [comment]
I have seen this as well in the nightly build I am using, 1.0.0 1096

**Comment by jfversluis** [comment]
Hm interesting. @sthewissen is this something that is changed from what you're doing in the "old" package?
