### ISSUE TITLE
[Enhancement] Down and Up gesture

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#561]
## Summary

2 new gestures -
- Down (triggered when the user touches the screen)
- Up (triggered when the user is no longer touching the screen)

In one of the controls I built for a personal project, I've built a similar thing that may help the implementation -

- Android - https://github.com/IeuanWalker/Xamarin.Forms.FlexButton/blob/master/Flex.Android/CustomRenderers/GestureFrameRenderer.cs
- iOS - https://github.com/IeuanWalker/Xamarin.Forms.FlexButton/blob/master/Flex.iOS/CustomRenderers/GestureFrameRenderer.cs

Could link this up with the work on #500 

## Intended Use Case
- Would allow me to remove system specific code in some projects, i.e. one linked above.
- Could be used for user interaction i.e. user could hold down on an object to trigger an animation i.e. 
![99miles_playback_komoot_dribbble_4](https://user-images.githubusercontent.com/6544051/99433262-3246ad00-2905-11eb-9d6a-d418ca868f74.gif)

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
#200 #566 Covers it (Supports Normal, Pressed, Hovered states)
