### ISSUE TITLE
[Bug] Tizen Sample App is giving a warning when loaded

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#563]
### Description

I got a message from someone stating that the warning that the Tizen sample could not be loaded is big and scary for people just starting to look into it. I never thought about it that way and just mindlessly closing it, but I can totally see their point. I've never seen this warning on the Forms repo, so I guess there is a way around this?

### Steps to Reproduce

1. Clone this repo
2. Open the Sample solution
3. A warning is shown Tizen project could not be loaded

### Expected Behavior

No warning, project is simply not loaded

### Actual Behavior

Big scary warning that might scare new-ish ccontributors or people looking into this

**Comment by VladislavAntonyuk** [comment]
@jfversluis Looks like it is fixed. I updated sdk version.

**Comment by AndreiMisiukevich** [comment]
@jfversluis I don't see any messages on VS for Mac. Can you please confirm that you don't see it on Win?

**Comment by jfversluis** [comment]
Seems gone for now! Thanks!
