### ISSUE TITLE
[Enhancement] Media casting in MediaElement

### ISSUE THREAD

**Issue by danieeis** [xamarin/XamarinCommunityToolkit#580]
The MediaElement control should be able to be sent to televisions through an event-driven method, as can be seen in this UWP documentation:

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-casting

This is still an experimental control so it should be a safe time to add it.

I think that is useful when users of media apps want to show video in others devices

**Comment by jfversluis** [comment]
Awesome idea @danieeis !

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
