### ISSUE TITLE
[Bug] MediaElement will crash when page popup 

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/XamarinCommunityToolkit#581]
### Description
The App will crash when leaving the page which has MediaElement.
### Steps to Reproduce

1. Use the MediaElement demo https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-mediaelementdemos/
2. Launch the App goto Custom Transport page
3. Click Play and pause a few times and then click stop, then go back the front page

### Expected Behavior
The App still running 
### Actual Behavior
The App is froze 
### Basic Information

- Version with issue:
- Last known good version: 4.7.0.968
- IDE:VS for Mac 8.6.5
- Platform Target Frameworks: 
  - iOS:  13.5
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Hi Jessie! Thanks for reporting this. There has been shuffling with the MediaElement and it now lives in the Toolkit with us.

Would you be able to check if the bug still happens in our code? I know there have been some bugfixes in the meantime. Thanks!

**Comment by AndreiMisiukevich** [comment]
I presume this bug is fixed (at least because now we don't override Dispose method for iOS MediaElement renderer)
