### ISSUE TITLE
[Bug] [iOS] SnackBar Color Customization doesn't propagate on iOS

### ISSUE THREAD

**Issue by rachelkang** [xamarin/XamarinCommunityToolkit#586]
### Description
SnackBar colors don't propagate on iOS, as it does on Android

### Steps to Reproduce
1. Open XCT Sample Solution https://github.com/xamarin/XamarinCommunityToolkit
2. Run on both Android and iOS and note the difference:
- Navigate to Views > SnackBar / Toast
- Click on the 3rd button, "Show SnackBar"

### Expected Behavior
Colors should propagate on iOS SnackBar.

### Actual Behavior
Colors don't propagate on iOS SnackBar :(

### Basic Information
- Version with issue: most recent
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  14.2

### Workaround
/

### Reproduction imagery
**Android (expected behavior):**
![Screenshot_1605739382](https://user-images.githubusercontent.com/21988533/99598293-51a60e80-29c7-11eb-9a42-94a19dba57d6.png)

**iOS (buggy behavior):**
![Simulator Screen Shot - iPod touch (7th generation) - 2020-11-18 at 17 46 51](https://user-images.githubusercontent.com/21988533/99598303-54a0ff00-29c7-11eb-9062-a62f6e92ed45.png)

### Reproduction Link
https://github.com/xamarin/XamarinCommunityToolkit

**Comment by jfversluis** [comment]
Talked about this with Rachel and looked into it myself. It seems the background color is not hooked up on iOS. @VladislavAntonyuk ?

**Comment by VladislavAntonyuk** [comment]
Please assign it to me. I will take a look
