### ISSUE TITLE
[Enhancement] Add Markdown support to Label

### ISSUE THREAD

**Issue by kazo0** [xamarin/XamarinCommunityToolkit#593]
## Summary
Would be nice to be able to display Markdown text in a Label, similar to the Window Community Toolkit's `MarkdownTextBlock`.
Not sure if this would require a totally new control or if we could tap into the `TextType` property on `Label`

## API Changes

Perhaps we can use the `TextType` property and add a new value of `TextType.Markdown`. Otherwise, add  `bool IsMarkdown` to `Label`. 
## Intended Use Case

```xaml
<Label Text="**Bold Text**" IsMarkdown="True"/>
```

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by IeuanWalker** [comment]
I'd love this.

To achieve this at the moment I'm converting the MD to HTML using (Markdig)[https://github.com/lunet-io/markdig] then displaying the HTML using (HTMLLabel)[https://github.com/matteobortolazzo/HtmlLabelPlugin]

**Comment by kazo0** [comment]
Right now I'm using v0.6.1-pre of https://github.com/dotnet-ad/MarkdownView

**Comment by jfversluis** [comment]
@kazo0 and how is that working for you? Few issues? All features supported?

**Comment by kazo0** [comment]
@jfversluis Overall pretty good. The theming support is nice, some rendering issues though. On initial page load if the content goes past the screen in a ScrollView, the text is cut off unless you force a re-render by doing something like rotating the screen.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
