### ISSUE TITLE
[Bug] AvatarView "bleeding" from Color set on background Frame

### ISSUE THREAD

**Issue by tonyfonager** [xamarin/XamarinCommunityToolkit#599]
### Description

Sometimes the Color from the background frame is visible on the edges of the image on AvatarView - I think its due to some alignment issues, going on when AvatarView is put inside more "complex" layout pages.

### Steps to Reproduce

1. Put AvatarView inside a StackLayout with a WidthRequest twice the size of the AvatarView Size property
2. You will now see that the background Frame gets the size of the StackLayout, but the Image is still "square"

### Expected Behavior

The background Frame should keep the same size as the Image (and the Size property)

### Actual Behavior

In some scenaries the background Frame picks up the size of the parent control.

### Basic Information

- Version with issue: 1.0.0-pre5
- IDE: Visual Studio Mac 8.8
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: Not tested on Android
  - UWP:  Not tested on UWP

### Reproduction imagery

left image is a standard Image control - Image to the right is AvatarView - see the yellow "bleeding" :

![image](https://user-images.githubusercontent.com/837894/99876204-92836a80-2bf5-11eb-8b89-ccd99312c120.png)

Change Color property on AvatarView to Red - makes it even more visible :

![image](https://user-images.githubusercontent.com/837894/99876209-9c0cd280-2bf5-11eb-965e-1a1518e1c2e1.png)

This is from my app where I have the bleeding issue - AvatarView is places inside Grid column same size as AvatarView :

![image](https://user-images.githubusercontent.com/837894/99876214-a75ffe00-2bf5-11eb-97df-09dae560dedb.png)

If I make my Grid colums horizontally larger the AvatarView Frame resizes - but not the AvatarView image :

![image](https://user-images.githubusercontent.com/837894/99876218-b050cf80-2bf5-11eb-9ad4-0a0c1b1a3b59.png)

Tried doing the same on the XCT samples page :

![image](https://user-images.githubusercontent.com/837894/99876222-b646b080-2bf5-11eb-84ce-6135b0bc4189.png)

**Comment by AndreiMisiukevich** [comment]
@tonyfonager have you tried to play with Aspect property?
