### ISSUE TITLE
[Bug] Long text inside expander

### ISSUE THREAD

**Issue by somewv** [xamarin/XamarinCommunityToolkit#609]
### Description
If you change the text of a label that is inside expander when executing Expander Command, then the length of the label is limited to one line.

### Environment
MainPage.xaml
```
<Expander VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                  BackgroundColor="White"
                  Command="{Binding GetAnswerCommand}">
            <Expander.Header>
                <Label Text="Question" TextColor="Black"/>
            </Expander.Header>
            <Label Text="{Binding Answer}" TextColor="Black"
                        VerticalOptions="FillAndExpand"
                        HorizontalOptions="FillAndExpand"/>
</Expander>
```
MainPage.xaml.cs
```
public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = this;
        }
        public string Answer { get; set; }
        public ICommand GetAnswerCommand => new Command(() =>
        {
            Answer = "fgdskalgjnsdlkgsdjnflkgdasfngljkasdnfgljsdfagnslajdkgnsdjgnjdsfgnasdljgTEST";
            OnPropertyChanged(nameof(Answer));
        });
    }
```

### Screenshots
![Expander Bug](https://github.com/somewv/ExpanderBug/blob/master/screenshot.PNG)

**Comment by AndreiMisiukevich** [comment]
@somewv you should call ForceUpdateCommand after Text Change

**Comment by somewv** [comment]
@AndreiMisiukevich I'm sorry, I made the wrong project. I use expander from xamarin forms

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I use expander from xamarin forms. @jsuarezruiz Why did you migrate issue from xamarin forms?

Cuz Expander was moved from Xamarin.Forms to XamarinCommunityToolkit :)

Well
```
Answer = "fgdskalgjnsdlkgsdjnflkgdasfngljkasdnfgljsdfagnslajdkgnsdjgnjdsfgnasdljgTEST";
OnPropertyChanged(nameof(Answer));
ForceUpdateCommand?.Execute(null);
```

Should solve your problem.
Don't forget to bind Expander's ForceUpdateCommand to VM's ForceUpdateCommand

**Comment by somewv** [comment]
@AndreiMisiukevich Works. Thank you very much

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich Works. Thank you very much

You are welcome)
