### ISSUE TITLE
[Bug] UWP: TouchEffect not working

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/XamarinCommunityToolkit#624]
### Description
I tested on iOS 14 and it was fine but in UWP nothing works!!!

### Steps to Reproduce
1. create a blank XF UWP app
2. add this piece of Code
  ```
<StackLayout
            Padding="10,5"
            xct:TouchEffect.NormalAnimationDuration="500"
            xct:TouchEffect.NormalBackgroundColor="Green"
            xct:TouchEffect.PressedAnimationDuration="500"
            xct:TouchEffect.PressedBackgroundColor="Red"
            xct:TouchEffect.PressedRotation="10"
            xct:TouchEffect.PressedRotationX="15"
            xct:TouchEffect.PressedRotationY="15"
            xct:TouchEffect.PressedScale="1.2"
            xct:TouchEffect.PressedTranslationX="5"
            xct:TouchEffect.PressedTranslationY="5"
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="CenterAndExpand">
            <Label
                FontSize="60"
                Text="CLICK ME"
                TextColor="Yellow" />
        </StackLayout>
```
3. test the UWP version

### Basic Information
- Version with issue: 1.0.0-preview2497
- IDE: VS 16.8.2
- Platform Target Frameworks:
- iOS: 14.2
- UWP:  19041 
- Affected Devices: Windows PC

### Reproduction Link
[TouchEffectTest.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5611030/TouchEffectTest.zip)

**Comment by pictos** [comment]
@mhrastegary77 thanks for your report. But this isn't a bug. 
Our minimal version support, for UWP, is `17793` if you update the Min Version, the effects will work.
![image](https://user-images.githubusercontent.com/20712372/100524575-13170d80-3198-11eb-8b51-3d975f882fa7.png)

**Comment by mhrastegary77** [comment]
Thanks @pictos !!! it works perfectly now.
Love the hover option btw @AndreiMisiukevich ❤

**Comment by pictos** [comment]
@mhrastegary77 good to know. Hope that you are enjoying the XCT!
