### ISSUE TITLE
[Enhancement] SelectedItem of TabView

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#633]
## Summary
Support bindable property `SelectedItem` on `TabView`.

Currently we can work with `SelectedIndex`, it would be useful to be able to work with the object directly.

## API Changes
````cs
public static readonly BindableProperty SelectedItemProperty =
    BindableProperty.Create(nameof(SelectedItem), typeof(object), typeof(TabView), default(object),
        defaultBindingMode: BindingMode.TwoWay);

public object SelectedItem
{
    get => GetValue(SelectedItemProperty);
    set => SetValue(SelectedItemProperty, value);
}
````

## Intended Use Case
Get current selected item of `TabItemsSource`.

## Who Will Do The Work?
- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Also see #595

**Comment by jfversluis** [comment]
@jsuarezruiz any objection to doing this?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
