### ISSUE TITLE
[Bug] Cannot compile Android App

### ISSUE THREAD

**Issue by Maraud3r** [xamarin/XamarinCommunityToolkit#635]
### Description
Error message trying to compile Android Application.
message: The specified language targets for Xamarin.Mac20 is missing. Ensure correct tooling is installed for 'Xamarin.Mac'. Missing: '/Library/Frameworks/Mono.framework/Version/6.12.0/lib/mono/xbuild/Xamarin/Mac/Xamarin.Mac.CSharp.targets'

### Steps to Reproduce

Using Visual Studio for the Mac. Version 8.8.3 (build 16)
Clone down the repo. 
open the Xamarin.CommunityToolkit.Sample.sln

Set the Android project as the startup project.

Right click on the Android project and select Rebuild

### Expected Behavior

The project compiles successfully

### Actual Behavior

The project doesn't compile successfully.

**Comment by AndreiMisiukevich** [comment]
@Maraud3r can you explain a little more.
What app cannot compile? XCT sample app or your own?

**Comment by Maraud3r** [comment]
@AndreiMisiukevich 
It's the XCT sample app.

I wanted to look at the sample app and run it so that I could see whats available.

I cloned the repo and opened the sample solution, tried to compile the android app.

Should I be able to run the sample app?

**Comment by AndreiMisiukevich** [comment]
Do you use mac or windows as your machine? (I guess mac, right?)

**Comment by Maraud3r** [comment]
@AndreiMisiukevich 
Yep, I'm on a mac.

Other Xamarin solutions I have compile without error.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> Yep, I'm on a mac.
> 
> Other Xamarin solutions I have compile without error.

Well, this problem occurs because you don't have Xamarin.Mac SDK installed.
If you install it, the problem will go.

But, what will happen if you try to **unload** macOS sample project?

**Comment by Maraud3r** [comment]
@AndreiMisiukevich 
Well if I'm unloading the correct project, I still get the same error.

I have the tests project loaded, the toolkit project loaded, the Xamarin core project loaded and the platform specific targets loaded.

A rebuild on the android project yields the same error.

![Screen Shot 2020-12-02 at 10 44 04 AM](https://user-images.githubusercontent.com/23086592/100903346-6a182d80-348b-11eb-8550-d11005dd67f9.png)

**Comment by AndreiMisiukevich** [comment]
@pictos @jfversluis @jsuarezruiz @sthewissen any ideas on how can we skip building macOS if SDK is not installed?

Workaround: installing xamarin.mac sdk

**Comment by Maraud3r** [comment]
@AndreiMisiukevich 
Is there a way to modify the VS for Mac install to get the macOS SDK without completely re-installing VS for the Mac?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> Is there a way to modify the VS for Mac install to get the macOS SDK without completely re-installing VS for the Mac?

if you run VS for mac installer it won't re-install everything, as I know. It will install only missed packages.

**Comment by Maraud3r** [comment]
@AndreiMisiukevich 
After installing the MacOS SDK, I was able to successfully compile the app.

Up to you if you want to just close the bug.

**Comment by pictos** [comment]
> @pictos @jfversluis @jsuarezruiz @sthewissen any ideas on how can we skip building macOS if SDK is not installed?
> 
> Workaround: installing xamarin.mac sdk

The user can delete the MaciOS target inside the `Xamarin.CommunityToolkit.csproj`

**Comment by jadenrogers** [comment]
I have the same issue but running from Windows. I assumed the compiler would know its not targeting that platform and not try to compile it.

I checked the wiki and there isn't any specifics on getting the samples to build. I am trying to run the android sample on windows and have hundreds on missing name spaces etc related to iOS or Mac

![image](https://user-images.githubusercontent.com/8000621/192910805-35fb04de-57d7-490a-97c2-e492b77c6435.png)

**Comment by pictos** [comment]
@jadenrogers are you trying to compile our project?

**Comment by pictos** [comment]
@jadenrogers open the lib's `csproj` and remove the `macos` target, that should solve your issue

**Comment by pictos** [comment]
@jadenrogers any time... Have fun!

**Comment by jadenrogers** [comment]
@pictos Is there anyway to chat about the project a bit more. Slack / Discord etc. 

What is the intended build environment, is it Mac or do you guys run this on windows. I am still scratching my head as to why I have to remove the targets, I am mac paired etc.

I fired this bad boy up on my mac in VS for Mac 2022 and I get 12 "Possible null reference" CS8602 & CS8604 errors. 

Is this something wrong with my setup or is there an actual compilation issue in the code, should I do a PR for these?

Reason I am looking into this is I want to fix this issue and submit a PR so just getting a good understanding 

https://github.com/xamarin/XamarinCommunityToolkit/issues/1715

Thanks for your time!

**Comment by pictos** [comment]
@jadenrogers yeah, we have a discord channel in the .net server.
Here's the [link](https://discord.gg/8BHUQj7R)
