### ISSUE TITLE
[Enhancement] Width of TabViewItemDataTemplate

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#636]
## Summary
Currently it is not possible to specify the `Width` of `TabView` item when it is defined by `TabViewItemDataTemplate`.

## API Changes
Add `double TabWidth` property on `TabView` or support `Width=GridLength.Auto` when `TabViewItemDataTemplate` is defined.

## Intended Use Case
Specify Width of TabView item when defined by DataTemplate.

Currently the `Width` is [GridLength.Star](https://github.com/xamarin/XamarinCommunityToolkit/blob/4f6f80e9c65335c1fba85472650afa6528dfb888/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs#L610) when the `TabViewItemDataTemplate` is defined.

## Who Will Do The Work?
- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
