### ISSUE TITLE
[Enhancement] TabView LazyLoading

### ISSUE THREAD

**Issue by Estevete** [xamarin/XamarinCommunityToolkit#637]
## Summary

Currently it is not possible to enable the lazy load in `TabView` like proposed in spec #501:

![81934699-ad927380-95ef-11ea-896c-ce4c5a71eb6e](https://user-images.githubusercontent.com/19273351/100896311-c779a200-34be-11eb-9703-33c6061cb3b5.gif)

## API Changes
Add new `bool IsLazy` property for `TabView`
Property | Type | Description
-- | -- | --
IsLazy | Bool | Enable or disable lazy tabs loading.

## Intended Use Case
Avoid loads of content that user doesn't need / want.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
@pictos I see you're assigned. We've merged `LazyView` can we make it easier to use with `TabView`? Or should we just tell people to wrap it in a `LazyView`? Maybe we can have that boolean `IsLazy` and do the wrapping for people?

**Comment by pictos** [comment]
@jfversluis not sure if we can do that by ourselves because the LazyView needs a type instead of a concrete View. I can try to do some experiments here and see if that's feasible. But for now, we should say to people to use the LazyView instead of a ContentView.

**Comment by pictos** [comment]
Closing this one, since we merged LazyView
