### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by a3atech** [xamarin/XamarinCommunityToolkit#64]
## Feature Request:
Hamburger Menu

**Comment by wcoder** [comment]
@a3atech 

Master-Detail Page: https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/master-detail-page/

**Comment by jsuarezruiz** [comment]
@a3atech Do you mean personalized menu?, something like SlideOverKit: https://github.com/XAM-Consulting/SlideOverKit

**Comment by jamesmontemagno** [comment]
This is already included in forms itself :)
