### ISSUE TITLE
[Bug] BadgeView doesn't display when Text is empty

### ISSUE THREAD

**Issue by adammeaney** [xamarin/XamarinCommunityToolkit#640]
### Description
BadgeView doesn't display when initial Text value is null or empty.

### Steps to Reproduce

1. Have a badgeview with Content.
2. Set its Text to string.Empty or null
3. Watch the badgeview and its content be IsVisible = false

### Expected Behavior
The content is visible, the badge is not as there is no value.

### Actual Behavior
There is no content

### Basic Information

- Version with issue: Commit 4f6f80e9
- Last known good version: never
- IDE: VS 19
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction imagery

Not overly helpful as the visual is to be invisible.

### Reproduction Link

Add to BadgeSamplePage
```
                <xct:BadgeView
                    BackgroundColor="Red"
                    Text=""
                    TextColor="White">
                    <Label Text="Initial Empty Value" />
                </xct:BadgeView>
```

**Comment by AndreiMisiukevich** [comment]
@jsuarezruiz is it expected behavior?

https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs#L325-L329

**Comment by adammeaney** [comment]
It's the coded behavior, but I can't imagine anyone expecting it. 

As badges are allowed to be strings, not numbers, a binding having a null or empty is not unusual, and would indicate in many circumstances that I want no badge, but the view to stay. 

I would bind the visibility if I wanted it to disappear

**Comment by AndreiMisiukevich** [comment]
> It's the coded behavior, but I can't imagine anyone expecting it.
> 
> As badges are allowed to be strings, not numbers, a binding having a null or empty is not unusual, and would indicate in many circumstances that I want no badge, but the view to stay.
> 
> I would bind the visibility if I wanted it to disappear

I agree with your points
