### ISSUE TITLE
[Bug] BaseBehavior generic

### ISSUE THREAD

**Issue by MarMarIV** [xamarin/XamarinCommunityToolkit#642]
### Description
I have a problem with EventToCommandBehavior (abstract BaseBehavior<TView>)

In BaseBehavior (https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/BaseBehavior.shared.cs) there is a restriction for TView inheritance from VisualElement. That is ok

But in Object Browser, i see restriction for View, not VisualElement
![Capture](https://user-images.githubusercontent.com/10964247/100972634-64792100-3539-11eb-9d6e-f358932224b6.PNG)

Thats a problem, because when i put EventToCommandBehavior to Page (which is not inherited from View, but VisualElement), i get runtime Exception:
`System.InvalidOperationException
  Message=bindable not an instance of AssociatedType`

### Steps to Reproduce

1. Apply EventToCommandBehavior to any Page type (ContentPage/...)
2. Run app

### Expected Behavior
Working behavior

### Actual Behavior
Invalid generic type restriction in NuGet

### Basic Information

- Version with issue: 1.0.0-pre5
- Last known good version: N/A
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  10.3
  - Android: 29 
  - UWP:  16299

**Comment by AndreiMisiukevich** [comment]
Hi @MarMarIV, thank's for your interest in this project)

Unfortunately, this change (View to VisualElement) wasn't included in **1.0.0-pre5**

@jfversluis can you hint when pre6 will be released?

**Comment by AndreiMisiukevich** [comment]
Please wait for a new pre-release or use the latest nightly
