### ISSUE TITLE
[Enhancement] MediaElement Caption Support

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#646]
## Summary

Now that Media Element has been moved here, please add Caption support to the media element so that we can properly use both embedded captions in videos AND provide a list of URLs of external captions in WebVTT and SRT.

## API Changes

This will require changing how the video/media is loaded, especially on iOS to be able to rebuild the m3u with the captions loaded in properly.

On windows this is straight forward as is Android

## Intended Use Case
Anyone that needs to be able to show captions. This would also be useful for internal consumers at Microsoft to be able to use Xamarin with video for live video with captions, channel 9 etc.

## Who Will Do The Work?

- [X] I am willing to take this on myself (I can provide sample code in every platform if required)
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Looks like a no-brainer to me! How much will change in regard to iOS?

What would the API look like for Forms developers? I have no clue how captions work. Is it built-in, so just a matter of setting: show captions == true && captions language == nl-NL? Do we/can we also supply a file?

I am totally in favor of adding this, but I do want to think about _how_ before we rush into it :)

**Comment by JohnGalt1717** [comment]
@jfversluis  Basically you have to write an interceptor that will take the URIs for the captions and update the m3u file (or create one) that lists the caption files in it and then pass that to the video player.

The same interceptor is required for HTTP Header support (bearer auth for Azure etc) and for DRM.

I would expect that the captions support on Forms would just be an array of a class with Language, forced, and URI. Ios, Android, Windows and Web all can use that information for playback.

Android is significantly easier for adding captions especially if this takes on exo player (which someone already has bindings for)

Windows UWP is trivial as is web (for UNO etc. later)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
