### ISSUE TITLE
[Enhancement] MediaElement HTTP Header Support

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#647]
## Summary

Please enable header support on all platforms in addition to URL.

## API Changes

This will require the same changes as caption support would require. (https://github.com/xamarin/XamarinCommunityToolkit/issues/646)

## Intended Use Case
I.e. Azure Media Services AES DRM support.

## Who Will Do The Work?

- [X] I am willing to take this on myself (I can provide code samples)
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
I'm not sure what this means. What do we gain with this? Be able to play DRM content? What will our developers notice about this change?

**Comment by JohnGalt1717** [comment]
@jfversluis Right now you can't use AES encrypted video streams like Azure Media Services with Xamarin Forms. By adding Http header support you can pass the Authortization Bearer {token} header information to the stream that is required to be able to use AES encrypted streams for Azure (and others)

On Android again this is trivial, it already has a property that can be mapped.

On iOS it requires an interceptor (just like captions) that intercepts the http requests and passes the header on the requests.

On UWP you just add an httpClientFilter to the AdaptiveMediaSource.CreateFromUriAsync. This code does captions and http headers on UWP:

```
                        var baseProtocolFilter = new HttpBaseProtocolFilter();
                        baseProtocolFilter.CacheControl.WriteBehavior = HttpCacheWriteBehavior.NoCache;  // Always set WriteBehavior = NoCache

                        httpClient = new HttpClient();

                        result = await AdaptiveMediaSource.CreateFromUriAsync(new Uri(source.Uri), httpClient);

                        if (result.Status == AdaptiveMediaSourceCreationStatus.Success)
                        {
                            ams = result.MediaSource;
                            ams.DownloadRequested += Ams_DownloadRequested;
							var ms = mediacore.MediaSource.CreateFromAdaptiveMediaSource(ams);
                            

                            var playbackItem = new MediaPlaybackItem(ms);

                            playbackItem.TimedMetadataTracksChanged += (sender, args) => {
                                playbackItem.TimedMetadataTracks.SetPresentationMode(0, TimedMetadataTrackPresentationMode.PlatformPresented);
                            };



                        Control.MediaPlayer.Source = playbackItem;
```

**Comment by JohnGalt1717** [comment]
@jfversluis Note that while there is a non-public call for this on iOS it both breaks external caption support and will get you blocked from publishing to the store. React Native tried this and people failed to publish.  So It's important to do it with the interceptor and build up the m3u file in your interceptor.

By interceptor I mean AVAssetResourceLoaderDelegate. Basically you create a custom class that inherits from this and then attach it to the player.  Then in the inherited request you handle the main request and then the ShouldWaitForLoadingofREquestedResource and you should be good to go. There is extensive documentation on Apple's website on how to do this, what we ran into was trying to get a working m3u file to push to it properly. This is the same functionality that is required for captions #646.  For this you just update the headers on the request that pulls the source m3u or simple mp4 file from the http client (typically only m3u) and then you return that to the video player.

I have code that doesn't work but is on the right track that needs someone that fully understands m3u files (easier said than done because the documentation on them is HORRIBLE) and is comfortable with Xamarin's iOS interfacing to build it all up and setup everything properly.

FYI the Azure Media Player (AMP) demo site here: https://ampdemo.azureedge.net/ has samples for all of this functionality requirements for the entire suite of my enhancement requests for the media element so it's straight forward to test to make sure you got it right.  (Ming Fe formerly of the Azure Media Services team also created a backend hack pass through to do m3u files for ios that got around the AES problem and we've created a backend that also does the captions in m3u which might help for the construction of the m3u file for iOS. I'm happy to contribute that code so that you can see how it's built up in C# right now.

**Comment by richp582** [comment]
For Azure Media Services, when using AES Encryption, you can apparently supply the token as a query parameter... though I haven't tried it personally it looks like that could be a work-around for this...

https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-pass-authentication-tokens

I'm using a home grown XF media player and have been watching the new media element with great interest, but header support is something we need too!

**Comment by JohnGalt1717** [comment]
@richp582  1. It doesn't actually work. 2. That doesn't solve the need to be able to send other headers through.  

This is actually trivial once the other functionality is done that puts the interceptor in on iOS and on android it's just a feature of exoPlayer or the standard mediaPlayer anyhow.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
