### ISSUE TITLE
[Enhancement] MediaElement add DRM support

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#648]
## Summary

Please add functionality to enable DRM functionality. That means widevine on Android, Fairplay on iOS/MacOs, and PlayReady on Windows.  Allow us to pass a set of values for each of the 3 DRM standards and have the video player use those to decode and playback.

## API Changes

This will need to be part of changes that are consistent with: https://github.com/xamarin/XamarinCommunityToolkit/issues/646

## Intended Use Case
Any company producing content in video format needs DRM video playback.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
How is this different from #647 ?

**Comment by JohnGalt1717** [comment]
@jfversluis  #647 is for header support which gives you amoung other things (you can pass any header you want so you can do other stuff too) AES encrypted video with jwt tokens for Azure AES Media Services.

This is to support Widevine, Playready and Fairplay which requires different functionality as far as I'm aware (we haven't looked deeply into how this works)

Here's sample code for UWP Playready functionality: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/adaptive-streaming-with-playready

I would assume that the player would get a property for each of the 3 drms and the things you need to pass to them to make it work. Those would be passed to the respective players per the docs from each of the 3 video players. (and web would do whatever the browser supported of the 3)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
