### ISSUE TITLE
[Enhancement] MediaElement - Add Playback Speed Controls

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#649]
## Summary

Please add playback speed controls as optional on the toolbar for every platform

## API Changes

.ShowPlaybackSpeed = true/false

## Intended Use Case
Anyone using the video player would find this valuable.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Is this supported on every platform? I guess it is? Is it as simple as just toggling a boolean to show that right control?

**Comment by JohnGalt1717** [comment]
@jfversluis  It's supported on all 4 platforms (and macos too).  On Android and uwp it's as easy as just toggling the option and it automatically shows up. On iOS you have to create a custom button overlay for it and wire up a popup menu to it to show the options for playback speed.  In general I'd guess that there would be a double property for playback speed and then an array of doubles for PlaybackSpeedOptions. The array would control what would be displayed when the user taps the button and the popup menu comes up.

**Comment by jfversluis** [comment]
Fixed by #1570
