### ISSUE TITLE
n00b issue? Can't compile the sample app

### ISSUE THREAD

**Issue by jbachelor** [xamarin/XamarinCommunityToolkit#65]
## Bug 

Version Number of Plugin: Cloned GitHub repo on 2018.01.18
Device Tested On: Visual Studio for Mac, 7.3.3 (build 5)
Simulator Tested On: n/a

### Expected Behavior
Successful compilation and then run the app to test out and hopefully start to understand how LabelSizeFontToFit works.

### Actual Behavior
I get four errors on my attempt to compile. Note that I tried restoring Nuget packages, and the errors persist:

#### -----------------------ERROR 1-----------------------------

```
Project "/Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations/Animations.csproj" (Build target(s)):

Target EnsureNuGetPackageBuildImports:
    /Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations/Animations.csproj(85,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/Xamarin.Forms.2.3.4.247/build/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20/Xamarin.Forms.targets.
Done building target "EnsureNuGetPackageBuildImports" in project "Animations.csproj" -- FAILED.
```

#### ------------------------ERROR 2----------------------------

```
Project "/Users/Shared/src/FormsCommunityToolkit/src/Effects/Effects/Effects.csproj" (Build target(s)):

Target EnsureNuGetPackageBuildImports:
    /Users/Shared/src/FormsCommunityToolkit/src/Effects/Effects/Effects.csproj(79,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/Xamarin.Forms.2.3.4.247/build/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20/Xamarin.Forms.targets.
Done building target "EnsureNuGetPackageBuildImports" in project "Effects.csproj" -- FAILED.
```

#### --------------------------ERROR 3--------------------------

```
Project "/Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations.iOS/Animations.iOS.csproj" (Build target(s)):

Target EnsureNuGetPackageBuildImports:
    /Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations.iOS/Animations.iOS.csproj(76,5): error : Este proyecto hace referencia a los paquetes NuGet que faltan en este equipo. Use la restauración de paquetes NuGet para descargarlos. Para obtener más información, consulte http://go.microsoft.com/fwlink/?LinkID=322105. El archivo que falta es ../../packages/Xamarin.Forms.2.3.4.247/build/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20/Xamarin.Forms.targets.
Done building target "EnsureNuGetPackageBuildImports" in project "Animations.iOS.csproj" -- FAILED.
```

#### -----------------------ERROR 4-----------------------------

```
Project "/Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations.Android/Animations.Android.csproj" (Build target(s)):

Target _SetLatestTargetFrameworkVersion:
     Xamarin.Android Supported $(TargetFrameworkVersion)s: (AndroidVersion: ApiLevel=10 OSVersion=2.3 CodeName='Gingerbread' Version=2.3 FrameworkVersion=v2.3 Id=10 Stable=True), (AndroidVersion: ApiLevel=15 OSVersion=4.0.3 CodeName='Ice Cream Sandwich' Version=4.0.3 FrameworkVersion=v4.0.3 Id=15 Stable=True), (AndroidVersion: ApiLevel=16 OSVersion=4.1 CodeName='Jelly Bean' Version=4.1 FrameworkVersion=v4.1 Id=16 Stable=True), (AndroidVersion: ApiLevel=17 OSVersion=4.2 CodeName='Jelly Bean' Version=4.2 FrameworkVersion=v4.2 Id=17 Stable=True), (AndroidVersion: ApiLevel=18 OSVersion=4.3 CodeName='Jelly Bean' Version=4.3 FrameworkVersion=v4.3 Id=18 Stable=True), (AndroidVersion: ApiLevel=19 OSVersion=4.4 CodeName='Kit Kat' Version=4.4 FrameworkVersion=v4.4 Id=19 Stable=True), (AndroidVersion: ApiLevel=20 OSVersion=4.4.87 CodeName='Kit Kat + Wear support' Version=4.4.87 FrameworkVersion=v4.4.87 Id=20 Stable=True), (AndroidVersion: ApiLevel=21 OSVersion=5.0 CodeName='Lollipop' Version=5.0 FrameworkVersion=v5.0 Id=21 Stable=True), (AndroidVersion: ApiLevel=22 OSVersion=5.1 CodeName='Lollipop' Version=5.1 FrameworkVersion=v5.1 Id=22 Stable=True), (AndroidVersion: ApiLevel=23 OSVersion=6.0 CodeName='Marshmallow' Version=6.0 FrameworkVersion=v6.0 Id=23 Stable=True), (AndroidVersion: ApiLevel=24 OSVersion=7.0 CodeName='Nougat' Version=7.0 FrameworkVersion=v7.0 Id=24 Stable=True), (AndroidVersion: ApiLevel=25 OSVersion=7.1 CodeName='Nougat' Version=7.1 FrameworkVersion=v7.1 Id=25 Stable=True), (AndroidVersion: ApiLevel=26 OSVersion=8.0 CodeName='Oreo' Version=8.0 FrameworkVersion=v8.0 Id=26 Stable=True)
     Found Android SDK.
    Found Java SDK version 1.8.0.
Target _ResolveMonoAndroidSdks:
    MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
    Android Platform API level: 23
    TargetFrameworkVersion: v6.0
    Android NDK: /Users/jbachelor/Library/Developer/Xamarin/android-ndk/android-ndk-r11c/
    Android SDK: /Users/jbachelor/Library/Developer/Xamarin/android-sdk-macosx/
    Android SDK Build Tools: /Users/jbachelor/Library/Developer/Xamarin/android-sdk-macosx/build-tools/26.0.1/
    Java SDK: /usr/
Target _GetPrimaryCpuAbi:
    _PrimaryCpuAbi=x86
Target _CheckInstantRunCondition:
    Dex Fast Deployment Enabled: False
Target _SetupInstantRun:
    Android Java Class for Fast Deployment: 
Target _SetupApplicationJavaClass:
    Application Java class: android.app.Application
Target _ValidateAndroidPackageProperties:
      PackageName: FormsCommunityToolkit.Animations.Android
Target EnsureNuGetPackageBuildImports:
    /Users/Shared/src/FormsCommunityToolkit/src/Animations/Animations.Android/Animations.Android.csproj(118,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/Xamarin.Android.Support.Vector.Drawable.23.3.0/build/Xamarin.Android.Support.Vector.Drawable.targets.
Done building target "EnsureNuGetPackageBuildImports" in project "Animations.Android.csproj" -- FAILED.
```

### Steps to reproduce the Behavior
1. Clone FormsCommunityToolkit repo.
2. Open with Visual Studio for Mac, 7.3.3 (build 5).
3. Restore nuget packages.
4. Attempt to build.

**Comment by jsuarezruiz** [comment]
Hey @jbachelor the project has been updated (and renamed) among other changes. Could you try again?

**Comment by jbachelor** [comment]
Thanks so much for getting back to me, @jsuarezruiz! I'm afraid I still get errors after re-cloning the repo today:

- I attempted to build, but got errors off the bat: Two of the same error, "Nuget packages need to be restored before building. NuGet MSBuild targets are missing and are needed for building. The NuGet MSBuild targets are generated when the NuGet packages are restored." (two projects are listed with these errors:  Animations and Effects).
- Next I tried restoring NuGet packages, but that results in another error in the package console (see just below). Hope this is helpful... Any clues? Thanks for your help!

> Running non-parallel restore.
> Reading project file /Users/Shared/src/XamarinCommunityToolkit/Samples/Samples/Samples/Samples.csproj.
> Restoring packages for /Users/Shared/src/XamarinCommunityToolkit/Samples/Samples/Samples/Samples.csproj...
> Restoring packages for .NETStandard,Version=v2.0...
> Resolving conflicts for .NETStandard,Version=v2.0...
> Checking compatibility of packages on .NETStandard,Version=v2.0.
> Checking compatibility for Samples 1.0.0 with .NETStandard,Version=v2.0.
> Checking compatibility for NETStandard.Library 2.0.1 with .NETStandard,Version=v2.0.
> Checking compatibility for Xamarin.Forms 2.5.0.122203 with .NETStandard,Version=v2.0.
> Checking compatibility for Animations 1.0.0.0 with .NETStandard,Version=v2.0.
> Checking compatibility for Effects 1.0.0.0 with .NETStandard,Version=v2.0.
> Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v2.0.
> Checking compatibility for Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 with .NETStandard,Version=v2.0.
> Package Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 supports:
>   - netcore50 (.NETCore,Version=v5.0)
>   - uap10.0.15138 (UAP,Version=v10.0.15138)
> Checking compatibility for Win2D.uwp 1.21.0 with .NETStandard,Version=v2.0.
> Package Win2D.uwp 1.21.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Win2D.uwp 1.21.0 supports: uap10.0 (UAP,Version=v10.0)
> Incompatible packages: 2
> Committing restore...
> Writing lock file to disk. Path: /Users/Shared/src/XamarinCommunityToolkit/Samples/Samples/Samples/obj/project.assets.json
> Writing cache file to disk. Path: /Users/Shared/src/XamarinCommunityToolkit/Samples/Samples/Samples/obj/Samples.csproj.nuget.cache
> Restore failed in 50.93 ms for /Users/Shared/src/XamarinCommunityToolkit/Samples/Samples/Samples/Samples.csproj.
> 
> NuGet Config files used:
>     /Users/jbachelor/.config/NuGet/NuGet.Config
> 
> Feeds used:
>     https://api.nuget.org/v3/index.json
> Restore failed.

**Comment by IssacKramer** [comment]
I also get build error of:
"Animations.csproj : error MSB4057: The target "Clean" does not exist in the project."
??

**Comment by jsuarezruiz** [comment]
Maybe we can change the minimum required version of the UWP SDK to make things easier.

**Comment by jamesmontemagno** [comment]
See #83
