### ISSUE TITLE
[Enhancement] MediaElement - Full Screen Support

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#650]
## Summary

Please implement transparent full screen functionality from button and also the ability to enable full screen on landscape flip.

## API Changes

Each platform is different. 

.AllowFullScreen = true/false
.AutomaticFullScreen = true/false
.FullScreen()

## Intended Use Case
Anyone using video will expect this basic functionality.

## Who Will Do The Work?

- [ ] I am willing to take this on myself **(I'd offer but my code is a hack)**
- [X] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
> Each platform is different.
>
> .AllowFullScreen = true/false
> .AutomaticFullScreen = true/false
> .FullScreen()

Then our challenge is how to unify this. My proposal would be a boolean people can bind to to make it fullscreen yes/no and a method so you can also call it from code-behind... Thoughts?

**Comment by JohnGalt1717** [comment]
@jfversluis  That would be a good start to have the boolean property. But each platform also has a button that can be displayed for users to tap on to initiate it which should also be available in the playback controls.

Further, I would suggest a property "FullScreenOnLandscape" that would allow people to just set it, and have the player switch to full screen if the person turns the phone.

Android is actually the hardest here because NONE of the android video players have native full screen support. You have to create a custom activity that is set to full screen, then copy over everything about the video player including position and any drm, headers etc., stop the other one, and start the new activity and then do the reverse when exiting full screen. (which is why #647, #646, #648, #649 and this need to all be taken together so that it's planned out as one unit even if the features ultimately are dripped because if not done correctly from the beginning especially with iOS, you'll end up having to rewrite the others to get it all working.)

Every other platform has it natively built in and is trivial to implement.

**Comment by Painwraith** [comment]
anyone have any solution for this?

**Comment by guytz72** [comment]
I'm after this too.  Can't believe this is so difficult...who wants to watch a video in a small corner of the screen????

**Comment by hirios** [comment]
I'm looking for it too!

**Comment by DaviBittencourt** [comment]
Any news about this?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
