### ISSUE TITLE
[Bug] Controls missing from intellisense

### ISSUE THREAD

**Issue by pictos** [xamarin/XamarinCommunityToolkit#658]
### Description
When I try to build a Xamarin app, and try to access the XCT namespace I can't see all the controls in the xaml intellisense
### Steps to Reproduce

1.  Create a new Xamarin.Forms app
2.  Add the XCT nuget
3.  Try to use the XCT on a page in xaml

### Expected Behavior
See all features that XCT has.
### Actual Behavior
I can see just a feel of features provided by the XCT
### Basic Information

- Version with issue:1.0.0-pre5
- Last known good version: NaN
- IDE: Visual Studio 2019 16.7.7
- Platform Target Frameworks: 
  - iOS: 14.2.0.12
  - Android: 11.0.2.0
- Nuget Packages: Xamarin.Forms
- Affected Devices: NaN

### Workaround

NaN
### Reproduction imagery

![image](https://user-images.githubusercontent.com/20712372/101437659-7703a980-38ef-11eb-8252-e2bda31ac724.png)

**Comment by pictos** [comment]
@dansiegel do you know if this can be related to the custom XAML scheme?

**Comment by dansiegel** [comment]
What's the namespace of the API that you're missing? Is the namespace included in the XmlnsDefinition's?

**Comment by jfversluis** [comment]
If you install the pre-release or nightly on a project you can see it.

The XCT.UI.Views namespace is in fact part of the XmlnsDefinition, but odd enough not all views/controls are there. Some are, which makes it even weirder.

**Comment by AndreiMisiukevich** [comment]
Maybe we should put all of our classes inside single namespace (views, effects, behaviors etc.)

**Comment by dansiegel** [comment]
@jfversluis Can you give me a snippet or example. Like which control were you trying to use that wasn't available? What's the XAML context around it? It's hard for me to diagnose without specifics.

**Comment by jfversluis** [comment]
See this screencast [here](https://1drv.ms/v/s!Anrk6U9nRknzg6FChPKXnpmbvKc3ew?e=lQvDRS), just a File > New Xamarin.Forms app where I install the toolkit on (pre5) which shows only a couple of views, but now Expander for instance. If I just ignore IntelliSense and put in Expander it does know its there with all its properties, but just not showing directly which seems weird.

**Comment by dansiegel** [comment]
this seems like a potential bug in XAML Intellisense. I was thinking that you might be referring to the context filtering that occurs, which would be why you won't see a Behavior or ImageSource when your context is a child element of a StackLayout. 

perhaps @maddyleger1 can help us out here.

**Comment by pictos** [comment]
> I was thinking that you might be referring to the context filtering that occurs, which would be why you won't see a Behavior or ImageSource when your context is a child element of a StackLayout.

@dansiegel I don't know if I get your point correctly, but I tried here, and this happens in any control level (Entry > StackLayout > ContentPage). So is this can be a bug on XAML Intellisense? If it's should the XF has the same problem?

**Comment by jfversluis** [comment]
OK so, the cause is not that exciting it seems :D

I've checked with someone from the XAML tooling and they pointed out.. Here it comes.. 🤦  We're setting the `EditorBrowsable` to never. I.e. the Expander, inherits from `BaseTemplatedView` which has [that attribute](https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BaseTemplatedView.shared.cs#L6) and thus it also applies to inherited classes.

So, we need a way to fix that :D
