### ISSUE TITLE
Effect Not compatible With the rounded Image ff:CachedImage

### ISSUE THREAD

**Issue by KevinAnass** [xamarin/XamarinCommunityToolkit#660]
when I want to use touch effect in ff: CachedImage not showing the  native animation

**Comment by AndreiMisiukevich** [comment]
Hi, what effect would you like to show?

**Comment by KevinAnass** [comment]
just the native animation press

**Comment by AndreiMisiukevich** [comment]
@KevinAnass can you please build a small sample?

**Comment by KevinAnass** [comment]
https://github.com/KevinAnass/SampleTest
I test and the native animation not show

**Comment by AndreiMisiukevich** [comment]
> https://github.com/KevinAnass/SampleTest
> I test and the native animation not show

First of all you should use XamarinCommunityToolkit (TouchView migrated to XCT)
![image](https://user-images.githubusercontent.com/10124814/101532698-f6ec4b00-39a5-11eb-82d5-f4dfcbdc57a7.png)

**Comment by KevinAnass** [comment]
so we can't use just the touch view ?

**Comment by roubachof** [comment]
TouchView is now embedded in the XamarinCommunityToolkit nuget package.
Add the XamarinCommunityToolkit nuget to your solution, not TouchView.

**Comment by KevinAnass** [comment]
but I don't know how I can use the touch view embedded in XamarinCommunityToolkit because no docs show how I can get that?

**Comment by AndreiMisiukevich** [comment]
> but I don't know how I can use the touch view embedded in XamarinCommunityToolkit because no docs show how I can get that?
> and this
> https://github.com/MicrosoftDocs/xamarin-communitytoolkit
> not have the touch view

it's in progress.
But they are almost the same (TouchEffect instead of TouchEff)
TouchEffect is not released yet (even in pre-release of XCT), but I believe it should be available in nightly nuget (here more info https://github.com/xamarin/XamarinCommunityToolkit)

**Comment by AndreiMisiukevich** [comment]
@KevinAnass I think NativeAnimation of TouchEffect doesn't work for regular Image as well

**Comment by AndreiMisiukevich** [comment]
@KevinAnass issue resolved here https://github.com/xamarin/XamarinCommunityToolkit/pull/668
You can test it :)
