### ISSUE TITLE
[Enhancement] Flex Grid (Bootstrap style grid for adaptive UI)

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/XamarinCommunityToolkit#675]
## Summary

Xamarin forms is severely hamstrung when it comes to doing adaptive UI.  It doens't even have the same power as UWP xaml to solve these issues, and honeslyt UWP isn't nice about it either.

It would go a long way to both Xamarin Forms and Maui being a best of breed cross platform environment if it had better declaritive markup to be able to have content flow intelligently similar to how bootstrap functions in css/html.

To that end I propose something similar to:

```
    <FlexGrid>
        <FlexRow BindingContext="{Binding to collection for repetition if needed or you can manually have many rows and the flexgrid automatically flows down to fit it's content}">
            <FlexColumn xs="6" md="3" xl="1">
                Other controls
            </FlexColumn>
            <FlexColumn xs="2">
                More controls
            </FlexColumn>
        </FlexRow>
    </FlexGrid>
```

## API Changes

No api changes would be required. Just a new control that would be perfectly suited for the Xamarin Community Toolkit and would make adaptive development across mobile, tablet and desktop VASTLY easier.

The FlexRow need only listen to the size changes and would always be the full width of whatever FlexGrid was. It would allow centering, start, end and justify and allow setting a padding between cols.

## Intended Use Case
Adaptive UI that will properly scale across Mobile, Tablet, Desktop (and ultimately web?!?) solving the problem for Xamarin forms that makes web so much better for doing adaptive design.  

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X ] Just putting this out there for someone to pick up

I'm happy to help but I haven't really written any Xamarin controls like this that allow children in them etc so it's a little out of my purview to start with and get done quickly.

**Comment by VladislavAntonyuk** [comment]
FlexLayout should give you enough power for it

**Comment by JohnGalt1717** [comment]
@VladislavAntonyuk That's fine, I'm asking if it should be part of this suite. It would make sense to do so, and would be highly beneficial to the community as tablet and desktop become more important into the maui world.

**Comment by JohnGalt1717** [comment]
@VladislavAntonyuk et al. I have this written and working pretty well. Need confirmation that this is something desirable for the toolkit and I'm happy to contribute it or just provide you the code and you can put it in if you want.

**Comment by jfversluis** [comment]
Hey @JohnGalt1717 I appreciate your enthusiasm and asking! We're always happy for any contributions :)

As for your concrete question: it seems that @VladislavAntonyuk is saying (in not many words :D) that this can also be done with `FlexLayout`? What would this bring as an advantage over `FlexLayout`? Why are people going to use this over the other one? Is this just `FlexLayout` with a different syntax to make it easier to work with?

What would be your proposal for handling the `xs`, `s`, `l` properties etc. that you mentioned in the sample code? Is that going to be `watch`, `phone`, `tablet`, `tv`? Else how will the developer know what is small and what is large?

I'm linking the idea, but would want to understand a little better what this will do.

Just to manage expectations: whichever way this will go, this won't be in the v1.

cc: @sthewissen

**Comment by JohnGalt1717** [comment]
So using FlexLayout you'd have to do a ton of code behind to do what my does automatically.

The power of bootstrap is that it isn't just a floating set of content. It's a row system that if there is more than 12 cols of content will wrap downwards on the single row instead of just flowing. And then the next row breaks and starts new.

And it has a break system for each xs, s, md, l, xl, xxl that uses the overall width to determine which to use when calculating this which you'd also then have to do custom with FlexLayout. So while you could in theory write up a ton of code every time you use this to make Flexlayout work it would be a horrific task.

With mine you get this:
```

        <controls:FlexRow HorizontalOptions="Center" VerticalOptions="Center">
            <controls:FlexCol Xs="12" Md="6" Lg="4" BackgroundColor="Orange">
                <Label Text="Test 12 xs, 6 md, 4 lg Cols" HeightRequest="250"/>
            </controls:FlexCol>
            <controls:FlexCol Xs="12" Md="8" Lg="6" BackgroundColor="Purple" VerticalOptions="Start">
                <Label Text="Test 12 xs, 8 md, 6 lg more Cols" HeightRequest="100"/>
            </controls:FlexCol>
            <controls:FlexCol Xs="12" Md="4" Lg="2" Xl="1" BackgroundColor="Aquamarine">
                <Label Text="Small 12 xs, 4 md, 2 lg, 1 xl Column" HeightRequest="400"/>
            </controls:FlexCol>
        </controls:FlexRow>
    </controls:FlexGrid>
```

And you're done.  And FlexGrid can override the breakpoints if you want for when sizes are applied and FlexRow allows setting if it's left, right or center aligned rows (so if you do only say 10 cols of 12 it will center them if you want or push to the right etc.) and Start, center, end vertical align so that the cells can center vertically within the FlexRow.  And then each col can override that and force their own height request as you see in the example above.

This will automatically scale the UI exactly like bootstrap does on web for all 3 platforms trivially.  This means that projects can in minutes start creating cross device UI without any custom handling code or logic of their own. It's as easy to use Xamarin Forms to do this as it is to use Bootstrap  + HTML.

The same as the above in flexlayout would take hundreds of lines of code to implement.

This is a major barrier for new developers to both Xamarin Forms and UWP xaml compared to Flutter (there's a package that does the above) or React Native (same, package for it) or any of the website wrapper cross platform tech.  Having this built into Xamarin Community Toolkit and easily accessible with nominclature that is familiar to virtually every developer that hasn't been living under a rock (or in Windows dev only for the last 20 years) means adoption is WAY easier.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
