### ISSUE TITLE
[Enhacement] IconTintColorEffect is not working with ImageSource

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#677]
### Description
IconTintColorEffect is not supporting `ImageSource`, (FileImageSource, UriImageSource, StreamImageSource) some examples where it can be used:

### Steps to Reproduce

1.     <ShellContent Title="Test" ContentTemplate="{DataTemplate local:Test}">
              <ShellContent.Icon>
                  <FileImageSource File="icon-name.png" xct:IconTintColorEffect.TintColor="Red"/>
              </ShellContent.Icon>
        </ShellContent>

2.     <Button>
        <Button.ImageSource>
          <UriImageSource Uri="https://image.flaticon.com/icons/png/512/48/48639.png" xct:IconTintColorEffect.TintColor="Red"/>
        </Button.ImageSource>
       </Button>

3.     <Tab Title="Home" xct:IconTintColorEffect.TintColor="Red">
            <Tab.Icon xct:IconTintColorEffect.TintColor="Red">
                <FontImageSource xct:IconTintColorEffect.TintColor="Red"
                                 FontFamily="FontAwesome"
                                 Glyph="{x:Static fontawesome:IconFont.Home}"/>
            </Tab.Icon>
        </Tab>

### Expected Behavior
The icon tint change to red.
### Actual Behavior
Remains unchanged.
### Basic Information
- Version with issue: 1.0.3

**Comment by Cfun1** [comment]
Ignore for now. I will properly edit this issue later.

**Comment by jBijsterboschNL** [comment]
@Cfun1 it is correct that the IconTintColorEffect doesn't work on ShellContent, as it just hasn't been implemented for this (yet). But for Images, Buttons and ImageButtons it should work! Could you try setting the `xct:IconTintColorEffect.TintColor="Red"` on the Button element itself, instead of on the ImageSource element? As that's where it should be set. Please let me know if this works for you!

**Comment by Cfun1** [comment]
@jBijsterboschNL You are correct it does work for Button I am going to edit my post.

**Comment by Cfun1** [comment]
@pictos have you been able to verify this as an issue ?

**Comment by Cfun1** [comment]
@pictos, @AndreiMisiukevich could someone verify this as a bug ? (or an enhancement?) I  have recently updated the issue by adding the third scenario where it doesn't work with shell Tab, in relation of XF issue mentioned just above it is not possible to change the Shell Tab font icon tint with neither of the ways (XF, xct).

**Comment by pictos** [comment]
@Cfun1 I would say that is an enhancement
