### ISSUE TITLE
[Enhancement] Mark PreserveXamarinCommunityToolkit.cs file as auto-generated

### ISSUE THREAD

**Issue by berhir** [xamarin/XamarinCommunityToolkit#679]
## Summary

The Xamarin Community Toolkit package automatically references the PreserveXamarinCommunityToolkit.cs file. We are using StyleCop and it analyzes all code files that are not recognized as auto-generated.

To solve possible analyzer warnings, it's enough to add a comment at the top of the file:
```
// <auto-generated/>
```

I know it's not really auto-generated, but as far as I know, it's the only way to exclude it from analyzers.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
Hello) Do you add XCT as a project (source code) instead of nuget/dll?

**Comment by berhir** [comment]
We add it as nuget package. But the `Xamarin.CommunityToolkit.targets` file adds the `PreserveXamarinCommunityToolkit.cs` file.

https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/build/Xamarin.CommunityToolkit.targets:
```xml
<Project>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)PreserveXamarinCommunityToolkit.cs"
             Visible="false" />
  </ItemGroup>
</Project>
```

**Comment by AndreiMisiukevich** [comment]
CC @jfversluis

**Comment by jfversluis** [comment]
@pictos you know if this is (still) necessary to include this file at all like that?

**Comment by pictos** [comment]
@jfversluis yes, we still need this file to be able to use the custom scheme for xaml.
I believe that we can add that comment line, suggested by the PR's author, and see if that works

**Comment by roubachof** [comment]
yup it's the standard way to ignore a file with stylecop you can merge this.

**Comment by jfversluis** [comment]
> yup it's the standard way to ignore a file with stylecop you can merge this.

If only it was a PR :P
