### ISSUE TITLE
[Bug] TouchEffect is disabling existing Command when applied to a Button

### ISSUE THREAD

**Issue by tocnar** [xamarin/XamarinCommunityToolkit#687]
### Description
When I add TouchEffect to a Button, existing Command does not work anymore and I have to use TouchEffect.Command.
This makes it time consuming to rewrite all Command bindings to TouchEffect.Command on buttons.
TouchEffect works OK when applied to other controls with TapGestureRecognizers, but not Buttons with Comand.

### Steps to Reproduce
1. Create Button in XAML with any TouchEffect animation properties, e.g.:
```
 <Button  xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
          Text="demo"
          Command="{Binding TestCommand}"
          xct:TouchEffect.NativeAnimation="True"
          />
```
2. run and click on Button, TestCommand does not run

### Expected Behavior
If there is no TouchEffect.Command defined, original Button Command should run when Button is touched

### Actual Behavior
If there any effect added to Button, original Button Command does not run when Button is touched

### Basic Information

- Version with issue: 1.0.0-pre6
- Last known good version: none
- IDE: VS2019
- Platform Target Frameworks:  Android /iOS /All?
- Android Support Library Version: 

### Workaround
Add xct:TouchEffect.Command="{Binding TouchCommand}" to Button
```
 <Button  xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
          Text="demo"
          Command="{Binding TestCommand}"
          xct:TouchEffect.NativeAnimation="True"
          xct:TouchEffect.Command="{Binding TouchCommand}"
          />
```
Run and click on Button, TouchCommand runs, TestComand still does not

**Comment by AndreiMisiukevich** [comment]
Hi @tocnar, thanks for the report.

I wonder, is there any specific reason you apply the touch effect to buttons?
Buttons support Pressed/Released states from the box.

**Comment by tocnar** [comment]
Hi @AndreiMisiukevich, thanks for the response and the lib :)

The intention of adding this to Button was using animations provided by the lib in streamlined fashion.
There are areas in app when simple "ContentView with GestureRecognizer" is used as a button and there are also proper Buttons. 
What I tried to achieve is same animation playing on 'Boxes' and 'Buttons'. 
NativeAnimation provided in example is only a simlified example, I tried using Scale and Opacity animations before.

**Comment by pictos** [comment]
@tocnar can you use the `Command` on TouchEffect?

**Comment by tocnar** [comment]
@pictos Yes, this is what I've described as a workaround. But this is not optimal if I'm including TouchEffect on app with hundreds of buttons. Need to rewrite each xaml then.

**Comment by AndreiMisiukevich** [comment]
It causes another UI glitch on iOS with a button (the pressed state is stuck)

Well, I am not sure that this is a good idea using TouchEffect with Button
How about using Button's events for your purpose (Pressed/Released) ?
