### ISSUE TITLE
[Bug] [Regression] After update from pre5 to pre6 MediaElement.Source binding to string stops working.

### ISSUE THREAD

**Issue by RadoslawKubas** [xamarin/XamarinCommunityToolkit#688]
### Description

After update from pre5 to pre6 MediaElement.Source binding to string stop working in Release on device. In debug it works fine. The problem appears on iOS and Android.

### Steps to Reproduce

1. Create page with `<MediaElement Source="{Binding UriAsString}"/>`

### Expected Behavior

Media is playing in Release and Debug

### Actual Behaviour

Media is playing only in Debug

### Basic Information

- Version with issue: 1.0.0-pre6
- Last known good version: 1.0.0-pre5

### Workaround
Convert UriAsString to MediaSource ( MediaSource.FromUri(new Uri(UriasString)) )

**Comment by pictos** [comment]
@RadoslawKubas can you attach a sample reproduction? That helps us to find the issue faster

**Comment by RadoslawKubas** [comment]
@pictos After update to pre6 only 2nd MediaElement works in Release (in Debug both are fine), before pre6 both are fine in Debug and Release. I use "Link All" in Release, but same problem appears when changed to "Link Frameworks SDKs only".

[MediaElementProblem.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5714311/MediaElementProblem.zip)

**Comment by pictos** [comment]
@RadoslawKubas 
>  I use "Link All" in Release, but same problem appears when changed to "Link Frameworks SDKs only".

That occurs because XCT is linker safe, in other words, we take care to remove unused code for you so `Link All` and `SDks Only` will have the same effect on this lib.

Thank you for the sample, I'll take a look over the weekend and hopefully bring a solution asap.

**Comment by pictos** [comment]
@RadoslawKubas I tested here using the `develop` for android and your sample for ios.

Your sample works fine
![image](https://user-images.githubusercontent.com/20712372/102677667-3bd06880-4182-11eb-8ae1-1016ae8be3b0.png)

but for android don't... If I change the URL, using the same that we use on our sample works

![image](https://user-images.githubusercontent.com/20712372/102677704-59053700-4182-11eb-86b7-7584452ff2d2.png)


On android, the system couldn't grab the metadata information, so I don't know if it's because of the video format "mov" or something related to the URL.

**Comment by RadoslawKubas** [comment]
Hello, I noticed this problem both on Android and iOS for sure (actually, I tested it more on iOS, so I missed this problem with metadata on Android). Did you check it on the real device? I don't understand the reason, but it works fine in simulator in any configuration (also Release), but when I published Release version builded in Microsoft App Center to Test Flight / Google Play Beta problem appears (solution with converting string to MediaSource helps, rolling back to pre5 also works).

**Comment by pictos** [comment]
For iOS I just have the simulator... Android was on a physical device. I trying to track what changed between pre5 and pre6 that could cause this issue. If you try any other link works? Can you try this one https://sec.ch9.ms/ch9/5d93/a1eab4bf-3288-4faf-81c4-294402a85d93/XamarinShow_mid.mp4

**Comment by RadoslawKubas** [comment]
I tested with your link and in my solution problem appears on iOS and Android with pre6, it seems that string to MediaSource TypeConverter not working in Release on device. I will try to do more tests tomorrow and let you know results.

**Comment by RadoslawKubas** [comment]
@pictos Hello, I tested more today. It seems reproduction of the problem is harder than I expect, it is perfectly reproducible in my original solution (with exactly same page code as in the example) but in the new solution with same build settings everything works fine. I modified my original solution where I noticed the problem to just open at the beginning page from the example (but keeps all nuggets and other configuration) and problem appears in Release (both deployed locally and from App Center). It seems that something between pre5 and pre6 bring kind of incompatibility with other nuggets I'm using. I will try to find any more details, but I'm out for holidays tomorrow, be back after the New Year.

**Comment by pictos** [comment]
@RadoslawKubas thank you so much for your help. Meanwhile, I'll try to reproduce it and hopefully find a fix before you return back. Enjoy your free time (:

**Comment by RadoslawKubas** [comment]
@pictos Thx, and have a great holidays too! :) 

In case maybe it will be useful, my problematic solution is using Prism and following nuggets:

```
<ItemGroup>
    <PackageReference Include="DryIoc.dll" Version="4.6.0" />
    <PackageReference Include="MarcTron.Admob" Version="1.6.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.0.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.0.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.22" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Plugin.FirebaseAnalytics" Version="4.1.0" />
    <PackageReference Include="Plugin.InAppBilling" Version="4.0.1-beta" />
    <PackageReference Include="Plugin.StoreReview" Version="3.0.0-beta" />
    <PackageReference Include="Prism.Plugin.Popups" Version="7.2.0.1046" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.0.0.7" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="2.80.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Syncfusion.Xamarin.Buttons" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.Cards" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.Core" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.Expander" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfAutoComplete" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfBusyIndicator" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfChart" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfListView" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfRating" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Xamarin.SfRotator" Version="18.4.0.30" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.0-pre6" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.0-rc1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.1791-pre5" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="7.2.0.1422" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.1791-pre5" />
  </ItemGroup>
```

**Comment by pictos** [comment]
I did more test on my end, and I could see the bug
![image](https://user-images.githubusercontent.com/20712372/103161497-61342680-47c1-11eb-947d-ca9834e903f9.png)

When the linker is on, for some reason we can't convert the String to MediaSource. The Converter isn't called even when the linker is off. I don't know when I can fix it, so I'll let this `up-for-grabs` for now. 
THe workaround is binding to a MediaSource type and not to a string.
