### ISSUE TITLE
[Bug] BadgeView should be round 

### ISSUE THREAD

**Issue by developer9969** [xamarin/XamarinCommunityToolkit#692]
### Description
Trying to use the badge view but noticed that the badgeview is not round but stretches vertically.
Also I think the badge positions should be more internal, it looks too detached.

    <StackLayout Orientation="Vertical">
            <xct:BadgeView
                BackgroundColor="Gainsboro"
                FontAttributes="Bold"
                FontSize="Medium"
                BorderColor="Blue" 
                BadgePosition="BottomRight"
                TextColor="White"
                Margin="0,20,0,0"
                Text="1">
                <Button HeightRequest="60" 
                        WidthRequest="60"
                        CornerRadius="30" 
                        Margin="0,30,0,0"
                        BackgroundColor="Red" 
                        HorizontalOptions="Center"
                        VerticalOptions="Center">
                </Button>
            </xct:BadgeView>
        </StackLayout>

![image](https://user-images.githubusercontent.com/16970109/102580962-878a0000-40f7-11eb-8bc1-f7d1ac3e473b.png)

**Comment by Cfun1** [comment]
Could be related to https://github.com/xamarin/XamarinCommunityToolkit/issues/641
