### ISSUE TITLE
Change namespces to match recommended naming

### ISSUE THREAD

**Issue by skendrot** [xamarin/XamarinCommunityToolkit#70]
## Feature Request:
The namespaces should change from XamarinCommunityToolkit.***.*** to Xamarin.Toolkit.***.***
This follows naming guidelines for C# namespaces

**Comment by jsuarezruiz** [comment]
Hi @skendrot,

There is an open PR with that change: https://github.com/xamarin/XamarinCommunityToolkit/pull/69

**Comment by skendrot** [comment]
Perfect!

**Comment by jamesmontemagno** [comment]
It will be "Xamarin.Toolkit" which will match how UWP toolkit does it.
