### ISSUE TITLE
[Enhancement] Add an effect for Entry to change the cursor color

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#701]
## Summary

Currently it is relatively hard to change the cursor color of an Entry, either needs custom renderer or digging into platform styles. It would be nice to have an effect (applied in xaml as in code) that enables the users to change the cursor color inside an Entry on all target platforms.

## API Changes
Something like `xct:CursorEffect.Color="red"`

## Intended Use Case
Ability to control the color of a cursor inside a control more easily and dynamically.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by sthewissen** [comment]
This is already built into Xamarin itself:
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.iosspecific.entry.setcursorcolor?view=xamarin-forms

**Comment by Cfun1** [comment]
@sthewissen  It is only available for iOS and seems there is no xaml way to set it.

**Comment by pictos** [comment]
@Cfun1 it's feasible on Android, iOS, and UWP, at least? Can you update your first comment with a spec?

**Comment by Cfun1** [comment]
@pictos for UWP and iOS I don't know, but for Android I know it is feasible but no sure if it is a more of  hack than an exposed property/method from Google.

**Comment by Cfun1** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/issues/735

**Comment by jBijsterboschNL** [comment]
@Cfun1, not sure if you still need this, but here is some docs on how to apply an entry cursor color on iOS via Xaml and C# code: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/entry-cursor-color

**Comment by Cfun1** [comment]
@jBijsterboschNL thanks for the suggestion but unfortunately I need it for Android.

**Comment by jBijsterboschNL** [comment]
> @jBijsterboschNL thanks for the suggestion but unfortunately I need it for Android.

@Cfun1 have you tried this?? https://social.msdn.microsoft.com/Forums/en-US/d975148a-1ce0-4fbe-9928-18cb2b0368fa/change-cursor-color-in-entry?forum=xamarinforms
