### ISSUE TITLE
[Enhancement] Entry autofill effect

### ISSUE THREAD

**Issue by krdmllr** [xamarin/XamarinCommunityToolkit#702]
## Summary

Xamarin.Forms `Entry` views seem to lack the ability to allow autofill from a password manager (Tested on Android).

## API Changes

We could follow this tutorial https://mikalaidaronin.info/blog/posts/xamarin-forms-password-autofill/

This would add an effect for entries

```
<Entry
    Keyboard="Email"
    Placeholder="Email...">
    <Entry.Effects>
        <local:AutofillEffect
            Type="Username" />
    </Entry.Effects>
</Entry>
<Entry
    IsPassword="true"
    Placeholder="Password...">
    <Entry.Effects>
        <local:AutofillEffect
            Type="Password" />
    </Entry.Effects>
</Entry
```

## Intended Use Case

Allows the OS to prompt using the default password manager to fill in credentials.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@krdmllr this is a great idea. I read the article as well and looks ok to me, but there's one part that I don't like too much. Is about the `ICrossAutofillManager` where the user needs to call this method manually at the end of the process. Do you know a way to avoid this?

**Comment by jBijsterboschNL** [comment]
> @krdmllr this is a great idea. I read the article as well and looks ok to me, but there's one part that I don't like too much. Is about the `ICrossAutofillManager` where the user needs to call this method manually at the end of the process. Do you know a way to avoid this?

Perhaps also adding the effect to the login button and handle inside the effect this logic to call the dependency commit method (at the click event handler of that button)? @krdmllr if you need any help with this, I will be happy to assist you in any way possible :) good luck on implementing this! Looks like a proper addition to the XCT! :)

**Comment by pictos** [comment]
@jBijsterboschNL this is an option, but that wasn't too clear to me. Like, if the login process fails, should we call that method? if not we can't handle it on our side, because there's no way to know if the login was successful.

**Comment by jBijsterboschNL** [comment]
> > @krdmllr this is a great idea. I read the article as well and looks ok to me, but there's one part that I don't like too much. Is about the `ICrossAutofillManager` where the user needs to call this method manually at the end of the process. Do you know a way to avoid this?
> 
> Perhaps also adding the effect to the login button and handle inside the effect this logic to call the dependency commit method (at the click event handler of that button)? @krdmllr if you need any help with this, I will be happy to assist you in any way possible :) good luck on implementing this! Looks like a proper addition to the XCT! :)

@pictos but does that mind? As the password managers are mostly not smart enough to only store succesfull logins, right? F.e. the Google Chrome extensions just saves any username and password, without knowing if it is a successfull login or not. And also, in the mean time the password could change, making it no longer work. So does it mind if it also stores unsuccesfull logins?

@krdmllr one thing that just came to my mind is that I would also opt for using attached proporties instead of having to attach the entire effect on both Entry controls and perhaps also on the Button.

**Comment by pictos** [comment]
@jBijsterboschNL yes, I think that matters, reading again we need to call the `commit` method when the user leaves the Login Page. And I'm not comfortable handling that on our side in the dark... There's a lot of ways to implement a login flow

**Comment by krdmllr** [comment]
I'm currently implementing it and would stick to the explicit commit call. I agree with @pictos that login flows can difference too much to implement a specific flow. Additionally its not only a login but can be any kind of fill.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
