### ISSUE TITLE
[Bug] Video sound still playing while volume set to 0 on video

### ISSUE THREAD

**Issue by nodoid** [xamarin/XamarinCommunityToolkit#703]
### Description
In my XAML, I have set the volume property to 0  for a video stored on the device. The sound still plays.

### Steps to Reproduce

1. Add a video clip to either the android or iOS project
2.  Set the steam source to the video file
3. Set the Volume property to 0

### Expected Behavior
Video will be silent

### Actual Behavior
Video sound plays

### Basic Information

- Version with issue: 1.0.0.pre5 
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
Android is fixed as a PR for #398
