### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nodoid** [xamarin/XamarinCommunityToolkit#711]
### Description
Latest nuget for X.Toolkit.Effects requires X.A.Support.v7.AppCompat.

I've updated my forms project to use AndroidX and have updated my project to use the latest preview versions of XF and Xam.Toolkit (5.0.0.1829-pre6 and 1.0.0-pre6 respectively)
### Steps to Reproduce

1. update to latest XF and X-toolkit
2. move the android project to AndroidX
3. 

### Expected Behavior
The X.Tookkit.Effects should pull in the AndroidX nuget package or the X.A.Support.v7.AppCompat nuget

### Actual Behavior
It doesn't

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019 1.6,9.0 preview 2
- Platform Target Frameworks: 
  - Android: 10.0, migrated to AndroidX
  -

**Comment by nodoid** [comment]
Downdrading to 1.0.0-pre5 fixes the problem - it can then be upraded to 1.0.0-pre6

**Comment by AndreiMisiukevich** [comment]
This nuget is outdated https://www.nuget.org/packages/Xamarin.Toolkit.Effects/ 
We do not support it. CC @pictos @jfversluis

**Comment by jfversluis** [comment]
As mentioned by Andrei the Effects package is not ours. I will see if we can get it removed to avoids confusion.

Our packages are the Xamarin.CommunityToolkit and Xamarin.CommunityToolkit.Markup.

If you have issues with one of those, please open a new issue, thanks!
