### ISSUE TITLE
[Enhancement] Provide scroll behavior for navigation bar/upper tab bar/bottom tab bar

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#716]
## Summary
Give developers control over the scrolling behavior of the navigation bar for all platforms at Xamarin.Forms level, either page-wis or app-global.

The most required (I suppose) scroll behavior is when a user scrolls down, the navigation bar disappears giving more space to the content, wherever/whenever scrolls up the navigation bar appears again, this can be achieved on Android with combination of flags: `ScrollFlagScroll` and `ScrollFlagEnterAlways`.

### Extra
The same could be done for Shell upper tabs (Tab) and bottom tabs (Tabbar).

## API Changes
Create a new Attached BindableProperty where it is possible to takes multiple flags, or as a beginning takes an Enum value
```
NavigationPage.ScrollBehavior="ScrollFlagScroll | ScrollFlagEnterAlways"
 ```
## Temporary workaround
Using a Shell custom renderer on Android: https://stackoverflow.com/a/65554298/5228202
if someone have a better approach using maybe styles on an Android+XF.Shell app please share it.

## Reference
https://material.io/components/app-bars-top#behavior
[List of flags](https://developer.android.com/reference/com/google/android/material/appbar/AppBarLayout.LayoutParams#scroll_flag_enter_always)

## Future reference
The AppBar will probably needs to provide such feature also https://github.com/xamarin/XamarinCommunityToolkit/issues/545

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
