### ISSUE TITLE
[Enhancement] SearchBar text changed command behavior

### ISSUE THREAD

**Issue by bitclicker** [xamarin/XamarinCommunityToolkit#721]
## Summary

In a previous project, I had a desire to execute a search bar command as the text was being typed into the search bar. I ended up coming up with a behavior that will execute the command that is bound to the search bar as the text is typed

## API Changes

I will create a new class in the Behaviors directory to implement the feature. I will also provider a sample of how to use it. There will be no api changes outside of that

## Intended Use Case

The use case would be for something like a real time filter. As opposed to typing text in, then submitting the text to process you could use this behavior to filter small subsets of data rather quickly.

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by pictos** [comment]
@bitclicker, thank you for your idea! Can you provide a spec for this? That way we can discuss it better.

**Comment by bitclicker** [comment]
@pictos Sure I will work on that tonight. Should I just reference this issue in the spec issue?

**Comment by pictos** [comment]
You can create the spec on this issue. Also, can you explain how this can be better than using the EventToCommandBehavior on the `TextChanged`? My question is to make sure that this proposal has an advantage above a feature that we already have in the lib.

**Comment by bitclicker** [comment]
Oh that's a good point you have there. Now that I think about it there really wouldn't be much of a benefit of having my implementation. Feel free to close out this issue, sorry about that

**Comment by bitclicker** [comment]
This brings no added benefit over using EventToCommandBehavior
