### ISSUE TITLE
hover touch effect not working in Xamarin ios sample

### ISSUE THREAD

**Issue by trossellcullenm** [xamarin/XamarinCommunityToolkit#733]
Hi Hover example works on uwp but not ios

**Comment by AndreiMisiukevich** [comment]
Hi @trossellcullenm 
Thank you for the report.

Does iOS support Hover?

**Comment by trossellcullenm** [comment]
Hi Andre,
I was using your toucheffect sample and I have been trying code using this nugget and also  the xamarin.community toolkit.effects sample with the hover function which is not working. Is there no way of making this work? -- it  does work perfectly on uwp.

**Comment by jfversluis** [comment]
@trossellcullenm how do you expect the hover to work? Are you using iOS with a pointer device like a mouse?

I don't think hover is supported with touch input

**Comment by trossellcullenm** [comment]
Hi Gerald,
On UWP hover works with a mouse or track pad and also with a touch screen holding a finger over an image triggers an event. On the sample app on the hover event the label should rotate. I use the hover event to provide information about the image which is underneath. Hover does not do anything on xamarin.ios.

**Comment by jfversluis** [comment]
I'm suspecting iOS does not expose any states like hover, but not sure. We might need to investigate on that.
