### ISSUE TITLE
[Enhancement] Provide ability to customize different material textfield/Entry properties

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#735]
## Summary

Currently it is relatively hard to change the cursor color of an Entry, either needs custom renderer or digging into platform styles. It would be nice to have an effect (applied in xaml as in code) that enables the users to change the cursor color inside an Entry on all target platforms. 

Also provide the ability to customize different properties that material `textfield` offers directly from xaml. 

## API Changes
Something like:
`xct:CursorEffect.Color="red"`
`xct:CursorEffect.IndicatorUnFocusedColor="red"`

## Intended Use Case
Less use of custom renderers, more easier to change the styling dynamically. 

## Preliminary List of properties
- Cursor color.
- Activation indicator when not focused (when focused I believe it takes PlaceholderColor).

## Reference
https://material.io/components/text-fields

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
