### ISSUE TITLE
[Bug] TouchEffect.NativeAnimation on Image crashes app on Android 5

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#737]
### Description
App crashes when opening the page that contains `Image` with `xct:TouchEffect.NativeAnimation="True"` on Android 5

Error details: 
```
Java.Lang.NoSuchMethodError: no non-static method "Landroid/widget/ImageView;.setForeground(Landroid/graphics/drawable/Drawable;)V"

JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature)
JniType.GetInstanceMethod (System.String name, System.String signature)
JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.set_Foreground (Android.Graphics.Drawables.Drawable value)
PlatformTouchEffect.OnAttached ()
```

### Steps to Reproduce

1. Add image with native animation to the page `<Image xct:TouchEffect.NativeAnimation="True" />`
2. Open the page

### Expected Behavior
Page opens

### Actual Behavior
App crashes

### Basic Information

- Version with issue: 1.0.0
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 5.0.2
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction imagery
![effect](https://user-images.githubusercontent.com/6609929/104081095-2b695600-5235-11eb-9ed6-1f1a98ddacfa.gif)

**Comment by AndreiMisiukevich** [comment]
Seems it's related https://stackoverflow.com/questions/33201712/cant-use-setforeground-method-on-imageview/33201753#33201753

**Comment by maxkoshevoi** [comment]
But app does crash. Maybe Xamarin creates some invalid mappings to Android API

**Comment by AndreiMisiukevich** [comment]
> But app does crash. Maybe Xamarin creates some invalid mappings to Android API

Yes, because actually this method "setForeground" was introduced in API 23

**Comment by maxkoshevoi** [comment]
> > But app does crash. Maybe Xamarin creates some invalid mappings to Android API
> 
> Yes, because actually this method "setForeground" was introduced in API 23

Read that answer wrong. Is it possible to to native animation on images in android 5? If not, could you please just ignore `NativeAnimation="True"` on images on API < 23?

**Comment by AndreiMisiukevich** [comment]
I am afraid it's impossible for ImageView.

Yes, let's ignore native animation for Images with API lower that 23

**Comment by AndreiMisiukevich** [comment]
BTW, try to wrap your image by ContentView or Frame, or StackLayout. It should help
