### ISSUE TITLE
[Bug] {xct:Translate String} works only for currently open pages

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#745]
### Description
If user changes language with `LocalizationResourceManager.Current.SetCulture()`, all strings localized with `{xct:Translate String}` on **currency open** pages get updated to new language, but if user opens new page it will be localized with old language.

### Steps to Reproduce

1. Open some page (page has language A)
2. Change culture to language B with `LocalizationResourceManager.Current.SetCulture()`
3. Open new page with some string localized with `{xct:Translate String}` 
4. New page will be localized with language A instead of B

### Expected Behavior
Newly opened pages respect current language

### Actual Behavior
Newly opened pages localized using language app was opened with

### Basic Information

- Version with issue: 1.0.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Manually localize all strings from the code

**Comment by sthewissen** [comment]
I have seen this behavior in my own app too and have been working on a fix there. I will have to look at how I can implement this the easiest within the current XCT API without breaking it.

**Comment by maxkoshevoi** [comment]
> I have seen this behavior in my own app too and have been working on a fix there. I will have to look at how I can implement this the easiest within the current XCT API without breaking it.

I thinks I found the cause for this issue. `Thread.CurrentThread.CurrenUICulture` is not persisted between pages. To fix it just for your app, you can store culture yourself and set `Thread.CurrentThread.CurrenUICulture` manually in constructor for each page.

I think it should work
