### ISSUE TITLE
Is this project supported? Where is the nuget?

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/XamarinCommunityToolkit#75]
Hey there,

Can't find the package on Nuget, except those with the old name "FormsCommunityToolkit" that haven't been updated since early last year. The link in the current readme here to the dev nuget feed is broken as is the one to the docs.  Is this project still being supported? I saw it referenced in Xamanimation - will that be part of this nuget going forward? 

Please let me know, thanks!

**Comment by bartlannoeye** [comment]
The docs are being moved to docs.microsoft.com. In the meantime you can read the available docs in this [repository](/docs). For the new NuGet packages, I'll have to check with @davidortinau or @jamesmontemagno.

**Comment by jamesmontemagno** [comment]
We will be specifying out the release schedule for what is going into v1 and the initial preview release. We will have an ongoing MyGet which can be found in the readme.
