### ISSUE TITLE
[Enhancement] CoordinatorLayout

### ISSUE THREAD

**Issue by roubachof** [xamarin/XamarinCommunityToolkit#753]
## Summary

Merge @mariusmuntean CoordinatorLayout in XamarinCommunityToolkit.
I know he was interested in merging it (https://twitter.com/MunteanMarius/status/1298368313551093761?s=20)
It's such a brilliant component I just open this feature as a reminder.
Of course there is no rush :)

https://user-images.githubusercontent.com/596903/104386633-db8cd680-5535-11eb-8d7f-1f3e2adf2e22.mp4

## API Changes

https://github.com/mariusmuntean/CoordinatorLayout.Forms

**Comment by AndreiMisiukevich** [comment]
@davidortinau did something similar for xappy https://twitter.com/davidortinau/status/1349016071404199936

**Comment by roubachof** [comment]
Indeed this is how I remember the coordinator layout :)

**Comment by jsuarezruiz** [comment]
@mariusmuntean Would you be interested in porting this functionality? Let me know if we can help in any way.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
