### ISSUE TITLE
[Spec]  Deprecate LocalizationResourceManager.SetCulture method in favor of CurrentCulture property

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#757]
# [The feature] 

Add setter to `CurrentCulture` and deprecate `SetCulture()`. 

Culture is handled via properties everywhere (`CultureInfo.CurrentCulture`, `Thread.CurrentThread.CurrentUICulture`, `AppResources.Culture`), so it feels like `LocalizationResourceManager.CurrentCulture` should have setter too. 
Especially accounting for when #749 will be merged culture will be stored in the backing field anyway. Feels wrong having get-only property to get value of a backing field and separate method to set it

# API

## [ class ]

`LocalizationResourceManager`

### Changes

```cs
[Obsolete("Use " + nameof(CurrentCulture) + " to set culture")]
public void SetCulture(CultureInfo language) => CurrentCulture = language;

public CultureInfo CurrentCulture
{
	get => currentCulture;
	set
	{
		currentCulture = value;
		Invalidate();
	}
}
```
 
# Scenarios

# Platform Compatibility
- Target Frameworks: 
  - iOS:  
  - Android: 
  - UWP: 
# Backward Compatibility

Users will see warning when using `SetCulture()`

# Difficulty : low

**Comment by AndreiMisiukevich** [comment]
I guess, anyway we should add a check

```csharp
if (currentCulture == value) // Or maybe check codes 
    return;
    
currentCulture = value;
Invalidate();
```

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich Even better! We can do this:

```cs
public class LocalizationResourceManager : ObservableObject

...

[Obsolete("Use " + nameof(CurrentCulture) + " to set culture")]
public void SetCulture(CultureInfo language) => CurrentCulture = language;

public CultureInfo CurrentCulture
{
	get => currentCulture;
	set => SetProperty(ref currentCulture, value, null);
}
```
