### ISSUE TITLE
[Bug] CameraView not showing/working on UWP

### ISSUE THREAD

**Issue by JoelPickin** [xamarin/XamarinCommunityToolkit#758]
### Description
I have been trying to use the CameraView in my app. It shows in Android & iOS but not in UWP. To make sure it wasn't by app I setup a new solution, copy & pasted the sample code and ran it. It still didn't show 

### Steps to Reproduce

1. Create a new empty Xamarin project with Android, iOS & UWP selected.
2. Update to Xamarin.Forms 5.0
3. Install the Xamarin.CommunityToolkit nuget package
4. Copy & Paste XAML & code-behind code from XCT.Sample < Xamarin.CommunityToolkit.Sample < Pages < Views < CameraViewPage
5. Run on UWP

### Expected Behavior
See camera the same as you would in the sample app.

### Actual Behavior
Buttons are visible but blank screen where camera should be.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Microsoft Visual Studio Community 2019 - Version 16.8.4
- Platform Target Frameworks: 
 - UWP:  1903

### Workaround
Nope

**Comment by pictos** [comment]
@JoelPickin can you provide a repro?

**Comment by JoelPickin** [comment]
@pictos Repo of the issue 
https://github.com/JoelPickin/CameraViewBug

Thanks for the response

**Comment by redeaglekiller** [comment]
@JoelPickin Hi, you need to add `Microphone `and `Webcam `in the `Package.appxmanifest` as a capability for this to work properly (same as Manifest permissions on Android). 
And you need to set the minVersion under target settings in the UWP project to 19.03 (build 18362)

cheers

**Comment by JoelPickin** [comment]
@redeaglekiller That has worked. Thank you very much for your help.
