### ISSUE TITLE
Integrate MDoc for API documentation

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinCommunityToolkit#76]
See: https://github.com/xamarin/Caboodle/tree/master/Caboodle

**Comment by jamescurran** [comment]
I believe that link now wants to be : https://github.com/xamarin/Essentials/tree/master/Xamarin.Essentials

**Comment by jfversluis** [comment]
Including this is probably still relevant, so keeping this one here so we won't forget

**Comment by Cfun1** [comment]
@jfversluis is this in progress ?

**Comment by jfversluis** [comment]
We have a repo setup here: https://github.com/MicrosoftDocs/xamarin-community-toolkit-api-docs

Now deciding on how to generate the docs and get them there as part of our builds/releases
