### ISSUE TITLE
[Bug] Linking with Sdk and UserAssemblies

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/XamarinCommunityToolkit#761]
### Description

Hi,

i tried to build in release mode with the linker set to "Linking with Sdk and UserAssemblies". We use a couple of converters (InvertedBoolConverter, ListIsNullOrEmptyConverter etc). Starting the App results in a crash.

> Xamarin.Forms.Xaml.XamlParseException: 'Position 9:3. Type xct:InvertedBoolConverter not found in xmlns http://xamarin.com/schemas/2020/toolkit'

### Expected Behavior

Should not crash

### Actual Behavior
![Unbenannt](https://user-images.githubusercontent.com/6727366/104703998-5d3c5a00-5718-11eb-8926-5b5beabb6ff8.PNG)

### Basic Information

- Version with issue: 1.0.0-pre5
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Link with Sdk Assemblies only

**Comment by pictos** [comment]
@AlleSchonWeg if you add this line inside the ctor of App.xaml.cs

`_ = new InvertBoolConverter();`

Does the error disappear?

**Comment by AlleSchonWeg** [comment]
> `_ = new InvertBoolConverter();`

Yes, it fixes the issue. I think the problem is, that the linker removes all code which isn't referenced in c#. Only register the converters in xaml is not enough.
I had a the same problem with my own converters. Adding Preserve Attribute to the classes helps.

**Comment by AlleSchonWeg** [comment]
Hi,

setting Linking to "Sdk Assemblies Only" works for us. The apk size increases only a bit. So no problem for us. You can close this issue if you want.

**Comment by jfversluis** [comment]
Closing this one in favor of the other linked issue. Glad it worked out for you @AlleSchonWeg !
