### ISSUE TITLE
[Bug] ListIsNullOrEmptyConverter doesn't respect ObservableCollection updates

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#768]
### Description

`ListIsNullOrEmptyConverter` (and `ListIsNotNullOrEmptyConverter`, and `ListToStringConverter`) doesn't update its value when `ObservableCollection.Add()` is called.

### Steps to Reproduce

1. Create a page with empty `ObservableCollection`, `ListIsNullOrEmptyConverter` tied to that collection and `IsVisible` attribute of some control, and button that adds one item to the collection
2. Open the page and press the button

### Expected Behavior
Control becomes hidden

### Actual Behavior
Control stays visible

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Add this at the end of ViewModel's constructor `MyCollection.CollectionChanged += (_, _) => OnPropertyChanged(nameof(MyCollection));`
Or after updating collection manually call `OnPropertyChanged(nameof(MyCollection));`

**Comment by AndreiMisiukevich** [comment]
Actually, I don't think it's possible to fix this issue.
And calling ```OnPropertyChanged``` is mandatory in this case.

CC @sthewissen

**Comment by maxkoshevoi** [comment]
Could this be solved if `ListIsNullOrEmptyConverter` were a markup extension, for example? I think this limitation makes this convertor dangerous to use (especially in combination with `ObservableRangeCollection` that supports replacing all items in collection without creating new instance)

**Comment by sthewissen** [comment]
I would also not really be sure how that could be fixed generically as it originates somewhere in the MVVM layer 🤔

Also, @maxkoshevoi all of our converters already inherit from `ValueConverterExtension` which makes them a markup extension if I'm not mistaking.

**Comment by maxkoshevoi** [comment]
@sthewissen can we make it like `Translate` extension? So that this converter would return `Binding` with source `collection` that is passed, and value `is null` or something. And then this Binding would update when collection updates.

**Comment by maxkoshevoi** [comment]
@sthewissen something like this, but without compiler errors:

```cs
/// <summary>
/// Converts the incoming value to a boolean indicating whether or not the value is null or empty.
/// </summary>
public class ListIsNullOrEmptyConverter : ValueConverterExtension, IValueConverter
{
	public class Tmp<T> where T : INotifyCollectionChanged, ICollection
	{
		readonly T observableCollection;

		public Tmp(T observableCollection)
		{
			this.observableCollection = observableCollection;
		}

		public bool IsEmpty => observableCollection.Count == 0;

		public bool IsNotEmpty => observableCollection.Count > 0;
	}

	/// <summary>
	/// Converts the incoming value to a boolean indicating whether or not the value is null or empty.
	/// </summary>
	/// <param name="value">The value to convert.</param>
	/// <param name="targetType">The type of the binding target property.</param>
	/// <param name="parameter">Additional parameter for the converter to handle. Not implemented.</param>
	/// <param name="culture">The culture to use in the converter.</param>
	/// <returns>A boolean indicating if the incoming value is null or empty.</returns>
	public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
	{
		if (value is null)
			return true;

		if (value is INotifyCollectionChanged && value is ICollection t)
		{
			var binding = new Binding
			{
				Mode = BindingMode.OneWay,
				Path = nameof(Tmp.IsEmpty),
				Source = new Tmp(t)
			};
			return binding;
		}

		if (value is IEnumerable list)
			return !list.GetEnumerator().MoveNext();

		throw new ArgumentException("Value is not a valid IEnumerable or null", nameof(value));
	}

	public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
		=> throw new NotImplementedException();
}
```

**Comment by maxkoshevoi** [comment]
Created PR where this converter can return `Binding`, but turns out convertors can only return simple values.
Code in PR throws `Object must implement IConvertible`.

**Comment by AndreiMisiukevich** [comment]
> Created PR where this converter can return `Binding`, but turns out convertors can only return simple values.
> Code in PR throws `Object must implement IConvertible`.
> 
> While testing I created sample page for this converter, so created a PR for that #780. It illustrates that user need to manually notify page on collection change.

Thanks :)
Since the PR with the sample is merged, I think we can close this issue. (because, as it was mentioned, it is impossible to implement).
