### ISSUE TITLE
[Bug] We can create new instances of the LocalizationManager

### ISSUE THREAD

**Issue by pictos** [xamarin/XamarinCommunityToolkit#769]
### Steps to Reproduce

1.  Create a new XF app with XCT
2. try `var p = new LocalizationResourceManager();`
3. You can create new instaces

### Expected Behavior
Compiler doesn't let me create new instances
### Actual Behavior
I can create new instances
### Workaround
none

### Reproduction imagery

none

### Reproduction Link

none

**Comment by AmrAlSayed0** [comment]
What is wrong with creating a new resource manager? I'm working on app with multiple modules (projects) and each with its own string resources and the main app project (the one the has the App.xaml.cs) references all of them and is the one responsible for changing the culture if the user requests it. This change will mean I can only use one ResourceManager class which is not the case for moderately complex apps.

**Comment by pictos** [comment]
@AmrAlSayed0, you don't need to create one instance per `.resx` file. The LRM can handle all `.resx` that you have with one instance.

**Comment by AmrAlSayed0** [comment]
@pictos How is that possible? There is only one instance and the Init takes only one ResourceManager which handles only one ```.resx``. Also the Translate extension also uses ```.Current`` which limits it to one ResourceManager too.

**Comment by pictos** [comment]
@AmrAlSayed0 
If you run our sample App you can see it, we just use the Current instance. I'm not an expert on that area, to explain how that works in deep, but the ResourceManager uses the CultureInfo to select what translation file it will pick.

**Comment by AmrAlSayed0** [comment]
@pictos No. I may have not made myself clear. I will explain my situation so it is clear what my use case is. My app has several ```csproj```s. For example
```Common.Forms.csproj``` // Has some stuff that any app I will work on will use (Converters, Common Interfaces, etc..) + ```Common.Form.AppResource.resx```
```App.Payment.csproj``` // Has pages and controls and services regarding the payment section of my app + ```App.Payment.AppResource.resx```
```App.Identity.csproj``` // Has pages and controls and services regarding the identity and login sections of my app + ```App.Identity.AppResource.resx```
```App.Common.csproj``` // Has some app-specific controls but any module or part of my app will need to use + ```App.Common.AppResource.resx```
```App.csproj``` //The main Xamarin.Froms project that has the first navigation + ```App.AppResource.resx```

Everyone of these ```.resx``` files have multiple translations. One ```LocalizationManager``` can't handle all of them.

**Comment by pictos** [comment]
Probably when you access the `Current` property the XCT will create one per assembly. In any case, the XCT should be able to handle that. Can you try [this nugget](https://github.com/xamarin/XamarinCommunityToolkit/pull/770#issuecomment-761856481) on your project and let me know if that works?

**Comment by maxkoshevoi** [comment]
@AmrAlSayed0 You should create one common place to store all your translations, and put it somewhere where all projects would have access to it (I assume in your case it's App.Common). If you need to separate them, you can prefix each resource name with project name for example. 

@pictos I believe, `Current` localization manager is created ones per process, not per assembly. So if user has multiple resource files, we cannot handle that with `Current`. 
Side note: I think we should throw exception if `Init` is called second time to avoid confusion. This will break our tests though since each of them needs to `Init` manager with mock values.

**Comment by GalaxiaGuy** [comment]
> You should create one common place to store all your translations

There are quite a few situations where that is not possible, or at least a lot more work.

**Comment by maxkoshevoi** [comment]
@AmrAlSayed0 there is a separate issue to support multiple resource managers #832
