### ISSUE TITLE
[Bug] [CameraView] When capturing video, MediaCaptured event video file is empty (android at least)

### ISSUE THREAD

**Issue by vtkachen111** [xamarin/XamarinCommunityToolkit#777]
### Description
When capturing video on android, the media captured event has a file path to video, but looking at that file, its length is 0
### Steps to Reproduce

1. Create cameraview
2. Subscribe to mediacaptured
3. Try to capture video
4. open file at path: MediaCapturedEventArgs.Video.File 
### Expected Behavior
The video file to be there and to not be empty
### Actual Behavior
File exists but is empty
### Basic Information

- Version with issue:1.0.1
- Last known good version:NA
- IDE:vs 2019
- Platform Target Frameworks: 
  - Android: Android 10 api 29
- Nuget Packages:
- Affected Devices:

**Comment by georgegoudie** [comment]
I've ben running a few tests, sometimes multiple files are created one or more of which are empty. Occasionally a good video is recorded, but normally alongside a few zero length files

**Comment by vtkachen111** [comment]
In mediacaptured create a filestream to that path that it gives you, the file size is always 0 for me.

**Comment by ManuLin** [comment]
I'm facing the very same issue when recording videos on Android. Is there any solution / fix for this yet?

**Comment by cuethenoise** [comment]
I call Camera.Shutter() to start the video and Camera.Shutter() to stop.

I'm seeing 2 files created one is always empty and the empty one is the path given to the MediaCaptured event.

**Comment by vtkachen111** [comment]
Seems to be resolved with 1.2.0
