### ISSUE TITLE
[Bug] MediaElement UWP Release build not working

### ISSUE THREAD

**Issue by StapSoft** [xamarin/XamarinCommunityToolkit#788]
### Description
The MediaElement is not working in the UWP release mode

### Steps to Reproduce

1. Build the Xamarin.CommunityToolkit.Sample.UWP sample in Release mode (with "Compile with .NET Native tool chain" enabled)
2. Run the sample program and navigate to Views-MediaElement

### Expected Behavior
The sample should play the video of James Montemagno
### Actual Behavior
Empty screen, no video
### Basic Information
It will run in Debug mode (with "Compile with .NET Native tool chain" disabled)

- Version with issue: 1.02
- Last known good version: ?
- IDE: Visual Studio Professional 2019, Version 16.8.4
- Platform Target Frameworks: 
   - UWP:  version 18362

**Comment by sjorsmiltenburg** [comment]
i think i just created a duplicate of this bug

**Comment by willtam** [comment]
I was able to resolve this by adding the following line into the UWP's app.xaml.cs file:

assembliesToInclude.Add(typeof(Xamarin.CommunityToolkit.UI.Views.MediaElementRenderer).GetTypeInfo().Assembly);

**Comment by StapSoft** [comment]
I tried it and it works fine.
Thanks.

**Comment by bbhxwl** [comment]
> I was able to resolve this by adding the following line into the UWP's app.xaml.cs file:
> 
> assembliesToInclude.Add(typeof(Xamarin.CommunityToolkit.UI.Views.MediaElementRenderer).GetTypeInfo().Assembly);

1.0.3   MediaElementRenderer does not exist

**Comment by StapSoft** [comment]
Version 1.0.3 MediaElementRenderer does exist  in "Xamarin.CommunityToolkit.UI.Views" (this solved the issue)
Version 1.1.0 MediaElementRenderer does NOT exist anymore

**Comment by Agredo** [comment]
Just tested this for Xamarin Community Toolkit 2.0.1, This Bug can be closed!  assembliesToInclude.Add(typeof(Xamarin.CommunityToolkit.UI.Views.MediaElementRenderer).GetTypeInfo().Assembly);

**Comment by pictos** [comment]
Thanks @Agredo
