### ISSUE TITLE
[Discussion] Create v1 Feature List

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinCommunityToolkit#79]

**Comment by jfversluis** [comment]
Let's determine what we want to have in a first v1 version

**Comment by sthewissen** [comment]
I would say at the very least:

- A rehash of what WAS in trimmed of excess things that are already in XF.
- The converters mentioned by @Depechie in #116 if the original author agrees.
- I would say some common effects and behaviors but I want to hold a quick tweet inquiry how many people actually use a lot of these, as I haven't seen them come up as often as I expected.

**Comment by jfversluis** [comment]
I think we have more than enough to release an initial version. So let's close this for now. I'd like to look into how we can work a bit more structure with the project boards and all, but that's something different.
