### ISSUE TITLE
[Enhancement] Place the docs' hyperlink to the docs page.

### ISSUE THREAD

**Issue by jingliancui** [xamarin/XamarinCommunityToolkit#790]
It seem like the [xct_docs](https://docs.microsoft.com/en-us/xamarin/community-toolkit/) not have a hyperlink in this [page](https://docs.microsoft.com/en-us/xamarin/)

**Comment by jfversluis** [comment]
I think that is being worked on, @davidbritch ?

**Comment by Cfun1** [comment]
I believe this should be on https://github.com/MicrosoftDocs/xamarin-communitytoolkit am I wrong ?

**Comment by davidbritch** [comment]
@cfun1 Kinda. Really it should be in https://github.com/MicrosoftDocs/xamarin-docs as that's the repo where the issue will be actioned.

**Comment by jfversluis** [comment]
OK, trusting this will be taken care of and is outside of our influence atm. Closing this one here
