### ISSUE TITLE
[Bug]  

### ISSUE THREAD

**Issue by jamsoft** [xamarin/XamarinCommunityToolkit#791]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Not sure what the intention was, but this doesn't look right :)

**Comment by jamsoft** [comment]
Ooops! Sorry all!
