### ISSUE TITLE
[Bug] Is MediaElement supported on Xamarin.Forms.UWP?

### ISSUE THREAD

**Issue by sjorsmiltenburg** [xamarin/XamarinCommunityToolkit#794]
### Description

Is MediaElement supported on Xamarin.Forms.UWP?

I can't find any special setup required in the documentation for UWP and I can't get it working
(v1.0.2 in combination with XF 5.0.0.1905)
The uwp version of the sample application also does not work for me.

**Comment by jfversluis** [comment]
Lets merge this one with #788
