### ISSUE TITLE
[Proposal] Validators

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#8]
_From @rubit0 on December 21, 2016 19:2_

As the title says, what about having validators?

Some ideas:
- valid email address
- not empty
- matches given regex
- is above or below a specific value
- etc.

I think this would be a pretty nifty and usefull thing to have in this Toolkit.
Opinions?

_Copied from original issue: FormsCommunityToolkit/Behaviors#1_

**Comment by weitzhandler** [comment]
Very compelling.
Validation is a total pain currently.
Validation in XF should be integrated, and should provide better ties to `INotifyDataErrorInfo`, DataAnnotations validation.
Also, `IValidatableObject` should be implemented for the Xamarin PCL.

**Comment by HideDev** [comment]
Sounds great!)

**Comment by jsuarezruiz** [comment]
Nice idea!

**Comment by pauldipietro** [comment]
Validators would be fine, but perhaps we should do these on a per-item basis to target for a future release, as it's easier to track that way.

**Comment by jfversluis** [comment]
Seems like a number of people is enthusiastic about this! Worth to still consider then, so let's keep it here for reference.

**Comment by roubachof** [comment]
https://github.com/FluentValidation/FluentValidation is doing a pretty good job with validators, and the model is platform-agnostic.

**Comment by SunnyMukherjee** [comment]
@roubachof This is a very comprehensive library for almost every type of validator, including Email, Empty, NotEmpty, CreditCard, RegularExpressions, etc.  Any developer should be able to use any validator in their apps.  I'm not sure if there is a need to reinvent in this toolkit what's already invented in this library.

**Comment by jfversluis** [comment]
I think we have a good number of validation behaviors right now. So let more ideas come in through separate issues
