### ISSUE TITLE
[Enhancement] Support ObservableRangeCollection operations by Index

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#800]
## Summary
Add support of `InsertRange/RemoveRange/ReplaceRange` by `Index` on `ObservableRangeCollection`. 

These API methods are approved in .NET: https://github.com/dotnet/runtime/issues/18087

## API Changes
```cs
// Inserts a range
// Raises CollectionChanged (NotifyCollectionChangedAction.Add)
void InsertRange(int index, IEnumerable<T> collection);

// Removes a range.
// Raises CollectionChanged (NotifyCollectionChangedAction.Remove)
void RemoveRange(int index, int count);

// Will allow to replace a range with fewer, equal, or more items.
// Raises CollectionChanged (NotifyCollectionChangedAction.Replace)
void ReplaceRange(int index, int count, IEnumerable<T> collection);
```

## Intended Use Case
Edit collection ranges by index.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
