### ISSUE TITLE
[Bug] [Android] TouchEffect NativeAnimation triggered twice

### ISSUE THREAD

**Issue by taenito** [xamarin/XamarinCommunityToolkit#804]
### Description

Using TouchEffect with  `xct:TouchEffect.NativeAnimation="True"` will trigger the animation twice during a quick click.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Enterprise 2019 (16.8.4)
- Platform Target Frameworks: 
  - iOS:  
  - Android: Android SDK 29 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction imagery

![bKmrYGXfmu](https://user-images.githubusercontent.com/6932633/105845346-e9813380-5fda-11eb-9423-b3cecf2e85a9.png)

![ezgif-3-224d1fdd741b](https://user-images.githubusercontent.com/6932633/105845367-eede7e00-5fda-11eb-8650-8904b3153ee5.gif)

### Reproduction Link

[https://github.com/xamarin/XamarinCommunityToolkit/tree/main/samples](url)

**Comment by AndreiMisiukevich** [comment]
It seems StartRipple and EndRipple methods are redundant now

**Comment by AndreiMisiukevich** [comment]
@taenito can you verify that the issue is gone in this PR: https://github.com/xamarin/XamarinCommunityToolkit/pull/817

**Comment by taenito** [comment]
@AndreiMisiukevich
The issue is gone with your PR.
I tested in your sample app and my app.
