### ISSUE TITLE
[Enhancement] PINVIEW

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#806]
this feature would be nice
https://github.com/MGohil/XFPINView

**Comment by pictos** [comment]
if @MGohil wants to bring his control to this awesome package, that will be very welcome!

**Comment by jfversluis** [comment]
I'd love to have it! I do want to see some proposal for a spec first with all the APIs but I like the idea :)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
