### ISSUE TITLE
[Bug] Apply an explicit style to an Entry using TextValidationBehavior with InvalidStyle

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#807]
### Description
from https://github.com/xamarin/XamarinCommunityToolkit/discussions/748

It seems impossible to apply an explicit style on an `Entry` which is using the `InvalidStyle` of `TextValidationBehavior`, you may say just append/add the explicit style to the `InvalidStyle` definition, but the issue is that the latter is only triggered upon text changed event I believe, thus the style won't be applied all the time.

Any ideas?

If I remove the Behaviors, `SomeEntryStyle` is applied, if I put back, only `InvalidEntryStyle` style will be applied when conditions met. the issue here is that `SomeEntryStyle`  should be applied regardless.

I am not sure if I am missing something or something needs to change/improve in xct that why I have put it as a bug for now.

### Steps to Reproduce
```
      <Entry Text="text"
                   Placeholder="palceholder"
                   Style="{StaticResource SomeEntryStyle}">
                <Entry.Behaviors>
                    <xct:EmailValidationBehavior DecorationFlags="Trim"
                                                 InvalidStyle="{StaticResource InvalidEntryStyle}"/>
                </Entry.Behaviors>
            </Entry>
```
```
    <ContentPage.Resources>
        <Style x:Key="SomeEntryStyle"
               TargetType="Entry">
            <Setter Property="TextColor" Value="White"/>
            <Setter Property="PlaceholderColor" Value="Blue"/>
            <Setter Property="BackgroundColor" Value="Purple"/>
            <Setter Property="Visual" Value="Material"/>
        </Style>

        <Style x:Key="InvalidEntryStyle"
               TargetType="Entry">
            <Setter Property="TextColor" Value="Red"/>
        </Style>
    </ContentPage.Resources>
```

### Basic Information

- Version with issue: 1.0.2
- Last known good version: -
- IDE: vs2019
- Platform Target Frameworks: All

**Comment by AndreiMisiukevich** [comment]
Hi
The problem is that **InvalidStyle** overrides **Style**, right?

you can set **Valid** style instead of setting **Style** property

**Comment by Cfun1** [comment]
@AndreiMisiukevich it will not work because only one style will be applied at a time either valid or invalid.
In my example I want that PlaceholderColor, BackgroundColor and Visual properties are always applied from SomeEntryStyle weather is it valid or no.

It will be nice if invalidstyle will only override concerned properties (in example TextColor) not overwrite the whole style. A solution would be to define styles like this (but it is duplicate and ugly):
```
        <Style x:Key="InvalidEntryStyle"
               TargetType="Entry">
            <Setter Property="TextColor" Value="Red"/>
            <Setter Property="PlaceholderColor" Value="Blue"/>
            <Setter Property="BackgroundColor" Value="Purple"/>
            <Setter Property="Visual" Value="Material"/>
        </Style>

        <Style x:Key="ValidEntryStyle"
               TargetType="Entry">
            <Setter Property="TextColor" Value="White"/>
            <Setter Property="PlaceholderColor" Value="Blue"/>
            <Setter Property="BackgroundColor" Value="Purple"/>
            <Setter Property="Visual" Value="Material"/>
        </Style>

      <Entry Text="text"
                   Placeholder="palceholder">
                <Entry.Behaviors>
                    <xct:EmailValidationBehavior DecorationFlags="Trim"
                                                 InvalidStyle="{StaticResource InvalidEntryStyle}"
                                                 ValidStyle="{StaticResource ValidEntryStyle}"/>
                </Entry.Behaviors>
            </Entry>
```

**Comment by Cfun1** [comment]
@AndreiMisiukevich is this to be considered as a verified bug or an enhacement ?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich is this to be considered as a verified bug or an enhacement ?

Actually, I am not sure that such behavior can be implemented at all...

**Comment by Cfun1** [comment]
@AndreiMisiukevich I believe the VSM approach will be a solution to this issue.

**Comment by Cfun1** [comment]
Closed in https://github.com/xamarin/XamarinCommunityToolkit/pull/955
