### ISSUE TITLE
[Enhancement] Add VisualStates & Events for Expanding & Collapsing

### ISSUE THREAD

**Issue by njsokalski** [xamarin/XamarinCommunityToolkit#808]
## Summary
I would like to see VisualState(s) for Expanded & Collapsed, along with events for Expanding, Expanded, Collapsing, & Collapsed

## API Changes
public event EventHandler Expanding;
public event EventHandler Expanded;
public event EventHandler Collapsing;
public event EventHandler Collapsed;
//These may or may not have the standard EventArgs or a custom inherited class, this may be determined later

## Intended Use Case
The Expanding & Collapsing events would be used to give the option of cancelling expanding or collapsing. This may be desired if there is a need to confirm with a popup, or possibly validate information. The Expanded & Collapsed events would be used to modify the UI after opening or closing the Expander. The Visual States (Expanded & Collapsed) would be used to modify the appearance of the Expander (most likely the Header) based on whether the Expander is expanded or collapsed. Most of the scenarios using any of these would be a simpler of performing tasks that are probably currently handled using the PropertyChanged event

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
