### ISSUE TITLE
[Bug] [Android] Slider and CarouselView don't work in SideMenuView

### ISSUE THREAD

**Issue by OwenCross289** [xamarin/XamarinCommunityToolkit#810]
### Description
Sliders and CarouselViews don't scroll or swipe within a SideMenuView on Android. No issue on iOS. I assume this would also be the case for all controls that use a drag effect?

Setting  xct:SideMenuView.MenuGestureEnabled to false does not fix this either. 

Downgrading from latest Xamarin.Forms package to 5.0.0.1829-pre6 gave expected behaviour back.

### Steps to Reproduce

1. Create a SideMenuView
2. Add a Slider or CarouselView
3. Try and scroll / swipe 
4. Example xaml below.
```xaml
 <xct:SideMenuView x:Name="SideMenuView">
        <!-- MainView -->
        <StackLayout
            Orientation="Vertical"
            BackgroundColor="Gold">

            <Button  />

            <Button  />
            <Slider HorizontalOptions="Fill" Minimum="0" Maximum="170" MinimumTrackColor="Red" MaximumTrackColor="Red"/>

        </StackLayout>

        <!-- LeftMenu -->
        <BoxView
            BackgroundColor="Orange"
            xct:SideMenuView.Position="LeftMenu"
            xct:SideMenuView.MenuWidthPercentage=".5" />

        <!-- RightMenu -->
        <BoxView
            BackgroundColor="LightGreen"
            xct:SideMenuView.Position="RightMenu"
            xct:SideMenuView.MenuWidthPercentage=".3" />

    </xct:SideMenuView>
```

### Expected Behavior
Controls to scroll and swipe.

### Actual Behavior
Controls do not scroll and swipe.

### Basic Information

- Version with issue:  Xamarin.Forms 5.0.0.1874
- Last known good version:  Xamarin.Forms  5.0.0.1829-pre6
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - Android: 10
- Nuget Packages: 
-       <PackageReference Include="Xamarin.Forms" Version="5.0.0.1874" />
        <PackageReference Include="Xamarin.Essentials" Version="1.6.0" />
        <PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.0" />
        <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.1874" />
        <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie" Version="4.0.8" />
        <PackageReference Include="Sharpnado.Shadows" Version="1.2.0" />
        <PackageReference Include="OxyPlot.Xamarin.Forms" Version="1.1.0-unstable0011" />
        <PackageReference Include="SkiaSharp.Views.Forms" Version="2.80.3-preview.24" />
        <PackageReference Include="SkiaSharp" Version="2.80.3-preview.24" />
- Affected Devices: Android

### Workaround

Downgrading from latest Xamarin.Forms package to 5.0.0.1829-pre6 gave expected behaviour back.

### Reproduction imagery

![ScrollView bug](https://user-images.githubusercontent.com/59806069/106280068-5132bb00-6235-11eb-88ff-99b95907d9cf.gif)

### Reproduction Link
https://github.com/OwenCross289/XamarinNav/tree/CollectionView
This branch on the renderers view and advertising view show this bug

**Comment by AndreiMisiukevich** [comment]
@PureWeen @jsuarezruiz Hey folks 

Is anything related to touch-management changed from 5.0.0.1829-pre6 to 5.0.0.1874 that might cause this issue?
