### ISSUE TITLE
[Bug] Binding: 'Xamarin.CommunityToolkit.ObjectModel.AsyncCommand' cannot be converted to type 'Xamarin.Forms.Command'

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#820]
### Description
I have a CustomControl with a Button.
```
<?xml version="1.0" encoding="UTF-8" ?>
<ContentView
    x:Class="TestFody.Control.MyCustomView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    x:Name="this"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <ContentView.Content>
        <Button Command="{Binding MyCustomCommand, Source={x:Reference this}}" Text="Press" />
    </ContentView.Content>
</ContentView>
```
I use this in my view (two times):

```
        <customcontrol:MyCustomView MyCustomCommand="{Binding CustomCommand}" />
        <customcontrol:MyCustomView MyCustomCommand="{Binding CustomAsyncCommand}" />

```

Then I use CustomCommand and CustomAsyncCommand 

```
            CustomCommand = new Command(async () => { await Application.Current.MainPage.DisplayAlert("TEST", "test", "Ok"); });
            CustomAsyncCommand = new AsyncCommand(Test);

        }

        async Task Test()
        {
            await Application.Current.MainPage.DisplayAlert("TEST", "test async command", "Ok");
       
 }
```
With @jamesmontemagno 's AsyncCommand, I have the warning  **Binding: 'Xamarin.CommunityToolkit.ObjectModel.AsyncCommand' cannot be converted to type 'Xamarin.Forms.Command'**

### Steps to Reproduce

as described above

### Expected Behavior
CustomAsyncCommand should popup an alert

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 1.0.2
- Last known good version: unknown
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[Test](https://www.dropbox.com/s/ejskkwb9gqi5te3/TestFody.rar?dl=0)

**Comment by mtsrdr** [comment]
The issue seems to be in your own code.

You cannot bind AsyncCommand to a Xamarin.Forms.Command. Instead, you can use the System.Windows.Input.ICommand interface in your custom view as the return type of your BindableProperty:

  ```
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MyCustomView : ContentView
    {

        public static readonly BindableProperty MyCustomCommandProperty = BindableProperty.Create(nameof(MyCustomCommand), typeof(ICommand), typeof(MyCustomView));

        public MyCustomView()
        {
            InitializeComponent();
        }

        public ICommand MyCustomCommand
        {
            get
            {
                return (ICommand)GetValue(MyCustomCommandProperty);
            }
            set
            {
                SetValue(MyCustomCommandProperty, value);
            }
        }
    }
```

**Comment by acaliaro** [comment]
Excellent @mtsrdr it works! Thanks
