### ISSUE TITLE
[Bug] SideView does not open if Bind State property in XAML

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#822]
### Description
I am uning SideView.

If I use 

```
        <xct:SideMenuView  x:DataType="viewmodel:InventarioViewModel"
            State="{Binding IsMenuVisible, Converter={StaticResource BoolToSideMenuViewStateConverter}}"> 
```
and convert the boolean IsMenuVisibile with something like this:

```
   public class BoolToSideMenuViewStateConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            SideMenuState sideMenuState;
            if (value != null && value is bool)
                sideMenuState = ((bool)value) ? SideMenuState.LeftMenuShown : SideMenuState.MainViewShown;
            else 
                sideMenuState = SideMenuState.MainViewShown;

            System.Diagnostics.Debug.WriteLine("SideMenuState = " + sideMenuState, "BoolToSideMenuViewStateConverter");

            return sideMenuState;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

When I change IsMenuVisible, the SideView does not appear.

If I use

`        <xct:SideMenuView x:Name="sidemenu" x:DataType="viewmodel:InventarioViewModel">
`

and in then codebehind

            if (((InventarioViewModel)BindingContext).IsMenuVisible)
                sidemenu.State = SideMenuState.LeftMenuShown;
            else
                sidemenu.State = SideMenuState.MainViewShown;

The SideView appears

### Steps to Reproduce

See above

### Expected Behavior
The SideView should show / hide depending by a value

### Actual Behavior
Nothing happens
### Basic Information

- Version with issue: 1.0.2
- Last known good version: unknown
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
@acaliaro thanks for the report)

Can you please clarify the issue:

Do you assume the issue that the SideMenuView doesn't open the menu **on start** (e.g. if you set the State = LeftMenuShow in xaml).

**Comment by AndreiMisiukevich** [comment]
If the issue is that **bool to state converter not working**, then you should check your code and verify you raise PropertyChanged after bool value. (I mean If you open the page and SideMenuView is **CLOSED** by default)

**Comment by acaliaro** [comment]
> @acaliaro thanks for the report)
> 
> Can you please clarify the issue:
> 
> Do you assume the issue that the SideMenuView doesn't open the menu **on start** (e.g. if you set the State = LeftMenuShow in xaml).

        <xct:SideMenuView x:Name="sidemenu" x:DataType="viewmodel:InventarioViewModel" State="LeftMenuShown">

If I set the State directly, I think I should see the menu, but there is not:

![image](https://user-images.githubusercontent.com/5759350/106707491-9407e080-65f1-11eb-8840-2acc7c0ba728.png)

But if I swipe, it appears:

![image](https://user-images.githubusercontent.com/5759350/106707519-a2ee9300-65f1-11eb-9cbf-1919977e26a7.png)

**Comment by acaliaro** [comment]
> If the issue is that **bool to state converter not working**, then you should check your code and verify you raise PropertyChanged after bool value. (I mean If you open the page and SideMenuView is **CLOSED** by default)

I use Binding and converters everywhere, and I don't rise PropertyChanged directly because I use Fody

**Comment by AndreiMisiukevich** [comment]
Well, it means that the problem is only with the initial load, right?
It doesn't show the menu on the initial View's load (if the ShowMenu option selected).

**Comment by acaliaro** [comment]
> Well, it means that the problem is only with the initial load, right?
> It doesn't show the menu on the initial View's load (if the ShowMenu option selected).

The problem is when State is binded but also when State is set directly to LeftMenuShown. Maybe I have another property to set?( I see that you talk about a ShowMenu option...)

**Comment by acaliaro** [comment]
@AndreiMisiukevich with datatrigger it works:

```
            <xct:SideMenuView.Triggers>
                <DataTrigger
                    Binding="{Binding IsMenuVisible}"
                    TargetType="xct:SideMenuView"
                    Value="true">
                    <Setter Property="State" Value="LeftMenuShown" />
                    <!--  multiple Setters elements are allowed  -->
                </DataTrigger>
            </xct:SideMenuView.Triggers>
```


For me, it's ok. If you want to close the issue, no problem, but I'd be very curious to know why databinding doesn't work

**Comment by AndreiMisiukevich** [comment]
I fixed setting State from xaml (so you can make the side menu opened by default)

**Comment by AndreiMisiukevich** [comment]
@acaliaro you need to implement ConvertBack as well (because State property works in two-way binding mode)

```csharp
public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    => value?.Equals(SideMenuState.LeftMenuShown) ?? false;
```
