### ISSUE TITLE
[Bug] EventToCommandBehavior not raised with ContentPage Appearing event

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#827]
### Description
It seems that is not possible to have the Appearing event as a Command. Am I doing something wrong?

```
    <ContentPage.Behaviors>
        <xct:EventToCommandBehavior Command="{Binding OnAppearingCommand}" EventName="Appearing" />
    </ContentPage.Behaviors>
```

### Steps to Reproduce

See above

### Expected Behavior
I would like to have the OnAppearingCommand executed when Appearing event raise

### Actual Behavior
OnAppearingCommand is not executed

### Basic Information

- Version with issue: 1.0.2
- Last known good version: unknownd
- IDE: Visual Studio 2019 16.8.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
It would be super helpful if you could attach a reproduction project, thanks!

**Comment by acaliaro** [comment]
> It would be super helpful if you could attach a reproduction project, thanks!

[TesiDemo.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5926733/TesiDemo.zip)

LoginPage and LoginViewModel

Thanks @jfversluis

**Comment by mtsrdr** [comment]
@acaliaro There is a typo in the command name of your reproduction project. It won't work.

`OnAppearingCommand != OnApperingCommand`

<img width="500" src="https://user-images.githubusercontent.com/33626789/106986417-11deff80-674a-11eb-9ac9-223b0ea3e4a9.png" />

<img width="800" src="https://user-images.githubusercontent.com/33626789/106986603-75692d00-674a-11eb-8805-f8437486211c.png" />

**Comment by acaliaro** [comment]
@mtsrdr I am a stupid. Thanks!
