### ISSUE TITLE
StringFormatConverter as an IValueConverter

### ISSUE THREAD

**Issue by njsokalski** [xamarin/XamarinCommunityToolkit#829]
I would like to see an IValueConverter in the Xamarin.CommunityToolkit.Converters section. This would be similar to the String.Format function, only for use in XAML rather than codebehind. The following is C# of a version I created and use:
public class StringFormatConverter : IValueConverter
{
	public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
	{ return string.Format(parameter.ToString(), value); }
	public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
	{ return value; }
}
My version is pretty straightforward & basic, so whether you would end up adding extra capabilities such as null checks, validating the format string (parameter), specializing for when value is certain types, etc. is a decision probably better left to more experienced designers like you. I use this converter at some point in almost all my apps, so I think it would be a good addition for the XCT. Thank you for considering my suggestion.

**Comment by pictos** [comment]
@njsokalski, thanks for your suggestion!
 If I understood correctly what you are asking already exist in xaml bindings, [here is the doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/string-formatting) for it, can you confirm if your proposal is different?

**Comment by njsokalski** [comment]
You're right, it does exist! I don't know how I missed that, I think I was looking for a Converter (since that is what I always used in the past), so I guess I never noticed this. Thank you for letting me know about it, it will definitely save me time by not needing to include code that just replicates an existing feature!
