### ISSUE TITLE
Sample App doesn't compile

### ISSUE THREAD

**Issue by rampyodm** [xamarin/XamarinCommunityToolkit#83]
## Bug 
Version Number of Plugin: Downloaded code on Apr 5, 2018.
Device Tested On: Visual Studio for Mac version 7.4.1 (build 48).

### Expected Behavior
App to compile and run.
### Actual Behavior
Nuget packages fail to download.

### Steps to reproduce the Behavior
Download or clone the code. Open samples sln file. Attempt to build.

Errors:
Running non-parallel restore.
Reading project file /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/Samples.csproj.
Restoring packages for /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/Samples.csproj...
Restoring packages for .NETStandard,Version=v2.0...
Resolving conflicts for .NETStandard,Version=v2.0...
Checking compatibility of packages on .NETStandard,Version=v2.0.
Checking compatibility for Samples 1.0.0 with .NETStandard,Version=v2.0.
Checking compatibility for NETStandard.Library 2.0.1 with .NETStandard,Version=v2.0.
Checking compatibility for Xamarin.Forms 2.5.0.122203 with .NETStandard,Version=v2.0.
Checking compatibility for Animations 1.0.0.0 with .NETStandard,Version=v2.0.
Checking compatibility for Effects 1.0.0.0 with .NETStandard,Version=v2.0.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v2.0.
Checking compatibility for Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 with .NETStandard,Version=v2.0.
Package Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.NETCore.UniversalWindowsPlatform 6.0.6 supports:
  - netcore50 (.NETCore,Version=v5.0)
  - uap10.0.15138 (UAP,Version=v10.0.15138)
Checking compatibility for Win2D.uwp 1.21.0 with .NETStandard,Version=v2.0.
Package Win2D.uwp 1.21.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Win2D.uwp 1.21.0 supports: uap10.0 (UAP,Version=v10.0)
Incompatible packages: 2
Committing restore...
Generating MSBuild file /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/obj/Samples.csproj.nuget.g.props.
Generating MSBuild file /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/obj/Samples.csproj.nuget.g.targets.
Writing lock file to disk. Path: /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/obj/project.assets.json
Writing cache file to disk. Path: /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/obj/Samples.csproj.nuget.cache
Restore failed in 136.65 ms for /Users/user/temp/XamarinCommunityToolkit-master/Samples/Samples/Samples/Samples.csproj.

NuGet Config files used:
    /Users/user/.config/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
Restore failed.

Build output says "NuGet packages need to be restored before building"...

**Comment by jamesmontemagno** [comment]
This is all being fixed in #82

**Comment by jamesmontemagno** [comment]
That said. I am adding this to the library:

Xamarin Community Toolkit is built with the new SDK style projects with multi-targeting enabled. This means that all code for iOS, Android, and UWP exist inside of the Xamarin Community Toolkit project.

If building on Visual Studio 2017 simply open the solution and build the project.

If using Visual Studio for Mac the project can be built at the command line with MSBuild. To change the project type that you are working with simply edit Toolkit.csproj and modify the TargetFrameworks for only the project type you want to use.
