### ISSUE TITLE
[Bug] CollectionView inside SideView's "MainView" does not scroll

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#831]
### Description

I have a CollectionView inside the SideView's MainView.
This does not scroll.
If I swipe the LeftMenu, after the swipe the CollectionView can scroll

### Steps to Reproduce

See the attached project:
1- Do login without username and password
2- Select a voice on the popup tapping on the list
3- Press "Inventario", Appears a page WITHOUT SideView. The CollectionView scroll
4- Press "Scadenze", Appears the same page WITH SideView, the collectionView does not scroll

### Expected Behavior
CollectionView should scroll

### Actual Behavior
CollectionView does not scroll

### Basic Information

- Version with issue: 1.0.2
- Last known good version: unknown
- IDE: Visual Studio 16.8.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms 5.0.0.1931
- Affected Devices: Zebra TC51

### Reproduction Link

[TesiDemo.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5926146/TesiDemo.zip)

**Comment by AndreiMisiukevich** [comment]
This PR https://github.com/xamarin/XamarinCommunityToolkit/pull/824 can fix your issue as well

**Comment by Cfun1** [comment]
@acaliaro could you please confirm if the pr mentioned by @AndreiMisiukevich fixed this issue?

**Comment by AndreiMisiukevich** [comment]
@acaliaro please try the latest version of NuGet. If the issue still exists, please reopen this ticket.
Thanks

**Comment by acaliaro** [comment]
> @acaliaro could you please confirm if the pr mentioned by @AndreiMisiukevich fixed this issue?

It works
