### ISSUE TITLE
[Enhancement] Localization manager with more than one resource manager

### ISSUE THREAD

**Issue by WebDucer** [xamarin/XamarinCommunityToolkit#832]
## Summary

Currently the localization manager (singleton) can be initialized only with one resource manager. This is often not enough.

We ceurrently use own implementation for this purpose, that accept a list of resource managers (form common library, different app modules).

## API Changes

Non breaking changes:

https://github.com/xamarin/XamarinCommunityToolkit/blob/f62c078146a05ef92e548f71d6cbb22cea89ff8c/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs#L16

```csharp
ResourceManager[] resourceManagers = new ResourceManager[0];
```

https://github.com/xamarin/XamarinCommunityToolkit/blob/f62c078146a05ef92e548f71d6cbb22cea89ff8c/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs#L25-L32

```csharp
public void Init(params ResourceManager[] resources) =>
    resourceManagers = resources;

public void Init(ResourceManager resource, CultureInfo initialCulture)=>
    Init(initialCulture, resource);

public void Init(CultureInfo initialCulture, params ResourceManager[] resources)
{
    resourceManagers = resources;
    currentCulture = initialCulture;
}
```

https://github.com/xamarin/XamarinCommunityToolkit/blob/f62c078146a05ef92e548f71d6cbb22cea89ff8c/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs#L34-L35

```csharp
public string GetValue(string text)
{
    string translated = null;

    foreach (var rm in resourceManagers)
    {
        translated = rm.GetString(text, CurrentCulture);
        if (translated != null)
        {
            break;
        }
    }

    return translated;
    // Or as LINQ
    // return resourceManagers.Select(s => s.GetString(text, CurrentCulture))
    //    .FirstOrDefault(f => f != null);
}
```

## Intended Use Case

Usage with more than one resource manager.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by AmrAlSayed0** [comment]
I don't think this would work correctly in case of multiple string resources with the same name but in different resource files. What I suggest it modify the ```LocalizationResourceManager``` to take either one ```ResourceManager``` or multiple and modify the current ```GetValue``` to check if there is only one ```ResourceManager``` registered, otherwise throw and exception. Also, add another ```GetValue``` that takes an extra parameter of ```ResourceManager``` which the method will use.

The ```TranslateExtension``` can be modified to take an optional reference to the ```ResourceManager``` it should use. If it is not set then it should assume that there is only one ```ResourceManager``` and use the one parameter ```GetValue``` method

**Comment by brminnick** [comment]
Thanks Eugen! 

Before approving this, I'm going to play around with `LocalizationResourceManager` to see if there's a way we can utilize RESX to do this for us.

If we can leverage RESX, we might be able to save ourselves a bunch code 🤞

**Comment by WebDucer** [comment]
@AmrAlSayed0 The possibility of _ovveriding_ translations, is feature that we already use. E.g. we override some translations from core library in our RESX in the application. During the initialization we put the most relevant resource manager first (Application) and least relevant as last (Core).

**Comment by WebDucer** [comment]
@brminnick This would be fine. I also miss now the possibility to set the culture on all resources in one place. Now we need to set the culture to all resource managers used in the application, if user set new culture.

**Comment by maxkoshevoi** [comment]
@WebDucer In your implementation you are searching through all resource managers until you find string with needed key. 
So each key is unique across all resource managers? I don't think this is the case for all users that use several resource managers.
In your use case what is the point of having multiple resource managers if you are searching though all of them anyway?

Could you please take a look at #1047 and see if that implementation suits your needs?

**Comment by WebDucer** [comment]
@maxkoshevoi No, the key is not unique. #1047 could match our needs.

**Comment by maxkoshevoi** [comment]
@WebDucer Thank you for validating #1047

If key is not unique, then LRM would always return first value it finds (and never any others). How do you deal with that in your project? I don't use multiple resource managers, so would be happy to hear how people deal with them in the real world.

Benefits of your approach is that you don't need to provide `TranslateExtesnion` with resource manager every time you use it, but in #1047 you do (except when you want to use default one).

**Comment by WebDucer** [comment]
@maxkoshevoi We explicitly use the possibility for everriding translations.

To prevent unwanted overriding, we use prefixes for translation keys, dependent on origin RESX project, e.g.:
- Common library
    - `COM_ButtonCancel`
    - `COM_ButtonAccept`
    - `COM_LabelCompany`
- App module 1
    - `MODA_LabelServer`
    - `MODA_LabelUrl`
    - `COM_LabelCompanny` (override the common library translation)

During the initialization of LRM we add the most relevant manager (mostly of the App) as first, and least relevant last (libraries).

In C# code of the App we explicitly use the resource managers directly (e.g.: `CommonLocalization.COM_LabelCompany` or `AppLocalization.COM_LabelCompany`). The multi registration we use in XAML extension (and in libraries code over localization service). So we are always able to override translations in libraries.

The overrides are mostly used, if we have more languages, that the library provides (most of our app has 3 languages, but some are translated in 8).

**Comment by maxkoshevoi** [comment]
@WebDucer Got it, thank you. 
I can sill add this override logic in #1047 by making `DefaultResourceManager`(s) a collection. 
- This would allow users to provide multiple resource managers as default ones, so they don't need to provide RM to `TranslateExtension` every time, 
- or they can provide RM every time to avoid possibility of unwanted override, and to not need to add prefixes to the keys
- or they can do some combination of both

**Comment by maxkoshevoi** [comment]
> I can sill add this override logic in #1047 by making `DefaultResourceManager`(s) a collection.

I think this needs to be a separate issue. Let's add basic support for multiple resource managers first, and add our custom override logic later.

My concerns are that this logic
- Will be used only for XAML, there is no alternative for C#
- Isn't present in vanilla resource manager, and might be confusing to the users
- I'm not sure how widely it is used/needed

But I don't have strong opinion either way, for now just want to merge basic multi-resource support.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
