### ISSUE TITLE
[Enhancement] Support iOS Accessibility Traits

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#838]
## Summary

Create an effect to support setting iOS 14 accessibility traits - https://developer.apple.com/documentation/objectivec/nsobject/uiaccessibility/accessibility_traits

An article was written on how to create the effect - https://stu.dev/xamarin-forms-accessible-headings/

## Intended Use Case
Improve app accessibility.

For example, in my case, there is a home button that's an SVG the voice over is attempting to describe the SVG but is completely wrong. Setting the accessibility trait to none should fix the issue - https://developer.apple.com/forums/thread/672389

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
@IeuanWalker is that what is implemented with #1087 ?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
