### ISSUE TITLE
Android blur effect request.

### ISSUE THREAD

**Issue by rampyodm** [xamarin/XamarinCommunityToolkit#84]
## Feature Request:
The Android side of the Blur effect seems to be missing. Would it be possible to add that? Any recommendations on an approach? All of the examples I've seen are using 3rd party Java libraries to do this, which won't work in Xamarin.

**Comment by pauldipietro** [comment]
#38

**Comment by rampyodm** [comment]
Gee, thanks for not responding and just closing this.
