### ISSUE TITLE
[Enhancement] On Android DisplayToastAsync should use Toast not SnackBar

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#840]
## Summary

I am confused to see that `DisplayToastAsync()` is in fact using `SnackBar` and not `Toast` on Android, I don't know about the other platforms but for Android this is confusing. I suggest we introduce/use [https://developer.android.com/guide/topics/ui/notifiers/toasts](toasts) when it is possible.

## Intended Use Case
To follow what a developer expect from a Toast in Android.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by roubachof** [comment]
I don't know what is it called DisplayToastAsync(), should be called DisplaySnackbarAsync()...

**Comment by Cfun1** [comment]
Guess what!? [DisplaySnackBarAsync](https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/PageExtension.shared.cs#L46) already exists beside `DisplayToastAsync()`. I don't know what is the difference?
Good to know I was not aware that toast has been deprecated  👍🏻 .

**Comment by roubachof** [comment]
MMhh must be some kind of confusion about the semantic. 
DisplayToastAsync seem to display a snackbar without an action associated
DisplaySnackBarAsync for a snackbar associated with an action

**Comment by roubachof** [comment]
Should be both called DisplaySnackbarAsync() with method overload from my point of view

**Comment by pictos** [comment]
@VladislavAntonyuk can you answer this question?

**Comment by VladislavAntonyuk** [comment]
It is by design: https://github.com/xamarin/XamarinCommunityToolkit/issues/260

**Comment by roubachof** [comment]
Yup, that's what I thought: it's semantic misunderstanding.
Snackbar can have action attached or not. 
Snackbar without action is not a toast, it's a Snackbar without action :-)
It's true that it's confusing but eeeeeh....

**Comment by Cfun1** [comment]
so it will be kept with Toast name or changed to something else (the snack bar without action) ?

**Comment by roubachof** [comment]
The issue is that it would be a breaking change... I guess you'll have to live with this x)

**Comment by VladislavAntonyuk** [comment]
I can add that it happens only on Android. Because only Android has native Snackbar and toast.
Further more Snackbar on Android unfortunately has only 1 button, but other platforms supports multiple buttons.
I think we need to discuss if we want to use native implementation or we can customize it with "StackLayout"
