### ISSUE TITLE
[Enhancement] More control for xct:TouchEffect

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#842]
## Summary

xct:TouchEffect is awesome so thanks for that! However there's two features I am sorely missing:

1) Ability to route the animation to another view. Ponder for example the following "button" consisting of a frame, label and image:
<img width="334" alt="Screenshot 2021-02-06 at 9 55 54" src="https://user-images.githubusercontent.com/60286968/107112615-a0927000-6861-11eb-9f04-2e07d75157ed.png">

If an `xct:TouchEffect.NativeAnimation="True"` is added to the root frame, the entire "button" will animate when interacted with:
<img width="331" alt="Screenshot 2021-02-06 at 9 56 09" src="https://user-images.githubusercontent.com/60286968/107112627-b869f400-6861-11eb-9fed-d972cac5a54c.png">

Expected is of course that (at least on iOS) just the contents would fade out; this is exactly what would happen if this was just a plain button.

I can't find a way to accomplish this with XCT's TouchEffect - if I add the effect to the root frame then the entire construct will fade out when interacted with (as in the above screenshot), and if I add it to say the label only then the fade will only take place if the user taps exactly on the label portion.

I would like to add the effect to the root of the construct and either:
a) have a flag controlling whether only children should be animated
b) have the ability to define animation target via a binding

Maybe there is some way of accomplishing this already but I just haven't found it?

2) Event support. I have a ton of events that are currently fired from TapGestureRecognizers in my project. (The reasoning for this is that the view handles visualisation like message boxes etc, and they subsequently invoke the vm commands if relevant). I couldn't find a way to specify events to xct:TouchEffect, only commands. Is there a reason why events are not supported? I can't see the feature as complete with only command support.

3) Ability to opt out some element in a hierarchy from an animation.
Use case is for example a button that has a 'badge' that appears if there's notifications.
The badge in this example should not fade out when the user taps the button.

Thank you.

## API Changes

On top of my head:

Feature 1:
`xct:TouchEffect.AnimateChildrenOnly="True"`
and/or
`xct:TouchEffect.AnimationTarget="{x:Reference someView}"`

Feature 2:
`xct:TouchEffect.Event="MyEvent"`
`xct:TouchEffect.LongPressEvent="MyLongPressEvent"`

Feature 3:
`xct:TouchEffect.OptOutFromAnimationHierarchy="True"`

## Intended Use Case

See above.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X ] Just putting this out there for someone to pick up

**Comment by Tommigun1980** [comment]
The lack of event support is quite effectively preventing me from really starting to use xct:TouchEffect. Could someone maybe instruct me as I'm thinking I'm missing something?
Thank you so much!

**Comment by AndreiMisiukevich** [comment]
Hi, maybe the "State" property will be helpful for you. You can observe its value (Normal or Pressed) and change other views appearance

**Comment by AndreiMisiukevich** [comment]
> xct:TouchEffect.Event="MyEvent"
> xct:TouchEffect.LongPressEvent="MyLongPressEvent"

Why don't you want to use commands?

**Comment by Tommigun1980** [comment]
> > xct:TouchEffect.Event="MyEvent"
> > xct:TouchEffect.LongPressEvent="MyLongPressEvent"
> 
> Why don't you want to use commands?

Hi and thanks for the reply.

Why would it matter tbh? Legacy, stubbornness, technical reasons, inherited projects, preference, whatever. Events are a concept in Xamarin.

(In this particular case it has to do with separation of concerns, where views handle presentation and view models logic only; and in certain cases it makes sense to handle it this way. But it shouldn’t really matter from an APIs point of view as events are a thing.)

**Comment by Tommigun1980** [comment]
> Hi, maybe the "State" property will be helpful for you. You can observe its value (Normal or Pressed) and change other views appearance

Thank you, I’ll look into it.

**Comment by AndreiMisiukevich** [comment]
> (In this particular case it has to do with separation of concerns, where views handle presentation and view models logic only; and in certain cases it makes sense to handle it this way. But it shouldn’t really matter from an APIs point of view as events are a thing.)

Got it, thanks for the explanation.

You can use "Completed" event in TouchEffect, but you will have to add TouchEffect manually.

```xaml
<ContentView>
    <ContentView.Effects>
        <xct:TouchEffect Completed="..."
```

**Comment by Tommigun1980** [comment]
> > (In this particular case it has to do with separation of concerns, where views handle presentation and view models logic only; and in certain cases it makes sense to handle it this way. But it shouldn’t really matter from an APIs point of view as events are a thing.)
> 
> Got it, thanks for the explanation.
> 
> You can use "Completed" event in TouchEffect, but you will have to add TouchEffect manually.
> 
> ```
> <ContentView>
>     <ContentView.Effects>
>         <xct:TouchEffect Completed="..."
> ```

Ah thank you!
Could ‘Completed’ (and presumably ‘LongCompleted

**Comment by Tommigun1980** [comment]
> > (In this particular case it has to do with separation of concerns, where views handle presentation and view models logic only; and in certain cases it makes sense to handle it this way. But it shouldn’t really matter from an APIs point of view as events are a thing.)
> 
> Got it, thanks for the explanation.
> 
> You can use "Completed" event in TouchEffect, but you will have to add TouchEffect manually.
> 
> ```
> <ContentView>
>     <ContentView.Effects>
>         <xct:TouchEffect Completed="..."
> ```

Accidentally clicked close, reopening :P

Ah thank you!
Could ‘Completed’ (and presumably ‘LongCompleted’ or whatever it’s called) be upped to same first citizen status as the Commands? Ie add them as attachable properties?

I’m thinking that Xamarin APIs usually expose both command and event properties so it was unexpected not to find the event variants, and I’d love to use them as attachable properties. I’m also concerned that if not all properties exist as attachable properties users will miss out on features (like I almost did), as one could reasonably expect that they are all exposed. I don’t think many people will try both ways to figure out what exists and doesn’t exist, so this great great API may become underutilized for some.

Thank you again!

**Comment by AndreiMisiukevich** [comment]
@Tommigun1980 I don't think it's possible to convert "events" to attachable properties.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 I don't think it's possible to convert "events" to attachable properties.

Oh gotcha! I had no idea, well then it would be hard to implement I guess :D
I will follow through with your suggestion of adding it as a separate block then, thank you for the info!

**Comment by Tommigun1980** [comment]
> Hi, maybe the "State" property will be helpful for you. You can observe its value (Normal or Pressed) and change other views appearance

Hi. I'd like to test this but I'm not sure exactly how to do it.

The only thing I could come up with is a 'DataTrigger' on the inner elements that should be affected, but DataTriggers can't bind to attached properties (`xct:TouchEffect.State` in this case).

So I'm not sure how to accomplish this - i.e. opting out certain elements from the native effect, while the handler is on the root element (see the first image in this ticket).

Thank you for insights!

**Comment by AndreiMisiukevich** [comment]
Hi @Tommigun1980 

Let's summarize this conversation

1) Events support is added, but for using events you should add TouchEffect as a regular Effect to Effects collection.
2) Opt-out & Animation target features seem quite similar to me. 
While implementing opt-out is not possible, we still can add animation target and I hope it would be sufficient for both cases

**Comment by AndreiMisiukevich** [comment]
But I am not sure it's easily to implement for native animations (cuz they are focused on the view with the touch effect).
For your case, I can propose adding a content view inside frame and attaching touch effect to that nested content view (so the frame won't be affected)

**Comment by AndreiMisiukevich** [comment]
@Tommigun1980 where are we with this issue?
I don't follow the conversation anymore :)

What should we implement to close this issue?

**Comment by AndreiMisiukevich** [comment]
Closing this ticket since I don't follow the conversation.
Could you please open a separate ticket for each "problem" or possible "enhancement" you want to see if you still interesteed?

**Comment by gsgou** [comment]
> > Hi, maybe the "State" property will be helpful for you. You can observe its value (Normal or Pressed) and change other views appearance
> 
> Hi. I'd like to test this but I'm not sure exactly how to do it.
> 
> The only thing I could come up with is a 'DataTrigger' on the inner elements that should be affected, but DataTriggers can't bind to attached properties (`xct:TouchEffect.State` in this case).
> 
> So I'm not sure how to accomplish this - i.e. opting out certain elements from the native effect, while the handler is on the root element (see the first image in this ticket).
> 
> Thank you for insights!

@Tommigun1980 did you find a workaround besides binding to a property for this one ?
