### ISSUE TITLE
[Bug] xct:TouchEffect breaks button events

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#844]
### Steps to Reproduce

xct:TouchEffect breaks button events:

```xaml
<Grid
    xct:TouchEffect.NativeAnimation="True"
    xct:TouchEffect.ShouldMakeChildrenInputTransparent="False">
    <Button
        Text="Click me"
        Clicked="Button_Clicked" />
</Grid>
```

The button's event is never fired.

### Expected Behavior

xct:TouchEffect shouldn't break events.

### Actual Behavior

xct:TouchEffect breaks events.

### Basic Information

- Version with issue: 1.0.2
- Last known good version: None?
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.2
- Android Support Library Version: Only tested on iOS.

**Comment by pictos** [comment]
@Tommigun1980 if you use the Commands and events provided by TouchEffect, that works?

**Comment by AndreiMisiukevich** [comment]
Try to set ShouldMakeChildrenInputTransparent="False"

**Comment by Tommigun1980** [comment]
> @Tommigun1980 if you use the Commands and events provided by TouchEffect, that works?

Hi and thanks for the reply.
Unfortunately I can’t.

**Comment by Tommigun1980** [comment]
> Try to set TouchEffect.ShouldMakeChildrenInputTransparent="False"

Hi Andrei. I do in fact have it there.

I didn’t investigate this more than just noticing it broke the logic and proceeded to revert back, but I think it only happens with events.

**Comment by Tommigun1980** [comment]
Let me clarify on the previous,

```c#
  xct:TouchEffect.NativeAnimation="True"
  xct:TouchEffect.ShouldMakeChildrenInputTransparent="False"
```

only broke _some_ listeners, but not all. I didn't look into it further but I think `ShouldMakeChildrenInputTransparent="False"` worked properly with Commands inside the children, but not with events.

So

```c#
// works
<Grid
    xct:TouchEffect.NativeAnimation="True"
    xct:TouchEffect.ShouldMakeChildrenInputTransparent="False">
    <Button
        Text="Click me"
        Command="{Binding SomeCommand}" />
</Grid>

// doesn't work
<Grid
    xct:TouchEffect.NativeAnimation="True"
    xct:TouchEffect.ShouldMakeChildrenInputTransparent="False">
    <Button
        Text="Click me"
        Clicked="Button_Clicked" />
</Grid>
```

I will try to find the time to verify this later today, but that was the impression I got on a quick cursory look (I reverted my code back as some of the buttons stopped working).

Thank you.

**Comment by AndreiMisiukevich** [comment]
Hm, https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs#L219-L220

**Comment by AndreiMisiukevich** [comment]
It seems it doesn't work well even with Command.

**Comment by AndreiMisiukevich** [comment]
Unfortunately, it isn't designed to be working this way.
You can
1) Add effect directly to Button
OR
2) Move Command/Clicked to be bound to effect's Command/Completed event.

**Comment by AndreiMisiukevich** [comment]
Sorry, but I am closing this issue since this effect is not supposed to cover this case.
