### ISSUE TITLE
[Bug] xct:TouchEffect: 'NativeAnimation' doesn't revert if used with 'Command'

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#845]
### Steps to Reproduce

1. Turn on `xct:TouchEffect.NativeAnimation="True"`.
2. Also add `xct:TouchEffect.Command="{Binding SomeCommand}"` to the same element.

### Expected Behavior

When releasing the finger over the element and after the command has invoked, the native effect should go away.

### Actual Behavior

When releasing the finger over the element and after the command has invoked, the native effect doesn't go away.

This only happens if a 'Command' is also specified.

### Basic Information

- Version with issue: 1.0.2
- Last known good version: None?
- IDE:
- Platform Target Frameworks: 
  - iOS: 14.4
  - Android: Only tested this on iOS

### Workaround

Use a separate TapGestureRecognizer for the command.

**Comment by AndreiMisiukevich** [comment]
@Tommigun1980 could you please build a sample app?

**Comment by Tommigun1980** [comment]
> @Tommigun1980 could you please build a sample app?

Hi. I will do that.

In my case the command invokes a native photo picker, so the issue may only appear if the entire app’s focus changes in the command, in case someone runs into this before it’s fixed.

**Comment by Tommigun1980** [comment]
I wonder if this is a similar situation to https://github.com/xamarin/XamarinCommunityToolkit/issues/850.

**Comment by AndreiMisiukevich** [comment]
@Tommigun1980 any updates regarding the sample app :)?

**Comment by AndreiMisiukevich** [comment]
I guess it happens because the animation stops when the app goes to the background.

**Comment by AndreiMisiukevich** [comment]
possibly fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1056
Please review and feel free to reopen :)
