### ISSUE TITLE
[Enhancement] Support ShadowEffect on UWP

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#847]
## Summary
Support `ShadowEffect` on UWP platform. Currently only supported by `Android/iOS/macOS` on #725.

## API Changes
No API change, add UWP implementation of `ShadowEffect`. Maybe using [DropShadow](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.dropshadow).

## Intended Use Case
Use `ShadowEffect` on UWP platform.

## Who Will Do The Work?
- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
We already have this for other platforms, we definitely need this for UWP

**Comment by MichaelStgt** [comment]
Have a look at the Windows Community Toolkit. They have a shadow for windows UWP and I implemented it in my Controls Toolbox, but only in a Custom Frame Control.

**Comment by sattew** [comment]
> Have a look at the Windows Community Toolkit. They have a shadow for windows UWP and I implemented it in my Controls Toolbox, but only in a Custom Frame Control.
Did you mean this [shadow](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls.Core/DropShadowPanel/DropShadowPanel.cs)?

**Comment by brminnick** [comment]
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/1102
