### ISSUE TITLE
[Enhancement] Calendar Control

### ISSUE THREAD

**Issue by Softtinn** [xamarin/XamarinCommunityToolkit#848]
## Summary

It would have been really cool with a Calendar control that supports selecting multiple dates (and/or date ranges). I think this control would have been a great addition to the toolkit. 

I'm not sure about how to implement it, but maybe a grid could be used as a base to it?

Here's a couple of examples:
![image](https://user-images.githubusercontent.com/7129814/107128506-876bdc80-68be-11eb-9d83-24f2c7b3b2ea.png)
![image](https://user-images.githubusercontent.com/7129814/107128527-ab2f2280-68be-11eb-8985-237f4dd4dd1c.png)

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by Cfun1** [comment]
Could you please include the **Intended Use Case** section ? Selecting discontinuous dates or selecting a period of time (successive days)

**Comment by jfversluis** [comment]
I'd love to have a more extensive calendar control for sure! But before anyone gets started on this I'd love to see a more detailed specification on how we would want to implement that.

**Comment by ahoefling** [comment]
I built a calendar control a long time ago that used 100% shared code. It was highly customizable where every day square was just another `ContentView` or `DataTemplate` (it has been a long time since I looked at it). I would be willing to contribute it to a branch as a starting point. It isn't fully featured as the focus was just the grid of days.

**Comment by Cfun1** [comment]
@ahoefling "highly customizable" this must be nice, under the hood it is using the native Pickers or no?

**Comment by ionixjunior** [comment]
Hi guys! I am developing a calendar view component for Xamarin.Forms. It is still in development and at this moment I am working in the component layout. 

I am customizing the layout using styles classes, so I believe that this will be easy to create many kinds of layout for the calendar.

What features does the calendar view have so far?
- Navigate to previous and next months using buttons
- Hightlight the current day
- Visualize events of the day with a dot indicator
- Select some day of the calendar to get the selected date to load some data in the app
- Choose the starting day of the week (sunday, monday...)

The project is available here https://github.com/ionixjunior/Xalendar

**Comment by Luiz-Franco** [comment]
Hi! I think a good feature would be the ability to disable specific days based on a list of DateTime or DayOfWeek enum.

**Comment by ahoefling** [comment]
@ionixjunior I took a look at your Xalendar control and that looks much better than my control. Maybe you can share the specification for it so we can discuss what it would look like in the XCT?

**Comment by ionixjunior** [comment]
@ahoefling Initially, I thought to develop a simple calendar view with the following features:

- Show days of the current month
- Highlight the current day
- Highlight the selected day
- Choose the start day of the week (Sunday, Monday, Tuesday, etc)
- Add events to a calendar to see some indicator in the days that contains events
- Navigate to previous and next month using buttons
- Invoke an action to the app retrieve the first and last day of the month navigated (useful to load the events of the navigated month)
- Easy way to change the style or customize the calendar layout

All features listed above are working. 

What is not included at this time and I plan to develop?

- Show a preview of the previous and next month days
- Navigate between months using gestures
- Select a month to start the calendar rendering

About the layout of the calendar, I am creating some themes based on styles. The component will have some built-in themes for user choice and will be possible for the user to create your own theme for the calendar. So, this way will be easier to customize the calendar setting styles for calendar elements, differently from other solutions that we have a lot of bindable properties to change colors, styles, layout dispositions, etc.

@jfversluis this is a new component that I and some people of the community are developing and it is not a problem for me to donate this codebase to XCT.

As soon as possible I will update the docs of the project to explain better how the calendar is working and how it can be customized.

**Comment by pictos** [comment]
Since we have a spec proposal I'll close this issue and we should move any further comment to #1135
