### ISSUE TITLE
[Enhancement] SVG Support 

### ISSUE THREAD

**Issue by danielmeza** [xamarin/XamarinCommunityToolkit#858]
Add SVG support 

This is the original issue at Xamarin Forms reprository: 
https://github.com/xamarin/Xamarin.Forms/issues/8078

And this a good starting point: http://www.pshul.com/2018/01/25/xamarin-forms-using-svg-images-with-skiasharp/
Implemented with Skia Sharp

**Comment by jfversluis** [comment]
> Implemented with Skia Sharp

I think this is exactly why it isn't implemented in Forms and I'm not a big fan of taking on the dependency on Skia for the Toolkit as well. If we want to do this it would be in a separate package I guess.

Is this possible without Skia, just native bits?

**Comment by roubachof** [comment]
Yup, a skia sharp dep is a no go. Could be an idea to have a XCT skiasharp drawn controls later...

It could be possible with wrapping native libs or decoding svg with shapes on respectives platforms.
But it's costly and I would recommend to use something like: https://github.com/Redth/ResizetizerNT
You will have both flexibility and performance.

**Comment by themronion** [comment]
+1 with @roubachof on the https://github.com/Redth/ResizetizerNT, soon it will support app icons as well, i guess, so i dont see any reasons not to use it

**Comment by Redth** [comment]
Perhaps with system graphics there’s a case to use it for svg images at runtime which is definitely sometimes a different use case than resizetizer.  I’d wait until we get a bit further in Maui to look at this.

**Comment by themronion** [comment]
@Redth btw, can we expect app icons coming out for resizetizer any time soon?

**Comment by jfversluis** [comment]
And with that we will close this one here for now :)

**Comment by themronion** [comment]
@jfversluis noooooo, i want an answer from Jonathannn!!))

**Comment by Redth** [comment]
Yup app icons are basically ready now. I just need to push an update.

**Comment by danielmeza** [comment]
@jfversluis Since we leverage the support of SVG to  https://github.com/Redth/ResizetizerNT, we shall include this on the repository or point user to use it on the readme?

**Comment by jfversluis** [comment]
@danielmeza I'm not sure I understand your comment :)

**Comment by danielmeza** [comment]
Sorry for that, I wonder if the Resizetizer should be included in the Xamarin Community Toolkit in some way, ir order to give it more visibility. Maybe including it at the readme file or bring the code to this repository, (@Redth what do you think?), as we have chosen it as a solution for SVG on Xamarin.

**Comment by themronion** [comment]
@danielmeza i dont think there is a need for it here. Resizetizer is already merged in MAUI, so wait a little bit and just use it from there built in) Untill then use it separately

**Comment by danielmeza** [comment]
@themronion oh I see, glad to her that is already merged in MAUI.

**Comment by themronion** [comment]
> @themronion oh I see, glad to her that is already merged in MAUI.

https://github.com/xamarin/Xamarin.Forms/pull/13784
