### ISSUE TITLE
[Bug] SideMenu does not visualize left and right menu correctly

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#859]
### Description
I have this xaml

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TestFody.Page.SideMenuDemo"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:xct="http://xamarin.com/schemas/2020/toolkit">

    <xct:SideMenuView>

        <StackLayout
            xct:SideMenuView.MenuWidthPercentage="0.8"
            xct:SideMenuView.Position="LeftMenu"
            BackgroundColor="Blue">
        </StackLayout>

        <StackLayout
            xct:SideMenuView.MenuWidthPercentage="1"
            xct:SideMenuView.Position="RightMenu"
            BackgroundColor="Red">
        </StackLayout>

        <StackLayout xct:SideMenuView.Position="MainView" BackgroundColor="Yellow" />

    </xct:SideMenuView>
</ContentPage>
```
It should visualize a blu left menu and a red right menu, but it seems is always red

### Steps to Reproduce

se above
### Expected Behavior

blue side menu on left, red on right

### Actual Behavior
red on left and right

### Basic Information

- Version with issue: 1.0.2
- Last known good version: unknown
- IDE: Visual studio 2019 16.8.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

```
        <StackLayout
            xct:SideMenuView.MenuWidthPercentage="0.2"
            xct:SideMenuView.Position="RightMenu"
            BackgroundColor="Red">
        </StackLayout>
```
Seems that using 0.2 in RightMenu's MenuWidthPercentage, it works. Must the two percentages have a total sum of 1?

**Comment by AndreiMisiukevich** [comment]
Reproduced as described.

**Comment by kerberosargos** [comment]
Issue still continues.
