### ISSUE TITLE
[Bug] TouchView on Item in BindableLayout

### ISSUE THREAD

**Issue by 1grzyb1** [xamarin/XamarinCommunityToolkit#861]
### Description
When TouchView is on element inside BindableLayout and it emits command that reload this list then app crashes. This was working in previous versions of original TouchView repo (Last working 4.1.77).
### Steps to Reproduce

1.  Create StackLayout and bind OC to it through BindableLayout
2.  In ItemTemplate add TouchView Command
3. In Command clear list

### Expected Behavior
After animation finish clear list/stop animation and clear list

### Actual Behavior
App crashes

**Comment by AndreiMisiukevich** [comment]
Hello, @1grzyb1 thanks for your question and your interest in this project.

You are asking about the TouchView NuGet package that is not supported anymore. (it's obsolete/deprecated)
Please pay attention to https://github.com/AndreiMisiukevich/TouchEffect (This project is **archived**).

"Responsive touches" migrated to XamarinCommunityToolkit as **TouchEffect**.

Check the Readme: https://github.com/xamarin/XamarinCommunityToolkit
Also, I propose to check this article: https://andrei-misiukevich.medium.com/touch-effect-xamarin-forms-xamarin-community-toolkit-91fb6691f99e

Feel free to open tickets related to XamarinCommunityToolkit here.

This one is closed.

**Comment by 1grzyb1** [comment]
Yes I know that it has been moved here but I wanted to mention that it was working on currently deprecated package and now in xct this problem occures

**Comment by AndreiMisiukevich** [comment]
> Yes I know that it has been moved here but I wanted to mention that it was working on currently deprecated package and now in xct this problem occures

But **TouchView** doesn't exist in XCT.
Can you please clarify what do you mean?

**Comment by AndreiMisiukevich** [comment]
@1grzyb1 can you please build a small sample with reproduction?

**Comment by AndreiMisiukevich** [comment]
@1grzyb1 can you please build a small sample with reproduction?

**Comment by 1grzyb1** [comment]
@AndreiMisiukevich yes tomorrow I will send you

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich yes tomorrow I will send you

Thanks a lot :)

**Comment by AndreiMisiukevich** [comment]
@1grzyb1 can you please provide a sample app :) ?

**Comment by 1grzyb1** [comment]
I created a repo with a recreation of bug. Sorry for the delay my pc broke down.
https://github.com/1grzyb1/XctBug

**Comment by AndreiMisiukevich** [comment]
Closed in #1078
