### ISSUE TITLE
[Bug] Replace `BaseCommand.IsMainThread` + `BaseCommand. BeginInvokeOnMainThread` with .NET MAUI MainThread Implementations

### ISSUE THREAD

**Issue by brminnick** [xamarin/XamarinCommunityToolkit#863]
### Description

[Link to Original Discussion](https://github.com/xamarin/XamarinCommunityToolkit/pull/830#discussion_r570593791)

After Xamarin.CommunityToolkit migrates its dependency from Xamarin.Forms to .NET MAUI, we should remove both `BaseCommand.IsMainThread` and `BaseCommand. BeginInvokeOnMainThread`, replacing them with [.NET MAUI's MainThread implementation](https://github.com/dotnet/maui/tree/main/src/Essentials/src/Xamarin.Essentials/MainThread).

### To Do

Remove the following files:
- `BaseCommand.android.cs`
- `BaseCommand.gtk.cs`
- `BaseCommand.ios.watchos.tvos.macos.cs`
- `BaseCommand.netstandard.cs`
- `BaseCommand.shared.cs`
- `BaseCommand.tizen.cs`
- `BaseCommand.uwp.cs`
- `BaseCommand.wpf.cs`

**Comment by pictos** [comment]
@inforithmics we don't want to reference Essentials on this project.

**Comment by inforithmics** [comment]
Thanks for the info, I saw that the UWP Implmentation in uses the same implementation as Xamarin.Essentials so this wouldn't improve the situation.

**Comment by brminnick** [comment]
Yup! Closing 👍
