### ISSUE TITLE
[Enhancement] Add Min/Max Labels to RangeSlider

### ISSUE THREAD

**Issue by CliffAgius** [xamarin/XamarinCommunityToolkit#869]
## Summary

For the RangeSlider add Min/Max Labels so that the User can see what the range is, also allow the Disabling of one/both of the Slider handles so have an IsEnabledLow and High for example.

## API Changes

Add MinLabel and MaxLabel as Strings/Color etc.

Add IsEnabledLow and IsEnabledHigh for them to be independantly enabled as Bool.

## Intended Use Case

This will allow the Slider to have more customisation and control.

## Who Will Do The Work?

Bit of both I am putting it out there to see if it's something that is wanted/needed by others if it gets a nod then I am happy to pick it up unless someone else wants it.

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
Hi @CliffAgius thanks for your feedback.

if you wish to hide some of thumbs, you have two options
1) Use regular Slider from Xamarin.Forms box
2) Set LowerThumbSize="0" if you wish to hide lower thumb and UpperThumbSize="0" if you need to hide upperthumb

**Comment by CliffAgius** [comment]
@AndreiMisiukevich Yes I have it working great with setting the ThumbSize to Zero but be great to have as part of the control so that it's obvious.  Also means that if the value is set to non-zero in the Model you can still have it turned off in the view.

The main reason for the Issue though is the Fixed position Min/Max labels rather than having to carefully position separate Labels above the control.

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
