### ISSUE TITLE
[Bug] TabView SelectedIndex Binding does not work

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#870]
### Description
```
                <xct:TabView
                    BackgroundColor="White"
                    SelectedIndex="{Binding SelectedTabViewIndex}"
                    SelectionChanged="TabView_SelectionChanged">


```

I have a TabView with 2 TabViewItem. I set a SelectedTabViewIndex binding with SelectedIndex, and SelectionChanged event.

I see that TabView_SelectionChanged is called and NewValue and OldValue change, but SelectedTabViewIndex is always 1:

[0:] MainPage: TabView_SelectionChanged new: 1 - old: 0
[0:] MainPage: TabView_SelectionChanged: SelectedTabViewIndex: 1
[0:] MainPage: TabView_SelectionChanged new: 0 - old: 1
[0:] MainPage: TabView_SelectionChanged: SelectedTabViewIndex: 1

### Steps to Reproduce

See the attached repo

### Expected Behavior
SelectedIndex binding should change the binded value
### Actual Behavior
Binded value does not change

### Basic Information

- Version with issue: 1.1.0-preview1009
- Last known good version: unknown
- IDE: Visual Studio 2019 16.8.4
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[TestFody.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5951308/TestFody.zip)

**Comment by Cfun1** [comment]
@acaliaro I have tested your repo, I believe your are not raising the `INotifyPropertyChnaged` for your `SelectedTabViewIndex` property in your `StudentViewModel.cs` that why it is always with the default initial value that you gave it (1), could you please confirm if it is the case ?

**Comment by acaliaro** [comment]
> @acaliaro I have briefly tested your repo, I believe that the reason have to do with raising `INotifyPropertyChnaged` and setting/updating on your `SelectedTabViewIndex` property in your `StudentViewModel.cs` that why it is always with the default initial value that you gave it (1), could you please confirm if it is the case ?

@Cfun1 it should be raised automatically because of PropertyChanged.Fody, but I take a look

**Comment by acaliaro** [comment]
it semms that with

`                    SelectedIndex="{Binding SelectedTabViewIndex, Mode=TwoWay}"
`

it works

**Comment by AndreiMisiukevich** [comment]
@jsuarezruiz is it a bug and SelectedIndexProperty should have TwoWay binding mode by default?
