### ISSUE TITLE
[Enhancement] DurationPicker

### ISSUE THREAD

**Issue by johnshardman** [xamarin/XamarinCommunityToolkit#881]
## Summary

Implement a DurationPicker View, that allows a duration to be specified using pickers. Should support options that specify which of hours, minutes and seconds are to be shown, as well as minimum and maximum TimeSpan values (e.g. I typically want the user to just be able to specify hours and minutes, not seconds, and to have a minimum TimeSpan allowed of 1 minute and a maximum of 23 hours and 59 minutes). I also have a scenario where I just want the user to be able to specify  minutes and seconds, with a minimum of 5 seconds and a maximum of 1 minute.

Should support accessibility, including but not limited to screen readers and operation using keyboard only (access keys, tabbing, space key, cursor keys).

## API Changes

public enum TimeSpanMode
{
    HoursMinutes,
    HoursMinutesSeconds,
    MinutesSeconds,
    Seconds
}

public sealed class TimeSpanValueChangedEventArgs : EventArgs
{
    public TimeSpan NewValue { get; set; }
    public TimeSpan OldValue { get; set; }
}

public class TimeSpanPicker : View
{
    public event EventHandler<TimeSpanValueChangedEventArgs>? ValueChanged;
    public static readonly BindableProperty DisplayFormatProperty;
    public static readonly BindableProperty TimeSpanModeProperty;
    public static readonly BindableProperty MaximumValueProperty;
    public static readonly BindableProperty MinimumValueProperty;
    public static readonly BindableProperty TextColorProperty;
    public static readonly BindableProperty TextSizeProperty;
    public static readonly BindableProperty ValueProperty;
    public string DisplayFormat { get; set; }
    public TimeSpanMode TimeSpanMode { get; set; }
    public TimeSpan MaximumValue { get; set; }
    public TimeSpan MinimumValue { get; set; }
    public Color TextColor { get; set; }
    public int TextSize { get; set; }
    public TimeSpan Value { get; set; }
}

## Intended Use Case
Anywhere where the user needs to specify a duration, typically in functionality relating to scheduling.

## Who Will Do The Work?

- Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
