### ISSUE TITLE
[Bug] Sort Code: prompt does not agree with behavior 

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/XamarinCommunityToolkit#890]
### Description
The Mask for Sort code is "AA-AA-AA" and when used, a numeric keyboard is given to do the entry with.
Everywhere else that a Numeric keyboard is used, the prompt/mask uses XXXX...
I think to be consistent, For Sort code, either the Mask should be changed to "XX-XX-XX" or the Keyboard should be changed to Text or Default.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
@WillAutioItrax could you please build a sample showing what are you talking about?)

**Comment by jfversluis** [comment]
Like Andrei I'm not really sure what you mean, so could you please clarify :)

**Comment by IeuanWalker** [comment]
@WillAutioItrax the pattern can use any character. The default character is 'X'.
The sample just shows that you can override the masked character, i.e. in the sample it's overridden to 'A'

The sample shows the defualt and overriden version -
```xaml
<Entry Keyboard="Numeric">
    <Entry.Behaviors>
        <xct:MaskedBehavior Mask="XX-XX-XX" />
    </Entry.Behaviors>
</Entry>
<Label Padding="10,0,10,50" FontSize="Small" Text="e.g. Sort code 'XX-XX-XX'" />

<Entry Keyboard="Numeric">
    <Entry.Behaviors>
        <xct:MaskedBehavior Mask="AA-AA-AA" UnMaskedCharacter="A" />
    </Entry.Behaviors>
</Entry>
<Label Padding="10,0,10,50" FontSize="Small" Text="e.g. Sort code 'AA-AA-AA'" />
```

There is no issue here.

**Comment by WillAutioItrax** [comment]
I find it confusing that sometimes that mask is "X" and sometimes (once) it is "A" and mostly there is a Numeric keyboard. I've been in places where "X" would mean any character can go here; "A" for alpha; "N" for numeric. I get that the "A" is a placeholder. It seemed odd that there are all these Behaviors with "X" and then one with "A". That's my 2 cents. 
BTW, I appreciate the work that you all put into this package.  Thanks.

**Comment by AndreiMisiukevich** [comment]
@WillAutioItrax can this issue be closed then? :)

**Comment by WillAutioItrax** [comment]
@AndreiMisiukevich Yeah - sure.
