### ISSUE TITLE
[Feature Request] [CameraView] [iOS] Allow photos to be taken in landscape. 

### ISSUE THREAD

**Issue by JoelPickin** [xamarin/XamarinCommunityToolkit#894]
### Description
I want to be able to take landscape photos and view them in landscape. I have tried two different routes to achieve this. Locking the iOS device orientation in portrait and rotating the phone to landscape causes the photo to be taken as a landscape photo but orientated as portrait. 

I have also tried creating a separate view for landscape so it uses this when the phone rotates but for some reason it rotates the camera as well as the UI so landscape photos are taken in inverse portrait. 

My explanation may not be the best but I have provided a repro to demonstrate this.

Also to note in the CommunityToolkit sample app, if the phone is rotated, the camera view is not rotated but the rest of the UI is. If you enter the CameraView in the sample app in landscape mode, the UI is rotated but the CameraView is not.

### Steps to Reproduce

1. Run the repro
2. Rotate the device
3. The landscape view will be used.
4. Camera is flipped to inverse portrait.

### Expected Behavior

1. Allow the camera to be used in landscape orientation when rotating the device
2. When a landscape orientation is used, have the camera rotated the same way.

### Actual Behavior

- CameraView not set to landscape doesn't resize to match the screen.
- CameraView in a landscape view flips the camera upside down, or inverse portrait.

### Basic Information

- Version with issue: 1.0.2
- IDE: Visual Studio 2019

### Reproduction Link

https://github.com/JoelPickin/CameraFlipBug

**Comment by pictos** [comment]
This looks like more an `enhancement` than a `bug`.

**Comment by michaldivis** [comment]
This would be useful

**Comment by JoelPickin** [comment]
I have created a pull request for this feature on iOS

https://github.com/xamarin/XamarinCommunityToolkit/pull/1017

Thanks

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Comment by jrahma** [comment]
> This looks like more an `enhancement` than a `bug`.

I would consider this is a bug because a main function is not working which is a landscape pic

**Comment by bijington** [comment]
This issue has been resolved as part of PR #1524 and this is available in release `1.3.0`. Therefore I am closing this down.
