### ISSUE TITLE
[Housekeeping] cleaning sample project from [XamlCompilation(XamlCompilationOptions.Compile)]

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#896]
## Summary

Remove all `[XamlCompilation(XamlCompilationOptions.Compile)]` from Sample project code-behind pages, and keep only `[assembly: XamlCompilation(XamlCompilationOptions.Compile)]` in AssemblyInfo.cs

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Makes sense, let's do it
