### ISSUE TITLE
Blur effect - UWP

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#9]
_From @Depechie on November 21, 2016 11:55_

Current implementation of the Blur effect needs Win2D, need to see if we can't refactor to only target Windows Composition framework ( newer way to do UI transitions and effects ).

_Copied from original issue: FormsCommunityToolkit/Effects#8_

**Comment by bartlannoeye** [comment]
_From @jassmith on November 21, 2016 18:51_

You can't ;)

However a thought occurs for the bug with this effect you might try. In the OnAttached callback, try setting the Width/Height of the target element (the native one, not the forms one) to a size, like 10x10 or something, and then setting it back to what it was to start with.

This should force apply the effect. I think, in theory... without side effects even... maybe...

**Comment by bartlannoeye** [comment]
_From @Depechie on November 21, 2016 18:53_

Haaa, good point! Will investigate more, thanks!

**Comment by bartlannoeye** [comment]
_From @skendrot on December 14, 2016 0:31_

Why can you not use composition?

**Comment by bartlannoeye** [comment]
_From @jassmith on December 14, 2016 0:43_

I might be wrong, but I'd be surprised since I actually wrote this based on conversations and sample code directly from the composition team. My understanding is the composition layer simply doesn't have the API's required to do the blur behind. I think long term this will be available but it's not possible at the moment. Even once it is, backwards compatible support will be required.

**Comment by bartlannoeye** [comment]
_From @skendrot on December 14, 2016 18:48_

What do you mean by "blur behind"?

**Comment by skendrot** [comment]
I'm sure I can get this working if you want blur for UWP

**Comment by pauldipietro** [comment]
This can be reopened if we have a clearer proposal due to a lack of activity.
