### ISSUE TITLE
[Enhancement] Expand MediaElement with support for adaptive streams like HLS / MPEG-Dash

### ISSUE THREAD

**Issue by sjorsmiltenburg** [xamarin/XamarinCommunityToolkit#902]
## Summary

The MediaElement supports loading content from an url but this method is not adequate yet for playing urls of adaptive streams like created with Azure Media Services.

Each platform does seem to have support for playback of these type of media streams.

The Xamarin.Forms.UWP code could for instance be expanded with the following code:

```
var adaptiveStreamUrl = "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest";

var uri = new Uri(adaptiveStreamUrl);
AdaptiveMediaSourceCreationResult result = await AdaptiveMediaSource.CreateFromUriAsync(uri);
if (result.Status == AdaptiveMediaSourceCreationStatus.Success)
{
   var ams = result.MediaSource;
   mediaPlayerElement.SetMediaPlayer(new Windows.Media.Playback.MediaPlayer());
   mediaPlayerElement.MediaPlayer.Source = MediaSource.CreateFromAdaptiveMediaSource(ams);
}
```

## Intended Use Case

Playback of adaptive steams.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by jfversluis** [comment]
Looks like something we should support! Thanks :)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
