### ISSUE TITLE
[Enhancement] Add support for TabView for MacOS platform

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/XamarinCommunityToolkit#908]
## Summary

The `TabView `does not render properly on a MacOS. In-fact - you can't see anything - only the tab bar at the top.

## API Changes

I don't know. :)

## Intended Use Case
The app I am making is intended for MacOS and iOS. It would have been simpler with `TabView`. Although I have now learnt an easy workaround with `TabbedPage `and using `MessageCenter`.

## Who Will Do The Work?

- Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
