### ISSUE TITLE
Toolkit Discussion: Namespaces, Xamarin Forms and Xamarin Native Controls

### ISSUE THREAD

**Issue by WilliamABradley** [xamarin/XamarinCommunityToolkit#91]
Hi there!
I'm glad this project has been officially created!

I have a few things to discus about this,
firstly, I am a member of the Core Team of the UWP Community Toolkit, and we have been working on some .NET Standard libraries there (Under `Microsoft.Toolkit` namespaces).

Since these are two Microsoft Toolkits, we should have the same namespace layout.
All our UWP Specific libraries are under the `Microsoft.Toolkit.UWP` namespace, so it would be fitting if this had namespaces of `Microsoft.Toolkit.Xamarin`, and/or `Microsoft.Toolkit.Xamarin.Forms`.

Eventually we can move the .NET Standard Libraries under the `Microsoft.Toolkit.*` namespaces to a shared Toolkit of some kind, that both this and the UWP Community Toolkit have dependencies on.

Second discussion,
I separated the Parser from the MarkdownTextBlock on the UWP Community Toolkit, so that it can be used in other Scenarios and controls on other .NET Platforms. I got some way through implementing and Android Native Control called MarkdownTextView, and I had plans for creating native variants for iOS and others at a later date, as well as a Xamarin Forms variant. I would love to add this here, however, the description makes it seem that this is for Xamarin Forms only. Should this be the Xamarin Forms Toolkit, or will you allow libraries specific to Platform?

That is all of my thoughts for now 😀 
Let me know what you think...

**Comment by pauldipietro** [comment]
We had discussed namespaces a few weeks ago and I don't have a problem with using something like `Microsoft.Toolkit.Xamarin.*`. I could probably also put together a PR with changes for this to be ready for if we want to go forward with it.

I think (@jamesmontemagno can refresh my memory on this) that the long term plan was to focus on Forms first, and then open it up to the other platforms over time if we felt that the demand was there. There are a couple open proposals lacking a spec for controls that don't exist in the Forms core (`RadioButton` is one of those examples) which could be very useful to implement in the Toolkit. That said, utilizing the aforementioned namespace, it still works for scenarios where we could use a `Microsoft.Toolkit.Xamarin.Android` or `Microsoft.Toolkit.Xamarin.iOS` if we wanted to leave platform specific controls here.

You can also send me an email if you'd like to discuss this further more directly (paul.dipietro at microsoft).
