### ISSUE TITLE
[Housekeeping] Wrap Linker-Specific Code in a `#region`, adding explaination

### ISSUE THREAD

**Issue by brminnick** [xamarin/XamarinCommunityToolkit#910]
## Problem

The Xamarin.CommunityToolkit contains a few work-arounds to prevent the Linker from accidentally removing platform-specific code. One example can be found here: https://github.com/xamarin/XamarinCommunityToolkit/pull/674/files/492d4f0908e84b9141deeb05dc19e3e5878ea105#r576375815

Typically, this code looks like it can be removed because it is "not used", but it is indeed required to tell the linker to keep the code in the compiled binary.

The concern is that future devs may remove this "unused code", accidentally causing a breaking change.

## Solution

As [discussed here](https://github.com/xamarin/XamarinCommunityToolkit/pull/674#discussion_r576380021), let's wrap this linker-specific code in a `#region` and a comment that alerts future devs to its purpose, like so:

```csharp
#region Required work-around to prevent linker from removing the platform-specific implementation 

#if __ANDROID__
			if (System.DateTime.Now.Ticks < 0)
				_ = new Xamarin.CommunityToolkit.Android.Effects.LifeCycleEffectRouter();
#elif __IOS__
			if (System.DateTime.Now.Ticks < 0)
				_ = new Xamarin.CommunityToolkit.iOS.Effects.LifeCycleEffectRouter();
#elif UWP
			if (System.DateTime.Now.Ticks < 0)
				_ = new Xamarin.CommunityToolkit.UWP.Effects.LifeCycleEffectRouter();
#endif

#endregion
```

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by jfversluis** [comment]
Yeah sounds definitely like a good idea. The code might look confusion so a bit of hiding/explaining is probably a good idea
