### ISSUE TITLE
Add CommandParameter to UserStoppedTypingBehavior

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#914]
### Description
```
<Entry>
    <Entry.Behaviors>
        <xct:UserStoppedTypingBehavior 
            Command="{Binding SearchCommand}"
            StoppedTypingTimeThreshold="1000"
            MinimumLengthThreshold="3"
            ShouldDismissKeyboardAutomatically="True" />
    </Entry.Behaviors>
</Entry>
```

If I use this code inside a CollectionView, how can I pass the object to the Command? Is CommandParameter missing?
### Steps to Reproduce

Use a CollectionView with an entry as ItemTemplate

```
<Entry
                                    Grid.Column="3"
                                    Style="{StaticResource NumeriEntryStyle}"
                                    Text="{Binding FasciCaricati}">
                                    <Entry.Behaviors>
                                        <xct:UserStoppedTypingBehavior
                                            Command="{Binding Path=BindingContext.CalcolaTonnellateCaricateCommand, Source={x:Reference Name=this}}"
                                            MinimumLengthThreshold="1"
                                            ShouldDismissKeyboardAutomatically="True"
                                            StoppedTypingTimeThreshold="2000" />
                                    </Entry.Behaviors>
                                </Entry>
```

### Expected Behavior
I would like to pass the object I am setting the property to the Command
### Actual Behavior
I don't know how
### Basic Information

- Version with issue: last nightly 
- Last known good version: unknown
- IDE: Visual Studio 2019 16.8.5
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Yep, looks like that one is missing! Technically would be a feature request though. @jBijsterboschNL might be interested in adding it to his own contribution and marking it up for grabs otherwise

**Comment by jBijsterboschNL** [comment]
That indeed hasn't been implemented yet. If it is okay with you guys I'll have a look at it in the next few days :)

**Comment by jfversluis** [comment]
No rush! I'll assign you for now, let us know how it goes or... not goes!

**Comment by jBijsterboschNL** [comment]
@acaliaro @jfversluis, currently the `InputView.Text` value is send as `CommandParameter`. How should we implement this additional `CommandParameter`? If a `CommandParameter` is given, it should send this parameter instead of the `InputView.Text` value? And when the `CommandParameter` is not set, we send the `InputView.Text` value?

**Comment by jfversluis** [comment]
I think that implementation makes sense! That way we still have the current way of working but people can override it if they want with the new `CommandParameter`
