### ISSUE TITLE
[Bug] WeakSubscribe<T>(this INotifyPropertyChanged target..) has incorrect EventArgs parameter type

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#917]
### Description

`WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, EventArgs> action)`
should be 
`WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, PropertyChangedEventArgs> action)`

since it explicitly extends `INotifyPropertyChanged` and `PropertyChangedEventHandler` provides subscribers with `PropertyChangedEventArgs`.

### Steps to Reproduce

This will get a complile-time error since currently `e` is `EventArgs` instead of `PropertyChangedEventArgs`:
```
someObservableObject.WeakSubscribe(this,(t, _, e) =>
{
    if (e.PropertyName == nameof(someObservableObject.SomeProperty))
    {
        DoWork();
    }
});
```

### Expected Behavior
I should be able to refer to `PropertyName` of event arguments.

### Actual Behavior
I cannot directly do that

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Cast `e` to `PropertyChangedEventArgs` inside event handler

**Comment by pictos** [comment]
@maxkoshevoi instead of doing it to be more specific what do you think to make it more generic? That way we can use it everywhere and maybe expose this as a lib feature?

**Comment by maxkoshevoi** [comment]
@pictos `EventArgs` is a return value. We only helping user by making it more specific.

- `WeakSubscribe` explicetly extends `INotifyPropertyChanged`, so event arguments always will be `PropertyChangedEventArgs`. We cannot make `WeakSubscribe` more generic unfortunately.
- This is already a lib feature! `WeakSubscribe` is public and can be called on anything that implements `INotifyPropertyChanged`

**Comment by pictos** [comment]
@maxkoshevoi we can do it more general, just following the original implementation (that you share the article), that way we can use it for any type and event not just for `INPC` types. No need to do it on this PR, but if you are interested in giving it a try let me know.

**Comment by maxkoshevoi** [comment]
@pictos Ah, you are talking about [original article](https://faithlife.codes/blog/2008/08/event_subscription_using_weak_references/), not about this method in particular. That implementation is not entirely generic either. The issue is "what to extend?". You cannot extend `IHasEvent` or something like that, so as I understand in that article wrapper `EventInfo` was created that needs to encapsulate class with the event. So if we wanted to use code from the article, `WeakSubscribe` would be generic, yes, but it would only accept classes that are wrapped in `EventInfo`. 
Maybe this issue is solvable to, but still, what do we extend? `object` is not the best idea. Maybe we can write one generic `WeakSubscribe` method and then just add `WeakSubscribe` overloads for every specific class. That might work actually.

**Comment by pictos** [comment]
@maxkoshevoi we can use generics for that, also we can pass the name of the event and using a light reflection to get it. I can say that's feasible, and that article provides the initial steps to do it. But no pressure, if can't see a way I can try to implement it later.

**Comment by maxkoshevoi** [comment]
@pictos Didn't quite get you. What type are you planning to write `WeakSubscribe` extension method for? If it's generic, what constraints does that generic type have?

**Comment by pictos** [comment]
@maxkoshevoi 

Let's pick 2 classes, the `Button` and the `ContentPage`, both objects have events to subscribe to, right? So for the `button`, we have the `Clicked` and for `ContentPage` we have the `OnAppearing`, for example.

Said that I want to use the WeakSubscribe to subscribe to these events. To do that I need the object instance (we can do it by a generic TSource), we need the event name that we want to subscribe to and the target (TTarget).

```csharp
// Usage sample
class MyPage : ContentPage {

void Build() {

   this.WeakSubscribe<ContentPage, MyPage>(this, (t, sender, args) => MyAction(t, sender, args);
   myButton.WeakSubscribe<Button, MyPage>(this, (t, sender, args) => MyButtonAction(t, sender, args);
}

void MyAction(Mypage target, object sender, EventArgs args);
void MyButtonAction(Mypage target, object sender, EventArgs args);
}
```
For the WeakSubscribe we don't need the `EventInfo<TSource, EventHandler>`  object.

**Comment by maxkoshevoi** [comment]
@pictos You also need event args type as a generic argument, but yes, this could work.

What I'm asking is what type does first parameter of WeakSubscribe have? Is it generic without constraints? Than this method will appear for everything (even for string instances).

**Comment by pictos** [comment]
> What I'm asking is what type does first parameter of WeakSubscribe have? Is it generic without constraints? Than this method will appear for everything (even for string instances).

Yeah, you're right, that will appears for every type. The solution is not implemented as an extension method.
