### ISSUE TITLE
[Enhancement] Provide UWP implementation for RemoveBorderEffect

### ISSUE THREAD

**Issue by Alex-Witkowski** [xamarin/XamarinCommunityToolkit#922]
## Summary

For the RemoveBorderEffect there is currently no implementation for UWP.

## API Changes

No real changes. Implementation can be done by setting BorderWidth to zero on attached, and reset on detached. 

## Intended Use Case

If you have a design that specifies a borderless entry you can use the effect from XCT except you need to support UWP. This would add a litte ❤️ to UWP. 

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by AndreiMisiukevich** [comment]
@Alex-Witkowski approved :)
I assigned this task to you.

Please tell us if you decide to not send PR for some reason)

**Comment by pictos** [comment]
@Alex-Witkowski friendly reminder to implement this lovely feature on top of `develop` branch

**Comment by AndreiMisiukevich** [comment]
Fixed in #1048
