### ISSUE TITLE
Expander cuts off part of CollectionView [Bug] 

### ISSUE THREAD

**Issue by janosfekete** [xamarin/XamarinCommunityToolkit#926]
### Description
Portions of CollectionView are not visible in expander body after expanding
### Steps to Reproduce

1. Create XAML view with expander with horizontal CollctionView in body
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="Sandbox.Views.ExpanderPage">
    <ContentPage.Content>
        <xct:Expander>
            <xct:Expander.Header>
                <Label Text="Header" Padding="20" BackgroundColor="LightCyan"/>
            </xct:Expander.Header>
            <StackLayout HeightRequest="160" BackgroundColor="Aquamarine">
                <CollectionView
                            ItemsSource="{Binding Items}"
                            VerticalOptions="End" 
                            SelectionMode="Single">
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout ItemSpacing="0" Orientation="Horizontal" />
                    </CollectionView.ItemsLayout>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <StackLayout 
                                WidthRequest="160"
                                HeightRequest="160"
                                BackgroundColor="Orange"
                                Spacing="0">
                                <Label Text="{Binding Text}" BackgroundColor="LightSkyBlue"/>
                                <Label Text="{Binding Text}" BackgroundColor="LightSkyBlue"/>
                                <Label Text="{Binding Text}" BackgroundColor="LightSkyBlue"/>
                                <Label Text="{Binding Text}" BackgroundColor="LightSkyBlue"/>
                            </StackLayout>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </StackLayout>
        </xct:Expander>
    </ContentPage.Content>
</ContentPage>`
2. Add simple ViewModel
`using System.Collections.ObjectModel;

namespace Sandbox.ViewModels
{
    public class ExpanderViewModel : BaseViewModel
    {
        public ObservableCollection<ExpanderItem> Items { get; }
        public ExpanderViewModel()
        {
            Items = new ObservableCollection<ExpanderItem>() { 
                new ExpanderItem(){Text = "Item 1" },
                new ExpanderItem(){Text = "Item 2" },
                new ExpanderItem(){Text = "Item 3" },
                new ExpanderItem(){Text = "Item 4" },
            };
        }
    }

    public class ExpanderItem
    {
        public string Text { get; set; }
    }
}`
2. 
3. 

### Expected Behavior
Show all items
### Actual Behavior
Only first two items shown. Scrolling right reveals all items
![expander-issue](https://user-images.githubusercontent.com/22258607/108215405-4d40dd00-70ff-11eb-9c2d-73e76f24b542.gif)

### Basic Information

- Version with issue:1.02
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 10 
  - UWP:  N/A 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
We've added to the [Docs](https://docs.microsoft.com/xamarin/community-toolkit/views/expander): Expander and CollectionView/ListView should not be used together. I'd love to have a solution for this but it’s one of those controls that don’t exist on the native platform. Because of that you will be fighting the OS on getting it right. Closing this one since there won't be any solution on the short-term unless someone contributes it.
