### ISSUE TITLE
[Bug] IconTintColorEffect does not work when the image is in Shared project as EmbeddeResource

### ISSUE THREAD

**Issue by azapatac** [xamarin/XamarinCommunityToolkit#934]
### Description
An added image in the shared project as EmbeddeResource does not change TintColor

### Steps to Reproduce

1. Create Xamarin project
2. Create ImageResourceExtension : IMarkupExtension
3. Add image the shared project and set up Build Action = EmbeddeResource
4. Add image in content page and apply IconTintColorEffect

### Expected Behavior
The image color must change the color

### Actual Behavior
The image has the original color

### Basic Information

Visual Studio Community 2019 for Mac
Version 8.8.8 (build 12)
Installation UUID: 4fcbc297-9169-4ef5-b390-ed7872967085
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

Mono Framework MDK
Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

Roslyn (Language Service)
3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

NuGet
Version: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.101
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.1
	3.1.12
	3.1.11
	3.1.10

.NET Core 3.1 SDK
SDK: 3.1.406

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

Xamarin Designer
Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

Xamarin.Android
Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/andreszapata/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Microsoft OpenJDK for Mobile
Java SDK: /Users/andreszapata/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

Android Device Manager
Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

Build Information
Release ID: 808080012
Git revision: 147eee6fcc43c486d8b79477b6a521322a015604
Build date: 2021-02-04 04:32:34-05
Build branch: release-8.8
Xamarin extensions: 147eee6fcc43c486d8b79477b6a521322a015604

Operating System
Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

![image](https://user-images.githubusercontent.com/8869059/108416966-64fe8b00-71fd-11eb-8032-16d39357ee2c.png)

![image](https://user-images.githubusercontent.com/8869059/108417007-721b7a00-71fd-11eb-8c29-dceb7f3a6d05.png)

![image](https://user-images.githubusercontent.com/8869059/108417228-b3138e80-71fd-11eb-8fa5-ff33e77dd078.png)

![image](https://user-images.githubusercontent.com/8869059/108417400-ec4bfe80-71fd-11eb-9497-081c6d6ecd1f.png)

**Comment by jBijsterboschNL** [comment]
I've had a quick look at this issue and is seems te be an iOS only issue. On Android embedded images are being tinted properly. Will try to get it fixed, but need to investigate it a bit further.

@azapatac, just curious. Why have you created your own ImageResourceExtension? You could also use the XCT version of this :)

**Comment by pictos** [comment]
@azapatac can you provide a small repro?

**Comment by TheDude1604** [comment]
We are facing the same issue like @azapatac , @jBijsterboschNL were you able to find a solution? I have tried to add an Observer to the Image Property of UIImageView but it was not triggered for new values, maybe I did something wrong there.

**Comment by TheDude1604** [comment]
@azapatac @jBijsterboschNL @jfversluis 
I could resolve this issue by changing SetUIImageViewTintColor to something like that:

```
async void SetUIImageViewTintColor(UIImageView imageView, Color color)
{
   if (imageView.Image == null)
      if (_retryCount < 4)
      {
        _retryCount++;
	await Task.Delay(100);
	SetUIImageViewTintColor(imageView, color);
      }
      else
	return;
   else
   {
      imageView.Image = imageView.Image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
      imageView.TintColor = color.ToUIColor();
       _retryCount = 0;
   }
}
```

**Comment by mike-rowley** [comment]
I have this exact issue and it seems there is little to no work being done on the Xamarin version of anything anymore, if it isn't MAUI no one at MS seems to care to fix bugs so I think were on our own.

Does anyone know how to override the CommunityToolkit version of IconTintColorEffectRouter in IOS to update this method and fix the issue without spinning off an entire new CommunityToolkit just to fix this bug?

**Comment by bijington** [comment]
> I have this exact issue and it seems there is little to no work being done on the Xamarin version of anything anymore, if it isn't MAUI no one at MS seems to care to fix bugs so I think were on our own.
> 
> 
> 
> Does anyone know how to override the CommunityToolkit version of IconTintColorEffectRouter in IOS to update this method and fix the issue without spinning off an entire new CommunityToolkit just to fix this bug?

Hey @mike-rowley it's true that we are spending more time getting the toolkit ready for MAUI but this toolkit is not maintained by Microsoft. There are some employees working in this but as the name suggests it's community based and they work on it in their spare time.

To answer your question, you could copy over the code to your project and fix the issue in your application. You will need to copy it for all platforms though. A better outcome would be that if you do solve it offer the fix back to us in a PR. I've used this approach in the past as I can fix it within my own release schedule but still always give it back

**Comment by mike-rowley** [comment]
Thanks @bijington, you are 100% correct, I forgot this is in XCT and not Xamarin proper.  I have taken your advice and created a PR based on the solution provided by @TheDude1604

**Comment by bijington** [comment]
> Thanks @bijington, you are 100% correct, I forgot this is in XCT and not Xamarin proper.  I have taken your advice and created a PR based on the solution provided by @TheDude1604 
> 
> 
> 
> 

Thank you so much for the contribution! I think @pictos has already taken a look, at least I've seen some notifications about it.

**Comment by pictos** [comment]
Yes, I'm. I'll test on my end ASAP (:

**Comment by VictorKochetkov** [comment]
Hello! 

`IconTintColorEffect` is very useful and we were tried to attach it to `SvgCachedImage` from [FFImageLoading](https://github.com/luberda-molinet/FFImageLoading) library.
But now it crashing right here - https://github.com/xamarin/XamarinCommunityToolkit/commit/6b6a02ec9c3135b1da472e7165a5faef2befc44a#r69840142

Is it possible to make something like that?
This code not crashing and tint icon as expected :)

```
if (e.PropertyName == Image.IsLoadingProperty.PropertyName)
{
    var isLoading = (bool)Element.GetType().GetProperty(e.PropertyName).GetValue(Element);

    if (!isLoading)
    {
         ApplyTintColor();
    }
}
```

**Comment by bijington** [comment]
@VictorKochetkov this toolkit won't provide support for tinting other libraries image controls. I do believe that FFImageLoading provides it's own mechanism for tinting images in their own controls though.

**Comment by bijington** [comment]
@pictos and @mike-rowley can this issue be closed? I think the PR went in that solves this issue?

**Comment by mike-rowley** [comment]
@bijington yes I think it can be closed, the PR solves this issue as far as I am concerned
