### ISSUE TITLE
[Enhancement] Automatically resize the popup depending on the content

### ISSUE THREAD

**Issue by acaliaro** [xamarin/XamarinCommunityToolkit#937]
## Summary

Currently the Popup has its own dimension independent of the content; for example, on Android the popup almost completely fills the height of the screen. It would be useful if the popup could resize according to the content so as to take up as little space as possible on the display.

## API Changes

I am not sure which APIs to use for this request. In my opinion, what I requested could be the default: if instead there is the need to have dimensions other than the minimum required by the content, the programmer can use the "Size" property to modify them.
If instead you want to keep the current default, you could use a new bool "Autosize" property which, if set to true, resizes the popup with respect to the content

## Intended Use Case
If you wanted to replace the DisplayAlert method with the Popup to display a simple title, a message with an "ok" or "ok" and "cancel" button, having a popup that resized itself according to the length of the message would be very useful

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

**Comment by acaliaro** [comment]
#990

**Comment by Brosten** [comment]
This would be great to have!

**Comment by jfversluis** [comment]
I think a lot of people want this, not sure how easy it is to implement though

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Comment by radoczsandor** [comment]
Hello!

If someone still facing this, I did the following workaround in my application: 
Since I was using `grid` it has the option to set the Row/Column definitions height or width to `auto` (but it is also works with fixed sizes).

Once you set these sizes use this code in the Popup page constructor:

`this.Size = new Xamarin.Forms.Size(300, this.YourElement0.Height + this.YourElement1.Height + this.YourElement2.Height);`

I'm using const value for width but it also works at the same way.

**Comment by andyzukunft** [comment]
I just want to provide some information as @kelltom gave me some idea.

I had a Popup which was semi-scaling. Meaning: it was scaling however long-ish label texts did not work properly. I changed the Popup Size height from 0 to -1:

Previous configuration, not fully working:
`RelativeMediumWithNoFixedHeight = new(0.7 * (DeviceDisplay.Current.MainDisplayInfo.Width / DeviceDisplay.Current.MainDisplayInfo.Density), 0);`

New size configuration, working with larger label texts
`RelativeMediumWithNoFixedHeight = new(0.7 * (DeviceDisplay.Current.MainDisplayInfo.Width / DeviceDisplay.Current.MainDisplayInfo.Density), -1);`
