### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by srikrishnan83** [xamarin/XamarinCommunityToolkit#951]
### Description
As mentioned in the web page https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield
Shield have StatusTextColor property. But the property not present in the current nuget 1.0.2.
### Steps to Reproduce

1.  Create a new xamarin app. 
2.  Add Xamarin community toolkit nuget in the application. Add shield in the page
3.  <xct:Shield
                Subject="chat"
                Status="on discord"
                StatusBackgroundColor="SeaGreen"
                StatusTextColor="White"
                Margin="2,0" />

### Expected Behavior
   Have Status TextColor Property. 
### Actual Behavior
Property was not found in the type shield.
### Basic Information

- Version with issue: 1.0.2
![Shield not Having Property](https://user-images.githubusercontent.com/78830013/108630957-91303b00-748d-11eb-8f92-acf023699215.png)

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Cfun1** [comment]
It will be available on the next release, for now you can use TextColor which will be deprecated in future

**Comment by jfversluis** [comment]
Yeah it was merged a bit too early :) 1.1 should be released soon. Sorry for the confusion
