### ISSUE TITLE
[Enhancement] ValidationBehavior VisualStates

### ISSUE THREAD

**Issue by YZahringer** [xamarin/XamarinCommunityToolkit#952]
## Summary
Support validation `VisualStates` with `ValidationBehavior`.

## API Changes
| VisualState Name | VisualStateGroup Name | Description                      |
|------------------|-----------------------|----------------------------------|
| Valid         | ValidationStates       | The value is valid.     |
| Invalid       | ValidationStates       | The value is not valid. |

## Intended Use Case
Define different visual appearances by `VSM`.

## Who Will Do The Work?
- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
Sounds good

**Comment by pictos** [comment]
@AndreiMisiukevich will you work on this or can we mark this as `up-for-grabs`?

**Comment by Cfun1** [comment]
I would love to contribute with this if you guys don't mind :)

**Comment by AndreiMisiukevich** [comment]
@Cfun1 I assign it to you with pleasure )

**Comment by Cfun1** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/pull/955 has been merged, thus this issue needs to be closed

**Comment by AndreiMisiukevich** [comment]
Fixed in #955
