### ISSUE TITLE
[Enhancement] Generic EventToCommandBehavior

### ISSUE THREAD

**Issue by pictos** [xamarin/XamarinCommunityToolkit#953]
## Summary

Today with our current EventToCommandBehavior implementation we can see some issue using strongly type arguments with `Command<T>` the workaround today is using `T` as `object` and that's a kinda bad-sh thing to do.
If we have an `EventToCommandBehavior<TType>` that inherits from our `EventToCommandBehavior` we will be able to force the `parameter` to be the `TType` and doesn't crash the application.

An example of this issue can be seen here #950

## API Changes
Here's the full implementation so far.

```csharp
public class EventToCommandBehavior<TType> : EventToCommandBehavior
{
    protected override void OnTriggerHandled(object sender = null, object eventArgs = null)
    {
	    var parameter = CommandParameter
		    ?? EventArgsConverter?.Convert(eventArgs, typeof(object), null, null)
		    ?? eventArgs;
    
	    if (parameter.GetType() != typeof(TType))
	    {
		    parameter = null; // not sure if this a good approach, but nulling it we prevent an InvalidCastException (I suppose)
		    parameter = Convert.ChangeType(parameter, typeof(TType));
	    }
    
	    var command = Command;
	    if (command?.CanExecute(parameter) ?? false)
		    command.Execute(parameter);
    }
}
```

## Intended Use Case
Make this scenario works

```csharp
Coffee selectedCoffee;
public Coffee SelectedCoffee
{
    get => selectedCoffee;
    set => SetProperty(ref selectedCoffee, value);
}

async Task Selected(Coffee coffee)
{
    if (coffee == null)
        return;

    await Application.Current.MainPage.DisplayAlert("Selected", coffee.Name, "OK");
    SelectedCoffee = null;
}
```
On XAML the usage will be
```xml
<xct:EventToCommandBehavior
    x:TypeArguments="model:Coffee"
    Command="{Binding SelectedCommand}"
    EventArgsConverter="{StaticResource ItemSelectedEventArgsConverter}"
    EventName="ItemSelected" />
```

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@jamesmontemagno I went out to cycle I came up with this implementation, and it works very well so far. Let me know what do you think.

Also, @AndreiMisiukevich , @sthewissen, and @jsuarezruiz can you share your thoughts on this?

**Comment by AndreiMisiukevich** [comment]
@pictos I think you did a good job on the investigation) And I like this solution

**Comment by jamesmontemagno** [comment]
I guess if `eventArgs` are null then just pass it null to Execute?

**Comment by pictos** [comment]
@jamesmontemagno 
> I guess if eventArgs are null then just pass it null to Execute?

But the `eventArgs` isn't null, it will be the event EventArgs, in that case, will be `ItemSelectedEventArgs`. If was the Tapped event the `eventArgs` will be `ItemTappedEventArgs`
