### ISSUE TITLE
[Enhancement] TouchEffect Command

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#956]
I have noticed that if you add the command effect and press fast, the command can be executed more than 1 time, could an improvement be added so that this does not happen? Or do we have to manage it 1 to 1 in our application? with CanExecute it could be solved, am I correct?

**Comment by AndreiMisiukevich** [comment]
Hi @angelru and thanks for your interest in this project :)
I don't except that it's possible, but I presume you can get the same behavior with regular TapGestureRecognizer or Button, don't you?) 

I guess, yes. It should be handled on Command's level.
But also we can add a property on TouchEffect's side for preventing it (CommandDelay or smth similar)

CC @pictos @jfversluis

**Comment by pictos** [comment]
Normally this is handle on ViewModel, like if you tap very fast in a button, that performs navigation, you can do the same navigations more than once. The most famous pattern to handle that is the `IsBusy`. So not sure if it makes sense to add this handle inside the control.

**Comment by angelru** [comment]
With prism framework I solve it with DelegateCommand with ObservesCanExecute with the IsBusy property in the ViewModel in the case of calls to the Api. I understand that we have to do it one by one. If you see that this does not proceed, feel free to close this issue.
