### ISSUE TITLE
[Bug] Java.Lang.NoSuchMethodError in TouchEffect and Rg.Plugins.Popup on Android 5 after updatiog to XCT 1.0.3

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#969]
### Description

`PlatformTouchEffect.OnDetached` began throwing `Java.Lang.NoSuchMethodError: 'no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.getForeground()Landroid/graphics/drawable/Drawable;"'` on android 5 after updating to XCT 1.0.3.

Also updating to XCT 1.0.3 breaks [Rg.Plugins.Popup](https://github.com/rotorgames/Rg.Plugins.Popup) NuGet for some reason (same exception).

### Steps to Reproduce

1. Run this app on Android 5 emulator (or real device): https://github.com/maxkoshevoi/NureTimetable
2. Switch between Menu and other tab

### Basic Information

- Version with issue: 1.0.3
- Last known good version: 1.0.2
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All Android 5 devices

### Workaround
Don't update to 1.0.3 or don't use `NativeAnimation`

### Reproduction imagery

![image](https://user-images.githubusercontent.com/6609929/108955806-6efa1100-7677-11eb-8061-fc0f709b733f.png)

![xct4](https://user-images.githubusercontent.com/6609929/108957627-7c64ca80-767a-11eb-9a25-3f24391c35a4.gif)

### Reproduction Link

https://github.com/maxkoshevoi/NureTimetable

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich Could you take a look at this please?

**Comment by AndreiMisiukevich** [comment]
@maxkoshevoi please verify #971

**Comment by maxkoshevoi** [comment]
> @maxkoshevoi please verify #971

Thank you! Issue is fixed via your PR

@jfversluis Any chance of 1.0.4 in the near future? 😄

**Comment by jfversluis** [comment]
> @jfversluis Any chance of 1.0.4 in the near future? 😄

I'm thinking 1.1 somewhere next week :)

**Comment by trumdongnat** [comment]
This issue still occur on the latest version v1.3.0.

**Comment by maxkoshevoi** [comment]
@trumdongnat While error message might be the same, root cause is likely different (I don't see the issue in my app, where it occurred previously).

Could you provide a repro project?

**Comment by trumdongnat** [comment]
@maxkoshevoi 
I found the issue on firebase crashlytic after using the xamarin community toolkit instead of TouchView.
Based on the report on firebase, the issue only happen on Android 5.
I will check my app and create a repo project.

**Comment by h1nson** [comment]
i face the same issue on Android 5. May be caused by TouchEffect
