### ISSUE TITLE
[Bug] DisplayToastAsync throws exception even if not awaited

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#972]
### Description
Currently displaying toast or snackbar throws `NullReference` sometimes  #959 
Issue is that exception is still thrown even if `DisplayXxx` is used as ["fire and forget"](https://www.meziantou.net/fire-and-forget-a-task-in-dotnet.htm)

`MyPage.DisplayToastAsync("Some string").Forget();`

This is happening because we never actually use `await` inside `DisplayXxx` so state machine is not created.

### Steps to Reproduce

1. Make `DisplayToastAsync` throw some exception
2. Copy `Forget` method from the article above
3. Execute this `MyPage.DisplayToastAsync("Some string").Forget();`

### Expected Behavior
Exception is not thrown (handled by `Forget` method)

### Actual Behavior
Exception is thrown

### Basic Information

- Version with issue: 1.0.3
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Add try-catch around `DisplayXxx` even when not awaiting it.

### Reproduction Link

Click "Show Toast" on SnackBar/Toast view here: https://github.com/maxkoshevoi/XamarinCommunityToolkit/tree/972-demo

**Comment by maxkoshevoi** [comment]
As I understand best practices right now, async methods should throw immediate exceptions only for parameter validation. Exceptions from actual logic on such methods shouldn't be visible until method is awaited (or result of the task is checked in some other way).

**Comment by pictos** [comment]
@maxkoshevoi can you provide a small repro?

**Comment by maxkoshevoi** [comment]
@pictos Sure. Click "Show Toast" on SnackBar/Toast view here: https://github.com/maxkoshevoi/XamarinCommunityToolkit/tree/972-demo

**Comment by brminnick** [comment]
> This is happening because we never actually use await inside DisplayXxx so state machine is not created

This is not accurate

**Comment by brminnick** [comment]
Closing this because the current behavior and implementation is correct.

`DisplayToastAsync` _should_ throw an `ArgumentNullException` regardless of whether or not it is `await`ed.

**Comment by maxkoshevoi** [comment]
@brminnick I'm not talking about `ArgumentNullException`. Because of a bug in the Shell those methods can throw `NullReferenceException` when all arguments are valid (#959)

**Comment by brminnick** [comment]
> Because of a bug in the Shell those methods can throw NullReferenceException when all arguments are valid

The solution is the same: use a try/catch block.

```csharp
try
{
    MyPage.DisplayToastAsync("Some string").Forget();
}
catch(ArgumentNullException e)
{
    /// Handle exception
}
catch(NullReferenceException e)
{
   // Handle exception
}
```

As Pedro pointed out, [this is a bug in Xamarin.Forms.Shell](https://github.com/xamarin/XamarinCommunityToolkit/issues/959#issuecomment-785513008), not in Xamarin.CommunityToolkit. I recommend fixing the bug where it exists, in the Xamarin.Forms repository.

**Comment by maxkoshevoi** [comment]
> The solution is the same: use a try/catch block

But this method returns `Task` methods that return task shouldn't throw exceptions (maybe except argument validation once) until result is awaited.
