### ISSUE TITLE
[Bug] TouchEffect causes View's stuck if PressedAnimationDuration is set, but NormalAnimationDuration isn't

### ISSUE THREAD

**Issue by gaurakshay** [xamarin/XamarinCommunityToolkit#974]
Hi!

I am trying to understand the difference between `TouchEffect.AnimationDuration` and `TouchEffect.PressedAnimationDuration`.

The markup below works fine:
```xaml
<Frame CornerRadius="30"
       Padding="30, 5"
       HorizontalOptions="CenterAndExpand"
       VerticalOptions="CenterAndExpand"
       xct:TouchEffect.PressedScale="0.9"
       xct:TouchEffect.AnimationDuration="100"
       xct:TouchEffect.AnimationEasing="CubicInOut"
       HasShadow="False"
       BackgroundColor="#0178D4"
       >
    <Grid ColumnDefinitions="Auto, Auto">
        <Label Text="AnimationDuration" FontSize="28" TextColor="White" Padding="0, 10"/>
        <Label Grid.Column="1" Text="&#xf054;" FontFamily="FASolid" FontSize="28" Margin="0,5,0,0" Padding="20,10,0,0" TextColor="White"/>
    </Grid>
</Frame>
```

However, the markup below causes the animation to be "stuck"
```xaml
<Frame CornerRadius="30"
       Padding="30, 5"
       HorizontalOptions="CenterAndExpand"
       VerticalOptions="CenterAndExpand"
       xct:TouchEffect.PressedScale="0.9"
       xct:TouchEffect.PressedAnimationDuration="100"
       xct:TouchEffect.AnimationEasing="CubicInOut"
       HasShadow="False"
       BackgroundColor="#0178D4"
       >
    <Grid ColumnDefinitions="Auto, Auto">
        <Label Text="AnimationDuration" FontSize="28" TextColor="White" Padding="0, 10"/>
        <Label Grid.Column="1" Text="&#xf054;" FontFamily="FASolid" FontSize="28" Margin="0,5,0,0" Padding="20,10,0,0" TextColor="White"/>
    </Grid>
</Frame>
```

https://user-images.githubusercontent.com/17280428/109081675-42bab080-76c8-11eb-9a41-c80c56b91acc.mp4

Please see the attached screen capture where the button looks like it is stuck when pressed.

I feel like this is more of a misunderstanding on my part rather than a bug which is why I didn't report this as a bug.

**Comment by gaurakshay** [comment]
Forgot to mention setup details:
Xamarin Forms : 5.0.0.2012
Community Toolkit version : 1.0.3
Android OS : 8.0

**Comment by AndreiMisiukevich** [comment]
AnimationDuration is applied to both Pressed and Normal state at the same time (if you want the same animation duriation for pressing and releasing transitions)

PressedAnimationDuration is applied only to pressing
NormalAnimationDuration is applied only to releasing

(if you want to have different animation durations)

**Comment by gaurakshay** [comment]
@AndreiMisiukevich Thanks I understand a little better now. Why does the `Frame` (on which the `TouchEffect` is applied) look like it is stuck? Shouldn't it return to its normal state?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich Thanks I understand a little better now. Why does the `Frame` (on which the `TouchEffect` is applied) look like it is stuck? Shouldn't it return to its normal state?

That's a bug)

**Comment by gaurakshay** [comment]
@AndreiMisiukevich what I have noticed is that if I keep the element pressed until the pressed animation is over, the element returns back to its normal state. If I press and let go before the animation is over, it stays stuck.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich what I have noticed is that if I keep the element pressed until the pressed animation is over, the element returns back to its normal state. If I press and let go before the animation is over, it stays stuck.

Yep) It's fixed. You may verify my PR

**Comment by gaurakshay** [comment]
> Yep) It's fixed. You may verify my PR

Sorry, I want to try the fix but I am getting error building the project on my system (I have never built XamarinCommunityToolkit before so my system configuration might be incorrect)
![image](https://user-images.githubusercontent.com/17280428/109094322-5faeae00-76df-11eb-8dba-b6f3b0f8e8f1.png)

**Comment by pictos** [comment]
@gaurakshay probably you're missing some UWP SDK to be able to run our project. Instead of that, you can try [this NuGet](https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/35800/artifacts?artifactName=nuget&api-version=6.0&%24format=zip), which has the bits of Andrei's PR.

**Comment by maxkoshevoi** [comment]
@gaurakshay Remove all the targets that you don't need. If you only want to test fix on android, do this:

![image](https://user-images.githubusercontent.com/6609929/109141164-18b7cb80-7766-11eb-8e55-d54c9dc8cb69.png)

**Comment by gaurakshay** [comment]
> @gaurakshay probably you're missing some UWP SDK to be able to run our project. Instead of that, you can try [this NuGet](https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/35800/artifacts?artifactName=nuget&api-version=6.0&%24format=zip), which has the bits of Andrei's PR.

@pictos Thanks!! I tested the NuGet and the fix works like a charm at my end!

> @gaurakshay Remove all the targets that you don't need. If you only want to test fix on android, do this:
> 
> ![image](https://user-images.githubusercontent.com/6609929/109141249-35ec9a00-7766-11eb-8b97-9f4afd18b3ee.png)

@maxkoshevoi Thanks for the the tip! This didn't work for me unfortunately as VS was not able to resolve TouchEffect for some reason. I am not going to work on fixing my setup for the time being but appreciate the suggestion :)
