### ISSUE TITLE
[Enhancement] ViewBox control

### ISSUE THREAD

**Issue by mgierlasinski** [xamarin/XamarinCommunityToolkit#978]
## Summary

`ViewBox` control similar to WPF/UWP. It always provides desired size for wrapped content and applies scaling according to available space.

[Spec for UWP](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.viewbox?view=winrt-19041)

## API Changes

``` C#
public class ViewBox : ContentView
{
    public Aspect Stretch { get; set; }  // Same enum as in Image
    public StretchDirection StretchDirection { get; set; }
}

public enum StretchDirection
{
    // The content scales upward only when it is smaller than the parent. 
    // If the content is larger, no scaling downward is performed.
    UpOnly = 0,

    // The content scales downward only when it is larger than the parent. 
    // If the content is smaller, no scaling upward is performed.
    DownOnly = 1,

    // Always stretches to fit the Viewbox according to the stretch mode.
    Both = 2
} 

```

Implemented in Xamarin.Forms, no custom renderers.

## Intended Use Case
For complex UI sometimes we need to provide fixed Width and Height but it doesn't play well with responsive design. With `ViewBox` we can wrap such fixed content and it handles proper scaling based on parent Layout.

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by pictos** [comment]
@mgierlasinski thanks for your proposal. I have a question, how this one can be different from the current `BoxView` control?

**Comment by mgierlasinski** [comment]
`BoxView` is for drawing colored box with optional corner radius, that's it. `ViewBox` wraps some content giving any space it needs, then it applies scale to fit available bounds. It behaves like `Aspect` in `Image` but for piece of child XAML. Name of control is taken from WPF/UWP but it may be confusing when we already have `BoxView` which is something totally different.

Let say you need a `Grid` with constant size of 500,500 but container has only 250,250 available size. Without `ViewBox`, half of this `Grid` will be clipped, when you put this inside 'ViewBox', `Grid` will get it's 500,500 but will have Scale 0.5,0.5.

You can find examples of ViewBox for WPF/UWP:
https://www.youtube.com/watch?v=7LgtNW3HJCU&t=178s

**Comment by pictos** [comment]
> Let say you need a Grid with constant size of 500,500 but container has only 250,250 available size. Without ViewBox, half of this Grid will be clipped, when you put this inside 'ViewBox', Grid will get it's 500,500 but will have Scale 0.5,0.5.

You can create empty rows/columns to archive that

**Comment by mgierlasinski** [comment]
@pictos OK forget about the `Grid`, more general example - you have some XAML content that is bigger than `Page`. You can put this into `ScrollView`. You could also use `ViewBox` instead that will scale down your content which sometimes may be useful. 

`ViewBox` and it's Content can be compared to `Image` and Bitmap source. If you want to stretch bitmap inside `Image` to fit it's bounds, you use `Aspect`. With `ViewBox` you do the same but with XAML content (see `Stretch` and `StretchDirection` properties.

As mentioned, `ViewBox` is present in WPF/Windows Phone/UWP. I found it useful especially for fixed size content that could be stretched with scale transform, no calculation in code behind was required for that.

**Comment by pictos** [comment]
@mgierlasinski I see now. Thanks for explaining it to me. Could you provide a spec for this API? And this will be a xaml control or do you need to use the platform-specific APIs?

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
