### ISSUE TITLE
[Bug] 1.1.0-pre1 LocalizedString gets unsubscribed while still in use

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#986]
### Description

`LocalizationResourceManager` inherits `ObservableObject` that uses `DelegateWeakEventManager`
`LocalizedString` WeekSubscribe. Turns out week events don't mix together with with week subscriptions  😄

### Steps to Reproduce

See new test in PR

### Expected Behavior
`LocalizedString` is always subscribed while in use

### Actual Behavior
`LocalizedString` gets unsubscribed

### Basic Information

- Version with issue: 1.1.0-pre1
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Implement your own `LocalizedString` without week subscription

**Comment by pictos** [comment]
@maxkoshevoi could you provide a repro? I want to see this deeper, to make sure that the root cause of this issue isn't in another place.

**Comment by maxkoshevoi** [comment]
@pictos The problem is that `WeakEventManager` works by unsubscribing dead subscribers. And if subscriber is subscribed using `WeekSubscribe`, nothing will reference it (it's the whole point of `WeekSubscribe`), so `WeakEventManager` will unsubscribe it.

It has nothing to do with `LocalizationResourceManager` being disposed. It won't be since `Current` property always references it.

Flow of the execution:
- Subscriber subscribes using `WeekSubscribe` => Nothing references that object that subscribed to the event except even itself
- `WeakEventManager` stores subscribtion as `WeekReference`
- GC is invoked, and since nothing references subscribtion (it's stores as `WeekReference`), it is removed from the heap
- Event is triggered.  `WeakEventManager` sees that subscribtion is now `null` and unsubscribes it

For reproduction you can just copy the test provided in PR into current develop branch and debug it. It there some issues with this method of preproducing the issies?

**Comment by maxkoshevoi** [comment]
@pictos Are you able to reproduce the issue?

**Comment by pictos** [comment]
@maxkoshevoi I didn't look yet, I'll look ASAP, try to solve this until tomorrow (:
