### ISSUE TITLE
[Bug] ShadowEffect on button adds shadow to text on the button

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#988]
### Description

1. ShadowEffect on button adds shadow to text on the button instead of button itself
`<Button Text="Hi" xct:ShadowEffect.Color="Black" />`
![image](https://user-images.githubusercontent.com/6609929/109230990-74b63a80-77ce-11eb-8987-3f0875aab0b3.png)

2. ShadowEffect.Offset on button changes size of the button
`<Button Text="Hi" xct:ShadowEffect.Color="Black" xct:ShadowEffect.OffsetX="50" />`
![image](https://user-images.githubusercontent.com/6609929/109231098-9b747100-77ce-11eb-9867-3f42dbf3d593.png)

### Steps to Reproduce

Add shadow effect to any button

### Expected Behavior
Effect is applied to the button

### Actual Behavior
Effect is applied to the text on the button and button size is changed

### Basic Information

- Version with issue: 1.1.0
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Effect can be applied to the parent container of the button, but corners will not look good
![image](https://user-images.githubusercontent.com/6609929/109231344-15a4f580-77cf-11eb-90b2-ebe46b401854.png)

**Comment by maxkoshevoi** [comment]
CC: @AndreiMisiukevich

**Comment by themronion** [comment]
Yeap, can confirm this one

**Comment by AndreiMisiukevich** [comment]
Feel free to grab this issue and submit a PR :)

**Comment by themronion** [comment]
Nah, too lazy) gonna stay on Sharpnado.Shadows for now)

**Comment by maxkoshevoi** [comment]
Looks like it's not that easy to add shadow to a button: https://stackoverflow.com/questions/62966078/to-drop-color-shadow-to-a-button-in-xamarin

**Comment by themronion** [comment]
@maxkoshevoi the most optimal solution for shadows in Xamarin.Forms is @roubachof's Sharpnado.Shadows, so i think we can kindly ask him and blend in his hard work here. But he has an absolutely different approach there. Or we can wait untill Maui...

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich Looks like it's still broken for rounded buttons:
![image](https://user-images.githubusercontent.com/6609929/118355732-4862bc80-b57a-11eb-9b19-88ad0eed95bb.png)

It looks the same as workaround in this bug (appling shadow to the container of the button)

**Comment by AndreiMisiukevich** [comment]
@maxkoshevoi yes, it's not the ideal solution, but it works better now, right?)
Feel free to throw a PR for a rounded button
Also, feel free to open a new issue for rounded button as well (since this issue is about adding shadow to text rather than to entire button)

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich Better, but still not as expected.. Created a new bug to track this: #1298
