### ISSUE TITLE
[Enhancement] Popup to autosize based on the content

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#990]
## Summary

Right now when I open a popup that contain one label, it looks like this:
![image](https://user-images.githubusercontent.com/6609929/109234532-8dc1ea00-77d4-11eb-9ef9-6e0ceeb82200.png)

I don't need it that high. Please provide an option to autozise it based on the content.

## API Changes

`bool Autozise`

## Intended Use Case
User don't need to calculate the size manually

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by acaliaro** [comment]
#937
