### ISSUE TITLE
[Enhancement] Navigation extension method to DIsmiss popup

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#991]
## Summary

Provide some way to `Dismiss` from within ViewModel (for example another `Navigation` extension). Right now I need to pass the whole page into view model to be able to dismiss it

## API Changes

`Dismiss(this Navigation)`

## Intended Use Case
To be able to easier use Popup in MVVM

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
