### ISSUE TITLE
[Bug] [Android] IconTintColorEffect may crash due to ImgeButtonRenderer disposed exception

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#994]
### Description
When using IconTintColorEffect with an `ImageButton`  inside of a `ControlTemplate` I was able to reproduce under Shell only.
If used with `Image` or `Button` it works fine. Not sure if the root cause is a bug in XF but it seems so.

### Steps to Reproduce
1. Run the repo.
2. Navigate to the second bottom tab and return to the first one.

### Expected Behavior
No Crash.

### Actual Behavior
App crash with 
> **System.ObjectDisposedException:** 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.ImageButtonRenderer'.'

For Android, exactly at line https://github.com/xamarin/XamarinCommunityToolkit/blob/01bfcdf98b3c5a34bbad224e4da321f8bc842f4d/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/IconTintColor/IconTintColorEffectRouter.android.cs#L56

### Basic Information

- Version with issue: V1.1.0-pre1
- Last known good version:-
- IDE:-
- Platform Target Frameworks: Tested on Android only
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[App1.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6050333/App1.zip)

**Comment by Cfun1** [comment]
Even if it is a XF issue we may avoid the crash, as discussed with @pictos earlier we may avoid the crash, either by testing the private property IsDisposed using reflection or by catching and ignoring the exception: 

https://github.com/Cfun1/XamarinCommunityToolkit/blob/68d899bec0aea90f0b386d4ae0f4346d104c6f96/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/IconTintColor/IconTintColorEffectRouter.android.cs#L54-L77

**Comment by pictos** [comment]
@Cfun1 will you implement this fix?

**Comment by Cfun1** [comment]
@pictos if you guys verify this bug and validate the fix then yes of course , remains two questions:
1- What is the situation in iOS could someone test it?
2- Which approach to go with, reflection or catch ignore exception ?

**Comment by pictos** [comment]
tbh I didn't look at the sample yet, doing some code review right now, but if I confirm the bug I would say that solution will be to use the catch and ignore that exception, just show it in the debug.WriteLine. But let me check if first, I'll ping you right after I look it

**Comment by pictos** [comment]
@Cfun1 we can add the catch and ignore the exception or we can verify if the `Element` is null. If the `Element` there's no more a `View` attached to that `Control` so we can infer that object is disposed of. Here I prefer to check for `Element == null` because exceptions are expensive. Thoughts?

**Comment by pictos** [comment]
OnAttached:
![image](https://user-images.githubusercontent.com/20712372/109402665-4fdcd700-7936-11eb-886b-f811ea5fb5d9.png)

OnDetached:

![image](https://user-images.githubusercontent.com/20712372/109402653-3d629d80-7936-11eb-9819-1bb7fbd01c7a.png)

**Comment by Cfun1** [comment]
@pictos when I checked earlier `Element` (of type ImageButton) is not null in this specific case, if you meant Control.Element (Unknown member) not sure how we access to it, if we try a cast `(ImageButtonRenderer) Control`, again we are going to hit the exception.

**Comment by pictos** [comment]
@Cfun1 I see now, we can't access those properties easily from code, because the Effect just call the `TControl Control`  as class. Yeah, let's keep the plan of just discard the exception.

**Comment by pictos** [comment]
FYI, I update your repro on my sandbox project, you can find it [here](https://github.com/pictos/XCT.SandBox/tree/icontint-disposed-exception)
