### ISSUE TITLE
[Bug] TouchEffect is no longer firing on UWP

### ISSUE THREAD

**Issue by ryanharding** [xamarin/XamarinCommunityToolkit#998]
### Description

In pre release 1.1.0 pre1, TouchEffect is no longer firing on UWP in ListView ViewCell's.

No error or warning is fired when tapping.

### Steps to Reproduce

1.  Create ListView and ListView ItemTemplate
2.  Add Grid to ItemTemplate with xct:TouchEffect.Command
3.  Run and tap item with debug on Command

### Expected Behavior

Expected to hit debug point on command

### Actual Behavior

Nothing is fired or hit. No errors or warnings

### Basic Information

- Version with issue: 1.1.0 pre1
- Last known good version: v1.0.0-preview2782
- IDE: VS 2019 Community
- Platform Target Frameworks: 
  - UWP:  18362 
- Nuget Packages: Community Toolkit - Xamarin Forms 5.0.0.1931
- Affected Devices: Windows

**Comment by inforithmics** [comment]
I think the reason that it doesn't work is that Xamarin Community Toolkit was retarget to use at least UWP Version 10.0.19041
when you look at the nuget package version you see (UAP 10.0.19041 / 2004)

https://www.nuget.org/packages/Xamarin.CommunityToolkit/1.1.0-pre1

Here is a pull request where I try to fix that.

https://github.com/xamarin/XamarinCommunityToolkit/pull/942

Here is some discussion about this concering the Popup (Where the same problem occurs, Only the shared implementation is used instead of the UWP Implementation)

**Comment by GuidoNeele** [comment]
Built app using min target UAP 10.0.19041 / 2004 and it somewhat (not always) works in Debug mode but it doesn't work in release mode.

Created a sample project which demonstrates the problem https://github.com/GuidoNeele/XctTouchEffectBug

**Comment by GuidoNeele** [comment]
With "Compile with .NET Native toolchain" disabled it works.
![image](https://user-images.githubusercontent.com/1301586/115882443-0a77ea00-a44d-11eb-8848-190c9a75e88b.png)

**Comment by bmacombe** [comment]
@GuidoNeele That likely could be a linking issue.

I need to do something like this to most third-party dlls in my UWP project that it doesn't reference directly in the app.cs

var assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(Microsoft.IO.RecyclableMemoryStream).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);

Keeps them from being linked away

**Comment by GuidoNeele** [comment]
Thanks @bmacombe! Why didn't I think of that. Added the following code to the sample and it worked.

```csharp
var assembliesToInclude = new List<Assembly>()
{
    typeof(Xamarin.CommunityToolkit.Effects.TouchEffect).GetTypeInfo().Assembly
};

Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

**Comment by bmacombe** [comment]
@GuidoNeele Your welcome!  Glad it helped you.  I banged my head on that same issue a few years ago too!
